### ISSUE TITLE
sharing code with brackets-typescript

### ISSUE THREAD

**Issue by fdecampredon** [TypeStrong/atom-typescript#1]
I'm planning to resume my works on brackets-typescript soon, and I thought about this.
Basically brackets-typescript is composed of 2 parts : 
- a web worker that manage all the 'project-like' logic, and expose services for error auto-completion, etc etc
- a front script that manage all the integration with brackets and feed the web-worker with info about filesystem, working-set, editing etc etc.

Perhaps I could externalize the web-worker part and it could be used by this extension, I think that would  benefits to both extension since more than 50% of the hard work is in the web-worker, so user of this extension and the brackets one could contribute to the same codebase.

**Comment by fdecampredon** [comment]
Ok it has been some times but I finally did it, https://github.com/fdecampredon/typescript-project-services, is a externalized version of brackets-typescript internal, I'm still actively working on it, but the master of brackets-typescript is already based on that and works well.
The project still needs : 
* Documentation
* Expose all language service feature
* more test
* generation of a declaration file
* better build system
* integration with tsconfig

If you think that this project is interesting for atom-typescript, or anyone wanting an high-level abstraction on top of ls, I'm ready to give the ownership to typestrong (if you want to). Anyway I'll continue to work on it.

**Comment by basarat** [comment]
> I'm ready to give the ownership to typestrong (if you want to)

It would be an honour to review your code. As a token of appreciation you are now an owner of the TypeStrong org. 

PS: I'll kill this: https://github.com/typestrong/tscs

**Comment by fdecampredon** [comment]
It will be an honour for me yo have a project I contibued to in typestrong ^^
