### ISSUE TITLE
Uncaught TypeError: Cannot read property 'null' of undefined

### ISSUE THREAD

**Issue by dinoDachi** [TypeStrong/atom-typescript#1000]
[Enter steps to reproduce below:]
1. Open typescript file (I used atom . in terminal to open the project folder)

errors keep getting generated even when close all

**Atom Version**: 1.8.0
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v9.0.0
### Stack Trace

Uncaught TypeError: Cannot read property 'null' of undefined

```
At /Users/Dave/.atom/packages/atom-typescript/node_modules/react/lib/ReactMount.js:636

TypeError: Cannot read property 'null' of undefined
    at Object.ReactMount.findReactContainerForID (/Users/Dave/.atom/packages/atom-typescript/node_modules/react/lib/ReactMount.js:636:50)
    at findParent (/Users/Dave/.atom/packages/atom-typescript/node_modules/react/lib/ReactEventListener.js:39:30)
    at handleTopLevelImpl (/Users/Dave/.atom/packages/atom-typescript/node_modules/react/lib/ReactEventListener.js:74:16)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/Dave/.atom/packages/atom-typescript/node_modules/react/lib/Transaction.js:134:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/Dave/.atom/packages/atom-typescript/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
    at Object.batchedUpdates (/Users/Dave/.atom/packages/atom-typescript/node_modules/react/lib/ReactUpdates.js:110:20)
    at ReactEventListener.dispatchEvent (/Users/Dave/.atom/packages/atom-typescript/node_modules/react/lib/ReactEventListener.js:174:20)
```
### Commands

```
     -1:50.8.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:46.7.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  5x -1:44.6.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:43.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -1:40 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:38.6.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:36.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:36.3.0 linter:lint (atom-text-editor.editor.is-focused)
  2x -0:19.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:18.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:18 linter:lint (atom-text-editor.editor.is-focused)
  2x -0:03.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.7.0 linter:lint (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "allowPendingPaneItems": false,
    "closeEmptyWindows": false,
    "disabledPackages": [
      "auto-update-packages",
      "symbols-view",
      "SFTP-deployment",
      "linter-scss-lint",
      "omnisharp-atom"
    ],
    "themes": [
      "one-dark-ui",
      "dracula-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.9
atom-jshint, v2.0.0
atom-ternjs, v0.14.2
atom-typescript, v9.0.0
compare-files, v0.6.2
dracula-theme, v1.2.8
file-icons, v1.7.16
json-schema, v0.1.15
linter, v1.11.14
linter-csslint, v1.3.2
linter-htmlhint, v1.2.1
linter-jshint, v2.1.0
linter-less, v2.5.0
linter-xmllint, v1.3.5
minimap, v4.24.7
remote-sync, v4.1.2
tabs-to-spaces, v1.0.2
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by RyanCCollins** [comment]
I am getting this same issue.  Would love to hear if there is a fix, but will be disabling typescript in atom for the time being.  Thanks in advance!

**Comment by leighghunt** [comment]
Strange - I thought typescript was all working fine on my machine apart from this issue, and updated it a few days ago to 10.1.5 (was 8.11.0) to see if that would resolve this issue, but no change.

Then read @RyanCCollins's note above and tried to uninstall, and got the same ``Failed to delete atom-typescript: Does not exist`` issue (see attached). 

<img width="775" alt="screen shot 2016-07-29 at 2 56 28 pm" src="https://cloud.githubusercontent.com/assets/349153/17236484/67949ca0-559d-11e6-8937-0e013bf0c761.png">

Re-installed with apm and I will see if that's resolved the ``Cannot read property 'null' of undefined`` issue (but it's intermittent, so may take a week or so before I'm sure).

**Comment by milk-shake** [comment]
I've since uninstalled (via rm -rf... but w/e) and reinstalled via apm at version 10.1.7 and haven't had an issue since. 

It looked as though ownership was messed up on a few packages (typescript included) as atom couldn't update through the interface. Probably an ill-advised sudo apm install on my part some point in the past. Not sure if it contributed to the issue reported, but since updating it's all been rosy.
