### ISSUE TITLE
Support syntax highlighting for JSDoc / Typedoc

### ISSUE THREAD

**Issue by ddaws** [TypeStrong/atom-typescript#1004]
I would like to document my Typescript code using JSDoc / Typedoc and would appreciate support for syntax highlighting JSDoc comments. I have forked this repo and would like to contribute though would like to understand if anyone is already working on this.

**EDIT :** I am also having trouble building the package via `apm rebuild` because `fs-events` is failing to compile native extensions due to the outdated version of node used by apm. Any advise on this issue would also be appreciated. I have created a [thread here](https://discuss.atom.io/t/upgrading-to-apm-1-11-4-and-encountering-libgit-errors/30901)

**Comment by guncha** [comment]
Basic keyword highlighting was released with `v10.1.10` 🎉 

If you need something fancier, check out https://atom.io/packages/docblockr
