### ISSUE TITLE
Failed to load the atom-typescript package settings

### ISSUE THREAD

**Issue by MarkPieszak** [TypeStrong/atom-typescript#1007]
When updating to the latest version I'm now seeing:

> Failed to load the atom-typescript package settings
> EPERM: operation not permitted, open 'C:\Users\mark.pieszak.atom\packages\atom-typescript\settings\language-tsx.cson' in C:\Users\mark.pieszak.atom\packages\atom-typescript\settings\language-tsx.cson

I believe it might of failed updating, never had any issues in the past.

OS     : Win7
Atom : 1.8

![image](https://cloud.githubusercontent.com/assets/2574412/16819998/e9842722-491c-11e6-9326-811b67e116d8.png)

**Comment by ashish1269** [comment]
I also have this error. How do I download previous version?

**Comment by CristyTarantino** [comment]
+1

**Comment by jcgertig** [comment]
+1

**Comment by Winster332** [comment]
+1

**Comment by FionaWong** [comment]
+1

**Comment by RefactorMan** [comment]
+1

**Comment by toddrothe** [comment]
+1
OS : mac 10.11.5
Atom : 1.8.0

**Comment by juliosogiteck** [comment]
+1
OS:Win7
Atom: 1.9.8

**Comment by gregflynn** [comment]
Happened on launch on OSX 10.11.5
Has been fine on Xubuntu 16.04.1 with synced `~/.atom` via Dropbox

**Comment by dyshi** [comment]
+1
OS: Mac 10.11.6
Atom: 1.9.4

**Comment by valepu** [comment]
+1
