### ISSUE TITLE
tsconfig.json Unknown Option: lib, Unknown Option: type

### ISSUE THREAD

**Issue by oers** [TypeStrong/atom-typescript#1009]
Since the newest version (10.1.2) my tsconfig.json cannot be parsed anymore.

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "noEmitHelpers": true,
    "lib": ["es6", "dom"],
    "strictNullChecks": false,
    "baseUrl": "./src",
    "paths": [
    ],
    "types": [
      "core-js",
      "hammerjs",
      "jasmine",
      "node",
      "protractor",
      "selenium-webdriver",
      "source-map",
      "uglify-js",
      "webpack"
    ]
  },
  "exclude": [
    "node_modules"
  ],
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": { "rewriteTsconfig": false }
}
```

I will only get:

```
Unknown Option: lib
Unknown Option: types
```

Removing the options from the file will result in strange erros in my angular2   Typescript files.

Project was created using Angular Class:
https://github.com/AngularClass/angular2-webpack-starter/

**Comment by oers** [comment]
I have to clarify some things :)
This error did not start with 10.1.2. I just didn't notice that a colleague changed this file and I just pulled it.

This config is the newest version from the angular class github, the version prior to that works without problems.

**Comment by Martin-Wegner** [comment]
Please have a look: https://github.com/AngularClass/angular2-webpack-starter/issues/781#issuecomment-232788165

**Comment by oers** [comment]
Issue seems to be related to TypeScript 2.0.
Setting the fullPath to the typesciptServices.js did not help.

**Comment by t246246** [comment]
Also "Unknown option: typeRoots".

http://json.schemastore.org/tsconfig

**Comment by hxlniada** [comment]
+1 help!!!!!!!!

**Comment by radarsu** [comment]
Same here. Couldn't find the solution anywhere.

**Comment by abdulhaq-e** [comment]
It seems to be caused by the new options introduced in TypeScript 2.0
