### ISSUE TITLE
JS Outdated / TS Emit failed

### ISSUE THREAD

**Issue by eskirk** [TypeStrong/atom-typescript#1013]
Every time I save a `.ts` file (even if there are no errors) atom will give me a little red pop-up flag indicating `TS Emit failed`. This is just one of the mildly infuriating things that I could totally live with, but would really love to disable. Any tips?

Thanks!

I'm on OSX 10.11.4 if that matters ¯\_(ツ)_/¯

pix or it didn't happen
<img width="792" alt="screen shot 2016-07-15 at 5 01 56 pm" src="https://cloud.githubusercontent.com/assets/7052378/16889706/ec9f7ef6-4aad-11e6-8420-83e3160148b5.png">

**Comment by eskirk** [comment]
I found a work around where I add 
```
atom-notification.error {
  display: none;
}
```
to the Stylesheet, but I don't like to have to do that :/

**Comment by xealot** [comment]
Since moving to Typescript 2.0 I've been seeing this as well. It still seems to update the file. If anyone wants to chime in with how to figure out what it's failing on I would be happy to debug.

**Comment by aderbas** [comment]
Same problem here. And disable "compileOnSave" is not a valid option for me. =/

**Comment by Olmer1st** [comment]
Hi, same issue on Ubuntu 16.04
Latest Atom, Typescript and Node.
![image](https://cloud.githubusercontent.com/assets/14262067/19418553/ed0ae730-93ce-11e6-9a2f-b7e18857362e.png)

**Comment by eonlepapillon** [comment]
I have got the same issue. My` tsconfig.json` looks like
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": false,
        "outDir": "./dist",
        "noEmitOnError": true
    },
    "files":[
      "src/main.ts"
    ]
}
```

When I remove the option `noEmitOnError`, everything works fine.

**Comment by nistath** [comment]
Same issue, happens on save.
```json
{
  "compilerOptions": {
      "target": "es6",
      "module": "commonjs",
      "moduleResolution": "node",
      "isolatedModules": false,
      "jsx": "react",
      "experimentalDecorators": true,
      "emitDecoratorMetadata": true,
      "declaration": false,
      "noImplicitAny": false,
      "noImplicitUseStrict": false,
      "removeComments": true,
      "noLib": false,
      "preserveConstEnums": true,
      "suppressImplicitAnyIndexErrors": true,
	  "declaration": true,
	  "rootDir": "./src",
	  "outDir": "./lib",
	  "declarationDir": "./lib"
  },
  "exclude": [
    "node_modules",
    "typings/browser",
    "typings/browser.d.ts"
  ],
  "compileOnSave": true,
  "buildOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```
Error is the exact same as anyone else.

I must add that the TypeScript compiler **works normally with the `tsc` command**.

**Comment by drernie** [comment]
+1

**Comment by davideicardi** [comment]
I have the same problem, but only when using `declaration: true` in `tscconfig.json`. 
And not always...sometime when I first open the project everything seems to work fine, then I do some changes (modify tscconfig.json, open generated file, ...) and bang! JS Outdated and TS emit error...
As already reported `tsc` compilation works just fine.

Here my project where you can reproduce the issue (I hope )  :
https://github.com/davideicardi/progress-logger-js/tree/5eafe4d76aa5177360ac7e75a83360c484618b3e

**Comment by josemera** [comment]
having the same problem.  Can bypass issue by setting "noEmitOnError": false but would rather not.  Saving files seems to make Atom think there was an error (when there actually was not) and thus .ts file is not emitted.  Can compile on command line with tsc just fine.

**Comment by davideicardi** [comment]
Maybe I have found a solution, at least for my use case.
Basically I have the following `tsconfig`:

```
{
    "compilerOptions": {
        ....
        "declaration": true,
        "outDir": "build"
    },
    "exclude": [
        "node_modules"
    ],
    "compileOnSave": true
}
```

Note that I have an `outDir` set to `build` but I have not added the `build` directory to the excluded array. So probably `atom-typescript` try to build also `*.d.ts` files in the `build` directory.
Adding `build` in the exclude array solve my problems and I don't see any error (no JS Outdated / TS Emit failed).

```
{
    "compilerOptions": {
        ....
        "declaration": true,
        "outDir": "build"
    },
    "exclude": [
        "build",
        "node_modules"
    ],
    "compileOnSave": true
}
```

**Comment by jbree** [comment]
Same issue. But if I exclude the `node_modules` folder as suggested by @davideicardi above, then any types I have installed from npm, such as `npm install @types/node` are also ignored.

According to the [typescript handbook](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html):

> The `"exclude"` property defaults to excluding the `node_modules`, `bower_components`, `jspm_packages` and `<outDir>` directories when not specified.

Is atom-typescript simply not respecting these defaults?
