### ISSUE TITLE
Option to lint only on save

### ISSUE THREAD

**Issue by jiayihu** [TypeStrong/atom-typescript#1029]
I'm still new in Typescript but I was wondering if it is possible to lint only on save to improve performance.
Also I don't need Typescript telling me that the current line has errors while I'm still thinking what to write 🤔

**Comment by djwhatley** [comment]
+1, this is super annoying and a huge waste of processing time; most IDE's wait a few seconds when you stop typing to re-compile, as that is the sane behavior, not queuing up 60 redundant jobs.

**Comment by handonam** [comment]
+1.  It's a huge burden for me as well.

**Comment by Jamesernator** [comment]
Yeah I dislike it telling me to do things I was already half-way through doing.

**Comment by samartioli** [comment]
Super Annoying [bump]

**Comment by trkoch** [comment]
With so many comments, this seems like a low hanging fruit but surely there must be a reason why it was not implemented yet?

**Comment by jiayihu** [comment]
I've moved to VSCode a while ago, where you still have the same issue but it's not really an issue. Errors are only underlined and the TS integration it's incredibly faster. 
Also integration with TS in VSCode is built-in in the editor, more rich and always aligned with the latest version of the compiler.

**Comment by trkoch** [comment]
My current workaround is to disable `atom-typescript` and instead use `language-typescript-grammars-only` in combination with `linter-tslint`.

**Comment by qwemaze** [comment]
The package even uses Linter which have the option to **not** lint on change and it's ignored for some reason

**Comment by rodmax** [comment]
Hi guys. First i want to say: Nice plugin!!! After migrating our project from es6 to ts i take a good experience with atom....
But this issue is really blocker for me especially:
> Also I don't need Typescript telling me that the current line has errors while I'm still thinking what to write

Can someone answer, what is the status of this issue, maybe do you need help?

**Comment by guncha** [comment]
There's no special reason why this isn't implemented except that people who really need it haven't done it. Now, there IS a reason why the plugin ignores the linter settings on when to lint and it's because it's using the linter in push mode instead of waiting for it to ask for the errors. Why is that I can't tell you from the top of my head.

There's also a timeout after the user has stopped typing before the plugin checks for errors as it's using Atom's `onDidStopChanging` event, but apparently it's too short for some people. Perhaps both of these could be addressed by letting the linter dictate when to lint, but they're also using `onDidStopChanging` so this is likely an `atom-core` issue.

**Comment by iwinux** [comment]
Current workaround is:

```cson
// config.cson
"*":
  linter:
    lintOnChangeInterval: 3000 // if I pause 3s without typing anything, lint it anyway
```

However a dedicated option to disable lint-on-type is still appreciated 😄

**Comment by trkoch** [comment]
Unfortunately this does not have any effect.

**Comment by iwinux** [comment]
Hmmm....I'm desperate enough to patch it with some dirty hack:

```diff
--- atom-typescript/dist/main/atomts.orig.js	2017-11-20 16:14:41.000000000 +0800
+++ atom-typescript/dist/main/atomts.js	2017-11-20 16:15:34.000000000 +0800
@@ -30,6 +30,8 @@
         .install("atom-typescript", true)
         .then(() => {
         let statusPriority = 100;
+        let isSaving = {};
+        let lastDiagnostics = {};
         for (const panel of statusBar.getRightTiles()) {
             if (panel.getItem().tagName === "GRAMMAR-SELECTOR-STATUS") {
                 statusPriority = panel.getPriority() - 1;
@@ -57,7 +59,14 @@
         if (linter) {
             errorPusher.setLinter(linter);
             exports.clientResolver.on("diagnostics", ({ type, filePath, diagnostics }) => {
-                errorPusher.setErrors(type, filePath, diagnostics);
+                if (isSaving[filePath] && lastDiagnostics[filePath]) {
+                  errorPusher.setErrors(type, filePath, lastDiagnostics[filePath]);
+                } else {
+                  console.debug('not linting:', filePath);
+                }
+
+                lastDiagnostics[filePath] = diagnostics;
+                isSaving[filePath] = false;
             });
         }
         // Register the commands
@@ -86,6 +95,7 @@
                 .sort((a, b) => a.activeAt - b.activeAt)
                 .filter(_pane => _pane.filePath && _pane.isTypescript && _pane.client === pane.client)
                 .map(pane => pane.filePath);
+            isSaving[pane.filePath] = true;
             pane.client.executeGetErr({ files, delay: 100 });
         }, 50);
         subscriptions.add(atom.workspace.observeTextEditors((editor) => {
```
