### ISSUE TITLE
Atom autocomplete does not work when atom-typescript is enabled

### ISSUE THREAD

**Issue by pejrich** [TypeStrong/atom-typescript#1032]
I have some snippets installed with angular-2-typescript-snippets. They work fine, with and without this package enabled, but when I enable it, the autocomplete no longer works.

Anyway to get both to work? I really just need snippets, autocomplete, and syntax. Not sure what part of this plugin is blocking the native Atom snippet autocomplete

EDIT: I went a little "scorched earth" to fix this. I deleted the entire `dist` directory, this fixed it. Still have syntax highlighting, and snippets and autocomplete work.

![screen shot 2016-07-26 at 2 18 30 am](https://cloud.githubusercontent.com/assets/5256951/17114310/873ebbe8-52d8-11e6-98e4-86d71ede76a1.png)
![screen shot 2016-07-26 at 2 23 56 am](https://cloud.githubusercontent.com/assets/5256951/17114311/873fc2c2-52d8-11e6-9a99-9b7c5aacc540.png)

**Comment by hiepxanh** [comment]
me too, the same problem ?!

**Comment by pquarme** [comment]
Same I'm having the same problem? Any fix or ideas on how to approach this?

**Comment by guncha** [comment]
Seems to work ok:

![image](https://cloud.githubusercontent.com/assets/679632/20073611/e0a99422-a4fa-11e6-870b-cf5fea88ab64.png)

I had to restart the editor after installing the snippets package for it to work:

![image](https://cloud.githubusercontent.com/assets/679632/20073792/a4a4103c-a4fb-11e6-9a2b-63f7be0bf2fe.png)

**Comment by pquarme** [comment]
It works, it's just slow when used in conjunction with atom-typescript. It works fast when I disable atom-typescript.

There is no error output in the dev console as-well and I haven't tried custom scripts.
