### ISSUE TITLE
Overly eager autocomplete after typing some characters

### ISSUE THREAD

**Issue by fishchisel** [TypeStrong/atom-typescript#1033]
Hi,

I've found that the atom-typescript autocomplete is a bit too eager to make suggestions when autocomplete-plus is set to 'Show Suggestions On Keystroke'. As you can see in that attached gif, after typing an opening brace for an 'if' statement the autocomplete pops up and suggests a random symbol to go next. When I press 'enter' to start a new line, instead the autocomplete suggestion is inserted. I have to backspace out the errant symbol. It is a little annoying as it breaks my flow.

![animation](https://cloud.githubusercontent.com/assets/20627857/17117500/26ae2e68-52b4-11e6-9ac2-da87e43f12c9.gif)

I would like to change atom-typescript's autocomplete provider to be a little more conservative about making suggestions when the autocomplete is not explicitly triggered. For instance, it should only make a suggestion if the proceeding fragment could be a variable name. [Or perhaps it would be safer](http://stackoverflow.com/questions/1661197/what-characters-are-valid-for-javascript-variable-names) to just exclude some more characters from autosuggestion!

I had a dig through the code and in the `autoCompleteProvider.ts` file I found this little fragment:

    // line 139
    // if explicitly triggered reset the explicit nature
    if (explicitlyTriggered) {
        explicitlyTriggered = false;
    }
    else { // else in special cases for automatic triggering refuse to provide completions
        const prefix = options.prefix.trim()

        if (prefix === '' || prefix === ';') {
            return Promise.resolve([]);
        }
    }

I would like to extend the exceptions there to include some more characters. Is this a good idea?

**Comment by banacorn** [comment]
+1, This is super annoying!! 😠

**Comment by fishchisel** [comment]
I wrote a tiny fix:

    if (prefix === '' || prefix === ';' || prefix === '{') {
        return Promise.resolve([]);
    }
