### ISSUE TITLE
Rendering issue when using closing tags

### ISSUE THREAD

**Issue by deyceg** [TypeStrong/atom-typescript#1042]
<img width="1622" alt="screen shot 2016-08-04 at 21 00 49" src="https://cloud.githubusercontent.com/assets/876466/17416579/a024f86a-5a86-11e6-8700-217f19138e67.png">

Not really sure how best to describe this! But its rendering (no pun intended) the plugin pretty useless for me :(

**Comment by Glavin001** [comment]
Also experiencing this issue. Removing the `close` class at https://github.com/TypeStrong/atom-typescript/blob/master/grammars/tsx.cson#L1216 would resolve this, I think.

**Comment by Glavin001** [comment]
I fixed this by enabling `Shadow DOM`: https://github.com/gandm/language-babel/issues/141
