### ISSUE TITLE
Ignore unknown tsconfig directives

### ISSUE THREAD

**Issue by spiffytech** [TypeStrong/atom-typescript#1047]
atom-typescript abandons checking a project if the tsconfig has a directive that atom-typescript doesn't support yet (e.g., some TypeScript 2.0 features).

It would be preferable for atom-typescript to continue working when it encounters an unknown directive, so users can use the latest TypeScript features without waiting for atom-typescript to support them.

**Comment by pcan** [comment]
Same issue here. I'm trying to add some features to a custom version of the compiler and they need a new option in the `compilerOptions` section to be enabled. I updated the `commandLineParser.ts` that comes with the compiler, that already does all the checks for `compilerOptions`. So why does Atom-Typescript itself implements the same check [here](https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/tsconfig/tsconfig.ts#L496)?
