### ISSUE TITLE
Syntax highlighting is not working for return types

### ISSUE THREAD

**Issue by 62316e** [TypeStrong/atom-typescript#1049]
As you can see depending on space the code looks totaly broken. Please fix asap.

':Matrix' and ': Matrix' <--

![image](https://cloud.githubusercontent.com/assets/564381/17591923/e7468044-5fe8-11e6-818e-507f535325a1.png)

![image](https://cloud.githubusercontent.com/assets/564381/17591926/eaa5eb3a-5fe8-11e6-8b32-d800d227f1f8.png)

**Comment by ddaws** [comment]
@62316e (if that's your real name) you should consider posting information on the version of the package, atom, and apm you are using, as well as your operating system info.

**Comment by 62316e** [comment]
apm  1.10.0
npm  2.13.3
node 6.2.2
atom-typescript 10.1.6

And yes, sixty-two thousand, three hundred sixteen-e is my real name.
