### ISSUE TITLE
tsconfig.json being created in directories/projects that aren’t for TypeScript

### ISSUE THREAD

**Issue by csnover** [TypeStrong/atom-typescript#105]
1. Create a directory and put a non-typescript file in the directory
2. Open the non-typescript file

Expected: No invocation of any atom-typescript code
Actual: atom-typescript creates a tsconfig.json file in the directory

**Comment by basarat** [comment]
Narrowed it down. Only happens if the file has no extension Or an extension that isn't handled by any grammar Or you explicitly set the grammar to "TypeScript". This is very disturbing. Sorry.

**Comment by basarat** [comment]
`v0.62.0`

**Comment by csnover** [comment]
> you explicitly set the grammar to "TypeScript" will still cause it but this is by design ;) 

Of course :) Thanks for looking into it!
