### ISSUE TITLE
setInterval - Type 'Timer' is not assignable to type 'number'

### ISSUE THREAD

**Issue by AskYous** [TypeStrong/atom-typescript#1053]
I am attempting to create an interval for a web app. But in the browser, `setInterval()` returns a number representing the ID of that interval. But instead, atom-typescript is saying it returns a `NodeJS.Timer` object. It seems it's the wrong overload method.

In short, the following works in the TypeScript playground, but doesn't work in atom-typescript:

```
let interval: number = setInterval(() => { }, 1000);
// Throws: "Type 'Timer' is not assignable to type 'number'" in atom-typescript.
```

**Comment by FleaChavez** [comment]
I'm also having this issue.

**Comment by guncha** [comment]
It seems like you are using `node` typings which override `setInterval()` as something that returns `NodeJS.Timer`. If you're running in the browser, it doesn't make a whole lot of sense to use these, except for the definition of `require` and you can get that by adding the following line to your project:

```ts
declare function require(name: string): any
```

**Comment by SRHerzog** [comment]
Use `window.setInterval` instead.

**Comment by ollwenjones** [comment]
Seems like a lame work-around, but I guess since difficult to determine which dependency in a large project introduced the ambient node types...

**Comment by fwchen** [comment]
I'm also having this issue in NodeJs.
window.setInterval and global. setInterval not work

**Comment by ThAlmighty** [comment]
same here, really annoying

**Comment by lierdakil** [comment]
Okay, complain about this on the TypeScript repo. We have zero control over how ambient types are resolved.

**Comment by fider** [comment]
Before resolved just use this for your browser code:
`let interval = \<any\>setInterval( ()=>{} )`

**Comment by lierdakil** [comment]
As @SRHerzog suggested, use `window.setInterval`, or figure out what brings in ambient NodeJS types and nuke it (likely `@types/node`). I'm locking the conversation because this is getting out of hand.
