### ISSUE TITLE
[TypeScript 2] Relative paths in typeRoots not resolved (tsconfig.json)

### ISSUE THREAD

**Issue by srjallan** [TypeStrong/atom-typescript#1055]
Hi,

I'm having trouble with type definitions being picked up using TypeScript 2/atom-typescript when the `tsconfig.json` is not in the same directory as node_modules. I have a src folder containing `tsconfig.json`, refrencing `../node_modules/@types` in the typeRoots, and a Jasmine test in src/app. atom-typescript does not pick up the Jasmine declarations (e.g. `describe`, `it` etc) and highlights them as errors.

My folder structure is as follows (some folders removed): 

```
- node_modules
-- @types
- src
-- tsconfig.json
-- app
--- app.component.spec.ts
--- app.component.ts
```

My `tsconfig.json` in `src` is as follows:

``` json
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ],
    "types": [
      "jasmine"
    ]
  }
}
```

`app.component.spec.ts`:

``` javascript
import { AppComponent } from './app.component';

describe('Example', () => {
  beforeEach(() => {
    // Stuff
  });

  it('should create the app', () => {
    expect(true).toBeTruthy();
  });
});
```

Environment info:

OS: OS X El Capitan 10.11.6
Node.js: 6.3.1
Typescript: 2.0.0
Atom: 1.9.8
atom-typescript: 10.1.6

This configuration works with `tsc` on the command line (either `tsc -p src` in the project root, or `tsc -p .` in `src`). It also works in atom-typescript if I put the entire path in typeRoots - e.g. `/Users/sean/someProject/node_modules/@types` - which makes me think that this is an atom-typescript specific issue in resolving relative paths.

Is this a bug or just something I'm doing wrong with my config?

**Comment by selkinvitaly** [comment]
Yes, I confirm it.

Environment info:
OS: Debian x64 stretch
Node.js: 5.11.0
Typescript: 2.1.0-dev.20160812
Atom: 1.5.3
atom-typescript: 10.1.6

**Comment by superchris** [comment]
Also seeing the same thing. OSX, node v 5.1

**Comment by oailloud** [comment]
Same thing here, none of the jasmine types are resolved.
I confirm it's working when `typeRoots` is set to the absolute path to `node_modules/@types` (with jasmine listed in `types`) in the `tsconfig.json`.
OS : Fedora 24
Node v6.6.0
NPM 3.10.3
Atom 1.9.9
atom-typescript 10.1.6

**Comment by spali** [comment]
similar problem with angular2-seed project (mgechev/angular2-seed).
type ```core-js``` not recognized by atom typescript.
defined in ```src/client/tsconfig.json``` with
```
    "typeRoots": [
      "../../node_modules/@types",
      "../../node_modules"
    ],
    "types": [
      "core-js",
      ...
```

```Array.from``` or ```Object.assign``` etc. is not recognized when used.
if I replace the the relative path in ```typeRoots``` with absolute path, it works.

OS: Windows 7
Node: 5.6.0
NPM: 3.10.8
Atom: 1.10.2
atom-typescript: 10.1.7

**Comment by jorgeas80** [comment]
Having the same problem with jasmine, but in VSCode. I don't know if ts plugin for VSCode and for atom are related, but looks suspicious...

**Comment by chrissloan** [comment]
Same issue here. To fix this as a hack until plugin is changed, I pulled in the `node_modules/@types` directory to be direct relative to the `tsconfig.json` file. Looking at the source code for the atom package, there is a default typeRoots path that is always set in relation to the read tsconfig file. I wonder if this is the issue as it does not get overwritten.

Seems dirty, but works and the Angular-cli project I am running does not care as it still looks to the `node_modules` directory outside the `src` directory.

**Comment by iamolivinius** [comment]
Looks like this is the same issue I'm facing right now. 

Excluding `node_modules` due to performance issues results in compiler errors within atom-typescript only.

In the screenshot you can see that VSCode@1.6 as well as tsc@2.0.3 compile the same code without any problems (as it should be). Browserify with tsify don't throw any errors either.

![screenshot from 2016-10-13 14-32-20](https://cloud.githubusercontent.com/assets/832245/19349286/8826a9f4-9152-11e6-9aa0-6394a3efec76.png)

**Comment by nycdotnet** [comment]
I think this is definitely a bug - or rather it had been implemented correctly and then the new functionality of TypeScript wasn't accounted for.  PRs definitely accepted.

**Comment by nikoTM** [comment]
This works as a temporary solution for me:

```JSON
  "exclude": [
    "!/node_modules/@types"
  ]
```

**Comment by spali** [comment]
Did not work for me in the angular2-seed project (mgechev/angular-seed) I mentioned.
But the following workaround did it:

in ```src/client/tsconfig.json```  change
```
    "typeRoots": [
      "../../node_modules/@types",
      "../../node_modules"
    ],
    "types": [
      "core-js",
      ...
```
to
```
    "baseUrl": "../../",
    "typeRoots": [
      "node_modules/@types",
      "node_modules"
    ],
    "types": [
      "core-js",
      ...
```

**Comment by jhm-ciberman** [comment]
+1

**Comment by klemenoslaj** [comment]
+1

**Comment by Shijir** [comment]
Using `include` instead of `exclude` is working too:

```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": false,
        "typeRoots": [
            "node_modules/@types"
        ],
        "types": [
            "jasmine",
            "node",
            "core-js",
            "selenium-webdriver"
        ]
    },
    "include": [
        "src/**/*.ts",
        "node_modules/@types"
    ],
    "atom": {
        "rewriteTsconfig": false
    }
}
```

**Comment by waldnercharles** [comment]
Why was this closed when the issue has not been resolved?

**Comment by kamok** [comment]
@Shijir I can confirm removing the `exclude` array fixed it for me. Thanks.
