### ISSUE TITLE
Medium to high CPU Usage when atom-typescript is enabled

### ISSUE THREAD

**Issue by chris69** [TypeStrong/atom-typescript#1056]
My 2013 Macbook with OS El Captain runs an AtomHelper process with 10-30% CPU usage, when atom-typescript is enabled in preferences. I have an typescript project open. The laptop becomes hot and the ventilators are running constantly. I had to disable the plugin at the end.

Can you please fix this? Thank you.

Tested with atom version 1.9.7 and 1.9.8 and atom-typescript version 10.1.6 (newest to date).

System:

 Model Name:    MacBook Pro
  Model Identifier: MacBookPro10,1
  Processor Name:   Intel Core i7
  Processor Speed:  2.7 GHz
  Number of Processors: 1
  Total Number of Cores:    4
  L2 Cache (per Core):  256 KB
  L3 Cache: 6 MB
  Memory:   16 GB

**Comment by leocorder** [comment]
Same issue here. Atom v1.9.9 and atom-typescript v10.1.6

**Comment by leocorder** [comment]
I managed to increase performance significantly by modifying the file **tsconfig.json** to this:

```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": false
    },
    "exclude": [
        "node_modules",
        "platforms"
    ]
}

```

**Comment by alexwall** [comment]
The compilerOptions has no performance impact for me and 

```
  "exclude": [
        "node_modules",
        "platforms"
    ]
```

does not really helps.

After opening one or more ts files Atom (atom-typescript) still starts to use 18%-30% of my CPU on my iMac (3.5 GHz Intel Core i5) for minutes, even if I change the focus to another application. After some time the cpu usage slows down, but when I just click in the atom editor without doing anything it starts again.

**Comment by alexeypetrushin** [comment]
Same, very slow and high CPU usage, macbook pro.

**Comment by nlaplante** [comment]
Same issue, on Windows 10. Very high CPU usage and typing in editor lags.

**Comment by alexwall** [comment]
Switching to **atom-typescript-beta** solved this problem for me. 
See https://github.com/TypeStrong/atom-typescript/pull/1166

**Comment by alexwall** [comment]
I think this issue can closed after atom-typescript-beta is merged into the master branch

**Comment by guncha** [comment]
Yep, should be fixed now!
