### ISSUE TITLE
Can not auto generated 'js'

### ISSUE THREAD

**Issue by sodaoil** [TypeStrong/atom-typescript#1057]
I installed atom-typescript. Then I created tsconfig.json. Once I was successfully created a helloworld.ts, then after save, the helloworld.js generated.

However, recently, I tried the same way, it could not generate helloworld.js or update helloworld.js after save. I have double checked that "compileOnSave": true,  is correct in my tsconfig.json. 

Does anyone know if there are other things that may cause this issue?

**Comment by AskYous** [comment]
Do you see this on the bottom of Atom?

![image](https://cloud.githubusercontent.com/assets/791996/17872705/24ea5a02-6876-11e6-92b3-030e2c4a0f13.png)

**Comment by sodaoil** [comment]
I always see red "JS outdated", not "JS Current" in the picture. 

Not sure why, is there any previous solution? I did search, but didn'g find one
![1](https://cloud.githubusercontent.com/assets/3161216/17882892/1e027d16-68c4-11e6-9c5e-b4ef2c9a00bb.PNG)
