### ISSUE TITLE
Is 'filesGlob' obsolete / deprecated?

### ISSUE THREAD

**Issue by phreed** [TypeStrong/atom-typescript#1058]
Documentation/FAQ update
In version 2.x of the typescript configuration file [tsconfig.json](https://github.com/Microsoft/TypeScript-Handbook/blob/release-2.0/pages/tsconfig.json.md) there are 'include' and 'exclude' elements which seem to overlap with 'filesGlob'.

Are there reasons why 'filesGlob' remains useful?

**Comment by Gerarddp** [comment]
For example https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#for-really-large-projects-atom-typescript-gets-slow
