### ISSUE TITLE
Cannot find name "require"

### ISSUE THREAD

**Issue by dcsan** [TypeStrong/atom-typescript#1059]
I have this problem with every node project.
I believe its caused by:

```
    "exclude": [
        "node_modules",
        "typings"
    ],
```

in the tsconfig. is it recommended then to be compiling the whole project every time?

![image](https://cloud.githubusercontent.com/assets/514002/17987486/0e2db474-6ad5-11e6-86c6-2ffbf5140cad.png)

**Comment by hszhsh** [comment]
Changing 'const' to 'import' will solve your problem.

**Comment by explicitcall** [comment]
changing `const` to `import` doesn't solve the problem when the required module is JavaScript, not TypeScript

**Comment by explicitcall** [comment]
installing `@types/node` npm package also doesn't help even though `tsc` compiles everything perfectly fine from command-line

**Comment by explicitcall** [comment]
The only solution that worked for me is `declare var require;` at the top of the file that requires a JavaScript module. The rest of the modules are imported with ES6 syntax that doesn't cause a trouble.

**Comment by wyqydsyq** [comment]
Looks like a duplicate of https://github.com/TypeStrong/atom-typescript/issues/829

**Comment by wyqydsyq** [comment]
I'm also experiencing this issue.

My project compiles fine with `tsc` so clearly the Typescript compiler is discovering my ambient definitions (meaning this is an issue with the Atom plugin directly and not a general Typescript question) yet Atom complains about `Cannot find name 'require` unless I add the `<reference ... />` annotation to my entry file.

The Atom plugin must behave consistently with the compiler for it to be useful.
