### ISSUE TITLE
Provide ability to generate tsconfig.json on demand

### ISSUE THREAD

**Issue by kfranqueiro** [TypeStrong/atom-typescript#106]
It would be useful (e.g. for cases of resolving merge conflicts between two branches) to be able to tell atom-typescript to regenerate tsconfig.json at a specific time, via the command palette.

It's not currently clear to me exactly what triggers tsconfig.json to be rebuilt, or whether this is already possible somehow.

**Comment by basarat** [comment]
If we are forced to query the file system (e.g new file) it is rebuilt.  If we have loaded it once and it changes > then it is rebuilt. 

Will add a command to <clear> cache though.

**Comment by basarat** [comment]
On save sounds like a good target for this. This way you don't need an explicit command that team members need to remember.

**Comment by basarat** [comment]
On save will regenerate the files glob. 

Let me know if it is unsufficient.

**Comment by kfranqueiro** [comment]
Thanks!  Chances are I'll have an opportunity to give it a test run sometime today.

**Comment by kfranqueiro** [comment]
Just wanted to confirm that this seems to have resolved things from what I've seen.  Thanks!

**Comment by basarat** [comment]
:heart:

**Comment by basarat** [comment]
The file glob will be regenerated it:

- the tsconfig.json file changes
- you edit a *new file on the file system*, that wasn't matched by the glob before but should be not that it exists. 

Let us know if it is unsufficient
