### ISSUE TITLE
Incorrect syntax highlighting after `${xxx}` symbols

### ISSUE THREAD

**Issue by yerzhant** [TypeStrong/atom-typescript#1061]
Hi,
maybe the \`${}\` symbols produce this result:
![image](https://cloud.githubusercontent.com/assets/11594067/18073026/abe61cf8-6e84-11e6-9890-d4f412468e3f.png)
i.e.
`
        console.error(msg);
        return Observable.throw(msg);
    }
`
incorrectly highlighted.
Atom    : 1.9.9
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Comment by guncha** [comment]
Fixed in `v10.1.10` 🎉
