### ISSUE TITLE
[hyperclick] stop scanning .js files

### ISSUE THREAD

**Issue by AsaAyers** [TypeStrong/atom-typescript#1062]
I have a package called [js-hyperclick](https://github.com/AsaAyers/js-hyperclick) and I have to tell users to disable `atom-typescript` if they want to use `js-hyperclick`. The `hyperclick` service asks each registered package in order to scan a file and the first package that returns a result wins. 

Your [`getSuggestionForWord`](https://github.com/TypeStrong/atom-typescript/blob/v10.1.6/lib/hyperclickProvider.ts#L11) implementation returns a match whether it's really a match or not, and then only does the work necessary in the callback. Because it always returns a value `hyperclick` will never call `js-hyperclick`.

**Comment by tungv** [comment]
yeah, I wish I wouldn't need to uninstall `atom-typescript`, but I can't live without `js-hyperclick`
