### ISSUE TITLE
autocomplete not working

### ISSUE THREAD

**Issue by ghost** [TypeStrong/atom-typescript#1068]
Recently installed atom-typescript with Atom 1.10.0 on Ubuntu 14.04.
Syntax highlighting appears to be working as is the lint at the bottom, however autocomplete does not appear to be working. 
Does not recognise ane previously created variables or any language words.

**Comment by HuysentruytRuben** [comment]
Hey, I also had an issue with atom-typescript autocomplete. It was working but it was extremely slow.

You need to have a `tsconfig.json` in the project root (anyone can correct me if I'm wrong).
atom-typescript can create this file for you by having your cursor in any open `.ts` file and hitting `ctrl+shift+p` (atom shortcut) and entering `create config`. The top result create the file (`tsconfig.json`).

You can check if it works by opening some .ts file with maybe these contents:
```
export class Test {
  constructor (
    public name: number,
    p
  ) { }
}
```
Put your cursor right after standalone `p` and hit `ctrl+space`. Give it some time, it was taking maybe 5-8 seconds before anything showed up (that was before letting the addon generate the config, after using the genrated one I am getting auto complete suggestions in less than half a second).

If auto complete is then still slow for you, you can add folders/files to the exclude list in `tsconfig.json` (it adds some by itself, like node modules).
