### ISSUE TITLE
FYI: `npm run build` grammar script is broken for tsx grammar

### ISSUE THREAD

**Issue by dsifford** [TypeStrong/atom-typescript#1075]
Hi there.

Just a friendly FYI: The `npm run build` script is currently broken for `.tsx` grammars. I can only imagine that this is due to the [recent updates](https://github.com/Microsoft/TypeScript-TmLanguage/commits/master/TypeScriptReact.YAML-tmLanguage) that were made to the tsx grammars in the `TypeScript-TmLangue` repo.

**Comment by guncha** [comment]
Yep, this was addressed in `v10.1.10`. Thanks
