### ISSUE TITLE
Noticeably slow intellisense / typeahead

### ISSUE THREAD

**Issue by sb8244** [TypeStrong/atom-typescript#1078]
Let me know how I can best help here (stack traces, perf profiles, sharing the code, etc).

I'm using the angular 2 webpack starter by Angular Classes and the out of the box typescript is unbearably slow in Atom with atom-typescript. In VSCode, it is instant. In Atom, it ranges from 1-5 seconds per intellisense popup.

Is this a known issue? Is there anything that could improve it? I like atom too much to go to VS Code.

Here is my config json:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "noEmitHelpers": true,
    "strictNullChecks": false,
    "baseUrl": "./src",
    "paths": [
    ],
    "lib": [
      "dom",
      "es6"
    ],
    "types": [
      "hammerjs",
      "jasmine",
      "node",
      "protractor",
      "selenium-webdriver",
      "source-map",
      "uglify-js",
      "webpack"
    ]
  },
  "exclude": [
    "node_modules",
    "dist"
  ],
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": { "rewriteTsconfig": false }
}
```

**Comment by eliOcs** [comment]
For me it was very slow until I excluded `node_modules`, seems you already got that part. I'll paste my current `tsconfig.json` for you to try it:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false
}
```

**Comment by arlowhite** [comment]
It's still horribly slow for me as well. Even if I disable **autocomplete-plus** "Show Suggestions On Keystroke", every character I type will still increase the TypeScript task spinner and it often takes a few seconds to finish. For example, I type ~20 characters, the TypeScript spinner jumps to ~30-40 for a second, then decreases to ~10-20 for another second, then finishes.

Atom 1.10.2
atom-typescript 10.1.8
TypeScript 2.0.3

This is with an [angular-cli](https://github.com/angular/angular-cli) project.

**Comment by arlowhite** [comment]
Also, I tried changing the **linter** package settings.
 * Unchecked "Lint As You Type"
 * Increased "Lint As You Type Interval"

This seems to have no effect on atom-typescript. It still creates a bunch of TypeScript spinner tasks as soon as I type a few characters.

**Comment by arlowhite** [comment]
Just updated Atom to **1.11.2**; it seems much faster, try upgrading Atom and see if your performance improves.
[Atom Releases Changelog](https://atom.io/releases)

**Comment by maticmeznar** [comment]
I'm having the same problem. I did everything suggested in this issue, but it's still way too slow. What is being done about this? What's the ETA?
