### ISSUE TITLE
Typescript highlighting

### ISSUE THREAD

**Issue by keithmichelson** [TypeStrong/atom-typescript#1080]
Not sure if this is something for atom or atom-typescript package but when selecting typescript as the file in an Angular 2 project some of the basic javascript doesn't color like you'd think it should but the typescript looks good. If you switch the file type to javascript the regular javascript looks good but not the typescript. Is there a way to get both colored/highlighted?

(select typescript as file type
![screen shot 2016-09-26 at 12 04 01 am](https://cloud.githubusercontent.com/assets/10779020/18824255/a85f22ec-837d-11e6-8ac0-f244d7a47f85.png)

(select javascript as file type)
![screen shot 2016-09-26 at 12 04 18 am](https://cloud.githubusercontent.com/assets/10779020/18824256/abae8906-837d-11e6-85d1-66b453ec7e55.png)

(select typescript as file type)
![screen shot 2016-09-26 at 12 08 35 am](https://cloud.githubusercontent.com/assets/10779020/18824266/b8752b18-837d-11e6-8521-94e2b18bb45d.png)

(select javascript as file type)
![screen shot 2016-09-26 at 12 08 50 am](https://cloud.githubusercontent.com/assets/10779020/18824269/bf5999a0-837d-11e6-844f-6fc72e977418.png)

**Comment by distante** [comment]
I'm starting with typescript and notice this too, is a little hard to keep up with the code when (for example) something like `document.body.innerHTML.length` is just plain white text.

**Comment by Goodwine** [comment]
A **temporary** workaround for now is adding this to your config.cson:

```
core:
  customFileType:
    "sources.js": [
      "ts"
    ]
```

**Comment by distante** [comment]
Should I restart Atom to see the changes?

**Comment by guncha** [comment]
Syntax highlighting got much better in `v10.1.10`. This largely depends on the theme you're using, but at least the proper hooks are there. Give it a shot and let me know how it works for you.
