### ISSUE TITLE
REMOVE spellcheck popup on each keypress and your plugin will be brilliant

### ISSUE THREAD

**Issue by snowyurik** [TypeStrong/atom-typescript#1086]
what's the point of checking spelling during typing? It's always like 

export c
OMFKG!! WRONG!!

export cl
OMFKG!! WRONG!!

export cla
OMFKG!! WRONG!!

export clas
OMFKG!! WRONG!!

export class
... oh, that's ok

..
export class MyClass {
  p
OMFKG!! WRONG!!

export class MyClass {
  pu
OMFKG!! WRONG!!

export class MyClass {
  pub
OMFKG!! WRONG!!

export class MyClass {
  publ
OMFKG!! WRONG!!

Yeah, extremely annoying. Footer bounce all the time. It's impossible to work. However everything else is fine )

**Comment by pzuraq** [comment]
👍

**Comment by arlowhite** [comment]
I've been annoyed by the autocomplete behavior too. From other issues, I've seen people say **autocomplete-plus** package settings should control this. "Show Suggestions On Keystroke", "Delay Before Suggestions Are Shown"

But for me, even when I change these settings, the TypeScript spinner keeps increasing with every character I type and it takes a few seconds to finish its tasks before I even get autocomplete results. Also, Atom crashes often when I edit TypeScript files.

But maybe changing **autocomplete-plus** settings will work for you.
