### ISSUE TITLE
Cannot point atom to the proper TS install

### ISSUE THREAD

**Issue by farcaller** [TypeStrong/atom-typescript#1088]
```
% tsc -v
Version 2.1.0-dev.20160919
```

I've set the full path to typescriptServices.js to:

`/Users/farcaller/.homebrew/lib/node_modules/typescript/lib/typescriptServices.js`

the error I'm getting is:

```
no tsconfig.json, The project file contains invalid options:
UnknownOption: traceResolution
```

(which is there in my tsconfig):

```
"traceResolution": false,
```

**Comment by phreed** [comment]
I believe the "traceResolution" option is only available from the command line.

**Comment by phreed** [comment]
Are there any options that are only available on the command line?
https://www.typescriptlang.org/docs/handbook/compiler-options.html
...indicates that some options are only available in tsconfig.json.
