### ISSUE TITLE
Unsupported target version: 0.34.3

### ISSUE THREAD

**Issue by AceTheFace** [TypeStrong/atom-typescript#1089]
I'm not really sure if this is an issue of atom-typescript, but the packaged worked well and since a few days (probably after an automatic atom-update) I only get this message:

`
npm WARN prefer global coffee-script@1.9.0 should be installed with -g
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.34.3
node-pre-gyp ERR! stack     at get_runtime_abi (/Users/dummyUser/.atom/packages/atom-typescript/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:156:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/dummyUser/.atom/packages/atom-typescript/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:277:19)
node-pre-gyp ERR! stack     at install (/Users/dummyUser/.atom/packages/atom-typescript/node_modules/fsevents/node_modules/node-pre-gyp/lib/install.js:148:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install](/Users/dummyUser/.atom/packages/atom-typescript/node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/Users/dummyUser/.atom/packages/atom-typescript/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/dummyUser/.atom/packages/atom-typescript/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:456:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:312:12)
node-pre-gyp ERR! System Darwin 15.6.0
node-pre-gyp ERR! command "node" "/Users/dummyUser/.atom/packages/atom-typescript/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/dummyUser/.atom/packages/atom-typescript/node_modules/fsevents
node-pre-gyp ERR! node -v v0.10.40
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok 

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/dummy.User/Library/Application Support/com.github.atom.ShipIt/update.V1zOS4f/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/dummy.User/Library/Application Support/com.github.atom.ShipIt/update.V1zOS4f/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/dummyUser/.atom/.apm/.apmrc" "--userconfig" "/Users/dummyUser/.atom/.apmrc" "rebuild" "--target=0.34.3" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
npm ERR! fsevents@1.0.14 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.0.14 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dummyUser/.atom/packages/atom-typescript/npm-debug.log
`

**Comment by bypotatoes** [comment]
+1
