### ISSUE TITLE
atom-typescript automatically opens and focuses to child.js file

### ISSUE THREAD

**Issue by prasanthkarukkuvel** [TypeStrong/atom-typescript#1098]
The latest atom-typescript opens the child.js from the .atom/atom-typescript/dist/worker and focus to it automatically. There is no such behavior while disabling the plugin.

Atom Version: 1.12.0-beta0
Platform: Windows 10

![image](https://cloud.githubusercontent.com/assets/714911/19325535/34e14290-90e4-11e6-84f0-1fb5f7fa458c.png)

**Comment by Equinox** [comment]
I had this on atom-typescript 10.1.7, too.

As soon as I open a .ts file it opens then focuses on that child.js file. I had to reload the editor window constantly to make it stop (then going to another .ts file starts it again).

**Comment by kpping** [comment]
I did fix this by completely uninstall Atom and re-intsall it again.

**Comment by lhecker** [comment]
> I did fix this by completely uninstall Atom and re-intsall it again.

I tried that and it didn't work for me. I'm on Windows with `1.12.0-beta1`.

**Comment by jemmrich** [comment]
I am also having this problem, I am running atom-typescript 10.1.9 with Atom v 1.5.4. Disabling this plugin prevents child.js from opening and forcing active tab.

**Comment by lhecker** [comment]
@jemmrich You're using Atom 1.5 which is now 9 months old. The current stable version is 1.11.

**Comment by ottoteixeira** [comment]
I had 1.5 and updating to 1.11.2 solved the problem.

**Comment by geltoncruz** [comment]
I need to disable the atom-typescript package to continue working

**Comment by lhecker** [comment]
@geltoncruz What's preventing you from updating Atom?

**Comment by geltoncruz** [comment]
**@lhecker,** I did the update through the package. But after that I could not work because of the **child.js** file
this file is open and I can not close it.

So to work with **IDE atom**, I had to disable the update of the **typescript**.

**Comment by lhecker** [comment]
@geltoncruz That's strange... It not just "should" but actually has to work as long as you're up to date. So please make sure you're using Atom 1.11.2 or newer and atom-typescript 10.1.11 or newer. If **either one** is too old it will continue opening the child.js file.

**Comment by fedebucich** [comment]
Happening to me on 1.12.2
I tried reinstalling but I can not get rid of this error

**Comment by jon123** [comment]
Same problem here. On latest (1.12.3).  Atom wouldn't respond on the task manager (window 8.1) so I gave it the three finger salute and when I restarted Atom,it started to bring child.js to the forefront every 5 seconds (roughly).

**Comment by jon123** [comment]
Updated atom-typescript to latest (10.1.12) and it fixed the problem

**Comment by jon123** [comment]
Spoke too soon. It fixed the problem with child.js but now intellisense appears broken on typescript files.

**Comment by jon123** [comment]
Spoke too soon again.  I disabled atom-typescript so I could navigate easier and didn't re-enable after updating. Everything appears fine.

**Comment by ashishsajwan** [comment]
reinstalling [atom-typescript package](https://atom.io/packages/atom-typescript package) works for me ..

**Comment by slavik57** [comment]
Resolved for me after updating to atom-typescript 10.1.12. Had to fight with the IDE though to actually make the update.

**Comment by ashishlad007** [comment]
It worked for me after updating typescript plugin

**Comment by 4xmg** [comment]
this continues even after uninstall and reinstall of atom (1.14.1) and typescript-atom

**Comment by CyrilleGuimezanes** [comment]
Same problem here with Atom 1.14.3 and atom-typescript 10.1.2...

**Comment by matthewdaniel** [comment]
Try closing atom and opening terminal and doing `apm install atom-typescript`. Using atom to disable typescript was impossible for me.
