### ISSUE TITLE
build tasks never finish on latest atom beta

### ISSUE THREAD

**Issue by giladgray** [TypeStrong/atom-typescript#1099]
`typescript 2.0.0 & 2.0.3`
`atom-typescript 10.1.8`
`atom-beta 1.12.0-beta1`

not a single build task finishes, they just keep queuing. tsconfig doesn't seem to matter much, i tried a bunch of different projects and they all had the same issue.

**Comment by giladgray** [comment]
reverted to `atom-beta 1.11.0-beta5` and it works beautifully again.

**Comment by steakknife** [comment]
Currently, Atom stable is `1.11.2`, beta is `1.12.0-beta3`.

**Comment by gizmodus** [comment]
I also have this problem with Atom 1.12.7

**Comment by gizmodus** [comment]
The problem is still present (Atom 1.14.4 ia32). I attached a screenshot to clarify it.

![image](https://cloud.githubusercontent.com/assets/11334553/23613265/098b3512-027f-11e7-9ff9-690503bd180d.png)

**Comment by giladgray** [comment]
my solution here was to switch to VS Code, the one true TypeScript editor. i haven't looked back. (sorry atom!)
