### ISSUE TITLE
Deprecated selector in `atom-typescript/styles/atomts-grammar-syntax.less`

### ISSUE THREAD

**Issue by Nikki1993** [TypeStrong/atom-typescript#1108]
In `atom-typescript/styles/atomts-grammar-syntax.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:
- `atom-text-editor::shadow .source.ts .require.path,
  atom-text-editor::shadow .source.tsx .require.path,
  atom-text-editor::shadow .source.ts .reference.path,
  atom-text-editor::shadow .source.tsx .reference.path,
  atom-text-editor::shadow .source.ts .es6import.path,
  atom-text-editor::shadow .source.tsx .es6import.path,
  atom-text-editor::shadow .source.ts .amd.path,
  atom-text-editor::shadow .source.tsx .amd.path` => `atom-text-editor .syntax--source.syntax--ts .syntax--require.syntax--path,
  atom-text-editor .syntax--source.syntax--tsx .syntax--require.syntax--path,
  atom-text-editor .syntax--source.syntax--ts .syntax--reference.syntax--path,
  atom-text-editor .syntax--source.syntax--tsx .syntax--reference.syntax--path,
  atom-text-editor .syntax--source.syntax--ts .syntax--es6import.syntax--path,
  atom-text-editor .syntax--source.syntax--tsx .syntax--es6import.syntax--path,
  atom-text-editor .syntax--source.syntax--ts .syntax--amd.syntax--path,
  atom-text-editor .syntax--source.syntax--tsx .syntax--amd.syntax--path`
- `atom-text-editor::shadow .source.ts .keyword.debugger,
  atom-text-editor::shadow .source.tsx .keyword.debugger` => `atom-text-editor .syntax--source.syntax--ts .syntax--keyword.syntax--debugger,
  atom-text-editor .syntax--source.syntax--tsx .syntax--keyword.syntax--debugger`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by C-Bouthoorn** [comment]
This message is also showing on my system:

Atom: `1.13.0-beta1`
OS: `Linux 4.4.0-32-generic #51-Ubuntu` (Ubuntu 16.04)
Node: `v6.9.1`
npm: `v4.0.2`
apm: `v1.1.1`

**Comment by TimvdLippe** [comment]
Atom `1.13.0` is now stable and it also reported on my system. A similar issue was fixed in the linter package, see https://github.com/steelbrain/linter/commit/98a63e1d280a753edbb2f4c9549eee9f686b78b6

**Comment by raulxproject** [comment]
Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

atom-text-editor::shadow .source.ts .require.path, atom-text-editor::shadow .source.tsx .require.path, atom-text-editor::shadow .source.ts .reference.path, atom-text-editor::shadow .source.tsx .reference.path, atom-text-editor::shadow .source.ts .es6import.path, atom-text-editor::shadow .source.tsx .es6import.path, atom-text-editor::shadow .source.ts .amd.path, atom-text-editor::shadow .source.tsx .amd.path => atom-text-editor.editor .syntax--source.syntax--ts .syntax--require.syntax--path, atom-text-editor.editor .syntax--source.syntax--tsx .syntax--require.syntax--path, atom-text-editor.editor .syntax--source.syntax--ts .syntax--reference.syntax--path, atom-text-editor.editor .syntax--source.syntax--tsx .syntax--reference.syntax--path, atom-text-editor.editor .syntax--source.syntax--ts .syntax--es6import.syntax--path, atom-text-editor.editor .syntax--source.syntax--tsx .syntax--es6import.syntax--path, atom-text-editor.editor .syntax--source.syntax--ts .syntax--amd.syntax--path, atom-text-editor.editor .syntax--source.syntax--tsx .syntax--amd.syntax--path
atom-text-editor::shadow .source.ts .keyword.debugger, atom-text-editor::shadow .source.tsx .keyword.debugger => atom-text-editor.editor .syntax--source.syntax--ts .syntax--keyword.syntax--debugger, atom-text-editor.editor .syntax--source.syntax--tsx .syntax--keyword.syntax--debugger
Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by veenified** [comment]
Running Atom 1.13.0 and atom-typescript 10.1.13

```
Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

atom-text-editor::shadow .source.ts .require.path, atom-text-editor::shadow .source.tsx .require.path, atom-text-editor::shadow .source.ts .reference.path, atom-text-editor::shadow .source.tsx .reference.path, atom-text-editor::shadow .source.ts .es6import.path, atom-text-editor::shadow .source.tsx .es6import.path, atom-text-editor::shadow .source.ts .amd.path, atom-text-editor::shadow .source.tsx .amd.path => atom-text-editor.editor .syntax--source.syntax--ts .syntax--require.syntax--path, atom-text-editor.editor .syntax--source.syntax--tsx .syntax--require.syntax--path, atom-text-editor.editor .syntax--source.syntax--ts .syntax--reference.syntax--path, atom-text-editor.editor .syntax--source.syntax--tsx .syntax--reference.syntax--path, atom-text-editor.editor .syntax--source.syntax--ts .syntax--es6import.syntax--path, atom-text-editor.editor .syntax--source.syntax--tsx .syntax--es6import.syntax--path, atom-text-editor.editor .syntax--source.syntax--ts .syntax--amd.syntax--path, atom-text-editor.editor .syntax--source.syntax--tsx .syntax--amd.syntax--path
atom-text-editor::shadow .source.ts .keyword.debugger, atom-text-editor::shadow .source.tsx .keyword.debugger => atom-text-editor.editor .syntax--source.syntax--ts .syntax--keyword.syntax--debugger, atom-text-editor.editor .syntax--source.syntax--tsx .syntax--keyword.syntax--debugger
Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.
```

**Comment by thatchercollins** [comment]
I have the same, running this system:
Atom 1.13.0 x64
MacOS Sierra 10.12.2
Node: 7.4.0
npm: 4.0.5
apm --version = 1.14.1, npm 3.10.5, node 4.4.5, python 2.7.11, git 2.10.1
atom --version = atom 1.13.0, electron 1.3.13, chrome 52.0.2743.82, node 6.5.0

**Comment by tekpilot-llc** [comment]
I got the same issue for atom-typscript plugin

**Comment by ulihorn** [comment]
I have the same issue for Atom 1.13.1

**Comment by ZuBB** [comment]
please stop writing "I have the same". In 2017 we have "add reaction" in github.

If you wanna subscribe for this thread there is dedicated button for this.

// sorry for buzz

**Comment by mumairofficial** [comment]
following change work for me
`atom-text-editor::shadow`
to
`atom-text-editor.editor`

**Comment by koba-ninkigumi** [comment]
https://github.com/TypeStrong/atom-typescript/pull/1195
