### ISSUE TITLE
can not update to or install atom-typescript v10.1.10

### ISSUE THREAD

**Issue by stesachse** [TypeStrong/atom-typescript#1115]
```
% apm --version
apm  1.13.0
npm  2.15.9
node 4.6.0
python 2.7.12
git 2.7.4
```

```
% apm install atom-typescript
Installing atom-typescript to /home/$MYLOGINNAME/.atom/packages ✗

npm WARN peerDependencies The peer dependency typescript@* included from byots will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Linux 4.7.7-200.fc24.x86_64
npm ERR! argv "/usr/lib/node_modules/atom-package-manager/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/$MYLOGINNAME/.atom/.apm/.apmrc" "--userconfig" "/home/$MYLOGINNAME/.atom/.apmrc" "install" "/tmp/d-116929-3503-1jawem1/package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=x64" "--global-style" "--legacy-bundling"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package typescript@2.1.0-dev.20161023 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer byots@2.1.0-dev.20161022.0.26 wants typescript@*

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116929-3503-1c1yv7o/npm-debug.log
```

there is no directory `/tmp/apm-install-dir-116929-3503-1c1yv7o`

maybe the problem is `peerDependencies` from [byots](https://github.com/basarat/byots/blob/master/package.json#L29)

```
"typescript": "*"
```

`*` doesn't match pre-release versions

```
% semver -r '*' 2.0.0 2.0.1 2.1.0 2.1.1 2.1.0-dev.20161023 2.2.0 2.2.1-dev.20161023 2.3.0
2.0.0
2.0.1
2.1.0
2.1.1
2.2.0
2.3.0
```

documentation for [node-semver](https://github.com/npm/node-semver#prerelease-tags) says

> If a version has a prerelease tag (for example, 1.2.3-alpha.3) then it will only be allowed to satisfy comparator sets if at least one comparator with the same [major, minor, patch] tuple also has a prerelease tag.

**Comment by guncha** [comment]
Yeah, this is a known issue with `npm 2.x`. The problem is that there's no way to specify a range that will match any prerelease version. `byots` would have to say `2.2.0-dev || 2.2.1-dev || 2.3.0-dev` and so on.

I can update Typescript to `2.0.6` which is very close to the nightly we're using now, but there's a different issue with the `byots` declaration file containing initializers.

What's your Atom version?

**Comment by saeedtabrizi** [comment]
Same problem as @stesachse reported :(

**Comment by stesachse** [comment]
```
% atom --version
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

**Comment by guncha** [comment]
Should be fixed in `v10.1.11`

**Comment by saeedtabrizi** [comment]
hi @guncha .
 i tried to install it again . the package installed but can not load as below error :

__```
filename is not defined
Hide Stack Trace
ReferenceError: __filename is not defined
    at isFileSystemCaseSensitive (evalmachine.<anonymous>:3410:36)
    at getNodeSystem (evalmachine.<anonymous>:3413:45)
    at evalmachine.<anonymous>:3695:19
    at ts (evalmachine.<anonymous>:3709:7)
    at evalmachine.<anonymous>:3715:3
    at Object.exports.runInContext (vm.js:44:17)
    at Object.makeTsGlobal (/home/fff/.atom/packages/atom-typescript/dist/typescript/makeTypeScriptGlobal.js:18:12)
    at Object.<anonymous> (/home/fff/.atom/packages/atom-typescript/dist/main/atomts.js:4:24)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
```

Thanks

**Comment by saeedtabrizi** [comment]
@guncha may be related to this issue as displayed in atom 
[#1071](https://github.com/TypeStrong/atom-typescript/issues/1071)

**Comment by stesachse** [comment]
`v10.1.11` works for me! thanks @guncha

**Comment by guncha** [comment]
@saeedtabrizi please open a new issue. You're running a custom version of Typescript using the "Full path to typescriptServices.js" option in the settings so this is unrelated to the issue here.
