### ISSUE TITLE
Refactoring Wishlist

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#112]
- extract interface from class, module, or function
- copy type from variable
- implement stub (to enable "use first" programming flow).  doStuff(p1 : string) doesn't exist on MyClass - would you like to implement it?
- "Declare this" refactoring on an instantiated variable.
- Declare all refactoring on a constructor function  

Courtesy @nycdotnet https://github.com/TypeStrong/atom-typescript/issues/59#issuecomment-73228618

**Comment by basarat** [comment]
Wishlist 

* [ ] rename file module (this is a big pain and the reason why we added `///ts:import` transform in the first place)

**Comment by rogergl** [comment]
I think I would volunteer for 'extract interface from class, module, or function'

**Comment by nycdotnet** [comment]
Feel free if you want a challenge.  That'd be great!

**Comment by Diullei** [comment]
:+1:

**Comment by rogergl** [comment]
BTW: Any ides how to handle settings for the quickfixes. e.g. sort methods names yes/no ?

**Comment by nycdotnet** [comment]
There is already a settings dialog for atom-typescript, though I would strongly suggest trying to avoid anything that would require using it.

In the situation you've provided - extract interface - perhaps have the interface members come out in the order they're declared (if that can be determined) and provide a new refactoring "sort interface properties alphabetically".

**Comment by rogergl** [comment]
The ordering was just an example. I think that it should be possible to customize the behavior of the quickfixes and that it should be a per project setting. I would prefer a section in the tsconfig.json file, but I do not know if this is possible and (or) allowed.

**Comment by rogergl** [comment]
Just wondering how the file path in a Quickfix result is supposed to work. If I return the following result test2.ts is opened and then I get an unhandled promise exception with TypeError: Cannot read property 'transact' of undefined.

```javascript
 result = {
            span: {
                start: 0,
                length: 5
            },
            newText: "hello",
            filePath: "test2.ts"  // does not exist yet
};
```

**Comment by basarat** [comment]
> Any ides how to handle settings for the quickfixes. e.g. sort methods names yes/no ?

Two solutions (neither implemented yet) : 

1.) Allow the quick fixes to add a UI (https://github.com/TypeStrong/atom-typescript/blob/674ea18a76d9765d35bf9359269b2e73d3029113/lib/main/atom/commands/commands.ts#L423) 

Basically run the quickfix code *in the ui thread* to generate a UI. Since creating atom UI's is a bit hard try not to do this :) 

2.) Return *multiple* quick fixes from a single *canProvideQuickFix*. And then pass in the selected version to *applyQuickFix*. 

I am leaning toward this because I already see need for this e.g. *readonly* vs *read-write* properties can come from same quickfix file. 

> I would prefer a section in the tsconfig.json file, but I do not know if this is possible and (or) allowed.

Not yet. I've already polluted tsconfig.json too much. Will clean up before I start adding more stuff (https://github.com/TypeStrong/atom-typescript/issues/324) 

> does not exist yet

This is not supported. It needs to be a file on the file system (that's how quick fixes have worked up until now). All the code is in here : https://github.com/TypeStrong/atom-typescript/blob/674ea18a76d9765d35bf9359269b2e73d3029113/lib/main/atom/commands/commands.ts#L33-L61

Currently it has "open files" and "closed files" : https://github.com/TypeStrong/atom-typescript/blob/674ea18a76d9765d35bf9359269b2e73d3029113/lib/main/atom/commands/commands.ts#L34-L39 Consider adding "new files" to this list as well.

**Comment by MarvinLudwig** [comment]
Is there any progress on the _extract interface_ feature?

**Comment by basarat** [comment]
> Is there any progress on the extract interface feature?

Nope. However I would hold off on it since the TypeScript team is planing official support for quick fixes :rose:

**Comment by chriszrc** [comment]
@basarat So can we do this now yet?

**Comment by basarat** [comment]
@chriszrc if people add them to TypeScript, they will show up in all IDEs 🌹:
https://github.com/TypeStrong/atom-typescript/blob/master/README.md#quick-fix

**Comment by chriszrc** [comment]
@basarat So that's a no? I might actually have to finally crack open vs code :(

**Comment by lierdakil** [comment]
@chriszrc see if whatever you need is implemented in tsserver: https://github.com/Microsoft/TypeScript/tree/master/src/services/codefixes. If it is, ctrl+enter (if using `intentions` -- `intentions:show` command) or alt+a (if using `atom-ide-ui` -- `diagnostics:show-actions-at-position` command) when the text cursor is close to the thing you want fixed, a menu will pop up. If it does not work, open a new issue. If it's not implemented in tsserver, chances are it won't work in vscode either.
