### ISSUE TITLE
[Syntax highlighting] for of loop with comment

### ISSUE THREAD

**Issue by 0815fox** [TypeStrong/atom-typescript#1121]
```
for (/*const*/ let x of X) {

}
```
As stable FireFox not yet supports const in for of loops I replaced all const those loops by let, but kept the const as inline comment for easier refind later. This breaks syntax highlighting from the next function on.
The following however works perfectly:
```
for (let /*const*/ x of X) {

}
```

**Comment by admosity** [comment]
![image](https://cloud.githubusercontent.com/assets/4655972/20079345/3bc6c930-a512-11e6-9324-07a0ea2ba9bc.png)

Looks fine?

**Comment by 0815fox** [comment]
After the last update of atom-typescript I cannot reproduce that behavior anymore.
I thought I had updated before writing the report but it seems that it was not the case (maybe I forgot to restart atom after the plugin update).
Thank you.
