### ISSUE TITLE
Autocomplete imports

### ISSUE THREAD

**Issue by JKatGSD** [TypeStrong/atom-typescript#1122]
Hi,

recently i updated atom-typescript to version 10.1.11.
After that when i import a module there is no autocompletion what i want to import.
After moving back to version 10.1.9 the auto-completion of modules works again.
I'm using atom on Windows 10 64 bit.

Do you need more information for this bug?

**Comment by rathermarv** [comment]
Same issue here - have been experiencing this for a few days.  Downgraded from 10.1.11 to 10.1.9 and module auto-complete works again. For the record, reference tags for *.d.ts files were auto-completing correctly under 10.1.11.
Ubuntu 16.04.1, Atom 1.11.2.

**Comment by guncha** [comment]
Does this happen with every import or just one package in particular? I.e., if you create a blank project, do you have this problem?

**Comment by rathermarv** [comment]
@guncha I've found this with all module imports in all projects. Toggling between versions 10.1.9 and 10.1.11 effectively toggles between module imports working and not working, respectively. It happens with existing and new projects.

**Comment by JKatGSD** [comment]
+1 i can confirm that

**Comment by guncha** [comment]
Ok, cool, I just confirmed it. I'll look into it.

**Comment by JKatGSD** [comment]
Version: 10.1.9
![atom-typescript v 10 1 9](https://cloud.githubusercontent.com/assets/15359270/20011313/71931640-a2ab-11e6-95e8-06b2cb6b5ab2.PNG)

Version: 10.1.11
![atom-typescript v 10 1 11](https://cloud.githubusercontent.com/assets/15359270/20011314/71934caa-a2ab-11e6-9cbf-1438179c1fc6.PNG)

**Comment by rbojha** [comment]
Hey Guys, any update on this??
i am also experiencing this for few days, had to downgrade to `atom-typescript@10.1.9`.
