### ISSUE TITLE
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed

### ISSUE THREAD

**Issue by Goodwine** [TypeStrong/atom-typescript#1124]
After update 10.1.12 I am getting:

> Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

I reverted the changes from this PR #1117 locally and now things work fine.

**Comment by guncha** [comment]
You're using a custom typescript version and not the one that came with `atom-typescript`. If you update to a recent nightly, it should work fine. The current stable (2.0.6?) still has the issue, but you can work around it by creating a wrapper package that's using `loophole` to require Typescript.

```js
var loophole = require("loophole")
module.exports = loophole.allowUnsafeNewFunction(function() {
  return require("typescript")
})

```

Then specify a full path to this module.

**Comment by dsifford** [comment]
@guncha I'm getting the issue with typescript `2.1.0-dev.20161109`

**Comment by robey** [comment]
I'm still seeing this.

**Comment by Goodwine** [comment]
My workaround was doing:

1. Update `makeTypeScriptGlobal.js` to:

```javascript
var loophole = require("loophole");
// ...
global.ts = loophole.allowUnsafeNewFunction(() => require(typescriptPath));
```

2. Update `package.json` to:

```javascript
"dependencies": {
  // ...
  "loophole": "1.1.0"
}
```

3. Install loophole

```bash
# Not sure if this is the correct way of doing it as I know nothing about node.
$ cd ~/.atom/packages/atom-typescript/node_modules
$ npm i loophole
```

**Comment by robey** [comment]
Is there any legit fix for this in the pipeline? Is atom-typescript deprecated?

**Comment by conan747** [comment]
This workaround doesn't work for me... Just to clarify, this is the new _makeTypeScriptGlobal.js_ that I have, in case I made csome mistake:

```
import {isAbsolute} from "path"

// Debugging helper
global.stack = function() {
    console.error((<any>new Error()).stack);
}

// Export Typescript as a global. Takes an optional full path to typescriptServices.js
export function makeTsGlobal(typescriptPath?: string) {
  if (typescriptPath) {
    if (!isAbsolute(typescriptPath)) {
      throw new Error(`Path to Typescript "${typescriptPath}" is not absolute`)
    }

    typescriptPath = typescriptPath.trim()
  } else {
    typescriptPath = "typescript"
  }
  // I added this:
  var loophole = require("loophole");
  global.ts = loophole.allowUnsafeNewFunction(() => require(typescriptPath));
  // global.ts = require(typescriptPath);
}
```

**Comment by Goodwine** [comment]
@conan747, it seems like you are updating `makeTypeScriptGlobal.ts` instead of `makeTypeScriptGlobal.js`

**Comment by conan747** [comment]
Yeah, that was it. Thanks man!

**Comment by Goodwine** [comment]
After version 11.x I believe this issue is now fixed.
