### ISSUE TITLE
Cannot find name 'describe' or any jasmine globals

### ISSUE THREAD

**Issue by rchod** [TypeStrong/atom-typescript#1125]
![capture du 2016-10-28 13-15-41](https://cloud.githubusercontent.com/assets/623771/20108122/438cd4ec-a5db-11e6-9aaf-abb0db8dba15.png)

here is my tsconfig.json file:
```

{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ],
    "types": [
      "jasmine"
    ]
  }
}
```
the path to node_modules/@types is correct

**Comment by ksharifbd** [comment]
I've answered similar issue on [SO](https://stackoverflow.com/questions/39020022/angular-2-unit-tests-cannot-find-name-describe/39945169#39945169). May be you will find it helpful.

**Comment by Lucas-C** [comment]
My workaround was to copy the `declare` definitions from there: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jasmine/index.d.ts

**Comment by Shijir** [comment]
Using `include` instead of `exclude` is working for me:

```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": false,
        "typeRoots": [
            "node_modules/@types"
        ],
        "types": [
            "jasmine",
            "node",
            "core-js",
            "selenium-webdriver"
        ]
    },
    "include": [
        "src/**/*.ts",
        "node_modules/@types"
    ],
    "atom": {
        "rewriteTsconfig": false
    }
}
```

**Comment by drernie** [comment]
I had the analogous problem with mocha.  I tried all the other options, but finally had to do:
```
import {} from "mocha";
```
at the top of each spec file.  The `typeRoots` and `include` didn't help.

**Comment by guncha** [comment]
Typescript will by default include everything from `node_modules/@types` UNLESS you specify something in the `types` option. This was problematic before, but should work fine now. If the compiler can find it, so can `atom-typescript`.

**Comment by renewooller** [comment]
Adding:
"node_modules/@types/mocha" to the include worked for me, eg:

 "include": [
    "src/**/*",
    "test/integration/**/*",
    "node_modules/@types/mocha"
  ]

you'll have to close the file and open it again or sometimes even restart vscode to see the effect

**Comment by b-malone** [comment]
I had this same problem with an Ionic-Angular mobile app using Ionic 3 and Angular 5.
The fix was to use packages ts-node and jasmine-ts and to install @types/jasmine and include them in a tsconfig.json file for Protractor to read.


Thanks for the help!

**Comment by acro5piano** [comment]
In my case, remove `node_modules` from `tsconfig.exclude`

```
  "exclude": [
    "node_modules", // remove this
    "dist",
    "static"
  ]
```
