### ISSUE TITLE
How do I disable the compile on save feature of typescript ?

### ISSUE THREAD

**Issue by sreyan32** [TypeStrong/atom-typescript#1126]
Could someone please tell me how to disable the compile on save feature of typescript plugin for Atom ?

**Comment by pelotom** [comment]
Add `"compileOnSave": false` to your `tsconfig.json`.

**Comment by ZuBB** [comment]
this option is specific to this package only but not to typescript itself. I do not understand why it should be stated in `tsconfig`? IMO it should be buried somewhere in `atom-typescript` package settings

@basarat what do you think on this?

**Comment by ZuBB** [comment]
also one more question on this option: does it imply somehow on '**Live error analysis**' feature of this plugin?
