### ISSUE TITLE
performance on mid-size projects

### ISSUE THREAD

**Issue by cortopy** [TypeStrong/atom-typescript#1131]
atom-typescript works like a charm when I start a new ts project. However, as soon as the number of files grows, performance issues start to creep in. Mainly:

- autocompletion stops working
- error reporting freezes (with visual cues pointing to what has already been corrected)
- native atom snippets stop working too!!

Today I noticed that the notification at the bottom for "Pending Requests" can reach 1500+ at certain points. If I leave Atom for a few minutes and the "Pending requests" reach zero, the same issues persist.

I've always noticed this behaviour when working with ts files in Atom. I've just been trying to debug possible causes but with no success.

Is there anything I should be configuring in a different way?
Is this a limitation with atom and/or typescript?

**Comment by nullptr128** [comment]
```
"filesGlob": [
        "!node_modules/**"
    ],
```

This can help A BIT. Unfortunately, even though it reduced lag for me a lot, it still is not very useable on large projects. My project consist of around 270 .ts files and for a simple autocompletion after placing a dot I must wait like 2-3 seconds. It may seem not much, but today I've tried Visual Studio Code as alternative and it is so blazing fast (stil using same html technology)...

**Comment by guncha** [comment]
We're using `atom-typescript` on a fairly large project too and the performance is good, unless we ask it to autocomplete a module import. Then the pending requests shoot up in the low hundreds.

Can you describe your directory structure and paste your `tsconfig.json` files?

**Comment by cortopy** [comment]
I've tried the glob that @nullptr128 suggests and I haven't noticed any difference. However, I've also followed his suggestion of using Visual Studio and I'm amazed about how fast typescript features are! Thanks for that!

At first, I thought that this was something to do with the limitations of using Electron, but Visual Studio Code is also an Electron app, so it must be something else.

I've counted all the `ts` files in the project and actually it's not that many. 160 (without counting node_modules). 2956 if I count node_modules too.

My folder structure is nothing out of the ordinary:

```
project_dir
   src
      app
      assets
      vendor
   ...
   tsconfig.json
   ...
```

My `tsconfif` file:

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "strictNullChecks": false,
    "removeComments": true,
    "sourceMap": true
  },
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useBabel": false,
    "useWebpackText": true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": {
    "rewriteTsconfig": true
  },
  "files": [
    "src/app/app.module.ts",
    "src/main.ts"
  ]
}
```
