### ISSUE TITLE
File "not included in the TypeScript compilation context" error on valid tsconfig?

### ISSUE THREAD

**Issue by aseemk** [TypeStrong/atom-typescript#1132]
Hi there,

Great work overall on the plugin! I've been using it for a couple of months now and overall it's very helpful. I've just been fighting with some issues, like <https://github.com/TypeStrong/atom-typescript/issues/1054#issuecomment-260481395> and this one:

On a new project, I'm getting this error even though `tsc` does include the file in question.

Here's what my project looks like:

```
lib/
+ index.ts

test/
+ types.ts

node_modules/
+ @types/
  + ...
+ ...

package.json
tsconfig.json
...
```

Here's what my `tsconfig.json` looks like:

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "strictNullChecks": true
  },
  "exclude": [
    "node_modules",
    "!node_modules/@types"
  ]
}
```

As you notice, I _only_ specify `exclude`, not also `files` or `include`. According to the TypeScript docs, this is no problem:

> If the `files` and `include` are both left unspecified, the compiler defaults to including all TypeScript (`.ts`, `.d.ts` and `.tsx`) files in the containing directory and subdirectories except those excluded using the `exclude` property.

https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#details

The file in question that's giving me this Atom-TypeScript error is `test/types.ts`.

> The file `/path/to/test/types.ts` is not included in the TypeScript compilation context. If this is not intended, please check the `files` or `filesGlob` section of your `tsconfig.json` file.

Any ideas what might be causing this? Thanks, and keep up the great work again.

**Comment by aseemk** [comment]
Oh, I forgot to mention I'm on the ~latest version of everything at the time of writing: Atom-TypeScript 10.1.12, Atom 1.12.2, TypeScript 2.0.9, Node 6.9.1, etc.

**Comment by aseemk** [comment]
Also, I searched the existing issues far and wide for the things I'm seeing. In this case, related issues seem to be #681, #558, and maybe a couple of others, but not sure any are exactly this.

If I'm wrong, feel free to close this and merge it into an existing issue. Thank you.

**Comment by vrmerlin** [comment]
I'm seeing the identical behavior. It doesn't seem to recognize the ```include```  at all, just the ```exclude```, but then I get the same error you got.

**Comment by swinc** [comment]
Same issue here.

**Comment by spencerscarpelli** [comment]
I had this issue after re-naming a couple files, which made several import statements invalid on other files. After correcting the import statements I was still getting the errors, but when I saved and restarted Atom it was fine.

**Comment by isaacg11** [comment]
![screen shot 2016-12-07 at 12 27 56 pm](https://cloud.githubusercontent.com/assets/13204510/20985293/c0707c30-bc78-11e6-9c7c-496dd2e05d95.png)

Same issue here, I make sure to include the @types but it gives me the same error:

> The file /path/to/test/types.ts is not included in the TypeScript compilation context. If this is not intended, please check the files or filesGlob section of your tsconfig.json file.

**Comment by ibqn** [comment]
I experience the similar limitation and I find it quite annoying

**Comment by distante** [comment]
Is there no fix for this? Atom-Typescript keeps complaining that I didn't have my specs files (jasmine) in the context.

**Comment by zeves095** [comment]
are here any plan to accomplish that issue?

I have project with different files that describe same (a little different) types.
And I have trouble with it - because it add this files in my context:

/tsconfig.json
/libs
/libs/a.ts
/libs/a-alternative.ts

and I got error:
Cannot redeclare block-scoped variable 'myVar'


my tsconfig:
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": false,
        "noEmitOnError": false, <------ here other trouble with it so I just don't use it
        "strictNullChecks":false
    },
    "include": [
        "./libs/a.ts" <------ here I hope I can choose exactly what I want to use... but atom:ts add ./libs/a-alternative.ts too
    ]
}

**Comment by sjordan1975** [comment]
+1 same issue with using "include"

**Comment by guncha** [comment]
Should be fixed in the latest version (v11) 😄 Please reopen if there's an issue.
