### ISSUE TITLE
Cannot find name error | Happened randomly

### ISSUE THREAD

**Issue by HauntedSmores** [TypeStrong/atom-typescript#1142]
Atom: 1.12.5
atom-typescript: 10.1.2
angular 2 build with CLI

I know this is an ambiguous problem to diagnose but I need to try and ask.

I have installed Swiper: http://idangero.us/swiper/get-started/
 ..and its types: https://www.npmjs.com/package/@types/swiper

Everything was working great, autocompletion and type information. Then all of a sudden, litterally, I was just looking at the browser, and I look back and im getting errors "Cannot find name 'Swiper'" and other definition errors.

```
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  }
}
```

Folder structure:
root > node_modules > @types > swiper > index.d.ts
Which is untouched from: npm install --save @types/swiper

root > src > typings.d.ts
Which literally has nothing in it.

root > src > tsconfig.json
```
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  }
}



```

I uninstalled atom, removed the .atom folder, uninstalled the atom-typescript package and reinstalled, restarted PC all to no avail.

And incase anyone wants to make sure, I also believe to be implimenting the global 3rd party library installation correctly for angular 2 cli:

angular-cli.json:
```
{
    "project": {
        "version": "1.0.0-beta.17",
        "name": "wpng2"
    },
    "apps": [
        {
            "root": "src",
            "outDir": "dist",
            "assets": "assets",
            "index": "index.html",
            "main": "main.ts",
            "test": "test.ts",
            "tsconfig": "tsconfig.json",
            "prefix": "app",
            "mobile": false,
            "styles": [
                "../node_modules/bootstrap/dist/css/bootstrap.css",
                "../node_modules/animate.css/animate.min.css",
                "../node_modules/swiper/dist/css/swiper.min.css",
                "styles.scss"

            ],
            "scripts": [
                "../node_modules/jquery/dist/jquery.js",
                "../node_modules/tether/dist/js/tether.js",
                "../node_modules/bootstrap/dist/js/bootstrap.js",
                "../node_modules/swiper/dist/js/swiper.min.js"
            ],
            "environments": {
                "source": "environments/environment.ts",
                "dev": "environments/environment.ts",
                "prod": "environments/environment.prod.ts"
            }
    }
  ],
    "addons": [],
    "packages": [],
    "e2e": {
        "protractor": {
            "config": "./protractor.conf.js"
        }
    },
    "test": {
        "karma": {
            "config": "./karma.conf.js"
        }
    },
    "defaults": {
        "styleExt": "scss",
        "prefixInterfaces": false
    }
}
```

**Comment by DiegoGonzalezOrtiz** [comment]
use this, I don't know why, but work 

under the import put this line 

declare var Swiper: any;

**Comment by xiaoouLi** [comment]
I got the same issue. 
Notice that it RANDOMLY happens.
I don't use atom-typescript, but I use typescript. 
So I guess, there is probably something wrong with typescript itself???

**Comment by xiaoouLi** [comment]
Any updates so far???

Thanks!!!

**Comment by xiaoouLi** [comment]
Or... maybe ts-loader? Since I saw TypeStrong also implements ts-loader

**Comment by lierdakil** [comment]
> I don't use atom-typescript

Then you're likely asking on the wrong repo.

This issue was reported with an antique version of Atom-TypeScript, so I'm going to close it as stale. Please open new issues if you run into something similar on the latest version of Atom-TypeScript. Thanks.
