### ISSUE TITLE
Examples directory

### ISSUE THREAD

**Issue by JohnMurga** [TypeStrong/atom-typescript#115]
The example directory more than doubles the size of the package and is not required.
Furthermore, the paths in the examples directory are extremely long and cause issues on some  Windows systems (>260 char destination path).

**Comment by csnover** [comment]
Refs:

https://github.com/TypeStrong/atom-typescript/issues/92#issuecomment-74683347
https://github.com/TypeStrong/atom-typescript/issues/97

**Comment by JohnMurga** [comment]
Currently breaks Atom setup on some machines as profile cannot be copied because of atom-typescript package. I deleted the examples directory as a temp workaround and all is good.

**Comment by basarat** [comment]
Sorry for my laziness. Fixed in `v0.65.0`. I'll push the examples to another repo shortly

**Comment by basarat** [comment]
examples moved to : https://github.com/TypeStrong/atom-typescript-examples 
@csnover sorry for not doing it when you asked me the first time :heart:

**Comment by JohnMurga** [comment]
Thank you, and for your awesome package too :-)

**Comment by csnover** [comment]
> @csnover sorry for not doing it when you asked me the first time :heart:

Well I wasn’t exactly the clearest on the action to take; I didn’t want to seem demanding but I knew it was a problem waiting to happen :)
