### ISSUE TITLE
Allow live error analysis to be turned off

### ISSUE THREAD

**Issue by guidorice** [TypeStrong/atom-typescript#1154]
I may be overlooking something, but is it not possible to turn off the live error analysis? I know that some typings are not installed correctly in my project, but I still want to be able to edit without being bombarded with red bullet items and a busy status bar listing all the "errors". Thanks for any advice.

**Comment by rickydazla** [comment]
In the very bottom left corner of the Atom window > click on "File" to hide the linter

**Comment by rickydazla** [comment]
(I just discovered [how to do this](https://github.com/TypeStrong/atom-typescript/issues/699) myself by trawling thru some old issues)

**Comment by guidorice** [comment]
Nice! thanks for tip

**Comment by rickydazla** [comment]
No worries. I've been trying to debug some code with only four or five lines of it visible for the last couple of days and finally figured there _must_ be a way! :stuck_out_tongue_closed_eyes:
