### ISSUE TITLE
Object Spread: "no-unused-variable - Unused Variable: '<variable_name>'"

### ISSUE THREAD

**Issue by nickfujita** [TypeStrong/atom-typescript#1157]
When using the object spread with Redux, I am getting a warning when using the `no-unused-variable` option, which appears to be caused by the `dispatch` method within the function return. Please see an example below:

```
let firstObj = {
  a: 1,
  b: 2,
};

let secongObj = {                  // no-unused-variable - Unused Variable: 'secongObj'
  b: 3,
  c: 4,
};

start('hi');

function getThirdObj() {
  return {
    d: 6,
    e: 7,
  };
}

function start(input) {
  return (dispatch, getState) => {
    let someBoolean = !input;       // no-unused-variable - Unused Variable: 'someBoolean'

    let combinedObj = {             // no-unused-variable - Unused Variable: 'combinedObj'
      d: 5,
      ...firstObj,
      ...secondObj,
      ...dispatch(getThirdObj()),
    }

    if (someBoolean) {
      console.log(testbool, combinedObj);
    }
  }
}
```

Is this expected, and am I possibly just missing some additional typing information on the internal annon function that is now required?

**Comment by guncha** [comment]
Sounds like a `tslint` warning. Does it have a yellow label that says "Warning" ?

**Comment by nickfujita** [comment]
@guncha Thanks for checking. I did confirm that this is due to `linter-tslint` rather than `atom-typescript`. Closing.
