### ISSUE TITLE
Reference path autocompletion not working anymore.

### ISSUE THREAD

**Issue by rzvc** [TypeStrong/atom-typescript#1161]
Since the last update, /// &lt;reference path="" > stopped using autocompletion for paths.

**Comment by rathermarv** [comment]
Have also found this. Version 10.1.9 appears to be last stable version for this functionality.

**Comment by rzvc** [comment]
It looks like this functionality was removed when the autocompletion provider was rewritten.

The old one seems to have had a special case for file autocompletion, which was handled by getting all the relevant, relative paths using getRelativePathsInProject() (which is still there, but not used).

The current one is relying on tsserver to provide the autocompletion suggestions, but tsserver doesn't do that.

I wanted to add it back, but it seems that projectService.js (the file that contains getRelativePathsInProject() is heavily relying on some "transformer" file, which doesn't seem to be around anymore and neither the functions it used to expose. This is where I gave up.

If anyone wants to pick this up, please note that the importPathScopes is wrong, it says 'tripple-slash-directive' and it has to be 'triple-slash.directive' in new versions of Atom. Also, `this.disableForSelector = ".comment";` should be commented out, because the triple slash directives also gain the .comment class and that would make the autocomplete provider not work on them.

I hope this gets bumped in priority because, without it, writing relative paths by checking the tree structure is extremely difficult.

**Comment by guncha** [comment]
Thanks for looking into it, @rzvc. You're right, this is one of the things I removed during the switch to `tsserver` based completions. `getRelativePathsInProject` (sorry about the dead code, btw) relied on the internals of the compiler to get the file list which we don't have access to anymore. I also don't use triple slash directives so this was never a priority. The regular module completions work via `tsserver` though there is much to be desired.

If you or anyone is interested in implementing autocomplete for triple slash references, there's a `projectInfo` command that can return a list of all files in the project. That plus changes to the `disableForSelector` and detecting the type of completion the user is asking for in `getCompletions` would get you mostly there.

**Comment by hszhsh** [comment]
@rzvc @guncha I've added this functionality back using projectInfo.body.fileNames, and committed here: https://github.com/hszhsh/atom-typescript/commit/d82bd1dd74ee43c7a9dd7fa214dc8392a0eba2b3. Please have a review if this approach is alright. I'd like to reorganize the code and contribute to the project.

**Comment by guncha** [comment]
Thanks @hszhsh! Please open a PR and I'll review it in the next few days.
