### ISSUE TITLE
Node_modules files are suggested in autocompletion

### ISSUE THREAD

**Issue by Nilos** [TypeStrong/atom-typescript#1165]
If I enter
`import Hero from '../ser` I get autocompletions that are located in the node_modules folder.
This is disadvantageous for 2 reasons:
- I don't need those imports
- Traversing node_modules for autocompletion slows it down notably.

I could not fix the problem using:
- filesGlob
- .gitignore

Thanks in advance for any help!

**Comment by isgj** [comment]
I added `''exclude": ["node_modules/"]` to the `tsconfig.json`

**Comment by Nilos** [comment]
I have that in my tsconfig too. Does not help though :(
