### ISSUE TITLE
Deprecated selector in `atom-typescript\styles\atomts-grammar-syntax.less`

### ISSUE THREAD

**Issue by alexoparin** [TypeStrong/atom-typescript#1168]
In `atom-typescript\styles\atomts-grammar-syntax.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .source.ts .require.path,
atom-text-editor::shadow .source.tsx .require.path,
atom-text-editor::shadow .source.ts .reference.path,
atom-text-editor::shadow .source.tsx .reference.path,
atom-text-editor::shadow .source.ts .es6import.path,
atom-text-editor::shadow .source.tsx .es6import.path,
atom-text-editor::shadow .source.ts .amd.path,
atom-text-editor::shadow .source.tsx .amd.path` => `atom-text-editor.editor .syntax--source.syntax--ts .syntax--require.syntax--path,
atom-text-editor.editor .syntax--source.syntax--tsx .syntax--require.syntax--path,
atom-text-editor.editor .syntax--source.syntax--ts .syntax--reference.syntax--path,
atom-text-editor.editor .syntax--source.syntax--tsx .syntax--reference.syntax--path,
atom-text-editor.editor .syntax--source.syntax--ts .syntax--es6import.syntax--path,
atom-text-editor.editor .syntax--source.syntax--tsx .syntax--es6import.syntax--path,
atom-text-editor.editor .syntax--source.syntax--ts .syntax--amd.syntax--path,
atom-text-editor.editor .syntax--source.syntax--tsx .syntax--amd.syntax--path`

* `atom-text-editor::shadow .source.ts .keyword.debugger,
atom-text-editor::shadow .source.tsx .keyword.debugger` => `atom-text-editor.editor .syntax--source.syntax--ts .syntax--keyword.syntax--debugger,
atom-text-editor.editor .syntax--source.syntax--tsx .syntax--keyword.syntax--debugger`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by mohanrao** [comment]
What should be changed in my below atomts-grammar-syntax.less?

atom-text-editor::shadow {
    .source.ts,
    .source.tsx {
        .require.path, .reference.path, .es6import.path, .amd.path {
            text-decoration: underline;
        }
        .keyword.debugger {
            background-color: lime;
        }
    }
}

**Comment by janchan-mgie** [comment]
The following works for me

atom-text-editor {
    .syntax--source.syntax--ts,
    .syntax--source.syntax--tsx {
        .syntax--require.syntax--path, .syntax--reference.syntax--path, .syntax--es6import.syntax--path, .syntax--amd.syntax--path {
            text-decoration: underline;
        }
        .syntax--keyword.syntax--debugger {
            background-color: lime;
        }
    }
}

**Comment by yvChauhan** [comment]
hey any idea on this, i am still facing this issue

**Comment by nekonenene** [comment]
shadow selector is deprecated.

So, you change
`atom-text-editor::shadow`
to
`atom-text-editor.editor`

That's all.

**Comment by developerads** [comment]
Is anyone working on this?

**Comment by koba-ninkigumi** [comment]
See https://github.com/TypeStrong/atom-typescript/issues/1108

**Comment by sondauta2** [comment]
where?

> shadow selector is deprecated.

So, you change
atom-text-editor::shadow
to
atom-text-editor.editor

That's all.
