### ISSUE TITLE
Tsconfig.cson always created

### ISSUE THREAD

**Issue by AndrewHathaway** [TypeStrong/atom-typescript#117]
Whenever I open a folder in Atom, it automatically creates a tsconfig.cson file, no matter what sort of project. Would be good to have the option to disable it or a prompt to add one. Planning to use Atom for everything, not just TypeScript projects and this file is already getting annoying. :(

**Comment by kfranqueiro** [comment]
This sounds kind of like #105... have you tried with 0.62 or higher?

**Comment by basarat** [comment]
@AndrewHathaway extremely sorry about this. As @kfranqueiro said should be fixed. https://github.com/TypeStrong/atom-typescript/issues/105#issuecomment-75153286  please let us know if it still happens.
