### ISSUE TITLE
NPM Can't find module error

### ISSUE THREAD

**Issue by CraigglesO** [TypeStrong/atom-typescript#1172]
Using a .js npm module,
If I run the created index files, It runs correctly. But atom-typescript wont stop yelling at me.

Did I miss something in the config file?

`
{
  "compilerOptions": {
    "allowJs": true,
    "module": "commonjs",
    "target": "es5",
    "noImplicitAny": false,
    "sourceMap": true
  },
  "filesGlob": [
    "**/*.ts"
  ]
}
`

**Comment by preslavrachev** [comment]
Replace `filesGlob` with `files`

**Comment by guncha** [comment]
Yeah, there's no more `filesGlob` option. The compiler has `includes` which does the same thing. You might also be importing a plain js module using `import` syntax in which case Typescript will complain that it can't find the types for it. Either install the correct package from `@types` or update to a more recent Typescript version where it will automatically give type `any` to all imports that can be resolved to `.js` packages.

https://www.typescriptlang.org/docs/handbook/tsconfig-json.html
