### ISSUE TITLE
Property does not exist on type, for public getter on private variable

### ISSUE THREAD

**Issue by joshuaohana** [TypeStrong/atom-typescript#1173]
Atom-Typescript is showing a TS error that a property does not exist, yet it does. The property is a TS getter.

Component's code
`timeout.timer$.subscribe(...`

Service's code
`get timer$(): Observable<number> {`

Error
> Property 'timer$' does not exist on type 'TimeoutService'

Obviously everything works perfectly when compiled, but the atom-typescript error is quite annoying.

My tsconfig

```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "compileOnSave": false
}
```

**Comment by blackmantram** [comment]
I ran into this issue when I renamed a class/file and created another one with the same name. For some reason either atom or atom-typescript still thinks my renamed file is the old one. Restarting atom fixed it for me.
