### ISSUE TITLE
Template literal missing syntax highlight

### ISSUE THREAD

**Issue by pe8ter** [TypeStrong/atom-typescript#1174]
**Overview**

Template literals lose their syntax highlight when they appear on a new line after whitespace.

**Steps to reproduce**

1. Create new TypeScript file.
2. Make the text content of the file any amount of whitespace followed by any template literal (I'm having trouble reproducing template literals here).

**Expected behavior**

Template literal should have string syntax highlighting.

**Observed behavior**

Template literal has no string syntax highlighting.

**Other notes**

If the template literal is the first text on a new line or if the template literal happens after any other characters than whitespace, then the template literal correctly has syntax highlighting (see image).

<img width="299" alt="screen shot 2017-01-13 at 22 38 52" src="https://cloud.githubusercontent.com/assets/7235240/21953007/6178e556-d9e1-11e6-85c5-67075fbd59eb.png">

**Environment**

Operating system: macOS 10.12.2 (16C67)
Atom: 1.13.0 x64
Plugin: Atom TypeScript 10.1.13

**Comment by bartocc** [comment]
Also happens with the arguments of functions

![capture d ecran 2017-08-28 10 49 31](https://user-images.githubusercontent.com/47953/29766301-978439c0-8bde-11e7-9aab-b4725bde4b17.png)

**Comment by guncha** [comment]
The grammar and highlighting is provided by https://github.com/Microsoft/TypeScript-TmLanguage. This might be something they have fixed already in which case we just need to update to the latest grammar file.

**Comment by sompylasar** [comment]
Reported: https://github.com/Microsoft/TypeScript-TmLanguage/issues/527

**Comment by sompylasar** [comment]
@guncha [They say](https://github.com/Microsoft/TypeScript-TmLanguage/issues/527#issuecomment-334246328) it does not repro in the `master` of https://github.com/Microsoft/TypeScript-TmLanguage in VSCode – please regenerate the grammar for `atom-typescript`.
