### ISSUE TITLE
Cannot spawn tsserver from the 'typescript/bin' dir on Windows

### ISSUE THREAD

**Issue by chrisfarms** [TypeStrong/atom-typescript#1178]
This is an issue with the `use-tsserver` branch #1166

Currently it tries to spawn the tsserver from the dir `<project>/node_modules/typescript/bin/tsserver` ... this seemed to work fine on my linux machine, but fails on my Windows 10 box. I do not use Windows much but it looks like it does not like the shebang line.... it also looks like `npm` makes a nicer wrapper for the scripts during install at `node_modules/.bin/tsserver` which _does_ work on windows.

Possible solutions:

- change the spawn line to something like `spawn("node", [this.tsServerPath, '--'].concat(this.tsServerArgs))`
- or try to resolve to the npm installed '.bin' dir.

The latter is probably nicer.

**Comment by guncha** [comment]
Thanks, that reminds me - I should probably test it on Windows, too. VSCode does something like the former, but with the path to `node_modules/typescript/lib/tsserver.js` so that's probably as safe bet.

**Comment by guncha** [comment]
Fixed with the latest update to the `use-tsserver` branch.
