### ISSUE TITLE
Turn off TypeScript snippets or prioritize JavaScript snippets

### ISSUE THREAD

**Issue by intcreator** [TypeStrong/atom-typescript#1185]
I've been struggling with this for a while now—is there a way to add in or prioritize JavaScript snippets for things like `console.log();` and `// TODO: `?  When TypeScript is selected as the language I get autocomplete snippets that I never use, like "interface LongRange" or "var localStorage" when I type "log".  If I add `console.log();` as a custom snippet (from the Atom menu —> Snippets on macOS) it gets sent to the very bottom of that list.  How can I make it default/at the top?  Is this a feature that needs to be implemented?

**Comment by jdhines** [comment]
I have this problem too, but even with TypeScript (.source.ts) snippets, getting sent to the bottom of the list, even when they match exactly. Can this priority be changed to prefer snippets, or be a user option, or is this not even anything to do with this plugin but with autocomplete+?

Here you can see my own snippet "jit" even if typed completely, is ranked below another suggestion.
<img width="367" alt="screen shot 2017-09-15 at 11 44 21 am" src="https://user-images.githubusercontent.com/2855641/30492003-118f817a-9a0d-11e7-8714-5ab5654936c2.png">

**Comment by jljorgenson18** [comment]
At the very least, it would be nice to turn autocomplete off Atom-Typescript until this is fixed. Every time I try to log something, I end up accidentally hitting localStorage and I would rather have no Typescript snippets than lose my current snippets.

**Comment by yubaoquan** [comment]
+1 wish to be fixed as early as possible

**Comment by yubaoquan** [comment]
1. Open setting panel of `atom-typescript` package
2. Click `View Code` button to open the package code
3. Find method named `getSuggestions` in file `lib/main/atom/autoCompleteProvider.ts`
4. Add `return []` to the first line of this method

The suggestions provided by this package will never appear.

**Comment by elliotaplant** [comment]
If you still want suggestions but want to keep your snippets on top, it looks like atom-typescript added the ability to change its autocomplete suggestion priority. I'm not sure why snippets have a priority of 1, but if you change the typescript snippet priority to match that of the snippets, then your snippets will go to the top:

Settings change (used to be 3):
![image](https://user-images.githubusercontent.com/22058265/37438231-7aa417f0-27ae-11e8-8db7-fd535cf3bb74.png)

UI change (order used to be location, ..., console.log)
![image](https://user-images.githubusercontent.com/22058265/37438280-b8c9e5aa-27ae-11e8-816f-0ab6510c6b56.png)
