### ISSUE TITLE
Typescript autocomplete and diagnostics in .js files

### ISSUE THREAD

**Issue by rwatts3** [TypeStrong/atom-typescript#1194]
Greetings, 

Please forgive me if this question has already been answered or appears to be rudimentary. 
A quick search through the issues, I was not able to find a relevant issue regarding this question. 

Is it possible to somehow get typescript intelligence and code hinting inside .js files, similar to how Microsoft VS Code does. Passing jsconfig.json , allows the typescript compiler and vscode editor to provide intelligent hinting from within a .js file. 

Thank you for your time. 

Ryan.

**Comment by guncha** [comment]
Hi @rwatts3,

I'm not 100% sure how VS Code does it, but if it is, I'm assuming, basically using the Typescript compiler with `allowJs` option, then it could be possible, but not without some significant refactoring. There's also the question of how to play nicely with other JS plugins the user might have..

I'll keep this issue open to track this as it would be an interesting feature for projects that mix Typescript and Javascript, but I wouldn't expect to see any progress for some time.
