### ISSUE TITLE
variable @scrollbar-background-color is undefined

### ISSUE THREAD

**Issue by rcollette** [TypeStrong/atom-typescript#120]
Getting this error when switching themes

.atom\packages\atom-typescript\stylesheets\documentationview.less
Line number: 33
variable @scrollbar-background-color is undefined

**Comment by basarat** [comment]
Happens if the UI theme is `Atom Light`.  Does not happen for `Atom Dark`

**Comment by basarat** [comment]
Happens because the `light` theme *doesn't* style the scrollbars: 

![image](https://cloud.githubusercontent.com/assets/874898/6321818/c9359b96-bb5a-11e4-9d14-990361ce78ad.png)

**Comment by basarat** [comment]
Fixed in `v0.66.0` Thank for trying + raising this issue!
