### ISSUE TITLE
Outdir treated different for tsc and atom-typescript

### ISSUE THREAD

**Issue by timhurkmans** [TypeStrong/atom-typescript#1202]
When using the following project structure
```
src
└── index.ts
tsconfig.json
```

with `tsconfig.json`:
```
{
    "compilerOptions": {
        "outDir": "target"
     }
}
```

then `tsc -p tsconfig.json` produces:
```
target
└── index.js
```

but atom-typescript produces on save:
```
target
└── src
    └── index.js
```

`tsc -v`
Version 2.1.4
atom-typescript: 10.1.14 (uses tsc v2.1.4 accodring to package.json)

I want to get rid of the target/src dir and just have my index.js file in target/. The tsc compiler does this for me, but atom-typescript does not.

**Comment by lzj1989712** [comment]
I have this issue too ,

**Comment by guncha** [comment]
Should be fixed with the newest version. Please open a new issue if it persists.

**Comment by runartrollet** [comment]
I have the same issue with Atom 1.18.9, atom-typescript 11.0.6 and tsc 2.4.1
