### ISSUE TITLE
Ignoring errors.

### ISSUE THREAD

**Issue by jerome724** [TypeStrong/atom-typescript#1214]
I have one ``.ts`` file which isn't included in my ``tsconfig.json``, since i compile this file with gulp. Now i'm getting always an error that this file isn't included in my ``tsconfig.json`` and if this is not intended i should check my ``tsconfig.json``.

Is it possible to ignore this error somehow?

**Comment by senyaak** [comment]
Not best what u can do but it works:
Include this file in tsconfig.json and use an another tsconfig.json where this file is excluded for gulp

**Comment by jerome724** [comment]
Well that workaround did it, thanks!

**Comment by guncha** [comment]
The plugin also now supports the `extends` directive in the `tsconfig.json` files so that makes it even easier to have separate config files for different parts of the project, but still share the some of the configuration.
