### ISSUE TITLE
After latest update to 11.0.1 Exported members / namespaces fail

### ISSUE THREAD

**Issue by danlsimplesite** [TypeStrong/atom-typescript#1224]
Maybe I'm doing something wrong (hope that's it). 

Using F12 / <SHIFT> + F12 all the time, and can't anymore, so any help is highly appreciated :)

![image](https://cloud.githubusercontent.com/assets/13620460/24393775/aa62d870-1399-11e7-8d0e-4295908fd3ca.png)

**Comment by Nandan108** [comment]
Same here.
11.0.0 introduces this issue: many "cannot find module xyz" linter errors, notably with node_modules but with some others as well.

![image](https://cloud.githubusercontent.com/assets/354944/24445525/78a61924-146a-11e7-8155-80b936b7fb3e.png)

Ah, I just found out that although importing `from '../brand'` no longer works, importing `from '../brand/index'` still works fine. But this fix doesn't work on node_module imports. 

In the meantime, the previous version (`apm install atom-typescript@10.1.15`) is working just fine for me.

**Comment by Nandan108** [comment]
@danlsimplesite try adding `"moduleResolution": "node"` under compilerOptions in your tsconfig.json.
This worked for me.

**Comment by guncha** [comment]
Module resolution is done entirely by Typescript since `11.0.0` so check your `tsconfig.json` settings. The suggestion @Nandan108 gave is probably what you're looking for.
