### ISSUE TITLE
Just stop working at all

### ISSUE THREAD

**Issue by mohitook** [TypeStrong/atom-typescript#1228]
Hello, 
Sorry, I have just a few details, but I've just started my Atom today and this comes to my screen:
![image](https://cloud.githubusercontent.com/assets/15103326/24469159/e9433324-14ba-11e7-83e3-b5286bc54f61.png)

Could you say something? Last time I've used my Atom it was open for a long time, but right now it just won't work with angular2, I mean typescript files and it really piss me off :( ..

Anyone else has the same bug? What should I do to make it work again?

Thanks, and sorry again.. as I remember I didn't do anything with atom.. it was maybe an npm update.. but should it relate this bad?!!

**Comment by mohitook** [comment]
Addotional information:
I have uninstalled and then installed it again... working fine till I close ATOM and reopen it.. now I have the same issue.. so it is working still you close the editor? :)

**Comment by sebilasse** [comment]
@mohitook All I can say: It is the same here !
For me it stopped working after I updated `linter-ui-default`.
@basarat

**Comment by guncha** [comment]
Any output in the console? If the syntax highlighting is not working, the plugin must not even be  enabled. Please also make sure you have `Typescript` or `TypeScriptReact` selected as the file type in the bottom right of the editor.

**Comment by sebilasse** [comment]
@guncha It just does not compile anymore. `Typescript` selected of course. 
It says "Emit failed" ...

**Comment by guncha** [comment]
@sebilasse that's a different issue then from plugin no loading at all. Please open the console (Cmd+Option+i or Ctrl+Alt+i) and take a screenshot.

**Comment by sebilasse** [comment]
@guncha Ups - Showing 2 of thousands ;) :

<img width="531" alt="bildschirmfoto 2017-03-30 um 19 26 33" src="https://cloud.githubusercontent.com/assets/750300/24517522/f7d575c2-157e-11e7-9653-ee01d626986d.png">

**Comment by guncha** [comment]
@sebilasse time to update Typescript to at least 2.0. I'll think about adding some minimum Typescript version warning when starting up.

**Comment by mohitook** [comment]
@guncha I have updated everything and reinstalled the linter too.. it seems that it is working now!

**Comment by sebilasse** [comment]
@guncha But it is already `Version 2.1.4` (?) - trying to reinstall anything now ...

**Comment by sebilasse** [comment]
@guncha Did not work. I guess it is an issue with the tsconfig which I am pasting here:

```
{
	"version": "2.0.2",
	"compileOnSave": true,
	"compilerOptions": {
		"declaration": false,
		"diagnostics": true,
		"experimentalDecorators": true,
		"emitDecoratorMetadata": true,
		"module": "umd",
		"noImplicitAny": true,
		"outDir": "_build/",
		"baseUrl": "./_build/src",
		"removeComments": false,
		"sourceMap": true,
		"target": "es5",
		"moduleResolution": "node"
	},
	"filesGlob": [
		"**/*.ts",
		"**/*.tsx",
		"!node_modules/**"
	],
	"atom": {
		"rewriteTsconfig": true
	},
	"files": [
		"src/API/main.ts",
		// ...
	]
}

```

**Comment by guncha** [comment]
You would only get `"Unknown compiler option 'compileOnSave'."` error if you put the `compileOnSave: true` option inside the `compilerOptions` hash. It's fine as you've pasted it. Btw, you can get rid of `filesGlob`, `atom` and `files` options. Typescript will by default include all Typescript files in the project directory and exclude `node_modules`, `bower_components`, etc. I tried a project with your config and `2.1.6` and it compiled ok.

**Comment by sebilasse** [comment]
btw: I knew that `compileOnSave` is a root option but the error was there ...

<img width="692" alt="bildschirmfoto 2017-03-31 um 18 09 15" src="https://cloud.githubusercontent.com/assets/750300/24565345/2f0c255a-1655-11e7-8689-0fb789aad08d.png">

@guncha I am sorry - it worked fine for years ...
Now - after deleting the oldschool options and upgrading node + TS to @latest I get the follow :

<img width="547" alt="bildschirmfoto 2017-03-31 um 21 08 18" src="https://cloud.githubusercontent.com/assets/750300/24565649/6a246958-1656-11e7-954f-725a24492a06.png">

In include it reads 
```
"**/*.ts",
"**/*.tsx"
```

**Comment by guncha** [comment]
The `Missing filePath..` error is fine, it just means `atom-typescript` doesn't recognize the file you have open.

**Comment by sebilasse** [comment]
@guncha I see. It is solved no - I think somehow the typescript update before was not successful -
I had to 
1. https://discuss.atom.io/t/error-eacces-permission-denied/3915
2. `sudo chown -R `whoami` ~/.atom`
3. update npm but with `rm -rf /usr/local/lib/node_modules/npm/node_modules/rimraf/node_modules`
to fix another error, see http://stackoverflow.com/questions/34960538/npm-cannot-find-module-minimatch

now everything is tippy toppy ;)

The whole thing had nothing to do with atom-typescript in the end and so : sorry for the confusion ...
