### ISSUE TITLE
Enable sourcemaps

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#123]
These will get checked in.
Update `tsconfig.json` + grunt.

**Comment by basarat** [comment]
A simple flick of `tsconfig.json` doesn't cut it. Atom does some fancy js loading that breaks TS sourcemaps.

**Comment by johnnyreilly** [comment]
I was just about to raise an issue saying that sourcemaps  don't seem to be being generated despite my settings:

```
{
    "compilerOptions": {
        "target": "es5",
        "module": null,
        "declaration": false,
        "noImplicitAny": true,
        "removeComments": false,
        "noLib": false,
        "sourceMap": true
    },
    "filesGlob": [
        "./**/*.ts",
        "../scripts/typings/**/*.d.ts",
        "!../scripts/typings/angularjs/angular-mocks.d.ts"
    ],
    "files": [
        // ...
    ]
}
```

Looks like you already have it in hand though!

**Comment by basarat** [comment]
@johnnyreilly sourcemaps from settings works. Just pused an example: https://github.com/TypeStrong/atom-typescript-examples/commit/c442a5cbf760eb1806988f2eb3f379467e7b13ef

The settings you have posted is invalid in that `module:null` is invalid. If you don't want to specify the `module` just remove it:

```json
{
    "compilerOptions": {
        "target": "es5",
        "declaration": false,
        "noImplicitAny": true,
        "removeComments": false,
        "noLib": false,
        "sourceMap": true
    },
    "filesGlob": [
        "./**/*.ts",
        "../scripts/typings/**/*.d.ts",
        "!../scripts/typings/angularjs/angular-mocks.d.ts"
    ],
    "files": [
        // ...
    ]
}
```

This issue is for getting sourcemaps working inside atom so that we see *.ts files instead of *.js files inside *our atom-typescript* code. :heart:

**Comment by basarat** [comment]
@johnnyreilly added an issue to track better error reporting for tsconfig : https://github.com/TypeStrong/atom-typescript/issues/138 Probably after I am done with the panels work

**Comment by johnnyreilly** [comment]
Ah I see - without module: null we're getting sourcemaps as expected.  Thanks!  :+1: 

I don't know if it's related but the `format` doesn't seem to be having any effect. Doesn't matter what I put in - it's ignored.  Shall I raise that as a separate issue?

```
{
    "compilerOptions": {
        "target": "es5",
        "declaration": false,
        "noImplicitAny": true,
        "removeComments": false,
        "noLib": false,
        "sourceMap": true
    },
    "filesGlob": [
        "./**/*.ts",
        "../scripts/typings/**/*.d.ts",
        "!../scripts/typings/angularjs/angular-mocks.d.ts"
    ],
    "format": {
        "indentSize": 10,
        "tabSize": 10,
        "newLineCharacter": "\r\n",
        "convertTabsToSpaces": true
    },
    "files": [
        //
    ]
}
```

**Comment by basarat** [comment]
hopefully covered by https://github.com/atom/atom/pull/5898 soon
