### ISSUE TITLE
Hyperclick support

### ISSUE THREAD

**Issue by andreasonny83** [TypeStrong/atom-typescript#1234]
Not sure why but the `cmd+click` shortcut used to work for me on Atom time ago with [atom-hyperclick](https://github.com/facebooknuclide/hyperclick) installed but now doesn't seem to work any more.
It would be great if I can jump to my Tytpescript declarations just with `cmd+click` instead using `fn+F12` from keyboard.

Thanks

**Comment by olee** [comment]
This happened to me as well, after updating to the new atom-typescript v11.
If you go back to the latest v10 release, it works again.

I guess I will wait with updating, until this and quickfix work again.

**Comment by andreasonny83** [comment]
It's working again with the latest Atom version (1.16)

**Comment by sverrejoh** [comment]
@andreasonny83 Does it work for you still? Did you have do do something special to get it to work? On my machine it does not work.

**Comment by guncha** [comment]
This should still be an open issue since there's no hyperclick support in the newest version.

**Comment by andreasonny83** [comment]
@sverrejoh, I notice that using `Cmd + F12` with the `atom-typescript` plugin works better than `Cmd + click` with `Hyperclick`. However, in order to use the hyperclick feature, I think you still need to install the `goto` and `goto-definition` plugins on top of `Hyperclick`

**Comment by guncha** [comment]
This is probably a question of taste. I prefer Cmd + F12 too, but other people have told me that they prefer to use mouse for this. Since the hyperclick provider barely adds any overhead, I think we can easily have both.

**Comment by sverrejoh** [comment]
I agree keyboard shortcut is usually nicer (I remap it as I don't have a  F12 button on my keyboard), but I'm used to cmd+click from using FlowType, and I kind of like it too.

I see! it works together with goto-definition. I'll try that if I'm not able to get the old build in code to work again. Thank you!

**Comment by sompylasar** [comment]
'Go to declaration' works for me in `atom-typescript@11.0.4` via `hyperclick` configured for `option+click` (non-default) on macOS. Just checked, `cmd+click` can also be used if configured in `hyperclick` settings. Looks like https://github.com/TypeStrong/atom-typescript/pull/1265 is a success here. https://github.com/TypeStrong/atom-typescript/compare/v11.0.3...v11.0.4

**Comment by pingshunhuangalex** [comment]
It stops working on Atom 1.21.0-beta1. Has this change been implemented yet?

**Comment by bhperry** [comment]
Can fix this by using your own keymap. In atom-typescript deselect 'Enable' under keybindings. 
Then past this in your key map:

`#typescript keymap`
`'atom-workspace atom-text-editor:not([mini])[data-grammar^="source ts"]':`
`   'alt-cmd-l': 'typescript:format-code'`
`   'ctrl-alt-l': 'typescript:format-code'`
`   'ctrl-;': 'typescript:context-actions'`
`   'cmd-;': 'typescript:context-actions'`
`   'f2': 'typescript:rename-refactor'`
`   'shift-f12':	'typescript:find-references'`
`   'ctrl-shift-M':	'typescript:output-toggle'`
`   'shift-cmd-M':	'typescript:output-toggle'`

`'atom-workspace':`
`   'f6':	'typescript:build'`
`   'f10':	'typescript:return-from-declaration'`
`   'cmd-mousedown':	'typescript:go-to-declaration' . # <-- the critical change`
`   'ctrl-':	'typescript:sync	atom-workspace'`
`   'cmd-':	'typescript:sync'`

Need to tab in everything under `'atom-workspace atom-text-editor:not([mini])[data-grammar^="source ts"]':`, and `'atom-workspace':`

Markdown doesn't support that for whatever reason

**Comment by lierdakil** [comment]
Tested just now. `ctrl`+`click` works with `atom-ide-ui` v0.7.1 and `atom-typescript` v12.0.0 on Atom v1.23. Please open new issues if it doesn't.
