### ISSUE TITLE
TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by nycdotnet** [TypeStrong/atom-typescript#124]
I was creating a comment reference and while I was typing it correctly, I started getting the below error.  I wonder if there is any way to suppress this error while I'm in the process of typing.  I wouldn't mind the error if I switched to a new line or navigated away.  (Note the error actually popped up before I typed the second double-quote).

![atom-ts-referenceerror](https://cloud.githubusercontent.com/assets/3755379/6361126/8f4b4ab8-bc4d-11e4-9388-35135e21c35c.png)

**Comment by nycdotnet** [comment]
And actually when I deleted that reference the red circle stayed and when I did CTRL+SHIFT+B I got this:

![bombafterbadreference](https://cloud.githubusercontent.com/assets/3755379/6361239/63b0d890-bc4e-11e4-83fd-409a3a48e81c.PNG)


```
TypeError: Cannot read property 'path' of undefined
  at [object Object].LineMessageView.goToLine (C:\Users\sognibene\.atom\packages\atom-typescript\node_modules\atom-message-panel\lib\LineMessageView.js:51:58)
  at HTMLPreElement.<anonymous> (C:\Users\sognibene\.atom\packages\atom-typescript\node_modules\atom-message-panel\node_modules\space-pen\lib\space-pen.js:214:36)
  at HTMLPreElement.jQuery.event.dispatch (C:\Users\sognibene\.atom\packages\atom-typescript\node_modules\atom-message-panel\node_modules\space-pen\vendor\jquery.js:4676:9)
  at HTMLPreElement.elemData.handle (C:\Users\sognibene\.atom\packages\atom-typescript\node_modules\atom-message-panel\node_modules\space-pen\vendor\jquery.js:4360:46)
```

**Comment by basarat** [comment]
> I wonder if there is any way to suppress this error while I'm in the process of typing 

We want errors to show up as quickly as possible. You don't want the resharper experience of .... waiting for the LS to tell you what might be wrong. Consider the case where you are experimenting with code: you want it to give you an error as soon as you are done experimenting.

You can however change this from the linter settings.

![Uploading image.png . . .]()

**Comment by basarat** [comment]
> I did CTRL+SHIFT+B I got this:

I think you also clicked on the error results in the build view. Clicking on those *used to* give this error. See :  https://github.com/TypeStrong/atom-typescript/issues/98 specifically : https://github.com/tcarlsen/atom-message-panel/issues/66#issuecomment-74972787 

It was supposed to be fixed since `v0.61.0` because of https://github.com/TypeStrong/atom-typescript/commit/ac3ca29a8ff1c2c1726a208b93d9d71c87b5726c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L29 can you check which version of `atom-message-panel` you have in your `atom's packages/atom-typescript/node_modules/atom-message-panel/package.json`?

**Comment by basarat** [comment]
@nycdotnet close this if my answer's are satisfactory :heart:

**Comment by nycdotnet** [comment]
I have 1.2.2 referenced in the `atom-message-panel\package.json`, so it appears that perhaps this is still happening.  Does that mean that I should not have experienced this error?  I'll mess around with it more today.

Regarding not wanting to have a Resharper "wait for it.... OK!" or "wait for it.... You're wrong!" experience, I *agree* with that goal.

That said, I don't like the user experience of being actively told I'm doing something wrong while I am in the process of typing something correctly.  For example, if I were typing "apple" in MS Word, the spell checker doesn't yell at me as I'm typing appl and then say "oh fine" after I put the e - it's only after I've given some indication that I'm done that the spell checker evaluates what I've typed (or at least it waits to show me the feedback).  I wouldn't even have a problem with it if I typed `///<deference` with a typo or something.  Just my opinion, so please take this as constructive criticism.

Thanks Bas.

**Comment by basarat** [comment]
> so it appears that perhaps this is still happening.

What version of atom do you have? Can you run the following two commands : 

`atom.project.rootDirectory.path` vs `atom.project.rootDirectories[0].path`

Mine: 

![image](https://cloud.githubusercontent.com/assets/874898/6381766/e2fab46e-bd97-11e4-8b1f-70e47e0c2727.png)

Note : versions of atom before `0.180.0` had an unreliable auto updater on windows (from experience). Solution is to uninstall and download the latest and install. My version right now is `0.182.0`.

**Comment by basarat** [comment]
@nycdotnet  Moved the agressive error discussion here so it can outlive the other bug we are discussing here :heart:

**Comment by basarat** [comment]
If you have the latest atom version (>0.183.0) and its still not fixed. Feel free to open it :heart:
