### ISSUE TITLE
Autocomplete should also fill out the arguments I will need for my functions

### ISSUE THREAD

**Issue by Goodwine** [TypeStrong/atom-typescript#1240]
Imagine I have `function objectValue(obj: SomeObject)`, whenever I type `objectVal` and press <kbd>CTRL</kbd>+<kbd>Space</kbd>, I am expecting an IDE-like autocompletion where the parameters are pre-filled out for me.

(Is this a limitation in atom/autocomplete?)

This is the current behavior, perhaps it's not very obvious, but I'm struggling trying to make something appear, hitting the keys for autocompletion, but nothing happens:
![autocomplete-not-good-enough](https://cloud.githubusercontent.com/assets/2022649/24792749/25619f1a-1b34-11e7-9ef2-64755003ca17.gif)

I wish autocomplete had filled `i.objectValue(obj: SomeObject)` for me.

**Comment by bekicot** [comment]
@Goodwine This is a duplicate for #608.

Couldn't agree more that this feature is very helpful!

**Comment by Goodwine** [comment]
You are right, thanks!
