### ISSUE TITLE
Angular 4 : tsconfig file not detected

### ISSUE THREAD

**Issue by mandisdv** [TypeStrong/atom-typescript#1241]
When I updated my project to Angular 4, I had to rename tsconfig.json to tsconfig.app.json. Since atom-typescript no longer detects it.

Thanks.

**Comment by giorgiopiatti** [comment]
I confirm the issue, it happens also to me. Renaming the file resolve the problem.

**Comment by guncha** [comment]
Do you have an example project where this happens? Is `tsc` able find the config with the `tsconfig.json` name?

**Comment by riccardopietropala** [comment]
I confirm the issue, atom-typescript detects only ./tsconfig.ts in root directory and not loads src/tsconfig.app.ts. It would extend the first.
