### ISSUE TITLE
Turning on "allowJs" in tsconfig.json makes Atom not use types from node_modules/@types any more

### ISSUE THREAD

**Issue by cntech** [TypeStrong/atom-typescript#1249]
The following typings are installed:

```
node_modules/@types/jquery
node_modules/@types/kendo-ui
```

They work well, but as soon as I add the `allowJs` compiler option and set it to `true`, types from those directories are not found any more.

**Comment by guncha** [comment]
Do you get the same errors when running `tsc` from command line?

**Comment by cntech** [comment]
I run `tsc` through `webpack` and it works as expected. No complaints.

**Comment by guncha** [comment]
I think you're using one of the Typescript loaders and they do some things differently `tsc`. Did you try specifying the `types` property in `tsconfig.json`? Also what do you mean, not found? Are the imports typed as `any` or something else?

**Comment by cntech** [comment]
> I think you're using one of the Typescript loaders and they do some things differently `tsc`

I don't think so. `allowJs` is officially documented: https://www.typescriptlang.org/docs/handbook/compiler-options.html

The `types` property is not required. I am working on several TypeScript projects (using Atom), and none of them requires mit to add the `types` property.

It is just the interference with `allowJs` which makes `atom-typescript` struggle.

> Also what do you mean, not found?

Many error messages like "Cannot find name 'JQuery'". As soon as I disable the `allowJs` option, all error messages disappear.

The `tsconfig.json` file is 100% since the Webpack TypeScript loader (which uses `tsc` internally) does not complain.

**Comment by guncha** [comment]
Do you mind uploading a minimal repo where you're seeing this issue? I could take a look at it and have something to test against.

**Comment by cntech** [comment]
I wrote a minimal project with a similar `tsconfig.json` file, a main file named `app.js`, a TypeScript class with `JQuery` and `kendo` (which is required in `app.js`) and a JavaScript class (which is used in the TypeScript class). In this project, the error messages do not appear.

There must be some interaction with something else.

**Comment by cntech** [comment]
Btw it happens with VS Code as well.

**Comment by ryanolsonx** [comment]
If it happens in VS Code as well there might be an issue with how you set things up.
