### ISSUE TITLE
Upgrade Error

### ISSUE THREAD

**Issue by nycdotnet** [TypeStrong/atom-typescript#125]
Upon trying to install v0.69.0, I got this error.

The output is this:

````
EPERM, unlink 'C:\Users\sognibene\.atom\packages\atom-typescript\binNode\iojs.exe'
````

Is it trying to delete this file?

Note that I do have VS 2013 Update 4 installed on this computer but not Python.

The hyperlink takes me here: https://atom.io/docs/latest/build-instructions/windows

Should this be required?  I'm assuming it's just an oddball explanation.

![upgradetov0 69 0](https://cloud.githubusercontent.com/assets/3755379/6361359/8e75d7aa-bc4f-11e4-9abd-6ea06ab213dc.PNG)

**Comment by basarat** [comment]
> Is it trying to delete this file

yes. Sorry. Just run `tskill iojs`. Its no longer required. 

> Compiler tools not found

These are not required. The error is misleading

**Comment by basarat** [comment]
@nycdotnet added clear guidance. Again, sorry for this.
