### ISSUE TITLE
Doesn't show typescript status bar anymore

### ISSUE THREAD

**Issue by surazzarus** [TypeStrong/atom-typescript#1251]
It was working fine but now the typescript status bar is not showing and also doesn't recognize the error on my code.

**Comment by Drabc** [comment]
Is not recognizing errors for me as well

**Comment by guncha** [comment]
Please try to be a little more detailed so I can help you. What version of atom-typescript are you using? Atom version? OS version? Are there any messages in the console? Does it work again if you restart Atom and then stop working again?

**Comment by Drabc** [comment]
atom-tyscript: 11.0.3
atom : 1.13.1 x64
OS: Fedora 25
There are no errors in the console
restarting does not fix the problem

It was working for me two days ago. I have not made any changes or applied any updates to my knowledge

**Comment by surazzarus** [comment]
atom-typescript 11.0.3  
atom 1.16.0
OS: macOS Sierra 10.12.4

No errors in the console. I tried reinstalling atom-typescript, still didn't work.

**Comment by Drabc** [comment]
I was able to fix the issue by renaming my .atom and installing all packages back.

**Comment by surazzarus** [comment]
@Drabc Could you please elaborate a little? I didn't understand exactly. Thank you :)

**Comment by Drabc** [comment]
@surazzarus sure :) Atom will install your packages and all your user settings in your user directory. The folder is called ```.atom``` If you rename it (or delete it if you don't care about your settings), you would have a "new" atom setup. This is in case some of the settings or even cache data was corrupted. You could then install your packages again.

You can also just try to rename the packages folder (inside the .atom folder) and install atom-typescript again. This way you can preserve your settings. If this doesn't work, then try the above approach.

**Comment by surazzarus** [comment]
@Drabc Thanks for the instruction
