### ISSUE TITLE
`Dependency view` option removed?

### ISSUE THREAD

**Issue by mrdulin** [TypeStrong/atom-typescript#1252]
atom: 1.16.0
system: osx
atom-typescript: 11.0.3

**Comment by sompylasar** [comment]
Last time available in `v10.1.15` https://github.com/TypeStrong/atom-typescript/blob/v10.1.15/docs/dependency-view.md

Functionality removed in and around this commit: https://github.com/TypeStrong/atom-typescript/commit/46f6e052653149ea6267f6d7e5e6b34b31a2ae8e

Somewhere within this range of commits: https://github.com/TypeStrong/atom-typescript/compare/v10.1.5...v11.0.0

The package README https://atom.io/packages/atom-typescript says:
> **NOTE**: This branch contains a major rewrite (**v11**) of the atom-typescript plugin that is lighter and faster, but lacks a few major features that you might miss. The previous version is still available in the `legacy` branch and will continue to receive minor bugfixes, but I wouldn't count on any new developments.

https://github.com/TypeStrong/atom-typescript/tree/legacy

**Comment by sompylasar** [comment]
On a related note, I found this TS dependency visualizer prototype, which, although very rough, might be interesting to someone:
- https://github.com/SpyR1014/ts-depDraw
- https://github.com/SpyR1014/ts-depDraw-front
- https://andrewjakubowicz.me/post/postmortem-tsdepdraw.html
