### ISSUE TITLE
Assign "Go To Declaration" to Ctrl + Click

### ISSUE THREAD

**Issue by josh18** [TypeStrong/atom-typescript#1253]
Is it possible to make the "Go To Declaration" method fire when your Ctrl + Click on a reference?

If not, is it possible to add this as a feature?

**Comment by sverrejoh** [comment]
Hyperclick should provice this, and atom-typescript supposedly has support, but I'm not able to get it to work. #1234 is marked as resolved, but it seems like it might have broken.

**Comment by guncha** [comment]
That's right, we had support for it, but it got lost in the shuffle when switching to the new compiler API. It should be pretty easy to add it back again - it just needs some plumbing to connect the hyperclick provider with the `go-t-declaration` command. If someone wants to take a stab at it, I'll gladly review the PR.

**Comment by sverrejoh** [comment]
@guncha I created a PR for it, doing the same as in `go-to-declaration`. Not sure if there's a nice way to nicely unify the code in the two files, but this works at least.

**Comment by sverrejoh** [comment]
I fixed some issues and updates the pull request. 

https://github.com/TypeStrong/atom-typescript/pull/1265

**Comment by sompylasar** [comment]
'Go to declaration' works for me in `atom-typescript@11.0.4` via `hyperclick` configured for `option+click` (non-default) on macOS. Just checked, `ctrl+click` can also be used if configured in `hyperclick` settings. Looks like https://github.com/TypeStrong/atom-typescript/pull/1265 is a success here. https://github.com/TypeStrong/atom-typescript/compare/v11.0.3...v11.0.4
