### ISSUE TITLE
tsserver crashed at OS level

### ISSUE THREAD

**Issue by ZuBB** [TypeStrong/atom-typescript#1255]
just got this today

![screen shot 2017-05-10 at 19 21 12](https://cloud.githubusercontent.com/assets/597016/25910227/55936904-35b8-11e7-8655-c6c1c5609e4a.png)

![screen shot 2017-05-10 at 19 22 20](https://cloud.githubusercontent.com/assets/597016/25910270/77453afa-35b8-11e7-83cc-b8faf1afaf9f.png)

https://gist.github.com/ZuBB/f3f6074de207fdd4b1353c4bba3e38b5

I am not sure if we can get something from this but I believe we should have everything logged

**Comment by guncha** [comment]
Thanks for reporting! Yeah, not sure what can be done about this now, but let's see if other people are having similar issues.

**Comment by ZuBB** [comment]
got one more crash on same? subject https://gist.github.com/ZuBB/41111cf4b96cb164dcf5bd3608f8339b

**Comment by guncha** [comment]
Looks like an OOM (out of memory) error. You might have a better luck with a newer (or older) compiler version.

**Comment by ZuBB** [comment]
one crash but with different? msg

```
Typescript quit unexpectedly
Last output from tsserver:
node::Abort() [/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 2: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 5: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 6: v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, v8::internal::JSMapIterator, 2>::EnsureGrowable(v8::internal::Handle<v8::internal::OrderedHashMap>) [/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 7: v8::internal::Runtime_MapGrow(int, v8::internal::Object**, v8::internal::Isolate*) [/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 8: 0x2a04b2a084e7
 9: 0x2a04b3e2000a
 
```

**Comment by guncha** [comment]
It's still an OOM error. Does it happen after you've been working for a while? Unless we're doing something bad like not closing files (which we are), this is a `tsserver` issue. If you're up for a good time, you can modify `atom-typescript` to pass `--inspect` to the `tsserver` process, connect to it with a debugger and poke around what's causing the memory bloat.

**Comment by ZuBB** [comment]
ok, sorry for a kind of dup

**Comment by ZuBB** [comment]
hi there.

I think we have some good news for this. imo this is being caused by this https://github.com/Microsoft/TypeScript/issues/14628.

in ts repo there are couple of bug reports on same subject, but this seems to have most details and caused lots of investigation. although solution is still not found

**Comment by lierdakil** [comment]
For posterity:
Basically, the resolution seems to boil down to https://sandersn.github.io/manual/Workarounds-for-Out-of-Memory-Crashes.html, and if that doesn't help, file an issue on https://github.com/Microsoft/TypeScript
