### ISSUE TITLE
Format on save

### ISSUE THREAD

**Issue by denis-sokolov** [TypeStrong/atom-typescript#1259]
#1243 has fixed picking up formatting options, which is great. But there is still no option to format the file on every save. It’d be great if it returned.

**Comment by xiaobaker** [comment]
+1

**Comment by abram-zhao** [comment]
+1

**Comment by lierdakil** [comment]
I personally use https://atom.io/packages/prettier-atom and am quite happy with it. Typescript's built-in formatting leaves a lot to be desired. That's not to say the feature request is declined, I'm just suggesting a band-aid one could use in the meantime.
