### ISSUE TITLE
Losing keystrokes in atom 1.17.0

### ISSUE THREAD

**Issue by ericeslinger** [TypeStrong/atom-typescript#1260]
I updated to atom 1.17.0 this evening, using atom-typescript 11.0.3

It seems like, once in a while, the autocomplete popup eats keystroke events. I'll be typing out an identifier name like `const foo: ThingConstType = {}`, but what will actually show up in atom is `const foo: ThonstType = {}` - the popup window appears after I type Th, and somewhere in there the system loses `ingC` before it starts taking inputs again.

It is intermittent, and I'm working on reproducing it. I can say that I haven't repro'd it at all outside of a typescript context, so it feels at least a bit like a typescript interaction. Typescript definitely has the heaviest autocomplete popup of all my atom.io languages.

**Comment by ericeslinger** [comment]
hmm, it's quite possible that this is not related to the package at all - shortly after filing this issue my entire laptop crashed. might just have been unrelated. I won't close this right away, in the event someone else experiences this, as it is a new version of atom that apparently has a keyboard focus regression.

**Comment by christianmesch** [comment]
I have experienced the same issue since updating this morning, so you're not alone in this.

**Comment by RafaelKr** [comment]
I have the same problem.
