### ISSUE TITLE
Type information hover covers linter-typescript messages

### ISSUE THREAD

**Issue by granteagon** [TypeStrong/atom-typescript#1267]
When hovering a linter error the type information hovers over it so you can't see the linter error below.  Would be nice to be able to:

![image](https://cloud.githubusercontent.com/assets/133823/26511927/1bf8152e-4232-11e7-85b3-4d7901ae6b74.png)

1. Toggle type information hover with a command
2. Toggle type information hover with a setting
3. Not cover linter errors

**Comment by Ky6uk** [comment]
Can we just add an option for disabling hover messages like that?

**Comment by granteagon** [comment]
Would probably be better to use a list concept like this:
![image](https://user-images.githubusercontent.com/133823/28221000-9745f02e-688f-11e7-84dd-7dc2c521ae82.png)
