### ISSUE TITLE
Not displaying errors

### ISSUE THREAD

**Issue by fishcharlie** [TypeStrong/atom-typescript#1269]
Atom displays the following:

<img width="1440" alt="screen shot 2017-05-31 at 3 17 10 am" src="https://cloud.githubusercontent.com/assets/860375/26624963/dc17568c-45af-11e7-898c-a2b5aaacd125.png">

When Visual Studio Code displays the following:

<img width="1440" alt="screen shot 2017-05-31 at 3 16 53 am" src="https://cloud.githubusercontent.com/assets/860375/26624964/dd9906c2-45af-11e7-87d3-990beecf1d01.png">

This is all for the exact same file. Is there a way to enable those errors to be displayed in Atom? I believe this is a TypeScript feature so I'm surprised it isn't displaying. Am I just doing something wrong?

**Comment by sebilasse** [comment]
@fishcharlie It seems this repo has issues with the linter now. See also this issue https://github.com/atom/atom/issues/14699
