### ISSUE TITLE
Changes required due to TextBuffer.save becoming async in Atom 1.19

### ISSUE THREAD

**Issue by maxbrunsfeld** [TypeStrong/atom-typescript#1273]
Hi! Thanks for maintaining the atom-typescript package!

In Atom v1.19, we will release a [major change](https://github.com/atom/atom/pull/14435) to Atom's core text buffer data structure. As part of this change, we have made `TextBuffer.save` asynchronous; rather than blocking until the save is complete, it now immediately returns a `Promise` that *resolves* when the save is complete. Because of this, a few other Atom APIs that *use* `save` have similarly become async:

* `Pane.close`
* `TextBuffer.save`
* `TextEditor.save`
* `Pane.saveItem`
* `Pane.saveItemAs`
* `Pane.saveActiveItem`
* `Pane.saveActiveItemAs`
* `Pane.saveItems`
* `Workspace.saveActivePaneItem`
* `Workspace.saveActivePaneItemAs`

#### Effects on this package

We think this package could be impacted by this upgrade because it calls the changed methods in the following places:

* `TextBuffer.save`
  * [here](https://github.com/TypeStrong/atom-typescript/tree/master/dist/main/atom/commands/renameRefactor.js#L41)
  * [here](https://github.com/TypeStrong/atom-typescript/tree/master/lib/main/atom/commands/renameRefactor.ts#L45)

We found these calls using a regex search, so this list might be incomplete, and it might contain some false positives.

#### What to do about the change

It should be pretty easy to adjust your package code and/or tests to work with the new async behavior, and to simultaneously keep it working with older versions of Atom. Here are some examples of pull requests we opened on our bundled packages to cope with the change:

* https://github.com/atom/autocomplete-plus/pull/852
* https://github.com/atom/whitespace/pull/155
* https://github.com/atom/line-ending-selector/pull/45
* https://github.com/atom/symbols-view/pull/222
* https://github.com/atom/status-bar/pull/193
* https://github.com/atom/tabs/pull/448

**Comment by Positive07** [comment]
Luckily this package doesn't seem affected by this issue, since it doesn't rely on `TextBuffer.save` being synchronous and instead waits for `TextBuffer.onDidSave`

**Comment by opavader** [comment]
@Positive07 have you tried it with it beta1, atleast the autocomplete on type is not working.

**Comment by Positive07** [comment]
I don't see any link between autocomplete and this issue.

If this issue were to affect anything it would be the rename-refactor command
