### ISSUE TITLE
HTMLElement.rootElement is deprecated.

### ISSUE THREAD

**Issue by rickydazla** [TypeStrong/atom-typescript#1276]
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `rootElement` and access
the editor contents directly instead.
```
HTMLElement.rootElement (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-element.js:23:10)
getFromShadowDom (/Users/Rick/.atom/packages/atom-typescript/dist/main/atom/tooltipManager.js:18:19)
Object.attach (/Users/Rick/.atom/packages/atom-typescript/dist/main/atom/tooltipManager.js:38:18)
TypescriptEditorPane.setupTooltipView (/Users/Rick/.atom/packages/atom-typescript/dist/main/typescriptEditorPane.js:176:24)
new TypescriptEditorPane (/Users/Rick/.atom/packages/atom-typescript/dist/main/typescriptEditorPane.js:129:14)
subscriptions.add.atom.workspace.observeTextEditors (/Users/Rick/.atom/packages/atom-typescript/dist/main/atomts.js:85:24)
```

**Comment by yesnault** [comment]
@rickydazla why do you close your issue ?

**Comment by LAyBT** [comment]
The contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. Please, stop using rootElement and access the editor contents directly instead.

HTMLElement.rootElement - /Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:23:10
getFromShadowDom - /Users/abaeza/.atom/packages/atom-typescript/dist/main/atom/tooltipManager.js:18:19
Object.attach - /Users/abaeza/.atom/packages/atom-typescript/dist/main/atom/tooltipManager.js:38:18
TypescriptEditorPane.setupTooltipView - /Users/abaeza/.atom/packages/atom-typescript/dist/main/typescriptEditorPane.js:187:24
new TypescriptEditorPane - /Users/abaeza/.atom/packages/atom-typescript/dist/main/typescriptEditorPane.js:140:14
subscriptions.add.atom.workspace.observeTextEditors - /Users/abaeza/.atom/packages/atom-typescript/dist/main/atomts.js:90:24

**Comment by mojenmojen** [comment]
I'm seeing this messages as well in Atom 1.19.0 x64.

**Comment by isaacg11** [comment]
I'm also getting the same issue in Atom, see below:

The contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. Please, stop using rootElement and access the editor contents directly instead.
Report Issue
HTMLElement.rootElement - /Users/isaacgrey/Downloads/Atom.app/Contents/Resources/app/src/text-editor-element.js:23:10
getFromShadowDom - /Users/isaacgrey/.atom/packages/atom-typescript/dist/main/atom/tooltipManager.js:18:19
Object.attach - /Users/isaacgrey/.atom/packages/atom-typescript/dist/main/atom/tooltipManager.js:38:18
TypescriptEditorPane.setupTooltipView - /Users/isaacgrey/.atom/packages/atom-typescript/dist/main/typescriptEditorPane.js:187:24
new TypescriptEditorPane - /Users/isaacgrey/.atom/packages/atom-typescript/dist/main/typescriptEditorPane.js:140:14
subscriptions.add.atom.workspace.observeTextEditors - /Users/isaacgrey/.atom/packages/atom-typescript/dist/main/atomts.js:90:24

**Comment by Massi17** [comment]
The contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. Please, stop using rootElement and access the editor contents directly instead.
Report Issue
HTMLElement.rootElement - C:\Users\Massi\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-element.js:23:10
getFromShadowDom - C:\Users\Massi\.atom\packages\atom-typescript\dist\main\atom\tooltipManager.js:18:19
Object.attach - C:\Users\Massi\.atom\packages\atom-typescript\dist\main\atom\tooltipManager.js:38:18
TypescriptEditorPane.setupTooltipView - C:\Users\Massi\.atom\packages\atom-typescript\dist\main\typescriptEditorPane.js:187:24
new TypescriptEditorPane - C:\Users\Massi\.atom\packages\atom-typescript\dist\main\typescriptEditorPane.js:140:14
subscriptions.add.atom.workspace.observeTextEditors - C:\Users\Massi\.atom\packages\atom-typescript\dist\main\atomts.js:90:24

**Comment by lnunezp** [comment]
The contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. Please, stop using rootElement and access the editor contents directly instead.
Report Issue
HTMLElement.rootElement - C:\Users\lnunez\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-element.js:23:10
getFromShadowDom - C:\Users\lnunez\.atom\packages\atom-typescript\dist\main\atom\tooltipManager.js:18:19
Object.attach - C:\Users\lnunez\.atom\packages\atom-typescript\dist\main\atom\tooltipManager.js:38:18
TypescriptEditorPane.setupTooltipView - C:\Users\lnunez\.atom\packages\atom-typescript\dist\main\typescriptEditorPane.js:187:24
new TypescriptEditorPane - C:\Users\lnunez\.atom\packages\atom-typescript\dist\main\typescriptEditorPane.js:140:14
subscriptions.add.atom.workspace.observeTextEditors - C:\Users\lnunez\.atom\packages\atom-typescript\dist\main\atomts.js:90:24

**Comment by Mo9a7i** [comment]
same here

**Comment by nachoperassi** [comment]
same here

**Comment by darrynjzb** [comment]
what is going on?

**Comment by matias1305** [comment]
How can it be solved? :c

**Comment by itssadon** [comment]
The contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. Please, stop using rootElement and access the editor contents directly instead.

HTMLElement.rootElement - /Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:23:10
getFromShadowDom - /Users/itssadon/.atom/packages/atom-typescript/dist/main/atom/tooltipManager.js:18:19
Object.attach - /Users/itssadon/.atom/packages/atom-typescript/dist/main/atom/tooltipManager.js:38:18
TypescriptEditorPane.setupTooltipView - /Users/itssadon/.atom/packages/atom-typescript/dist/main/typescriptEditorPane.js:187:24
new TypescriptEditorPane - /Users/itssadon/.atom/packages/atom-typescript/dist/main/typescriptEditorPane.js:140:14
subscriptions.add.atom.workspace.observeTextEditors - /Users/itssadon/.atom/packages/atom-typescript/dist/main/atomts.js:90:24

**Comment by hutzne** [comment]
same here, how to fix this?

**Comment by jinchuuriki91** [comment]
same issue here :(

`HTMLElement.rootElement - /Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:23:10
getFromShadowDom - /Users/gandharpednekar/.atom/packages/atom-typescript/dist/main/atom/tooltipManager.js:18:19
Object.attach - /Users/gandharpednekar/.atom/packages/atom-typescript/dist/main/atom/tooltipManager.js:38:18
TypescriptEditorPane.setupTooltipView - /Users/gandharpednekar/.atom/packages/atom-typescript/dist/main/typescriptEditorPane.js:187:24
new TypescriptEditorPane - /Users/gandharpednekar/.atom/packages/atom-typescript/dist/main/typescriptEditorPane.js:140:14
subscriptions.add.atom.workspace.observeTextEditors - /Users/gandharpednekar/.atom/packages/atom-typescript/dist/main/atomts.js:90:24`

**Comment by Atrus-sama** [comment]
Same here
I dont know if it is because of this, but the autocomplete don't work any more :(
I'll wait an update to fix this, in the mean time i have to use Visual Studio Code for typescript

**Comment by sondauta2** [comment]
work around? solution? fix?

**Comment by JohnAlvaro** [comment]
Same here

**Comment by carvalhods** [comment]
Same here

**Comment by valkonzero** [comment]
same

**Comment by norfeo87** [comment]
same here

**Comment by xexe45** [comment]
same here

**Comment by reliy0n** [comment]
same here

**Comment by ilDug** [comment]
same here

**Comment by raresferastauaru** [comment]
Same here.

**Comment by yvoste** [comment]
Same here

**Comment by dardaiin** [comment]
same here :( how is it going with the fix

**Comment by notlikethis** [comment]
something is the same

**Comment by gusfravo** [comment]
Same here

**Comment by JoeriDamme** [comment]
same here

**Comment by etholen** [comment]
same here

**Comment by albertrosa** [comment]
same here

**Comment by FahadAlbukhari** [comment]
same here

**Comment by Riyaz0001** [comment]
same here

**Comment by werd2000** [comment]
same here

**Comment by homeless2010** [comment]
same here
