### ISSUE TITLE
Typescript file is not getting compiled to javascript file after renamed

### ISSUE THREAD

**Issue by zpaya** [TypeStrong/atom-typescript#1277]
atom-typescript 11.0.3
Atom v1.17.2 x64

I renamed the grammar.ts to 01grammar.ts and tried to compile but .js file not getting created. For new .ts file .js is created.

**Comment by guncha** [comment]
Yep, there's an issue with atom-typescript not keeping track of files as they're renamed. I'll look into it some more.
