### ISSUE TITLE
Use new TypeScript Extensibility for code completion in html templates etc.

### ISSUE THREAD

**Issue by DerZyklop** [TypeStrong/atom-typescript#1278]
As far as i understand this thread:

https://github.com/Microsoft/TypeScript/issues/6508

It should be possible to have code completion in html templates. This would be awesome! 

The Language Extensibility is available in TypeScript since 2.3. Whats missing is some code in atom-typescript, am i right?

**Comment by jonyeezs** [comment]
I believe TypeScript has decided this a domain related issue and won't be adding it in.

That discussion has lead to the creation of [language-service](https://blogs.msdn.microsoft.com/typescript/2017/04/27/announcing-typescript-2-3/#language-server-plugin-support)  with the support of [angular language service](https://github.com/angular/angular/blob/master/packages/language-service/src/ts_plugin.ts)

I'm currently toying with creating a package that would help enable the angular language service.

I currently can't find anything that really fits this criteria

**Comment by jonyeezs** [comment]
This issue should be close as it shouldn't be part of typescript's main client.

**Comment by jonyeezs** [comment]
@guncha @TypeStrong I'm planning to create a package that extends this for angular language service.

But I'm finding it a hard time to see where the language client gets initialize when a pane is open to.

Could i get a rough guide on how this package works on a high-level?

**Comment by guncha** [comment]
The nice thing about using the Typescript plugin feature is that it's not editor specific, i.e., you can write it once and it will work in atom-typescript, vscode, sublime text, vim plugins, etc. I'd say look at some already written plugins (the simpler the better, there's a few listed at the bottom of [the plugin wiki](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin)) and try to modify them to do what you want.

That said, I should still document how this package works, but that's a different issue..

**Comment by jonyeezs** [comment]
That's true for the language service.

But atom-typescript has a huge IDE feature (ie autocomplete, codefix, etc)
which is not part of the plugins.

I am planning to use the angular language service plugin. But i need to get
the IDE (ie atom-typescript) to work with it.

At the moment this package supports ts files. Which it should only. There's
bit of code in the grammar that regex on `template:`. Imo that shouldn't be
in the project but in a plugin to atom-typescript.

That's my intention to figure out how to make this package extendable and
not modify it just for a framework.

**Comment by DerZyklop** [comment]
I am still interested in this. If anyone has a workaround or hints how to get this, please post it here
✌
