### ISSUE TITLE
Semantic View integration is missing

### ISSUE THREAD

**Issue by russaa** [TypeStrong/atom-typescript#1279]
similar to issue #1219 "Symbols-view integration is missing", the _Semantic View_ (or _Outline_) is also missing since the update to v11.x.x

cf. the image from the old (v 10.x.x) [README](https://github.com/TypeStrong/atom-typescript/tree/v10.1.15#semantic-view) (Semantic View is on the right):
![](https://raw.githubusercontent.com/TypeStrong/atom-typescript-examples/master/screens/semanticView.png)

I find this feature extremely useful -- in fact, its absence is _the_ reason for me, why I did not switch to v11.x.x yet (closely followed by the missing symbols-view)

**Comment by lierdakil** [comment]
Released as v12.2.0 :tada:
