### ISSUE TITLE
new TextBuffer is deprecated.

### ISSUE THREAD

**Issue by cyanotrix** [TypeStrong/atom-typescript#1282]
The `load` option to the TextBuffer constructor is deprecated. Get a loaded buffer using TextBuffer.load(filePath) instead.
```
new TextBuffer (<embedded>:30622:22)
resolve (D:\Atom\atom-x64-windows\.atom\packages\atom-typescript\dist\main\atomts.js:173:28)
Object.<anonymous> (D:\Atom\atom-x64-windows\.atom\packages\atom-typescript\dist\main\atomts.js:172:30)
Generator.next (null:null:null)
<unknown> (D:\Atom\atom-x64-windows\.atom\packages\atom-typescript\node_modules\tslib\tslib.js:91:69)
Object.__awaiter (D:\Atom\atom-x64-windows\.atom\packages\atom-typescript\node_modules\tslib\tslib.js:87:16)
```

**Comment by ElecTreeFrying** [comment]
reinstall atom-typescript 
else
install this this git repo to atom as a temporary solution https://github.com/lierdakil/atom-typescript

**Comment by lierdakil** [comment]
Please, don't install from that fork anymore. It's no longer maintained. Also, this particular deprecation isn't fixed there, because I didn't see it, and I'm fuzzy about the details of when that particular code branch is executed.

**Comment by nmpribeiro** [comment]
Actually, I've just installed atom and atom-typescript on my Mac today, and this deprecation appeared. I believe I'm on https://github.com/TypeStrong/atom-typescript repo.

Details:
`
new TextBuffer - <embedded>:30981:22
resolve - /Users/susanasantos/.atom/packages/atom-typescript/dist/main/atomts.js:192:28
Object.<anonymous> - /Users/susanasantos/.atom/packages/atom-typescript/dist/main/atomts.js:191:30
Generator.next - null:null:null
<unknown> - /Users/susanasantos/.atom/packages/atom-typescript/node_modules/tslib/tslib.js:96:75
Object.__awaiter - /Users/susanasantos/.atom/packages/atom-typescript/node_modules/tslib/tslib.js:92:16
`

**Comment by walleboom** [comment]
I get this when I use the Rename Refactor (F2) on Windows 8.1.
