### ISSUE TITLE
Angular4/Typescript - Importing absolute path doesn't work

### ISSUE THREAD

**Issue by sahilpurav** [TypeStrong/atom-typescript#1285]
I've enabled absolute path with the help of tsconfig.json property (baseUrl and paths). Following is my tsconfig:
`
{
  "compilerOptions": {
    "module": "es2015",
    "baseUrl": ".",
    "types": [],
    "paths": {
      "@eos/classes": ["app/classes/index"],
      "@eos/config": ["config/index"],
      "@eos/provider": ["providers/index"]
    }
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
`

then in app.component.ts, I add following code:
`import { AppClass } from "@eos/classes"`

It works fine when I build the project but in Atom, it gives module not found error. 
![screenshot from 2017-06-25 16-44-13](https://user-images.githubusercontent.com/8158506/27515626-9e930cc8-59c5-11e7-8441-e28a08669d0f.png)

I'm working on Angular4 with CLI configuration.

**Comment by guncha** [comment]
`paths` and `baseUrl` options should work fine unless you're on some old version of atom-typescript. Can you make a minimal example repo that reproduces the error?

**Comment by Goodwine** [comment]
Could this be because of the recent "use NODE_PATH instead"? I guess it's possible that if you have an older version in NODE_PATH it may mess things up. You can confirm that by looking at the status bar and seeing if it says "2.3.4", if it says otherwise then that's why.

**Comment by guncha** [comment]
Pretty sure this was opened before I published those changes.
