### ISSUE TITLE
[bug] latest release causes freezes of scrolling

### ISSUE THREAD

**Issue by ZuBB** [TypeStrong/atom-typescript#1288]
atom: latest as of today
atom-typescript: 11.0.4

when I open any ts file and want to scroll it nothing happens. but in a second or two file is scrolled. highly annoying

**Comment by guncha** [comment]
Can you run a profile to see where the lag is? Not much has changed except for the change from `linter 1.x` to `2.x`.

**Comment by ZuBB** [comment]
for some reason files with profile data I am saving result in zero size 😕 so I have only sceeen
<img width="1440" alt="screen shot 2017-06-26 at 22 58 58" src="https://user-images.githubusercontent.com/597016/27557718-34ce245e-5ac3-11e7-8565-0277c9c48a24.png">

**Comment by guncha** [comment]
Okay, it's spending ~3s globbing some directory entries. Now I suspect it has to do with the change that allows people to keep their typescript installation in `NODE_PATH` directory. The resolution fo the correct `tsserver` happens in sync now so that might explain the lockup you're seeing. What does `process.env.NODE_PATH` say for you in the console?

**Comment by ZuBB** [comment]
> process.env.NODE_PATH
> "/Applications/Atom.app/Contents/Resources/app/exports"

but.. afaik I do not have node there..

**Comment by ZuBB** [comment]
does this help?
```
Last login: Thu Jun 22 12:47:45 on ttys000
vzuzyak@mbp16 ~
$ node -v
v6.11.0
vzuzyak@mbp16 ~
$ whereis node
vzuzyak@mbp16 ~
$ which node
/usr/local/opt/node@6/bin/node
vzuzyak@mbp16 ~
$ 
```

**Comment by guncha** [comment]
It all looks ok to me. That's the default `NODE_PATH` set by Atom. It's what allows your plugin code to require `atom` and get it. If you're feeling adventurous, you can edit the `resolveServer` function in `clientResolver.ts` to not use the `paths` option and see if that fixes it.

**Comment by ZuBB** [comment]
I have commented it and it still does not help..

**Comment by guncha** [comment]
There's another thing that the plugin now does when opening a file:

https://github.com/TypeStrong/atom-typescript/commit/8a7209bea194f210b02ac4f59dc32c3fd307a167#diff-6475f9ce9db38156d8f1804c6cedf354R182

I don't see how it could cause a ton of file system requests, but try to comment that out and see if it changes.

**Comment by ZuBB** [comment]
no that also does not help..

**Comment by guncha** [comment]
Then I'm out of ideas, sorry 😞 . I'd probably try to use the profiler to narrow it further.

**Comment by tylkomat** [comment]
It seems there is a problem with glob or its usage. I opened the same file of 45 lines of code.

### 11.0.4 All the top functions are related to glob.
![atom-typescript-11 0 4](https://user-images.githubusercontent.com/815915/27587540-102e6c30-5b45-11e7-9f73-336198c29105.png)

### 11.0.3 all top functions are related to atom itself
![atom-typescript-11 0 3](https://user-images.githubusercontent.com/815915/27587636-5d7ca1aa-5b45-11e7-8882-bd955116c9a3.png)

**Comment by pete-hotchkiss** [comment]
I'm experiencing this too. Is there a way ro rollback to the previous instailation ?

**Comment by guncha** [comment]
@pete-hotchkiss, you can run `apm dev atom-typescript` and then checkout any previous version from there. I'm not seeing the lag, but I have SOME idea of what's causing it so, if at all possible, I'd like to push a fix and test it on your system before releasing a new version.

**Comment by guncha** [comment]
I have a potential fix in #1298. If anyone would like to test before I publish, that'd be great.

**Comment by tylkomat** [comment]
Looks good to me, no lag anymore.

**Comment by bartocc** [comment]
Looks good to me as well
