### ISSUE TITLE
Codefix for auto-imports should replace the prefix with compilerOptions.paths

### ISSUE THREAD

**Issue by Goodwine** [TypeStrong/atom-typescript#1289]
In my setup I'm using [bazel](bazel.build) to put things together and autogenerate my tsconfig file, and in the end auto-imports assume that I have all files locally and gives me relative paths from apparently the root dirs. I believe it should replace all prefixes with stuff from `compilerOptions.paths`.

Take for example a file that has some angular and rxjs stuff, like...

```
r/myapp/a/b/c.ts
r/myapp/x/y/foo.ts
```

This files is then built into these

```
r/myapp/tsconfig.ts
r/myapp/a/b/c.ts
r/myapp/a/x/y/foo.ts
build/r/myapp/a/b/c.ts
build/r/myapp/a/x/y/foo.ts
build/r/angular/v456/a/b/core/a.ts
build/r/angular/v456/a/b/core/b.ts
build/r/rxjs/v123/src/a/b/subject.ts
build/r/rxjs/v123/src/a/b/observable.ts
```

And the tsconfig looks roughly like this:

```js
{
  compilerOptions: {
    baseUrl: ".",
    paths: {
      "*": ["../../build/*"],
      "@angular/core": ["../../build/r/angular/v456/a/b/core/*"],
      "rxjs": ["../../build/r/rxjs/v123"],
      "rxjs/*": ["../../build/r/rxjs/v123/*"],
      "r/myapp": [
        "./*",
        "../../build/r/myapp/*"
      ],
      "myapp": [
        "./*",
        "../../build/r/myapp/*"
      ],
    },
   files: [ /* ... */ ],
   rootDirs: ["./", "../../build/r/myapp/a/"]
  }
}
```

Then when trying to get auto imports, I get odd results. Imagine I have the following class that I want to get auto imports for `Foo`, `Subject`, and `Inject`:

```ts
@Directive({selector:'test'})
export class TestDirective{
  constructor(private @Inject('somesubject') somesubject: Subject<Foo>){}
}
```

Then I get the following suggestions:

```ts
import { Inject, Directive } from '../../build/r/angular/v456/a/b/core'
import { Subject } from '../../build/r/rxjs/v123'
import { Foo } from 'x/y/foo'
```

Is it possible to modify the suggested import path(s) and replace it with the `compilerOptions.paths`?
For example Foo could be suggested as `x/y/foo`, `myapp/a/x/y/foo`, or `r/myapp/a/x/y/foo`, while @Inject would suggest `@angular/core`

**Comment by guncha** [comment]
Yeah, I'm seeing something similar. The codefix feature does what I want about half the time. This is something that should be addressed by the Typescript team, so please try to see if they have an open issue for this and, if not, open a new one. They're pretty good with responding to issues.
