### ISSUE TITLE
Aggressive error message while creating a reference

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#129]
From @nycdotnet :

I was creating a comment reference and while I was typing it correctly, I started getting the below error.  I wonder if there is any way to suppress this error while I'm in the process of typing.  I wouldn't mind the error if I switched to a new line or navigated away.  (Note the error actually popped up before I typed the second double-quote).

![atom-ts-referenceerror](https://cloud.githubusercontent.com/assets/3755379/6361126/8f4b4ab8-bc4d-11e4-9388-35135e21c35c.png)

**Comment by basarat** [comment]
We want errors to show up as quickly as possible. You don't want the resharper experience of .... waiting for the LS to tell you what might be wrong. Consider the case where you are experimenting with code: you want it to give you an error as soon as you are done experimenting.

You can however change this from the linter settings.


![image](https://cloud.githubusercontent.com/assets/874898/6365486/5acd457e-bd0c-11e4-9ed8-28dd47bade4c.png)

**Comment by basarat** [comment]
From @nycdotnet :

Regarding not wanting to have a Resharper "wait for it.... OK!" or "wait for it.... You're wrong!" experience, I *agree* with that goal.

That said, I don't like the user experience of being actively told I'm doing something wrong while I am in the process of typing something correctly.  For example, if I were typing "apple" in MS Word, the spell checker doesn't yell at me as I'm typing appl and then say "oh fine" after I put the e - it's only after I've given some indication that I'm done that the spell checker evaluates what I've typed (or at least it waits to show me the feedback).  I wouldn't even have a problem with it if I typed `///<deference` with a typo or something.  Just my opinion, so please take this as constructive criticism.

Thanks Bas.

**Comment by basarat** [comment]
I agree that an aggressive error can be annoying. However don't see an algorithmic way of reading the user's mind for "I am waiting for an ok or nOk response" vs. "I and still typing".

**Comment by rscottfree** [comment]
Please, just show the red underline then, not a popup that covers up text -- what if I were reading that line while I typed? This popup is very distracting.

**Comment by basarat** [comment]
> Please, just show the red underline then, not a popup that covers up text -- what if I were reading that line while I typed? This popup is very distracting.

@rscottfree that's an issue for : https://github.com/atom-community/linter  :rose: 

Since there aren't any actionable items here, we just use what linter gives us. I'm closing this issue.
