### ISSUE TITLE
Countless warnings: Message.location must be valid

### ISSUE THREAD

**Issue by DavidStenstroem** [TypeStrong/atom-typescript#1291]
atom-typescript version: 11.0.4
atom version: latest

I'm getting this error/warning whenever I touch any .ts file: 

![skaermbillede 2017-06-27 kl 10 38 59](https://user-images.githubusercontent.com/5563022/27578670-16e03b46-5b25-11e7-96a3-16e762652501.png)

The error is always the same.
The code linter and syntax highlighting is working as it should, the only problem is the error/warning I receive, whenever I type or move the cursor around a file

**Comment by DavidStenstroem** [comment]
Turns out it was a problem in my own code - not in atom-typescript. Closing now.

**Comment by guncha** [comment]
If anyone else runs into this, this is likely caused by all of the dependencies of `atom-typescript` not being correctly installed. Nuking the `~/.atom/packages/atom-typescript` directory and installing the plugin again should fix it.
