### ISSUE TITLE
Module resolution not correct in atom-typescript in @types

### ISSUE THREAD

**Issue by gpit2286** [TypeStrong/atom-typescript#1297]
I'm having a problem with tsc correctly finding values and atom-typescript failing. I have all of the relevant types installed under node_modules/@types 

* atom-typescript: 11.0.4
* linter: 2.2.0

atom-typescript in app lint: 
```
Error	Typescript	Cannot find module 'http'.	4:23
Error	Typescript	Cannot find module 'https'.	5:24
Error	Typescript	Cannot find module 'fs'.	6:21
Error	Typescript	Cannot find module 'path'.	7:23
Error	Typescript	Cannot find module 'child_process'.	8:23
Error	Typescript	Cannot find module 'bunyan'.	12:25
Error	Typescript	Cannot find module 'config'.	13:25
Error	Typescript	Cannot find module 'hashids'.	14:26
Error	Typescript	Cannot find module 'lodash'.	15:20
Error	Typescript	Cannot find module 'passport'.	17:27
Error	Typescript	Cannot find name 'require'.	18:28
Error	Typescript	Cannot find module 'phantom'.	19:26
Error	Typescript	Cannot find module 'restify'.	20:26
Error	Typescript	Cannot find name 'require'.	21:17
Error	Typescript	Cannot find name 'require'.	24:18
Error	Typescript	Cannot find module 'mailgun-es6'.	25:26
Error	Typescript	Cannot find name 'process'.	38:12
```

* tsc: 2.2.1

tsc output:
``` 
>> tsc src/index.ts 
src/generalFns.ts(34,14): error TS2693: 'Promise' only refers to a type, but is being used as a value here.
src/routes/customers/index.ts(9,48): error TS2694: Namespace 'Logger' has no exported member 'Logger'.
src/routes/invoices/index.ts(35,48): error TS2694: Namespace 'Logger' has no exported member 'Logger'.
src/routes/invoices/index.ts(335,21): error TS2304: Cannot find name 'SalesOrder'.
src/routes/types.ts(6,64): error TS2694: Namespace 'Logger' has no exported member 'Logger'.
```

tsconfig: 
```
{
  "compilerOptions": {
    "outDir": "./build",
    "rootDir": "./src",
    "target": "ES5",
    "module": "commonjs"
  },
  "compileOnSave": false,
  "filesGlob": [
    "./src/**/*.ts"
  ]
}
```

One thing that I noticed is that it does find the module for moment, but the moment d.ts is located in the module directory and not in the @types directory. 

How to I get atom-typescript to resolve in the same way as tsc?

**Comment by guncha** [comment]
Typescript (both `tsc` and `atom-typescript` because it uses `tsserver` which shares code with `tsc`) will automatically pick up all of the types installed in `node_modules/@types`. I just tried it with your exact Typescript version and `tsconfig.json`.

Things to try:

1. Restart Atom
2. Make sure there's only one `node_modules` and one `tsconfig.json` file in the project
3. Run `npm i @types/node` to make sure they're installed (top level directory)
4. Rebuild the project from the ground up in a new directory 

P.S. `filesGlob` is not a supported `tsconfig.json` property. You should use `include` instead.

**Comment by gpit2286** [comment]
@guncha None of the above helped. It looks like there are other people having the same issue. 
#1307 #1209 #1142 #1059 and possibly #994

**Comment by gpit2286** [comment]
I kept reading the issues and discovered that there was a project in my deps that had a dep to a typescript that was in the 1.8.x version.  I added a dep in my project for the currently installed typescript (2.2.x) and everything works fine. For anyone else who is having this issue, make sure there is no out dated typescript dependency. (You can view all depends by running npm ls in the base directory.)
