### ISSUE TITLE
changelog / release notes

### ISSUE THREAD

**Issue by robjtede** [TypeStrong/atom-typescript#1302]
_Obviously related to #756 and #621._

There's the breaking changes changelog in `docs` but it would be nice to have a proper CHANGELOG.md in the root or notes on the releases page (since there hasn't been any notes attached to releases since v10.1.8).

Having to look at the commit titles to figure out what has changed is less than ideal.

**Comment by guncha** [comment]
I agree, this would be useful. I'll try to document the changes better.

**Comment by jonyeezs** [comment]
The other issues proposes to use If  https://github.com/TypeStrong/atom-typescript/releases.

If we intend to use that, we should be diligent to convey the changes in a more visible way.

Our beloved editor does a good job with that: https://github.com/atom/atom/releases

**Comment by robjtede** [comment]
Changelog.md has been added. Can we trust that it will be maintained and close this issue ;)

**Comment by guncha** [comment]
We can 😁
