### ISSUE TITLE
Atom Typescript is not able to find modules when tsc can

### ISSUE THREAD

**Issue by morsecodist** [TypeStrong/atom-typescript#1307]
I made a bare bones test of this. My file structure is:
```
/bin
    index.js
/src
    index.ts
package.json
tsconfig.json
```

Here is my `tsconfig.json`:

```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "sourceMap": true,
    "removeComments": true,
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "suppressImplicitAnyIndexErrors": true,
    "outDir": "bin",
    "moduleResolution": "node"
  },
  "include": [
    "node_modules/@types",
    "./src/**/*.ts"
  ]
}
```

Here are the dependencies from `package.json`, which I have installed:
```
"dependencies": {
    "@types/mathjs": "0.0.34",
    "mathjs": "^3.14.2"
  }
```

`src/index.ts`:
```
import { eye } from 'mathjs'

console.log(eye(3))
```

`atom-typescript` underlines `mathjs` and says: `Cannot find module 'mathjs'` but when I run:
```
$ tsc
$ node bin/index.js
```

Everything works just fine. Any suggestions?

**Comment by gpit2286** [comment]
There seem to be a lot of open issues that are relating to this. It seems that the runner in atom-typescript is not finding the npm/@types folder.  I have a couple pieces of evidence.  

1. When tsc is ran with moduleResolution: classic the errors seem to be the same, which is what would be expected when not ran in a node env. 

2. In my project, atom-typescript IS able to find the tpes for moment, which does not have a separate node/@types  def, but rather within the moment package itself.  

I tried looking through the code but I'm a little lost on how the information gets passed to the linter... it seems that the users config is not getting passed to the linter and rather something like the classic module resolution is getting passed through.

**Comment by mgrivera** [comment]
Hi, 

My project uses _meteor_. It seems _atom-typescript_ is not accepting absolute paths in imports. 

this works: 
`import { Monedas } from '../../../../imports/collections/monedas';`

but this does not and generates a warning: 
`import { Monedas } from '/imports/collections/monedas';`

it says 
> cannot find module '/imports/collections/monedas'

Of course when _meteor_ compiles ts files, the error is not shown. 
Maybe I'm missing something, but what could it be? 

Thanks and bye ....

**Comment by gwely** [comment]
@mgrivera I think your issue will be solved by using the following:

`import { Monedas } from 'imports/collections/monedas';`

(note the missing `/`)

**Comment by DrMiaow** [comment]
I'm finding that it complains in the case of a namespaced module.

`import { a } from '@b/c'`

Compiles fine, but atom-typescript complains about it.

`Cannot find module '@b/c'.`
