### ISSUE TITLE
Loading typescript from NODE_PATH doesn't work correctly

### ISSUE THREAD

**Issue by Goodwine** [TypeStrong/atom-typescript#1314]
Apparently Atom overrides NODE_PATH with the "exports" directory, for example `/usr/share/atom/resources/app/exports`

This was also noticed on Issue #1285, and it caused Issue #1311 because I use a special version of typescript that wasn't being loaded.

This is probably working as intended, I guess?
My workaround is to symlink the typescript directory from my NODE_PATH to Atom's NODE_PATH. It worked really well!

**Comment by lierdakil** [comment]
You can manipulate `NODE_PATH` in Atom's init script. Since https://github.com/TypeStrong/atom-typescript/commit/6acc1644228059948edbe6d9c5517bd43bc8e0ea we support multiple directories there (delimited by `:` or `;` depending on your platform)
