### ISSUE TITLE
Compile On Save not working with TypeScript 1.8.10 & atom-typescript v11

### ISSUE THREAD

**Issue by dogfoodsilo4** [TypeStrong/atom-typescript#1319]
My dev team and I are in a bit of a pickle with 2 issues (plus one minor issue).

Since the Atom update to v1.18, and atom-typescript v11, we have been unable to compileOnSave.

Our solution was to roll back to atom-typescript v10.1.14.  This resolved our issue.

Since the Atom update to v1.19 however, we have been seeing almost continual errors that appear to stem from atom-typescript.

e.g.
```
Uncaught TypeError: Cannot read property 'length' of undefined
C:\Users\chrisb\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-component.js:2286
Hide Stack Trace
TypeError: Cannot read property 'length' of undefined
    at TextEditorComponent.screenPositionForPixelPosition (C:\Users\chrisb\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-component.js:2286:33)
    at HTMLElement.screenPositionForPixelPosition (C:\Users\chrisb\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-element.js:247:32)
    at TextEditor.module.exports.TextEditor.screenPositionForPixelPosition (C:\Users\chrisb\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor.js:3658:38)
    at showExpressionType (C:\Users\chrisb\.atom\packages\atom-typescript\dist\main\atom\tooltipManager.js:52:31)
    at C:\Users\chrisb\.atom\packages\atom-typescript\dist\main\atom\tooltipManager.js:41:59

The error was thrown from the atom-typescript package. This issue has already been reported.
```

These errors don't appear to cause any problems, they are just very frustrating for the whole team.

I tried again updating to v11, but still cannot compile on save and (minor issue) the create tsconfig.json command is missing!?  so I cannot see if the updated version requires a change the structure of tsconfig.

Our existing tsconfig is:
```
"compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "isolatedModules": false,
        "jsx": "react",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": true
    },
"compileOnSave": true,
"buildOnSave": false,
"atom": {
        "rewriteTsconfig": true
    }
```
We are using Typescript 1.8.10 and don't have any plans to update in the near future.

The first issue then is why won't v11 compileOnSave
The second issue is why does v1.19 of Atom sit nicely with 10.1.14 of atom-typescript (I think the answer to this will be "you should upgrade to v11": but see above)
The third issue is, "where has the create tsconfig command gone in v11?"

Any suggestions on how to resolve these issues is greatly appreciated.

Thanks

**Comment by lierdakil** [comment]
Maintainers seem to be MIA, so I will do my best to answer.

1. I have no idea why `compileOnSave` doesn't work for you, and I never used it myself, but see below
2. Atom 1.19 changed a bunch of internal APIs, so atom-typescript is borked. See #1310.
3. A while back, in an effort to make atom-typescript somewhat more maintainable, a bunch of stuff was thrown away. In particular, tsconfig manipulation. It was meaningful before TypeScript 2.something, I think. Nowadays (i.e. on a sufficiently recent TypeScript version) you just do something like this:
```cson
{
    "compilerOptions": { ... },
    "exclude": [
        "node_modules"
    ],
    "include": [
        "src/**/*.ts",
        "src/**/*.tsx",
        "src/**/*.js"
    ]
}
```
and `tsc` figures out the rest.

Not my place to ask, but why you want to keep using TS 1.8? Upgrading should be relatively painless in most cases, and there are many reasons to *want* to upgrade, IMO. In any case, from what I can tell, there's little support for TS 1.x in newer versions of tooling. You could of course stay on older Atom and atom-typescript versions, if you have to.

**Comment by lierdakil** [comment]
ETIMEDOUT, closing.
