### ISSUE TITLE
When I install inter Atom's autocomplete stops working

### ISSUE THREAD

**Issue by dimitri320** [TypeStrong/atom-typescript#1321]
When I install inter Atom's autocomplete stops working.
This problem came about when I've decided to update Atom and all my packages!
Not Atom says that "atom-typescript" is depricated!!????

**Comment by micaelmbagira** [comment]
Same here, after updating to Atom 1.19.0

**Comment by anta-semenov** [comment]
Related to
#https://github.com/TypeStrong/atom-typescript/issues/1294

**Comment by RobertCordes** [comment]
Doesn't seem to work for me 😞

**Comment by lierdakil** [comment]
I'll just leave these here: #1310, #1317.

**Comment by lierdakil** [comment]
Pretty sure this can be closed.
