### ISSUE TITLE
I get random type info at random cursor positions

### ISSUE THREAD

**Issue by DerZyklop** [TypeStrong/atom-typescript#1324]
My atom shows me type info. But the type info i get seem to be not related with the cursor position. I even get type info when my cursor points at empty lines.

![2017-08-13 17 59 08](https://user-images.githubusercontent.com/912344/29251221-800ba19a-8051-11e7-9996-f2fe10170152.gif)

The type info i get is related to methods/vars in my current file, tho.

**Comment by DerZyklop** [comment]
It seems like atom-typescript or atom itself has problems with my scroll position. If i scroll one line, my "type info on hover" feature is offset by one line.

**Comment by DerZyklop** [comment]
Related Stackoverflow entry: https://stackoverflow.com/questions/45662503/atom-shows-type-info-tooltips-at-random-cursor-positions

**Comment by cenkentimist** [comment]
I seem to be having this problem too.

**Comment by lierdakil** [comment]
I believe I fixed it in https://github.com/TypeStrong/atom-typescript/pull/1310. If feeling adventurous, you can install my fork (see comments there and in https://github.com/TypeStrong/atom-typescript/issues/1317)

**Comment by qwemaze** [comment]
Also experiencing same problem.
Usually info shown is for anything straight down to some distance from a cursor position.
![Invalid info](https://i.imgur.com/xxnQvbr.png)

**Comment by lierdakil** [comment]
Should be fixed in 11.0.7

**Comment by DerZyklop** [comment]
@lierdakil  works well for me. thx!
