### ISSUE TITLE
Buffer corruption.

### ISSUE THREAD

**Issue by rzvc** [TypeStrong/atom-typescript#1327]
Hello,

This started a couple of releases back I think. From time to time the buffer atom-typescript uses to compile the code gets mangled and it starts displaying weird errors and worst of all, the generated code (if you save & it automatically builds) is all broken.

The only solution I could find was to close the file and reopen it, which then gets rid of the errors and a subsequent save, generates a correct output file.

Is this affecting other users as well or is it just me? It's a very serious issue, but I failed to find another issue on the topic.

Thanks.

**Comment by mmermerkaya** [comment]
This just started happening to me after I updated Atom to 1.19.4.

**Comment by robjtede** [comment]
Frequent occurrence for me, too.

**Comment by guncha** [comment]
This is likely also related to the issue introduced in TextBuffer in 1.19.4 (more info in #1333).

**Comment by lierdakil** [comment]
Pretty sure this can be closed. Resolution: update to Atom 1.19.5.

**Comment by emnh** [comment]
I am experiencing corruption with Atom 1.20.1 as soon as I have multiple buffers on the same file (right click and choose Split Right).

**Comment by rzvc** [comment]
I recently experienced corruption too, but I couldn't replicate.
