### ISSUE TITLE
Typescript autocompletion significantly slow since atom 1.19 (incl. 1.20 betas) comparing to 1.18

### ISSUE THREAD

**Issue by deankevorkian** [TypeStrong/atom-typescript#1331]
On atom 1.18 versions, atom-typescript performs well (atom-typescript 11.0.6, Atom 1.18). Ever since I upgraded to 1.19 or 1.20 versions, atom-typescript performs slow. Tried reverting back to atom-typescript 11.0.6, but 11.0.6 doesn't work with atom >= 1.19. So I must use 11.0.7 which suffers from performance issues.

Any ideas about this? Anything you'd like me to check or details to add?
Thanks!

**Comment by guncha** [comment]
What sort of slowness are you talking about? Is the autocomplete slow to open?

**Comment by deankevorkian** [comment]
Yep, autocomplete suggestions are slow to open.

**Comment by HitomiTenshi** [comment]
I had the same issue. Tried to switch because of this to VSCode but it doesn't have some features that I need.

Decided to downgrade to 1.18 for the meantime and autocomplete works fine again.

How it works in 1.18:
You start typing and autocompleted results already pop up. Almost instantly.

Slowness in 1.19:
You start typing and nothing. Only once you pause typing for 1 second it starts showing autocompleted results. Sometimes it doesn't even show that and I have to press CTRL + Space to force it to show results.

This delay kills productivity so hard I had to downgrade.

**Comment by deankevorkian** [comment]
Same here, had to downgrade to 1.18 to enjoy it again. Maybe it's something cause by changes in atom's core?

**Comment by GlenCFL** [comment]
I'm pretty sure that Atom 1.18 had a bug where onDidStopChanging would emit much more frequently than it should have, with it seemingly ignoring the timeout that should have been imposed on it. I'm not sure if atom-typescript's Autocomplete provider can be unhinged from onDidStopChanging, but I think that's the only way to regain that speed.

**Comment by GlenCFL** [comment]
That would explain the speed difference in the current version of atom-typescript between Atom 1.18 and Atom 1.19+.

@lierdakil was there a particular reason to use debouncedEmitDidStopChanging over emitDidStopChanging in [this commit](https://github.com/TypeStrong/atom-typescript/commit/52811ad78569391805e9662e3f237a41ca54d43f)?

**Comment by deankevorkian** [comment]
Also, in [this](https://github.com/TypeStrong/atom-typescript/pull/1322) PR, (which I tested locally but seemed to make the autocompletion worse, maybe because I'm using Atom 1.20 beta-5 now), there was an attempt to use `this.buffer.stoppedChangingDelay = 0 `. I didn't find anything setting this property in the Atom docs (even for 1.19 versions), only the use of [getStoppedChangingDelay()](https://atom.io/docs/api/v1.19.5/TextBuffer#instance-getStoppedChangingDelay). Maybe it's something I'm not understanding correctly, but perhaps there's a default debounce time for autocompletion with TextBuffer?

**Comment by deankevorkian** [comment]
Solved with the last the merge of #1337 .
