### ISSUE TITLE
Errors aren't cleared

### ISSUE THREAD

**Issue by noseglid** [TypeStrong/atom-typescript#1333]
I'm a bit uncertain when this bug started happening, but it looks like errors aren't cleared properly.

If I get a typescript error, it informs me about it. When I fix it the error remains.
![typescript](https://user-images.githubusercontent.com/933880/29890143-de0c11d0-8dc6-11e7-95a5-ed522d26e3d3.gif)

I'm not sure if it's related or it's another bug, but every so often I see stuff like `unable to find identifier "somethn"` but in the code, the identifier it marks is `something` and it is spelled correctly. The typescript compiler works in all these cases where I get false errors from atom-typescript. My best guess is some cache/buffer corruption - but I haven't looked in to the code.

This recently started happening. I think the upgrade to 1.19.4 from 1.19.2 (never installed 1.19.3) is what made it start.

Edit: I just installed 1.19.2 and 1.19.3 and it's not a problem here. When running 1.19.4 I get the error (as shown in the gif above)

**Comment by GlenCFL** [comment]
I think most of these buffer corruption issues are due to a recent change in [text-buffer](https://github.com/atom/text-buffer), with it essentially failing to provide the list of changes whenever the user uses undo.

I've opened an issue on it there:
[atom/text-buffer#251](https://github.com/atom/text-buffer/issues/251)

**Comment by noseglid** [comment]
Thanks for the awesome quick response and action. Looks like it's all under
control, but if there's anything else I can provide, please don't hesitate
to ask.

**Comment by maxbrunsfeld** [comment]
Atom 1.19.5 is out and contains the fix.

**Comment by KSuttle-cng** [comment]
Noticing this in `1.21.0-beta0` also.

**Comment by JaxGit** [comment]
Same on Atom `1.32.0`
I just made a custom keybinding to 'typescript:clear-errors' and hit it often.

**Comment by lierdakil** [comment]
@JaxGit this particular issue has been fixed many times over. Please create a new one with more information than Atom version alone, i.e. your OS, your TypeScript version, the pacakges you're using, and if you can, a reproduction guide.
