### ISSUE TITLE
Linter shows many errors with no reason

### ISSUE THREAD

**Issue by piotrgredowski** [TypeStrong/atom-typescript#1334]
When writing any .ts file in Atom there is bunch of errors.
Disabling and enabling plugin (and Atom) helps only for few new lines of code. Then it shows new errors i.e. according to non-existing names of variables or functions.
Please notice that these errors are in part referring to non-existing line.

Atom    : 1.19.4
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
atom-typescript: 11.0.7

UPDATE: Closing file and opening it again clears these errors. But after writing and editing some code they will appear again. 
I am trying now on Atom 1.20.0-beta5 but it's still happening.

![screenshot from 2017-08-31 12-50-44](https://user-images.githubusercontent.com/4294480/29919841-3218ef6c-8e4b-11e7-8c69-6fb203737e4a.png)

**Comment by RafikSM** [comment]
Same issue here !

**Comment by jolivr** [comment]
Same... i've tried disabling, uninstalling, restarting. It's like the linter functionality is holding on to some old/corrupted versions of files.

**Comment by guncha** [comment]
This might be related to #1333 in which case the fix is to downgrade to 19.3 or wait for the nice folks on the atom team to fix the TextBuffer implementation.

**Comment by piotrgredowski** [comment]
Finally i downgraded to 1.19.3, I didn't notice any similar problems for now. And I'm waiting for fixing TextBuffer :)

**Comment by maxbrunsfeld** [comment]
😬  This one's my fault. I merged [a fix](https://github.com/atom/text-buffer/pull/252) already. It will go out in Atom 1.19.5.

**Comment by jolivr** [comment]
Works great in 1.19.5.. thanks max!

**Comment by demisx** [comment]
I still run into this issue in latest 1.20.1 Atom mostly when working with multiple panes.
