### ISSUE TITLE
Errors that are not present

### ISSUE THREAD

**Issue by danakt** [TypeStrong/atom-typescript#1335]
I do not understand why this happens. At any time, any error can appear. Even after I delete all the code, the error remains. It does not disappear until I re-open the file. I start writing code, for some time everything goes well, and then a similar errors occurs.

![0](https://user-images.githubusercontent.com/1110075/29967508-8d1ff30e-8f1f-11e7-9b13-1f00877f728e.png)
![1](https://user-images.githubusercontent.com/1110075/29967509-8d3ca594-8f1f-11e7-9360-2470b59ba379.png)
![2](https://user-images.githubusercontent.com/1110075/29967510-8d44b5d6-8f1f-11e7-8b0f-6c9169402586.png)

**Comment by guncha** [comment]
Try the newest Atom update.

**Comment by lierdakil** [comment]
Related to #1333.
