### ISSUE TITLE
isNaN accept only number argument

### ISSUE THREAD

**Issue by Armyw0w** [TypeStrong/atom-typescript#1339]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN

it accept strings too, lol.

**Comment by lierdakil** [comment]
If you want implicit conversions, why are you using TypeScript? Anyway, this isn't controlled by this package, so if you have to you might file an issue on TypeScript repo <https://github.com/Microsoft/typescript/issues>
