### ISSUE TITLE
Add Syntax Highlighting for css in template string

### ISSUE THREAD

**Issue by lukasoppermann** [TypeStrong/atom-typescript#1342]
Hey,

I and probably many other people are using typescript to write custom elements. A typical scenario is to create the html & css of the custom element in a template string.

```JavaScript
let template = document.createElement('template')
template.innerHTML = `<style>
:host{
   display: flex;
}
</style>
<slot></slot>`
```

Sadly css is not highlighted within a template string. It would be awesome if you could add highlighting for css within a template string within a `<style>` tag.

**Comment by rr-kalbeck** [comment]
+1
i'm using [styled-components](https://www.styled-components.com/). i need to keep switching my grammar to babel to get autocomplete and syntax highlighting

**Comment by lierdakil** [comment]
Autocomplete in template strings is tracked in https://github.com/TypeStrong/atom-typescript/issues/1351. 

As for the highlighting, see https://github.com/TypeStrong/atom-typescript/wiki/Grammar. TL;DR: we don't have resources to support a grammar fork, and there's an upstream grammar available, which conflicts with ours to boot. So we're discontinuing our grammar. Please, report any grammar-related issues upstream. Sorry for the inconvenience.
