### ISSUE TITLE
Auto-import feature not working

### ISSUE THREAD

**Issue by gsoldevila** [TypeStrong/atom-typescript#1344]
Hello,

A couple of key functionalities of atom-typescript are not working at all for me:

- Automatically adding import statements (neither Angular classes or my own exported classes within the project) 
- Auto-completing type names for external types

I have a project with a tsconfig.json, and I tried installing the _atom-typescript_ both from Atom package manager and command line. I also tried uninstalling and re-installing atom-typescript, linter and autocomplete-plus, as suggested in another post, without any success.

I did not see any message of the form:
> AtomTS: Dependencies installed correctly. Enjoy TypeScript

I'm on Elementary OS (Ubuntu 16.04), using  Atom 1.19.3 x64 and atom-typescript-11.0.9

Any clues or logs that I can check?

Thanks and kind regards

**Comment by lierdakil** [comment]
> Automatically adding import statements (neither Angular classes or my own exported classes within the project)

Uh... did we ever have that? Readme doesn't seem to suggest we do now at least.
 /cc @guncha

> Auto-completing type names for external types

What's external types?

> AtomTS: Dependencies installed correctly. Enjoy TypeScript

Wait, what?

**Comment by gsoldevila** [comment]
> Automatically adding import statements (neither Angular classes or my own exported classes within the project)
> Uh... did we ever have that? Readme doesn't seem to suggest we do now at least.
> /cc @guncha

Oops, my bad then. I thought this feature would be present. Indeed no mention about it on the list of features. I believe it would be a very nice addition.

> Auto-completing type names for external types
> What's external types?

For example, if I define a class _export class MyClassA { ... }_ in a file _a.ts_.
Then I intend to use this class on another file, say _b.ts_.
In order for autocomplete to work, I noticed I must manually add an import statement in b.ts.
Isn't there such thing as folder scanning to detect the available types?

> AtomTS: Dependencies installed correctly. Enjoy TypeScript
> Wait, what?

Stated [here](https://github.com/TypeStrong/atom-typescript/issues/549), after successful installation a couple of notification messages should appear, which I do not have when installing atom-typescript. Some people reported they experienced better autocompletion after fixing this problem. Unfortunately the proposed fix did not work for me. That's why I thought my installation was perhaps faulty and some features were missing.

Thanks and kind regards

**Comment by lierdakil** [comment]
> Oops, my bad then. I thought this feature would be present. Indeed no mention about it on the list of features. I believe it would be a very nice addition.

Actually, we do have that feature, I just wasn't aware of it. You need [intentions package](https://atom.io/packages/intentions) in addition to atom-typescript, then run 'intentions:show' command on an error with unknown import, kinda like this:
![image](https://user-images.githubusercontent.com/7275622/30805227-2dc9f156-a1f9-11e7-8f2c-8469abd3095f.png)

> Isn't there such thing as folder scanning to detect the available types?

Uhh... we're using tsserver for autocompletion suggestions, and I don't think it does that. More than that, I don't think I'd want local autocompletion scope to be polluted by every possible definition from whole project, I imagine that'd easily turn into a mess for anything larger than "hello world"-type application.

Atom will, however, automatically include identifiers from all currently-open buffers. Those have lowest priority, so expect to find them way down in the suggestions list.

> Stated here (https://github.com/TypeStrong/atom-typescript/issues/549)

That's old. Two years old in fact. We don't do that message anymore.

**Comment by gsoldevila** [comment]
I have _intentions_ installed. However, such a suggestion does not appear in my list:
![image](https://user-images.githubusercontent.com/25349407/30806594-c7b89a4a-a1f6-11e7-90cf-a0ce99a3e6ad.png)

And in the same folder, I have a sample.ts, of the form:
![image](https://user-images.githubusercontent.com/25349407/30806621-e0395104-a1f6-11e7-8066-20bd8a9b2fa9.png)

**Comment by lierdakil** [comment]
> However, such a suggestion does not appear in my list

I don't see the list at all. Um. Maybe a gif will help?
![intentions](https://user-images.githubusercontent.com/7275622/30807373-392f781e-a202-11e7-93b2-5d25bbc84747.gif)
you need to run 'intentions:show' command when text cursor is on the error (which is underlined in dotted red)

**Comment by gsoldevila** [comment]
Correct, don't have a list at all, just the tooltip from the TS compiler / linter. Any clues of what could be wrong?
![intentions-show](https://user-images.githubusercontent.com/25349407/30808253-a292583a-a1fd-11e7-99ce-b2b1c567b2bf.gif)

**Comment by teristam** [comment]
Hi, I am also having a similar problem. Tried everything but the list just doesn't show up. I am on Windows 10, atom-typescript 11.0.10, Typescript 2.3.4. I also tried to force update the Typescript to the latest version but still didn't work.

**Comment by gsoldevila** [comment]
@teristam I have the auto-import feature working now, but I believe it's provided by some other package I installed afterwards. Here's the list of packages I have currently installed:

- angular-2-typeScript-snippets@0.7.0
- atom-beautify@0.30.5
- atom-bootstrap4@1.4.0
- atom-npm-outdated@0.13.1
- atom-ternjs@0.18.3
- atom-typescript@11.0.10
- autoclose-html@0.23.0
- **autocomplete-modules@1.7.3** ===> (I believe that's one)
- busy-signal@1.4.3
- css-color-name@0.4.0
- emmet@2.4.3
- git-plus@7.10.0
- hyperclick@0.1.5
- intentions@1.1.5
- jumpy@3.1.3
- linter@2.2.0
- linter-ui-default@1.6.10
- minimap@4.29.7
- minimap-find-and-replace@4.5.2
- minimap-git-diff@4.3.1
- npm-plus@0.4.0
- refactor@0.11.5

**Comment by dotmagic** [comment]
This keep me busy for over 1 hour :(
I've found the solution in this comment: https://github.com/TypeStrong/atom-typescript/issues/549#issuecomment-325934841

Atom as a build-in Typescript support. If you install atom-typescript plugin there are 2 different kind of Typescript syntax. The solution is to switch to the one from atom-typescript. Done!

I will create another issue because I think atom-typescript should disable language-typescript to avoid this confusion.

**Comment by olee** [comment]
I also have no working auto-import feature (I had it once sometime in the past) but I already have language-typescript disabled.
...
After some investigation I found out this (probably) only affects Windows.
At this code https://github.com/TypeStrong/atom-typescript/blob/eb107ec87e966b00ae52a369e0101300d5f0339d/lib/main/atom/codefix/codefixProvider.ts#L31 `filePath` is written using backslash, however `errorPusher` stores errors using normal slashes.

I don't know WHERE this should be fixed (I guess the filePaths should just always be OS dependent as `textEditor.getPath()` is also OS dependent.

**Comment by lierdakil** [comment]
@olee, thanks for catching this. The tricky part here is tsserver only uses `/` as path separator on any platform. Which can actually mess with a lot of stuff.

Anyway, 12.3.7 should hopefully fix that particular bug, with any luck without introducing new ones.

... although bear in mind you need language-typescript **enabled** for 12.x, since we've decided it's pointless to try to fight with the bundled grammar and switched to it instead.
