### ISSUE TITLE
[Feature] Disable Linting / Error checking

### ISSUE THREAD

**Issue by wyqydsyq** [TypeStrong/atom-typescript#1347]
I'm currently using `atom-ide` in conjunction with `ide-typescript`, I would prefer to use the linter included in `ide-typescript` however I cannot disable the linter in this plugin resulting in my linter UI (`Diagnostics` pane of `atom-ide`) resulting in my linter warnings being shown twice, once from each plugin.

A simple checkbox on the settings page for this plugin to disable this feature would resolve this

**Comment by AlexanderOMara** [comment]
Would really like to see this as well, as I prefer to just use the configurable tslint instead.

Also since updating to TypeScript 2.9 I'm seeing a bunch of warnings I'd like to ignore, but don't seem to have any way to.

**Comment by wyqydsyq** [comment]
A similar feature to the one requested here was implemented in `ide-typescript`, so now I disable linting from that package and use the linting from this one to solve the duplicated warnings: https://github.com/atom/ide-typescript/issues/55
