### ISSUE TITLE
No error message showed today

### ISSUE THREAD

**Issue by wy193777** [TypeStrong/atom-typescript#1348]
I'm using atom 1.20.1 on Ubuntu 16.04. atom-typescript is also the newest. Already reinstalled the package several times but still shows no errors.

**Comment by wy193777** [comment]
Seems it's because 'linter' been disabled sometime. Maybe provide a warning when linter isn't available?

**Comment by rodmax** [comment]
It seems i get the same issue...
Notice that `linter-tslint` works fine
but compile/typings errors like

> Property 'bum' does not exist on type 'EventModel[]'

now i can see only in console from webpack :(

in dev console i see "unexpected response" warning from `atom-typescript/libs/client/client.ts`:
![tooltip_008](https://user-images.githubusercontent.com/6079597/31453342-8085ed0a-aeba-11e7-85fa-748aa2f6db2b.png)

**Comment by lierdakil** [comment]
@rodmax, you're apparently running into inotify limit, see https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#typeerror-unable-to-watch-path

It's either that, or you're running out of resources in some other way, which `ENOSPC` seems to suggest unambiguously.
