### ISSUE TITLE
Autocomplete disabled in template strings

### ISSUE THREAD

**Issue by mjbvz** [TypeStrong/atom-typescript#1351]
From https://github.com/Microsoft/typescript-styled-plugin/issues/3

## Problem
The [typescript-styled-plugin](https://github.com/Microsoft/typescript-styled-plugin) TypeScript server plugin adds IntelliSense and basic error reporting for styled-component css strings:

```ts
import styled from 'styled-components'

styled.button`
    color: blue;
`
```

This works fine in Sublime and VS Code, but with Atom TypeScript, autocomplete does not work in the styled component strings. I believe the current behavior is intentional ( https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/atom/autoCompleteProvider.ts#L109 ) but should be revisited now that TS Server plugins can add helpful suggestions in these contexts

**Comment by guncha** [comment]
Good suggestion. I have a local branch that does this since I was playing around with a GraphQL plugin. I'll just polish and publish that.

**Comment by kachkaev** [comment]
I'd be also glad to see this in Atom! Just moved one project to typescript and lost graphql syntax highlighting in `js` → `ts` files with such content:

```js
export default /* GraphQL */ `
# graphql types etc. (expected to be highlighted)
`;
```

GraphQL types etc. used to be [highlighted](https://github.com/gandm/language-babel#graphql-code-highlighting) by language-babel.

**Comment by lierdakil** [comment]
@kachkaev, syntax highlighting is handled by https://github.com/atom/language-typescript, which is downstream from https://github.com/Microsoft/TypeScript-TmLanguage (meaning Atom copies TextMate's grammar). Feel free to complain on either of those.
