### ISSUE TITLE
Syntax highlighting broken?

### ISSUE THREAD

**Issue by walleboom** [TypeStrong/atom-typescript#1359]
**11.0.10**
![syntax highlighting 11 0 10](https://user-images.githubusercontent.com/2277378/31489479-0875114c-af41-11e7-925d-59bfdebfa680.PNG)

**11.0.9**
![syntax highlighting 11 0 9](https://user-images.githubusercontent.com/2277378/31489480-08967a08-af41-11e7-9636-cd055a23e80d.PNG)

**Comment by lierdakil** [comment]
The grammar and highlighting is provided by https://github.com/Microsoft/TypeScript-TmLanguage. And yes, we updated it recently in https://github.com/TypeStrong/atom-typescript/pull/1358.

I don't think it's broken, it just added `support.class.component` scope for component-tags, which I find is a reasonable change.

**Comment by walleboom** [comment]
Oh I see! That's reasonable.
