### ISSUE TITLE
Colon (:) grey block inside @Component({})

### ISSUE THREAD

**Issue by chiangs** [TypeStrong/atom-typescript#1360]
Mac OS 10.13
Atom 1.21.1
seti-syntax 1.0.1
seti-ui 1.9.0
Colon `:` is just a grey block within the @Component({}) section, but fine outside it in the same TypeScript file.

<img width="634" alt="screen shot 2017-10-13 at 08 56 18" src="https://user-images.githubusercontent.com/10984593/31534301-a74c6742-aff6-11e7-83cb-26efbd8e312a.png">

When I switch both atom-typescript and language-typscript off, the colons show up.

**Comment by RyanMitchellWilson** [comment]
I'm getting the same problem

**Comment by guncha** [comment]
I'm seeing something similar, but only with a few themes. The default Atom theme (Atom Dark) has special styling for the `.meta.separator` class (the new scope that was introduced with the recent grammar update) and it looks ok:

Atom Dark
![image](https://user-images.githubusercontent.com/679632/31570293-62ef8cbe-b050-11e7-8d4d-48601ee66a71.png)

Atom Light (does not have any special coloring)
![image](https://user-images.githubusercontent.com/679632/31570316-8627b6ca-b050-11e7-8e0f-c89270fef19b.png)

One Dark (this is what I use)
![image](https://user-images.githubusercontent.com/679632/31570329-9d8d6fb2-b050-11e7-9639-49d346046dbb.png)

One Light
![image](https://user-images.githubusercontent.com/679632/31570340-aa68a18e-b050-11e7-816a-5c1e8b7101f3.png)

You can see that the last one has the same problem. It is applying a style that looks like this:
![image](https://user-images.githubusercontent.com/679632/31570343-c25454b4-b050-11e7-9892-90c1d235a49c.png)

Clearly anything with this class is not going to be readable, which makes me think that this is a problem with the themes and not the grammar. The themes can either leave the `.meta.separator` class alone and it will work just fine or make sure they're applying reasonable styles.

@chiangs, @RyanMitchellWilson for the time being you can just add this to your custom stylesheet to address the problem:

```scss
.syntax--meta.syntax--separator {
  color: inherit;
  background-color: inherit;
}
```

**Comment by chiangs** [comment]
@guncha thanks, that was exactly it and fixed it for me.

**Comment by Volcanic-Penguin** [comment]
In One Dark the curly braces for a class are yellow, as well as semicolons inside the class, can be fixed with the following; 

```
.syntax--punctuation.syntax--definition.syntax--block.syntax--ts,
.syntax--punctuation.syntax--terminator.syntax--statement.syntax--ts {
  color: white;
}
```

**Comment by tshowers** [comment]
@guncha Thanks for the solution, the grey square was so annoying.

**Comment by daniel-gwilt-software** [comment]
This seems to be a bug in the "One Light" syntax theme.  As soon as I changed to the "Atom Light" syntax theme the issue went away.

**Comment by lierdakil** [comment]
This is technically unrelated, but I will treat this as a grammar-related issue and close it due to https://github.com/TypeStrong/atom-typescript/wiki/Grammar
Feel free to yell at me if you think I'm wrong.

**Comment by jadsonjs** [comment]
Just to make it clearer.

Write this:

.syntax--meta.syntax--separator {
  color: inherit;
  background-color: inherit;
}

in end of the file: %USERPROFILE%\.atom\styles.less
