### ISSUE TITLE
Typescript bottom bar only shows "Emit Success" label, no error messages, no status related to TS. Also linting is not working properly.

### ISSUE THREAD

**Issue by patrickoliveras** [TypeStrong/atom-typescript#1361]
I just got started on typescript and this atom package was highly recommended. But I was really confused at the beginning since it only really had Syntax highlighting and an obscure way to watch files for compilation.

Atom version: 1.21.1
Atom-typescript: 11.0.10
OS: macOS Sierra 10.12.6

![image](https://user-images.githubusercontent.com/11946875/31550722-da2d9dba-aff7-11e7-9f8e-9facc47aea97.png)

**Comment by lierdakil** [comment]
For error reporting to work, you need either

- https://atom.io/packages/linter
- https://atom.io/packages/linter-ui-default

or

- https://atom.io/packages/atom-ide-ui

I personally would recommend the latter option, but YMMV.

**Comment by lierdakil** [comment]
P.S. Re-reading my comment, I wonder if it's clear what I meant. In case it's not, you need either BOTH `linter` and `linter-ui-default` OR `atom-ide-ui`

**Comment by lierdakil** [comment]
ETIMEDOUT, closing.
