### ISSUE TITLE
go to declaration / hyperclick not working on css imports

### ISSUE THREAD

**Issue by rr-kalbeck** [TypeStrong/atom-typescript#1365]
holding cmd and hovering over a css import shows the hand cursor but cmd-clicking a css import does not take me to the file.

**Comment by guncha** [comment]
Can you show us an example? In the best case scenario, you would be taken to the definition file that allows you to `import style from "foo.css"` and probably looks like this:

```ts
declare module "*.css" {
  export default function styles(): any // or whatever the type is here
}
```

As such, Typescript is blissfully unaware of any actual stylesheets that you're importing.
