### ISSUE TITLE
"needs to install" linter when atom-ide installed

### ISSUE THREAD

**Issue by lukescott** [TypeStrong/atom-typescript#1368]
I get the following dialog:

![dialog](https://user-images.githubusercontent.com/486224/32239988-5488249c-be29-11e7-96d7-6ca0bf4712eb.png)

I have atom-ide installed. The README says either atom-ide or linter, so it shouldn't be asking me to install linter if the other option is installed.

**Comment by lierdakil** [comment]
Actually, readme you're looking at is for as-of-right-now unreleased version. Sorry about the confusion. Readme for the latest released version is on https://atom.io/packages/atom-typescript

But a fair point, we really should avoid this.

**Comment by lierdakil** [comment]
@guncha, I'm wondering if we should default to `atom-ide-ui` actually if neither that nor `linter` is installed. Thoughts? I'll whip up a PR detailing proposed changes and rationale in a bit, but just in case asking here as well.

**Comment by Thorski** [comment]
What action should I take when I get this dialog?   I have atom-ide-ui installed.   Do I need to install linter or not?

**Comment by lukescott** [comment]
`atom-ide-ui` provides all the features that `linter` does. So you won't have to install `linter`. I believe `atom-ide-ui` provides additional features though. You can safely dismiss the dialog.

I click "No Thanks" every time I launch Atom to make sure this bug gets fixed eventually. You can click "Never" to not be bugged by it again.

**Comment by lierdakil** [comment]
This should be fixed in v12. Thanks for your patience.
