### ISSUE TITLE
Symbols view

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#137]
https://atom.io/packages/symbols-tree-view for inspiration

**Comment by Ciantic** [comment]
:+1: I can't use this plugin until it's implemented, only way I navigate within file is through Symbols view. In eclipse called "Quick Outline".

**Comment by basarat** [comment]
That http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2FgettingStarted%2Fqs-Quickviews.htm looks very different from what I was recommending here and I think it's better. So I'll have a first cut of that.

**Comment by basarat** [comment]
![image](https://cloud.githubusercontent.com/assets/874898/6819712/b2514ade-d319-11e4-88a3-6342401bfb1b.png)

after my next push :heart:

**Comment by Ciantic** [comment]
I don't know if it's okay to comment but I love this. :heart: It's now better than in other languages as it includes more information.

As a trivial side note, I like my symbols view more condensed so I've added to my StyleSheet this:


    .symbols-view .primary-line {
      padding: 0 !important;
      line-height: 1.2;
    }

    .symbols-view .secondary-line {
      padding: 0 !important;
      line-height: 1.2;
    }

    .symbols-view .two-lines {
      padding: 5px 0 5px 5px !important;
    }
