### ISSUE TITLE
[Feature Request] Localized diagnostics messages for TS 2.6

### ISSUE THREAD

**Issue by InExtremaRes** [TypeStrong/atom-typescript#1371]
Since TypeScript 2.6 a new option for localized diagnostics was added ([more info](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html)).

Is there any possibility to add this option to Atom diagnostics messages?

**Comment by lierdakil** [comment]
Since we're not calling `tsc` directly, we can't really pass CLI options to it. In fact, almost everything, including diagnostics, is handled by `tsserver`. Maybe try specifying `locale` in `compilerOptions` in `tsconfig.json`?

**Comment by InExtremaRes** [comment]
Oh, I see. Using `locale` in `compilerOptions` doesn't seem to work, not even for CLI `tsc`. Documentation for `tsserver` mentions `--locale` option, although it is a CLI option too. Maybe `tsserver` can be executed with that option at starting (with an appropriate settings window option)?
