### ISSUE TITLE
Validate `tsconfig.json`

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#138]
Warn users about invalid `compilerOptions`. 

* [ ] casing issues
* [ ] invalid values

We already warn about not being able to parse the json (invalid json).

**Comment by nycdotnet** [comment]
@basarat Should I register this project here?  http://up-for-grabs.net/#/tags/typescript

**Comment by basarat** [comment]
@nycdotnet already started this morning : https://github.com/dahlbyk/up-for-grabs.net/pull/173 :heart:

**Comment by basarat** [comment]
![invalidprojectoptions](https://cloud.githubusercontent.com/assets/874898/6500155/caf15f02-c35b-11e4-84f5-f35674e3daf2.gif)

For @johnnyreilly :heart:

**Comment by johnnyreilly** [comment]
Thanks chap!  :heart:
