### ISSUE TITLE
Ability to restart worker via command

### ISSUE THREAD

**Issue by isiahmeadows** [TypeStrong/atom-typescript#1380]
With the [frequent](https://github.com/Microsoft/TypeScript/issues/14628) [OOM](https://github.com/Microsoft/TypeScript/issues/14628) [bugs](https://github.com/Microsoft/TypeScript/issues/16029) I've run into with TS, it'd be nice to be able to kill (if alive) and restart the TS worker so I can resume having types checked after doing whatever to fix it short term. (It'd also be helpful after, say, a TS update, so I wouldn't have to restart my editor.)

**Comment by guncha** [comment]
I just use `Ctrl+Alt+Command+L` to reload the window, but yeah, a command would be nice. Even nicer would be Typescript not crashing.

**Comment by shellscape** [comment]
Seconding this. I can't count how many times a day I need to kick Atom when working with linked modules and updating the type definitions. /cc @lierdakil

**Comment by shellscape** [comment]
@lierdakil which commit in #1456 addressed this issue?

**Comment by lierdakil** [comment]
e4a753b33bf4f1e389f49a006734f8af46e6f308
