### ISSUE TITLE
Missing dependency: tslib

### ISSUE THREAD

**Issue by GlenCFL** [TypeStrong/atom-typescript#1381]
The `tsconfig.json` file under `lib` uses the `importHelpers` option, which results in a require on `tslib` being placed into the generated JS files. The issue is that `tslib` was removed as a dependency recently, so running `npm install --production` against the master branch right now will result in the package failing to activate due to this missing dependency.

**Comment by lierdakil** [comment]
Ouch. Entirely my fault. Thanks for catching. I was cleaning dependency list and apparently just happened to throw tslib away as well somehow. Weird that CI didn't catch that, since I'm pretty sure we test for activation.

`tslib` dependency re-added in master.
