### ISSUE TITLE
not functioning correctly inside of .test.ts files (such as those used by jest)

### ISSUE THREAD

**Issue by ryanhornberger** [TypeStrong/atom-typescript#1384]
When working inside of .test.ts files this library cannot find other ts files, even .ts standard files. It also does not recognize the functions that jest injects during the runtime. 

It may be faster to just exclude test.ts files or offer a configuration that allows the developer to exclude specific file conventions for now. 

I may try to help write a PR for this tonight if I get some time.

**Comment by lierdakil** [comment]
Since what you describe is handled by tsserver, with this package being a relatively thin wrapper around that, I wonder if it's a deficiency in your setup. Check your `tsconfig.json`?

**Comment by ryanhornberger** [comment]
currently my tsconfig.json contains the following excludes: 

"exclude": [
      "node_modules",
      "**/*.test.ts"
  ]

**Comment by ryanhornberger** [comment]
Building, linting, and testing all work great.

**Comment by guncha** [comment]
`"**/*.test.ts"` is the problem. You probably have it there to avoid `tsc` building the test files, but it also excludes the tests from the project context, meaning that types that are global or explicitly added using `types` directive is not going to apply to the test files.

The simplest solution is to include all typescript files in the project by default, but exclude the tests when building (can be done with a separate tsconfig.json and `extends` directive as well as using a bundler like webpack).

**Comment by lierdakil** [comment]
I believe this is more or less resolved, so closing. Feel free to yell at me if you think I'm wrong.
