### ISSUE TITLE
First TS keyword in file misses last character of bold highlighting

### ISSUE THREAD

**Issue by johnnyreilly** [TypeStrong/atom-typescript#139]
See screenshot illustrating below - look out for **modul**e and **interfac**e

![screenshot 2015-03-02 17 05 54](https://cloud.githubusercontent.com/assets/1010525/6445807/6bf18fae-c0fe-11e4-9c34-d208d9253879.png)

This only seems to be an issue if the first word in a file is TS keyword.  You can see here it's not a problem:

![screenshot 2015-03-02 17 10 26](https://cloud.githubusercontent.com/assets/1010525/6445886/20f9077e-c0ff-11e4-8bf3-179d1a243c34.png)

**Comment by basarat** [comment]
@johnnyreilly what theme's (ui + syntax) + atomts version are you using. I don't seem to be getting this :

![image](https://cloud.githubusercontent.com/assets/874898/6451871/a56e1f0e-c185-11e4-9407-1c2ee0b0255a.png)


Note: In your example `{` also gets eaten up i.e. you have `module controllers ` instead of `module controllers {`. This is a clear example of Grammar tokenization gone wrong (a bug in our or TypeScript language service code). I'd be very interested in investigating. Can you post an example `.ts` file?

**Comment by johnnyreilly** [comment]
I hadn't spotted the `{` vanishing - you have keener eyes than I!  :laughing: 

The files in the shot are these:

https://github.com/johnnyreilly/proverb-offline/blob/master/Proverb.Web/app/sayings/sayings.ts
https://github.com/johnnyreilly/proverb-offline/blob/master/Proverb.Web/app/app.ts

My UI and syntax themes are Atom Light.  I'm using `atom-typescript@0.74.0`

**Comment by basarat** [comment]
I suspect this is a file encoding issue. Two bytes off feels like a BOM marker not getting detected.

**Comment by johnnyreilly** [comment]
Some odd behaviour to report.  I just fired up atom again and `app.ts` wasn't illustrating the behaviour whilst `sayings.ts` was.

Both files are UTF-8 according to atom.

**Comment by basarat** [comment]
Having a BOM in the file does throw it off. : https://github.com/TypeStrong/atom-typescript-examples/tree/master/bomtest furthermore its how the typescript classifier classifies it. It completely ignores the BOM.

**Comment by johnnyreilly** [comment]
Interesting.  What do you make of both files being UTF-8 but only one illustrating the behaviour? (I'm assuming that right clicking in the editor and clicking "change encoding" is an adequate test?

![screenshot 2015-03-03 11 27 55](https://cloud.githubusercontent.com/assets/1010525/6461496/5b795450-c198-11e4-91c4-3d8fcfcf6574.png)

**Comment by basarat** [comment]
> (I'm assuming that right clicking in the editor and clicking "change encoding" is an adequate test

No. The quickest way I find is to save with "Advanced save options" in visual studio using an encoding that has "with signature" marked. e.g. 
![image](https://cloud.githubusercontent.com/assets/874898/6461612/a0b59d50-c1f5-11e4-8142-3b84f53cdbf8.png)

**Comment by johnnyreilly** [comment]
By Jingo you're right!  Atom has lied to me :fearful: 

![screenshot 2015-03-03 11 38 48](https://cloud.githubusercontent.com/assets/1010525/6461672/203dc7c0-c19a-11e4-97f8-9b11553cb61c.png)
![screenshot 2015-03-03 11 39 11](https://cloud.githubusercontent.com/assets/1010525/6461673/2211cf56-c19a-11e4-966b-c89133ca13ad.png)

So is the conclusion that UTF-8 is a problem? (Given that `sayings.ts` which is UTF-8 demonstrates the problem and `app.ts` which is not doesn't)

**Comment by basarat** [comment]
> UTF-8 is a problem

A combination of how Atom + TypeScript classifies BOM. TypeScript ignores it (a bad thing ... I would have liked it to classify it as whitespace). Atom doesn't want other's to classify it (this makes the bad thing by TypeScript a good thing), except that atom will still give you the string with the BOM and expect *you* to not return it as a part of your classification. 

You can see the commit for details :heart:

**Comment by basarat** [comment]
published as `v0.78.0`

**Comment by johnnyreilly** [comment]
Cool - so the fix was in atom-typescript rather than elsewhere.

**Comment by basarat** [comment]
yes :heartbeat:

**Comment by basarat** [comment]
BTW check out them fancy panels in the next version ;) 
![image](https://cloud.githubusercontent.com/assets/874898/6461793/be1f26e8-c1f7-11e4-8841-f3d854f0bb39.png)

Off to bed for me

**Comment by johnnyreilly** [comment]
Nice - that's pretty clear.  I remembered seeing discussions around TypeScript and encoding elsewhere but had completely forgotten the details.  I'm just upgrading to 0.78.0 now - will report back....

**Comment by johnnyreilly** [comment]
Sleep well chap! Good work :clap:

**Comment by johnnyreilly** [comment]
I've just given it a test with 0.78 and there's good and bad news.

The good news is the highlighting now looks different:

![screenshot 2015-03-03 12 07 20](https://cloud.githubusercontent.com/assets/1010525/6462089/f6d784b2-c19d-11e4-9694-a061a3343c04.png)

But unfortunately `module` doesn't appear to be bold now?  Or at least not as bold as it was before....

The slightly worse news is that the TypeScript build doesn't seem to work at all now.  Both saving and ctrl+shift+b result in this:

> No Build. Press (ctrl+shift+b / cmd+shift+b ) to start a build for an active TypeScript file's project.

**Comment by basarat** [comment]
>
> Quick note : the shortcut only works if your focus cursor is in an editor
> window.
>

If that fixes it for you we can make the shortcut more global later.


-- 
Cheers,
BAS (*BAS*arat *A*li *S*yed)
0422 888 669
http://basarat.com

**Comment by basarat** [comment]
The build shortcut + goto definition shortcut are a bit more global so they should just work. Try `0.79.0`

**Comment by basarat** [comment]
Regarding it not appearing as bold : it seems to be tokenize correctly as you can see :

![image](https://cloud.githubusercontent.com/assets/874898/6478827/dccf0e9a-c28e-11e4-8734-262391309a4a.png)

I am assigning `module` the category `storage.modifier` and not `keyword` because of previous work that does the same thing : https://github.com/fdecampredon/brackets-typescript/blob/master/src/main/mode.ts#L101 

`module` will look at the same as `class` and `var`. How it looks will depend on your theme. I should do the same with `interface`. These decisions are somewhat arbitrary on my part. :heart: I'll clear those up later but there is no unintentional side effect that needs to be further investigated here :+1:

**Comment by johnnyreilly** [comment]
Hey @basarat,

>  `module`  will look at the same as  `class ` and  `var` . How it looks will depend on your theme.

Yup the theme lends it almost no visibility - maybe I'll switch!  But it seems to share the same presentation as `class` and `var` as you suggest.

I'm still getting no compilation but I'll try and clean install of Atom and atom-typescript and see if that resolves it.  (Imagine trying that with Visual Studio - would take days!)

If the compilation issue still presents I'll open new issue.

**Comment by johnnyreilly** [comment]
Completely clean install and I can't compile at all.  However I think it's related to some problem with my system - when I roll back to atom-typescript@0.74 I still get no compilation (even though `tsc` on the command line works fine)....

I'm not about to rebuild this machine so I'm going to look at this as an opportunity to try out atom on Linux...

**Comment by johnnyreilly** [comment]
And after all that it was a return of `module: null` in `tsconfig.json`... sigh.  Fixed now.

**Comment by basarat** [comment]
Sorry about that. I've made this my main task : https://github.com/TypeStrong/atom-typescript/issues/138 will have it sorted today after work. Hopefully before you get to read this in your timezone ❤️
