### ISSUE TITLE
Cannot find module 'xyz'

### ISSUE THREAD

**Issue by matths** [TypeStrong/atom-typescript#1391]
Hi!

Maybe it's not an issue but a problem only for me, but I am not able make atom-typescript not to report ```Cannot find module 'xyz'``` errors in the diagnostics pane.
To reproduce, you can ```git clone https://github.com/DanielRosenwasser/typescript-vue-todomvc``` which comes with a tsconfig.json file, I did not change.
I already understand that atom-typescript utilizes sourcegraph/javascript-typescript-langserver, but I have no clue, why it does not resolve the modules - all modules, whether implicit node modules like ```path```or explicit node_modules like e.g. ```Vue```.

I really would appreciate some help with this.
Br,
@matths

**Comment by lierdakil** [comment]
We do not utilize javascript-typescript-langserver. You sure you're not confusing us with [ide-typescript](https://github.com/atom/ide-typescript)?

Typescript will report that it cannot find a module if it can't find definitions for said module, and not all modules bundle (or even have) TypeScript definitions. For popular packages, you can usually find definitions in https://www.npmjs.com/~types (install via `npm i @types/...`, a good idea is to save those into `devDependencies`)

**Comment by matths** [comment]
@lierdakil you're absolutely right, I confused atom-typescript with ide-typescript! And thanks for explaining ```@types/*``` to me, which I suddenly understand much better. I close this non-issue. ;)
