### ISSUE TITLE
Auto complete suggestions priority not working

### ISSUE THREAD

**Issue by yubaoquan** [TypeStrong/atom-typescript#1397]
Since the priority is set to 3, the suggestion items of atom-typescript are still on top of snippets. My custom ts snippets are at the bottom.  I set the priority to 50, still not working.

**Comment by lierdakil** [comment]
Try lowering it, not raising.

**Comment by lierdakil** [comment]
Don't forget you need to restart Atom for the setting to take effect.

**Comment by yubaoquan** [comment]
Set to 0, and restart, it works. Thank you!
