### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by TheAndrewFranklin** [TypeStrong/atom-typescript#1399]
![screen shot 2018-01-21 at 3 54 26 pm](https://user-images.githubusercontent.com/11582190/35200441-70fd20ac-fec3-11e7-97a9-243edf352f2b.png)

Can anything be done about function name and parameter(s) color?

**Comment by lierdakil** [comment]
Pleas see https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#syntax-highlighting-is-bad and https://github.com/atom/language-typescript/issues/16
