### ISSUE TITLE
Performance regression 0.63.0 to 0.64.0

### ISSUE THREAD

**Issue by csnover** [TypeStrong/atom-typescript#140]
In 0.63 and earlier, saving a file after the first time caused emit to happen pretty much immediately. Upon updating to 0.64 the saves are much slower. This is caused by this commit:

```
commit a72718f1ad0f51f77703c364a6ffb57f090f8026
Author: Basarat Syed <basaratali@gmail.com>
Date:   Fri Feb 20 15:32:58 2015 +1100

    regenerate the files glob on file save
    closes #106

:040000 040000 bcc74c13fd9e2a93058b271274baeea95dea3d51 d1e2e5613d550d5eb4c888b612e44476b29c9602 M	lib
```

This commit introduces a sync file write that blocks the rest of the system and makes it sloooww over network shares.

**Comment by basarat** [comment]
Alright. I'll revert that and go back to file watching for tsconfig + invalidating the cache for a new file resolving to a tsconfig that doesn't have this file mentioned last time we read it. Same as before but this time will not take an additional chokidar dependency and hope fs.watchFile will be sufficient.

**Comment by basarat** [comment]
I'll assign myself before tackling it.
