### ISSUE TITLE
Just want to send my gratitude

### ISSUE THREAD

**Issue by jonyeezs** [TypeStrong/atom-typescript#1400]
I used atom-typescript in its early days till it did its first overhaul. It became unusable.

ide-typescript came out and it was nice. One thing i hated that it was so coupled to nuclide.

Which i felt went against the idea of Atom being modular and community driven.

It really killed innovation.

Till i came back to atom-typescript. You guys have done tremendous work! I'm glad we have someone like @lierdakil working on this.

Thank you so much. And I'll give this another go and hopefully be a supporter.

Thank you for your work

**Comment by lierdakil** [comment]
Thank you for your kind words. Hopefully, we won't disappoint.
