### ISSUE TITLE
spawn tsc ENOENT

### ISSUE THREAD

**Issue by 1337iceskater** [TypeStrong/atom-typescript#1403]
On Windows it is not possible to run tsconfig as it will always fail with the following message:
spawn C:\Users\user\.atom\packages\atom-typescript\node_modules\typescript\bin\tsc ENOENT

and has the following stack trace:
Error: spawn C:\Users\user\.atom\packages\atom-typescript\node_modules\typescript\bin\tsc ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

I am therefore not able to create the tsconfig.json file and I would suspect that other functionality will not work either.
When I try to run the above file from command line, it is failing as well. But the file is existing in the file explorer, so there must be something else.

I have therefore checked the content of that file and found it to be the following:
#!/usr/bin/env node
require('../lib/tsc.js')

Of course, the path to node does not exist on Windows, so that may be the root cause.

Is that considered a bug when downloading the package via Windows Atom editor?
Or is there any fix to be done to this?

**Comment by lierdakil** [comment]
Hello. Thank you for the report.

Config initialization was only recently reintroduced, and the fact that `tsc` doesn't run on Windows natively slipped my mind when reviewing the relevant pull request. Everything else *except* config initialization should work though, so your suspicion is incorrect.

Anyway, v12.1.2, which should hopefully fix this, has been released just now. Please update and let me know how it goes.

**Comment by 1337iceskater** [comment]
Absolutely correct. This new version fixed that issue and I am impressed on how fast that has been adressed!

Thanks a lot!
