### ISSUE TITLE
Suggestions appearing in places where no suggestions should appear

### ISSUE THREAD

**Issue by csnover** [TypeStrong/atom-typescript#141]
Finish a statement, e.g.

```ts
function foo() {
  this.foo;/*1*/
  /*2*/
}
```

With the cursor at `/*1*/` or `/*2*/`, after having typed the previous `;` or `\t`, suggestions will appear, but should not.

**Comment by csnover** [comment]
Sorry, accidentally hit Enter in the subject line. Description is there now. :disappointed:

**Comment by basarat** [comment]
@csnover can you give me a screenshot? Note: suggestions will appear *inside* comments. I actually find those helpful. I think they appear from *other default* providers that come with `autocomplete-plus`. But to be sure a screenshot at the exact location would help me understand better

**Comment by csnover** [comment]
![screen shot 2015-03-02 at 22 53 37](https://cloud.githubusercontent.com/assets/229244/6456756/033deb2a-c12f-11e4-83d6-da63630e674e.png)

**Comment by basarat** [comment]
@csnover this is intentional. Although *not because of our code*. Autocomplete+ is now super aggressive (and I think that's a good thing). This is the reason I had to remove `commit on enter` though : https://github.com/TypeStrong/atom-typescript/commit/9c17b7349b08703d3933759a8a6ca25496542669

**Comment by csnover** [comment]
I can’t think of a reason to tell users all the possible completions like this. I’ve never had an IDE do this without explicit request (i.e. hotkey), because as you noted in that commit it breaks all sorts of things (and it isn’t helpful).

This is not matching normal autocomplete-plus behaviour. Try typing in a JavaScript file and note that autocompletes don’t start until you actually start typing a word, not punctuation.

**Comment by csnover** [comment]
I suspect this may also be breaking auto-indent, which seems to have stopped working properly at some point within the last couple of weeks.

**Comment by basarat** [comment]
> I suspect this may also be breaking auto-indent, which seems to have stopped working properly at some point within the last couple of weeks

I've noticed as well. I'd be happy for a fix. Working on better panels right now though.

**Comment by basarat** [comment]
> I suspect this may also be breaking auto-indent

I think moving to a dynamic code based grammar parsing broke it. Before that it was taken care by us inheriting from `.source.js`. auto-indent feature will be tracked here : https://github.com/TypeStrong/atom-typescript/issues/159

**Comment by MarlonFan** [comment]
@basarat Me Too!

**Comment by vilic** [comment]
Nice to see it's been marked as high priority.

**Comment by basarat** [comment]
I haven't found a better solution than the one I've commited so there it is. 
released with `v4.0.11`
