### ISSUE TITLE
Shift+f12 (find-references) finds the correct line but goes to the wrong file

### ISSUE THREAD

**Issue by mininek** [TypeStrong/atom-typescript#1413]
I am not sure if this is the place to report this, please let me know if it is not and where else should I go for help. I have searched the internet high and low for a similar issue but couldn't find anything that fixes the issue.
I have multiple projects in Atom and I use Shift+f12 a lot. After the latest update for atom-typescript I have been seeing the following error: The window showing the files and lines where the usage is occurring comes up and I click on one of the lines. Instead of going to the referenced file in the same project, Atom opens a new file in the project that is at the top of the tree view in the pane on the left (with the same name as the referenced file in the other project). Of course, the new file is a empty, there are no lines in it. Shift+f12 works fine if I am working in the topmost project in the tree view in the left pane.

**Comment by lierdakil** [comment]
Thanks for reporting. Should be fixed with 12.3.6.

**Comment by mininek** [comment]
Thanks for fixing this! It works as expected now. That fix was really fast!!
