### ISSUE TITLE
Cannot find module when node_modules dir is symlinked

### ISSUE THREAD

**Issue by gwely** [TypeStrong/atom-typescript#1415]
I am working in an Ubuntu Vagrant box on a Windows host. To avoid issues with setting up symlinks in the `node_modules/.bin` I am using [sympm](https://github.com/ezekg/sympm).

`atom-typescript` is not recognizing packages in the symlinked node_modules directory. I get the `cannot find module 'request'.` error.

I have copied the project to another directory and ran `npm i`, resulting in a not-symlinked node_modules dir, and atom-typescript has no problem finding the module and the types within.

Here is some version info:

atom: 1.25.0
atom-typescript: 12.3.5
typescript: 2.7.2

**Comment by lierdakil** [comment]
All module resolution is done through tsserver. tsserver shouldn't really care whether `node_modules` is symlinked or not, so the root of the issue is likely elsewhere.

Make sure relevant typings are installed (via `@types` or otherwise)

**Comment by gwely** [comment]
Yes, you are right - I've figured out the real issue: atom-typescript can't find the node_modules dependencies because I am running Atom on the Windows host which has no access to the symlinked directory in the Linux Vagrant box. This seems so obvious now, of course :)
