### ISSUE TITLE
Guys i was trying to make a user editable polygon in ionic 3 , but not coming ...help me to do this

### ISSUE THREAD

**Issue by Yuvanes** [TypeStrong/atom-typescript#1416]
import { NavController } from 'ionic-angular';
import {
  LatLng,
  GoogleMaps,
  GoogleMap,
  GoogleMapsEvent,
  GoogleMapOptions,
  CameraPosition,
  MarkerOptions,
  Polyline,
  Polygon,
  PolygonOptions,
  Spherical,
  // MapType,
  Marker
} from '@ionic-native/google-maps';
import { Component } from "@angular/core/";
import { Geolocation } from '@ionic-native/geolocation';
// var newShape;
    // var map;
    // var drawingManager;
@Component({
  selector: 'home',
  templateUrl: 'home.html'
})
export class HomePage {
  map: GoogleMap;
  me: any;
  locations = []
  

  constructor() { }

  ionViewDidLoad() {
    this.loadMap();
  }

  loadMap() {

    let mapOptions: GoogleMapOptions = {
      // camera: {
      //   target: {
      //     lat: this.me._x,
      //                  lng: this.me._y
      //   },

      //   zoom: 18,
      //   tilt: 30,
      // },
      MyLocation:true,
      MyLocationButton:true,
       disableDefaultUI: true,
      mapType: "MAP_TYPE_HYBRID",

    };

  let map= this.map = GoogleMaps.create('map_canvas', mapOptions);

    // var div = document.getElementById("map_canvas");
    // var map = new GoogleMaps()

    // Wait the MAP_READY before using any methods.
    this.map.on(GoogleMapsEvent.MAP_READY)
      .subscribe(() => {
        console.log('Map is ready!');

        this.map.setMyLocationEnabled(true)

        this.map.setMyLocationButtonEnabled(true)

        this.map.on(GoogleMapsEvent.MAP_CLICK).subscribe((location: any) => {

          console.log(location);

          this.locations.push(new LatLng(location[0].lat, location[0].lng));

          console.log(location);

          let PolyLineInfo;
     

              
           this.map.addPolygon({
               'points' : this.locations , 
               'strokeColor'  :  '# AA00FF' ,  
               'fillColor'  :  '# 00FFAA' , 
               'strokeWidth' :  4 ,
               'editable' :true,
          }).then((info: Polyline) => {

            // info.setPoints
            PolyLineInfo = info;
            
          
          }

          );
          
        //   PolylineOptions add (LatLng point)

        //     let drawingManager = this.map.DrawingManager({
        //   'drawingMode': google.maps.drawing.OverlayType.MARKER,
        //   'drawingControl': true,
        //   'drawingControlOptions': {
        //     'position': google.maps.ControlPosition.TOP_CENTER,
        //     'drawingModes': ['marker', 'circle', 'polygon', 'polyline', 'rectangle']
        // });

        //    drawingManager.setMap(map);

          this.map.addMarker({
            
            animation: 'DROP',
            draggable: true,
            
            position: {
              lat: location[0].lat,
              lng: location[0].lng,
            },
            customInfo: this.locations.length - 1
          })
            .then(marker => {

              marker.on(GoogleMapsEvent.MARKER_DRAG_END)
                .subscribe((marker) => {

                  let index = marker[1].get("customInfo");

                  this.locations[index] = new LatLng(marker[0].lat, marker[0].lng);
                            

                  PolyLineInfo.remove();

                  console.log(this.locations[0]);
                  console.log(this.locations[1]);
                  console.log(this.locations[2]);
                                    

                 
                                    let dis = Spherical.computeSignedArea(this.locations);
                                    
                                          console.log(dis);
                                    let km = Spherical.computeLength(this.locations);
                                         console.log(km);

                  this.map.addPolygon({
                          'points' : this.locations , 
                          'strokeColor'  :  '# AA00FF' ,  
                          'fillColor'  :  '#FF0000' , 
                          'strokeWidth' :  4 ,
                          'editable' :true,
                  }).then((info: Polyline) => {

                    PolyLineInfo = info;
                  }

                  );

                

             });

            })
   });  
     
    });

  }
}

**Comment by lierdakil** [comment]
This is not a general TypeScript help forum.
