### ISSUE TITLE
False error highlights for default generic types

### ISSUE THREAD

**Issue by miaucl** [TypeStrong/atom-typescript#1418]
I discovered some problems with default generic types. (v12.3.8)

As I define a generic typed interface

    interface Foo<T = any>
    {
      bar: T;
    }

    let foo: Foo = { bar: 'bar' };

*Typescript* provider marks it as error with following messages:

    Generic type 'Foo<T, any>' requires 2 type arguments

**Comment by lierdakil** [comment]
Try restarting Atom, it's possible tsserver didn't pick up recent changes for some reason. This can happen from time to time, regrettably.

Also, bear in mind that Atom will use whatever TypeScript version is installed into `node_modules` (as specified in your `package.json` probably). Only if there is none, it will use whatever version we're bundling (TS 2.6 as of v12.3, TS 2.7 as of v12.4). So, if your TS version in `node_modules` is particularly old, it might not understand this syntax.
