### ISSUE TITLE
[Not working - need help] autocomplete on types not working

### ISSUE THREAD

**Issue by jonyeezs** [TypeStrong/atom-typescript#1422]
The autocomplete doesn't seem to work when the language is set to `Typescript` but works when `TypescriptReact`.

This is my configs which i think maybe relevant (let me know if you need more:

* Core (Atom v1.26.0):
  - [x] Use Tree Sitter Parser
* Autocomplete-plus (v2.40.5):
  - Maximum Visible Suggestions - 10
  - [x] Use Core Movement Commands
* Language-typescript (v0.3.3)
* Atom-typescript (v12.4.0):
  - Autocomplete Suggestion Priority - 5

When as Typescript grammar:

I've noticed the classes aren't TS
![image](https://user-images.githubusercontent.com/10862726/39280593-90a56a48-4943-11e8-8aa9-e7bc3fa07e9b.png)

![ts-notworking](https://user-images.githubusercontent.com/10862726/39280785-99c1c1f2-4944-11e8-9f81-37bf6f094293.gif)

When as TypescriptReact grammar:

![tsreact-working](https://user-images.githubusercontent.com/10862726/39280792-a1f70256-4944-11e8-85f6-16b275ed5ed3.gif)

Changing it back to Typescript still results in the same problem.

Any ideas?

I've tried toggling tree sitter off - same problem.

**Comment by lierdakil** [comment]
Most likely a third-party TypeScript grammar interfering. Make sure you don't have other typescript-related packages installed?

**Comment by lierdakil** [comment]
Just FYI, `editor:log-cursor-scope` command (accessible from command palette) will show you the list of grammar scopes the text cursor is currently in. The top one is always the document scope. It should either be `source.ts` or `typescript` (when using tree-sitter)

**Comment by jonyeezs** [comment]
> editor:log-cursor-scope command grammar scopes the text cursor is currently in.

Looks like it is typescript. Is the scopes correct?

```
typescript
program
expression_statement
call_expression
arguments
arrow_function
statement_block
expression_statement
call_expression
arguments
call_expression
arguments
arrow_function
statement_block
expression_statement
assignment_expression
call_expression
member_expression
property_identifier
```

> Make sure you don't have other typescript-related packages installed?

Suggestions on the quickest way to do this? ...i suppose safemode..will have to try that

**Comment by lierdakil** [comment]
Sorry, my bad. I think I know where the problem is. Although this remark:
> I've tried toggling tree sitter off - same problem.

kinda threw me off.

**Comment by lierdakil** [comment]
So... this is bullshit. There is no way to enable autocomplete for tree-sitter TypeScript without also enabling it for JavaScript.

So yeah... don't use tree-sitter for now I guess. I don't have another solution at the moment.

**Comment by lierdakil** [comment]
Nevermind, figured it out... somewhat. v12.4.1 should work. Sorry for giving you the runaround.

**Comment by jonyeezs** [comment]
All good! Much ❤

**Comment by jonyeezs** [comment]
Confirming: it works now!
