### ISSUE TITLE
ng serve command in Atom not working

### ISSUE THREAD

**Issue by Plautus123** [TypeStrong/atom-typescript#1428]
I try to get Angular running, but "ng serve" command just doesnt do anything when I type it in terminal.
I am also in the right folder, and npm, ng, node versions are up to date
What#s wrong?

**Comment by lierdakil** [comment]
No idea. I don't think atom-typescript is in any way related to this as far as I can tell, and I don't use Angular.

**Comment by Plautus123** [comment]
not related to what?

**Comment by lierdakil** [comment]
To the issue as described. Atom-typescript doesn't in any way directly interact with `ng serve` (or with any Angular components for that matter), and it doesn't provide a terminal. So I don't see how it's related to the OP.

**Comment by Plautus123** [comment]
how can I make it work?

**Comment by lierdakil** [comment]
As I said, I have no idea. I don't use Angular, and we do not provide Angular support directly. Try asking on an Angular support forum, wherever that is.

**Comment by logesh07** [comment]
Try using **npm run ng serve** open terminal in atom(powershell)

**Comment by kalpeshrajpurohit** [comment]
Try using " npm run start  "  Atom terminal (  Ctrl + ` )
