### ISSUE TITLE
Tooltips don't work in remote session

### ISSUE THREAD

**Issue by mvcoding** [TypeStrong/atom-typescript#1429]
I'm using Atom in a remote session where the type information tooltips don't show on hover. The request is looping and nothing is displayed.

I tried some debugging and saw that the data is coming in fine but the display is always cancelled by the TooltipManager in the showExpressionType function. I assume it has something to do with the callback timeout because my remote session has a slight delay and it only happens there.

**Comment by lierdakil** [comment]
What are you using for remote sessions? Does `atom-typescript:show-tooltip` command work?

Try v12.5.3. If it still doesn't work, you could try experimenting with 'tooltip delay' setting.

**Comment by mvcoding** [comment]
I'm on a x2go remote session here. Using the command made no difference but v12.5.3 did the trick! Tooltips are coming up fine now with the default delay setting.

Thanks for the quick fix! 👍 😃
