### ISSUE TITLE
Autocomplete settings

### ISSUE THREAD

**Issue by mclusky** [TypeStrong/atom-typescript#1430]
Hi,

is it possible to change the autocomplete command from the tab key to the enter key? It conflicts with my emmet settings otherwise.
Thanks for your help.

**Comment by lierdakil** [comment]
See autocomplete-plus package settings. It's a built-in package which provides autocompletion GUI.

**Comment by Mclusky** [comment]
hi,

yeah that's already set up. it only occurs when autocomplete shows up for imports, which is not a big deal. thanks anyway.
