### ISSUE TITLE
Updating Issues

### ISSUE THREAD

**Issue by andykimchris** [TypeStrong/atom-typescript#1431]
My app is not updating.I'm trying to uninstall it then reinstall again. Any help?

**Comment by lierdakil** [comment]
> My app

Sorry, what app?

> I'm trying to uninstall it then reinstall again

When Atom packages are concerned, this usually works unless either your Internet connection or Atom itself is horribly broken.

> Any help?

Atom/Apm probably shows some sort of error, so you could start by telling what that error is exactly.
