### ISSUE TITLE
Autocomplete on script imports not working

### ISSUE THREAD

**Issue by DustinJSilk** [TypeStrong/atom-typescript#1435]
Ive just updated my atom-typescript version (I was a couple weeks behind maybe). And it seems that now when importing a file it doesnt autocomplete the script when hitting enter.

So when it gets to this part and hit enter, it doesn't fill in the rest of the import statement anymore.

<img width="390" alt="screen shot 2018-06-22 at 09 54 42" src="https://user-images.githubusercontent.com/5979984/41767753-6105c5f8-7602-11e8-8d71-a2973db1f7e3.png">

**Comment by lierdakil** [comment]
All autocompletion UI is handled by the autocomplete-plus core package. Check its settings?

**Comment by DustinJSilk** [comment]
Oh! Hmm okay i'll dig around and see what I can find. Thanks, I'll post an answer here when i find one.

Ps. Its the same for directories when autocompleting.

**Comment by lierdakil** [comment]
Also, a quick note: make sure the `enter` keybinding isn't stolen by something else. You can use the keybinding resolver to debug those ('key binding resolver: toggle' in command palette)
