### ISSUE TITLE
Error markers and text view is not updated

### ISSUE THREAD

**Issue by zeff89** [TypeStrong/atom-typescript#1438]
I decided to finally give Atom (1.28.0 Win 10) a try and installed the editor with the atom-ide-ui (0.12.0), atom-typescript (12.6.1) and linter-tslint (1.9.1). However, error markers won't get cleared and sometimes the file doesn't get updated until after I close and reopen it when applying imports through the popup.

Case 1:
What I did was remove a random import and try to add it via the popup.
Result: Nothing gets importet and the markers remain. When I close my file without saving it and reopen, I see multiple imports (depending on how often I pushed on that import button before).
![Bug1](https://i.imgur.com/yswIL24.gif)

Case 2:
On occasion, the import button will work, but the error marker still don't get cleared. Additionally red underlines get stuck in their previous positions.
![Bug2](https://i.imgur.com/Km5sQEh.png)

Case 2 seems to occur only when I save between removing an import and then adding it again. Case 1 happens if I don't save at all.

**Comment by lierdakil** [comment]
It seems the files are being modified directly instead of going through Atom. I'm suspecting a very old TypeScript version. So... what TypeScript version are you using? It should be shown in the status bar to the right somewhere.

As a reminder, atom-typescript will try to use whatever TypeScript version it can find (usually installed in `node_modules`) before falling back to a bundled version (TypeScript 2.9.2 at the moment I think)

If I'm wrong, then this might be platform-specific. I'll try to run some tests on a Windows machine later when I find one.

**Comment by zeff89** [comment]
I used TypeScript 2.8.3 for this test. I don't know if that counts as old though.
I redid my tests with TypeScript 2.9.2. Creating and inserting the import statement seems to be working properly now, but error markers still won't get updated after the insert. I have to close and reopen the file every time to fix it. This means case 1 is solved but case 2 still remains as is.

**Comment by lierdakil** [comment]
When talking about "old" I was more expecting something to the tune of 2.4. 2.6 and up definitely should be fine.

Thanks for reporting. Probably a platform-specific bug then, which are always "a lot of fun" to debug. Likely something to do with the path normalization if I had to guess (the whole thing where Windows likes backslashes while TypeScript likes forward slashes, Node itself doesn't care either way really, and Atom seems to use both on occasion).

I'm sorry you're running into this, I'll try to find a Windows box to run some tests on ASAP.

**Comment by lierdakil** [comment]
Okay, I believe this should be fixed in v12.6.2. Sorry again you had to deal with this. And thanks again for reporting,
