### ISSUE TITLE
Reporting mismatched jsdoc tags (params, etc.)

### ISSUE THREAD

**Issue by brettz9** [TypeStrong/atom-typescript#1439]
Could you add the option to report any mismatches between say a function whose parameter did not match (or was missing) on  `@param` or vice versa? Likewise for `@return`/`@returns`, etc...

**Comment by lierdakil** [comment]
All error checking is handled by [TypeScript](https://github.com/Microsoft/TypeScript) itself. So, unless it can do that, which I don't think it can, no.

**Comment by brettz9** [comment]
Ok, thanks! Closing in favor of https://github.com/Microsoft/TypeScript/issues/15852 and/or https://github.com/Microsoft/TypeScript/issues/11378
