### ISSUE TITLE
Type tooltip overlay the suggestions info

### ISSUE THREAD

**Issue by maksimsemenov** [TypeStrong/atom-typescript#1442]
When I hover a mouse over the variable, that has a typescript or tslint error, the variable type gets in front of errors info. It is very confusing and very hard to see the error message:
<img width="1680" alt="image 2018-07-25 at 3 35 40 pm" src="https://user-images.githubusercontent.com/3608139/43196349-0ae568d4-9021-11e8-8894-e7ee8ad7de02.png">

Is it possible to show type information in suggestions below the errors and warnings, like ide-typescript does?
<img width="1680" alt="screen shot 2018-07-25 at 3 36 55 pm" src="https://user-images.githubusercontent.com/3608139/43196400-2d228742-9021-11e8-9b9e-51b2cf932fcc.png">

**Comment by karolfalkiewicz** [comment]
I would also prefer the `ide` version of hover messages like `ide-typescript` does it.

**Comment by ozra** [comment]
This has annoyed me for a long time too — my solution so far is to move things around a bit:
```less
.tooltip.atom-typescript-tooltip {
    transform: translateY(-40px);
}
```
