### ISSUE TITLE
permission denied, unlink, updating atom-typescript@12.6.3

### ISSUE THREAD

**Issue by rbpancoast** [TypeStrong/atom-typescript#1446]
Updating to “atom-typescript@12.6.3” failed.
EACCES: permission denied, unlink '/Users/it/.atom/packages/atom-typescript/.gitattributes'

Manually performed the unlink using sudo, which ran okay, but it keeps trying to do an unlink.

**Comment by lierdakil** [comment]
Try removing the whole `/Users/it/.atom/packages/atom-typescript/` directory altogether and reinstalling the package. And just in case, don't use `sudo` to install Atom packages.
