### ISSUE TITLE
Shortcut Review for build and goto declaration

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#145]
Atom defaults: 

`ctrl+b` : find in buffer
`ctrl+shift+b`: find modified file 

Although I like what I have. I don't feel right in: 

a. competing with default shortcuts
b. I find `ctrl+shift+b` to be difficult to override, in that atom has it hooked very deeply. 

So: find other defaults

**Comment by poelstra** [comment]
Suggestion for "Goto Declaration": F12. It's what Visual Studio uses, and doesn't seem to be in use in Atom by default.

**Comment by basarat** [comment]
Suggestion for Build : `F6` Its what visual studio uses

ref: https://github.com/TypeStrong/atom-typescript/issues/145
