### ISSUE TITLE
Option to put semantic tree on _left_ side, next to project tree

### ISSUE THREAD

**Issue by ozra** [TypeStrong/atom-typescript#1450]
This would be very nice, since source code is "left heavy", and as such I prefer having the "lefts" of my panes more in the center. Thus, putting side-line info to the left of editor buffers is always better. Imho ofc.

**Comment by lierdakil** [comment]
You can just drag the semantic view panel into the left dock...

**Comment by ozra** [comment]
ah, duh! Thanks xD
