### ISSUE TITLE
TypeScript quit unexpectedly

### ISSUE THREAD

**Issue by bercly0b** [TypeStrong/atom-typescript#1457]
Hello. 
I have install `atom-typescript` and it worked once, but next I have such issue

`TypeScript quit unexpectedly
Last output from tsserver:
node::Abort() [/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 2: node::FatalError(char const*, char const*) [/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 3: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 4: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 5: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 6: v8::internal::RegisterConfiguration::AreAliases(v8::internal::MachineRepresentation, int, v8::internal::MachineRepresentation, int) const [/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 7: 0x2111f7c8463d
terminated on signal: SIGABRT
Hide Stack Trace
Error: terminated on signal: SIGABRT
    at ChildProcess.cp.once (/Users/admn/.atom/packages/atom-typescript/dist/client/client.js:97:23)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)`

OS X 10.14
typescript 3.1.3
atom 1.28.1

Please help me)
I really don't want to change the editor because of the problems with typescript..

**Comment by lierdakil** [comment]
Well, apparently Node throws out of memory error here. Perhaps freeing up some RAM might help?

Also, you might want to update Atom, the newest version is 1.32.0, this might've been a bug that has since been fixed.

**Comment by bercly0b** [comment]
> Well, apparently Node throws out of memory error here. Perhaps freeing up some RAM might help?
> 
> Also, you might want to update Atom, the newest version is 1.32.0, this might've been a bug that has since been fixed.

I always have 3-4 gb free ram. did this not enough?
I have updated atom to 1.32.0 couple hours ago, and yes, it's works for me. I will work with TS during the day, and evening I could write here if it ok or not

**Comment by lierdakil** [comment]
> I always have 3-4 gb free ram

This should be plenty. Well, then it's most likely a bug in Node or Electron, then. I'm pretty sure both of those were updated between Atom 1.28 and 1.32, so there's a good chance that the newer Atom will work.

**Comment by bercly0b** [comment]
yes, electron and node were updated.
now I had the same issue.
I use `gulp/browserify/tsify`, and I thought that entry point in my `gulpfile` will be enough, 
but when I removed `files` from `tsconfig` I had the same error..

**Comment by lierdakil** [comment]
Uh... `files`? What version of TypeScript are you using? I don't think many people still use `files` option nowadays, considering `include` and `exclude` are available since TS 2.0 or something like that.

If it's reasonably new, maybe it's crashing while scanning a huge directory hierarchy? Perhaps adding 
```json
{
  ...
  "exclude": [ "node_modules"  ]
  ...
}
```
to tsconfig would help? Or alternatively, specifying `include`.

Disclaimer: shooting in the dark here, don't have the slightest idea about particular details of your setup.

Note: TypeScript server has no idea about your build system, since it's not it's job. So tsc/tsserver is basically ignoring your `gulpfile` and whatnot, and just searching for `*.ts` and `*.tsx` under the directory containing a given `tsconfig.json`. `files`,  or `include` and `exclude`, basically control where it looks, so if neither of those is specified, it'll go on to search everything.

**Comment by bercly0b** [comment]
yes, I have `"exclude": [ "node_modules"  ]` in my `tsconfig`
I'm just getting acquainted with the typescript. I guess I need to learn more about `tsconfig` or about something else. but it's not about `atom-typescript` anymore))
Thanks a lot for you explanation :handshake:
