### ISSUE TITLE
Plugin does not build on Atom 1.32 with OSX Mojave 10.14

### ISSUE THREAD

**Issue by glemiere** [TypeStrong/atom-typescript#1458]
Hi!

This morning, my TS file were not loading the syntax coloration. It seems like this plugin fails to build. I also got the following error message at some point :

`SourceGraph language server for TypeScript unable to start`

**Comment by lierdakil** [comment]
Syntax highlighting is (supposedly) handled by Atom's bundled language-typescript package. SourceGraph language server is a third-party add-on.

So... I see nothing that would indicate that Atom-TypeScript failed at any point.
