### ISSUE TITLE
How to disable "this may be converted to an async function" messages, etc?

### ISSUE THREAD

**Issue by trusktr** [TypeStrong/atom-typescript#1461]
I have some messages coming from (I think) atom-typescript, which don't seem to be configured in either my eslintrc or in tsconfig.

How can we configure these messages (f.e. disable the `this may be converted to an async function` specifically)?

**Comment by lierdakil** [comment]
Use `ignoredDiagnosticCodes` option in Atom-Typescript settings. Currently only globally-configurable, although that might change in the future.

**Comment by lierdakil** [comment]
In particular, "this may be converted to an async function" is suggestion diagnostic 80006, so you would add `80006` to the (comma-separated) list of `ignoredDiagnosticCodes`

**Comment by lierdakil** [comment]
FWIW, those "suggestion" diagnostics are only there to provide GUI endpoints for automatic code transformations. So those can be safely ignored (as is the case with any diagnostics with severity "informational")

**Comment by trusktr** [comment]
How can I discover the code numbers of any diagnostics?

**Comment by lierdakil** [comment]
It's literally in the settings GUI:
![image](https://user-images.githubusercontent.com/7275622/47966483-0e88d500-e064-11e8-958c-6ec45575c922.png)
`diagnostigMessages.json` is a clickable link.

**Comment by trusktr** [comment]
Oh sorry, well now that I know they were called "diagnostics" I surely could have figured that one out. Thanks!
