### ISSUE TITLE
Relative Alias Not Found

### ISSUE THREAD

**Issue by ChrisTalman** [TypeStrong/atom-typescript#1464]
In `webpack.config.js`, I specify the following alias:

```JavaScript
{
    common: Path.join(__dirname, '../Common')
}
```
Then, I import from a path using that alias:
```JavaScript
import * as Module from 'common/Modules/Module';
```
In my compiler, there are no errors, and runtime logging demonstrates that the module is successfully imported.

However, in Atom, with `atom-typescript`, the import is reported as having the error 'cannot find module'. I've also tested this in `ide-typescript`, which reports the same error.

I imagine that both modules are probably using another module which is responsible for this bug, but I'm not familiar with the internals of these plugins, and so I don't know where the source of the bug lies.

Any help would be much appreciated.

**Comment by lierdakil** [comment]
TypeScript compiler has no idea about webpack, so your webpack config is somewhat irrelevant here. Most importantly, it's not webpack that provides IDE niceties, but TypeScript. You most likely need to set up TypeScript's module resoltution algorithm to work roughly the same as webpack does in your case. Please see here: https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping

**Comment by ChrisTalman** [comment]
Hey, thanks for the pointer! I was aware that TypeScript itself has no knowledge of Webpack, but I was not familiar with `paths`. It seems as though I had also setup a (perhaps unnecessary) Webpack alias which just happened to work, without the help of `paths`, which was a little confusing.

For the benefit of anyone who may find this in the future, this is what I went with in `tsconfig.json`:
```JSON
{
    "paths":
    {
        "common/*": ["../Common/*"]
    }
}
```
