### ISSUE TITLE
Constantly getting errors with autocomplete and refactor identifier name after updates

### ISSUE THREAD

**Issue by ozra** [TypeStrong/atom-typescript#1466]
atom-version: 1.32.2
typescript-version in the project: 3.1.6

Things done that may or may not be causes for this: Tried using atom-ide / ide-typescript instead of regular ts-plugin-chain. Have since removed them and use linter, linter-standard-ui, etc. "standard" plugins for that.

I assume the errors, despite their difference, are related, since they began at the same time:

Trying to rename-refactor:
```
Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (
... long list of paths and stack trace follows ...
```

Autocompletion doesn't work anymore, gets this:

`Uncaught SyntaxError: Invalid regular expression: /[A-Za-z\xAA\xB5\xBA\xC0-\xD6\xD8-\xF6\xF8-\u02C1\u02C6- .... and so on for a page or two ...`

**Comment by lierdakil** [comment]
It'd be interesting to see the stacktrace. Otherwise, it's unclear what's going on exactly.

**Comment by ozra** [comment]
Haven't seen this in quite a while. It was probably just something temporarily messed up in the installation. Closing.
