### ISSUE TITLE
allowJs and checkJs config

### ISSUE THREAD

**Issue by jrobinson01** [TypeStrong/atom-typescript#1467]
In reading other issues, it doesn't look like checking .js files is supported out of the box, nor by adding the `allowJs` and `checkJs` compiler options to tsconfig.json. ~It DOES seem however, that adding a comment to the top of your .js files `// @ts-check` gets it working, except that it complains about that comment.~ this seems to be coming from the "ide-typescript" plugin and not "atom-typescript".

I see that support for `allowJs` and `checkJs` is up for grabs. I'd be interested in tackling it but am not familiar with this project at all. Would anyone be willing to point me at a starting point?

edit: Looks like this PR fixes my woes: https://github.com/TypeStrong/atom-typescript/pull/1456

**Comment by lierdakil** [comment]
> Looks like this PR fixes my woes: #1456

Right. I missed #315 when referencing issues in that PR (the backlog is a horrifying place, so I tend to avoid staring there too much)

**Comment by lierdakil** [comment]
V12.7.0 is released which includes experimental support for JS. It's a bit hacky at the moment, but it should work for the most part. See: https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#i-want-to-use-atom-typescript-with-javascript-too
