### ISSUE TITLE
Definition files not being found

### ISSUE THREAD

**Issue by rcollette** [TypeStrong/atom-typescript#147]
The project https://github.com/rcollette/RequireAngularTS/tree/master/RequestAngularTS.Web compiles just fine and there are no complaints in the Visual Studio editor.  VS will find all definition files in the project and use them.   Atom does not appear to be doing this.  All angular type usage is resulting in "Cannot find name" errors.

**Comment by basarat** [comment]
Just create a `tsconfig.json` file containing `{}` here : https://github.com/rcollette/RequireAngularTS/tree/master/RequestAngularTS.Web 

Reopen if that doesn't work :heart: Learn more : https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md
