### ISSUE TITLE
no hover in .js files

### ISSUE THREAD

**Issue by jrobinson01** [TypeStrong/atom-typescript#1470]
hovering doesn't produce a tool-tip in .js files.
test.js
![screen shot 2018-11-18 at 3 35 56 pm](https://user-images.githubusercontent.com/1584296/48677769-c7144580-eb47-11e8-852e-36d2c2f58671.png)

test.ts
![screen shot 2018-11-18 at 3 36 09 pm](https://user-images.githubusercontent.com/1584296/48677774-d1364400-eb47-11e8-87b3-e0bad0be803e.png)

**Comment by lierdakil** [comment]
Works for me. FWIW, you just probably need to restart Atom after enabling JS.

**Comment by jrobinson01** [comment]
It's working now after a restart. I'm pretty sure I had restarted prior to creating the issue though, as I was getting type checking in other .js files.

**Comment by lierdakil** [comment]
> was getting type checking in other .js files.

The parts that require restart and that don't are rather inconsistent, sadly. Autocomplete, for instance, does, but linter does not (or does, depending on how you use it). This is a consequence of some odd-ish architectural decisions made by Atom team way back when autocomplete-plus was still a community package.
