### ISSUE TITLE
[Warning]: The error was: Unexpected token ] in JSON at position 385

### ISSUE THREAD

**Issue by dacevedo12** [TypeStrong/atom-typescript#1476]
Failed to parse tsconfig.json

Steps to reproduce:

1. Update to atom-typescript 12.7.1
2. Restart atom
3. Open any .ts or .tsx file

Atom: 1.32.2 x64
Electron: 2.0.9
OS: Deepin 15.8
Thrown From: atom-typescript package 12.7.1

Non-Core Packages
atom-ide-ui 0.13.0 
atom-typescript 12.7.1
autocomplete-python 1.11.0 
file-icons 2.1.26 
file-watcher 2.0.0 
goto-definition 1.3.4 
minimap 4.29.9 
oceanic-next 1.0.0

**Comment by lierdakil** [comment]
... really? There's apparently a syntax error in your `tsconfig.json` file. Most likely an extra comma somewhere. That's kinda the point. Until v12.7.0 these errors were masked. Now they are reported. As far as I can tell, this is not a bug.

**Comment by dacevedo12** [comment]
Alright, but anyway this message is misleading. Something like "There is an error in your tsconfig file" would be more appropiate in my opinion.

**Comment by SinoBoeckmann** [comment]
Hi there,
I would gladly reopen this issue because I'm getting the same error BUT this error is not pointing into MY tsconfig.json.
It says:

`Failed to parse tsconfig.json
The error was: Unexpected token } in JSON at position 750`

Would it be possible to have this issue reported AND a link to the file? As this is a real issue I would say.

**Comment by lierdakil** [comment]
> error is not pointing into MY tsconfig.json

It really couldn't point anywhere else, frankly... the `tsconfig.json` in question is most likely in the Atom project root, wherever that is.

If you're confused by 'position 750', that's how JSON parser does stuff sadly, it just treats newlines as whitespace, hence it only reports linear position, not (line, col). Could you perhaps feed your `tsconfig.json` into https://jsonlint.com/?

**Comment by SinoBoeckmann** [comment]
Ay, thanks! 
Thanks for pointing this out and making it more clear!
