### ISSUE TITLE
autocomplete is slow

### ISSUE THREAD

**Issue by trusktr** [TypeStrong/atom-typescript#1477]
Autocomplete is so slow that it is unusable. I can type whatever I need faster (and fix typos).

I tried 

```
atom.config.set('core.debugLSP', true)
```

and restarted Atom but I don't see anything in the console when I do autocompletion.

What else can I do to provide any info?>

**Comment by lierdakil** [comment]
Also I have no idea why would you think that `core.debugLSP` does anything in our case. To see debug information for Atom-TypeScript, you need to set `window.atom_typescript_debug = 1`. Note that's a global variable, not a config setting.

**Comment by trusktr** [comment]
Cool, I put `window.atom_typescript_debug = 1` in my init script. I'll report if I see anything.

> _Maybe_ it's TypeScript being slow

Any thoughts why? Maybe I'm checking node_modules too (though I never see any errors coming from that folder). I don't think my project is _that_ big.
