### ISSUE TITLE
Atom freezing for 10 minutes (while building type information?)

### ISSUE THREAD

**Issue by rcollette** [TypeStrong/atom-typescript#148]
Atom is freezing on me for about 10 minutes when I open a project and do the following actions. (i7 processor, windows 7)

In the project directory here:
https://github.com/rcollette/RequireAngularTS/tree/master/RequestAngularTS.Web

When I open a .ts file from the project, atom starts using about 6-7%cpu.

I tried a tsconfig.json file with just `{}` in it.   I typed `angular.` got no typeahead after typing the period, then backspaced and atom froze.   It was running at a steady 6%.

I then used the following config to attempt to narrow down the list of files, in case it was looking at too much.

```
{
    "compilerOptions": {},
    "filesGlob": [
        "./**/*.ts",
        "!./node_modules/**/*.ts"
    ],
}
```
It froze again after typing in `angular.` and then backspacing but it did update the list of files so the config now looks like:
```
{
    "compilerOptions": {},
    "filesGlob": [
        "./**/*.ts",
        "!./node_modules/**/*.ts"
    ],
    "files": [
        "./app/blocks/router/RouteResolver.provider.ts",
        "./app/blocks/router/block.router.module.ts",
        "./app/blocks/validation/ServerErrorDirective.ts",
        "./app/blocks/validation/block.validation.module.ts",
        "./app/directives/HtmlTemplate/HtmlTemplate.directive.ts",
        "./app/interfaces/FeatureController.I.ts",
        "./app/interfaces/PagebleT.I.ts",
        "./app/main.ts",
        "./app/modules/App/App.controller.ts",
        "./app/modules/App/App.module.ts",
        "./app/modules/App/App.routes.ts",
        "./app/modules/Core/App.Core.module.ts",
        "./app/modules/PurchaseOrder/PurchaseOrder.controller.ts",
        "./app/modules/PurchaseOrder/PurchaseOrder.module.ts",
        "./app/modules/PurchaseOrder/PurchaseOrder.service.ts",
        "./app/modules/PurchaseOrder/PurchaseOrders.controller.ts",
        "./app/modules/Vendor/Vendor.module.ts",
        "./app/modules/Vendor/Vendor.spec.ts",
        "./app/modules/Vendor/Vendors.controller.ts",
        "./dist/blocks/router/RouteResolver.provider.ts",
        "./dist/blocks/router/blocks.router.module.ts",
        "./dist/directives/HtmlTemplate/HtmlTemplate.directive.ts",
        "./dist/directives/ModelValidatorDirective.ts",
        "./dist/interfaces/FeatureController.I.ts",
        "./dist/interfaces/PagebleT.I.ts",
        "./dist/main.ts",
        "./dist/modules/App/App.controller.ts",
        "./dist/modules/App/App.module.ts",
        "./dist/modules/App/App.routes.ts",
        "./dist/modules/Core/App.Core.module.ts",
        "./dist/modules/PurchaseOrder/PurchaseOrder.controller.ts",
        "./dist/modules/PurchaseOrder/PurchaseOrder.module.ts",
        "./dist/modules/PurchaseOrder/PurchaseOrder.service.ts",
        "./dist/modules/PurchaseOrder/PurchaseOrders.controller.ts",
        "./dist/modules/Vendor/Vendor.module.ts",
        "./dist/modules/Vendor/Vendor.spec.ts",
        "./dist/modules/Vendor/Vendors.controller.ts",
        "./typings/angularjs/angular-animate.d.ts",
        "./typings/angularjs/angular-cookies.d.ts",
        "./typings/angularjs/angular-resource.d.ts",
        "./typings/angularjs/angular-route.d.ts",
        "./typings/angularjs/angular-sanitize.d.ts",
        "./typings/angularjs/angular.d.ts",
        "./typings/jquery/jquery.d.ts",
        "./typings/modernizr/modernizr.d.ts",
        "./typings/moment/moment.d.ts",
        "./typings/requirejs/require.d.ts",
        "./typings/tsd.d.ts"
    ]
}
```

**Comment by basarat** [comment]
I've added a tsconfig.json file to your project. Would be great to debug that project with you. I am on gitter  if you want to chat : https://gitter.im/TypeStrong/atom-typescript?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by basarat** [comment]
![test2](https://cloud.githubusercontent.com/assets/874898/6500390/4d069fae-c35f-11e4-9f4b-102e8546138a.gif)

Working off of that PR branch, I am unable to experience the same as you can see.

**Comment by rcollette** [comment]
Once, the 10 minute period is up, I do get the typeahead like you have shown.  It's the initial start up time that takes a while.   Sorry I didn't see your post about gitter.  I probably went to sleep just after I posted.   I'm on EST (GMT-5)

**Comment by basarat** [comment]
*Sorry I misunderstood, I thought it was "after 10 minutes it becomes slow" whereas you meant "its slow for the first 10 minutes".* So now: 

For me its quite fast and near instantaneous once atom boots up as you can see in the near realtime gif here :

![fromstart](https://cloud.githubusercontent.com/assets/874898/6516508/ab850e62-c3e6-11e4-9647-da39458fa520.gif)

It does need to read the entire project filesystem. I see around 100ms delay here and not much more. Also all this work in the background so it shouldn't freeze the UI. 

* Are you working off the local file system or network?

**Comment by rcollette** [comment]
I am working off the local filesystem.  After adding in the tsconfig that you provided, I am not getting any typeahead at all, not even for the built in types it seems.   It's taking a little longer now to lock up but eventually it freezes.   In the attached gif, it locks up the very end when you see "dd" in my typing.

![typeahead](https://cloud.githubusercontent.com/assets/136476/6517061/4f23c874-c365-11e4-944c-9646d2c10fe7.gif)

**Comment by rcollette** [comment]
This may be of more use.   It appears that maybe there is a deadlock since all processes are running and then suddenly everything stops and only one process is spinning?
![editorlockup](https://cloud.githubusercontent.com/assets/136476/6517467/3ffa461c-c369-11e4-85ee-6932706a0224.gif)

**Comment by basarat** [comment]
I am on gitter again.  Can you open up the atom dev tools `ctrl+shift+i` to see if anything bad is happening that gets logged there?

**Comment by rcollette** [comment]
I've registered but haven't used it before.  Not sure how to get you privately.

**Comment by rcollette** [comment]
```
C:\Users\rich\.atom\packages\atom-typescript\lib\worker\parent.js:8 AtomTS worker started
index.js:57 Window load time: 5479ms
C:\Users\rich\.atom\packages\atom-typescript\lib\worker\lib\workerLib.js:135 CHILD ERR STDERR: fs.existsSync() is deprecated. Use fs.accessSync() instead.
```

**Comment by basarat** [comment]
> Not sure how to get you privately. 

You can't get me privately. But we chat in the room https://gitter.im/TypeStrong/atom-typescript. No one gets a notification unless *they explicitly asked for it* (like I have for this particular room) or the get @ mentioned e.g. @basarat

**Comment by basarat** [comment]
@rcollette your log shows that there were no *errors*.

**Comment by basarat** [comment]
@rcollette message me when in the room (so that people that are watching this project for source code don't get chat like messages :heart: )

**Comment by basarat** [comment]
Suspect this will be take care of by https://github.com/TypeStrong/atom-typescript/issues/183 Fix coming with `v1` once https://github.com/TypeStrong/atom-typescript/pull/179 is merged.

**Comment by rcollette** [comment]
Great.  #183 sounds very similar to what I am experiencing.   Still have not had time to do fresh install and test.
