### ISSUE TITLE
Is it possible to hide tooltips

### ISSUE THREAD

**Issue by anta-semenov** [TypeStrong/atom-typescript#1483]
It would be great to hide tooltips, because they are very annoying and overlay autocompletion.
I've tried different options in settings (like increasing delay and so on), but nothing helped.
Maybe it's not tooltip, but there are no other options in settings.

<img width="1416" alt="screenshot 2018-12-18 at 13 53 49" src="https://user-images.githubusercontent.com/555146/50142744-a8cb7200-02cc-11e9-9774-7eabfef5c274.png">

**Comment by trusktr** [comment]
Hmmm, seems like yours shows the full type information, whereas mine seems to truncate long ones with an ellipsis.

For example, though it is long, mine isn't as long as yours, seems truncated:

<img width="761" alt="screen shot 2018-12-27 at 9 53 04 pm" src="https://user-images.githubusercontent.com/297678/50504449-92d35500-0a22-11e9-9fef-5889a0020ee7.png">

And here's another truncation example example:

<img width="1707" alt="screen shot 2018-12-27 at 9 57 54 pm" src="https://user-images.githubusercontent.com/297678/50504458-9d8dea00-0a22-11e9-844a-253044a2a627.png">

Also the tooltip position is configurable in atom-typescript 12.7+, so you can make it be on top instead of on bottom, then it won't cover the autocompletions.

**Comment by trusktr** [comment]
You might also be able to write some CSS, `display: none` in your stylesheet to hide the tooltips...

**Comment by lierdakil** [comment]
That's "signature help". The way it's implemented might not be the best way possible. Ideas on how to improve it and PRs are welcome. You might also want to try atom-IDE provided ui, you might find it less obtrusive.

**Comment by vamshi9666** [comment]
@trusktr what would be class name for applyng `display: none` ?

**Comment by anthonyraymond** [comment]
![image](https://user-images.githubusercontent.com/7503585/58127908-bd62bc00-7c16-11e9-814d-1122403f5f1d.png)

`atom-typescript-tooltip`

**Comment by cheukyin699** [comment]
This still feels like a hacky way to do it. Would anyone mind if I add an option in settings that disables these tooltips?

**Comment by MiracleBlue** [comment]
I seem to have disabled these specific ones (the signature help ones) by disabling Atom IDE UI's "Signature Help" feature (go to Settings > Atom IDE UI > Atom-ide-signature-help > uncheck "Enable signature help").  For me, Signature Help has only ever worked in the context of typescript, so I doubt I'll miss it, but be aware anyone who takes this route it means disabling it for anything else which might use it.  The best thing is that the on-hover datatips all still work, which I love!

After opening parenthesise with signature help disabled:
![image](https://user-images.githubusercontent.com/23368/71297174-86d06800-23d6-11ea-86b3-bdd1b59b17de.png)

My pretty datatips still work:
![image](https://user-images.githubusercontent.com/23368/71297332-34dc1200-23d7-11ea-8957-9c8a89e076b5.png)

**Comment by lierdakil** [comment]
v13.5.0 adds a new configuration option `sigHelpDisplayOnChange` ("Display signature help tooltips on keystroke"), which controls whether signature help is displayed on keystroke (enabled by default).

Even when this option is disabled, one can manually open signature help tooltip with `typescript:show-signature-help` command if desired. It won't show up unprompted though.

**Comment by paddotk** [comment]
@lierdakill It still shows up on hovering code, despite that option.

**Comment by lierdakil** [comment]
As far as I remember, signature help is never shown on mouse hover. You're likely seeing type tooltips, which is expected and is kind of one of the primary features. If you want to suppress those, you could tweak the "type tooltip delay" option, or use css hacks described in this thread (e.g. https://github.com/TypeStrong/atom-typescript/issues/1483#issuecomment-494543554)

**Comment by paddotk** [comment]
@lierdakil Thanks, I guess that'll do. Ideally there'd be an option to turn it off but a long delay works for me too :)
