### ISSUE TITLE
Type pop up blinking

### ISSUE THREAD

**Issue by rcollette** [TypeStrong/atom-typescript#149]
When I hover over a variable or type, the pop up type information that is displayed blinks at the pace of the cursor blink.

**Comment by basarat** [comment]
Is it something different from what I see here, there is a blink on first hover : 
![test](https://cloud.githubusercontent.com/assets/874898/6500293/d93eb224-c35d-11e4-9ee7-548790603098.gif)

Or are you getting consistent blinks i.e. it keeps blinking at the same pace as the cursor?

**Comment by rcollette** [comment]
Same place under the cursor.  No time right now to capture it (what tool do you use btw?)

**Comment by basarat** [comment]
https://screentogif.codeplex.com/

**Comment by vaughnroyko** [comment]
I get this from time to time as well. Will see if I can reproduce on purpose.

**Comment by filipesilva** [comment]
Have this as well. Windows 8.1, Atom 0.189.0, atom-typescript 2.9.0.

Here is a gif of it happening:

![blinking-hover](https://cloud.githubusercontent.com/assets/4172079/6994222/e3c2fa62-db08-11e4-8a29-48aca69911e0.gif)

**Comment by nycdotnet** [comment]
Bas, instead of blink you should have implemented marquee.

**Comment by basarat** [comment]
> Bas, instead of blink you should have implemented marquee.

`blink` was a feature. I don't know why people don't get it. But okay if you prefer marquee: 

![marquee](https://cloud.githubusercontent.com/assets/874898/6995149/bc176abe-db78-11e4-933c-ef71c315f82d.gif)


*This post is meant for humor*.

**Comment by basarat** [comment]
@filipesilva questions:

* are you getting this reliably?
* Is there a 1:1 relationship between the blink rate and the cursor blink rate as originally suggested (yours seems to be much faster than the cursor blink rate)


Things I've ruled out: 
* window not being in focus. Doesn't reproduce it.

* dependent on theme: Doesn't reproduce it.  
![t1](https://cloud.githubusercontent.com/assets/874898/6995171/576f6d12-db7a-11e4-84d2-39e01d00d80c.gif)

* dependent on font size: Doesn't reproduce it.
![t2](https://cloud.githubusercontent.com/assets/874898/6995172/654ebfa0-db7a-11e4-9769-a8f053d2f691.gif)

I haven't got a reliable reproduction yet.

**Comment by filipesilva** [comment]
Yesterday I installed atom-typescript, and had this problem immediately. Tried restarting and disabling all community packages, but it still seems to happen. 

It does not seem to be tied with cursor refresh rate though, but it's tied to an icon at the bottom right:
![bottom-left](https://cloud.githubusercontent.com/assets/4172079/6996505/b9ee4478-db83-11e4-87f8-60a004bc7ae6.gif)

**Comment by basarat** [comment]
> It does not seem to be tied with cursor refresh rate though, 

Cool. Might be a rendering issue. 

> but it's tied to an icon at the bottom right:

That icon is there to show if there is any TS processing stuff going on. Since there is going to be a new request for every "get tooltip" query that is expected. Its likely (strong) correlation not causation, but thanks for testing again. PS: the icon only got added recently :heart:

**Comment by filipesilva** [comment]
Anything else you'd like me to look into, just say the word. I'm trying to get into TypeScript and this plugin is just awesome :p

**Comment by basarat** [comment]
@filipesilva thanks for the kind words mate. 

Does this blinking happen to you consistently or only sometimes?

**Comment by filipesilva** [comment]
Consistently. In fact, I've always had it since I installed the plugin.

**Comment by basarat** [comment]
> Consistently.

OS? Windows or mac or linux?

**Comment by filipesilva** [comment]
Windows 8.1

**Comment by david-driscoll** [comment]
Similar thing is happening for me as well.  I'm also on Windows 8.1 if that helps.

**Comment by vaughnroyko** [comment]
I have not been able to reproduce this on purpose as of yet, and my blinking rate is definitely not as fast as @filipesilva but it happens commonly. Will continue testing; however I'm on Windows 7.

**Comment by basarat** [comment]
I am on windows 8.1 in the office so I don't think there is a correlation. Hopefully this will fix itself over time if we don't get a good repro.

**Comment by basarat** [comment]
Looking at the repo where I copied this logic from to see if its been reported there and indeed it has : https://github.com/chaika2013/ide-haskell/issues/44 

Fixed there by returning if last show location is same as this show location : https://github.com/chaika2013/ide-haskell/commit/0a587358cf6e77ad56f9847dc8c1457044054862 

The real issue is why is `mousemove` getting triggered and now I suspect its just dust particles in the mice.

**Comment by filipesilva** [comment]
I've my mouse settings at a high sensitivity, but I happened to try with
the touch pad and the same thing happened.

**Comment by filipesilva** [comment]
I can confirm it works :D
