### ISSUE TITLE
Stale linter errors trigger while half-done typing then don't go away

### ISSUE THREAD

**Issue by ryanberckmans** [TypeStrong/atom-typescript#1493]
Linter errors as displayed in Nuclide don't clear after the code has been updated to fix the error. Most often this happens when halfway done typing and linter "error" fires.

For example you'll type
```
const foo = ba/*not done typing and linter error shows*/
// --> linter error "ba not found"
// because it's supposed to be "bar" and I'm not done typing
```
and after completing the line, the linter error doesn't go away
```
const foo = bar;
// linter error is still "ba not found"
```

I have to run `Typescript: Clear Errors` and do so dozens of times per day. Maybe I shouldn't be using Nuclide anymore?

* atom-typescript 13.1.0
* atom 1.34.0
* nuclide 0.366.0
* linter-tslint 1.10.10

**Comment by lierdakil** [comment]
Hi. Sorry for the late response.

Not entirely sure what exactly is at fault here, but purely in theory, running `Typescript: Clear Errors` shouldn't help if tsserver got out of sync with the buffer (which is the usual culprit for issues like this), only if the UI got borked. It *is* possible that Nuclide is at fault here.

FWIW, Facebook dropped support for Nuclide last year. On the other hand, they dropped support for atom-ide-ui too, and I'm still using Atom-TypeScript with atom-ide-ui, and experience little to no issues.
