### ISSUE TITLE
Autocomplete strings?

### ISSUE THREAD

**Issue by chrisdrackett** [TypeStrong/atom-typescript#1494]
I've noticed that autocomplete does not work for strings. Would this be possible to add? for example I have the following:

```
type Color = 'blue' | 'red' | 'green'

let color: Color

color="b"
```
 I would expect if the cursor is after the `b` in the last string to have an autocomplete menu with `blue` as an option.

**Comment by lierdakil** [comment]
Right. This is a holdover from way back. Hopefully fixed in v13.2.1
