### ISSUE TITLE
Can we typecheck plain JavaScript files?

### ISSUE THREAD

**Issue by trusktr** [TypeStrong/atom-typescript#1498]
Is it possible to use atom-typescript to typecheck regular JS files (like VS Code)?

**Comment by lierdakil** [comment]
https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#i-want-to-use-atom-typescript-with-javascript-too

Note: you also need `allowJs` and `checkJs` in your `tsconfig.json`.

**Comment by trusktr** [comment]
Thanks! Seems to work great! Nice to be able to incrementally convert them to `.ts` files.
