### ISSUE TITLE
[Opinion] atom-ide-ui is now archived

### ISSUE THREAD

**Issue by kpping** [TypeStrong/atom-typescript#1499]
From its [repository](https://github.com/facebookarchive/atom-ide-ui), atom-ide-ui is now archived. It's still usable but it will break. Should we remove it from Dependencies -> Option in README ?

**Comment by kpping** [comment]
Never mind. Duplicate of #1459

**Comment by lierdakil** [comment]
> it will break

Will cross that bridge when that happens. Perhaps someone from the community will pick it up (or at least parts of it).

FWIW, Atom APIs are rather stable these days, so there's a good chance atom-ide-ui will work for a good while still. Well, except terminal emulator that is, that one will break super-fast, if it's not broken already.
