### ISSUE TITLE
[Feature Request] File rename refactoring support

### ISSUE THREAD

**Issue by tanfonto** [TypeStrong/atom-typescript#1502]
Are there any plans to to implement such a feature? It seems it was possible for a while with tsserver*, VSCode and Tide both support it and jumping out of an otherwise _amazing_ editor / package just to run a single command is silly. 

*Basing on [this one](https://github.com/microsoft/TypeScript/blob/ec9652d9d697b555de9240ac3336d7452efdd2ae/src/testRunner/unittests/tsserver/rename.ts#L10) it may have something to do with user preferences and the  _allowRenameOfImportPath_ flag but don't take my word on it, I only started looking into tsserver internals today ;)

**Comment by lierdakil** [comment]
I believe basic function was implemented in v13.3.0. Please open new issues (or better yet, pull requests) in case you think it can be improved. Thanks.
