### ISSUE TITLE
Typescript export "interface" token is unexpected

### ISSUE THREAD

**Issue by TheEmrio** [TypeStrong/atom-typescript#1506]
Hello, I have updated the atom-typescript package to the latest version, and I have got this error:

[Steps to reproduce]

Open a typescript file
Type 
```ts
export interface a {
}
```
The keyword `interface` is underlined in red and hovering over it shows `Parsing error: Unexpected token interface (null)`

Btw, `tsc` compiles the script just fine so it is not a syntax error (also I used `export interface` a lot in my code)

Atom: 1.39.1
OS: Mac OS X 10.14.5
atom-typescript: 13.3.0

Community packages in my atom setup :
```
├── arduino-upload@1.5.1 (disabled)
├── ask-stack@2.2.0 (disabled)
├── atom-discord@2.0.2
├── atom-easy-jsdoc@4.12.5
├── atom-ternjs@0.19.1
├── atom-typescript@13.3.0
├── busy-signal@2.0.1
├── file-icons@2.1.33
├── hyperclick@0.1.5
├── intentions@1.1.5
├── jslint@1.5.1 (disabled)
├── language-ejs@0.4.0 (disabled)
├── linter@2.3.0
├── linter-eslint@8.5.5 (disabled)
├── linter-js-standard@6.1.2
├── linter-ui-default@1.7.1
├── processing@0.13.0 (disabled)
├── processing-autocomplete@0.2.0 (disabled)
└── processing-language@0.2.0 (disabled)
```

**Comment by lierdakil** [comment]
Can't reproduce. Try restarting Atom. Also, try `restart-all-servers` command, sometimes tsserver just gets confused for no discernable reason. No changes were made since v13.2.0 to produce the behaviour described (you can see the [diff](https://github.com/TypeStrong/atom-typescript/compare/v13.2.1...v13.3.0), it's rather short)

**Comment by TheEmrio** [comment]
Many sorries I found were the error comes from: when I updated atom-typescript, I also updated other packages like linter-js-standard which I changed the code locally because it performed linter on ts files and got confused with ts specific syntax. By updating the package, I guess it undid my changes, and that's why I was getting this error.
Thank you very much for your help :)
