### ISSUE TITLE
Configuring TS location

### ISSUE THREAD

**Issue by arcanis** [TypeStrong/atom-typescript#1511]
VSCode allows customising the location of TypeScript thanks to [`typescript.tsdk`](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions). Could the same be possible for `atom-typescript`? After digging in the sources I've noticed that there is an [automatic detection](https://github.com/TypeStrong/atom-typescript/blob/896e85275859979a24f83f7ace24b20464ef7064/lib/client/clientResolver.ts#L124), but in my users' case TypeScript is located outside of the `node_modules` folder.

**Comment by lierdakil** [comment]
> but in my users' case TypeScript is located outside of the node_modules folder.

Describe the use-case please, not entirely sure I follow.

The thinking in this particular case goes roughly like this: for one-off small projects, using the bundled TypeScript is in most cases adequate. For larger projects, it's generally a good idea to explicitly specify the required TypeScript version in `devDependencies`, and install it with the other dependencies as needed (hence the auto-detection resolution code).

If dependencies are just not installed in the standard `node_modules` directory, specifying `NODE_PATH` environment variable accordingly should work (this can be done in the Atom init script if needed only for Atom).

**Comment by arcanis** [comment]
For context, I work on Yarn, the package manager. You may have heard about something called Plug'n'Play, which replaces typical `node_modules` in JS installs by a single file that tells Node where are located the packages on the disk. It works great, but some projects that redefine the Node resolution (ie bypass `require.resolve`) may have difficulties.

TypeScript is one particular example. To make it work, we've developed a tool called [PnPify](https://next.yarnpkg.com/advanced/pnpify) which emulate the `node_modules`. Injecting PnPify in the Node runtime gives compatibility to tools that wouldn't otherwise where to find packages.

In order to enable PnPify with VSCode, we configure `typescript.tsdk` to a folder that contains a simple file that requires it before spawning the real typescript. This isn't possible at the moment with Atom, because we cannot configure the location of the sdk.

> specifying `NODE_PATH` environment variable accordingly should work 

The `NODE_PATH` setting has consequences outside of this plugin, so I'm not sure how practical it would be 🤔 I would prefer to just be able to set the setting in a file that would be checked-in, just like for VSCode.

**Comment by lierdakil** [comment]
> I would prefer to just be able to set the setting in a file that would be checked-in, just like for VSCode.

Hmm. I was thinking more along the lines of adding a package setting. But okay, it's not impossible to check a config file, say `.atom-typescript.json`, for the path to typescript installation. Do you suppose simple upwards directory traversal work for finding that config file, or do we need something more elaborate?

**Comment by lierdakil** [comment]
Ping. Is this still relevant? I'm a bit vague on what exactly the requirements are here, so I need some input. I did come up with some code, which you can see in #1527. Could you perhaps take a look, test, and let me know if it would work for you?

**Comment by arcanis** [comment]
Hey! Yep, still relevant 😃 Directory traversal as you implemented seems fine, I will take a look at it later this week. For reference, the following [repository](https://github.com/yarnpkg/berry) is an example where this situation arises. We configure TypeScript [here](https://github.com/yarnpkg/berry/blob/master/.vscode/settings.json#L4) so that it runs with a runtime that allows it to properly apply the resolution.

**Comment by lierdakil** [comment]
I played around a bit with the repo you linked, and after a few tweaks, #1527 seems to work. I've added explicit compatibility with the setup you have there. Still would be nice if you could take a look, but at this point I'm reasonably confident it should work.

One caveat is that we're using not only `tsserver`, but occasionally `tsc` as well (well, to be precise, the "initialize config" command will run `tsc`). The way the setup works right now, Atom-TypeScript will most likely use the bundled TypeScript to create the initial `tsconfig.json`. Not necessarily a huge issue, but still. The way to avoid that is to add `tsc.js` to `.vscode/pnpify/typescript/lib` (along the same lines as `tsserver.js` I imagine).

**Comment by lierdakil** [comment]
Released as v13.5.0. Please open new issues for additional suggestions and/or issue reports.
