### ISSUE TITLE
Wrong TypeScript version detected (no support for 3.7)

### ISSUE THREAD

**Issue by ramtinsoltani** [TypeStrong/atom-typescript#1524]
OS: Ubuntu 18.04.3 LTS x64
Atom version: 1.41.0 x64
Atom TypeScript version: 13.3.0

---

I'm using TypeScript 3.7.2 on my Ubuntu machine and Atom is detecting version 3.5.3 in my .ts files.

Is there no support for the new syntax in TypeScript 3.7.x? I'm specifically referring to optional chaining.

**Comment by lierdakil** [comment]
Atom-TypeScript should use whatever TypeScript version it finds in `node_modules` in your project. Failing that, it will fall back to the bundled TypeScript version, which happens to be v3.5.3 at the moment.

**Comment by ramtinsoltani** [comment]
@lierdakil I was hoping it would read the globally installed version of typescript if it's not installed in the project. But that makes sense. Closing this issue.

**Comment by lierdakil** [comment]
v13.5.0 adds a config option to specify a path to globally installed typescript SDK. Also the ability to override that per-project. See #1527 and/or https://github.com/TypeStrong/atom-typescript/blob/master/docs/advanced.md for more information
