### ISSUE TITLE
Something went wrong, see details below.

### ISSUE THREAD

**Issue by gurbaj5124871** [TypeStrong/atom-typescript#1529]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.2
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 13.4.4

### Stack Trace

Something went wrong, see details below.

```
At terminated on signal: SIGABRT

Error: terminated on signal: SIGABRT
    at ChildProcess.cp.once (/packages/atom-typescript/dist/client/client.js:137:19)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
  2x -9:48.9.0 datatip:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-typescript 13.4.4 
```

**Comment by lierdakil** [comment]
Hi. Apparently tsserver has crashed for some reason. The more common reason for this kind of crashes is Node out-of-memory errors (note that Node getting an OOM doesn't necessary mean your system is out of memory). If this doesn't happen too often, it's safe to simply ignore.
