### ISSUE TITLE
activating via init script not working?

### ISSUE THREAD

**Issue by chrisdrackett** [TypeStrong/atom-typescript#1538]
I'm not sure if something changed recently, but I'm trying to use this package with language-babel and the init screen no longer seems to be working. I know atom also recently updated, but wanted to check here as well.

```
do (grammarPackageImUsing = "language-babel") ->
  atom.packages.onDidTriggerActivationHook "#{grammarPackageImUsing}:grammar-used", ->
    atom.packages.triggerActivationHook 'language-typescript:grammar-used'
```

**Comment by lierdakil** [comment]
Apparently, Atom now uses Javascript for its init script (well, at least that's the case for me on Atom 1.41)?
Anyway, the equivalent JS code is like this:
```js
{
  const grammarPackageImUsing = "language-babel";
  atom.packages.onDidTriggerActivationHook(
    `${grammarPackageImUsing}:grammar-used`,
    () =>
      atom.packages.triggerActivationHook("language-typescript:grammar-used")
  );
}
```

**Comment by lierdakil** [comment]
Ah, right, 1.43 is out already. Let me update and get back to you

**Comment by lierdakil** [comment]
The code above works on 1.43 also.
