### ISSUE TITLE
Better Warnings / Tooltip for type errors please.

### ISSUE THREAD

**Issue by reduxdj** [TypeStrong/atom-typescript#1539]
Many times when trying to sort out errors in return types, the output is a mess. It comes back as a big long tooltip that says language like ...19 more | undefined;SomeTypeError. Reasoning about this is so difficult. I often even wish i could copy and paste, I actually take a screenshot and try to read this output because i can't even select copy and past from the tooltip

Please.

**Comment by lierdakil** [comment]
I'll be honest. The only feature request I could parse from this stream of consciousness is "copy-paste from error tooltips". Which isn't handled by us, so we can't do anything about it. `linter` with `linter-ui-default` allows copying from the diagnostics panel though (albeit it's a little wonky to tell the truth).

So... The best interpretations I can come up with are:

- This is a complaint about UI. This should go to the relevant UI package. Well, actually, atom-ide-ui is archived, so it's impossible and pointless to complain about that one, regrettably.

- This is a complaint about how the TypeScript compiler reports some class of type errors. Well, that should go to Microsoft/TypeScript probably, but beware that they don't appreciate issues that don't explain the issue clearly.

Either way, I don't know what I could help with here, besides pointing to the relevant repository.

**Comment by reduxdj** [comment]
Hey thanks, yeah, it's on the atom side. Thanks for your response, I'll go digging.
