### ISSUE TITLE
Atom-Typescript error: exited with code: 3

### ISSUE THREAD

**Issue by Superkooka** [TypeStrong/atom-typescript#1544]
**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 13.5.1

### Stack Trace

Atom-Typescript error: exited with code: 3

```
At Error: exited with code: 3

Error: exited with code: 3
    at ChildProcess.cp.once (/packages/atom-typescript/dist/client/client.js:158:19)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
     -0:38.4.0 core:paste (input.hidden-input)
     -0:38.2.0 core:save (input.hidden-input)
     -0:35.5.0 core:copy (input.hidden-input)
     -0:34.2.0 core:paste (input.hidden-input)
     -0:34 core:save (input.hidden-input)
     -0:31.9.0 core:copy (input.hidden-input)
     -0:30.5.0 core:paste (input.hidden-input)
     -0:27.3.0 core:copy (input.hidden-input)
     -0:25.7.0 core:paste (input.hidden-input)
     -0:23.2.0 core:copy (input.hidden-input)
     -0:21.6.0 core:paste (input.hidden-input)
  2x -0:21.6.0 core:copy (input.hidden-input)
     -0:17.6.0 core:paste (input.hidden-input)
     -0:15 core:copy (input.hidden-input)
     -0:09.8.0 core:paste (input.hidden-input)
     -0:09.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.17 
atom-discord 2.0.2 
atom-ide-ui 0.13.0 
atom-typescript 13.5.1 
autocomplete-glsl 0.2.3 
hyperclick 0.0.0 
ide-typescript 0.9.1 
language-glsl 2.0.4 
language-lua 0.9.11 
linter-luaparse 0.2.0 
```

**Comment by lierdakil** [comment]
Uh... Unless you've somehow built Atom with Node v8 or earlier (you'd have to work _really hard_ to do this, so you'd know if you did), exit code 3 [apparently](https://nodejs.org/api/process.html#process_exit_codes) means "Internal JavaScript Parse Error", which basically should never happen.

If this is a one-time thing, this would probably suggest a random bit flip in RAM, which, while rare, do  happen occasionally, unless you're using ECC memory (and in that case those still can happen, but the probability is much lower).

On the other hand, if this happens consistently, then your Node/Atom installation is likely corrupted somehow. This might indicate faulty storage (not necessarily, but somewhat likely).

**Comment by Superkooka** [comment]
> Uh... Unless you've somehow built Atom with Node v8 or earlier (you'd have to work really hard to do this, so you'd know if you did)

I've download the package on the tools provide by atom.

> If this is a one-time thing, this would probably suggest a random bit flip in RAM, which, while rare, do happen occasionally, unless you're using ECC memory (and in that case those still can happen, but the probability is much lower).

Now that you say it, right now I have a lot of bad memory problem

**Comment by Max-Strick** [comment]
I have got the same error in ~one minute after opening typescript file. But first, I have got : 
```
TypeScript server quit unexpectedly
Last output from tsserver:
emory: Zone
#
#
#
#FailureMessage Object: 000000041F5FA058
exited with code: 3
Hide Stack Trace
Error: exited with code: 3
    at ChildProcess.<anonymous> (C:\Users\{user_name}\.atom\packages\atom-typescript\dist\client\client.js:161:19)
    at Object.onceWrapper (events.js:282:20)
    at ChildProcess.emit (events.js:194:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
```
Then:

### Stack Trace

Atom-Typescript error: exited with code: 3

```
At Error: exited with code: 3

Error: exited with code: 3
    at /packages/atom-typescript/dist/client/client.js:161:19)
    at Object.onceWrapper (events.js:282:20)
    at ChildProcess.emit (events.js:194:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
```

### Commands

```
  5x -9:08.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-typescript 13.9.2 
busy-signal 2.0.1 
emmet 2.4.3 
file-icons 2.1.42 
ide-json 0.2.1 
intentions 1.1.5 
json-colorer 1.0.0 
linter 2.3.1 
linter-jscs 4.2.4 
linter-jshint 3.1.19 
linter-ui-default 1.8.1 
minimap 4.29.9 
rainbow-csv 1.4.0 
theme-switch 0.6.0 
```

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 13.9.2

**Comment by lierdakil** [comment]
@Max-Strick, TL;DR: most likely corrupted Node installation or faulty memory; can't do anything about that on our end obviously.

Output is truncated slightly, but from what I see, it has to be Node crashing with `Fatal: process out of memory: Zone` error, which is, more eloquently, "Zone allocation failed" V8 memory allocation error. So... it's either faulty memory and/or Node installation, or you're on a system with a tiny amount of RAM and no swap file. Or perhaps there isn't any _free_ memory.

In any case, the package isn't at fault here at all, and we can't provide system support.

Good luck.
