### ISSUE TITLE
Make typings a @types/... package

### ISSUE THREAD

**Issue by aminya** [TypeStrong/atom-typescript#1548]
The types are useful to any Atom users. It is good to make them an individual package so everyone can use them.

**Comment by lierdakil** [comment]
Feel free to extract and publish those if you want to maintain them. I'm perhaps a bit jaded after being roped into maintaining a few packages over the last 5 years, but I certainly don't want to take on any more.

**Comment by aminya** [comment]
Sure. `atom-ide-ui` types can directly go to `@types/atom`. 
For `atom-select-list`, I might just release my package as `atom-select-list-plus` until someone merges that PR.
For others, we can have separate `@types` packages.

**Comment by aminya** [comment]
This is fixed in atom-ide-base. I will bring a PR.
