### ISSUE TITLE
Atom-Typescript error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by nurdyguy** [TypeStrong/atom-typescript#1564]
[Enter steps to reproduce:]

1. I clicked on a ts file 
2. message window said atom-typescript needed to download a package so I clicked "yes"
3. message windows showed error

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 14.0.1

### Stack Trace

Atom-Typescript error: Cannot read property 'length' of undefined

```
At TypeError: Cannot read property 'length' of undefined

TypeError: Cannot read property 'length' of undefined
    at /packages/atom-typescript/dist/main.js:9:8390)
    at /packages/atom-typescript/dist/main.js:9:294443
```

### Commands

```
     -1:19.9.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-typescript 14.0.1 
```

**Comment by lierdakil** [comment]
Thanks for the report and sorry for the trouble. Should be fixed in v14.0.2.

For the curious, issues with an upstream package, v14.0.2 reverts to an earlier release (that doesn't have this bug). Bug reported upstream: https://github.com/steelbrain/package-deps/issues/321
