### ISSUE TITLE
Option "Enable Atom-Typescript for JavaScript files" cannot be disabled

### ISSUE THREAD

**Issue by alexeiz** [TypeStrong/atom-typescript#1566]
This option is "on" by default.  If I set it to "off" and then restart Atom, it's still in the "on" state.  The version of atom-typescript is 14.0.3.

**Comment by lierdakil** [comment]
Can't reproduce.

If you're using a non-official Atom distribution, it's something that fork might be doing, take it up with the distributor.

Otherwise, post outputs of the following commands:

`apm --version`
`atom --version`
`apm list`

**Comment by lierdakil** [comment]
I've searched for a bit, and apparently 
`atom-ide-javascript` package forces this option to the "on" state. If you're using it, feel free to [take it up with them](https://github.com/atom-ide-community/atom-ide-javascript/issues) but be aware that it's a "wrapper" package -- it doesn't really do much besides installing some dependencies and configuring atom-typescript, so you should be free to disable/remove it in case you don't want atom-typescript on JS.

**Comment by alexeiz** [comment]
Indeed, disabling `aom-ide-javascript` resolves this issue.
