### ISSUE TITLE
Apply rename in one editor transaction

### ISSUE THREAD

**Issue by park9140** [TypeStrong/atom-typescript#157]
Rename applies changes as individual changes and undo takes way to long.  Roll undo into one transaction so that it is one undo step.

**Comment by basarat** [comment]
:+1: tips on how to do that? I'd be tempted to take a whack at it. I did it on our codebase during a demo and it quickly became non manageable

**Comment by park9140** [comment]
@basarat, If I don't get to it first, basically wrap the application of each call to editor to do a rename in https://atom.io/docs/api/v0.186.0/TextEditor#instance-transact.  Set the grouping interval to 1ms and since you are doing sync changes they should all group together. You may need to extend the grouping interval.

**Comment by basarat** [comment]
I do see transact used here https://github.com/atom/find-and-replace/blob/3386d13e412623bf64cc9001586db35a19364b58/lib/find-model.coffee#L59

**Comment by basarat** [comment]
I'm not sure about the grouping interval code though https://github.com/atom/find-and-replace/issues/108. Couldn't find it using my phone ❤️

**Comment by park9140** [comment]
@basarat, I was mostly complaining about having to undo multiple changes in one file.  

But no there does not appear to be a cross editor undo capability, ctrl-z just undos the current editor by design so it really would be weird if suddenly an undo reverted multiple editors.  Maybe a library to track and manage undo history project wide would be useful.

**Comment by basarat** [comment]
find and replace doesn't use a grouping interval. Neither should we : https://github.com/atom/find-and-replace/blob/3386d13e412623bf64cc9001586db35a19364b58/lib/find-model.coffee#L59 it is optional :+1:
