### ISSUE TITLE
Can't ctrl+click "multiclick" text with lint errors

### ISSUE THREAD

**Issue by NodeJoSe** [TypeStrong/atom-typescript#1571]
I can't multi-click code that has lint errors, this only happens when I have atom-typescript enabled. Tried to install Hyperclick and change it to alt+click and still does not work.

![image](https://user-images.githubusercontent.com/22928616/106619268-c90b2900-6546-11eb-9b46-d2f1f0c5a013.png)

**Comment by lierdakil** [comment]
This seems to be due to package `intentions`, specifically `ctrl` being bound to `intentions:highlight`. Perhaps try disabling it, see if it helps.
