### ISSUE TITLE
Atom-Typescript error: Server stopped normally

### ISSUE THREAD

**Issue by Nostomo** [TypeStrong/atom-typescript#1576]
[Enter steps to reproduce:]

1. The error is thrown when selecting a file in the tab.
2. This opens (attached fie).
![AtomIssue](https://user-images.githubusercontent.com/52637598/109831672-49d04a00-7c05-11eb-9788-e3461cce4ae7.png)

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: linux 5.8.0-44-generic
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 14.1.2

### Stack Trace

Atom-Typescript error: Server stopped normally

```
At Error: Server stopped normally

Error: Server stopped normally
    at /packages/atom-typescript/dist/main.js:1:115252)
    at Object.onceWrapper (events.js:288:20)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-django 0.3.2 
atom-material-ui 2.1.3 
atom-typescript 14.1.2 
busy-signal 2.0.1 
file-icons 2.1.46 
intentions 1.1.5 
language-graphql 1.0.0 
linter 3.3.0 
linter-eslint 8.5.5 
linter-flake8 2.4.0 
linter-ui-default 3.0.2 
minimap 4.39.9 
pigments 0.40.6 
```

**Comment by lierdakil** [comment]
So, we have two issues:

1. your tsserver just quits without reporting any errors when atom-typescript tries to do something
2. you apparently don't have any UI in Atom

I strongly suspect something is horribly broken under the hood. Couldn't tell what exactly. Is your Atom functional at all to begin with?

FWIW, can't reproduce.

**Comment by Nostomo** [comment]
Yeah, it wasn't, but apparently Ubuntu missed telling me Atom needed an update, now fully updated Atom & Atom-Typescript works perfectly.
Thanks.

**Comment by lierdakil** [comment]
Glad to hear you got it working!
