### ISSUE TITLE
New code is not being parsed correctly

### ISSUE THREAD

**Issue by henriquesaias** [TypeStrong/atom-typescript#1589]
I've tried reinstalling the package but it keeps giving me what appear to be random errors whenever I type in or paste new code. Every line has multiple errors and they make no sense, as far as I can tell. 

This has been happening for at least a week, I've been working mostly on the frontend folder which parses the code using TypeScriptReact and gives me no problems. Now I need to do stuff on the server and, instead of helping me, the IDE is cluttering my screen with squiggly lines, red exclamation marks and bad advice. 

Please help me understand what's going on!

<img width="1154" alt="Screenshot 2021-07-28 at 21 09 53" src="https://user-images.githubusercontent.com/31808055/127389056-22848010-ef19-475e-85a9-6c795c304e18.png">

<img width="1139" alt="Screenshot 2021-07-28 at 21 13 28" src="https://user-images.githubusercontent.com/31808055/127389368-2b03823f-6011-4e16-9995-83e3ce70f02a.png">

**Comment by lierdakil** [comment]
No idea, but if I had to guess, tsserver is picking up the wrong project. Perhaps try enabling "Spawn separate tsserver instance for each tsconfig.json" -- it often helps if that is the case. Other than that, restarting Atom (via `Window: Reload` for example) generally helps when things go out of whack.
