### ISSUE TITLE
Auto-indent doesn't work?

### ISSUE THREAD

**Issue by mindplay-dk** [TypeStrong/atom-typescript#159]
The only problem I have with this plugin so far, is it seems to mess up auto-indent?

Using ATOM 0.186, with "Auto Indent" enabled, "Show Indent Guide" switched on, "Tab Length" set to 4 and "Soft Tabs" enabled.

Whenever I press ENTER in the editor, the cursor positions itself at the beginning of the line.

I have no other community packages installed, just this one.

PS: Thank you for this incredible plugin! I have tried every other Typescript plugin for ATOM (typescript-atomizer, language-typescript and atom-typescript-tools) some of which threw errors, none of which were able to even auto-complete. Excellent work!

Are you getting paid for this work, or where can we donate?

**Comment by basarat** [comment]
> Are you getting paid for this work, or where can we donate?

No plan for a financial donation mechanism at the moment :heart:. It would be great if you can [leave a review on twitter](https://twitter.com/intent/tweet?text=Silky smooth TypeScript development&url=https://atom.io/packages/atom-typescript&hashtags=Atom,TypeScript&via=basarat)

ref : https://github.com/TypeStrong/atom-typescript/issues/66

**Comment by basarat** [comment]
![autoindent](https://cloud.githubusercontent.com/assets/874898/6524712/c1c23b36-c450-11e4-9ac9-bc6bbaaf1a67.gif)

It doesn't work. We didn't do any *special* work to tweak to so it was expected. As you can see in the gif Atom is doing *something* for TypeScript files in that the brackets are placed correctly but you still need to indent the cursor into place. I suspect its done because of `scope` being `source` (we set the grammar scope to be `source.ts`). This magic done by atom is the reason why it hasn't been crucial. Going all the way with great auto-indent shouldn't be too hard if it goes according to my plan. Expect it soon.

**Comment by basarat** [comment]
research : https://github.com/griiin/atom-auto-indent/blob/master/lib/auto-indent.coffee

**Comment by basarat** [comment]
The non dynamic grammars get their indent settings from : https://github.com/atom/language-javascript/blob/master/settings/language-javascript.cson

**Comment by basarat** [comment]
Based on my last commit `atom.config.get('editor.increaseIndentPattern', {scope: ['.source.ts']})` gives `"(?x) \{ [^}"']* $ | \[ [^\]"']* $ | \( [^)"']* $ | case[\s\S]*: $ | default: $"` 

This is now same as `atom.config.get('editor.increaseIndentPattern', {scope: ['.source.js']})`. Previously it was really just `atom.config.get('editor.increaseIndentPattern', {scope: ['.source']})` that was triggered for TS. 

![image](https://cloud.githubusercontent.com/assets/874898/6526045/5a6405d0-c461-11e4-9de9-c8e64f9e5c2a.png)

# my new suspicion
Now a larger issue is that js gets tokenized seperately for each `{` and `}` as shown : 
![image](https://cloud.githubusercontent.com/assets/874898/6526064/9459b730-c461-11e4-81b7-2d3cb73f8eff.png)

Whereas TS merges the two: 

![image](https://cloud.githubusercontent.com/assets/874898/6526069/b1d1d07c-c461-11e4-935c-9aa62b59d888.png)

**Comment by basarat** [comment]
I've differentiated the punctuation. TS was classifying each seperately. Atom is just efficient to collapse adjacent similar classifications into a single DOM node. I still pushed my commit as it make it easier for us to reuse `(){}` js theme styles (if any).

**Comment by basarat** [comment]
However this was not the source of the problem and I am still looking for a solution

**Comment by basarat** [comment]
I've asked for help https://discuss.atom.io/t/need-help-fixing-autoindent/15322

**Comment by basarat** [comment]
Well figured it out myself. There are plenty for dragons in writing our *dynamic grammar*. The tricky one here was that atom wants you to tokenize an empty line as whitespace (or anything with a name) for autoindent to work :heart:

**Comment by basarat** [comment]
watch it :loop: 
![autoindent](https://cloud.githubusercontent.com/assets/874898/6526642/44deaf1a-c468-11e4-9610-7d244a800bc9.gif)

**Comment by basarat** [comment]
`v0.82.0`

**Comment by mindplay-dk** [comment]
Looks good! Thanks :-)

Something that confused me is, in ATOM's core settings, there's an "Auto Indent" checkbox, which apparently does nothing at all. In the "Edit" menu, in the "Lines" submenu, there's also an "Auto Indent" checkbox menu item, which doesn't appear to be the same setting - it's unchecked, even though I checked the one on the core settings screen... Anyway, checked the one in the menu, and, behold, that one actually works - the one in the core settings screen doesn't seem to have any effect at all. I wonder why there's two of these...
