### ISSUE TITLE
It breaks one-key autocomplete

### ISSUE THREAD

**Issue by artyompal** [TypeStrong/atom-typescript#1590]
I use Autocomplete-plus plugin, which has an option of automatically confirming a single possible suggestion. Let's say, I have an identifier `my_long_function_name` somewhere in my code, so I start typing `my_long_f` and press autocomplete key, and since there is only one possible option, it just finishes the word without displaying any menus. This plugin breaks this behaviour. The menu with function prototype is shown instead. Would it be possible to make this behaviour optional please? I cann't seem to find a setting to disable prototype tooltips. Thanks!

**Comment by artyompal** [comment]
Also it seems to change autocomplete settings to enable fuzzy autocomplete, like `on_ev` not matches `on_event_happened`, but also `on_some_evaluation`. Can we have a setting to control this behaviour?

**Comment by lierdakil** [comment]
Released v14.4.0 that adds a few setting toggles to configure autocomplete suggestion filtering behaviour.

So your first gripe should be solved by enabling the following setting:
![image](https://user-images.githubusercontent.com/7275622/139599565-3910532c-d69a-48a6-885b-cfb94248df81.png)

The second one should be covered by disabling
![image](https://user-images.githubusercontent.com/7275622/139599593-7faa8e49-ca0d-4bf3-bd87-c38c041a81be.png)

Also, a couple toggles below that allow you to control how filtering is done exactly. This is obviously somewhat experimental, but it worked surprisingly well in my limited testing.
