### ISSUE TITLE
Is it possible to use this package with language-babel instead of language-typescript?

### ISSUE THREAD

**Issue by saadq** [TypeStrong/atom-typescript#1597]
The main thing I'm missing from `language-babel` is using the builtin Emmet autocompletion for `styled-components`. I did see that there was a [PR](https://github.com/TypeStrong/atom-typescript/pull/1182) to do something similar, but it seems to have been abandoned. Now that this package is not using its own grammar, this seems harder to do.

Is there any way I can just always use the `language-babel` package for all my TS files and to make `atom-typescript` still work with it somehow? I tried changing the [`activationHooks`](https://github.com/TypeStrong/atom-typescript/blob/master/package.json#L9-L11) from:

```
"activationHooks": [
    "language-typescript:grammar-used"
  ],
```

to

```
"activationHooks": [
    "language-babel:grammar-used"
  ],
```

but it didn't seem to have any effect. If this is possible to achieve, please let me know! Thanks.

**Comment by lierdakil** [comment]
https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#i-want-to-use-package-x-for-syntax-highlighting-instead-of-language-typescript-but-atom-typescript-doesnt-work
