### ISSUE TITLE
Discoverability of commands

### ISSUE THREAD

**Issue by nycdotnet** [TypeStrong/atom-typescript#161]
Quick suggestion - It would be great if atom-typescript's commands were listed in an item under the Packages menu.

The menu would serve as a helpful, always up-to-date reminder of what atom-typescript can do and what the keyboard shortcuts for those commands are.  This menu could also include a link to the project readme.

**Comment by basarat** [comment]
We prefix all our commands with "TypeScript". Press ctrl + shift + p to open atoms command pallet and type in typescript to see the list. Definitely worth mentioning this in the docs.

**Comment by Aedaeum** [comment]
I'd like to mention that the https://atom.io/packages/keybinding-cheatsheet is an excellent plugin for this. Simply filter typescript and you get all the keybindings.

**Comment by sedwards2009** [comment]
I suspect that a lot of people (myself included) don't use the command palette and instead rely on and expect the menus in an application to function as an index to the application's functions and a place to look up and learn the keyboard shortcuts.
