### ISSUE TITLE
Don't include apd in your code

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#163]
Fork the official repo. Make the edits and tag it. Use the tag in your package.json

**Comment by basarat** [comment]
closed by https://github.com/TypeStrong/atom-typescript/commit/30813fd8692976a678832a06372638ddbc35426f

**Comment by basarat** [comment]
@park9140 with this I cannot publish anymore. Any tips? 

![image](https://cloud.githubusercontent.com/assets/874898/6538021/b02617a2-c4b0-11e4-8582-30112848793c.png)

**Comment by basarat** [comment]
Note that NPM is okay with this https://github.com/TypeStrong/atom-typescript/blob/master/package.json#L36 I commited an `npm install` which ran fine

**Comment by basarat** [comment]
@park9140 `git:` urls work ;) 

@csnover worth considering if you ever plan to publish TypeScript pointing to a repo instead of NPM.

**Comment by csnover** [comment]
I’d recommend using https URL pointing to archive instead, git protocol is restricted by many corporate firewalls and https archive will not download a whole git repository just for one set of checkouts.

**Comment by basarat** [comment]
@csnover you mean `https://github.com/basarat/atom-package-dependencies.git`? (I didn't get what you meant by `archive`> perhaps `repo`?).

**Comment by csnover** [comment]
https://github.com/basarat/atom-package-dependencies/archive/cb1.tar.gz

**Comment by jordanbtucker** [comment]
URLs in the form of `github:user/repo` work. The `github:` protocol is required. See https://github.com/atom/apm/blob/v1.1.1/src/publish.coffee#L300
