### ISSUE TITLE
Integrate TSD

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#167]
see https://github.com/DefinitelyTyped/tsd/ 

Steps:
- [ ] Load tsd.json for a given tsconfig.json. Assume its right next to tsconfig.json 
- [ ] Document its location
- [ ] Provide a quick fix `tsd install` if user does an `import` for something that isn't there

Nice to have: 
- [ ] Provide a PR to definitely typed
- [ ] Provide an uninstall

**Comment by lierdakil** [comment]
Closing due to tsd deprecation. Current definition management system doesn't use external tools.
