### ISSUE TITLE
Get formatting changes while editing

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#17]
on `;` and `}` would be great.

**Comment by park9140** [comment]
@basarat, I believe typescript tools api can have requests for this sent on every edit, and it should be efficiently handled.  So we probably don't need to limit it to just those two characters.

**Comment by basarat** [comment]
@park9140 issue is people don't want edits to happen in the middle of an edit session. This is what resharper does. Also only on matched `}` Or and enter after a matched `}`

**Comment by basarat** [comment]
Sample : getFormattingEditsAfterKeystroke at https://github.com/Microsoft/TypeScript/blob/master/src/server/session.ts#L456
