### ISSUE TITLE
Files in <reference> comments not found if not in tsconfig.json

### ISSUE THREAD

**Issue by csnover** [TypeStrong/atom-typescript#171]
atom-typescript correctly loads files from `import` statements but it doesn’t seem to load reference files, they will only work correctly if you have a tsconfig.json.

**Comment by basarat** [comment]
Cause : reference expansion does not work if you are not referencing by file extension. 

In the test I've added `/// <reference path='./foo'/>` fails but `/// <reference path='./foo.ts'/>` succeeds. Just thought I'd leave this information here

**Comment by csnover** [comment]
`/// <reference path="../foo/foo.d.ts" />` was what failed for me. There used to be a function for processing these, I committed code to it before, but I can’t find it in the source any more…

**Comment by basarat** [comment]
> I committed code to it before, but I can’t find it in the source any more

This function : https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/tsconfig/tsconfig.ts#L390-L444 . There needs to an `fs.existsSync` check to figure out which version the user meant

**Comment by csnover** [comment]
Seems that saving d.ts files referenced in tsconfig.json `files` does not cause code intel to reflect those saved changes; wondering if it is part of this bug or a separate bug…
