### ISSUE TITLE
Doc tsconfig.json

### ISSUE THREAD

**Issue by Phaiax** [TypeStrong/atom-typescript#172]
Hey.

I'm currently trying to mimic the behaviour of `filesGlob` in my sublime plugin ArcticTypescript.

In the [doc](https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md) you mention that it is possible to use `glob / minimatch / RegEx`.

I just installed atom to test your implementation and I found no way to use regex. I think it may only work with `var somglob = /regex/;`, but this is not allowed in json.

Is that right or am I missing a trick?

**Comment by Phaiax** [comment]
for further compatibility, I would propose to minimize the functionality of filesGlob parsing. There are many IDEs out there, and if this will not become an official feature it is hard to implement the same behaviour in different languages.

I think we should define a featureset:
 * `!` for invertion
 * `*` and `**` for `foo` and `foo/bar`
 * `?` for chars
 * `[a-z]` for character sets

Things i would not consider *standard*:
 * `src/+(foo|bar).ts`
 * `src/{app,main}.ts` shell expansion

I just compared different glob implementations and they differ in the interpretation of `**`:
 * Some allow the `**` expansion to *not* contain a slash, some assume `**` must have a slash within.
   -> `**` will either include the file foo.bar in the root dir or it will exclude that file
 * Sometimes `**.ts` is allowed, sometimes not.

I would suggest, that `**` can also match a simple file in a root folder and `**.ts` would be allowed. This would consider the string-aspect of each path.

**Comment by Phaiax** [comment]
Since I ran into to many issues, i decided to use a simple nodejs script with exactly the same library as atom-typescript > 100% compatibility.

I think this can be closed.

**Comment by basarat** [comment]
:heart: Awesome to hear that. I have a friend who insists on using TypeScript. I just tried *better TypeScript* and it wasn't better. I'll give your package a go :heart: 

We plan to outsource tsconfig.ts parsing to this project : https://github.com/TypeStrong/tsconfig once we solve the TypeScript tooling problem.

**Comment by Phaiax** [comment]
try the next_big_thing branch if you are not using windows (there are some bugs i did get rid of so far)

**Comment by basarat** [comment]
@Phaiax just found out that the TypeScript team is also working on a sublime text plugin : https://github.com/Microsoft/ngconf2015demo

**Comment by basarat** [comment]
@Phaiax the main file : https://github.com/Microsoft/ngconf2015demo/blob/master/sublimetext/typescript/TypeScript.py
