### ISSUE TITLE
Disable emit-on-save in tsconfig.json?

### ISSUE THREAD

**Issue by Deathspike** [TypeStrong/atom-typescript#175]
I would like to request a feature to disable emit-on-save based on the `tsconfig.json` file. In my situation, I have 2~3 projects living together in the same folder structure. These are the client and server components, sharing some of the definitions and logic with one another using a shared component. I will elaborate on the feature request.

The client component is compiled using `browserify` and `tsify`. This enables writing `nodejs`-like applications which bundles all the dependencies nicely together into a single output file to load into browsers. It also supports source maps, which would otherwise be lost when the files were build into an intermediary file prior to bundling them up with `browserify`. This component should have **emit-on-save** disabled.

The other component is a *NodeJS*-based application. It serves as the server back-end for the client component. Bundling this up would be awkward and silly, so the emit-on-save facilities save time and provide nice integration with the editing experience. Furthermore, `node-inspector` debugging is quite happy with the emits I can make from the editor like this. No further build or watchers necessary, so this is great here.

Would it be a reasonable idea to enable/disable emit-on-save per project, rather than on/off?

**Comment by basarat** [comment]
@Deathspike we recommend you use something like : https://github.com/TypeStrong/atom-typescript/blob/master/docs/packages.md#manage-your-projects for now.

Having said that I now realize that perhaps it does belong in `tsconfig.json` under an `atomts` key as well since you might want to share this setting. So I will reopen with `has-workaround`. Probably low priority though.

**Comment by Ciantic** [comment]
What is the name of this setting? I saw "compileOnSave" in the another thread, this however does not work:

    'MyTestProject':
      'title': 'MyTestProject'
      'paths': [
        '...'
      ]
      'settings':
        'atom-typescript.compileOnSave': false

I use webpack so extra js files doesn't make sense. I still want to compile or statically check though, just without extra files.

**Comment by Ciantic** [comment]
Oh I see this link https://github.com/TypeStrong/atom-typescript/blob/master/docs/packages.md#manage-your-projects doesn't contain new information. It's enough to just put in tsconfig a "complieOnSave : false".

**Comment by basarat** [comment]
@Ciantic Can I have the link to that thread 🌹
