### ISSUE TITLE
Respect tab length for generated tsconfig.json

### ISSUE THREAD

**Issue by Deathspike** [TypeStrong/atom-typescript#181]
I have Atom configured with a Tab Length of 2 (main settings).

The tsconfig.json that is generated uses 4 spaces instead of 2.

It's not really critical, but a nice-to-have thing since I have everything else in 2 tabs.

**Comment by basarat** [comment]
:+1:

**Comment by hachre** [comment]
Same goes for using tabs for indentation. Even though my atom-beautify is correctly set up atom-typescript replaces all tabs with spaces for this file.

**Comment by msssk** [comment]
:+1:

**Comment by pixelshaded** [comment]
We use 2 spaces per tab as well and it's been painful when using version control. I have to convert it back to 2 spaces before I commit so there isn't a bunch of noise related to the file. Not everyone is using atom.

**Comment by pixelshaded** [comment]
I've no idea at the moment how to get tab length out of the global settings, but if you want to change what atom-typescript is using, go to:

C:\Users\<username>\.atom\packages\atom-typescript\dist\main\tsconfig\tsconfig.js and on line 416 you can change the tab length used by JSON.stringify.

**Comment by pixelshaded** [comment]
Normally you'd do atom.config.get('tabLength') but the tsconfig.js is run inside a web worker that doesn't have access to the atom global =/

**Comment by D1no** [comment]
This problem seems to also apply to formatting.js
- atom-typescript was ignoring the 2 spaces tab settings until I changed it in there from 4 to 2.

**Comment by pranayhere** [comment]
tsconfig.js file is not there.
changed formatting.js, set the value to 2 but still facing the same issue. 

What should I do to change tab space?

Below is the content of my formatting.js file

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Maintainance:
 * When a new option is added add it to:
 * - the FormatCodeOptions interface
 * - the defaultFormatCodeOptions function
 * - the makeFormatCodeOptions function
 */
const os_1 = require("os");
function defaultFormatCodeOptions() {
    return {
        baseIndentSize: 2,
        indentSize: 2,
        tabSize: 2,
        newLineCharacter: os_1.EOL,
        convertTabsToSpaces: true,
        indentStyle: "Smart",
        insertSpaceAfterCommaDelimiter: true,
        insertSpaceAfterSemicolonInForStatements: true,
        insertSpaceBeforeAndAfterBinaryOperators: true,
        insertSpaceAfterKeywordsInControlFlowStatements: true,
        insertSpaceAfterFunctionKeywordForAnonymousFunctions: false,
        insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis: false,
        insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets: false,
        insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces: false,
        insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces: false,
        placeOpenBraceOnNewLineForFunctions: false,
        placeOpenBraceOnNewLineForControlBlocks: false,
    };
}
exports.defaultFormatCodeOptions = defaultFormatCodeOptions;
//# sourceMappingURL=formatting.js.map

```
