### ISSUE TITLE
Emit detect broken

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#182]
Previously we had: 

success : `output.emitOutputStatus === ts.EmitReturnStatus.Succeeded;`
emitOnly: `!success && outputFiles.length`

Now `getEmitOutput` only returns :

```ts
interface EmitOutput {
    outputFiles: OutputFile[];
    emitSkipped: boolean;
}
```

With only `emitSkipped` we don't know if it was a *complete success* i.e. a semantically valid emit or just a bland emit.

**Comment by basarat** [comment]
refs https://github.com/TypeStrong/atom-typescript/pull/179#issuecomment-78026878

**Comment by basarat** [comment]
refs https://github.com/Microsoft/TypeScript/issues/2289

**Comment by DanielRosenwasser** [comment]
You can use the `--noEmitOnError` flag for this.

**Comment by basarat** [comment]
@DanielRosenwasser I still want to get an emit. So did this : https://github.com/TypeStrong/atom-typescript/commit/02622f9cb3516bf868781cdaebd55eb9ed4060ee#diff-578ff651be440fee29ecfe22d52e81a4L41
