### ISSUE TITLE
Performance Issues With Undo/Backspace - Freezing/Crashing

### ISSUE THREAD

**Issue by vaughnroyko** [TypeStrong/atom-typescript#183]
On a fresh, clean install with Atom Typescript (with Linter/Autocomplete+) installed, the following issues occur on a larger .ts file (around 3000+ lines, although the more lines you have, the bigger the issue - there is some stuttering even on 500 line files):

Holding down backspace over any code in file will cause the linter to execute (or maybe it's just the TypeScript error checking?), seemingly every character removed, freezing Atom completely during being held down and up to 1 minute after backspace is let go. This effect can sometimes even lock up Atom completely, never recovering. It also appears that the autocomplete dialog seems to be firing as well during this, as if you get it to stop in the right place, it will open up (only sometimes). Undoing a large amount of operations will also illustrate this issue, especially over lots of small changes.

This isn't directly related, but could solve the issue I am describing. Changing any option in the Linter/Autocomplete+ settings will have no effect on Atom Typescript. Not sure if this is by design, but being able to control the linter and autocomplete settings would solve the issues I am describing since I could disable linting/error-checking on change, or use a execution timeout, or limit the results in autocomplete, or the letters needed to autocomplete. Type the letter "i" and watch the tens of thousands of results it gives on a medium-sized project.

Showing the effects of the performance issue:
http://screencast.com/t/iBywbX2KF2w5

I start by editing a smaller file with no issues, then move to a bigger one. As you can see it's taking full chunks out of my code with backspace, freezing and stuttering as it goes. During undo, it locks up for a couple seconds at a time.

Any workaround is appreciated. Thanks!

**Comment by basarat** [comment]
Can you try the 1.5 branch 

cd %HOMEPATH%\.atom\packages
git clone https://github.com/TypeStrong/atom-typescript.git
git checkout typescript-1.5

It has fixes that don't post the entire text file to the worker all the time : https://github.com/TypeStrong/atom-typescript/pull/179

**Comment by basarat** [comment]
Can you try the 1.5 branch 

cd %HOMEPATH%\.atom\packages
git clone https://github.com/TypeStrong/atom-typescript.git
git checkout typescript-1.5

It has fixes that don't post the entire text file to the worker all the time : https://github.com/TypeStrong/atom-typescript/pull/179

**Comment by vaughnroyko** [comment]
Unfortunately still having the same issue.

**Comment by basarat** [comment]
@vaughnroyko Thanks for testing. Sorry that it didn't fix it. Can you share the repo? 

Also tip: you can paste images from clipboard directly in the github comment window. No need to use screencast.

**Comment by vaughnroyko** [comment]
@basarat Unfortunately it's a private repo at the moment. But I can reproduce it with a single file, completely unlinked from anything else. Here's such a file: http://vaughnroyko.com/stuff/items.ts

The screencast was a video. I could not find a way to attach the video directly - let me know if this is not the case.

**Comment by basarat** [comment]
> I could not find a way to attach the video directly - let me know if this is not the case.

ah. That explains why I couldn't open it on my phone. Just use https://screentogif.codeplex.com/

**Comment by basarat** [comment]
Your video is most excellent :+1: . Investigating.

**Comment by basarat** [comment]
A bigger issue is that editing the end of this large file will reliable (every time) : https://github.com/TypeStrong/atom-typescript-examples/blob/master/bigfile/bigfile.ts crash the new edit change detection.

**Comment by vaughnroyko** [comment]
I'm glad my giant definition file can serve as an example, hah. Thanks for looking into this!

**Comment by basarat** [comment]
Fixed : https://github.com/TypeStrong/atom-typescript/commit/c78a0f1d35fe4944cd191a47e70af174dac1c1ba#commitcomment-10157972 

Sorry about that. Still investigating LS version getting out of sync from reality. But that isn't causing this performance bug.

**Comment by basarat** [comment]
> Still investigating LS version getting out of sync from reality.

fixed https://github.com/TypeStrong/atom-typescript/commit/8fd3610d96c14d6f312b1255956fe11790bc4b57#diff-ed09a6b54d1678ad915acb85684ad75fR160 I am sad.

**Comment by basarat** [comment]
@vaughnroyko This should be fixed. Here is a demo on your bigfile: 
![bigfile](https://cloud.githubusercontent.com/assets/874898/6632472/f8f68424-c98a-11e4-9bca-8eee5adc6f83.gif)

**Comment by vaughnroyko** [comment]
I experienced the same performance as you did, doing what you were doing. And even backspacing over ObjectTypes in the lootGroups, it was all good (first thing done in the .gif below). But, when tried the same thing on strings, and then some more complex item objects, the same stuttering and freezing occurred, although I want to say it's not as bad as it was before, but not 100% sure on that:

![ts-backspace-performance](https://cloud.githubusercontent.com/assets/2846662/6634205/cc61d86a-c911-11e4-9b91-7b1d7217d87b.gif)
