### ISSUE TITLE
Warn on deprecated tsconfig properties

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#188]
As that seems to be the area where we (I?) keep finding the need to do breaking changes. The fact that I needed to rename `format` to `formatCodeOptions` is a good example. 

Will be done the next time we deprecate stuff.

**Comment by danielearwicker** [comment]
I just noticed that when I create a .ts file in an empty folder and save it, a tsconfig.json is saved with 

        "noimplicitany": false,
        "removecomments": true

i.e. names all lowercase. Then the plugin warns me that they are wrong and can auto-fix them! :+1:

**Comment by basarat** [comment]
❤️

**Comment by basarat** [comment]
we have a framework in place for this.
