### ISSUE TITLE
Atom TypeScript Update Failure

### ISSUE THREAD

**Issue by vaughnroyko** [TypeStrong/atom-typescript#190]
Just got this, this morning while trying to update Atom TypeScript to new version. I'm on Windows 7 (64-bit). I had no .ts files open at the time. Let me know if you need any more information.

After restarting Atom, it didn't show any updates for Atom TypeScript. It was indeed installed, but only partially? It didn't function at all and remained in "Installed Packages" without an image or version. 

Resolved by uninstalling and reinstalling. Not a big deal, but just thought I'd submit.

![update-fail](https://cloud.githubusercontent.com/assets/2846662/6714756/43540d46-cd57-11e4-9ec3-61a37bcbc978.png)

![update-fail-2](https://cloud.githubusercontent.com/assets/2846662/6714876/fac1cff4-cd57-11e4-840e-6dcb563e1f56.png)

**Comment by poelstra** [comment]
I've experienced this too, on Windows (on Linux, updating works like a charm).

There may be a bug in Atom's plugin management as well, which leaves the 'package database' in a invalid state: in my case I had to click Uninstall, then restart Atom, then search for the package and click Install again. Just Uninstall then Install didn't work.

Glad to help with testing, if needed.

**Comment by basarat** [comment]
I can reproduce it. Just did 
```
apm install atom-typescript@1.2.0
```
And then did an update through settings. Got the same error: 
![image](https://cloud.githubusercontent.com/assets/874898/6729064/eaa5b12c-ce82-11e4-8089-cc82e5ae1c52.png)

------------

Some useful information for me: 

the worker does get a kill signal, but we restart it very quickly
![image](https://cloud.githubusercontent.com/assets/874898/6729079/fd4aaa62-ce82-11e4-8837-6fa17d5d60c0.png)

Perhaps worthwhile to ignore worker restarting somehow for this particular case.

**Comment by basarat** [comment]
![image](https://cloud.githubusercontent.com/assets/874898/6729665/ec89ad08-ce88-11e4-8af2-bfa46badb2e9.png)
Fixed since v `1.3.1`

**Comment by poelstra** [comment]
Just confirmed that upgrading from 1.3.1 to 1.3.2 works!
Thanks @basarat!

Good to know about the double-window thing, I'll make sure to close them first for now :)

**Comment by vaughnroyko** [comment]
Just tried updating to 1.3.2 and got the same issue as described above. Only had one window open. Let me know if there's anything I can do to help debug.

**Comment by vaughnroyko** [comment]
Actually, I don't think I was on 1.3.1, I was on a earlier version, before the fix I would assume. Nevermind! Thanks!
