### ISSUE TITLE
Run pre-processing only

### ISSUE THREAD

**Issue by corneadoug** [TypeStrong/atom-typescript#194]
Hi,

I am wondering if it's possible to run pre-processing only in order to have errors, but to not generate any .js files.

I wanted to use outDir options, but it doesn't seem to be working so I'm looking for a way to just get errors since I'm using grunt to build on the side

**Comment by poelstra** [comment]
FWIW: I'm using outDir too, and for me it's working as expected. Relevant piece of my tsconfig.json:

```json
{
    "version": "1.4.1",
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "declaration": true,
        "noImplicitAny": true,
        "removeComments": false,
        "sourceMap": true,
        "outDir": "../dist/src",
        "noLib": false
    },
    "filesGlob": [
        "./**/*.ts"
    ],
    "files": [
    ]
}
```

**Comment by basarat** [comment]
You can disable compileOnSave : https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#compileonsave doing so might limit our ability to progress towards a better plugin so try to keep it disabled. 

But as mentioned outDir should work. Can you open a spectate issue about why your outDir isn't working :heart:
