### ISSUE TITLE
Update fails on windows if you have two atom windows open

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#195]
If you have two atom windows only the one where you are updating deactivates the package (and therefore stops the worker, needed to allow a file system unlink). 

This is not an issue if only a single atom window is open when you run an update.
## Workaround

Always update with just one atom window open. 
However if you are in a bad state workaround is to uninstall / reinstall the package. 
## Steps to reproduce

On windows run:

```
apm install atom-typescript@1.3.1
```

and then open two atom windows and run update in one of them. 
## Related

https://github.com/TypeStrong/atom-typescript/issues/190

**Comment by basarat** [comment]
You can see a demo. `ts worker sucessfully stopped` only appears in the front window. This means its still running the background window and hence cannot be unlinked / deleted. 

![image](https://cloud.githubusercontent.com/assets/874898/6729791/1b41af96-ce8a-11e4-84fb-239776d49920.png)

**Comment by nycdotnet** [comment]
@basarat Do you think something like https://www.npmjs.com/package/ps-node would help us know if there were multiple copies of atom running?  If so, do you know if there is a way to block or defer an update of a package until certain conditions are true?  I would be willing to look implement this as I constantly have several instances of Atom open.

**Comment by basarat** [comment]
> do you know if there is a way to block or defer an update of a package until certain conditions are true

Nope. And I suspect the atom team would be unwilling for packages to take such control. Best if someone fixes atom ... to call disable package on all open instances https://github.com/atom/atom/issues/6032

I just opened the bug and saw it says *needs reproduction* perhaps they are waiting on that. Pretty easy to do ... one just needs to create a package that has a log message on package deactivate and show that its isn't called in all windows.
