### ISSUE TITLE
formatCodeOptions are ignored

### ISSUE THREAD

**Issue by sclausen** [TypeStrong/atom-typescript#196]
It seems that formatCodeOptions in tsconfig.json are simply ignored.
setting intent size, tabsize or newlinechar doesn't affect the output.

Without compilerOptions, files and so on, my tsconfig.json looks as follows
``` javascript
{
  "formatCodeOptions": {
    "IndentSize": 2,
    "TabSize": 2,
    "newLineCharacter": "\n"
  }
}
```

**Comment by gregcwinn** [comment]
Looks like this might have been a regression.  

Changing "formatCodeOptions" to "format" caused it to work again on my system. (Plugin version 1.3.2)

**Comment by basarat** [comment]
> doesn't affect the output.

Just to clarify: do you mean JS output or formatting commands output

**Comment by sclausen** [comment]
Yes, exactly. Sorry I didn't pointed this out.

**Comment by basarat** [comment]
> Yes, exactly. Sorry I didn't pointed this out.

Again: do you mean JS output or formatting commands output :heart:

**Comment by sclausen** [comment]
Oh damn that was an either-or question. I'm so sorry!
I meant the js output.

**Comment by basarat** [comment]
Cool. Its not designed to impact the JS output. Its designed for format TypeScript. I've updated the docs to clarify. There is no plan to control JS output formatting at the moment. Perhaps take it up with https://github.com/Microsoft/TypeScript :rose:
