### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by pspi** [TypeStrong/atom-typescript#2]
This looks interesting, good job basarat! What is on your roadmap for the few first features after syntax highlighting? 

Is it possible for Atom to do any object oriented stuff, I have been desperately looking for Typescript equivalent of Eclipse's Java-fatures like 

  - "Organize Imports" (remove unused import lines, add missing unambiguous ones) 

or many refactorings like
  - rename anything (class, method, variable and changes are propagated to related files)
  - move class to other module / file (and changes are propagated to related files)
  - take bunch of code lines, variables they depend on and wrap them in a function (extract method)

**Comment by basarat** [comment]
From the original list only `fundamental refactoring exposed by the typescript language service` is left. Please see milestones for current roadmaps

**Comment by basarat** [comment]
https://github.com/TypeStrong/atom-typescript/milestones

**Comment by stepancar** [comment]
@basarat 'Organize Imports" (remove unused import lines, add missing unambiguous ones)'
is it available now?

**Comment by basarat** [comment]
> 'Organize Imports" (remove unused import lines, add missing unambiguous ones)'
> is it available now?

No, I've been distracted :rose:

**Comment by samsamm777** [comment]
> No, I've been distracted :rose:

@basarat What about now?
