### ISSUE TITLE
User issue: Installed the plugin, but it doesn't appear to do anything.

### ISSUE THREAD

**Issue by jtheisen** [TypeStrong/atom-typescript#201]
I want to apologize in advance, I probably simply do a usage mistake as I'm new to atom as well. I can't get the plugin to even give me syntax highlighting, even though my file has the right extension:

![image](https://cloud.githubusercontent.com/assets/1516294/6780536/76d323c4-d166-11e4-9851-58fb2e7cf738.png)

It also doesn't give me typescript in the language selector:

![image](https://cloud.githubusercontent.com/assets/1516294/6780508/43aa4108-d166-11e4-9447-841906a2e836.png)

But it's installed:

![image](https://cloud.githubusercontent.com/assets/1516294/6780499/28f0a00a-d166-11e4-88dc-540b88a820de.png)

Atom is at version 0.187.0, I'm using it on windows.

**Comment by basarat** [comment]
a.) Is the file saved to disk?
b.) did you get the message `AtomTS: Dependencies installed correctly. Enjoy TypeScript ♥`?

**Comment by jtheisen** [comment]
a) Yes. Shouldn't I at least have TypeScript in the language selector?
b) No, but where should the message appear anyway? I installed it in the package management you get on pressing ctrl-; - I don't see any console for text to appear there.

**Comment by basarat** [comment]
> where should the message appear anyway

Once you install the package this should appear : 
![image](https://cloud.githubusercontent.com/assets/874898/6794862/f4a93c50-d22b-11e4-90a8-ec3206d6eb48.png)

Followed by : 

![image](https://cloud.githubusercontent.com/assets/874898/6794864/fe132710-d22b-11e4-88fe-1fa0442b978c.png)

Since it isn't, please try the following with atom closed: 

```
apm uninstall atom-typescript
apm install atom-typescript 
```

Sorry that it got fiddly. Shouldn't have happened. Hopefully it will be more painless over time. Do note that its a simple file system clean and re-install without deep OS hooks (like VS) so its still better once you get used to it.

**Comment by jtheisen** [comment]
The uninstall works - the package disappears - but the second install leads to the same result as the first one: After firing atom up again, the package is listed as installed, but it doesn't do anything.

(Had some trouble getting apm to run also, but it works when I run it in the bash that comes with git for windows.)

**Comment by basarat** [comment]
> Had some trouble getting apm to run also

That would explain it. You need to have `apm` in your path (reason why I don't mention is that it *should happen if you use the official atom installer*). We run the following on your behalf

```
apm install linter
apm install autocomplete-plus
```

So complete fix for you: 

```
apm uninstall atom-typescript 
apm install atom-typescript
apm install linter
apm install autocomplete-plus
```
And then run atom. 


Also you might want to reinstall atom and check that `apm` does end up on your path or you journey with *atom* might be a bit wobbly. 

Please close if this fixes it :heart:

**Comment by jtheisen** [comment]
Yes, reinstalling worked!

Thank you very much for your assistance, especially since this wasn't an issue with your package per se.

**Comment by omidkrad** [comment]
I had the same problem, and with @basarat's instructions I could install it. However, it's still not usable as I constantly get the console poped up with this error: `Uncaught TypeError: undefined is not a function` coming from `tooltipManager.js`

**Comment by basarat** [comment]
@omidkrad more info please. Seems to work fine here :

![image](https://cloud.githubusercontent.com/assets/874898/7291908/aab5cd96-e9d9-11e4-9a5f-b297268c0a60.png)

Perhaps even create a new issue.

**Comment by omidkrad** [comment]
I never get the message `AtomTS: Dependencies installed correctly. Enjoy TypeScript ♥?` whether installing with CLI or from inside Atom. I'll try some more if I couldn't get it working I'll open a new issue.

**Comment by mattmogford** [comment]
Following the instructions you gave to jtheisen this doesn't fix it for me.
The plugin installs for me, but I get no autocompletion.

Installing from Atom I don't see that 'complete' message, so I tried 
apm uninstall atom-typescript 
apm install atom-typescript
apm install linter
apm install autocomplete-plus

I still don't get autocomplete for anything.

**Comment by mattmogford** [comment]
I have found my problem.

A tsconfig.json file is required! Nowhere have I seen any mention of this. 
I know it's a thing, but didn't know it was required for autocompletion to work.

Maybe this should be a 'step 4' under the installation header on the github readme?
Possible just in the Auto Complete section, at the moment it simply says - "Just start typing and hints will show up".  This isn't 100% true.

Or maybe if there isn't a tsconfig file and you've created a .ts file it should ask if you want to create one?

**Comment by basarat** [comment]
> Or maybe if there isn't a tsconfig file and you've created a .ts file it should ask if you want to create one?

@mattmogford It does that already :rose: If it doesn't create a :bug: 

![image](https://cloud.githubusercontent.com/assets/874898/11134691/da2485b8-89f2-11e5-9759-a346bb5f201e.png)

**Comment by mattmogford** [comment]
True, but still odd that autocomplete doesn't work because of this.
I was going to get around to the config file, but wanted to just type some
code first.
