### ISSUE TITLE
Compile on save preference is not being respected

### ISSUE THREAD

**Issue by pspeter3** [TypeStrong/atom-typescript#202]
I had turned off compile on save but it continues to compile on save.

**Comment by basarat** [comment]
@pspeter3 its a `tsconfig.json` option :  https://github.com/TypeStrong/atom-typescript/blob/master/docs/CHANGELOG.md  : https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#compileonsave 

Is this how you used it?

**Comment by pspeter3** [comment]
I was using it as a plugin option from the settings. I'll switch to the tsconfig option.

**Comment by basarat** [comment]
cool :heart:
