### ISSUE TITLE
Import autocomplete uses single quotes

### ISSUE THREAD

**Issue by pspeter3** [TypeStrong/atom-typescript#203]

**Comment by basarat** [comment]
Yes. This is by design. Single quotes for JS double quotes for HTML is what I've learnt to live with based on the teams I've worked with.

**Comment by pspeter3** [comment]
Ok, is this configurable in anyway? Most typescript I've encountered uses double quotes and as result our team has used this convention.

**Comment by basarat** [comment]
@pspeter3 alright the TS compiler uses double quotes : https://github.com/Microsoft/TypeScript/blob/master/src/compiler/scanner.ts plus I trust your judgement. We don't care in our team, so lets just go with double quotes. I'll push.

**Comment by basarat** [comment]
released `v1.6.0` :heart:

**Comment by pspeter3** [comment]
Thanks!
