### ISSUE TITLE
More syntax options

### ISSUE THREAD

**Issue by Aedaeum** [TypeStrong/atom-typescript#204]
I just want to say, love the work that's been done on this project. I am currently creating my own custom syntax coloring for the various languages I use and noticed that the syntax in this package is very generalized.

``` ts
var myGlobal = true;

interface IMyInterface {
  someproperty: string;
}

class className {
  constructor(arg: string) {
    var localVar = 1;

    if (localVar > 0) {
      console.log(localVar);
      this.instanceVariable = true;
    }
  }

  public myMethod(arg: string) : void {
    // do some things
  }
}
```

**What should be colorable**
- Local variable names
- Class names
- Interface names
- Method/function names
  - method/function parameters (args)
- Global variables
  - System variables, like console (might be *.d.ts dependent)
- The "this" keyword, though that's an after-thought

As it is right now, there are only 3 color options that are needed to accurately define necessary parts of typescript code. One color for punctuation, one for identifiers, and one for keywords.

It would be really nice to have this extra level of customization, which the leading IDEs currently support like Visual Studio and WebStorm. I want to fully switch over to Atom for my development, so having these little extra bits of "fluff" would be much appreciated. In my opinion though, having these extra colors increases the readability of the code a lot (at least for me).

Thanks for your time.

**Comment by basarat** [comment]
Perhaps will be taken care of by : https://github.com/TypeStrong/atom-typescript/issues/71 or just *more custom code* in `typescriptGrammar.ts`

**Comment by Aedaeum** [comment]
I look forward to it :)
