### ISSUE TITLE
Lock up and Out of Memory in child process on Windows

### ISSUE THREAD

**Issue by sedwards2009** [TypeStrong/atom-typescript#207]
I'm experiencing lock ups of the editor for minutes at a time and complaints in the dev console that atom-typescript's child process has run out of memory. See screenshots below.

This occurs in a small project which does have a .d.ts file in the 1MB size range. The lock occurs after typing a line or two in another .d.ts file in the project. This problem appears to have been introduced sometime in the last couple of days.

atom-typescript 1.8.0, atom 0.187, Windows 7 64bit.

![atom-typescript_oom_console](https://cloud.githubusercontent.com/assets/6926644/6806557/b3247b78-d249-11e4-8853-377619f8c788.png)

![atom-typescript_oom_timeline](https://cloud.githubusercontent.com/assets/6926644/6806558/b5a00890-d249-11e4-805a-dae4d4d24229.png)

(I would send the profile data but Atom crashes if I try to save it.)

**Comment by sedwards2009** [comment]
Using atom-typescript 1.10.0 today I haven't hit this problem yet. Maybe it is already gone.

**Comment by basarat** [comment]
Were you running vs as well by any chance? I know it sounds crazy but I've seen vs take down atom (and then the os)

**Comment by sedwards2009** [comment]
Visual Studio? no.

**Comment by sedwards2009** [comment]
Tonight on a Linux machine I'm seeing very heavy CPU use coming from that child process. Something is still not right.

**Comment by sedwards2009** [comment]
I don't know if this helps, but the project I'm working on has some big .d.ts files which are also being updated externally, behind ATOM's back. (i.e. the .d.ts files are seen by atom-typescript but are often being (re)generated when I run my app.)

I'll try to see if there is correlation here. VS taking down ATOM also sounds crazy, but the TS compiler and service only really interact with the world through external files.

**Comment by basarat** [comment]
> VS taking down ATOM also sounds crazy,

agreed. There might have been no causality there.

**Comment by basarat** [comment]
I haven't found a reliable reproduction for this yet. The issue definitely does exist though.
