### ISSUE TITLE
Disable javascript generation on build

### ISSUE THREAD

**Issue by mclausen** [TypeStrong/atom-typescript#208]
After saving a ts file is saved a js file is generated from the compilation. This can be a pain when checking files into source control.

To give a bit of background, we are using gulp for building our project in the background, it places our final product i a different folder, than our work environment. Therefore we have to remove all the newly generated js files each time we check in.

**Comment by basarat** [comment]
> places our final product i a different folder, than our work environment. 

You can use compilerOptions.outDir : I encourage you to set it up as it's going to compile faster than gulp.

But if you must. There is an option compileOnSave that you can set to false. Please see tsconfig.md

**Comment by basarat** [comment]
Link : https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md

**Comment by mclausen** [comment]
Thank you for the reply! Have a nice day.

**Comment by val-samonte** [comment]
big help. thanks!
