### ISSUE TITLE
Most functionality not available

### ISSUE THREAD

**Issue by jtheisen** [TypeStrong/atom-typescript#209]
Me again - I just closed #201 since I now got the "Enjoy typscript" message and I do indeed get the TypeScript language, syntax highlighting and tab completion.

However, there's still something wrong.

* I don't get any emit messages on saving a *.ts file.
* A *.js file is created at some point, but it's always empty.
* Howering over symbols don't give me any information, although tab completion does include my own symbols.
* Ctrl-B does never find a definition (see screenshot below).
* Ctrl-Shift-B says "Building", but nothing more. I don't think it ever built anything.

![image](https://cloud.githubusercontent.com/assets/1516294/6856863/05f246a4-d403-11e4-9136-c00c4e507c72.png)

My tsconfig.json has been automatically created as:

```
{
    "version": "1.4.1",
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false
    },
    "filesGlob": [
        "./**/*.ts",
        "!./node_modules/**/*.ts"
    ],
    "files": [
        "./myfile.ts"
    ]
}
```

What could those symptoms mean?

**Comment by basarat** [comment]
Shouldn't be needed ..... But  ..... Can you reopen that atom window ?

**Comment by jtheisen** [comment]
Ok, I didn't try the obligatory restart. :-) Thanks, it's working now!

**Comment by basarat** [comment]
@jtheisen 

TIP: you can also do a `ctrl+alt+r` to reload an atom window without restarting it :heart: 
TIP: If things go out of shape. `ctrl+s` should bring them back in shape

**Comment by jtheisen** [comment]
Thanks for the tips, and thank you for your quick assistance.
