### ISSUE TITLE
reference error

### ISSUE THREAD

**Issue by thanzen** [TypeStrong/atom-typescript#213]
I have react-global.d.ts and react-addons-global.d.ts in the same folder.
But  react-addons-global.d repported error, see  pic below:
![error](https://cloud.githubusercontent.com/assets/1901357/6913007/97383a14-d72e-11e4-8d69-f3edb202e556.png)

**Comment by basarat** [comment]
Note that it works fine if you have a valid `tsconfig.json` referencing both files: 

![image](https://cloud.githubusercontent.com/assets/874898/6913408/913facf8-d7cb-11e4-9182-6ede112f52c6.png)

I am a bit hesitant to add a file resolution logic i.e. `tsconfig.json:files` expansion other than a relative path resolution which is all that we have right now. 

But for this simple case I will assume that I should look at the file *at the same level*. If not found, give up (i.e. don't nav up the dir tree).

**Comment by basarat** [comment]
I was wrong. The resolution logic is correct. We didn't do file expansion for *default in-memory projects* we create for `.d.ts` files when they don't have a parent `tsconfig.json`. I'll have a fix shortly.

**Comment by thanzen** [comment]
That is wonderful! Thanks so much!
