### ISSUE TITLE
Autocomplete text is difficult to read on light themes

### ISSUE THREAD

**Issue by ChaosinaCan** [TypeStrong/atom-typescript#215]
Atom TypeScript appears to be applying style="color: white" to the function prototypes on the right side of the completion list. This makes them difficult or impossible to read when using light themes such as Atom Light with Solarized Light syntax.

![TypeScript autocomplete in Solarized Light theme](http://i.imgur.com/Bwwcse6.png)

**Comment by basarat** [comment]
I've known this for a while. You're the first one to hit this. No combinations of colours is going to be good for *both light and dark*. 

Currently code is doing the colouring : https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/atom/atomUtils.ts#L106-L117

I'll try to move these down to CSS and then you / others can customize this for themselves.

**Comment by basarat** [comment]
After my next push :

![image](https://cloud.githubusercontent.com/assets/874898/6957041/840eba38-d942-11e4-91e5-0fd9c9f36b7a.png)

For the white theme people : 
![image](https://cloud.githubusercontent.com/assets/874898/6957044/8dfb69d8-d942-11e4-919d-cc0ad9cf7aaa.png)

But if we want random colors based on type, its only really plausible if we have a determinate background.
