### ISSUE TITLE
Project Symbols View and Symbols View flashes once before showing

### ISSUE THREAD

**Issue by filimon-danopoulos** [TypeStrong/atom-typescript#219]
## The issue

When toggling either or of the two symbol views, a quick "empty" symbol view flashes by (applying the overlay and removing it) before the atom-typescript plugins kicks in, shows the view (and overlay) and populates the view with the symbols. 

In any other non-ts file the flash of an "empty" result does not occur. 
### Versions

I am running the following versions of relevant packages:

Atom 0.188.0
atom-typescript 1.13.0

**Comment by basarat** [comment]
The symbols view doesn't provide an API for such stuff yet : https://github.com/atom/symbols-view/issues/70

So we've done some hacky stuff making sure that we don't break other languages. Theres a tradeoff of letting the symbols view do its stuff by default and only doing our stuff afterwards..

refs : https://github.com/TypeStrong/atom-typescript/issues/76 and https://github.com/TypeStrong/atom-typescript/issues/137

will keep this open for future tracking :heart:

**Comment by filimon-danopoulos** [comment]
I suspected as much. Keep up the good work!
