### ISSUE TITLE
A way to completly hide and unhide the statusbar

### ISSUE THREAD

**Issue by mgutz** [TypeStrong/atom-typescript#220]
The typescript status bar shows on every file.

**Comment by basarat** [comment]
Todo: add a feature to completely collapse it into a button in the status bar

**Comment by Ciantic** [comment]
I think the TypeScript status bar should appear only when editor grammar is TypeScript.

Having it collapsible is not a good option because it would require user to collapse and expand it all the time when switching editors or projects.

**Comment by basarat** [comment]
> Although I see it's conditioned on having tsconfig because right now it's not appearing in other projects.

Close. Its actually conditioned on someone opening a `.ts` file.

**Comment by basarat** [comment]
Closing in favor of #261
