### ISSUE TITLE
Pluggable syntax highlight engine for templating languages between backticks ``

### ISSUE THREAD

**Issue by Ciantic** [TypeStrong/atom-typescript#221]
Since backticks `` are ment for template formats, it would be nice to have a pluggable way to define own syntax highlighting between them.

For example [ts-jsx-loader](http://github.com/jbrantly/ts-jsx-loader) implements JSX in TypeScript followingly:

```
// This is valid TypeScript:
React.jsx(`
    <MyApplication>
        <MyNavbar />
        <span>some html</span>
        {
            // This is TypeScript part again, except...
            this.state.results.map(function (a) {
                // ... following line, which is JSX within the TypeScript:
                return <div>{a}test</div>
            })
        }
    </MyApplication>
`);
```

Now I don't expect atom-typescript to implement the syntax highlighting for this specific language format, but if one could plugin a new highlighting engine between templating backticks, with some regexp for example `jsx(`Make syntax highlight here a pluggable, perhaps based on a word before backticks`)` it could be a start.

**Comment by sclausen** [comment]
:+1:  a must have for angular2 inline templates :wink:

**Comment by chapati23** [comment]
agree, this would make life so much better

**Comment by mattdanna** [comment]
:+1:

**Comment by saminiemi** [comment]
:+1:

**Comment by sclausen** [comment]
Yeah can't wait for #221

**Comment by dchacke** [comment]
Me neither. #798 is merged, but version 7.15.0 doesn't seem to include it yet...

**Comment by basarat** [comment]
@dchacke / @sclausen for angular its released with : https://github.com/TypeStrong/atom-typescript/releases/tag/v7.16.0 :rose:

**Comment by dchacke** [comment]
Cool, this is great, thank you!

**Comment by dchacke** [comment]
@basarat This is a great start. Posted a potential idea for improvement in #800.

**Comment by dchacke** [comment]
Also, just heads up but it seems like normal strings aren't highlighted anymore at all:

<img width="465" alt="string not highlighted" src="https://cloud.githubusercontent.com/assets/2866749/12077692/f8dbb126-b1a6-11e5-810a-0600a34e945a.png">
