### ISSUE TITLE
Enhance autocomplete for module paths when output is AMD

### ISSUE THREAD

**Issue by danieldisu** [TypeStrong/atom-typescript#227]
Hi,

I'm working in a project that turns all the typescript modules into AMD modules, I've found that atom-ts is more prepared to handle commonjs output or single file compilation but no so much AMD modules.

The biggest problem I've found so far is the module path auto-complete, AMD modules are not relative to the current file but relative to a Base Path.

It could be nice to have a setting that could enable auto-complete relative to a path chosen by the user  instead of the current file.

I've made a prototype in my computer ( with hard-coded paths and no settings ) and it works great, In case someone also has this problem I could clean it up and make a PR.

**Comment by basarat** [comment]
> It could be nice to have a setting that could enable auto-complete relative to a path chosen by the user instead of the current file

The typescript compiler will give you compiler errors in this case. The path *must* be relative to the current file. Relative paths work fine in AMD as well.

**Comment by basarat** [comment]
Sorry mate. Closing this to keep the issue count manageable. Let us know if you think I am wrong :heart:
