### ISSUE TITLE
Deprecated calls on Install atom-typescript (Windows 7 64bits)

### ISSUE THREAD

**Issue by StanleyAM** [TypeStrong/atom-typescript#229]
Hi, I got "deprecated calls" after installing atom-typescript (ver 1.19.0)

![deprecated-atom-typescript](https://cloud.githubusercontent.com/assets/9450739/6960834/a94fb980-d958-11e4-88cd-0ba202115002.png)

**Comment by basarat** [comment]
@StanleyAM thanks, I've removed `"activationEvents": [],` However the error you are seeing is not (was not) in this package. Its in atom-core and came with `189`.
