### ISSUE TITLE
Get autocomplete for function signature

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#23]
Add this simply to the returned result of autocomplete plus

Potentially as a snippet (https://github.com/atom-community/autocomplete-plus/wiki/Provider-API): If your suggestion defines an anonymous snippet, you can provide the snippet here and it will be inserted via the snippets package

**Comment by basarat** [comment]
Add this simply to the returned result of autocomplete plus

**Comment by basarat** [comment]
FWIW a hover tooltip is quite useful even for now. 
![image](https://cloud.githubusercontent.com/assets/874898/5985734/86324cea-a93a-11e4-8f66-35566364722e.png)

**Comment by basarat** [comment]
I am thinking of using this : https://github.com/atom/atom-space-pen-views#selectlistview

**Comment by claudio-silva** [comment]
Could you please elaborate on how is your proposed solution different from a simple tooltip, like it's depicted above?
Also, that tooltip is not yet implemented, is it? I can see a tooltip for identifiers, but I can't get one on function signatures. So when you say "a hover tooltip is quite useful even for now", do you mean "would be useful", or do you mean "it already exists" but I don't know how to get it?

**Comment by basarat** [comment]
Also wait for https://github.com/atom-community/autocomplete-plus/pull/245

> that tooltip is not yet implemented, is it?

It is if you hover over the `bar` identifier you will get that tooltip. Also for functions : https://github.com/TypeStrong/atom-typescript#type-information-on-hover 

> "a hover tooltip is quite useful even for now"

Yes, right now. But issue is with overloads its not so pretty. Definitely need work in this.

**Comment by lazutkin** [comment]
:+1:

**Comment by jonyeezs** [comment]
is this issue still active?

I have the same problem atm.

using atom-typescript 11.0.3

**Comment by pietrasiak** [comment]
Any update? That's the only reason keeping me from going back from vs-code.

**Comment by binarious** [comment]
@basarat Any news?
