### ISSUE TITLE
External modules Dependency Diagram

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#234]
This is one of the things I promised when I suggest that you *must* use external modules. 

This is a problem for which people have asked for a solution before. Specifically doing cyclic checks is also useful.  

Samples : 
* https://github.com/brzpegasus/mimosa-dependency-graph 
* https://github.com/pahen/madge (cool idea about colors : red for circular, blue for has dependency and green for has no dependencies)
* https://github.com/auchenberg/dependo something built with madge. Demo : http://auchenberg.github.io/dependo/example/ which in turn is inspired by : http://bl.ocks.org/mbostock/1153292  Source : https://github.com/auchenberg/dependo/blob/master/example/index.html

**Comment by basarat** [comment]
After my next push: 
![image](https://cloud.githubusercontent.com/assets/874898/6996404/fa9d4fa0-dbc9-11e4-84b9-6a861da02a1b.png)


Red arrow denote stuff this file depends upon. Implies that this file cannot be extracted without also moving these files.
Green arrows denote stuff that depends on this file. Green as this means the code in this file is moveable to another project and these links will play no part in that.

**Comment by nycdotnet** [comment]
Wow!

**Comment by basarat** [comment]
After my next push: 

Size is based on indegree and out degree: 

![image](https://cloud.githubusercontent.com/assets/874898/6999273/1fd81340-dc47-11e4-89a9-0af4ab8c1279.png)

Distance is determined by how much of the file path is common between two nodes: 

![image](https://cloud.githubusercontent.com/assets/874898/6999304/84c11f62-dc48-11e4-91db-0dbf2a3edc2b.png)

**Comment by basarat** [comment]
Nodes that do not depend on anything are colored green : These are probably utilities. 
Nodes that only depend on other stuff are colored blue: These are probably application entry points: 

![image](https://cloud.githubusercontent.com/assets/874898/6999367/5727727e-dc4b-11e4-99b3-6323c5f61b66.png)

**Comment by basarat** [comment]
Circular dependencies are highlighted in red: 

![image](https://cloud.githubusercontent.com/assets/874898/6999797/8ef606e6-dc57-11e4-9737-0557eb290b3d.png)
