### ISSUE TITLE
Odd completion popup behavior

### ISSUE THREAD

**Issue by Aedaeum** [TypeStrong/atom-typescript#239]
I'm getting a lot of lag with code completion now. Before all the updates, it was very responsive, but now it's almost unusable, since I type faster then the completion can pop up. The completion box also spans the entire width of the screen for no apparent reason.

![ss 2015-04-07 at 06 17 14](https://cloud.githubusercontent.com/assets/2054218/7037133/61fd0fb2-dd52-11e4-8d68-49fc4c13154d.png)

**Comment by basarat** [comment]
Which version of atomTS  are you on. This should be fixed in latest.

**Comment by Aedaeum** [comment]
Version 2.14.0

**Comment by basarat** [comment]
The limiting results logic was a bit broken : https://github.com/atom-community/autocomplete-plus/pull/272 

Will have a fix soon :heart:

**Comment by basarat** [comment]
Published `v2.14.1`
Please let me know how it goes for you :rose: I've limited the number of items we return. 

I'm investigating having our cake and eating it too : i.e. return large lists without reduced performance, so keeping this open

**Comment by Aedaeum** [comment]
You are amazing @basarat, thanks, everything is working as it should now :)

**Comment by basarat** [comment]
Thank you. Extremely sorry for the inconvenience 🌷

**Comment by Aedaeum** [comment]
No worries, I understand that all things Atom are in a constant state of flux so bugs are to be expected :)
