### ISSUE TITLE
Rename file module: file move

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#240]
- [ ] rename file module (this is a big pain and the reason why we added `///ts:import` transform in the first place)

**Comment by ifeltsweet** [comment]
Completely agree. Is this in the plans?

**Comment by basarat** [comment]
> Completely agree. Is this in the plans?

We already have the refactoring code working (https://github.com/TypeStrong/atom-typescript/blob/ac11fe7323051f94bfac95a14805ead897a4efda/lib/main/atom/commands/commands.ts#L181-L213) The only issue is getting notified from atom tree view -> https://github.com/atom/tree-view/issues/433

**Comment by trusktr** [comment]
This would be sweet. Can we keep this open?

**Comment by lierdakil** [comment]
Please open a new issue lest I miss this in the backlog.
