### ISSUE TITLE
Support `es6.d.ts` 

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#245]
*Very* high priority

Run on https://github.com/cmichaelgraham/spike-aurelia-ts-port

**Comment by cmichaelgraham** [comment]
so can i delete the es6.d.ts and test it out?

**Comment by basarat** [comment]
Naa. You still want to compile to es5.

**Comment by Aedaeum** [comment]
Is there a reason you've bound this to only es6 compilation, since the es5 compiler can currently compile most of the es6 features without issue?

It would be nice to optionally have syntax completion for es6 natively without having to rely on a separate es6.d.ts file for es5 projects.

**Comment by basarat** [comment]
> Is there a reason you've bound this to only es6 compilatio

That's how TypeScript is designed. Not my choice :) 


> It would be nice to optionally have syntax completion for es6 natively without having to rely on a separate es6.d.ts file for es5 projects

The only way to do it is to completely switch off `lib.d.ts` using `noLib : true` in `tsconfig.json` and copy / include `lib.es6.d.ts` into your project. 

Alternatively copy over the sections of `es6.d.ts` that you have shimmed (or available natively)

**Comment by Aedaeum** [comment]
Well that's disappointing. Thanks for the `nolib` info though, I was wondering if there would be redundancy with having both libs referenced.

**Comment by getsetbro** [comment]
With this configuration - "noLib: true & include lib.es6.d.ts." - does it transpile to es5 and give you intellisense?

**Comment by Aedaeum** [comment]
Yes.

**Comment by getsetbro** [comment]
Is this how to do it?
https://gist.github.com/getsetbro/60c20793c939e6fac582f842fdaa510d

**Comment by Aedaeum** [comment]
Yes, as far as I remember.
