### ISSUE TITLE
Accept multiple tsconfig.json (ex: client/server)

### ISSUE THREAD

**Issue by narf** [TypeStrong/atom-typescript#248]
When you have both client and server folders with files in typescript in your project, you have to make different rules for compilation.
It would be awesome to be able to specify specific rules for directories.

How about going up in Hierarchy and merging all tsconfig.json with priority to deepest config before compiling a file?

**Comment by basarat** [comment]
> How about going up in Hierarchy and merging all tsconfig.json with priority to deepest config before compiling a file?

We have been giving quite a lot of thought to this. `merging all tsconfig.json with priority to deepest config before compiling a file?` alone will not work as e.g. the deepest config might be `target:amd` and the outer one will be `target:commonjs` and you want the result of *both* compilations. 

The plan :
* emit and build need to to be done for *both* tsconfig.json. 
* code intelligence only done for *inner* tsconfig (sort of like you are suggesting). That means you cannot mistakenly use *outer* tsconfig stuff in an inner file and you still get *inner* file stuff when editing an outer file. 

This is a part of this milestone : https://github.com/TypeStrong/atom-typescript/milestones/3%20Project

**Comment by basarat** [comment]
I am hoping for stuff like : https://github.com/Microsoft/TypeScript/pull/2605 to happen *before* I start work on this. 

Also the angular team is going to care about this so the solution might just come from microsoft. I'm keeping my eyes and ears open.

**Comment by basarat** [comment]
Will be delt with : https://github.com/TypeStrong/atom-typescript/issues/492 :rose:
