### ISSUE TITLE
Omit "file" key generation in tsconfig.json

### ISSUE THREAD

**Issue by cybrown** [TypeStrong/atom-typescript#250]
Is it necessary to save each new files in the tsconfig.json ? Since the build configuration is in this file, I commit it in my projects, and every time there are modifications in the files, such as creations, deletions or moved files, the tsconfig file must be recomitted.

I think it adds polution to the comit history, and sometimes it might even be forgotten, leaving a functionning project but an inconsistent tsconfig.json file.

So is it possible to disable the tsconfig.json files key generation and use only the filesGlob ?

Nevertheless, thank you for this wonderfull atom plugin :)

**Comment by basarat** [comment]
> So is it possible to disable the tsconfig.json files key generation and use only the filesGlob

`filesGlob` is an unofficial extension. The offical standard is only `files` which we try to keep consistent so that people can open their projects in VisualStudio / Sublime Text / Whatever. 

Thanks for the kind words :rose:

**Comment by cybrown** [comment]
Ok, thank you very much for the explanation, I knew there was some kind of a good reason for this behaviour !
