### ISSUE TITLE
Hover information over `export default function` does not work

### ISSUE THREAD

**Issue by Deathspike** [TypeStrong/atom-typescript#251]
If you have a file with the following contents:

```
export default function(a: string, b: number) {
  return Promise.resolve(a + b);
}
```

Then there is no way to see function signature through hovering. Basically, because it has no name? It would be nice to get the hover information over the `export` or `default` keyword :-)

**Comment by basarat** [comment]
Raised with the TypeScript team : https://github.com/Microsoft/TypeScript/issues/2736 :heart:
