### ISSUE TITLE
Syntax highlighting for variable using a keyword

### ISSUE THREAD

**Issue by Deathspike** [TypeStrong/atom-typescript#252]
When I define a variable that uses a keyword as name, like this:

```
interface ITest {
  a: number;
  b: number;
  number: number;       // Weird highlighting.
  string: string;       // Weird highlighting.
}

var a = <ITest>{
  a: 100,
  b: 100,
  number: 123,          // Weird highlighting.
  string: 'Hello world' // Weird highlighting.
}
```

The variable name will be highlighted as if it is a keyword. It would be nice if it would remain the normal color.

**Comment by basarat** [comment]
Duplicate of : https://github.com/TypeStrong/atom-typescript/issues/71
