### ISSUE TITLE
Hide .js and .map files in project file tree

### ISSUE THREAD

**Issue by kpgarrod** [TypeStrong/atom-typescript#253]
I am just trying out Atom with your typescript plugin and was wondering if there is a way to hide the .js and .map files associated with a .ts file in the file tree, as WebStorm and (I believe) VisualStudio do?

**Comment by basarat** [comment]
> if there is a way to hide the .js and .map files associated with a .ts file in the file tree

If you have them excluded from the repo (.gitignore) there are options in Atom to hide it.

I do agree that there needs to be better control for this.

**Comment by vilic** [comment]
+1 to this.

**Comment by filimon-danopoulos** [comment]
I feel that this is outside the scope of this plugin. The plugin is already a bit invasive, since it if it opens it doesn't close until a restart. 

If it goes on to automatically hide JS files in the editor it would render it more or less useless for any environment where you edit JS and TS files.

As it stands currently this feature would kill this plugin.

**Comment by basarat** [comment]
> As it stands currently this feature would kill this plugin.

Got it. Will only be done if `tree-view` provides native support of it :+1:

**Comment by kpgarrod** [comment]
Just to be clear, the way that Webstorm ( and I think Visual Studio) does
it is to give the appearance of a folder (with the filename.ts appearing as
the folder name) in the tree-view when there is a .ts file, .map.js and .js
file of the same name in a parent folder.

.js and .map.js files are hidden by default, but if you click on them, the
underlying .js and .map.js files are revealed and you can then open them.

@basarat: I will try the .gitignore option, it may work for me, thanks for
the tip.

**Comment by basvdijk** [comment]
:+1: for this feature. Collapsing like VS or Webstorm whould be really nice.

**Comment by laurelnaiad** [comment]
I use leny/atom-tree-ignore to do this (it doesn't do the fancy "code-behind") styling of the tree as Visual Studio, but it can be toggled on/off.

**Comment by JoaoGuedes** [comment]
@laurelnaiad good tip :+1: thanks

**Comment by jsheely** [comment]
Or do it like Visual Studio Code, where it can hide files by extension when a file with the same name and another extension exists

Example
- /controller/main.ts
- /controller/main.js (hidden)
- /controller/secondary.js (not hidden)

Visual Studio Code **settings.json** configuration file
```
{
	"files.exclude": {
		"**/.git": true,
		"**/.DS_Store": true,
		"**/*.js": {
			"when": "$(basename).ts"
		}
	}
}
```

**Comment by jaspersorrio** [comment]
Hey guys some people have been developing a solution to this at https://github.com/atom/tree-view/issues/572. This issue should be closed.

**Comment by avatsaev** [comment]
WebStorm handles it pretty well, Atom needs to implemented this feature, working with Angular2 projects is annoying with all that junk.

**Comment by caroso1222** [comment]
@laurelnaiad worked for me as well, pretty much what I needed
