### ISSUE TITLE
Add "none" as a valid module options.

### ISSUE THREAD

**Issue by vilic** [TypeStrong/atom-typescript#254]
https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/tsconfig/tsconfig.ts#L52

**Comment by basarat** [comment]
Its not a valid value. See : http://json.schemastore.org/tsconfig

**Comment by basarat** [comment]
'none' is implicit if you omit it. Note that we don't support omitting it though as we don't think `--out` as it is implemented is a good idea : https://github.com/TypeStrong/atom-typescript/blob/master/docs/out.md
