### ISSUE TITLE
Typescript angularJs Import declaration conflict

### ISSUE THREAD

**Issue by kpgarrod** [TypeStrong/atom-typescript#258]
I'm just getting started with typeScript and have added tsd files for a number of components, including angular.d.ts. 

I like Atom and the plugin a lot, but I'm getting one error.

In angular.d.ts: "Import declaration conflicts with local declaration of 'ng'" on line 17.

It's obviously causing other errors resulting in intellisense issues.

I'm using Atom.io v0.190.0, and atom-typescript 2.15.0 in case that makes a difference.

I don't see the same error in WebStorm 10.2.

Any suggestions please?

**Comment by filimon-danopoulos** [comment]
It's a bit hard to tell from the supplied information. But I use Atom, TypeScript with this plugin and Angular without any problem. 

A quick search gave this: https://github.com/borisyankov/DefinitelyTyped/issues/3878

**Comment by basarat** [comment]
@kpgarrod make sure you don't have "declare module ng " anywhere in *your* code

Ps: webstorm has its own language service implementation. It's not a judge of *official TS*. Still good to compare ❤️
