### ISSUE TITLE
Package option to set import/require completion quote character (single vs. double)

### ISSUE THREAD

**Issue by cybrown** [TypeStrong/atom-typescript#259]
Most of the time, the standard for quotes is simple quotes, is it possible to add an option so the autocompletion can write simple quotes in the file, or maybe set it as a default ?

**Comment by basarat** [comment]
The exact opposite was requested by @pspeter3 : https://github.com/TypeStrong/atom-typescript/issues/203 :smile: 


> is it possible to add an option

I'll change the title of this request to be just that. I'll mark it as up for grabs as I am not motivated by this, I feel either quoting is fine :) PS: this will need some form of support in `snippet`s too.

**Comment by cybrown** [comment]
Ok thank you for your answer :) I understand that it can't be the default behaviour, and that it may be a plugin option.

I think I should be able to do that by myself, but since I do not know how to use the atom API, is the config object a good place to start investigating ? (https://atom.io/docs/api/v0.191.0/Config)

**Comment by basarat** [comment]
> but since I do not know how to use the atom API, is the config object a good place to start investigating

Yes. But we have it neatly abstracted : https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/atom/atomConfig.ts 

Add a new option `preferredQuoteCharacter` with default to `"` and then push it through here : https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/atom/autoCompleteProvider.ts#L217-L235

Coming to think of it its not that hard to do :) I just didn't want to do it as I want all atom projects to look the same. Don't want to be working on one project with one atomts settings and on another with another atomts settings.

But if its what you want (and I am sure there are others) its good to have it :heart: Looking forward to some PR :+1:

**Comment by basarat** [comment]
`atomConfig` is something you can just require anywhere in the project e.g. in `autoCompleteProvider.ts` ;)

**Comment by park9140** [comment]
@basarat, how do you feel about defaulting this based on tslint config?  I assume we should have both tsconfig, and, editor configuration overrides for this.  I was doing some refactoring today and the default being double quote is opposite of our tslint config, I probably spent 20 minutes going back and fixing the incorrect quotes.

**Comment by basarat** [comment]
> how do you feel about defaulting this based on tslint config

That's a great suggestion. I feel very averse to having a package option for it. I've been thinking of putting this in an `ide` section in `tsconfig.json` but using `tslint.json` is *much* better.

**Comment by cybrown** [comment]
Having tslint integration directly in atom-typescript might be a problem (but a very nice idea), since not everyone uses tslint. What would be nice is somekind of api between the atom-typescript plugin and the tslint plugin (or any other plugins), maybe with some kind of event bus.

This is just a quick thought, I am not familiar with the atom api.

**Comment by park9140** [comment]
Maybe I'll look at rather than just directly reading the tskint config I can just implement an the api to get the settings directly from the tslint plugin.

**Comment by vilic** [comment]
Added an option, will soon create a pull request.

**Comment by basarat** [comment]
closed in #274
