### ISSUE TITLE
tooltips.less not found

### ISSUE THREAD

**Issue by kpgarrod** [TypeStrong/atom-typescript#260]
I'm getting this error (Atom 0.191.0 atom-typescript 2.15.0):

> Failed to load the atom-typescript package
'tooltips.less' wasn't found in /Users/admin/.atom/packages/atom-typescript/styles/atom-typescript.less:7:0
Hide Stack Trace
LessError: 'tooltips.less' wasn't found
  at /Users/admin/.atom/packages/atom-typescript/styles/atom-typescript.less:7:0
The error was thrown from the atom-typescript package. This issue has already been reported.

It says the bug has already been reported, but the issue it points to is something different afaics.

I couldn't find a tooltips.less in the repo.

**Comment by basarat** [comment]
As always. I looked to the source : https://github.com/chaika2013/ide-haskell/issues/48 

Expect a fix soon :heart:

**Comment by kpgarrod** [comment]
@basarat: thanks. Sorry I don't know my way around this project at all, so
I didn't know what was going on. I'll look forward to the fix :)

**Comment by basarat** [comment]
@kpgarrod do you have `unity` theme or some other custom theme applied? Or are you on a default atom installation?

**Comment by basarat** [comment]
closed with : https://github.com/TypeStrong/atom-typescript/commit/52ed5386e7af142661e062bf3d3e41e2c1301d5e `v2.15.1`

**Comment by kpgarrod** [comment]
@Basarat: Yes, I have Unity theme installed

**Comment by kpgarrod** [comment]
@basarat: I updated my plugin and the bug seems to be cleared. Thanks for
the phenomenal response!
