### ISSUE TITLE
Hide status bar when non-ts file is the current file.

### ISSUE THREAD

**Issue by filimon-danopoulos** [TypeStrong/atom-typescript#261]
# The issue
I am opening this issue as I believe it is different than #220 in that it adds some sort of contextual awareness to the status bar. In contrast to #220 the user should not have direct control over this feature other than via a setting.

Screen real estate is valuable on a laptop, the status bar is always visible if I have opened a TS file now. If I open a TypeScript project and then want to edit some non-project file I will have the TypeScript status bar even when editing in that file. 

## Solution

In addition to #220 we should hide the atom-typescript status bar whenever the user switches to a non-ts file. 

When a valid project-wide TypeScript action (for example build project) is triggered from any non-ts file the status bar should appear and remain open until the next time the user switches to a non-ts file.

**Comment by basarat** [comment]
> When a valid project-wide TypeScript action (for example build project) is triggered from any non-ts file

We don't allow any project-wide actions if the active file is not a `ts` file. This is because the Atom workspace might contain multiple TS projects.

**Comment by basarat** [comment]
So it would mean we effectively have "hide the atom-typescript status bar whenever the user switches to a non-ts file." 

I think its reasonable.

**Comment by Ciantic** [comment]
:+1:  Yes, this is what I suggested in the now closed thread. When editor grammar is TypeScript show the bar.

**Comment by basarat** [comment]
> I suspect it should be tight to that not the opened file extension.

We went with extension as we do stuff like create a `tsconfig.json` file + *require* the file to be on the file system (so we can know which project this file belongs to). Lets stick to that for now. Also TypeScript is picky about the extension of the file (by default must be `.ts`)

**Comment by Ciantic** [comment]
Oh right.

Would it suffice to hook here: https://atom.io/docs/api/v0.192.0/TextEditor#instance-setGrammar if there is some onSetGrammar, which I can't find?

**Comment by Ciantic** [comment]
Sorry for spamming, can't we hook here: https://atom.io/docs/api/v0.192.0/TextEditor#instance-observeGrammar it is the event. I think it changes when you switch file.

**Comment by basarat** [comment]
> Sorry for spamming, can't we hook here

Add an else here : https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/atomts.ts#L81-L89 ;)

**Comment by Ciantic** [comment]
Interesting, this onDidChangeActivePaneItem is not run first time the editor loads when I hit ctrl+alt+R. It is run when I switch tabs.

This means I this hook has to be in init too.

**Comment by basarat** [comment]
> This means I this hook has to be in init too.

No. Because we don't show the status bar *till* the user opens some ts file. So the if they never opened ... we never hide. If they opened ... and move away .. we hide ... till they come back

**Comment by basarat** [comment]
@Ciantic recommend https://gitter.im/TypeStrong/atom-typescript
