### ISSUE TITLE
Convert `==` to `===` and `!=` to `!==`

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#262]

**Comment by basarat** [comment]
![equalstoequals](https://cloud.githubusercontent.com/assets/874898/7196974/5122f67e-e51e-11e4-96c8-5df7b8a7eb38.gif)

This might be the most useless feature I've ever added. But I plan to combine these into a larger feature.

**Comment by cybrown** [comment]
Nice but what about == and != used to compare with null or undefined ?
This might be a problem if there is a feature for an entire file/project :D

**Comment by basarat** [comment]
> an entire file/project :D

Thanks I was going to add this part to that feature but will leave it out for now.
