### ISSUE TITLE
String to Template String

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#264]

**Comment by basarat** [comment]
![quotetotemplate](https://cloud.githubusercontent.com/assets/874898/7198039/6adc765a-e52b-11e4-962e-69ab89484280.gif)

**Comment by vilic** [comment]
Is it possible to automatically convert basic string joining expression like `'...' + abc + '...' ` to template string? If there's not nested brackets.

**Comment by basarat** [comment]
> Is it possible to automatically convert basic string joining expression like '...' + abc + '...' to template string

Doable. Created an issue for tracking : https://github.com/TypeStrong/atom-typescript/issues/298 :rose:
