### ISSUE TITLE
Remove non-filtered symbol tooltip

### ISSUE THREAD

**Issue by tinganho** [TypeStrong/atom-typescript#265]
Is this default symbol tooltip useful(the non-filtered one)? What are the use-cases?

![screen shot 2015-04-18 at 1 41 23 am](https://cloud.githubusercontent.com/assets/1324476/7207438/0740b2b4-e56c-11e4-9ea6-eaa615211bfe.png)

It seems like it just pops up after end of expression or declaration? And it doesn't happen so often that I want to write two expression on the same line. So I don't want auto-complate suggestions.

**Comment by basarat** [comment]
> Is this default symbol tooltip useful (the non-filtered one)

Not for me. But I can imagine someone liking it. Admittedly it is over aggressive and that issue is tracked here : https://github.com/TypeStrong/atom-typescript/issues/141
