### ISSUE TITLE
Add new line to tsconfig.json when automatically updating.

### ISSUE THREAD

**Issue by vilic** [TypeStrong/atom-typescript#267]
As atom will automatically append a new line to every file when saving, it would be nice to behave the same so we may avoid tsconfig.json being marked as modified by git when we manually save tsconfig.json.

**Comment by basarat** [comment]
Done :rose: as other editors might do it too (@vilic did you use sublime text on that file?). Pushed in `v2.15.7`

Might make people unhappy the first time ... but I think its a good idea to be consistent with *whats recommended*.

**Comment by vilic** [comment]
That's fast~ Thanks! :+1:
