### ISSUE TITLE
Workspace.getActiveEditor is deprecated.

### ISSUE THREAD

**Issue by englercj** [TypeStrong/atom-typescript#271]
Posting the deprecation that popped up after I updated to v2.15.10.

Call ::getActiveTextEditor instead
```
Workspace.getActiveEditor (C:\Users\Chad\AppData\Local\atom\app-0.192.0\resources\app\src\workspace.js:999:12)
<unknown> (C:\Users\Chad\.atom\packages\atom-typescript\dist\main\atomts.js:27:24)
```

**Comment by basarat** [comment]
Thanks! Fixed locally. I plan to push by end of day (big refactoring going around generating `.d.ts` files) :rose:

**Comment by englercj** [comment]
Np, just wanted to make sure you were aware. Love the plugin, thanks for all the hard work!
