### ISSUE TITLE
Renaming with "compile on save" affects focus

### ISSUE THREAD

**Issue by vrinek** [TypeStrong/atom-typescript#276]
GIVEN the editor has unsaved changes,
AND the "compile on save" option is on,
AND the rename dialog appears
THEN the focus is moved to the dialog briefly until it moves back to the editor (which is in the background).

![Example](http://i.imgur.com/iP0cEYg.gif)

Atom version: 0.190
atom-typescript version: 2.15.1

**Comment by basarat** [comment]
> "compile on save" affects focus

Yes. In fact *any notification* has a bad effect on focus. This is more like an issue in atom *core*. Notification will also effect focus on e.g. `ctrl+shift+p`. 

Workaround. Just press f2 again ;) 
Solution : report on https://github.com/atom/atom

**Comment by vrinek** [comment]
Thanks for the reply, I'll check atom's issues

**Comment by vrinek** [comment]
Just for reference, I have reported the issue to atom/atom: https://github.com/atom/atom/issues/6439

**Comment by basarat** [comment]
Investigating it further : https://github.com/atom/atom/issues/6439#issuecomment-101090343 I'll look into finding an alternate means of notifying the user about the current `.ts` -> `.js` relationship (in sync or not in sync or not being synced (e.g. compile on save is disabled or user is using `--out`))

**Comment by basarat** [comment]
Closed by a fix in atom https://github.com/atom/notifications/pull/59 :rose:
