### ISSUE TITLE
Syntax highlighting for punctuations, null and undefined.

### ISSUE THREAD

**Issue by tinganho** [TypeStrong/atom-typescript#278]
There is currently no syntax high-lightning for the following punctuations:

```
!=
==
!==
===
!
?
:
```

and more... But the above are some of those I expect to have syntax high-lightning.

Also null and undefined are missing syntax high-lightning:
```
null 
undefined
```

**Comment by basarat** [comment]
I made it high priority to double check. But after checking there is *some* syntax highlighting for these compare ts and js: 

![image](https://cloud.githubusercontent.com/assets/874898/7224888/62c15556-e77b-11e4-827a-179d56bd60b0.png)

Marking this as a duplicate of https://github.com/TypeStrong/atom-typescript/issues/71 which is tracking *advanced* highlighting desires :rose:
