### ISSUE TITLE
Hitting endless loop when typing a non-existent import path

### ISSUE THREAD

**Issue by tinganho** [TypeStrong/atom-typescript#279]
I've just noticed if you type the wrong import path:

``` typescript
import * as types from './not-leading-to-anything';
```

Close Atom and re-open again it will be stuck in some kind of while loop:

![screen shot 2015-04-20 at 2 13 03 pm](https://cloud.githubusercontent.com/assets/1324476/7224658/cbea6770-e767-11e4-9d48-74227626b447.png)

**Comment by basarat** [comment]
I added a test : https://github.com/TypeStrong/atom-typescript-examples/blob/master/errorcases/notGoingAnywhere/notGoingAnywhere.ts but that doesn't reproduce it. 

Note that yes atom-ts does get into a loop sometimes, Its got to do with the typescript language service (used by other TS ides as well) *hanging*. I suspect it will fix itself over time as more and more people use typescript.

**Comment by tinganho** [comment]
@basarat took me long time to figure out how to recreate this bug.

Take any project. Rename on of the files. Close and start Atom again. The bug appears.

**Comment by tinganho** [comment]
@basarat It just seems like it taking very long time it doesn't get stuck. The counter is also increasing when you type things.

I couldn't recreate this bug on a minimal project though.

**Comment by basarat** [comment]
> I couldn't recreate this bug on a minimal project though.

Its okay. I suspect its got to do with file watching. I'm in the process if removing / refactoring that logic in favor of https://github.com/TypeStrong/atom-typescript/issues/273. I'll let you know when I push (hopefully in under 30 minutes).

**Comment by basarat** [comment]
@tinganho please try latest version : https://github.com/TypeStrong/atom-typescript/issues/273#issuecomment-94405124

And use sync : https://github.com/TypeStrong/atom-typescript#sync for any issues :rose:

**Comment by tinganho** [comment]
@basarat I'm still seeing this issue. It probably got worsen. I experience a longer time for indexing now.

**Comment by basarat** [comment]
Does it reproduce for this repository : https://github.com/TypeStrong/atom-typescript-examples/tree/master/errorcases/notGoingAnywhere

**Comment by tinganho** [comment]
@basarat no it doesn't. I think that project is too small. As said before, I'm only experiencing the long indexing/loading on a larger project.

With the new release I think it introduced another bug. When I rename a file, edit all relevant paths to correspond to the new file name. And when I rename the file again to the original and all paths to the original it doesn't recognize the original file path. I have to close Atom and open it before recognizes the original path.

**Comment by tinganho** [comment]
Here is a video demoing the bug: https://www.youtube.com/watch?v=pXPCy1HZPiM

**Comment by basarat** [comment]
@tinganho sorry to see that. The fact that it jumps to 200 initially is a bit disturbing. Seems `updateText` is throttled on your machine / repo for some reason. I suspect files with 5000+ lines?

Just a tip : at the step where you *I press `cmd+s` but file still shows missing, I need to restart atom* > you can instead use `cmd+'` to do a complete file system reanalysis.
