### ISSUE TITLE
Add cmd-click to go to declaration

### ISSUE THREAD

**Issue by tinganho** [TypeStrong/atom-typescript#280]
I think many people expect `cmd-click` is a default behavior for `go to definition`.

**Comment by Aedaeum** [comment]
I would prefer this as well, F12 feels too far away :tongue:

**Comment by tinganho** [comment]
little bit off topic but how do I press `f-buttons` in Atom on a Mac? `fn+f12` will go to dashboard for me?

**Comment by Aedaeum** [comment]
http://apple.stackexchange.com/questions/85978/how-to-use-f1-f12-keys-with-macbook

**Comment by tinganho** [comment]
@Aedaeum That stack exchange thread didn't help me. I had a default keyboard shortcut. `f12` was set to show dashboard in my computer. I just removed the shortcut and it works now.

**Comment by basarat** [comment]
@tinganho sorry for the crappy defaults. But coming up with them is difficult considering there are competing resharper/vs/webstorm/sublimetext/eclipse bindings.

I've gone with the default `vs` ones where it makes sense and there isn't one that `atom` ships with out of the box.

Note that you can easily override any of these. Just copy https://github.com/TypeStrong/atom-typescript/blob/master/keymaps/atom-typescript.cson Into your `keymaps.cson` and make it whatever you want :rose:
