### ISSUE TITLE
Output toggle showing map instead of js

### ISSUE THREAD

**Issue by Aedaeum** [TypeStrong/atom-typescript#281]
In your demonstration on the front page, it shows the respective `.js` file being split against the `.ts` version. However when I activate it `ctrl+shift+m`, it gives me the `.js.map` file.

Oh, I should add that I'm using the latest version `2.15.12`

**Comment by basarat** [comment]
Thanks :rose:

**Comment by Aedaeum** [comment]
Thank YOU for being so quick :smile:
