### ISSUE TITLE
Support a build server

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#284]
The more stuff we do the more we want the build server to do the *same* stuff, at the very least same TS version.

Export `atom-typescript` to NPM.

Note: it will need IOJS.

**Comment by nycdotnet** [comment]
Hey Bas - any way you can implement this as a module to allow grunt-ts to use also?

**Comment by basarat** [comment]
> any way you can implement this as a module to allow grunt-ts to use also?

If I take pull out `tsconfig.ts` then grunt-ts should be able to just use that logic. 

Note: for big projects `grunt-ts` / others might still be the best option (they will need css setup / minification as well). The plan is to make it easier to create NPM packages / Feed existing JS pipelines with atom-typescript. E.g. one guy I know uses "maven"

**Comment by basarat** [comment]
closed with : https://github.com/TypeStrong/atom-typescript/commit/5e4bf6493376cad94a80b577f36c763ed68bbf22

`npm install atom-typescript -g` 

Then run `atbuild file.ts` wherever and it will build the relevant tsconfig.json

**Comment by basarat** [comment]
Doesn't seem to be working right post deploy. I'll do more tests

**Comment by basarat** [comment]
It works now. But I prefer people use something more liteweight like : https://github.com/basarat/ntypescript#grunt-support just on the build server (grunt-ts offers a much better workflow for non IDE users)
