### ISSUE TITLE
Do I need to browserify?

### ISSUE THREAD

**Issue by kpgarrod** [TypeStrong/atom-typescript#289]
I have been trying to use an enum across multiple files and have implemented the code based on the example https://github.com/TypeStrong/atom-typescript-examples/tree/master/bugs/282.

The code now compiles correctly, but generates errors at run time.

I see that the import statements have generated 'require's in the .js, which is understandable, but does that mean that I have to browserify the files which are using enums? I am not currently using browserify. My build system is based on gulp with injection and concatenation etc.

If I need to browserify, does that mean I need to use a gulp/grunt watch task instead of the automatic compilation that atom-ts does?

I tried implementing the enums with internal modules, but that also did not work satisfactorily in my angular project.

I plan to switch to some sort of external module system when I migrate to angular 2, but am waiting to see what the best practice is for building angular 2 apps.

Am I missing something again? I would really appreciate any guidance.

**Comment by basarat** [comment]
> but does that mean that I have to browserify the files which are using enums

Yes. You need to use *some* module loader. I recommend you just go with webpack right now. See : https://github.com/TypeStrong/atom-typescript-examples/tree/master/multipleCompileTargets 

Note : more guidance coming soon. 

Like the IDE story ... its a bit of a mess. Sorry :rose:
