### ISSUE TITLE
Auto indent could be smarter for something like asterisk comment.

### ISSUE THREAD

**Issue by vilic** [TypeStrong/atom-typescript#290]
Press enter after the last character of the comment below, it should not indent.

```typescript
/**
 *
 */
 [but I got one space before me]
```

**Comment by vilic** [comment]
Ahh, sorry... Wrong place to post. Meant to post on atom project.

**Comment by basarat** [comment]
This annoys me too 🌹 But a backspace isn't tooooo much

**Comment by vilic** [comment]
LOL. Yes but my teammates might forget that,,, and that would be kind of annoying to me. :joy:

**Comment by basarat** [comment]
If you use docblockr it works like a charm now :rose: 
https://github.com/TypeStrong/atom-typescript/blob/master/docs/packages.md#documentation

**Comment by vilic** [comment]
Yeah, I am using that! :D

**Comment by basarat** [comment]
> Yeah, I am using that! :D

I just fixed a bug so that now *it actually* works : https://github.com/TypeStrong/atom-typescript/commit/0e7eff72584dacf0a8679836ef81e34c6311fc0b

**Comment by vilic** [comment]
Yup... But I managed to make it work in some way that I don't really understand. I found the combination of jsdoc and docblockr made it work... LOL.
