### ISSUE TITLE
Prevent default tsconfig.json being created

### ISSUE THREAD

**Issue by felixbillon** [TypeStrong/atom-typescript#292]
Hi,

default tsconfig.json is automatically created. This works well with my TypeScript application but i got an issue in my unit test project wich is in another folder. Multiple default tsconfig.json are automatically created in all sub-folder of my unit test folder... Can i disable this functionnality through setting's menu of atom-typescript package ?

**Comment by basarat** [comment]
> Multiple default tsconfig.json are automatically created in all sub-folder of my unit test folder

For a workaround : Create a `tsconfig.json` at the root of your project, that also encompasses all the tests :rose:

**Comment by felixbillon** [comment]
That's work ! Thanks @basarat ! 

I'm closing this issue.
