### ISSUE TITLE
Support decorators

### ISSUE THREAD

**Issue by alexeagle** [TypeStrong/atom-typescript#297]
This is needed to write Angular2 apps. Need to include TypeScript from head, or package the 1.5 beta when it is out.

**Comment by basarat** [comment]
@alexeagle they should be working. We are already post alpha TypeScrit 1.5 alpha: https://github.com/TypeStrong/atom-typescript/blob/master/package.json#L37

**Comment by basarat** [comment]
Atom-TypeScript is now up to date with TypeScript master by 3 days. :rose:

**Comment by alexeagle** [comment]
Thanks, it was indeed working, I think we had some miscommunication about the rebuild we did for --emitDecoratorMetadata but the emit from Atom does look right.
We plan to promote the plugin to Angular users! (along with WebStorm and Sublime Text)

**Comment by basarat** [comment]
> We plan to promote the plugin to Angular users!

Thanks!
