### ISSUE TITLE
Clarificatoiin on using Promise with quickfix api

### ISSUE THREAD

**Issue by gautamsi** [TypeStrong/atom-typescript#299]
I am trying to right a quickfix which would search for files in the project and insert filename.
I am using parent.getRelativePathsInProject(), this returns a promise. I am unable to build this quickfix. 

how do i convert this call to a sync call instead of async?

**Comment by basarat** [comment]
I've needed to do something similar ... I just ended up copying code from projectService. In your case you should be able to just use : 

```
import {getExternalModuleNames } from "./modules/getExternalModules";
```

which is the heart of `getRelativePathsInProject`.

I'd be happy to review your code if you want :rose:

**Comment by gautamsi** [comment]
I need to search for files and not just external modules. I can make it work for me by changing all the promise chain. breaking all other quick fix.

some other ways:
1. expose projectService on parent and then use is internally for all the sync calls, still need to make sync version of getRelativePathsInProject (quickly possible to clone the function and not resolve, update base function to resolve return value of sync version.

2. inject projectService in constructor of my quickFix, still need to clone the getRelativePathsInProject  function as explained in above option

i am leaning towards option 2; will post code shortly

**Comment by basarat** [comment]
this code is going to run in the worker right?

**Comment by gautamsi** [comment]
it should be, uploading in a min

**Comment by gautamsi** [comment]
just pushed at https://github.com/gautamsi/atom-typescript/commit/7c4ec9f52a16270283a8254f3c2df606efcc5123

let me know if this has any complication of running code outside of worker.

next Wish: can we allow multiple fix provided by single quick fix.

in above example the fix fail if the cursor symbol does not match the file name, i can have this fix provide multiple filename option and then also fix cursor text itself.

**Comment by basarat** [comment]
Your stuff is merged in :rose: 

>  I can have this fix provide multiple filename option and then also fix cursor text itself.

Yes you can return multiple refactorings, its an array for a reason ;). I just need to do a small fix to sort whatever you send : https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/lang/fixmyts/quickFix.ts#L55-L56 so that we apply the fix correctly in the editor < if this confuses you ... don't worry :rose ... just assume *yes*.

**Comment by basarat** [comment]
> if this confuses you

Basically we need to make changes starting at the bottom so that edits don't effect locations of other edits ;)

**Comment by basarat** [comment]
> let me know if this has any complication of running code outside of worker.

minor note: can't use `atom` global in worker :heart:

**Comment by basarat** [comment]
> I can have this fix provide multiple filename option and then also fix cursor text itself.

I'm working on this myself right now. Thanks for an awesome quickfix ... I actually needed this myself quite commonly :rose:

**Comment by gautamsi** [comment]
how about adding another field in refactoring named error, if this is not null, show error using atom in command bindings else go ahead with the refactoring.

**Comment by basarat** [comment]
> how about adding another field in refactoring named error

Such errors should be detected in the `canProvideFix`. If there is a suspicion of an error then the quick fix should not be offered. That's just how I've designed it in its current state but am open to expansion if it doesn't offer any flexibility that is needed.
