### ISSUE TITLE
Find a way to bring in TypeScript "source"

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#300]
Instead of using it from package.json 

Motivations: 
* I don't like getting locked out: https://github.com/Microsoft/TypeScript/issues/2899 Same reason why I'm using the full language service instead of TSServer
* I would (and perhaps *you* whoever is reading) would like to hack stuff in the compiler and get an immediate feedback in the UI. Currently F12 takes me to a `.d.ts` that takes a lot of context away from me and I need to open another window and look at the source *elsewhere*.

**Comment by csnover** [comment]
This change now makes it impossible for me (or anyone) to easily load in a custom compiler by changing package.json and makes #236 probably impossible to implement.

**Comment by basarat** [comment]
> to easily load in a custom compiler by changing package.json

Yes. But they can equivalently just copy their `compiler` and `services` folder. Just a different form of custom compiler loading.

> makes #236 probably impossible to implement.

It does seem like it in first look but its actually quite easy. We just need to run *their* `typescriptServices.js` a vm context can replace our `ts` with *their* `ts`.

**Comment by basarat** [comment]
@csnover #236 done ;) 

![image](https://cloud.githubusercontent.com/assets/874898/7331521/d7d47cf0-eb55-11e4-8541-1654b4a13176.png)
