### ISSUE TITLE
reference path - file cannot be found until Atom is restarted

### ISSUE THREAD

**Issue by spacejack** [TypeStrong/atom-typescript#305]
When you add a new `/// <reference path` line, it will be marked as an error because the file cannot be found - even if the file *is* there. This behaviour will persist until Atom is restarted, then it seems to be able to find the file.

This is happening for me on Windows 8.1.

Example:

    /// <reference path="../../../src/ts/SomeFile.ts" />

**Comment by basarat** [comment]
You don't need to restart. Just run sync : https://github.com/TypeStrong/atom-typescript#sync

Also in faq : https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md

Thanks :rose:

**Comment by spacejack** [comment]
Thank you. Great job on this, I've been using it a lot!

I think one problem is that I have 2 separate directories with .ts files, each with their own tsconfig. I wonder if it gets them confused when opening/editing files from both directories. Sync seems to let me fix things without restarting.

**Comment by basarat** [comment]
Thanks for the kind words :heart: 


> I wonder if it gets them confused when opening/editing files from both directories.

It will definitely be out of date if *you add a file*. That is what sync is for :rose:
