### ISSUE TITLE
Add a quick fix notification

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#306]
A nice icon should show up if there is a quick fix available for a particular location

Possible icons :hammer:  or :bulb: or octicon :heart:

**Comment by nycdotnet** [comment]
Lightbulb will be used in VS 2015/Roslyn.

**Comment by basarat** [comment]
> Lightbulb will be used in VS 2015/Roslyn.

Lightbulb it is then :rose:  
![stringconcattotemplate](https://cloud.githubusercontent.com/assets/874898/7359954/8264bf5c-ed88-11e4-8ec6-85ada4687081.gif)
