### ISSUE TITLE
Adding a reference causes build to create unwanted directory tree

### ISSUE THREAD

**Issue by spacejack** [TypeStrong/atom-typescript#308]
I have the following file structure:

    test/
        ts/
            test.ts
            tsconfig.json
        js/
            test.js <- compiler output

My tsconfig specifies “outDir”:”../js” so that ts files are compiled to js files in that directory.

But if I add a reference to a typescript file to test.ts, eg:

    /// <reference path="../../lib/ts/File.ts"/>

Then on build, it creates an unwanted directory tree under ‘js’ and the compiled js ends up under js/test/ts/test.js. Eg:

    test/
        ts/
            test.ts
            tsconfig.json
        js/
            test/
                ts/
                    test.js <- compiler output

This happens on Windows 7 & 8.1.

**Comment by basarat** [comment]
> Then on build, it creates an unwanted directory tree under ‘js’ and the compiled js ends up under js/test/ts/test.js. Eg:

This is by design. Output is based on a concept of `commonRootDir`. Search for `rootDir` and `baseDir` in Microsoft/TypeScript/issues for details. 

Thanks ! :rose:
