### ISSUE TITLE
How to see signatures of function's overloads?

### ISSUE THREAD

**Issue by lazutkin** [TypeStrong/atom-typescript#309]
Is there any way to see all signatures of functions's signatures? Currently popup shows only first signature and number of its overloads like `+n`.

**Comment by basarat** [comment]
The show up as snippets when you are in the calling context i.e. `(`: 
![image](https://cloud.githubusercontent.com/assets/874898/7364301/59c5b5de-edc8-11e4-9b4f-5c6d1469e58f.png)

Note that autocomplete isn't triggering correctly in this case. https://github.com/atom-community/autocomplete-plus/issues/329 so you need to trigger it manually (ctrl + space). 

I will close https://github.com/TypeStrong/atom-typescript/issues/23 once that is resolved :rose:
