### ISSUE TITLE
How to break long lines in tooltips?

### ISSUE THREAD

**Issue by donnut** [TypeStrong/atom-typescript#313]
I'm trying to figure out how to break long lines in the tooltip, see picture

![linebreak](https://cloud.githubusercontent.com/assets/417406/7387330/89ffaba8-ee5c-11e4-8e1a-bda328c8456d.jpg)

I've tried using
- tags, like the picture shows (`<p></p>`)
- `\n`
- `<br/>`
- extra empty line

**Comment by basarat** [comment]
`\n` should have made it multiple lines. 

I'll investigate today.

**Comment by basarat** [comment]
`4.0.15`

**Comment by donnut** [comment]
Great! Thanks
