### ISSUE TITLE
Improve TS 1.5 support.

### ISSUE THREAD

**Issue by Zoltu** [TypeStrong/atom-typescript#323]
https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/tsconfig/tsconfig.ts#L9

TS 1.5 is now available via `npm install typescript`.  Since this plugin now uses that, I believe it is safe to follow-through with that TODO.

**Comment by Zoltu** [comment]
Personal Note:
My interest lies primarily in support for `rootDir`.  I am trying to slowly migrate an ES6 project over to TypeScript and that means some of the first things migrated will be files nested inside of folders.  Currently, I cannot get this plugin to work correctly because it throws my build output in the wrong location.

**Comment by basarat** [comment]
Note: I think using `rootDir` is a bad idea : https://github.com/Microsoft/TypeScript/pull/2034#issuecomment-94649963 but YMMV.

**Comment by basarat** [comment]
We cannot use ts.parse because of the validation stuff we do. Please raise an issue if there are any other compiler flags you need supported :rose:

**Comment by Zoltu** [comment]
Thanks!  As to why `rootDir`:

My project structure usually looks something like:
* project
	* tsconfig.json
	* package.json
	* config.js
	* gulpfile.js
	* \<every other config file a tool wants to add\>
	* source
		* index.ts
		* index.html
		* styles.css
		* subdirectory
			* index.html
			* styles.css
			* index.ts
	* output
		* \<same as source, but transpiled/copied\>
	* npm_modules
		* \<modules\>
	* jspm_modules
		* \<modules\>

As you can see, my source tree is not rooted at my tsconfig.json.  This is intentional because I want my source tree to be *just* source, not a bunch of tool config files, dependency managed files, etc.  Because of this structure, I need a way to tell TypeScript that when it builds `source/subdirectory/index.ts` and has an `outDir` of `output` it needs to retain the `subdirectory` in the path, but not the `source` in the path.

One of the advantages of this structure is that it allows my tooling to glob on source.  If you were to glob on the root directory, you would have to be sure to ignore all of the dependency managed folders as well as all of the various config files.  I find it easier (and cleaner) to just keep all of my source code separate from the project metadata which sits in the root folder.

**Comment by basarat** [comment]
> I find it easier (and cleaner) to just keep all of my source code separate from the project metadata which sits in the root folder.

Cool. Previously I would just move `tsconfig.json` into the `source` folder and then `outDir` to `../output`. But I see the benefit of `tsconfig.json` being where you have put it. Thanks for taking the time to share :rose:
