### ISSUE TITLE
Issue with Mocha and Angular sintax tests

### ISSUE THREAD

**Issue by dantedubon** [TypeStrong/atom-typescript#326]
I have a problem using Mocha with Angular, the following line 
```
beforeEach(module('app.users'));
```
Is rejected, apparently, by the compiler of Typescript with the following error 
**Cannot invoke an expression whose type lacks a call signature.
module('app.users')**
The problem is that this error only appear with the atom plugin, and not with the console. I don't know if this is an error of the plugin or an error of the type definition. I already posted this situation on the definitions repository: https://github.com/borisyankov/DefinitelyTyped/issues/4250

Thanks

**Comment by basarat** [comment]
> module('app.users')

Can you share the project. Note: I am specifically interested in the `module` variable *declaration*.

**Comment by dantedubon** [comment]
This is the code of the spec, all my others specs suffer of the same issue in the same place, with the _module_ of Angular. if you need more information I will provide it: 

```javascript

describe('users.forgotPassword.service', () => {

    var forgotPasswordService: IUserForgotPasswordService;
    var $httpBackend: angular.IHttpBackendService;
    var emailSent: IUserForgotPasswordRequest = {
        email: 'test@test.com'
    };

    beforeEach(module('app.users'));
    beforeEach(inject(function(_forgotPasswordservice_: IUserForgotPasswordService,
            _$httpBackend_: angular.IHttpBackendService) {
        forgotPasswordService = _forgotPasswordservice_;
        $httpBackend = _$httpBackend_;
    }));
   ;
    afterEach(function() {
        $httpBackend.verifyNoOutstandingExpectation();
        $httpBackend.verifyNoOutstandingRequest();
    });
    it('Should be definied', function() {
        chai.expect(forgotPasswordService).to.not.be.undefined;
    });
});
```

**Comment by basarat** [comment]
@dantedubon I am assuming you have the file `angular-mocks` included? https://github.com/borisyankov/DefinitelyTyped/blob/master/angularjs/angular-mocks.d.ts#L21

**Comment by dantedubon** [comment]
It's correct, I am using the following typings: 
mocha.d.ts
chai.d.ts
sinon.d.ts
sinon-chai.d.ts
angular.d.ts
angular-mocks.d.ts

**Comment by basarat** [comment]
Can you share an example on github, would make it easier for me to investigate :rose:

**Comment by dantedubon** [comment]
I fixed the problem using all the typed name: 
```javascript
beforeEach(angular.mock.module('app.users'));
```

**Comment by basarat** [comment]
Awesome. Thanks :+1:

**Comment by oshalygin** [comment]
Thanks for the tip @dantedubon, was stumbling with this in VSCode.
