### ISSUE TITLE
Issue with complex object literal with null property

### ISSUE THREAD

**Issue by nycdotnet** [TypeStrong/atom-typescript#337]
Hi,

This may very well be a TypeScript language service issue, but I figured it might be worth bringing up.

I was just working on this repository: https://github.com/nycdotnet/downloadAnalysis

In `downloadAnalysis.ts`, on line 31 (line 22 in the screenshot), I tried to add a new property to the return of the `map` function.  When I do `item.` in atom-typescript, the popup is quite large - it even has scrollbars.  This is mostly related to the `author` property which is a complex type.  It might be nice if really long items in this popup could overflow but more normal-sized ones could behave in their normal manner because scrolling horizontally in the autocomplete window is not the greatest experience.

![atom-typescript-scrollpopup1](https://cloud.githubusercontent.com/assets/3755379/7539070/6e2ea150-f572-11e4-9933-41e57ae49234.png)

Second, I notice that everything listed below `author` shows as just `property` instead of having the actual type.  I wonder if the language service is getting confused here?  I have a theory that it is because the value for `author.label` is `null` for all instances of `author` and TypeScript isn't able to infer the type.  This code doesn't currently compile if `--noImplicitAny` is active.

![atom-typescript-scrollpopup2](https://cloud.githubusercontent.com/assets/3755379/7539072/76632422-f572-11e4-9941-a701a92b7705.png)

Hope that this is a useful and actionable report.  Thanks, @basarat for a great editing experience that is getting better by the day!!

**Comment by basarat** [comment]
Just info for amusement: 

The way the language service completion info works : it gives you a list of completions with some basic stuff and if you want stuff like doc comments etc you call [`getCompletionEntryDetails`](https://github.com/TypeStrong/atom-typescript/blob/1e490a4785db28f868fa0d6a8d77ec70f73a6df7/lib/main/lang/projectService.ts#L180)

And *we do custom stuff on top to make it a pleasant experience*. Marked as a bug as it needs to be more pleasant :rose:

**Comment by basarat** [comment]
The current experience is better : 

![image](https://cloud.githubusercontent.com/assets/874898/8475913/503c865e-20ff-11e5-8ef5-f3951c19c096.png)

**Comment by basarat** [comment]
Also:

> Second, I notice that everything listed below author shows as just property instead of having the actual type

![image](https://cloud.githubusercontent.com/assets/874898/8475937/8c95b9f4-20ff-11e5-93ec-08152560a3bd.png)
