### ISSUE TITLE
Support TODO in the grammar

### ISSUE THREAD

**Issue by Aedaeum** [TypeStrong/atom-typescript#338]
I created an issue over here: https://github.com/atom/language-todo/issues/22

Evidently the way atom-typescript is inserting its grammar (via tokenization) is circumventing the standard convention. Can you confirm/deny this?

**Comment by basarat** [comment]
> is circumventing the standard convention. Can you confirm/deny this?

Confirmed. Reason: Because it was easier to maintain (based on code *maintained by the typescript team*) and faster than `language-typescript`.

**Comment by Aedaeum** [comment]
Is this something you're willing to support? I understand you've got a lot of higher priority issues right now, I just want to know if I can expect this added/fixed in the future.

**Comment by basarat** [comment]
> I just want to know if I can expect this added/fixed in the future.

definitely, I would like this too :rose:

**Comment by basarat** [comment]
TODO something the following for `.ts` files:

![image](https://cloud.githubusercontent.com/assets/874898/7558601/3de5bf3a-f7eb-11e4-9836-1453a3741cb6.png)

**Comment by Aedaeum** [comment]
You're such a tease!

Looks good :smile:

**Comment by nycdotnet** [comment]
Looks great, Bas.  `// bug:` please.  :-)

**Comment by basarat** [comment]
After my next push:

![image](https://cloud.githubusercontent.com/assets/874898/7560159/b0b54b76-f803-11e4-9847-f0a1502b5fbc.png)


@nycdotnet it is case sensitive so `BUG` no `bug`
