### ISSUE TITLE
Show autocomplete Doc Comments

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#34]
Show more than just the kind e.g. show function signatures in label (trimmed)

Also show doc comments. e.g. see: 

https://github.com/tststs/atom-ternjs

Would be easier if Autocomplete+ supported so keep an eye on : https://github.com/atom-community/autocomplete-plus/issues/209

**Comment by basarat** [comment]
This is the view that it uses : https://github.com/tststs/atom-ternjs/blob/master/lib/atom-ternjs-documentation-view.coffee 

And the view is managed by : https://github.com/tststs/atom-ternjs/blob/master/lib/atom-ternjs-documentation.coffee

**Comment by basarat** [comment]
Its okay to extend `HTMLElement` : https://github.com/atom-community/autocomplete-plus/blob/f17659ad4fecbd69855dfaf00c11856572ad26e7/lib/suggestion-list-element.coffee

**Comment by claudio-silva** [comment]
:+1: for this one!
Always having documentation at your fingertips is a major productivity boon.
It would make one's development experience much closer to Webstorm ;-)

**Comment by basarat** [comment]
the magic lines for registering up / down / cancel : https://github.com/tststs/atom-ternjs/blob/4616908855ac2efd1e2f3a1129a4eb4e47b78b52/lib/atom-ternjs-provider.coffee#L163-L175

**Comment by basarat** [comment]
set position logic https://github.com/tststs/atom-ternjs/blob/4616908855ac2efd1e2f3a1129a4eb4e47b78b52/lib/atom-ternjs-documentation.coffee#L17-L43

**Comment by basarat** [comment]
the events come from here : https://github.com/atom-community/autocomplete-plus/blob/9610565ae688ffd9b07cc8b850ad7dd562f5e969/lib/suggestion-list.coffee

**Comment by basarat** [comment]
Hold on working this ourselves *just for us* https://github.com/atom-community/autocomplete-plus/issues/209#issuecomment-75149463

**Comment by basarat** [comment]
Will be a part of : https://github.com/atom-community/autocomplete-plus/pull/347

**Comment by basarat** [comment]
Wait for autocomplete plus 2.10.0 :eyes: on https://github.com/atom-community/autocomplete-plus/blob/master/package.json

because https://github.com/atom-community/autocomplete-plus/pull/386 got merged

**Comment by basarat** [comment]
This should work now. In case you are wondering: 
![image](https://cloud.githubusercontent.com/assets/874898/7171763/449e35de-e420-11e4-834b-d636fc40e33a.png)
