### ISSUE TITLE
Build errors after a git checkout

### ISSUE THREAD

**Issue by simonlast** [TypeStrong/atom-typescript#340]
After I do a `git checkout`, and a lot of files change in my project, the editor displays errors in every file. When I quit and reopen atom the errors disappear.

**Comment by basarat** [comment]
> and a lot of files change in my project, the editor displays errors in every file. When I quit and reopen atom the errors disappear.

You don't need to restart. Just `sync` : https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#atom-typescript-is-complaining-about-not-finding-files-or-other-weird-errors for external file system changes :rose:

**Comment by simonlast** [comment]
Awesome, thanks :)
