### ISSUE TITLE
width tooltip pane restricted by window split

### ISSUE THREAD

**Issue by donnut** [TypeStrong/atom-typescript#345]
I'm not sure if this is an atom-typescript issue.
![tooltip-break](https://cloud.githubusercontent.com/assets/417406/7632930/5b7b74d2-fa51-11e4-92dc-70b119de7bcf.png)
Thanks!

**Comment by basarat** [comment]
more like an autocomplete-plus issue. Instead of fixing width I'd be interested in fixing the z-index so it comes over both panes. Leaving it open for now :rose:
