### ISSUE TITLE
Missing dependencies on every startup

### ISSUE THREAD

**Issue by fbender** [TypeStrong/atom-typescript#350]
I installed `atom-typescript` with `apm install atom-typescript` and restarted Atom (it was running during install and downloaded an app update before I ran `apm install`). On every (re-)start since then, a message appears saying that AtomTS dependencies are missing; shortly afterwards, the message confirming successful installation of the dependencies appears.

**Comment by fbender** [comment]
Can no longer reproduce, did a uninstall & reinstall.

**Comment by basarat** [comment]
Thanks 🌹

**Comment by wiggisser** [comment]
I still see this issue with Atom 0.209 on Windows and AtomTS 4.5.13. In addition I notice a package ".bin" in my package list, which seems to be related to atom-typescript (judging from its contents)

**Comment by basarat** [comment]
The .bin is because of a "safe" bug in atom.  So you can ignore that.

**Comment by jjlorenzo** [comment]
Atom 1.0.0 atom-typescript 4.6.11 and OSX
If `linter` or `autocomplete-plus` are uninstalled or deactivated the popups appears.

Since I usually works disconnected (Cuba) I tend to install everything I could when online, then deactivate unused extensions. The popup could be more explicit, since it appears to fix temporarily the problem.

**Comment by basarat** [comment]
> then deactivate unused extensions.

If you disable atom-typescript when you disable linter / autocomplete-plus this shouldn't happen

**Comment by wiggisser** [comment]
huh, i didn't have linter installed. after i installed it, the popup did not appear again.

**Comment by alexweber** [comment]
Confirm I get this on every new window being opened... running Atom 1.0 on OSX with Linter already enabled before I installed the Typescript package

**Comment by basarat** [comment]
@alexweber try uninstall / reinstall / atom restart

**Comment by alexweber** [comment]
@basarat That did the trick, thanks!

**Comment by jjlorenzo** [comment]
@alexweber what about  `autocomplete-plus` ?
```javascript
    var linter = apd.require('linter');
    var acp = apd.require('autocomplete-plus');
    if (!linter || !acp) {
        var notification = atom.notifications.addInfo('AtomTS: Some dependencies not found. Running "apm install" on these for you. Please wait for a success confirmation!', { dismissable: true });

@basarat apologize for not having explained well. What I meant was that the error started when I turned off some extensions.
```

**Comment by alexweber** [comment]
@jjlorenzo To clarify, I did a full uninstall & reinstall of atom-typescript and linter and the nagging popup stopped.  I wasn't aware that autocomplete-plus also was one of the dependencies but fortunately I already had it enabled.

**Comment by jjlorenzo** [comment]
@alexweber I really don't know the atom api, so I can't say that `atom-typescript` fail activating those modules, in this code: 

```javascript
// atomts.js L139
atom.packages.activatePackage('linter')
  .then(function () { 
    return atom.packages.activatePackage('autocomplete-plus'); 
  })
  .then(function () { 
    return readyToActivate(); 
  });
```

It seems that it activate those packages, but probably the `atom.packages.activatePackage` doesn't permanently save the package state, it's only my guess.

What it seems to me that `atom-typescript` should fix in case my guess are right, is the popup messages, giving the user a hint about the real problem:
 - the packages deps aren't installed
 - the packages deps aren't active

As previously users report, a full uninstall + reinstall probably makes the popup disappears, but doesn't fix the laying bug.

**Comment by jjlorenzo** [comment]
@fbender to reproduce, try to manually deactive in the settings page the mentioned required plugins `linter` and/or `autocomplete-plus`. IMHO this issue should be reopened since it can be reproduced. 

But again the fix IMHO is more like a cosmetic change in the messages.

**Comment by jjlorenzo** [comment]
Did atom api allow to permanently activate packages?

**Comment by basarat** [comment]
> Did atom api allow to permanently activate packages?

Not as far I can see

**Comment by basarat** [comment]
> Did atom api allow to permanently activate package

Would need to dig into the settings package. The beauty of OSS ;)
