### ISSUE TITLE
Refactoring : extract variable

### ISSUE THREAD

**Issue by geowarin** [TypeStrong/atom-typescript#351]
I think it would be nice to have a refactoring where you take a statement and put it into a variable.

Example 1

```typescript
class Example {
   method():string {
      return 'hello';
   }
}

new Example().hello()
```

extract variable on the `hello()` method =>

```typescript
class Example {
   method():string {
      return 'hello';
   }
}

var hello:string = new Example().hello()
```

Example 2:

```typescript
class Example {
   method(num:number):string {
      return 'hello ' + number;
   }
}

new Example().hello(42)
```

extract variable on the `42` parameter =>

```typescript
class Example {
   method(num:number):string {
      return 'hello ' + number;
   }
}

var num:number = 42;
new Example().hello(num)
```

In the first case, the name of the variable can be inferred from the method name and in the second, from the parameter name.

What do you think?

**Comment by basarat** [comment]
> What do you think?

Reasonable request. Anything that make your life easier :rose:

**Comment by rogergl** [comment]
Since I'm having trouble with the extract inteface refactoring I'll continue with this one. Or is someone already working on this?

**Comment by rogergl** [comment]
I think I need some help. Since the AST does not contain any type information it seems that I have to ask the language service. But how ? And if I have an expression like this:

     anObject.aProperty.anotherObject.aCall()

can I ask the language service about the return type of this expression ?

**Comment by basarat** [comment]
> can I ask the language service about the return type of this expression

Yes. You need to ask the language service's `typechecker`. This is available on the QuickFix info object. As a sample check out : https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/lang/fixmyts/quickFixes/addClassMember.ts#L67 

Also note that `Symbol` is supposed to be the unit of type information : https://github.com/Microsoft/TypeScript/wiki/Architectural-Overview#data-structures

**Comment by rogergl** [comment]
Thanks, it's starting to work. Just one question. Is this the right way to get the start of the line:

        let theSource = info.positionNode.getSourceFile()
        let pos = theSource.getLineAndCharacterOfPosition(info.positionNode.pos);
        let currentLine = pos.line;
        let start = theSource.getLineStarts()[currentLine];

**Comment by basarat** [comment]
> Is this the right way to get the start of the line:

I would recommend: 

```ts
var {line} = info.project.languageServiceHost.getPositionFromIndex(info.filePath, info.position);
var start = info.project.languageServiceHost.getIndexFromPosition(info.filePath, { line, col: 0 });
```

Your method isn't bad either and :+1: for figuring *that* out :rose:. That's mostly what I do as well :)

**Comment by rogergl** [comment]
I think I've got it ready. But I would like to post an example here how it works right now. What tool have you used to screen record the quickfixes ?.

**Comment by basarat** [comment]
> What tool have you used to screen record the quickfixes 

https://screentogif.codeplex.com/

Tip: resize the recorder, and work through the example to make sure it fits. Then rerun with the recording on ;)

**Comment by rogergl** [comment]
That is the stuff that is currently working:

![example](https://cloud.githubusercontent.com/assets/98088/8438678/9aea2c54-1f67-11e5-918e-620adccdb9ce.gif)

**Comment by geowarin** [comment]
Looks promising! I'm really looking forward for the pull request to see how you manage to implement it.
Thanks @rogergl for the time invested.

**Comment by tomsdev** [comment]
Should this issue be closed since the PR has been merged?

**Comment by basarat** [comment]
🌹
