### ISSUE TITLE
Refactoring: inline variable

### ISSUE THREAD

**Issue by geowarin** [TypeStrong/atom-typescript#352]
This is the opposite transformation of the extract variable refactoring (#351).

With this refactoring, you take a variable and replace its usages by the actual value.

Example:

``` typescript
var debug:string = "something";
console.log(debug);
console.log(debug);
```

Inline on the `debug` variable:

``` typescript
console.log("something");
console.log("something");
```

Inlining could also be done on method calls, but I think it would require more work.

Example:

``` typescript
class Greeter {
   greet() {
       console.log('statement');
       console.log('hello');
   }
}

var greeter = new Greeter();
greeter.greet();
greeter.greet();
```

Inline on the `greet()` method:

``` typescript
class Greeter {
}

var greeter = new Greeter();
console.log('statement');
console.log('hello');
console.log('statement');
console.log('hello');
```

In this case, keeping the original method can also be an option, if I want to inline only the first call:

``` typescript
class Greeter {
   greet() {
       console.log('statement');
       console.log('hello');
   }
}

var greeter = new Greeter();
console.log('statement');
console.log('hello');
greeter.greet();
```

What do you think?

**Comment by basarat** [comment]
> What do you think?

A bit complex transform in terms of making sure there are no side effects. Also generally people prefer refactoring into variable (the reverse direction) to ease readability / maintainability.

**Comment by geowarin** [comment]
Side effects, yes.
You mean what happens if the method has a reference to an inner attribute of this object...
In that case, intellij just displays an error message.

I have to disagree, it's a very useful refactoring. See:
https://sourcemaking.com/refactoring/inline-method

During a refactoring you sometime get to a place where one method gets in your way and you have to inline it in order to extract something more interesting.

I agree the refactoring might be a little difficult to implement but I'm really loving my typescript experience with the plugin so far. I'd like everything to be perfect :)

**Comment by basarat** [comment]
Reading that link:

> when someone is using too much indirection and it seems that every method does simple delegation to another method, and I get lost in all the delegation

Been there. So :+1:
