### ISSUE TITLE
Add property to object quick fix fails to create a method when passed as an argument

### ISSUE THREAD

**Issue by geowarin** [TypeStrong/atom-typescript#356]
In the case you wish to pass a non existing method to a callback:

```typescript
class Test {
  
}

function execute(callback:Function) {
  callback();
}

var test = new Test();
execute(test.callback);
```

The 'add callback to Test' quick fix will appear.
But that will not create a method as expected:

```typescript
class Test {
    callback: any; 
}

function execute(callback:Function) {
  callback();
}

var test = new Test();
execute(test.callback);
```

I know this is a limit case but that would be uber awesome to have this ;)

**Comment by basarat** [comment]
Related : https://github.com/TypeStrong/atom-typescript/issues/344 :rose:

**Comment by helarqjsc** [comment]
Apparently it was fixed already. It creates a new method as it supposed to:

![Gif](http://g.recordit.co/APdfup5ly9.gif)

**Comment by basarat** [comment]
Yes by @xperiments https://github.com/TypeStrong/atom-typescript/pull/426#issuecomment-118126226 :rose:
