### ISSUE TITLE
Support comments in tsconfig.json

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#357]
Pipe through jsmin before sending to JSON.parse. Depending upon status of https://github.com/Microsoft/TypeScript/issues/3079

**Comment by eekboom** [comment]
Yes, please!
Somebody just changed
`"removeComments": false`
to
`"removeComments": true`
and broke minification of our angular app.
I really want to write
`"removeComments": false, // Needed to make @ngInject comment work for ng-annotate`
