### ISSUE TITLE
Code completion failing

### ISSUE THREAD

**Issue by Aedaeum** [TypeStrong/atom-typescript#359]
I've created a new project with `node.d.ts` and `lib.es6.d.ts` using the `noLib: true` flag in the `tsconfig` file. I'm using the latest Atom `v0.200.0`

I import the file like so:
```javascript
import * as chalk from 'chalk'
```

If I reload Atom using `CTRL+ALT+R` completions work only once, then subsequent completions produce odd results as demonstrated below:

**After Atom reload**
![image](https://cloud.githubusercontent.com/assets/2054218/7730886/c040b4de-fed1-11e4-8f8f-9785e64537aa.png)

**Try second completion**
![image](https://cloud.githubusercontent.com/assets/2054218/7730923/ec0b30d0-fed1-11e4-8584-003e9cd85b15.png)

I should note that this is not isolated to Chalk. After the first completion, all subsequent completions will not work for any libraries that I have `d.ts` files for.

**Comment by basarat** [comment]
I've had similar issues happen recently. Didn't investigate much. Will do that today :rose:

**Comment by basarat** [comment]
Sorry that this keeps happening. I thought there was a bug in atom, then found one in my code instead and assumed atom was okay (based on testing), and now found one in atom again. Fixed with `v4.5.0`. Thanks for your patience :heart:

**Comment by Aedaeum** [comment]
No problem :smile: 
I'm just glad you're able to quickly resolve these.
