### ISSUE TITLE
speed up opening time

### ISSUE THREAD

**Issue by muhasturk** [TypeStrong/atom-typescript#361]
It takes 226 ms on my OSX i7 2.2ghz machine
![](http://i.imgur.com/gOq57C4.png)

**Comment by Aedaeum** [comment]
I'll contribute to this:
![image](https://cloud.githubusercontent.com/assets/2054218/7758003/4c67edda-ffbb-11e4-9e0d-d0128817e32f.png)

I believe this is going to be a fairly large undertaking though and will probably be one of the last things addressed.

**Comment by krzychukula** [comment]
![screen shot 2016-05-31 at 16 28 33](https://cloud.githubusercontent.com/assets/240264/15678008/ed5d91cc-274c-11e6-9367-cba37d2c16b2.png)
Package activation takes a lot of time (for a relatively small project).
