### ISSUE TITLE
Syntax highlighting should highlight AMD comments

### ISSUE THREAD

**Issue by ryanp-me** [TypeStrong/atom-typescript#363]
Currently, atom-typescript only highlights comments for references, but it should also highlight the AMD comments:

```typescript
/// <amd-module name="..." />
/// <amd-dependency path="..." />
```

They can be found on lines [4792 to 4812][1] of Microsoft's current parser.

[1]: https://github.com/Microsoft/TypeScript/blob/029fbb0d4f37ef2b90c1d6749030e03136db305d/src/compiler/parser.ts#L4792-L4812

**Comment by basarat** [comment]
Thanks :rose:. Marking it up for grabs. Hints : 

* needs to go here : https://github.com/TypeStrong/atom-typescript/blob/f506e83ea84e2ae026ce07837ee4afcf11042a06/lib/main/atom/typescriptGrammar.ts#L67-L75 

* Along with optional styling here : https://github.com/TypeStrong/atom-typescript/blob/f506e83ea84e2ae026ce07837ee4afcf11042a06/styles/atomts-syntax.less

* And autocomplete support : https://github.com/TypeStrong/atom-typescript/blob/f506e83ea84e2ae026ce07837ee4afcf11042a06/lib/main/atom/autoCompleteProvider.ts#L125

**Comment by ryanp-me** [comment]
That looks easy enough. I can do it and submit a pull request.
