### ISSUE TITLE
irrelevant .bin package

### ISSUE THREAD

**Issue by muhasturk** [TypeStrong/atom-typescript#365]
As you see below there is a package called **.bin** on "Packages" section. If you click on it you will see this package relevant with atom-typescript.

![](http://i.imgur.com/dpGyJOr.png)

![](http://i.imgur.com/VFJQ7AL.png)

OSX 10.10.3
Atom 0.204
All packages are updated

**Comment by basarat** [comment]
Issue is that `apm install` (like `npm install`) creates a `.bin` directory copying the contents of any `.bin` files. It makes sense for `npm` but not for `apm`. Needs to be reported to the atom team. I'll make that issue report when I have time. Till then this should not cause any issues.

**Comment by zimme** [comment]
Can't find an issue about this in atom/atom, have someone submitted it yet?

**Comment by basarat** [comment]
> have someone submitted it yet?

nope. I feel it harmless which is why I didn't

**Comment by zimme** [comment]
Ok, I'll open an issue about this on atom's issue tracker referencing this issue. Sure it's harmless but it's still anoying to have a "package" in the list which isn't a package.

**Comment by zimme** [comment]
atom/settings-view#348

**Comment by impinball** [comment]
@basarat Could you close this? The relevant bug is already linked.

**Comment by basarat** [comment]
Thanks. Please follow : https://github.com/atom/settings-view/issues/348 for tracking :rose:
