### ISSUE TITLE
Project templates

### ISSUE THREAD

**Issue by Diullei** [TypeStrong/atom-typescript#366]
Just an idea, I think would be nice to have typescript project templates. This could be implemented using yeoman.

**Comment by david-driscoll** [comment]
I made https://github.com/david-driscoll/atom-yeoman for Atom as well, and we use it in https://github.com/OmniSharp/omnisharp-atom for project creation.

**Comment by Diullei** [comment]
Nice! This is exactly what I was thinking about. I'll take a look on how you integrate it with omnisharp-atom.

**Comment by basarat** [comment]
I find creating snippets very helpful (compared to generated files)

**Comment by Diullei** [comment]
@basarat, I agree, the snippets are very helpful. I was thinking about the following scenarios:

* I want to create an AngularJs application using Typescript.
* I want to create a Backbone application using Typescript.
* I want to create an Atom package application using Typescript (not coffee :) ).
* ...

To start this application I need to configure grunt/gulp, tslint, test, bower, travis, ...

It would be very useful if I had a good template to use as a kick start.

What do you think?

**Comment by basarat** [comment]
> What do you think?

yeoman templates for the win :rose:

**Comment by Diullei** [comment]
I'll create a new repo and start this work! :)
