### ISSUE TITLE
Semantic Grammar coming back?

### ISSUE THREAD

**Issue by david-driscoll** [TypeStrong/atom-typescript#367]
I was wondering if the Semantic Grammar was coming back or if the plan is just to the cson based grammar?

**Comment by basarat** [comment]
At this point I am a bit undecided (docs https://github.com/TypeStrong/atom-typescript/blob/master/docs/grammar.md) but it looks like I will stick to CSON. 

One thing that is a fact is that CSON grammar makes embedded DSLs MUCH easier to syntax highlight, which is what I am aiming for : https://github.com/TypeStrong/atom-typescript/issues/362 the grammar : https://github.com/TypeStrong/atom-typescript/blob/212028cede9b444919f8115ebb0e5073b32fbe68/grammars/typescript.cson#L141-L181
