### ISSUE TITLE
Error finding files not in tsconfig.json

### ISSUE THREAD

**Issue by isuda** [TypeStrong/atom-typescript#368]
There is an error in the console when you attempt to view and edit typescript files in your project that are not listed in the files array in tsconfig.json:

![image](https://cloud.githubusercontent.com/assets/25780/7887724/0cbb05e0-05e8-11e5-9309-36dc8efe29c7.png)

![image](https://cloud.githubusercontent.com/assets/25780/7887749/3533406e-05e8-11e5-9b07-5d537c55d8c3.png)

If test2.ts is in my files array, then there is no errors, and everything works normally.

In my project this error prevents all intellisense and autocompletion in those files, as well as causes the AtomTS worker to take up 100% of my CPU (although it does not in the example I pasted).

I would like to exclude files like unit tests written in typescript from being compiled to javascript, because I do not need/want them to output JS files normally.

**Comment by basarat** [comment]
We definitely need support for *files that are part of the compilation context __but__ not actual compilation*. This work hasn't been done and marking this up for grabs
