### ISSUE TITLE
Rename external modules

### ISSUE THREAD

**Issue by nycdotnet** [TypeStrong/atom-typescript#369]
It would be great if when a .ts file is renamed, atom-typescript would update external module references automatically.

For example if renaming `foo.ts` to `bar.ts`, it would be awesome if `bas.ts` changed from this:

```typescript
import stuff from './foo';
```

...to this...

```typescript
import stuff from './bar';
```

**Comment by erikvullings** [comment]
And wouldn't it be great if any generated definition and JavaScript files would be renamed or removed too. I sometimes, after renaming a file, end up with duplicate errors in my concatenated files, and have to remove them manually.

**Comment by basarat** [comment]
Duplicate of https://github.com/TypeStrong/atom-typescript/issues/240. If you focus on `./foo` and press f2 and type in a new path the refactoring *actually works and references are updated*, 

Pending : 
* the *file is not actually renamed on file system*
* the user can't trigger the refactoring from the tree view https://github.com/atom/tree-view/issues/433

**Comment by nycdotnet** [comment]
Thanks
