### ISSUE TITLE
Make error pop-up more like Visual Studio.

### ISSUE THREAD

**Issue by Zoltu** [TypeStrong/atom-typescript#370]
![image](https://cloud.githubusercontent.com/assets/886059/7898904/d726cf0e-06c3-11e5-9dd3-6238ead08be5.png)

While typing, I will get a little tooltip like this all the time.  While it is open, I cannot see what is under the tooltip.  Also, it is perpetually there since at any given point in time I'm likely in the middle of a word/expression so the syntax is invalid.

Ideally, I would rather not see the error tooltip *as* I type.  It should only be on mouse-over of an error (like Visual Studio intellisense).  Second to that, I would like to be able to close the error tooltip via the escape key, like I can close the auto-completer.

**Comment by basarat** [comment]
Really belongs in : https://github.com/AtomLinter/Linter :+1: 

FWIW you can change using `linter` settings:

* the location of the tooltip
* the duration after which the tooltip will show since last change
