### ISSUE TITLE
quickfix: create properties from constructor args ?

### ISSUE THREAD

**Issue by rogergl** [TypeStrong/atom-typescript#375]
This is the one feature I really miss: create assignment and property from a constructor argument.

**Comment by basarat** [comment]
I am thinking:

```ts
foo:string
constructor(someArg:string)
```
to: 
```ts
constructor(someArg:string, public foo:string)
```

Is this correct?

**Comment by rogergl** [comment]
Or

```javascript
private _someArg:string;
private _foo:string;
```
to

```javascript
private _someArg:string;
private _foo:string;

constructor(someArg:string, foo:string) 
{
   this._someArg = someArg;
   this._foo = fool
}

get someArg(): string {
    return this._someArg;
}

set someArg(value: string) {
    this._someArg = value;
}

get foo(): string {
    return this._foo;
}

set foo(value: string) {
    this._foo = value;
}
```
It would be nice if it is possible to select If I just wan't to create getter, setter or both.

**Comment by rogergl** [comment]
I  would like to implement this feature. Could you give me a tip on how to start ?

**Comment by basarat** [comment]
@rogergl added some docs : https://github.com/TypeStrong/atom-typescript/blob/master/CONTRIBUTING.md#quickfix Let us know if you need any further assistance :rose:

**Comment by rogergl** [comment]
I tink I start with the creation of a simple create read only property fix.  So far my code to check if it is a constructor arg looks likes this:
```javascript
    canProvideFix(info: QuickFixQueryInformation): CanProvideFixResponse {

        if (info.positionNode && info.positionNode.parent &&
            info.positionNode.parent.parent && info.positionNode.parent.parent.symbol &&
            info.positionNode.parent.parent.symbol.name === '__constructor') {

            return { display: "create read only property for " + info.positionNode.parent.symbol.name };
        }

    }
```
Is this ok ?

**Comment by rogergl** [comment]
The basic stuff is working now. But I have problems with indentation:

```javascript
module Test {

    class Test {
        constructor(param1, param2: number) {
        }

    }
}

```
```javascript
class Test2 {
    constructor(param1, param2: number) {
    }
}
```
Applying the quick fix to the last example works but applying it to the first gives

```javascript
        constructor(param1, param2: number) {
                this._param1 = param1;
    }
```
The question is now, what is the best way to go from
```javascript
constructor(param1, param2: number) {
}
```
to
```javascript
 constructor(param1, param2: number) {
     this.param1 = param1;
 }
```

The code looks like this
```javascript
let indentLevel2 = this.createIndent(indentSetting, 2);
let lastBrace = constructorDecl.body.getChildren().filter(x=> x.kind == ts.SyntaxKind.CloseBraceToken)[0];

let newText = `${indentLevel2}this._${symbolName} = ${symbolName};${EOL}`;

return {
    span: {
        start: lastBrace.end - 5,
        length: 0
    },
    newText: newText,
    filePath: filePath
};
```

**Comment by basarat** [comment]
> But I have problems with indentation:

Have a look at : https://github.com/TypeStrong/atom-typescript/blob/fcaab60aa14ee78cae2cd63623b30a9b66c38ba4/lib/main/lang/fixmyts/quickFixes/addClassMember.ts#L105-L108 

TIP add the `EOL` before the new text : https://github.com/TypeStrong/atom-typescript/blob/fcaab60aa14ee78cae2cd63623b30a9b66c38ba4/lib/main/lang/fixmyts/quickFixes/addClassMember.ts#L116

**Comment by basarat** [comment]
Word of warning : Using a custom `getter` / `setter` limits your ability to design a framework that can *create these magical things for MVVM style observation*. 

Also having a `setter` with side effects results in horrible to analyze code. I would recommend against using these.

**Comment by basarat** [comment]
closed by : https://github.com/TypeStrong/atom-typescript/pull/385 :rose:
