### ISSUE TITLE
Support the `exclude` property

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#377]
* Update to latest master
* Support the property 
* Update the default generated tsconfig to be "exclude" only

https://github.com/Microsoft/TypeScript/pull/3188

Need to think about its interaction with `filesGlob`

**Comment by elmariofredo** [comment]
:+1:

**Comment by basarat** [comment]
People have expressed desire to still have `filesGlob` so I'll wait on this for a while

**Comment by nycdotnet** [comment]
It seemed that the only reason the TypeScript team went with exclude is that they didn't want to take a dependency on a glob matcher library.  It would be a shame to lose this great functionality.  I hope filesGlob doesn't have to go away when exclude support is implemented.

**Comment by Cu3PO42** [comment]
I strongly agree with everyone who likes `filesGlob`. Even though `excludes` gives you some of the power, you may want to exclude all TS files in a certain folder and not list them manually. This might be the case if you have copies of a dependency which is subject to change.

**Comment by basarat** [comment]
Updated issue accordingly :rose: `filesGlob` will stay

**Comment by Cu3PO42** [comment]
I'm very glad to hear that :+1:

**Comment by basarat** [comment]
Up for grabs

# Implementor guidance 

Source code needs to go here : [tsconfig.ts](https://github.com/TypeStrong/atom-typescript/blob/1f516fd2061fe2e6dcaea4fbc560024fdd35121d/lib/main/tsconfig/tsconfig.ts)

For guidance one can use the work done [here](https://github.com/TypeStrong/tsconfig/blob/be5007c5505f73810c6510ecbdc166bed4dfe036/src/tsconfig.ts). Basically add the excludes to the pseudo filesGlob.

**Comment by tanguylebarzic** [comment]
@basarat  Please have a look at https://github.com/TypeStrong/atom-typescript/pull/637. I'm happy to work on improving this pull request.

**Comment by basarat** [comment]
closed with #637
