### ISSUE TITLE
Incorrect compiliing

### ISSUE THREAD

**Issue by FalloutPL** [TypeStrong/atom-typescript#380]
Hi,

I use Promises in my project which are fully supported only by compiler flag ```-t ES6```
I also use TS in version ```1.4.1.0``` because ```1.5.x``` is still in beta and do not compile in ```node``` supported javascript.

# tsconfig
```
{
    "version": "1.4.1",
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": true,
        "outDir": "../build"
    },
    "filesGlob": [
        "./**/*.ts",
        "!./node_modules/**/*.ts"
    ],
    "files": [
        "./app.ts",
        "./device.ts",
        "./dispatcher.ts",
        "./index.ts",
        "./server.ts",
        "./users.ts",
        "./virtuals.ts"
    ]
}
```
# My code (ts):
```typescript
class Module {
   public call = (action: string, args: any): Promise<any> => {
        if (this[action] !== undefined) {
            return this[action](args);
        } else {
            return Promise.reject('Not implemented');
        }
    }
 }
```

# TSC compiles to (correct):
```javascript
var Module = (function () {
    function Module() {
        var _this = this;
        this.call = function (action, args) {
            if (_this[action] !== undefined) {
                return _this[action](args);
            }
            else {
                return Promise.reject('Not implemented');
            }
        };
    }
    return Module;
})();
```

Command used:  ```tsc src\device.ts -m commonjs -t ES6```

# atom-typescript compiles to (incorrect):
```javascript
class Module {
    constructor() {
        this.call = (action, args) => {
            if (this[action] !== undefined) {
                return this[action](args);
            }
            else {
                return Promise.reject('Not implemented');
            }
        };
    }
}
```

# Summary;

with TSC 1.4.1 and ES6 atom-typescript shows error to use ```import * as app from 'app'``` which its unsupported by TSC and compiles to unsupported javascript like in Typescript@1.5. Compiled code by atom-typescript should be exactly like TSC.

**Comment by basarat** [comment]
This is by design. If you use typescript `1.5` and compile with `"target": "es6",` you will get the same output that atom-typescript is giving. 

Solution : bring in stuff from es6.d.ts *into your project* and raise your concern here : https://github.com/Microsoft/TypeScript/issues/3211. Thanks :rose:
