### ISSUE TITLE
Getting odd tooltips in grunt-ts

### ISSUE THREAD

**Issue by nycdotnet** [TypeStrong/atom-typescript#381]
I'm currently working on grunt-ts support for TypeScript 1.5 in the update-to-typescript-1.5.0-beta branch.

I'm getting some very odd tooltips in atom-typescript.  Any ideas?  Am I doing something wrong here?

I have atom-typescript 4.5.7.  These screenshots were both taken while compile.ts was open.

![unusualtooltips1](https://cloud.githubusercontent.com/assets/3755379/8022613/7f25bd5e-0cab-11e5-9501-e2e20f23ef11.png)

![unusualtooltips2](https://cloud.githubusercontent.com/assets/3755379/8022614/7f28ecc2-0cab-11e5-9819-18285059d7cc.png)

**Comment by alexwall** [comment]
This is a generic problem, not only for grunt-ts. I'm also on atom-typescript 4.5.7.

**Comment by david-driscoll** [comment]
It appears to be using the buffer rows, not the screen rows.  If you scroll to the top, then you get the correct tooltips.  If you scroll down a line, then you get the tooltip that was there, with the scroll all the way at the top.

**Comment by nycdotnet** [comment]
You're exactly right!

**Comment by david-driscoll** [comment]
And omnisharp-atom is experiencing the same problem, if I fix it over there before it's fixed in atom-typescript I'll share the code fix for it (currently working on something else at the moment)

**Comment by nycdotnet** [comment]
@david-driscoll I think I've fixed this.  Please check out https://github.com/TypeStrong/atom-typescript/issues/384

**Comment by nycdotnet** [comment]
@basarat If you get a chance, I would love it if you'd take a peek at this fix.  I am assuming that GitHub changed something about how the atom works in a recent change, but I wasn't able to see something in the patch notes.  I believe this broke in the past week or so.  I'm willing to chase it down with the Atom folks if you agree it's worth doing.

**Comment by basarat** [comment]
@nycdotnet see : https://github.com/TypeStrong/atom-typescript/pull/384/files#r31981007

**Comment by basarat** [comment]
> I'm willing to chase it down with the Atom folks if you agree it's worth doing.

completely your call :rose:

**Comment by nycdotnet** [comment]
OK.

Also of note... I'm going to start calling it "the atom" from now on.

**Comment by nycdotnet** [comment]
I opened this with the Atom team.

https://github.com/atom/atom/issues/7193

Closing this one for now.
