### ISSUE TITLE
Type hovers unreliable

### ISSUE THREAD

**Issue by JonathanMEdwards** [TypeStrong/atom-typescript#383]
Type hovers are very unreliable for me. They are often incorrect and then seem to almost completely stop working. Are there any tips for how to diagnose this?

**Comment by nycdotnet** [comment]
I think this is a duplicate of #381.  Would you please look at https://github.com/TypeStrong/atom-typescript/pull/384 ?  If you don't mind, I would appreciate you making that change in your local copy of atom-typescript and reloading the editor to see if it's fixed.  If so, I can do a minor release.  Thanks.

**Comment by JonathanMEdwards** [comment]
Yes #384 fixes the problem for me! Thanks

**Comment by nycdotnet** [comment]
Thanks for the report. v4.5.9 includes the fix.
