### ISSUE TITLE
Module keyword always report an error.

### ISSUE THREAD

**Issue by busbina** [TypeStrong/atom-typescript#391]
The module keyword always says it is expecting a ";" after the keyword
![screenshot from 2015-06-13 11 51 01](https://cloud.githubusercontent.com/assets/8128599/8145591/86503e80-11c2-11e5-8911-c9e2de4527be.png)

**Comment by nycdotnet** [comment]
Not sure if you closed this intentionally or not but since one of the betas the TypeScript team changed the keyword to require.  So import mylib = require("somelib"); .

**Comment by busbina** [comment]
I noticed that after I filed it, so I closed it ASAP. I was using some old
documentation.
