### ISSUE TITLE
d.ts file not being generated

### ISSUE THREAD

**Issue by christyharagan** [TypeStrong/atom-typescript#394]
I have two issues (I suspect are related):
 1) I cannot get the d.ts file for my package to generate. 
 2) When I hand craft this file (or use dis-generator) it isn't picked by other packages

For issue 1), I am using atom.io v0.209.0 and atom-typescript v4.5.13
My package.json has the line:

"typescript": {
    "definition": "./definition/typescript-schema.d.ts"
  }

And my tsconfig.json has the line:

"package": "./package.json"

(both files are in the root of the project)

Everything builds fine, except the d.ts file, which isn't built.

For problem 2), when I create this file (I use dts-generator) and output it to the specified location (./definition/typescript-schema.d.ts) and then npm install this project as a dependency, it doesn't seem to be picked up by atom.

Am I doing something wrong, or is this a regression?

**Comment by christyharagan** [comment]
Oh, I should also mention I'm using typescript 1.5-beta

**Comment by nycdotnet** [comment]
Hi Christy.

If you want atom-typescript to generate d.ts files, you need to set `"declaration": true` in the `compilerOptions` section of your tsconfig.json file.

I am not aware of any sort of integration of package.json with TypeScript definition files, nor with tsconfig.json with package.json ([docs here](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json)).  Did you find documentation for that somewhere?  I'm interested to see what prompted you to set that up.

Let me know if that gets the declarations generating and then hopefully we can resolve the references issue.

**Comment by basarat** [comment]
Sorry for the confusion @nycdotnet this is recent feature, so valid bug.

**Comment by basarat** [comment]
> 1. I am using atom.io v0.209.0 and atom-typescript v4.5.13

You don't need to specify `package.json` anymore : https://github.com/TypeStrong/atom-typescript/blob/master/docs/CHANGELOG.md#v3 

BUT : You do need to set `"declaration": true` in the `compilerOptions` section of your tsconfig.json file (I'll document this requirement). 

> 2), when I create this file (I use dts-generator) and output it to the specified location (./definition/typescript-schema.d.ts) and then npm install this project as a dependency, it doesn't seem to be picked up by atom.

Try opening up the console to see if there are any errors : `ctrl+alt+i` will open the dev tools within atom.

**Comment by nycdotnet** [comment]
Doh!  Thanks @basarat and thanks for the report @christyharagan.  You sounded so specific that I figured it was something that I didn't know about, but I wasn't sure how to respond in a helpful manner if it was really something simple.

**Comment by basarat** [comment]
@christyharagan 2 should work now with release `4.5.14`

**Comment by basarat** [comment]
@christyharagan also `definition` cannot be relative so use : `"definition": "typescript-schema.d.ts"`

I've push a commit that documents what's been discussed here https://github.com/TypeStrong/atom-typescript#packagejson-support :rose:  

Also more bug fixes with `4.5.16`. Give it a go.

**Comment by christyharagan** [comment]
Awesome thanks guys. Will check it out when I'm back from work. Atom typescript FTW!
