### ISSUE TITLE
Syntax highlighting fails with optional properties 

### ISSUE THREAD

**Issue by gnomeontherun** [TypeStrong/atom-typescript#395]
Declaring an optional property in an interface breaks the syntax highlighting. For example, the `url?: string` highlighting stays white, but if you remove the `?` it will highlight the type properly.

```typescript
interface Options {
    url?: string
}
```
vs.

```typescript
interface Options {
    url: string
}
```

**Comment by basarat** [comment]
`v4.5.15` :rose:
