### ISSUE TITLE
Disable a popup message on successful compilation

### ISSUE THREAD

**Issue by helarqjsc** [TypeStrong/atom-typescript#397]
It would be nice to have an option to disable this message, it seems a bit annoying to me. I mean, just the message that says "TS emit succeeded" should be possible to disable. It's nice to have a popup when you have a typo somewhere in your code, but when everything goes well, I would like the plugin to do its job silently. Showing a popup every time saving goes successfully isn't very useful. Can such an option be added to this plugin?

The message I'm talking about:
![Screenshot](http://i.imgur.com/pv2wdGb.png "Screenshot")

**Comment by basarat** [comment]
> Can such an option be added to this plugin?

I would prefer a better *UI* for this. Basically I imagine a small icon on the screen that shows the status of the `js` (different, old, up to date)

**Comment by helarqjsc** [comment]
How would it know if the js file is old or up to date after you have just opened the editor?

**Comment by basarat** [comment]
> How would it know if the js file is old or up to date after you have just opened the editor?

good question. It can assume *not* to begin with ... or it can send an initial *compile* command right after initial load (its async and in the background anyways)  ... or something else

**Comment by basarat** [comment]
closed with #415
