### ISSUE TITLE
Missing Uint8ClampedArray type!

### ISSUE THREAD

**Issue by GoToLoop** [TypeStrong/atom-typescript#400]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray

The other unsigned typed arrays (Uint8Array, Uint16Array & Uint32Array) were readily available.
Sorry in advance if it's something internal to TS compiler and not Atom-TS plugin.

**Comment by basarat** [comment]
> Sorry in advance if it's something internal to TS compiler and not Atom-TS plugin.

Belongs on [Microsoft/TypeScript](https://github.com/Microsoft/TypeScript/issues). 

This is an issue with the contents of a file `lib.d.ts` That comes from microsoft :rose:
