### ISSUE TITLE
noEmit compilerOption not supported

### ISSUE THREAD

**Issue by henrjk** [TypeStrong/atom-typescript#402]
I have a project with an existing grunt workflow and I'd like to add the conversion from TypeScript to JavaScript using grunt-ts. This should also allow folks who do not use atom-typescript to have a watcher task generate the JavaScript code.

Of course I'd like to also allow usage of all the cool features while editing ts with atom-typescript. To avoid friction I wanted to switch of JavaScript code generation by adding the noEmit compiler option to the tsconfig.json file. 

```JSON
{
    "version": "1.5.0-alpha",
    "compilerOptions": {
        "noImplicitAny": false,
        "noEmit": true,

``` 

However I am getting an error which comes from atom-typescript at [this line](https://github.com/TypeStrong/atom-typescript/blob/61b2a12e9ca61c6174d20481536b36d8cdf530ea/lib/main/tsconfig/tsconfig.ts#L50).

The related schema can be found at http://json.schemastore.org/tsconfig which is linked from https://github.com/Microsoft/TypeScript/wiki/tsconfig.json.

Could this be added easily that is by simply changing the validation or are deeper reasons why atom-linter should generate the JavaScript?

On the hand it might be even better if this option could be enabled in an atom-typescript specific configuration file in the project, so that the grunt-ts can use the same tsconfig.json file.

**Comment by basarat** [comment]
> Could this be added easily that is by simply changing the validation or are deeper reasons why atom-linter should generate the JavaScript?

Nope. Just didn't come across it. Pushed with `4.6.2` but haven't tested. 

FWIW you probably want https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#compileonsave  Setting it on `tsconfig.json` will disable it for `tsc` command line tool as well and you probably don't want that.

:rose:

**Comment by henrjk** [comment]
Thank you!
