### ISSUE TITLE
Add experimentalDecorators to CompilerOptions

### ISSUE THREAD

**Issue by Mig1st4ck** [TypeStrong/atom-typescript#404]
ntypescript already support this. 

So adding experimentalDecorators we can use decorators.

**Comment by basarat** [comment]
Sorry I missed the memo : https://github.com/Microsoft/TypeScript/pull/3330 

Resolving soon :rose: Thanks for spotting this :+1:

**Comment by basarat** [comment]
published with `v4.6.3`
