### ISSUE TITLE
The new error view does not show line and column, not allowing to click on the error.

### ISSUE THREAD

**Issue by tomitrescak** [TypeStrong/atom-typescript#408]
See the screenshot.
The TsLint warnings are shown correctly.

![screen shot 2015-06-25 at 13 40 06](https://cloud.githubusercontent.com/assets/2682705/8346428/c080f49c-1b3f-11e5-9695-ec9535f34347.png)

**Comment by tomitrescak** [comment]
Not your issue, but the one of tslint.

**Comment by tomitrescak** [comment]
Well, linter people blame this on the provider in AtomLinter/Linter#611, so I'm reopening this issue here. Would be nice to have it working.

**Comment by basarat** [comment]
for my reference https://github.com/TypeStrong/atom-typescript/commit/cfa9fed0626766dcad0dc5fce7b4c40eba1d0a54
