### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by rnikitin** [TypeStrong/atom-typescript#41]
Blank document, even not saved yet. I've just changed filetype from bottom right corner menu.

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v0.18.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At /Users/rnikitin/.atom/packages/atom-typescript/lib/linter.js:27

TypeError: Cannot read property 'path' of null
  at LinterTslint.lintFile (/Users/rnikitin/.atom/packages/atom-typescript/lib/linter.js:27:43)
  at /Users/rnikitin/.atom/packages/linter/lib/linter-view.coffee:139:18
  at Array.forEach (native)
  at /Users/rnikitin/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
     -0:03.1 grammar-selector:show (atom-text-editor.editor)
     -0:00.7 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "typescript-atomizer"
    ],
    "themes": [
      "atom-dark-ui",
      "visual-studio-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v0.18.0
autocomplete-plus, v2.0.3
linter, v0.10.1
visual-studio-dark-syntax, v0.1.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by basarat** [comment]
Thanks for the report! 

This is very similar to https://github.com/TypeStrong/atom-typescript/issues/37. Basically we only work on files that are `persisted to disk`. Otherwise the context e.g. `require('./foo')` is completely unclear. I've fixed the error. 

Published as `v0.19.0`.  `apm update typescript` ;)

Working on showing a notification to the user that the file needs to be on disk.

**Comment by rnikitin** [comment]
Oh man, that was fastest issue closing & realising I've ever seen, even I noticed about bugfix from atom new updates notifier.

Thx!

**Comment by nycdotnet** [comment]
Atom-Basarat fixes issues that aren't even committed to disk yet...

**Comment by basarat** [comment]
:heart:
