### ISSUE TITLE
Use `trace` for certain errors to link people to definitions

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#412]
See https://github.com/AtomLinter/Linter/issues/587#issuecomment-115070888 for an example.

Tip: Code needs to go into `linter.ts` file.

**Comment by helarqjsc** [comment]
Any ideas on how to differentiate between the errors that should show trace and the ones that shouldn't?

**Comment by basarat** [comment]
> Any ideas on how to differentiate between the errors that should show trace and the ones that shouldn't?

It is more work than I anticipated on first look. Honestly, one would need to start with one simple error like `foo.bar` where `bar` does not exist on `foo` and then link the user back to the definition for `foo`
