### ISSUE TITLE
Integrate with the linter's error panel

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#413]
This came new with the `linter-plus` package. We should integrate with their "current file" and "project" error panels and then remove ours ("errors in file" at the very least).
# Things to consider:
- Quick cycle through errors _f8_ and _shift+f8_ : linter already does have support for a similar feature with different shortcuts. 
- Code preview for error locations are not shown in the linter
# Code changes:
- Trigger a linter refresh : We already have code for triggering it ... but now we need to trigger it at the _right times_ (e.g. tab change).
- Update documentation `readme.md`
- Update quick switch panel and remove `errors in file feature`
- Update main panel and remove that code
- Update history panel and remove that code

**Comment by austincummings** [comment]
:+1:

**Comment by DanielJoyce** [comment]
Also the errors shown are usually erroneous or out of date, especially if you type fast. Right now its just about useless. It even shows the text in error backs sometime, and emits multiple spurious errors

I see text like this all the time

";" expected
rav <== 'var' backwards
";" expected
wen   <== 'new' backwards
...

**Comment by basarat** [comment]
> Also the errors shown are usually erroneous or out of date, especially if you type fas

our panel or the linter panel?

**Comment by DanielJoyce** [comment]
The atom-typescript panel, but it seems 6.0.1 fixed it

AFAIK the plugin isn't using the atom linter panel yet, unless a config setting has been added

**Comment by basarat** [comment]
> AFAIK the plugin isn't using the atom linter panel yet,

We integrate with the atom `linter` as well. We have *both* at the moment....hence I asked the question. Thanks for the clarification :rose:

**Comment by DanielJoyce** [comment]
Then how do you turn the other on? Didn't see it in settings...


On Wed, Sep 2, 2015 at 9:24 PM Basarat Ali Syed <notifications@github.com>
wrote:

> AFAIK the plugin isn't using the atom linter panel yet,
>
> We integrate with the atom linter as well. We have *both* at the
> moment....hence I asked the question. Thanks for the clarification [image:
> :rose:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TypeStrong/atom-typescript/issues/413#issuecomment-137327039>
> .
>
-- 
Daniel Joyce

The meek shall inherit the Earth, for the brave will be among the stars.

**Comment by basarat** [comment]
> Then how do you turn the other on

Here are both the panels: they should both be showing

![image](https://cloud.githubusercontent.com/assets/874898/9650732/74b106aa-524a-11e5-98a6-8cb3a5dda09b.png)

**Comment by blakeembrey** [comment]
@basarat This would be an awesome addition :+1: Let me know if there's anything needed to close this off on either side - I've been doing a bit of work to improve the linter visually using TypeScript as the example (since the errors are quite large).

**Comment by DanielJoyce** [comment]
I'm getting errors in the atom-typescript panel, but they never show in the
atom linter panel.

On Tue, Oct 6, 2015 at 5:09 PM Blake Embrey <notifications@github.com>
wrote:

> @basarat <https://github.com/basarat> This would be an awesome addition [image:
> :+1:] Let me know if there's anything needed to close this off on either
> side - I've been doing a bit of work to improve the linter visually using
> TypeScript as the example (since the errors are quite large).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TypeStrong/atom-typescript/issues/413#issuecomment-146040441>
> .
>
-- 
Daniel Joyce

The meek shall inherit the Earth, for the brave will be among the stars.

**Comment by ciesielskico** [comment]
Is there any way to remove the bottom panel? 
I just switched from VS Code to Atom and love everything, but the blue shiny 'Errors in Open files' just kills it for me. I've been looking everywhere.

**Comment by FallingSnow** [comment]
I also have 2 error panels now. Can you give us the option to disable the integrated one.

P.S. as above, the teal button kills my theme lol
