### ISSUE TITLE
Uncaught Error: Project file already exists

### ISSUE THREAD

**Issue by NoelAbrahams** [TypeStrong/atom-typescript#43]
Open a new .ts file and start typing.

**Atom Version**: 0.176.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v0.22.0

### Stack Trace

Uncaught Error: Project file already exists

```
At c:\Users\Noel\.atom\packages\atom-typescript\lib\main\tsconfig\tsconfig.js:112

Error: Project file already exists
  at Object.createProjectRootSync (c:\Users\Noel\.atom\packages\atom-typescript\lib\main\tsconfig\tsconfig.js:112:15)
  at getOrCreateProject (c:\Users\Noel\.atom\packages\atom-typescript\lib\main\lang\programManager.js:108:25)
  at Object.getOrCreateProgram (c:\Users\Noel\.atom\packages\atom-typescript\lib\main\lang\programManager.js:117:27)
  at Object.provider.requestHandler (c:\Users\Noel\.atom\packages\atom-typescript\lib\main\atom\autoCompleteProvider.js:23:38)
  at c:\Users\Noel\.atom\packages\autocomplete-plus\lib\autocomplete-manager.coffee:117:39
  at Array.map (native)
  at AutocompleteManager.module.exports.AutocompleteManager.scatterRequest (c:\Users\Noel\.atom\packages\autocomplete-plus\lib\autocomplete-manager.coffee:116:27)
  at AutocompleteManager.scatterRequest (c:\Users\Noel\.atom\packages\autocomplete-plus\lib\autocomplete-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.runAutocompletion (c:\Users\Noel\.atom\packages\autocomplete-plus\lib\autocomplete-manager.coffee:111:6)
  at c:\Users\Noel\.atom\packages\autocomplete-plus\lib\autocomplete-manager.coffee:1:1

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-typescript, v0.22.0
autocomplete-plus, v2.0.6
linter, v0.10.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by basarat** [comment]
@NoelAbrahams I am having trouble reproducing this. This is the code that is raising it

https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/tsconfig/tsconfig.ts#L205-L206

You can press `ctrl+alt+i` to open debug tools in atom : 

![image](https://cloud.githubusercontent.com/assets/874898/5994292/430fa330-aac1-11e4-8f0c-9d2ddeec4c10.png)

Can you log out `srcFile` (modify the code and add `console.log`)

**Comment by NoelAbrahams** [comment]
@basarat, here are some more details.

Assume I have a file `c:\test\foo.ts` that I have opened in atom. The atom-typescript code creates a `tsconfig.json` in directory `c:\test`. This causing the error in line 111 in `tsconfig.js`:

```JavaScript
    if (fs.existsSync(projectFilePath))  // projectFilePath = 'tsconfig.json'
        throw new Error('Project file already exists');
```

I guess the problem is that when you want to open a random file, we don't really want to create a `tsconfig.json` in that directory.

**Comment by basarat** [comment]
> The atom-typescript code creates a tsconfig.json in directory c:\test. This causing the error in line 111 in tsconfig.js the second time round:

It shouldn't hit it the second time around. I've just tested i.e. create a file `foo.ts` in `c:\test

![image](https://cloud.githubusercontent.com/assets/874898/6010319/6ec8f502-ab85-11e4-8e25-ab1624ea9424.png)

Open with atom

![image](https://cloud.githubusercontent.com/assets/874898/6010331/8447d6dc-ab85-11e4-98ab-3302841b6650.png)

It just works. 

> I guess the problem is that when you want to open a random file, we don't really want to create a tsconfig.json in that directory.

I'm considering it : https://github.com/TypeStrong/atom-typescript/issues/44 the thing is I want to push people into using `tsconfig.json`

**Comment by NoelAbrahams** [comment]
@basarat,

In `glob.js` line 402:

```JavaScript
      s.forEach(function (gsPattern) {
        this._process(gsPattern, depth + 1, index, function (er) {
          if (errState) return
          if (er) return cb(errState = er)
          if (--l <= 0) return cb()
        })
      }, this)
```

There are attempts to read hidden system files such as `$RECYCLE.BIN` or `System Volume Information`. It's possible that this is the problem.

**Comment by basarat** [comment]
> There are attempts to read hidden system files such as $RECYCLE.BIN or System Volume Information. It's possible that this is the problem.

Possibly. This would mean that `getOrCreateProject` https://github.com/TypeStrong/atom-typescript/blob/37a844f9870d5af9d9ab570a018593a04f6998e3/lib/main/lang/programManager.ts#L133-L140 would fail to read the project file and try to create it again : https://github.com/TypeStrong/atom-typescript/blob/37a844f9870d5af9d9ab570a018593a04f6998e3/lib/main/lang/programManager.ts#L138 

We should make the `catch` be explicit to only the case `No Project Found` : https://github.com/TypeStrong/atom-typescript/blob/37a844f9870d5af9d9ab570a018593a04f6998e3/lib/main/tsconfig/tsconfig.ts#L147

**Comment by basarat** [comment]
> There are attempts to read hidden system files such as $RECYCLE.BIN or System Volume Information. It's possible that this is the problem.

@NoelAbrahams If it was then we will now give a better error : https://github.com/TypeStrong/atom-typescript/commit/8ccd0e264108b3429d41a4885b31425cbf6fe8eb#diff-95504d2972e1db5e1e25a0156f5841f8R138 i.e. not error on (a bad) create project but error on `getProject`.  Can you try the latest version of `atom-typescript` i.e. `v0.24.0`.

**Comment by NoelAbrahams** [comment]
Here's the stack from `v0.26.0`

```
Error: Project file already exists
  at Object.createProjectRootSync (C:\Users\Noel\.atom\packages\atom-typescript\lib\main\tsconfig\tsconfig.js:119:15)
  at getOrCreateProject (C:\Users\Noel\.atom\packages\atom-typescript\lib\main\lang\programManager.js:112:29)
  at getOrCreateProgram (C:\Users\Noel\.atom\packages\atom-typescript\lib\main\lang\programManager.js:122:27)
  at getErrorsForFile (C:\Users\Noel\.atom\packages\atom-typescript\lib\main\lang\programManager.js:148:19)
  at Object.getErrorsForFileFiltered (C:\Users\Noel\.atom\packages\atom-typescript\lib\main\lang\programManager.js:158:12)
  at LinterTslint.lintFile (C:\Users\Noel\.atom\packages\atom-typescript\lib\linter.js:35:37)
  at C:\Users\Noel\.atom\packages\linter\lib\linter-view.coffee:150:18
  at Array.forEach (native)
  at C:\Users\Noel\.atom\packages\linter\lib\linter-view.coffee:149:18
  at FSReqWrap.oncomplete (fs.js:100:15)
```

The editor works fine in other directories. It's not a real problem.

**Comment by basarat** [comment]
@NoelAbrahams can you try it now after updating atom-typescript. Should be fixed since `v0.53.0`

**Comment by NoelAbrahams** [comment]
Appears to have been fixed :+1:

**Comment by basarat** [comment]
thanks for testing :heart:
