### ISSUE TITLE
Snippets don't work in TS files

### ISSUE THREAD

**Issue by helarqjsc** [TypeStrong/atom-typescript#433]
I have the following code in `snipets.cson`:
```
'.source.ts':
  'Console log':
    'prefix': 'cc'
    'body': 'console.log($1);'
```
But it doesn't work when I type `cc` in any open TypeScript files. How can I fix or troubleshoot it?
Also, the exact same code works fine in `.source.js`. None of the snippets I tested work in TS.

**Comment by basarat** [comment]
I just tested that and it works:


![snippets](https://cloud.githubusercontent.com/assets/874898/8490343/61f8ca18-216a-11e5-8245-cf548b7c8ac8.gif)

Note that you might need to press `esc` to dismiss autocomplete as I've done in this demo :rose:

**Comment by helarqjsc** [comment]
Oh, right. The problem is that autocomplete interferes with the snippets system. The only way I can use snippets inside TypeScript files is doing something like `cc<Esc><Tab>` every time, which isn't convenient at all. Can we fix this? Is this autocomplete window part of `atom-typescript` or it's a built-in Atom thing? If it's the former, maybe snippets can be integrated into autocomplete window somehow?

**Comment by helarqjsc** [comment]
Posted it to atom/autocomplete-plus#522, maybe they will help to find a proper solution to it.
