### ISSUE TITLE
Autocomplete window and linter error window overlap

### ISSUE THREAD

**Issue by helarqjsc** [TypeStrong/atom-typescript#434]
Here's a gif that demonstrates the problem:
![Gif that demonstrates the problem](http://g.recordit.co/FA3flolUo9.gif)

**Comment by basarat** [comment]
Agreed. The autocomplete team worked hard to make sure that it shows *above* the linter. If you want to see the error you can always dismiss the autocomplete with `esc` and if you want to see it again *retrigger* it using `ctrl+space`. 

Closing as we don't manage linter or autocomplete-plus packages :rose:
