### ISSUE TITLE
[question] Which prerequisits do I need to get dependency view to work

### ISSUE THREAD

**Issue by GregOnNet** [TypeStrong/atom-typescript#443]
Hi,

I want to analyze our TypeScript app with the [dependency view](https://github.com/TypeStrong/atom-typescript/#dependency-view).
When I type `dependency view` in the command console (`STRG` + `SHIFT` + `P`) nothing happens.

Can you provide me some information if I have to do some setup to get the  [dependency view](https://github.com/TypeStrong/atom-typescript/#dependency-view) to work?

Kinds
Gregor

**Comment by basarat** [comment]
> Can you provide me some information if I have to do some setup to get the dependency view to work?

You need to use external modules aka. file modules. 

Documented this as well: https://github.com/TypeStrong/atom-typescript/commit/872c59ba195ac95423b33df6d9b60c7ef6ff056d 

Feel free to ask further clarifications.

**Comment by GregOnNet** [comment]
Thank you very much!

**Comment by pitjow** [comment]
Hi basarat,

Thanks for your info, but I still do not know what "file modules" these are. It seems to be no atom package, so where can I get them?

Kinds

**Comment by basarat** [comment]
@pitjow it's covered in this chapter 🌹 https://basarat.gitbooks.io/typescript/content/docs/project/project.html
