### ISSUE TITLE
Persistent display of errors after successful TypeScript compilation

### ISSUE THREAD

**Issue by cosinekitty** [TypeStrong/atom-typescript#444]
I have noticed that atom-typescript (versions 5.0.12(?) through 5.0.16) continues to nag me with syntax errors that I have already fixed, saved, and successfully compiled.  Below is an example screen shot showing where I have corrected the syntax error, pressed Ctrl+S to save, and pressed F6 to verify the build.

The error messages persist as I keep typing, showing both in the "Errors in Open Files" pane at the bottom and inline in my source code.  To get rid of the errors, I have to save the file, then make a "safe" change like pressing the space bar after the semicolon.

I would think that the instant there is a successful compile, all errors should be erased.

![atom-typescript-persistent-errors](https://cloud.githubusercontent.com/assets/11699954/8552682/9dcb831a-24ac-11e5-82a8-95d2f703a820.png)

**Comment by basarat** [comment]
This is a bug in linter that has been reported and actually fixed in master : https://github.com/AtomLinter/Linter/issues/707 sorry for the inconvinience 

Our own error panel is the source of truth in the meanwhile

**Comment by steelbrain** [comment]
A release has been published, so You can just close this one.

**Comment by basarat** [comment]
:rose:

**Comment by cosinekitty** [comment]
Thanks for steering this, @basarat .  It is MUCH better after upgrading.  It's not 100% fixed; I had one case where the same thing happened, but I haven't figured out how to repro yet.  When/if I do, where should I report it, here, or create a new issue for the linter?

**Comment by basarat** [comment]
New issue here please.
