### ISSUE TITLE
Typescript Plugin Reload

### ISSUE THREAD

**Issue by n2westman** [TypeStrong/atom-typescript#447]
Switching git branches doesn't prompt a reload of atom-typescript

After switching between branches, compilation errors will appear because of inconsistent state. I need to close and re-open atom for these errors to go away.

**Comment by basarat** [comment]
> I need to close and re-open atom for these errors to go away.

You don't need to reopen atom. Just sync : https://github.com/TypeStrong/atom-typescript#sync Also faq : https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#atom-typescript-is-complaining-about-not-finding-files-or-other-weird-errors

I experimented with file watchers. None of them performed well enough or reliably and sync is fast enough.

**Comment by n2westman** [comment]
Missed that! Thanks!
