### ISSUE TITLE
Implement hyperclick package

### ISSUE THREAD

**Issue by park9140** [TypeStrong/atom-typescript#448]
Part of Nuclide is the hyperclick package, https://atom.io/packages/hyperclick, it allows for interacting with text in the editor while holding the alt key, via a service.  

Some thoughts of things we could implement with this.
- Jump to definition.
- allow quick fixes to define syntax errors they are associated with
  - for example quick fix to implement an interface could be attached to the, the syntax error for a interface not being implemented.

**Comment by adidahiya** [comment]
+1 this would be awesome!

**Comment by littleStudent** [comment]
Is anyone working on this? would love to see this feature added to atom-typescript.
Never did atom package development, would be a lot work for me to get into this stuff.

**Comment by basarat** [comment]
> Is anyone working on this?

Nope :rose:

**Comment by cevek** [comment]
+1

**Comment by marcoskichel** [comment]
+1

**Comment by markvandenbrink** [comment]
This is very nice, but there is a problem using the `ctrl`-key, since this key is used to make multiple selections/use multiple text cursors in Atom (which is very useful). Maybe it is better to use the `alt`-key as described in the readme of hyperclick:

> - `<alt>` or `<alt-mousemove>` underlines clickable text under the mouse.
> - `<alt-mousedown>` performs the action associated with the clickable text.
> - `<cmd-alt-enter>` performs the action on the text under the cursor.

**Comment by wingyplus** [comment]
@markogresak Atom Typescript implement hyperclick provider for jump to declaration since version 10.0.1 . You can use `alt` key that hyperclick mapped.

**Comment by markvandenbrink** [comment]
It seems the ctrl-key is mapped on Windows instead of the alt-key. Submitted a PR to change this behavior: https://github.com/facebook/nuclide/pull/612

**Comment by tlaverdure** [comment]
I agree with @markvandenbrink about the keymap issue. I'm used to using **cmd + click** to make multiple selections. 

Is this also only supposed to work with typescript files? Seem to see the white hyperclick underline in every file type I'm in when holding down **cmd** which makes this feature buggy.

**Comment by robofish** [comment]
If i'm not mistaken, the integration is gone again with atom typescript v11? 😅

**Comment by guncha** [comment]
@robofish, it sure is. Command+click is also used to place multiple cursors and if hyperclick is only used for jumping to the definition, I didn't see the point in keeping it since clicking on the symbol and pressing F12 is very close, though I agree that switching from the mouse to the keyboard is not perfect. I might be convinced that it make sense to use with quickfixes though.

**Comment by andrewstart** [comment]
Hyperclick added an option to change which modifier(s) is used, so that it doesn't have to interfere with multiple cursors. I'd also ask that the integration be added back.

**Comment by sverrejoh** [comment]
I implemented this and made a pull request, which you can test if you want: https://github.com/TypeStrong/atom-typescript/pull/1265
