### ISSUE TITLE
for.. of grammar issue

### ISSUE THREAD

**Issue by avarices** [TypeStrong/atom-typescript#451]
ES6 added `for of` loops for arrays, but it seems when you use `of` instead of `in`, the highlighting for the scope is removed.

Self testing example 

```javascript
class Test {
    constructor() {
    }
    breaker() {
      let example_array = [[0, 1], [0, 2]]
      for (let [index, position] of example_array) {
          // all grammar in here seems to be gray
          let position_plus_one = position + 1
          console.log(position_plus_one)
      }
    }
}
```

Here is what it looks with `of`
![for_of_loss_of_highlighting]
(http://i.imgur.com/dxFOxcB.png)

And with `in` instead of `of`
![working_with_in]
(http://i.imgur.com/pJQUaFq.png)

The second example was just me testing if the issue was just the `of` keyword, seems to look that way. Extensive testing was not done.

**Comment by adidahiya** [comment]
+1, I'm seeing this issue as well.

Interestingly enough, if you introduce any block scope _within_ a for-of loop's scope, syntax highlighting seems to resume working after the nested block.

![image](https://cloud.githubusercontent.com/assets/723999/8611426/cf443d54-268e-11e5-9b44-685a8443b603.png)

**Comment by Cu3PO42** [comment]
What is happening here is that the variable declaration basically consumes the entire scope, because it doesn't end on the `of` as it does on the `in`. Unfortunately I forgot about ES6 introducing those. I will get this fixed.
