### ISSUE TITLE
[Bug] Not autocompleting full path to *.d.ts path: Ignores .ts

### ISSUE THREAD

**Issue by icereed** [TypeStrong/atom-typescript#454]
Hi folks,

I encountered some minor bug.
When Atom makes suggestions for type definition files (.d.ts) the file ending .ts is missing.
Here a little screen cast:

![image](http://g.recordit.co/FpmIuouVFA.gif)

I am running Atom V1.0.2 and atom-typescript version 5.0.19 on Windows 8.1.

Regards,
Icereed

**Comment by basarat** [comment]
`v5.0.22` :rose:

**Comment by icereed** [comment]
Thanks a lot for the quick fix! :rose: back :)
