### ISSUE TITLE
Formatting doesn't work for .tsx jsx code

### ISSUE THREAD

**Issue by manishtpatel** [TypeStrong/atom-typescript#458]
Title says it all

JSX code is not getting formatted correctly, it removes all indentations only. makes formatting unusable for tsx files.

**Comment by basarat** [comment]
If you don't mind would be good to have this issue on https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+jsx along with examples of how you imagine it to be :rose:

**Comment by basarat** [comment]
Seems to be working better now.

Closing as its relevant for tracking in Microsoft/TypeScript and not just this plugin :rose:

**Comment by snowcxt** [comment]
updated to 7.5.0. It seems that it doesn't work at all (not just incorrectly).

**Comment by snowcxt** [comment]
Also tsx files can't figure out the import-require path and no underline anymore.

![image](https://cloud.githubusercontent.com/assets/1463415/10681809/13e26a26-78e2-11e5-92c7-6889ccff40e5.png)

**Comment by basarat** [comment]
* The scope renames from `.ts.tsx`  to just `.tsx` broke the formatting (basically keybindings broke). 
* still need to look at `import-require` 

Expect a fix today :rose:

**Comment by blakeembrey** [comment]
Sorry! Thanks so much :+1:

**Comment by basarat** [comment]
Fixed with https://github.com/TypeStrong/atom-typescript/releases/tag/v7.5.1 :rose:

**Comment by snowcxt** [comment]
Works now. Thanks so much :+1:
