### ISSUE TITLE
Object.activate is deprecated.

### ISSUE THREAD

**Issue by prabhatsharma** [TypeStrong/atom-typescript#461]
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
```
Object.activate (/home/prabhat/.atom/packages/linter/lib/main.coffee:57:8)
Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:240:19)
<unknown> (/usr/share/atom/resources/app.asar/src/package.js:221:30)
Package.measure (/usr/share/atom/resources/app.asar/src/package.js:165:15)
Package.activate (/usr/share/atom/resources/app.asar/src/package.js:213:14)
PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:452:21)
```

**Comment by basarat** [comment]
> AtomLinter v0.

We are already `v1.0`. Perhaps this error is from another package. See : https://github.com/TypeStrong/atom-typescript/blob/master/package.json#L20-L24

:rose:
