### ISSUE TITLE
Show class member overrides indicator in the left margin

### ISSUE THREAD

**Issue by markvandenbrink** [TypeStrong/atom-typescript#464]
First of all thanks for all the hard work on Atom TypeScript! I've switched from Webstorm to Atom and like to suggest the following feature which is available in Webstorm:

Show an icon/indicator in the left margin of the code view for class members which are an override or members who have overrides elsewhere. In webstorm you can hover this indicator and even see where these overrides are (and jump to it). Also the classes who are extended are indicated. This really helps in large projects with complex class dependencies.

Example:
![class-overrides](https://cloud.githubusercontent.com/assets/7869636/8673481/21652c96-2a37-11e5-9d4b-661cc82d0dfa.jpg)

**Comment by basarat** [comment]
Good feature request. We do not have infrastructure for something like this at the moment. 

TIP for potential implementer: For starters the "error reporting for current file" infrastructure *code locations* can be used to hook in "get semantic information for file"
