### ISSUE TITLE
"No project file found" error for .json files

### ISSUE THREAD

**Issue by adidahiya** [TypeStrong/atom-typescript#468]
I'm seeing errors like this for .json and .js files in my project:

![image](https://cloud.githubusercontent.com/assets/723999/8702964/d7b70f08-2ae8-11e5-8ac9-ea6029f5cb42.png)

When I click on that error to go to the file that triggered it, Atom opens up many copies of the .json file:

![image](https://cloud.githubusercontent.com/assets/723999/8703077/6530183e-2ae9-11e5-9c0c-b5f714c7b0d2.png)

No errors or logs in the console during that operation.

I'm using atom-typescript v5.0.28

**Comment by basarat** [comment]
> I'm seeing errors like this for .json and .js files in my project

Is it after you *just opened atom* and it restored open windows?

> Atom opens up many copies of the .json file

We've seen this. The atom's file open api is *only called once* but sometimes it opens the file a dozen times (other tools that use the open api e.g linter suffer the same problem). We don't have a good repro so we haven't reported it to atom/atom yet.

**Comment by adidahiya** [comment]
Yeah, this only seems to happen when restoring open windows.

**Comment by basarat** [comment]
> this only seems to happen when restoring open windows.

Cool. Then we have a potential *race condition* based bug. Marking it up for grabs for investigation by any hero. Code is in `atomts.ts` < needs simplification at some point

**Comment by giladgray** [comment]
+1 seeing this when I open a folder in a new window, which may or not involve restoring open windows. Either way it's the primary way in which I use Atom.
