### ISSUE TITLE
add a "show documentation" shorcut

### ISSUE THREAD

**Issue by nahuel** [TypeStrong/atom-typescript#470]
It will be nice to press a key over a method/fun and get his complete documentation opened in another pane. For example, you press F1 with the cursor over `abs(222)` and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/abs  is opened.

**Comment by basarat** [comment]
Sounds reasonable. 

Tip for implementer : Basically one would need to call get definition and then if definition is in `lib.d.ts` and of a specific global `Math` or `String` or _others_ they would open the MDN reference.
