### ISSUE TITLE
version 5.0.29 not working

### ISSUE THREAD

**Issue by michAtEl** [TypeStrong/atom-typescript#471]
Hi,

i recently updated to version 5.0.29. After the update, atom-typescript doesn't work any more.
When I enable atom-typescript I get the message "AtomTS: Dependencies installed correctly. Enjoy TypeScript"
Then I open a project and press F6 to compile but nothing happens. A tsconfig.json already exists and worked with the version of atom-typescript, that was installed before.

I already uninstalled atom.io an deleted the folder .atom before installing atom.io again. This did not help.

Do you need more information about this problem?

Thank you for developping atom-typescript and for your support
Michael

**Comment by basarat** [comment]
Sorry to hear this, can you repro on a new project?

* create a `.ts` file in a new folder (`c:\new\test.ts`)
* create a `tsconfig.json` with contents `{}` in the same folder.

Does atom-typescript work with this `.ts` file now?

**Comment by michAtEl** [comment]
I tried your suggestions but atom typescript did not work.

Then I had a look at the developer Console:
... Error: cannot find Atom package linter ...

I installed the Atom packate linter and Typescript works fine!
I just wonder why linter has not been installed by atom automatically. I suppose, there is a dependency System in Atom?

Thanks for your support
Michael

**Comment by vaughnroyko** [comment]
Getting this same issue. It does seem to be Linter related as @michAtEl suggests. Unlike @michAtEl though, I already have the linter installed and working. Here's what my console says though when I load up a .ts file:

![image](https://cloud.githubusercontent.com/assets/2846662/8753565/9b67e830-2c71-11e5-932a-36291ec51926.png)

**Comment by basarat** [comment]
> I just wonder why linter has not been installed by atom automatically. I suppose, there is a dependency System in Atom

We have custom code to do this. That code needs a bit of cleanup. I'll do that soon. Thanks :rose:

**Comment by basarat** [comment]
Closing as haven't found a repro for this and the people facing this have resolved it themselves.
