### ISSUE TITLE
Few questions.

### ISSUE THREAD

**Issue by nripendra** [TypeStrong/atom-typescript#473]
How to bundle the generated js? Is that something atom-typescript can do?

Is there a way to make atom-typescript detect node.js modules?
I'm using reactjs, but it gives me error **'cannot find module react'** on line 
```js
import React, { Component } from 'react';
```

I can see something like lightbulb when I click on error, does it work like light bulb functionality in visualstudio? If so how to invoke?

**Comment by nycdotnet** [comment]
Atom-typescript leaves bundling to external build tools.

The issue you're having with react is likely because you don't have the definition file downloaded.  TypeScript needs definition files to work with regular JS libraries that aren't in TypeScript.  Check out http://definitelytyped.org to see how to do that.

**Comment by basarat** [comment]
> I can see something like lightbulb when I click on error, does it work like light bulb functionality in visualstudio? If so how to invoke

`alt+enter` : https://github.com/TypeStrong/atom-typescript/blob/master/docs/quickfix.md However a quickfix for `'cannot find module react'` does not exist so you need to download the definitions from DT manually. Recommend `tsd install react react-jsx -soa`

**Comment by nripendra** [comment]
Thank you guys for awesome reply, now I'm able to get react to work without that nasty error :)

So, what I'm thinking right now is, the way atom-typescript currently works messes up my source folder, can it at least be configured to generate all d.ts and .js file in some preconfigured location?

The problem I'm facing is: Let's I have say a react component named Login.tsx, for each such component I'll have 2 extra files Login.d.ts and Login.js. When I have say just 4-5 such components the folder already looks quite crowded with all those extra files.

Each time I want to open a component I need to give some attention to focus on correct extension, which I find is unnecessary mental shift when working for long hours in large projects.

Regards,
Nripendra

**Comment by basarat** [comment]
>  currently works messes up my source folder, can it at least be configured to generate all d.ts and .js file in some preconfigured location?

Use `outDir` option in your `tsconfig.json`'s `compilerOptions` :rose:

**Comment by nripendra** [comment]
Thanks! worked like charm :)
