### ISSUE TITLE
autocomplete - no indication for optional properties

### ISSUE THREAD

**Issue by eliorcohen** [TypeStrong/atom-typescript#480]
Hi guys, 

i have created a basic interface with 3 properties, one of them is optional.

```
interface IClass1Params {
    name: string;
    phoneNumber: number;
    description?: string;
}
```

when i'm trying to create a new instance that implement the interface, i'm using the autocomplete as my guideline, but i have no indication which property is mandatory or optional..

![screen shot 2015-07-21 at 11 37 18 pm](https://cloud.githubusercontent.com/assets/7816765/8811885/9d5ab968-3001-11e5-8504-f12496a330c2.png)

as a result i need to check the interface explicitly by going to the definition and observe the structure
it's a little pain..

thanks, 
Elior

**Comment by basarat** [comment]
Sample: 

```ts
interface IClass1Params {
    name?: string;
    phoneNumber: number;
}
var foo:IClass1Params = {
    /*here*/
}

```
