### ISSUE TITLE
String `") {"` breaks subsequent tokens

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#481]
E.g. 

```ts
function write(str:string){
}

write(") {");
// var foo = 123;
```

Look like: 

![image](https://cloud.githubusercontent.com/assets/874898/8816931/2bfff98a-3070-11e5-97d4-de101ac60186.png)

**Comment by Cu3PO42** [comment]
I'll definitely look into this later today. Seems very weird to me, though.

**Comment by Cu3PO42** [comment]
@basarat I actually can't reproduce this.

![screen shot 2015-07-24 at 16 00 41](https://cloud.githubusercontent.com/assets/5256300/8876018/34a6d186-321d-11e5-805c-bbde92622ad1.png)

**Comment by basarat** [comment]
Try the "exact" code I posted. The code you posted is very different.

**Comment by Cu3PO42** [comment]
I thought you were referring to the `){` at the end of the function definition for write and just added more tokens to confirm that wasn't broken. Sorry for that misunderstanding.

![screen shot 2015-07-25 at 11 49 50](https://cloud.githubusercontent.com/assets/5256300/8888936/58498e70-32c3-11e5-8568-d266293342ff.png)

I can reproduce this now, however this is also broken in the transpired JavaScript as you can see above. I suspect this is a bug in the string definition for the JS grammar. I'll investigate a bit and open an issue there if appropriate.

**Comment by basarat** [comment]
> , however this is also broken in the transpired JavaScript as you can see above.

I half expected that :rose: :)

**Comment by Cu3PO42** [comment]
Right, the issue on the JavaScript grammar is still there, but I "manually" fixed it for TS files.

**Comment by 50Wliu** [comment]
I just fixed this in `language-javascript` so it should be out in the next Atom release.
