### ISSUE TITLE
Add support for "go to declaration" by ctrl/cmd + click

### ISSUE THREAD

**Issue by pleerock** [TypeStrong/atom-typescript#482]
This is definatelly must-have feature, to be honest the only inconvinece I have with atom and atom-typescript plugin. This feature is used by millions of developers on almost every IDE that exists. Please add this feature.

Looks like there is an issue https://github.com/atom/symbols-view/issues/18 maybe someone can contribute this feature directly to atom

**Comment by basarat** [comment]
Would be done using : https://github.com/TypeStrong/atom-typescript/issues/448

**Comment by cevek** [comment]
After webstorm this feature really must have
