### ISSUE TITLE
Output generated twice (while the correct on is empty) when using --out 

### ISSUE THREAD

**Issue by mickeyvip** [TypeStrong/atom-typescript#484]
Hello.

I have `tsc` version `1.5.3`.

Running:
```
$ tsc -m system -t es5 --emitDecoratorMetadata --experimentalDecorators ./src/javascripts/app.ts --out ./public/javascripts/app.js
```
generates:
```
./src/javascripts/app.js
./public/javascripts/app.ts
```

while the `./src/javascripts/app.js` which **should not** be generated has the correct content, while `./public/javascripts/app.js` which I expect to be the correct one, is empty.

When using `sourceMaps` option, there is almost the same happening: the incorrect `./src/javascripts/app.js.map` has the correct content, while `./public/javascript/app.js.map` has:

```json
{"version":3,"file":"app.js","sourceRoot":"","sources":[],"names":[],"mappings":""}
```
 and `./public/javascripts/app.js` has:
```javascript
//# sourceMappingURL=app.js.map
```
Thank you.

**Comment by basarat** [comment]
Do not combine `-m` and `--out`. The TypeScript compiler doesn't support it :rose: . Use `-m` only and let an external module loader generate the `--out` if you want to :rose:
