### ISSUE TITLE
Support Overload View for autocomplete

### ISSUE THREAD

**Issue by manishtpatel** [TypeStrong/atom-typescript#485]
Right now, it does not show overload methods, it is highly unlikely that default method autocomplete is what you want and there is no way of seeing overloaded methods. Any way we can support to see all overaloaded methods? may be by pressing down/up arrow when autocomplete is displayed.

Or any other way supported by autocomplete plugin would be fine.

**Comment by lazutkin** [comment]
:+1: also asked in #309

**Comment by basarat** [comment]
> also asked in #309 

Agreed, basically show overloads at the first level of autocomplete (I misunderstood that intent in 309)

**Comment by abhishek-kakkar** [comment]
Any updates on this?

**Comment by lierdakil** [comment]
I believe the core of this request is more or less fulfilled by signature help. Feel free to open new issues for improvements.
