### ISSUE TITLE
Spaces in apm path breaks atom-typescript pre-install.

### ISSUE THREAD

**Issue by graphnode** [TypeStrong/atom-typescript#486]
I have a space in my apm path and that breaks the installation:

    Window load time: 1856ms
    C:\Users\Diogo Gomes\.atom\packages\atom-typescript\node_modules\atom-package-dependencies\index.js:26 Error: cannot find Atom package linter
    C:\Users\Diogo Gomes\.atom\packages\atom-typescript\node_modules\atom-package-dependencies\index.js:49 linter not installed. Attempting installation now.
    C:\Users\Diogo Gomes\.atom\packages\atom-typescript\node_modules\atom-package-dependencies\index.js:70 linter install failed. Output: 
    'C:\Users\Diogo' is not recognized as an internal or external command, operable program or batch file.

**Comment by graphnode** [comment]
Added a pull request with my personal fix if you are feeling lazy. No idea if this should be fixed in this repository or on [travs/atom-package-dependencies](https://github.com/travs/atom-package-dependencies) since "hacks" have been mentioned.

I will leave the decision in the maintainers hands. :bow:

**Comment by basarat** [comment]
Thanks :rose: merged manually actually into https://github.com/basarat/atom-package-dependencies

**Comment by basarat** [comment]
released as part of `v5.1.1`. Thanks for fixing this :100:
