### ISSUE TITLE
Multiple tsconfig support for a single file

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#492]
It is not uncommon for a single file to be used by multiple `tsconfig.json` files. 

Two code organizations are common here: 
- Sibling client and server folders
- Parent server with a child client folder

There should be a user option to select _which context the user wants to work in_ at the moment. 

This is going to require significant rework but its about time I did that :rose:

**Comment by Davste93** [comment]
Hi, what is the best work around at the moment? Two instances of atom / project folders with two packes.json?

**Comment by cwharris** [comment]
@basarat It's also worth mentioning multiple tsconfigs within the context of testing. server/server-test/client/client-test, are all valid scenarios. I'm sure you're working to make this as agnostic as possible, I just wanted to provide some other interesting scenarios.
