### ISSUE TITLE
tsconfig : postbuild

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#495]
`scripts:postbuild` support similar to `project.json` : https://github.com/aspnet/Home/wiki/Project.json-file#scripts

Will work on if it is indeed needed and I can't work around it. Sort of needed for : https://github.com/TypeStrong/ntypescript/issues/10

**Comment by nycdotnet** [comment]
Would you be open to allowing the output from a `postBuild` script to find its way back into the UI?  I am imagining this would be great for bundling and minification scripts, among others.

**Comment by basarat** [comment]
> Would you be open to allowing the output from a postBuild script to find its way back into the UI?

Yes please. Create an issue for tracking ;) 🌹

TIP: Note case "postbuild" ie small b.
