### ISSUE TITLE
Question: How to save file without compiling it

### ISSUE THREAD

**Issue by lazutkin** [TypeStrong/atom-typescript#498]
I need an option that allows just to save a file without compiling it. It is required when using `gulp#watch` with pipeline like `gulp-changed -> ts -> babel -> js`. In that case when I save a file, `atom-typescript` compiles it according `tsconfig` settings and completes it before then `gulp-changed` initiate its check for outdated deps and as result I have `js` files produced by `atom-typescript` and not passed `babel` and a pipeline at whole.

Thanks

**Comment by basarat** [comment]
> I need an option that allows just to save a file without compiling it.

See FAQ https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#i-dont-want-atom-typescript-compiling-my-js Thanks for using this package :rose:

**Comment by lazutkin** [comment]
Thanks! It works!! But how about an option like `Shift + F6` to get project compiled but without emitting any js code (like emitting it into `/dev/null`)?

**Comment by basarat** [comment]
> But how about an option like Shift + F6 to get project compiled but without emitting any js code (like emitting it into /dev/null)

Plausible, call it `TypeCheck complete project`. Open for grabs.
