### ISSUE TITLE
Grammar: Splitting a ternary operator with a type assertion on multiple lines causes subsequent tokens to be classified as support.class.ts

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#499]
Sample: 
```ts
class Foo {
    foo = true ? 231
        : <number>234;
    bar; // Tokenized as support.class.ts
}
```
Screenshot: 

![image](https://cloud.githubusercontent.com/assets/874898/8921912/6c321dcc-351f-11e5-9030-1ec639a9dc6e.png)

BAD screenshot just for amusement: 
![image](https://cloud.githubusercontent.com/assets/874898/8921915/8142b898-351f-11e5-93f0-d97e405ccb47.png)

# Workaround
Don't split the ternary operator on multiple lines or don't use a type assertion

/cc @Cu3PO42 (the grammar God) :rose:

**Comment by Cu3PO42** [comment]
Oh boy. I'll look into it. From what I know about my own rules, though, it strikes me as very odd.
