### ISSUE TITLE
support commented transforms

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#5]
In addition to https://github.com/TypeStrong/grunt-ts#transforms we should support: 

Something like

``` ts
class Foo{
    ///ts:$inject
    constructor(bar:string){
    }
}
```

will become 

``` ts
class Foo{
    ///ts:$inject
    static $inject = ['bar']; ///ts:$inject:generated
    constructor(bar:string){
    }
}
```

Note: These need to be AST + Project Properties rules.

**Comment by nexussays** [comment]
I like the idea. How would you generalize this so it's not a transform specifically for Angular?

**Comment by basarat** [comment]
Not sure if it is a very good example but I've seen people want stuff like: 

```ts
///ts:typeName
class Foo{
	typeName = "Foo" ///ts:typeName:generated
}

var foo = new Foo();
console.log(foo.typeName === "Foo"); 
```
Admittedly it was an example of *Angular* on SO : http://stackoverflow.com/questions/27945515/is-it-possible-to-get-name-of-the-interface-as-a-string that sparked this (I wouldn't count the example in this question as useful though). Additionally this is to potentially support effectively [AtScript](https://docs.google.com/document/d/11YUzC-1d0V1-Q3V0fQ7KSit97HnZoKVygDxpWzEYW0U/edit#)

**Comment by basarat** [comment]
Needed this today: 

```ts
declare class Foo implements Bar{
 ///ts:implement=Bar
}
```
I really don't see the point of manually copy pasting all the member of `Bar` myself. I remember @vvakame needing this for `atom` specifically although I cannot find the reference request on GitHub (would be great if I found it).

**Comment by basarat** [comment]
Another use case : 

http://stackoverflow.com/questions/28566969/create-programmable-snippet-for-visual-studio-with-node-js-code

```ts
interface MyFunc {
  (item: string, num: number): string
  (item: string): (num: number) => string
}

var myFunc = <MyFunc> _.curry((item: string, num: number): string => {
```
