### ISSUE TITLE
Updating this plugin is generally pretty slow...

### ISSUE THREAD

**Issue by impinball** [TypeStrong/atom-typescript#503]
It usually takes roughly 30 seconds to a minute to update on my laptop. The TypeScript compiler can usually compile itself in about the same period of time. Is there any way to speed up the update?

**Comment by basarat** [comment]
> It usually takes roughly 30 seconds to a minute to update on my laptop.

Its because of the stuff that needs to download from `package.json` usually an updated release on ntypescript. That said most other packages (including e.g. linter) take about 30 seconds as well. 

> Is there any way to speed up the update?

Get a faster internet connection `¯\_(ツ)_/¯` Open for suggestion :rose:

**Comment by impinball** [comment]
1. It usually takes closer to a minute. Linter itself takes about a third of the time to update for me than this. I've seen this take up to 2 minutes to update a couple of times.
2. I don't really have a lot of control over my internet connection. I blame Comcrap on this one (there aren't a lot of alternatives).

**Comment by impinball** [comment]
@basarat 

I honestly don't know what all goes on when this updates, though. IMHO, this is probably something better resolved by Atom than this.
