### ISSUE TITLE
Disapearing tsconfig.json

### ISSUE THREAD

**Issue by vjau** [TypeStrong/atom-typescript#505]
Hi,
i have a project with multiples tsconfig.json (one in each folder, because of scope issues).
The problem is that the tsconfig.json don't show up anymore in the files "tree".
I have tried to reproduce with a small project, but i can't.
What could i do ?
![tsconfig](https://cloud.githubusercontent.com/assets/5278429/8981330/ba89ee98-36b7-11e5-9bb7-0b722bdc7b9e.png)

Thank you.

**Comment by basarat** [comment]
We have done absolutely *nothing* to the tree view, so not an issue to report to us :rose: 

TIP: Make sure you haven't asked atom to hide it :

![image](https://cloud.githubusercontent.com/assets/874898/8997906/3a806796-376a-11e5-854f-e65fb0610e35.png)


You can report it to https://github.com/atom/tree-view/issues if you still have problems :rose:
