### ISSUE TITLE
Visual Studio color scheme

### ISSUE THREAD

**Issue by aleksey-bykov** [TypeStrong/atom-typescript#506]
Is there an option to pick a color scheme of Visual Studio?

**Comment by Cu3PO42** [comment]
Color schemes are handled by the Atom editor itself. To my knowledge there are quite a few Visual Studio like color schemes. Open your settings, go to install, select themes and search for "Visual Studio".

If you intend to convert any existing theme over, you can do that for Sublime Text and TextMate themes. I'm not aware of such an option for Visual Studio themes.

**Comment by basarat** [comment]
Checkout : https://atom.io/themes/search?utf8=%E2%9C%93&q=visual 

Interestingly found this by @nycdotnet :rose:  https://atom.io/themes/redmond-syntax

![image](https://cloud.githubusercontent.com/assets/874898/8997853/b189815c-3769-11e5-9e47-f77a99a155f9.png)

**Comment by nycdotnet** [comment]
That's mah theme!!

If you like, be sure to install both redmond-ui and redmond-syntax for the full VS "Blue" experience.

**Comment by aleksey-bykov** [comment]
luving it :heart: :heart: :heart:
