### ISSUE TITLE
Block comment: use // instead of /* */

### ISSUE THREAD

**Issue by markogresak** [TypeStrong/atom-typescript#507]
I am setting up my atom typescript workflow again after formatting my computer and I can't figure out how to make `cmd + /` perform a block comment by adding `//` before each of line instead of creating an actual block comment.

What happens:
Initial state:
```
line 1
line 2
line 3
```
Comment block (`cmd + /`) action:
```
/*line 1
line 2
line 3*/
```
What I would like to do:
```
// line 1
// line 2
// line 3
```

I'm used to this from other grammars with this style of comments because if I want to uncomment only one line, I don't have to modify anything other line. If I would do the same for line 3, I have to change line 1 and line 3 first.

I am sure I had this functionality before, but I haven't been using atom-typescript for almost two months and now I can't find where to enable it again.

**Comment by basarat** [comment]
> I am sure I had this functionality before, but I haven't been using atom-typescript for almost two months and now I can't find where to enable it again.

Probably broke post this : https://github.com/TypeStrong/atom-typescript/pull/418

Note the `.js` files behave that way in atom i.e. we get multiple `//`. 

@isuda has raised the same issue privately with me. Marking as a bug :rose:

**Comment by markogresak** [comment]
Sorry for two referenced messages, I later amended commit message and github still recorded it as 2.

**Comment by markogresak** [comment]
Since #508 was pulled, this is resolved.
