### ISSUE TITLE
Using atom typescript with plain js files

### ISSUE THREAD

**Issue by scottwio** [TypeStrong/atom-typescript#509]
Would it be possible to use atom typescipt on plain old .js files. I have seen this working in Visual Studio Code and love it. Sometimes I work on projects where devs are not comfortable using .ts .and I miss the autocomplete magic the ts compiler brings. Visual Studio Code gives you auto complete on standard js files as well as integrating .d.ts files into that auto completion so you get a bit of the typescript goodness even with plain js. Is this possible with atom-typescript?

**Comment by basarat** [comment]
Duplicate of https://github.com/TypeStrong/atom-typescript/issues/315 

I definitely understand the motivation as [migrating can be painful](http://basarat.gitbooks.io/typescript/content/docs/types/migrating.html). My personal plan is add something that allows you to use the `.ts` files like JavaScript  and discussing that here https://github.com/Microsoft/TypeScript/issues/4094

**Comment by scottwio** [comment]
For me this is more about being able to use some of typescripts abilities without having to change the workflow of everyone on the team. For a lot of people even changing the file extension is to much as they are js purists aka don't like the idea of typescript. This way you can work along side another js dev without effecting them at all. 

I wonder how Visual Studio Code has implemented the feature as they are just using the standard ts compiler.
