### ISSUE TITLE
Proposal: Add option "Auto build" in Settings

### ISSUE THREAD

**Issue by Chofoteddy** [TypeStrong/atom-typescript#510]
I think it would be great to have an option like this:

![captura de pantalla de 2015-07-31 13 12 37](https://cloud.githubusercontent.com/assets/1615875/9014141/200bc7c2-3786-11e5-9d73-4a3c61790eeb.png)

Where you can choose where in the typescript file to build and choose whether you want these to be built or not.

**Comment by basarat** [comment]
> Where you can choose where in the typescript file to build and choose whether you want these to be built or not.

Already exists as an option on tsconfig.json : https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#buildonsave 

Should add it to FAQ. Will do that soon :rose: leaving open till then
