### ISSUE TITLE
import autocomplete should provide relative path started with ./

### ISSUE THREAD

**Issue by stepancar** [TypeStrong/atom-typescript#514]
Hello, @basarat !
When i write `import * as myModule from ''"` i have autocomplete wich provide relative path to module - for example   '../../MyFolder/myModule'. 
i think it should be './../../MyFolder/myModule' 
What do you think about it?

**Comment by basarat** [comment]
> What do you think about it?

Are you seeing a runtime error because of this? Should work fine, don't see the point of adding `./` needlessly ;) :rose:

**Comment by stepancar** [comment]
I haven't any runtime errors . But i see that most webpack loaders uses relative paths which starts with './' maybe you know why?
I catch problem which force me rewrite all relative paths with './' when i used [ts-loader] (https://github.com/jbrantly/ts-loader/issues/29) for example. 
Maybe you know why tsc supports relative paths '../../dir/dir2' and './../../dir/dir2'? Any historical reasons?
Thank you! 
I think this issue look like as question ;)

**Comment by basarat** [comment]
> './' maybe you know why

Its easy to prefix `./` to all paths to ensure its relative ... e.g. `./foo` , `./../foo` instead of `./foo`, `../foo`. Don't see the reason for deleting our code if its doing something better. 


> Maybe you know why tsc supports relative paths '../../dir/dir2' and './../../dir/dir2'? Any historical reasons?

It just does a path.resolve ... if it work it works. 

> I think this issue look like as question ;)

:rose:

**Comment by stepancar** [comment]
@basarat, Hello!
I created [issue](https://github.com/jbrantly/ts-loader/issues/29) for ts-loader which supports only relative paths which started with ./ or ../
results of investigation is that its typescript issue and in the future all relative path's should started with ./ and ../ (see @jbrantly comment)
I think that atom typescript should provide autocomplete for import with ./ and ../ now, because without it programmers should rewrite their paths in the future. Imagine how much paths can write programmers which uses you awesome atom-typescript. Last week i rewrote about 200 relative paths))
Thank you!

**Comment by basarat** [comment]
> I think that atom typescript should provide autocomplete for import with ./ and ../ now, because without it programmers should rewrite their paths in the future.

This is what we already do. We provide relative paths with `./` if the file is located right next to it.
