### ISSUE TITLE
compilerOptions validation for target does not accept capitalized targets

### ISSUE THREAD

**Issue by moreginger** [TypeStrong/atom-typescript#517]
`tsc --help` says to use "ES3", "ES5" or "ES6" for the target value, but it doesn't care about the case.

OTOH atom-typescript tsconfig validator asserts that the values must be exactly "es3", "es5" or "es6". This is confusing.

There's an obvious trivial tweak to tsconfig.js but it would probably be better to alter the code to ignore case (so that e.g. "Es6" is also accepted as per tsc).

**Comment by basarat** [comment]
> OTOH atom-typescript tsconfig validator asserts that the values must be exactly "es3", "es5" or "es6". This is confusing.

This is consistent with what was discussed with the TypeScript team here : https://github.com/Microsoft/TypeScript/issues/1933 

[I Quote](https://github.com/Microsoft/TypeScript/issues/1933#issuecomment-72982784): 

> Command line arguments in Windows are usually case-insensitive (though with powershell maybe this is not the case any more) because of their DOS heritage. In *nix, they are all case sensitive. TypeScript’s cli is an aberration in the *nix world. See for example ls -a versus ls -A. They do two different things.

If you use `tsconfig.json` using `-p` with the typescript compiler what happens? Does it *actually work*?

**Comment by moreginger** [comment]
> If you use tsconfig.json using -p with the typescript compiler what happens? Does it actually work?

Yes, `tsc -p ...` (1.5.3) works whatever the case; for this option at least. I assume they changed the behavior since [this comment](https://github.com/Microsoft/TypeScript/issues/1933#issuecomment-72988825)?

Also see https://github.com/Microsoft/TypeScript/wiki/Compiler-Options. If case is to be enforced, it would be better to enforce the same one (but no doubt that would cause a lot of aggro for existing projects!).

**Comment by basarat** [comment]
You are right. 

![image](https://cloud.githubusercontent.com/assets/874898/9128958/520983d4-3d14-11e5-9c60-9ae296cf9812.png)

The objective of sensitivity was to support the users for errors they might run into elsewhere ... not enforce our personal opinions :rose: Marked as a bug

**Comment by basarat** [comment]
`v5.2.8` :rose:
