### ISSUE TITLE
programManager cleanup

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#52]
It is becoming obvious to me that `programManager` should be split into multiple external modules. Also the interfaces for inter-process communication I am using should just be interfaces of the arguments / returns of program manager. 

Also the `query` functions in `parent.ts` could potentially move into `programManager` right next to the function that actually gets called by `child`. But that might confuse people in understanding what is child and what is parent so I need to think about this more. Open to suggestions.

Also more Async: 

* [x] goto definition 
* [x] format code

**Comment by csnover** [comment]
I’d like to help out describing an architecture, but you seem more available than I am to move forward on this over the next week. Do you want to just keep moving forward for now until things are reasonably stable and we can talk more seriously about a bigger cleanup at a later time?

**Comment by basarat** [comment]
> Do you want to just keep moving forward for now until things are reasonably stable

The async stuff will be stable by the end of today. 

>  we can talk more seriously about a bigger cleanup at a later time

I am on gitter right now if you want : https://gitter.im/TypeStrong/atom-typescript but whenever you want is okay :)

**Comment by basarat** [comment]
> The async stuff will be stable by the end of today.

Done. Phew. `programManager` exports these sync functions : https://github.com/TypeStrong/atom-typescript/blob/a90bd067bba8656e41c6e1ed3c1bdea06118274f/lib/main/lang/programManager.ts#L228-L408

And all you need to do to make a function `async` is add it to the worker child's list of responders : https://github.com/TypeStrong/atom-typescript/blob/a90bd067bba8656e41c6e1ed3c1bdea06118274f/lib/worker/child.ts#L45-L56 

And then add it to the parent : https://github.com/TypeStrong/atom-typescript/blob/a90bd067bba8656e41c6e1ed3c1bdea06118274f/lib/worker/parent.ts#L132-L142 where `childQuery` automatically takes a `sync` function and changes it signature to one that is `async` and `promise` based. 

Gain : you only need to define the query/response `interface` *once* and its never out of sync from the function definition. Plus adding new functions is done is a typesafe *using name only once* manner.

**Comment by basarat** [comment]
> we can talk more seriously about a bigger cleanup at a later time

@csnover just finished #63. See https://github.com/TypeStrong/atom-typescript/blob/master/CONTRIBUTING.md#architecture and raise a concern if there is anything you don't like / understand.
