### ISSUE TITLE
Goto correct definition reference import path

### ISSUE THREAD

**Issue by thr0w** [TypeStrong/atom-typescript#520]
In above sample, if a point the mouse over `something` in `var a=something()` don't show the JSDoc.

I think it's happens because atom-typescript points to import clause. Trying with F12, in first press goes to import clause, in second press goes to correct definition in file2.

I suggest skip import clause and go directly to definition in file2.

> file1.ts
```typescript
import {something} from "file2"
var a=something(); // << mouse hover or F12 here
```
> file2.ts
```typescript
/** something  text */
function something()
{   
}
```

**Comment by basarat** [comment]
> if a point the mouse over something in var a=something() don't show the JSDoc.

Really a language service feature request. Should go to Microsoft/TypeScript :rose:

**Comment by basarat** [comment]
For reference, the function we use is `getQuickInfoAtPosition` : https://github.com/TypeStrong/atom-typescript/blob/c8140a26451f65ef5d399cb5a4ea81a350c7a578/lib/main/lang/projectService.ts#L82
