### ISSUE TITLE
There must be a way to provide Babel options

### ISSUE THREAD

**Issue by s-panferov** [TypeStrong/atom-typescript#521]
Hello! Thanks for the awesome project. 

I found the feature https://github.com/TypeStrong/atom-typescript/pull/475 with optional babel support very useful. But it seems incomplete to me, because there must be a way to specify Babel's options. Existed solutions like https://babeljs.io/docs/usage/babelrc/ don't work (or I'm doing something wrong).

**Comment by s-panferov** [comment]
Maybe we can offer the second extended form of the `externalTranspiler` option?

```
"externalTranspiler": {
	name: "babel",
	options: {
		/* babel options goes here */
	}
}
```

Or maybe there is a way to make `.babelrc` work?

**Comment by basarat** [comment]
> Maybe we can offer the second extended form of the externalTranspiler option

I like the simplicity of this :rose: 

Closed by https://github.com/TypeStrong/atom-typescript/pull/523

**Comment by tomitrescak** [comment]
How does this work? I set this, I have babel installed in my node_modeuls dir, yet no transpilation with babel hapens. Also, the options are not available, I need to use babel plugins.

**Comment by basarat** [comment]
@tomitrescak personally I've never used this option so can't be much help. With the TypeScript compiler getting a transformer based emitter soon, we wouldn't need to offload heavy plug-gable emitting to babel hopefully :rose:

Still docs https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#can-i-use-an-alternate-transpiler

**Comment by nycdotnet** [comment]
It calls Babel on the emitted result before writing it to disk.  This was a bit of a hack to get let for loops working pre-1.8 and it includes babel 5.  Look at the referenced PR.
