### ISSUE TITLE
padding removed when uses autocomple in jsx 

### ISSUE THREAD

**Issue by stepancar** [TypeStrong/atom-typescript#525]
Hello, @basarat!
I catch simple issue with autocomple in tsx. 
you can see pictures. 
start type div then space, then ctrl+space then press enter
![screenshot_9](https://cloud.githubusercontent.com/assets/2854910/9173955/fff6c178-3f85-11e5-81dc-525c0c255150.png)
you get <divref instead <div ref
![screenshot_2](https://cloud.githubusercontent.com/assets/2854910/9173960/0597cea6-3f86-11e5-9d04-75cfa8053441.png)
Thank you!

**Comment by basarat** [comment]
Basically https://github.com/atom/autocomplete-plus/ is eaching whitespace. See following example: 

![eatwhitespace](https://cloud.githubusercontent.com/assets/874898/9188926/55e9fdc6-4025-11e5-944a-f6a26ef095bf.gif)

Suggest raising here : https://github.com/atom/autocomplete-plus/issues

**Comment by thomasjo** [comment]
> Basically https://github.com/atom/autocomplete-plus/ is eating whitespace

I'm unable to verify this claim. Not able to reproduce any whitespace "eating" in safe mode. This seems like a grammar issue, but I might be wrong.

**Comment by basarat** [comment]
> Not able to reproduce any whitespace "eating" in safe mode.

Actually not happening in atom-typescript anymore either :rose: Someone fixed something :dancer: 
![whitespace2](https://cloud.githubusercontent.com/assets/874898/9265054/353b423a-4271-11e5-94ca-6b1823ef9e7f.gif)

**Comment by stepancar** [comment]
@basarat, try autocomplete in tsx. its still working not correct.
Thank you!

**Comment by gregerolsson** [comment]
A quick test without analyzing any repercussions (might break things) solved it for me.

autocomplete-plus selects to the left from the cursor, `replacementPrefix.length` characters when the suggestion is inserted. I tried using an empty string here and the problem went away:
https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/atom/autoCompleteProvider.ts#L218

Again; might break other stuff.

**Comment by basarat** [comment]
> I tried using an empty string here

@gregerolsson You mean `' '` or `''`?

**Comment by gregerolsson** [comment]
@basarat A zero-length string (`''`). As far as I can tell, autocomplete-plus uses the length of that string to select left from the cursor position when a suggestion is selected by the user:

https://github.com/atom/autocomplete-plus/blob/master/lib/autocomplete-manager.coffee#L378

I'll do some more code-tracing today to see if the `options.prefix` string sent by autocomplete-plus, and sent back as `replacementPrefix` by atom-typescript needs to consider any special scenario or if it can just be discarded (zero-length string returned instead).

Currently, in JSX, it appears only to be the number of spaces before the component class name or the previous attribute:

![prefix-string](https://cloud.githubusercontent.com/assets/306822/9573991/894f577c-4fc2-11e5-9842-21e72b6455e2.png)
