### ISSUE TITLE
conflict node.d.ts and /node_modules/ntypescript

### ISSUE THREAD

**Issue by stepancar** [TypeStrong/atom-typescript#526]
Hello @basarat. 
I have issue: 
conflict beetween ntypesctript.d.ts and node.d.ts. 
i dont now why ntypescript exists in compile context.
attached [repo](https://www.dropbox.com/s/ufyfb1fm2h8hnds/bugWithNode.zip?dl=0)
, which reproduce this issue only in atom typescript. if you try compile you will NOT catch error, but if you'll press F6 in atom-typescript u'll catch it.
![nodentypescriptbug](https://cloud.githubusercontent.com/assets/2854910/9261119/986cb71a-4214-11e5-96b1-8cd04c98532b.png)
why /node_modules/ntypescript in compile sources?

**Comment by stepancar** [comment]
I know about package.json atom-typescript feature 
![screenshot_3](https://cloud.githubusercontent.com/assets/2854910/9262453/a8b15884-421d-11e5-89c7-63c705d868b2.png)
but i think, if we disable node_modules in tsconfig.json it not should appears in compile sources
What do you think about it?

**Comment by basarat** [comment]
> if we disable node_modules in tsconfig.json it not should appears in compile sources
> What do you think about it

no typescript.definition should *still appear*. Just not *all the sources* :+1:

**Comment by basarat** [comment]
Thanks for raising this. I should have done more scrutiny when this came up :rose: https://github.com/TypeStrong/ntypescript/issues/12
