### ISSUE TITLE
Setting an output path

### ISSUE THREAD

**Issue by danielearwicker** [TypeStrong/atom-typescript#53]
In Visual Studio there is an option to put the .js output in a specific folder - is there an equivalent for this in tsconfig.json?

PS. This plugin is TERRIFIC.

**Comment by csnover** [comment]
Yes sir! As of 0.28.0 you can specify `compilerOptions.outDir`. Is that what you are looking for?

**Comment by basarat** [comment]
Feel free to reopen if you still have issues

**Comment by danielearwicker** [comment]
And guess what, it worked perfectly. Like everything else!

**Comment by basarat** [comment]
You have @csnover to thanks for this particular thing ;) https://github.com/TypeStrong/atom-typescript/commit/8f98c7f989bfaea9ddf18702523451a22cff6e2b

BTW @csnover It would be awesome if I could get your twitter address.

**Comment by csnover** [comment]
@basarat https://twitter.com/zetafleet
