### ISSUE TITLE
Go to declaration with Ctrl/Cmd + click

### ISSUE THREAD

**Issue by s-panferov** [TypeStrong/atom-typescript#530]
Hello! In our company several people migrated from WebStorm to Atom+AtomTypescript, and everything is amazing except one thing. There is a cool thing in WebStorm when you can press ctrl/cmd button, hover an item in the code and make a click:

![kxgbp6f7hc](https://cloud.githubusercontent.com/assets/198327/9301411/ea8bfdf2-44d6-11e5-8c19-4e13dc24aa66.gif)

It is much faster and simpler than current F12 workflow. The other difference is that F12 in atom-typescript at first goes to an import declaration, and then goes to a real declaration. This requires to press F12 several times and it's a little bit annoying, especially on mac keyboards, when Fn key is in the bottom left side of a keyboard and F12 key is in the top right.

Is there any way to implement the same behaviour as in WebStorm?

**Comment by blakeembrey** [comment]
Related: https://github.com/TypeStrong/atom-typescript/issues/482 and https://github.com/TypeStrong/atom-typescript/issues/448

**Comment by Cu3PO42** [comment]
Also relevant: #520

**Comment by basarat** [comment]
As mentioned. I'll just link the issues to your queries:

> There is a cool thing in WebStorm when you can press ctrl/cmd button, hover an item in the code and make a click:

If anyone wants to work on this use https://github.com/TypeStrong/atom-typescript/issues/448 as a reference.


> The other difference is that F12 in atom-typescript at first goes to an import declaration, and then goes to a real declaration

If anyone wants to work on this you can work on either the our code base : https://github.com/TypeStrong/atom-typescript/issues/520 or upstream at Microsoft/TypeScript

:rose:
