### ISSUE TITLE
js files emits if "noEmit" option setted to true

### ISSUE THREAD

**Issue by stepancar** [TypeStrong/atom-typescript#531]
Hello, @basarat.
in my tsconfig:
```javascript
  "compilerOptions": {
        "jsx": "react",
        "noEmit": true
   }
```
but when i build project in atom-typescript (F6) or save i see that compiled js appears.
if just compile project with ntsc - .js not appears.
What i do wrong?
Thank you!

**Comment by basarat** [comment]
> build project in atom-typescript

Don't build :) We should probably respect `noEmit`. Code is in [building.ts](https://github.com/TypeStrong/atom-typescript/blob/5c9fe2772df610f4e8463550d12ff9b2f13ba879/lib/main/lang/modules/building.ts) basically it should just do all the checks but not write the emitted file to disk :rose:
