### ISSUE TITLE
Unpublish from npm

### ISSUE THREAD

**Issue by steelbrain** [TypeStrong/atom-typescript#532]
This package is published to [`npm`][1]. I believe this to be an accident.

[1]:https://www.npmjs.com/package/atom-typescript

**Comment by basarat** [comment]
> I believe this to be an accident.

Nope. Although the readme for npm is a quite confusing. 

It was to provide users with this bin command `atbuild` : https://github.com/TypeStrong/atom-typescript/blob/5c9fe2772df610f4e8463550d12ff9b2f13ba879/package.json#L6
