### ISSUE TITLE
TypeScript pane resizes over the text I am typing

### ISSUE THREAD

**Issue by Ptival** [TypeStrong/atom-typescript#534]
I cannot test with the most recent version of atom-typescript, but in the version I am using, the following annoying thing happens.

Open a new file, and write the following at the bottom **after more newlines than you screen can vertically fit**:

```
class Parent {}

class Child extends Parent {
  constructor() {

  }
  field: ;
}
```

Now, the TypeScript error message should be "Type expected. ;".

Now type a character after the field, as if you were filling its type.

The error message will turn to "Cosntructors for derived classes...." which takes more space. The TypeScript pane will extend, but the buffer will not be scrolled down or updated, so you end up not seeing the line you were typing in, and the suggestion box is still at the old location of your now hidden text.

**Comment by basarat** [comment]
Sorry didn't see this issue. Already closed by : https://github.com/TypeStrong/atom-typescript/commit/86d8d69f55a8ad26ee47ab19c404e08a1b0ba510 :rose:
