### ISSUE TITLE
Automatic removal of valid entries in tsconfig.json

### ISSUE THREAD

**Issue by ziahamza** [TypeStrong/atom-typescript#535]
Hello. 
In our codebase, we have a lot of different typescript packages in a flat folder structure. In each of the tsconfig.json, we include types from the other packages as follows:

"files": [ "../{types from different packages}", "./{local type definitions}

it compiles, and run perfectly fine with the typescript compiler. But atom-typescript removes any reference to files outside of the root typescript module structure. Can we make sure that atom-typescript stops removing any valid references in tsconfig.json?

thanks!

**Comment by basarat** [comment]
> Can we make sure that atom-typescript stops removing any valid references in tsconfig.json

I suspect you guys also have a `filesGlob` option in the tsconfig.json?

**Comment by ziahamza** [comment]
Yes. We do use the file globs option to auto include all local ts files except node modules.

**Comment by ziahamza** [comment]
But I guess auto include should not cause atom typescript to remove any paths that don't follow the file globs unless explicitly excluded?

**Comment by basarat** [comment]
> remove any paths that don't follow the file globs unless explicitly excluded

We expand it based on the file system. Feel free to add `../**/etc` to filesGlob to get it add files external to the current folder :rose:
