### ISSUE TITLE
No definition found when ts code is in a subfolder

### ISSUE THREAD

**Issue by AndrewSav** [TypeStrong/atom-typescript#537]
Hi there!
So I tried to installing atom and atom-typescript to see how it compares with Visual Studio / WebStorm for nodejs web projects. What I immediately noticed is that I'm getting `Atom Ts: No definition found`. 

"What the heck does this mean?" though I. Well after searching the issues here, it became apparent that this is because of missing `tsconfig.json`. (Could the error message be improved? A user has no fighting chance dealing with this cryptic error message).

But the thing is, my `tsconfig.json` was not missing. It was there all right. It was working perfectly in WebStorm. What I quickly realized is that atom-typescript expects `tsconfig.json` at the project root.

I prefer to have all typescript files in a subfolder (as opposed to js, etc). Firstly I feel it's cleaner. Secondly, from time to time ts files appear inside node_modules, and ts compiler (at least in webstorm) dutifully walks the whole tree and compile them. And then complains. I did not want that to happen so I moved all my TS in a subfolder, put there `tsconfig.json` and it worked perfectly, but not in atom.

How do I configure atom-typescript so that it looks for `tsconfig.json` in a different place and starts transpiling from that folder? Is it possible to improve the error message?

**Comment by basarat** [comment]
> Atom Ts: No definition found

That is for if you pres `f12` aka `goto definition`. The message seems right for that. 


> What I quickly realized is that atom-typescript expects tsconfig.json at the project root

Not true. 

> How do I configure atom-typescript so that it looks for tsconfig.json in a different place and starts transpiling from that folder?

It looks at all folder above the current open `.ts` file. This is the way `tsc` is designed to work as well :rose: 

Feel free to discuss any other issues here, we'd be hapy to help :rose:

**Comment by AndrewSav** [comment]
>That is for if you pres f12 aka goto definition. The message seems right for that.

That's weird. In the bottom pane there is following text:

    No Build. Press ( F12 ) to start a build for an active TypeScript file's project.

This message suggests that F12 is for starting a build not for going to definition. Note that if I press F6 nothing happens at all. F12 builds the typescript. What am I missing?

>It looks at all folder above the current open .ts file. This is the way tsc is designed to work as well

So it looks like it's broken. It does not build with `tsconfig.json` in the same folder as .ts. Anything I can do to help diagnose?

**Comment by AndrewSav** [comment]
Thank you for this. It must have been artifact from very old Atom installation. I removed it completely and reinstalled from scratch, after that all started working as expected.

**Comment by jonsamwell** [comment]
I'm also getting this error 'No Definition Found'.  It seems to compile the *.ts files fine until I add the 'out' options to the tsconfig.json then it stops compiling the ts files on save.  If I press F12 from with a ts file I then get the 'No Definition Found' error.

Here is a simplified version of the project:

root
  models
    modelOne.ts
    modelTwo.ts
 module.name.ts
tsconfig.json

**Comment by jonsamwell** [comment]
Sorry for wasting your time it is working now adding the 'buildOnSave' options then uninstalling and reinstalling atom it is working as expected.  Seems odd I had to uninstall though?

**Comment by basarat** [comment]
> Seems odd I had to uninstall though

You are not on windows are you? https://github.com/TypeStrong/atom-typescript/issues/195

**Comment by jonsamwell** [comment]
Yeah, that looks like the issue

**Comment by Justin123ishere** [comment]
I was getting the same problem, but all I did was set "buildOnSave" from false to true, and restart the atom IDE. It was working fine with me without reinstalling.
