### ISSUE TITLE
Linter is too aggressive at displaying errors, blocks auto-complete list in the middle of typing

### ISSUE THREAD

**Issue by csnover** [TypeStrong/atom-typescript#54]
The linter complains about errors when you are in the middle of typing, which blocks the display of the autocomplete list (since it is usually rendered first) and leads to a bad user experience. There should be a way to suppress errors from being displayed in this case.

**Comment by basarat** [comment]
It can be fixed with a z-index override which would move linter *behind* any open autocomplete plus. Currently its *in yo face*: 

![image](https://cloud.githubusercontent.com/assets/874898/6072759/6aff97ac-adf9-11e4-9338-c44cbea528e2.png)

**Comment by csnover** [comment]
I tried looking at changing z-indexes before opening the ticket; the element with the z-index didn’t appear to have any identifiable characteristic that could allow the order to be changed. Let me know if I was blind or something but I am pretty sure more aggressive work needs to be done to not show both at once.

**Comment by basarat** [comment]
> the element with the z-index didn’t appear to have any identifiable characteristic

Yeah. There isn't a reliable way. But what I have should work for *most* of the cases

**Comment by basarat** [comment]
Perhaps only a partial fix : https://github.com/TypeStrong/atom-typescript/commit/f255127b66a9a31a0b0859ed518b32f76b989d38#commitcomment-9615537

**Comment by basarat** [comment]
Workaround: Just type a single character and the overlay order will fix itself.

**Comment by basarat** [comment]
@csnover given the workaround from the partial fix I don't think this is worth pursuing further. If you agree close this. Otherwise we can leave it open.

**Comment by csnover** [comment]
I’d like to do some more testing with the current workaround. I mean, really I’d like to fix it so that atom-typescript is smart enough to not show linter while autocomplete-plus is displaying options, but that requires some additional code.

**Comment by basarat** [comment]
cool. Thanks!

**Comment by basarat** [comment]
Yeah, after testing its not soo great. Because as you type linter will not refresh till you stop typing, so we don't get the *old* error message (the one that was there before you started typing) removed from the dom and it will stick around in front of the autocomplete.

**Comment by basarat** [comment]
Feature request on atom : https://github.com/TypeStrong/atom-typescript/issues/54

**Comment by basarat** [comment]
Feature request on atom : https://github.com/atom/atom/issues/4401

**Comment by basarat** [comment]
Feature request on atom-autocomplete : https://gitter.im/atom-community/autocomplete-plus?at=54daf309d9eaafd66f7e6cbd Should happen automatically soonish.

**Comment by basarat** [comment]
Fixed with `v2.1.4` of autocomplete-plus : https://github.com/atom-community/autocomplete-plus/commit/49b5215a8b943d9fb7b3d0bb1d594f9b6363a237
