### ISSUE TITLE
Compiler option "listFiles" unsupported in tsconfig.json

### ISSUE THREAD

**Issue by ScottHamper** [TypeStrong/atom-typescript#540]
Hey All,

atom-typescript currently displays an error when a tsconfig.json file uses the "listFiles" compiler option. It looks like this option is missing from `/lib/main/tsconfig/tsconfig.ts`

**Comment by basarat** [comment]
Verified bug : http://json.schemastore.org/tsconfig :rose: Up for grabs

**Comment by ScottHamper** [comment]
Hey Basarat,

I'd be happy to create a pull request for this, since it looks like there's only two lines of code that need to be added. I'm not really looking to set up a complete dev environment for atom-typescript in order to fix the issue, though. Would it be reasonable for me to fork/branch/fix/pull-request "blindly"?

Otherwise I will wait patiently, :)

Thanks!

**Comment by basarat** [comment]
> Otherwise I will wait patiently

Sadly I really wish I had tests setup in place, so better to wait ... it is indeed two lines though

**Comment by ScottHamper** [comment]
Ok, no prob!

**Comment by vvakame** [comment]
:+1:

**Comment by basarat** [comment]
fixed with `6.0.15` :rose:

**Comment by vvakame** [comment]
:smile_cat: thanks!
