### ISSUE TITLE
AST Viewer Often Doesn't Work

### ISSUE THREAD

**Issue by JKillian** [TypeStrong/atom-typescript#541]
Often when I run the "Ast" or "Ast Full" command on a typescript file, the Ast tab pops up but is essentially blank (see screenshot below). In fact, I only have been able to get it to show up correctly on one occasion. 

<img width="1133" alt="screen shot 2015-08-24 at 8 11 09 pm" src="https://cloud.githubusercontent.com/assets/1400151/9455761/a432231a-4a9c-11e5-84f3-08aca3b61f9a.png">

Unfortunately, not sure what other debugging/reproduction info I could include to help. Let me know if there's anything of that sort which would be beneficial.

**Comment by JKillian** [comment]
This might be a performance issue actually. I came back about 10 minutes later and I see an AST now :smiley: I'll look into it more.

**Comment by basarat** [comment]
> Let me know if there's anything of that sort which would be beneficial.

Its be finiky for me two. The following *does __always__ work* :

*Only open ONE AST view*

Its got to do with D3 interacting with Atom :panda_face: :rose:

**Comment by basarat** [comment]
That said ... I mostly only need one ast view open at a time anyways for a quick review :). Then I take a screenshot if I need to look at it longer

**Comment by JKillian** [comment]
Interesting, I've also noticed that when I run the command, it opens up two AST tabs. When it works, one shows the whole AST and the other shows a cut-off version of the AST. As finicky as it is, it's a really neat feature when it works!

**Comment by JKillian** [comment]
Just wanted to ass a somewhat obvious note that I sometime forget (in case it will help others). The AST will only work if the file you're working with is part of the project, i.e. in `tsconfig.json`. If it's not, you'll get the blank view like above.

**Comment by basarat** [comment]
> The AST will only work if the file you're working with is part of the project, i.e. in tsconfig.json

Definitely. No project -> nothing works ... although not everything shows an error

**Comment by ctaggart** [comment]
I was hoping to see the AST for `TypeScript/lib/typescriptServices.d.ts`, but it is always blank for me. I copied the `tsconfig.json` from elsewhere and modified it to be:
``` json
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "sourceMap": true
    },
    "files": [
        "typescriptServices.d.ts"
    ]
}
```

![image](https://cloud.githubusercontent.com/assets/80104/11988385/95ee76f8-a9a3-11e5-8e26-4f57bb7b7f59.png)

**Comment by JKillian** [comment]
@ctaggart That's a very long file which might be causing things to not work. I'd try reducing it to about 20 lines and seeing if you can get things working and then working up from there.

**Comment by basarat** [comment]
@ctaggart as Jason said it will only work for small files around 20 lines. You can generally an understanding of the AST from code samples that small and extrapolate mentally to whatever you truly want to do with the AST. 

It was written mostly as a quick hack for me to see *the typescript view of code* quickly :rose:

**Comment by ctaggart** [comment]
Thanks @JKillian & @basarat. It is working fine with a smaller file. Yes, it is very useful!
![image](https://cloud.githubusercontent.com/assets/80104/11988695/a94c940a-a9a8-11e5-94f8-e73499eaf15c.png)

**Comment by basarat** [comment]
@ctaggart also note that here is a difference between AST (The forEachChild visitor) / Full-AST (node.getChildren). Both are viewable via different atom commands :rose:
