### ISSUE TITLE
Quick Fix overlay toggled in wrong file

### ISSUE THREAD

**Issue by Tharkun86** [TypeStrong/atom-typescript#542]
Hi,

the Quick Fix overlay does only on the first file it is triggered. When triggered on a second file, the menu  will still appear in the first file it was triggered on and behave strangely (like staying open until a option is chosen or it is triggered again in the first file). 

I looked a bit into the code and will have a pull request ready for this shortly.

**Comment by basarat** [comment]
Awesome, thanks! :rose:

**Comment by basarat** [comment]
comes out with `5.5.1`
