### ISSUE TITLE
dts.generator breaks multi-package import

### ISSUE THREAD

**Issue by christyharagan** [TypeStrong/atom-typescript#544]
Before the latest version (6.0.0) the following worked (where we're generating the declarations, including the package level declarations):

```
package A

package B dependent on A
package C dependent on A

package D dependent on B, C

```

Now, if B and C expose symbols from A, then D had to also include a dependency on A itself, but it all worked.

Now, however, we get duplicate symbol warnings (because the generated typings for B and C now reference the typings file for A, and expose its symbols). 

If A imports the node definitely-typed typings (for example), we easily get thousands of errors and compile times become impossibly slow.

For me, this fundamentally breaks things, and v6 is unusable.

I can't see any way around this problem, except downgrading to previous versions.

**Comment by basarat** [comment]
The main motivation for dts-generator was that the user doesn't need to have `definition` `true` for it to work. Also its less susceptible to setting the correct *relative paths*. 

But I hoped that it would work as is ... nevertheless took the caution of upgrading a major version. 

I'll try right now with having a `node.d.ts` in both projects and update today for a way forward

**Comment by basarat** [comment]
I'm sorry I can't even use atom right now because of https://github.com/atom/atom/issues/8551 Will try again tomorrow

**Comment by christyharagan** [comment]
Hey Basarat :)

Thanks for the response. Yup, I have been (loosely) following the new module resolution in typescript, and noticed that (woohoo) typescript knows how to follow node_modules, which is awesome.

So you are right, really, the problem comes with explicit typings files, a la definitely typed - node.d.ts being the obvious one.

Thanks - as always - for your support on this (and a great plugin, in general). Let me know if I can help.

**Comment by basarat** [comment]
@christyharagan I just added `node` typing to both projects https://github.com/basarat/ts-npm-module and https://github.com/basarat/ts-npm-module-consume and they still build without error (this is because the generated `.d.ts` does not reference node.d.ts)

Would it be possible to get a working sample with the issue, would help expedite a workaround ... I am sure the issue is there ...

**Comment by fmarsoni** [comment]
Hi
I tried to use this feature but the generated .d.ts file references node.d.ts
Using 6.0.0

**Comment by basarat** [comment]
Please try version `6.0.1` with *native* support used from Latest TypeScript

 https://github.com/TypeStrong/atom-typescript/blob/02555cdf7aff657d223d3e69d364b7c4c5b9e8d5/README.md#npm-module-support 

Raise concerns if issues still exist :rose:
