### ISSUE TITLE
atom-typescript emits ASCII text with CRLF line terminators

### ISSUE THREAD

**Issue by eldertfrancke** [TypeStrong/atom-typescript#547]
Atom-typescript on Linux emits ASCII text with CRLF line terminators.
Command line execution of a javascript file with a shebang results in the following error:
`: No such file or directory`

The following command fixes the error
`dos2unix [file.js]`

**Comment by Cu3PO42** [comment]
As far as I know, that's simply the TypeScript default.

Related: #545

**Comment by Narquadah** [comment]
No, it's not a TypeScript default. I just tested it with tsc and it emits LF on OS X. However, atom-typescript emits CRLF.
