### ISSUE TITLE
Use IPC for child process

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#55]
See : https://github.com/TypeStrong/atom-typescript/commit/7cd7522ad3a32a4681a57bfee89107cc73d31ad0#commitcomment-9605599 

And `on('message')` and `.send`

**Comment by basarat** [comment]
@csnover would love your test on `mac` for this : https://github.com/TypeStrong/atom-typescript/commit/25c03869527aa5e59e19524f640481768958ac75 before I push to APM. 

Thanks!

**Comment by csnover** [comment]
@basarat On master now, seems to be working.

**Comment by basarat** [comment]
:heart:
