### ISSUE TITLE
Add option to ignore missing tsconfig

### ISSUE THREAD

**Issue by unional** [TypeStrong/atom-typescript#551]
I'm using systemjs with typescript as the transpiler.  In this configuration there is not need to have a tsconfig file.  But atom-typescript would keep complain about it

**Comment by nycdotnet** [comment]
Without a tsconfig.json file, how would atom-typescript know that it should use systemjs versus amd, commonjs, etc?  How about other compilation settings like noImplicitAny?

**Comment by unional** [comment]
In systemjs it has its own `config.js` file.  The file name can change and is specified in the `package.json`. Inside the `config.js` file, there is a typescriptOptions object which can specify further settings.

**Comment by unional** [comment]
e.g., in the `package.json`:
````
  "jspm": {
    "directories": {
      "baseURL": "src/client"
    },
    "dependencies": {
      "jquery": "github:components/jquery@1",
      "ts": "github:frankwallis/plugin-typescript@^2.0.7",
      "underscore": "npm:underscore@^1.8.3",
      "when": "github:cujojs/when@^3.7.3"
    },
    "devDependencies": {
      "typescript": "github:mhegazy/typescript@v1.5-beta2"
    }
  }
````
The `directories` specify the config file is `src/client/config.js`, you can also specify a different file name using `config` property.

Inside the `config.js`:
````
    "transpiler": "typescript",
    "typescriptOptions": {
        "noImplicitAny": false
    },
    "packages": {
        "mysource/**/ts": {
            "defaultExtension": "ts"
        }
    },
````
which specify specific paths will use typescript.  It is all configurable.

**Comment by blakeembrey** [comment]
This is unrelated to the issue at hand, except that I would also like to ignore the missing `tsconfig.json` sometimes - sometimes I'm just hacking on a quick script and using `ts-node` (https://github.com/blakeembrey/typescript-node). Most of the options are all defaulted anyway, and if defaults should need to be configurable they could live in the plugin settings.

**Comment by unional** [comment]
@blakeembrey , definitely no need to create another issue.  It just another scenario that has the same cause (error on missing tsconfig) and need same solution (add option to ignore it).

The question is, besides adding an option to ignore it, is there an alternative solution?  IMO the option is suffice.

**Comment by basarat** [comment]
> except that I would also like to ignore the missing tsconfig.json sometimes - sometimes I'm just hacking on a quick script and using ts-node

We have a command `create tsconfig.json file` to decrease the barrier.

That said we support lose files *only if the current file is a `.d.ts` file*. For `.ts` files I really wish people to use tsconfig.json. 

I don't want to maintain a lose mode that does any transpilation (non issue for a .d.ts)

**Comment by mgiraldo** [comment]
i am also hacking on a single typescript file (that is part of a static html/css site) and manually compile/watch it and atom is complaining a lot, getting in the way: the status bar jumps up and down and i get errors where there is none (eg my scss folder doesnt need a tsconfig file, or does it?)

**Comment by basarat** [comment]
> my scss folder doesnt need a tsconfig file, or does it

@mgiraldo That is an issue with atom, we haven't been able to reproduce it... but sometimes atom fails to detect a tab change (you will see that the *grammar* will be stuck at TypeScript as well). We don't get notified that the tab change and try to get typescript stuff for a non typescript file.

**Comment by jonathandelgado** [comment]
Adding an option to just take the default settings (the settings from create tsconfig) if a tsconfig is missing would be great

**Comment by jeffschwartz** [comment]
I agree with @basarat and would also like to point out that requiring the file is not limited to just this plugin alone, as I believe the MS VS Code editor and the Sublime plugin also require its presence in order to identify typescript projects. Too many config options would IMHO just add more complexity to what should be and currently is a very straight forward and well understood process.

**Comment by unional** [comment]
Well, adding option or not can be discussed. But the use cases (`jspm` and loose write up) should be handled with grace, right? 🌷 

One question to ponder on is this: are we considering `atom` with `atom-typescript` an IDE or an editor?
IDE: Yeah, a project based, enforcing `tsconfig.json` make sense.
Editor: Nope, there is no project needed. I just want to use it like a text editor with some bells and whistles.

**Comment by wowatarasov** [comment]
I have the error: No tsconfig for current file.
