### ISSUE TITLE
Package load is slow (~800ms)

### ISSUE THREAD

**Issue by gabriel** [TypeStrong/atom-typescript#552]
Via Timecop:

![2015-09-02 at 1 32 pm](https://cloud.githubusercontent.com/assets/2669/9643485/29b4228c-5177-11e5-8eab-f632a7ae8440.png)

**Comment by nycdotnet** [comment]
It's a long term goal to make package loading faster for atom-typescript, but it's unlikely to happen for a while.  The main problem is that atom-typescript runs the TypeScript language service in an external process which takes a while to spawn.

I suspect Bas would be willing to take a pull request to defer spawning that process until the first .ts or .tsx file is opened, if you're willing to put something like that together.

**Comment by basarat** [comment]
> I suspect Bas would be willing to take a pull request to defer spawning that process until the first .ts or .tsx file is opened, if you're willing to put something like that together.

We already do that. Ref https://github.com/TypeStrong/atom-typescript/blob/c644fefe78b1add0e298d8baf4382d1887dfcb45/lib/main/atomts.ts#L316

But we have a *lot of files* and a *lot of them `import` external npm modules*. These all need to be made *lazy*. Up for grabs :rose:

**Comment by mrmckeb** [comment]
I'd like to point out that this package is much slower on a lower powered device. On my Surface Pro 2 (mid-range in power) this package is often over 5 seconds - I've seen it take 6+ seconds.
![image](https://cloud.githubusercontent.com/assets/5043083/10906136/2826a87c-8273-11e5-8382-d8fa56da93d0.png)

**Comment by PaulBGD** [comment]
I have a very fast computer with an SSD, and it takes 1500ms to load the package.

**Comment by intellix** [comment]
3278ms for me here on a MBP
