### ISSUE TITLE
Importing modules Vs importing definitions

### ISSUE THREAD

**Issue by vjau** [TypeStrong/atom-typescript#554]
Hi everyone, there is something i don't get.
I'm trying to create a react / tsx project in atom typescript.
In a file, i'm using the React module to create a class with usual React.createClass() function.
The framework i'm using (Meteor) provides me with the React module in the global scope, so i don't need to import anything.
But for the typescript compiler to be happy, i add
```ts
import * as React from "react";
```
on the first line,  to import definitions which have been previously correctly installed. 

Now the problem is that in the generated code, be it js or jsx, this following line 
```ts
import * as React from "react";
```
is still generated, hence the loader (System.js in my case) still try to import the React module which doesn't exist.
Is it normal that this import is still there in the generated code although Typescript knows that it's only for his own (== type checking) use ?

What am i not getting ?
Thank you in advance for your help.

**Comment by Cu3PO42** [comment]
You can use reference comments to only include type definitions.

    /// <reference path="path/to/type/definition.d.ts"/>

**Comment by vjau** [comment]
@Cu3PO42 i know, but i thought that import/export and tsconfig.json finally solved the ///<reference inclusion burden ?

**Comment by basarat** [comment]
> Now the problem is that in the generated code, be it js or jsx, this following line
import * as React from "react";
is still generated


You have compiler target set to `--target es6`. Please target `es5` for any *codegen* transform to happen on ES6 import. If you still have concerns about this raise to Microsoft/TypeScript or feel free to ask further questions here :rose:
