### ISSUE TITLE
Evergrowing number of pending requests

### ISSUE THREAD

**Issue by Ablu** [TypeStrong/atom-typescript#556]
Hello,

My number of pending request goes up without end, rendering most functionality of the plugin useless :(

I already asked about this on gitter:
https://gitter.im/TypeStrong/atom-typescript?at=55eb508a24228c321f1ae23d

My increasing pending request number: https://dl.dropboxusercontent.com/u/45541625/2015-09-05-222751_74x37_scrot.png

My installed version of the plugin: `6.0.2`
Atom: `1.0.9`

**Comment by basarat** [comment]
> My number of pending request goes up without end,

You probably have a `tsconfig.json` located *high up in the directory tree* globbing a *lot of files* ... which is slow

**Comment by Ablu** [comment]
This does not seem to be the case, I have no tsconfig.json in the part 
folders. Also the tsconfig atom displays below the editor window is the 
right one.

The number of ts files is moderate I think. I reference angular2 which 
has a couple of .ts files, but nothing which should cause this lag I 
think? I actually only have 2 .ts files. Anything else are angular .ts 
files.

~~~
~/web_playground/angular_grid_editor (master *) $ find -name "*.ts"| wc -l
377
~/web_playground/angular_grid_editor (master *) $
~~~

Visual Studio Code does not have any issue to handle the files either...

**Comment by basarat** [comment]
Consider `getProjectFileDetails` was hanging ... can you see if there are any errors in the dev tools console (https://github.com/TypeStrong/atom-typescript/blob/master/CONTRIBUTING.md#workflow)

**Comment by Ablu** [comment]
No. There are no errors in the dev tools. I also tried to change my tsconfig to include:
~~~
        "./src/app.ts"
~~~
only.

I made a small screencast showing the problem: https://drive.google.com/file/d/0B8JQlPw3d8dCSjZRWHl3UzJoT1E/view?usp=sharing (please ignore the flickering on the lower left, that is my second screen being smaller than my primary one :))

**Comment by basarat** [comment]
Beyond filesGlob, we do some processing of `/// reference` tags + `node_modules/package.json` + `node_modules/typescript.main` 

So try deleting node_modules for a bit? PS: Sorry about this

**Comment by Ablu** [comment]
Hm? I have no `node_modules/package.json` or `node_modules/typescript.main` file...

Also node_modules contains my dependencies (angular) and that contains the typescript definitions...

So if I remove `node_modules` I won't be able to compile due to missing references... right?

**Comment by basarat** [comment]
Can I get a copy of the repo? This will help me debug faster. Thanks :rose:

**Comment by Ablu** [comment]
See https://drive.google.com/open?id=0B8JQlPw3d8dCd0xZbERCMHRtdmM
I bundeled the node_modules and bower_components, Simply try to edit the `src/app.ts`

**Comment by basarat** [comment]
> See https://drive.google.com/open?id=0B8JQlPw3d8dCd0xZbERCMHRtdmM
> I bundeled the node_modules and bower_compone

Thanks. I just sent an access request :rose: using my gmail account `basaratali` `gmail.com`. I don't have permissions to get that file till you grant it :)

**Comment by Ablu** [comment]
Uh... I thought it would be available for everybody... Sorry... Access
granted.

**Comment by basarat** [comment]
The `filesGlob` was wrong (misspelled). You had the following: 

```json
{
    "version": "1.5.0",
    "compilerOptions": {
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es5",
        "module": "commonjs",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "outDir": "dist/js/cjs"
    },
    "fileGlobs": [
        "./src/app.ts"
    ]
}
```

This meant we were looking at *all the .ts files* in the project (including node_modules and bower). Fix  and everything will work *much snappier*: 

```json
{
    "version": "1.5.0",
    "compilerOptions": {
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es5",
        "module": "commonjs",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "outDir": "dist/js/cjs"
    },
    "filesGlob": [
        "./src/**/*.ts"
    ]
}
```

Sorry for not providing a better *detection* of this possible user error. :rose:

**Comment by Ablu** [comment]
Haha. Thanks a lot. Will try how it works if i add a few more files as soon
I am home again.

**Comment by Ablu** [comment]
Hm. How do I now get the compiler to recognize the angular module? I now use

~~~ ts
{
    "version": "1.5.0",
    "compilerOptions": {
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es5",
        "module": "commonjs",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "outDir": "dist/js/cjs"
    },
    "filesGlob": [
        "./src/**/*.ts",
        "!./node_modules/**/*.ts"
    ],
    "files": [
        "./src/app.ts",
        "./src/listview.ts"
    ]
}
~~~

as config file. But with that I get:
`Cannot find module 'angular2/angular2'`

If i remove the `!` before `./node_modules/**/*.ts` it works but is slow again. What does the `!` do? I am unable to find it in the documentation (https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#filesglob)

**Comment by nycdotnet** [comment]
The ! means "not".  I'm assuming angular 2 ships with its own d.ts file.  You may wish to explicitly reference that in the filesGlob which should override the directory cancel.

**Comment by Ablu** [comment]
Ah ok... I thought it would be some magic for setting reference but not 
project files since so many people seem to use it even though the folder 
would not be included in their config anyway... Thanks for clearing me 
up. Everything works now!
