### ISSUE TITLE
group `tsconfig` extensions (e.g. filesGlob) under a different key

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#56]
This is because I feel like I need to add more keys e.g. to support `tsx` from `tsconfig.json` (https://github.com/fdecampredon/jsx-typescript/) as an alternative to `require('typescript')` 

@csnover your thoughts on this?

**Comment by basarat** [comment]
So instead of 

```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false
    },
    "filesGlob": [
        "./**/*.ts"
    ]
}
```
we would have 
```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false
    },
    "typestrong":{
        "filesGlob": [
            "./**/*.ts"
        ]
    }
}
```

Better now than latter.

**Comment by basarat** [comment]
This is ready to go in `v1` https://github.com/TypeStrong/atom-typescript/blob/master/docs/CHANGELOG.md

**Comment by csnover** [comment]
Honestly, I’m not sure why something like `filesGlob` isn’t part of the actual tsconfig.json spec.

**Comment by csnover** [comment]
(Which I realise doesn’t actually answer the original question… but man.)

What are the extra keys?

**Comment by basarat** [comment]
Having slept on it I feel like this extra grouping is needless. I'll revert for now. See reasons below.

> Honestly, I’m not sure why something like filesGlob isn’t part of the actual tsconfig.json spec.

I agree. Keeping `fileGlob` at the root might just push it for standardization. 

> What are the extra keys?
 
Just `filesGlob` right now : https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#filesglob but will be adding more stuff later (e.g. option to specify a different `languageService` endpoint (like `tsx`). I guess those too do not need to be grouped under `typestrong` which isn't really a *functional* name and just namespacing.
