### ISSUE TITLE
Support for TypeScript npm modules without declaractions

### ISSUE THREAD

**Issue by Bobris** [TypeStrong/atom-typescript#560]
Enhancement proposal:

I have simple npm module which contains "only" index.js (in commonjs) and index.ts - its source.
But its import cannot be found and typechecked by current atom-typescript because it requires index.d.ts and also definition of that in package.json. First it could be more clever and just change extension from main index.js. but if it cannot find index.d.ts just live with index.ts...

Another option would be to make moduleResolution customizable - like ts.CompilerHost can do.
It would probably need crazy escaping of javascript in tsconfig.json, but ultimately it would allow everything.

till now I used nasty `import * as xxx from "node_modules/xxx/index";` but now it should be possible much nicer `import * as xxx from "xxx";`

**Comment by basarat** [comment]
> But its import cannot be found and typechecked by current atom-typescript because it requires index.d.ts and also definition of that in package.json

Just add `declaration:true` to the tsconfig to get a `index.d.ts` and it should *just work*. 

> till now I used nasty import * as xxx from "node_modules/xxx/index"; but now it should be possible much nicer import * as xxx from "xxx";

Should just work. Also you can use a `typings` field to point to an `index` field. Checkout a package that I just pushed : https://www.npmjs.com/package/onresize for an example

**Comment by basarat** [comment]
Closing as it already work ... unless there is a bug ... in which case feel free to comment :rose:

**Comment by Bobris** [comment]
Yes, it is true that it works with declaration:true, but it means to have much more files which have basically duplicate information and when you have a lot of modules its add up, so it would be nice to support this also without d.ts files. Think of "Pure" TypeScript modules (just *.ts, no *.js, no *.d.ts).

Second part with customizable module resolver would allow as support both ways in mean time until people will republish all modules with new way.

**Comment by basarat** [comment]
> Yes, it is true that it works with declaration:true, 

Thaks for the verification. This is new stuff so always good to get more :eyes: :rose: 

> Think of "Pure" TypeScript modules (just *.ts, no *.js, no *.d.ts)

The issue with that is that a `.ts` file becomes a part of a *compile* context. and needs to be compiled ... which slow. The choice to only use `.d.ts` was made by the TypeScript team btw.

Reference : https://github.com/Microsoft/TypeScript/blob/971c7770314467964c536242becad2555ef9c758/src/compiler/program.ts#L70-L73 

> Second part with customizable module resolver would allow as support both ways in mean time until people will republish all modules with new way.

Definitely. But better if done upstream (microsoft/typescript)

**Comment by Bobris** [comment]
You are absolutely right that it should be solved upstream. I just tried you as very responsive person, thanks for all your work.

**Comment by basarat** [comment]
Yeah, the main issue is a compiler refactoring to support *internal* vs. *external* `.ts` files. For all purposes `.d.ts` are already considered external so it was easy to *jank* into the current compiler code to support node_module .d.ts lookup :wink: :rose:

**Comment by s-panferov** [comment]
@Bobris @basarat 

this is related https://github.com/TypeStrong/atom-typescript/issues/562#issuecomment-147620723
