### ISSUE TITLE
Import file quickfix and es6 modules

### ISSUE THREAD

**Issue by GabiGrin** [TypeStrong/atom-typescript#561]
In our latest project we are using the es6 syntax for importing modules: `import {Bob} from './bob'`
When using the add module quick fix, it will only use the "require" notation. I saw that it's hard-coded in the code.

I've build a [naive plugin](https://atom.io/packages/typescript-modules-helper) that does it for me but I would like to suggest and possibly implement this feature in this plugin.

If this sounds like a good idea I'll be happy to implement :)

**Comment by basarat** [comment]
> When using the add module quick fix, it will only use the "require" notation. I saw that it's hard-coded in the code

Sure ... add a PR with a quickfix to use es6 notation if you want `import * as foo from "foo";`
