### ISSUE TITLE
Resolve a library that fully written in TypeScript

### ISSUE THREAD

**Issue by s-panferov** [TypeStrong/atom-typescript#562]
Hello!

In our company we have several libraries fully written in TypeScript and we want to use them as-is in other projects.

E.g. we have a library called `arui`, when we have a file `src/lib/assign.ts`

In another project I have a structure:

```
index.ts
node_modules/arui
```

And inside `index.ts` I have an import declaration:

```
import { spread } from 'arui/src/lib/assign';
```

Result:
![listing ts - users panferov-s workspace alfa-listing - atom 2015-09-08 19-19-19](https://cloud.githubusercontent.com/assets/198327/9740668/907b3cbc-565e-11e5-9039-44244dd885a6.png)

```
Cannot find module `arui/src/lib/assign`
```

The module correctly resolves by tools like `https://github.com/s-panferov/awesome-typescript-loader` or `https://github.com/jbrantly/ts-loader`. Can we teach `atom-typescript` to see the files?

E.g. it worked correctly with symlinks before merging `node_modules` support into TypeScript:

```
arui -> node_modules/arui
```

**Comment by basarat** [comment]
> it worked correctly with symlinks before merging node_modules support into TypeScript

Does the tsconfig have a `declaration : true` in it? Is there a `arui/src/lib/assign.d.ts` present? 

This is how the official node_modules support was implemented in typescript.

**Comment by s-panferov** [comment]
@basarat, no, there are no `.d.ts` file and no `declaration : true`, because the library is *fully* written in typescript and all client are written in typescript too I don't see any reason to compile it.

**Comment by basarat** [comment]
> here are no .d.ts files and no declaration : true,

This isn't supported at the moment. Please see this comment : https://github.com/TypeStrong/atom-typescript/issues/560#issuecomment-138456739 :rose: Waiting for an upstream resolution :rose:

**Comment by s-panferov** [comment]
@basarat thanks for the answer. Do you know if any related issue exists in TypeScript repo?

**Comment by basarat** [comment]
> Do you know if any related issue exists in TypeScript repo?

Doesn't. If you create it please tag me in :rose:

**Comment by s-panferov** [comment]
@basarat the issue was resoled by TypeScript team: 

Issue: https://github.com/Microsoft/TypeScript/issues/5225
PR: https://github.com/Microsoft/TypeScript/pull/4911

**Comment by basarat** [comment]
Cheers :rose:
