### ISSUE TITLE
Holds onto obsolete type declarations

### ISSUE THREAD

**Issue by psnider** [TypeStrong/atom-typescript#563]
Using:  
- atom-typescript v6.0.2
- typescript v1.5.3

It seems that sometimes my edited declaration files are not considered by the plug-in.

In one case, I had renamed a field, yet wherever I used the new name, the plug-in showed an error
saying that the types were incompatible, and suggesting that I change the name back to the old one.
(BTW, I grepped my code base, and the old field name was no longer present anywhere.)

I am constantly building via the command line at the same time, and _tsc_ reported no errors.

Is it possible that the plug-in cached the results of parsing my declaration file?
Exiting _atom_ completely seemed to clear the problem.

**Comment by basarat** [comment]
> Is it possible that the plug-in cached the results of parsing my declaration file?

possible. Instead of completely exiting please use sync : https://github.com/TypeStrong/atom-typescript#sync

>  I had renamed a field,

Did you do this *externally* ... i.e. outside atom / atom-typescript ?

**Comment by psnider** [comment]
I definitely edited the field from within atom, as I don't use any other editor for my TypeScript projects.

However, I did rename the problematic file at the command line, as I wanted to change the case of the name, and the Mac OS file system preserves but doesn't distinguish case. Perhaps this was the cause? The name went from Person.d.ts to P to person.d.ts

I often perform file system tasks at the command line, as its faster.
I also run most git commands from the command line, or from the GitHub app.
