### ISSUE TITLE
Autocomplete is taking time to appear when a new file is added

### ISSUE THREAD

**Issue by Raathigesh** [TypeStrong/atom-typescript#565]
When I add a new .ts file, autocomplete doesn't appear right away. It takes about a minute to appear back again. Even during the initial load I can observe this delay. The project is fairly large. Is this a known behavior or am I doing something wrong ?

**Comment by basarat** [comment]
> The project is fairly large. Is this a known behavior or am I doing something wrong

Probably expanding the file glob is taking a long time. Need to look at a better globing library at some point

**Comment by basarat** [comment]
Note: I have a project with 300+ ts files with around 300 lines each ... its under a second for that :rose:

**Comment by Raathigesh** [comment]
I don't have that many files though. I will try to pin point the cause. Thank you for maintaining such as awesome project. Best typescript development experience I have used so far :100:

**Comment by Raathigesh** [comment]
All seems to be fine now. Closing the bug!
