### ISSUE TITLE
Bottom bar "jumps" every time cursor is moved

### ISSUE THREAD

**Issue by tmandry** [TypeStrong/atom-typescript#567]
I just installed this plugin for the first time and am having this issue (YouTube downscaled to 360p but I can send a higher-res version if needed):

https://www.youtube.com/watch?v=kNhsq2UQy3o

Only plugins enabled are TypeScript (6.0.5) and Linter (1.5.1). Atom is latest (1.0.11) and the problem persists across restarts.

There's also a light bulb that shows up by the line numbers on every single line, not sure if that's intended (it is kind of distracting!) Other than that, everything else seems to be working fine.

**Comment by nycdotnet** [comment]
Lightbulb is a helper notification - hit alt+enter to see what it can do for you.  Its current behavior is intended (though we would be open to discussing improving it).

Regarding the jumping bottom bar - it looks like you're running in a portrait setup.  It may be Chrome doing some layout inconsistently as you work.  Any chance you can widen your window and see if it still happens (or significantly narrow it)?

Also, do me a favor and open the dev tools (cmd+alt+i in Atom, which is just Chrome dev tools) and look in the elements tab to see if there is an element that is being added and removed consistent with what you're seeing.  That should give us more info.

Thanks for the report.

**Comment by basarat** [comment]
@tmandry You have it at exactly an *evil* width. If you shrink it further it will stick to the *two line format* ... of you make it a bit bigger it will stick to the one line format. 

Definitely a bug in our layout  .... open for grabs :rose: 

About the light bulb .. what steve said + docs : https://github.com/TypeStrong/atom-typescript#quick-fix

**Comment by ealves-pt** [comment]
Possible behaviour fix in PR #644

**Comment by basarat** [comment]
https://github.com/TypeStrong/atom-typescript/releases/tag/v7.1.5 :rose:
