### ISSUE TITLE
Failed to expand the glob for the project when I run mongodb in the project folder

### ISSUE THREAD

**Issue by snowcxt** [TypeStrong/atom-typescript#568]
I have my local mongodb running (under temp/db folder) and open the Atom. Then I get error:

Failed to expand the glob for the project file
EBUSY: resource busy or locked, scandir: 'xxxxx\temp\db\mongod.lock'

BTW I've excluded the temp fold in the filesGlob:
`"!./temp/**/*"`

**Comment by basarat** [comment]
> BTW I've excluded the temp fold in the filesGlob:

Yup. But out filesGlob library `glob-expand` still tries to *go into the folder*. Previous report : https://github.com/TypeStrong/atom-typescript/issues/332 

Up for grabs :rose:
