### ISSUE TITLE
Add support for `tsx`. 

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#57]
If a file belongs to a `project` that has `tsx` enabled then `getOrCreateProgram` will `require` https://github.com/fdecampredon/jsx-typescript/ instead of `typescript`. 

Including @fdecampredon into the conversation by force mentioning :stuck_out_tongue: :heart:. Just curious if we should expect the `languageService` to just work?

Refs : https://github.com/TypeStrong/atom-typescript/issues/56

**Comment by fdecampredon** [comment]
yup In fact I was able to use brackets-typescript with it :D, however the 'formatting' part won't work, I had to disable it, and you don't have completion on attributes due to https://github.com/Microsoft/TypeScript/issues/1947 and https://github.com/Microsoft/TypeScript/issues/1926
