### ISSUE TITLE
Typescript TS file fold generated files in the tree view

### ISSUE THREAD

**Issue by matheo** [TypeStrong/atom-typescript#571]
Hi all
I wonder if it's possible to implement a folding option for TypeScript like [WebStorm's one](https://www.youtube.com/watch?v=Sl1Uk3zT5Fg&t=33) so transpiled files are somehow more navigable.
Thanks in advance!

**Comment by tebanep** [comment]
Must have feature!

**Comment by basarat** [comment]
> I wonder if it's possible to implement a folding option for TypeScript

Duplicate of : https://github.com/TypeStrong/atom-typescript/issues/253 see discussion there. Some people like the way it is. Will only be done if the `treeview` provides *native* support for it :rose:
