### ISSUE TITLE
Typescript compiler takes a long time after a new file is added

### ISSUE THREAD

**Issue by tomitrescak** [TypeStrong/atom-typescript#573]
Hi. First KUDOS to this amazing plugin. Microsoft has a long way to go to catchu up with you guys ;)

I have a small problem. 
When I add a new file, the compilation vecomes stalled on follosing task "getProjectFileDetails" and spins processor to the max. This lasts about 1-2 minutes, then compilation runs as expected. This happes after I add any file to the project.

**Comment by basarat** [comment]
Sound like a dupe of https://github.com/TypeStrong/atom-typescript/issues/332

Can you try the [workaround](https://github.com/TypeStrong/atom-typescript/issues/332#issuecomment-140287071)

**Comment by tomitrescak** [comment]
Indeed. Thanks!

**Comment by basarat** [comment]
We need a better globing library :)
