### ISSUE TITLE
How not to compile on save?

### ISSUE THREAD

**Issue by gyzerok** [TypeStrong/atom-typescript#574]
I'm using webpack for bundling my code and would like to prevent atom-typescript to compile to .js on save. How do I do that?

In my case I do want use this package only for type checks and autocomplete.

**Comment by basarat** [comment]
For future search results : https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#i-dont-want-atom-typescript-compiling-my-js

:rose:
