### ISSUE TITLE
Import paths aliases

### ISSUE THREAD

**Issue by tomitrescak** [TypeStrong/atom-typescript#577]
I'm not sure if this has been handled in #132 but I have a request for possibility to use import path aliases. In webpack I can easily configure following alias:

```
resolve: {
    extensions: ['', '.js', '.jsx'
      //, '.ts', '.tsx'
    ],
    alias: {
      app: path.join(__dirname, '../app'),
    },
  },
```

From that moment on, I don't have to write painful paths like `../../../../component/view/me' 

While application compiles well with webpack, typescript plugin is announcing errorrs as it does not recognise this config. Would you consider adding the section in the tsconfig for aliases, or any other solution?

Thanks!

**Comment by basarat** [comment]
> typescript plugin is announcing errors as it does not recognise this config. Would you consider adding the section in the tsconfig for aliases,

This is (was https://github.com/Microsoft/TypeScript/issues/2338#issuecomment-139561751) being tracked by this issue https://github.com/Microsoft/TypeScript/issues/2338 in typescript core. 

Unless I have a better idea ... I'd wait for them to come up with a solution :rose:

**Comment by tomitrescak** [comment]
Yup, I was reading through that thread, was hoping that you guys will be faster than MS, as you already are ;) Anyway, I'll close this so that it does not polute the list.
