### ISSUE TITLE
Request: support `moduleResolution` compiler option in `tsconfig.json`

### ISSUE THREAD

**Issue by horiuchi** [TypeStrong/atom-typescript#578]
via: https://github.com/Microsoft/TypeScript/wiki/Compiler%20Options

This option is available on TypeScript 1.6.

**Comment by basarat** [comment]
Note workaround: if you compile with `module commonjs` it *automatically* switches to node resolution ;) :rose:

**Comment by basarat** [comment]
Up for grabs

# Implementer's guide 

Code is here : [tsconfig.ts](https://github.com/TypeStrong/atom-typescript/blob/de68e8e5d04eaad3d9c9b6b6a3ec5327de03c23d/lib/main/tsconfig/tsconfig.ts#L13-L18)

**Comment by horiuchi** [comment]
:+1:
