### ISSUE TITLE
Can't find a way to disable autocomplete when not needed

### ISSUE THREAD

**Issue by DiThi** [TypeStrong/atom-typescript#579]
When I write anything like... "function(){" and then I press enter to go to the next line, the first item of the menu ("arguments" in this example) is added to the text instead of going to the next line, unless I remember to press esc every time.

It's very annoying. Can I change the default key of confirmation? Or can I disable autocomplete for some cases? Or enable it only when writing specific characters? Or at least disable autocomplete completely to open it manually with ctrl-space?

**Comment by basarat** [comment]
> Or can I disable autocomplete for some cases?

Up for grabs : https://github.com/TypeStrong/atom-typescript/blob/de68e8e5d04eaad3d9c9b6b6a3ec5327de03c23d/lib/main/atom/autoCompleteProvider.ts#L177-L181 :rose:
