### ISSUE TITLE
The keyword abstract is not colored correctly

### ISSUE THREAD

**Issue by daniel-a-melo** [TypeStrong/atom-typescript#581]
The keywork `abstract` introduced by TypeScript 1.6 is does not get the keyword color. 

Atom 1.0.11 on Ubuntu Linux 12.04
atom-typescript 6.0.9

**Comment by basarat** [comment]
Up for grabs.

# Guidance 

Code here : https://github.com/TypeStrong/atom-typescript/blob/master/grammars/typescript.cson Probably follow whats there for `public` / `private` etc :rose:

**Comment by booooh** [comment]
I looked at the file you linked here:
https://github.com/TypeStrong/atom-typescript/blob/master/grammars/typescript.cson

and there seems to be a typo (that's copy-pasted 4 times) - puclic instead of public.
See lines 168, 191, 217, 236

**Comment by basarat** [comment]
> puclic instead of public

Fixed :rose:

**Comment by mjohnsonengr** [comment]
I noticed this one myself today; I'll take a look at this this weekend if I have free time :+1:

**Comment by mjohnsonengr** [comment]
@basarat that looks like a refactor, replacing the grammar? Does that mean you're leaving these grammar issues open to be verified/fixed after the new grammar?

**Comment by basarat** [comment]
@mjohnsonengr yes, I would close these but these need to be verified after the merge + pointed at as valid bugs that exist right now.

**Comment by basarat** [comment]
Should work with release https://github.com/TypeStrong/atom-typescript/releases/tag/v8.0.0 :rose: If not raise issue at https://github.com/Microsoft/TypeScript-TmLanguage/issues and link me :rose:
