### ISSUE TITLE
Newest version atom does not support your package

### ISSUE THREAD

**Issue by jeffaustin81** [TypeStrong/atom-typescript#584]
<img width="1172" alt="screen shot 2015-09-17 at 8 17 09 pm" src="https://cloud.githubusercontent.com/assets/10277396/9951263/1c8b6c4c-5d79-11e5-9baf-2517be696ebc.png">

**Comment by basarat** [comment]
duplicate of https://github.com/TypeStrong/atom-typescript/issues/583. Seems mac only bug.

**Comment by basarat** [comment]
Feel free to chime in here : https://github.com/TypeStrong/atom-typescript/issues/583#issuecomment-141353810 :rose:
