### ISSUE TITLE
QuickFix importing uses `import ... = require()` in target ES6

### ISSUE THREAD

**Issue by mizchi** [TypeStrong/atom-typescript#586]
In ES6 modules, we can't use `import ~ require`. We have to use `import ~ from '...'`

**Comment by basarat** [comment]
Up for grabs

# Docs 

https://github.com/TypeStrong/atom-typescript/blob/master/CONTRIBUTING.md#quickfix

Please add a new quickfix. Something like `es6 import` :rose:
