### ISSUE TITLE
Add basic rename a variable / refactoring support

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#59]

**Comment by nycdotnet** [comment]
On a plane and thinking about future wish list stuff.
  * extract interface from class, module, or function
  * copy type from variable
  * implement stub (to enable "use first" programming flow).  doStuff(p1 : string) doesn't exist on MyClass - would you like to implement it?
  * "Declare this" refactoring on an instantiated variable.
  * Declare all refactoring on a constructor function

**Comment by basarat** [comment]
Wishlist 

* [ ] rename file module (this is a big pain and the reason why we added `///ts:import` transform in the first place)

**Comment by basarat** [comment]
Reuse this if you can : https://github.com/atom/find-and-replace/blob/master/lib/find-view.coffee
