### ISSUE TITLE
atom-typescript specific settings shouldn't be in tsconfig.json

### ISSUE THREAD

**Issue by slikts** [TypeStrong/atom-typescript#594]
It's really untidy to have atom-typescript specific settings mixed in with normal TS settings. It's not clear that they relate to atom-typescript to anyone unfamiliar with atom-typescript. It confused me when I started using atom-typescript, since I'm also new to TS. The norm is for tools to create their own config files, like tsd does with tsd.json. This makes it easy to manage the settings and prevents confusion.

**Comment by basarat** [comment]
> This makes it easy to manage the settings and prevents confusion

Agreed. However I'd rather it be under a key like `atom-typescript`. But I'm not looking forward to making that breaking change anytime soon.

**Comment by slikts** [comment]
Doesn't seem right to just close valid and unresolved issues…

**Comment by basarat** [comment]
> Doesn't seem right to just close valid and unresolved issues.

Sure. It's open and up for grabs.

# Implementor's guide

* Move all the atom-typescript specific stuff under `atom` key in `tsconfig.json`. 
* Update https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md
* Code needs to go here : https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/tsconfig/tsconfig.ts
* Republish as a major version and document the breaking change : https://github.com/TypeStrong/atom-typescript/blob/master/docs/CHANGELOG.md
* Also update the FAQ https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md

:rose:

**Comment by slikts** [comment]
You shouldn't put non-TS settings in the TS config file. It's invalid according to [its schema](http://json.schemastore.org/tsconfig), and coupling the TS and atom-ts settings makes them both more difficult to manage, because you need to edit JSON in cases where you would otherwise be able to just work with files. Every other tool uses their own config files too. It should just be `atomts.json` or something for this tool as well. It should also be fixed sooner than later because it's needed and putting off breaking changes makes implementing them harder.

**Comment by nycdotnet** [comment]
Thank you for your feedback.

**Comment by nickroberts** [comment]
Agreed. If I can get some time in the near future, I'll take a stab at this.

**Comment by nycdotnet** [comment]
Early on, the TypeScript team said they were OK with third-party extensions to the `tsconfig.json` file as long as they didn't conflict with first-party functionality.

The extensions used by atom-typescript (and now grunt-ts as of v5 beta) have been around for a long time and do not conflict with present or anticipated first-party functionality to my knowledge (if I am wrong here, please let me know).  They are also quite useful to thousands of developers in their present state.  Therefore, this seems like needless work for the person writing the change, the TypeStrong team, and our end users.

I don't see the value in taking a breaking change for this.  I appreciate your comments @slikts and @nickroberts, but I think your time might be much better spent on either improving atom-typescript's documentation for this issue (to lessen any confusion), to advocate for an official mechanism for third party extensions for `tsconfig.json` with the TypeScript team (in which case it would be worth taking a breaking change), or on our many other issues.

In particular, we could really use a globbing library that supports exclusions.

**Comment by basarat** [comment]
> Agreed. If I can get some time in the near future, I'll take a stab at this.

@nickroberts don't. Based on @nycdotnet's comments I've re-evaluated the stance and decided that the options we have *make a lot of sense for the community* (and its not just my opinion). 

All the options we have are documented here : https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#options 

I'll be (and have been in the past) very careful adding further extensions. We will no longer think of moving / or removing any of the options we have right now without *very strong justification*.
