### ISSUE TITLE
Syntax highlighting fails with shebang

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/atom-typescript#595]
I'm actually not sure where the best place to log this is, potentially it should be a change will Atom's language detection implementation. However, because of this line, https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson#L13, any file with the shebang `#!/usr/bin/env node` will be detected as JavaScript instead of TypeScript - even when it's a `.ts` file.

**Comment by basarat** [comment]
Verified. Indeed that happens now. 

Workaround : Change the detected language by either clicking the following 
 
![image](https://cloud.githubusercontent.com/assets/874898/9983919/47e40d70-6050-11e5-8df7-97df96f0de2d.png)

or using the `Grammar Selected : show` command.
