### ISSUE TITLE
Linter text not rendered correctly in multiline errors.

### ISSUE THREAD

**Issue by tomitrescak** [TypeStrong/atom-typescript#596]
![screen shot 2015-09-21 at 18 16 52](https://cloud.githubusercontent.com/assets/2682705/9987656/1c04cd7e-608d-11e5-9510-cab7ddfa6b51.png)

**Comment by basarat** [comment]
Also raised here : https://github.com/atom-community/linter/issues/893#issuecomment-141956253 Fix needs to go there :rose:

**Comment by tomitrescak** [comment]
Yes, sorry, I have realised that it's actually Linter problem not yours and forgot to close the issue :/
