### ISSUE TITLE
tsconfig.json is indented using hardcoded 4 spaces

### ISSUE THREAD

**Issue by slikts** [TypeStrong/atom-typescript#598]
All my other .json files use different indentation settings, but tsconfig.json generated by atom-typescript is indented using [hardcoded 4 spaces](https://github.com/TypeStrong/atom-typescript/blob/c69c21f4ca1541e58e993034302fc9032b9cfe5b/lib/main/tsconfig/tsconfig.ts#L708). It should probably use `FormatCodeOptions.TabSize` instead.

**Comment by basarat** [comment]
> It should probably use FormatCodeOptions.TabSize instead.

That is for `ts` file. Probably we should *stop writing tsconfig.json files*. This can be done if `filesGlob` is moved into an `atom` section and we no longer maintain `files` for the user. There are tradeoffs here but its been working well the way it is.
