### ISSUE TITLE
The TypeScript grammar Tab Length setting is ignored

### ISSUE THREAD

**Issue by slikts** [TypeStrong/atom-typescript#599]
The Settings -> Packages -> atom-typescript -> Settings -> TypeScript Grammar -> Tab Length setting doesn't seem to do anything, so using the TypeScript formatter causes code to be indented by 4 spaces by default regardless of what the Tab Length setting says.

**Comment by basarat** [comment]
> using the TypeScript formatter causes code to be indented by 4 spaces by default regardless of what the Tab Length setting says.

Yes. Instead use `formatCodeOptions` which is the typescript way of specifying formatting

**Comment by slikts** [comment]
So what's the point of the TypeScript grammar settings, why are they there?
