### ISSUE TITLE
Improve `import` auto-complete experience

### ISSUE THREAD

**Issue by danfma** [TypeStrong/atom-typescript#602]
When I write `import` and type TAB, the atom will autocomplete with `import from "path"`, which works and is great.

But almost the time I have to, after selecting the path and typing enter, go back manually to the import and put the {} manually.

I don't know if is possible but will be nice if after choosing the path the atom changed the cursor automatically to the position after the import, so I could just continue to choose the imported types.

DESIRED STEPS:
1. import $CURSOR (TAB);
2. import from "path $CURSOR (ENTER)";
3. import $CURSOR from "path";

;)

**Comment by danfma** [comment]
One alternative will be to write something like from "path" import {bla bla} and the atom then invert the code.

**Comment by basarat** [comment]
> DESIRED STEPS:

The current case is very close to what you want: 

1. import $CURSOR (TAB);
1. import from "path $CURSOR (TAB)"; `(this tab selects the shown path and auto complete takes you to the end of the line)`
1. (TAB) to go to next position: 
1. import $CURSOR from "path";

Basically don't press `enter` :+1: 

![tester](https://cloud.githubusercontent.com/assets/874898/10036409/dbc617b8-61ea-11e5-9b29-57711b1c4512.gif)

It is open for an improvement, but its a tricky area and an extra (unintutive tab...but if you know you know) isn't too painful :rose:

**Comment by danfma** [comment]
Hummm... I will check this but I think that I tried this way too! ;)
