### ISSUE TITLE
show method signature parameters whilst typing?

### ISSUE THREAD

**Issue by jmp909** [TypeStrong/atom-typescript#608]
Hi

I was wondering if there's a way to show method signature parameters as you type?

Visual Studio Code does it for instance:
![vscode](https://cloud.githubusercontent.com/assets/2184982/10061765/d67e38ee-6253-11e5-8ae9-5349dd9ea839.png)

with Atom, I can press ctrl+space when I open the parenthesis, but after that the signature disappears and is replaced with an error

![signature](https://cloud.githubusercontent.com/assets/2184982/10061707/35f5f5ce-6253-11e5-9d59-8989dc06db21.png)
![atomvars](https://cloud.githubusercontent.com/assets/2184982/10061718/5c6ec82a-6253-11e5-9cd0-a247d14bf952.png)

sorry if this has already been answered

(note I have a .d.ts for GreenSock here)

thanks
J

PS should this be moved to  https://github.com/AtomLinter/Linter ?

**Comment by basarat** [comment]
> PS should this be moved to

Definitely not, belongs here.

> I was wondering if there's a way to show method signature parameters as you type

Up for grabs :rose: Would have to be a completely new feature ... look at hover tooltip for ideas (much custom code).

**Comment by david-driscoll** [comment]
I've got a working PR for [OmniSharp/omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom/pull/525) that adds signature help, feel free to rip us off if you want to. Heaven knows we've ripped enough out atom-typescript.  :smile: :tada:

**Comment by pietrasiak** [comment]
Any update on this?

**Comment by sompylasar** [comment]
Dup of / related: https://github.com/TypeStrong/atom-typescript/issues/23
Related: https://github.com/atom/autocomplete-plus/issues/329

**Comment by fasa123** [comment]
Bracket Matcher enabled:

![bm_enabled](https://user-images.githubusercontent.com/7671649/26949899-0b79059a-4c9c-11e7-8c07-28effa003508.gif)


Bracket Matcher disabled:

![bm_disabled](https://user-images.githubusercontent.com/7671649/26949945-45fd4636-4c9c-11e7-9f2e-758df700b772.gif)

**Comment by vitorrd** [comment]
I'm actually not getting any autocompletion for methods, Bracket Matcher disabled or not.

**Comment by rasdaniil** [comment]
No progress on this feature by any chance?
