### ISSUE TITLE
Improved semantic view

### ISSUE THREAD

**Issue by tomitrescak** [TypeStrong/atom-typescript#609]
This is just a wishlist for extensions to your amazing plugin
- [ ] Improved semantic view to have a possibility to order items by name and possibly color different elements (variables with one color, functions with another)
- [ ] This is the wildest one ... I love to structure code as in C# using regions. So region support would be fantastic. Moreover, if those regions would be visible in semantic view and I would have a possibility to change their color to my liking. Awesome ;) For example have code folded as 

``` javascript
// [region My Cool Region][color=#ededed]
class Awesome {
}
// [endregion]
```

---

Note : Basarat changed the issue to not detract future readers: ~~Stop reading~~~
Bug fixed:
- [x] Have a possibility to view emitted source of TSX file with [cmd+shift+m] as it is possible to do with TS files, currently it says `No Source Found`

**Comment by basarat** [comment]
> Have a possibility to view emitted source of TSX file with [cmd+shift+m] as it is possible to do with TS files, currently it says No Source Found

Bug. Created : https://github.com/TypeStrong/atom-typescript/issues/612

**Comment by basarat** [comment]
> currently it says No Source Found

Can you double check, share the `tsconfig.json`? or try with a `.ts` file in the same project. 

It works for me : 

![image](https://cloud.githubusercontent.com/assets/874898/10063426/de945c9a-62b0-11e5-9929-c386d004c333.png)

**Comment by tomitrescak** [comment]
Not working for me ;(

![test](https://cloud.githubusercontent.com/assets/2682705/10063518/035c7b06-62b2-11e5-9cc5-d054cfce2eca.gif)

**Comment by tomitrescak** [comment]
The typescript TS files work well, the TSX is not working althought it is emited fine into the dist directory.

**Comment by basarat** [comment]
Is it possible to get the project, so I can repro?

**Comment by tomitrescak** [comment]
easy: https://dl.dropboxusercontent.com/u/3418607/TypescriptTSXErrorRepro.zip

try files in "app/components/app_publications.ts" vs "app/components/app.tsx"

first one shows emit, secod one not.

**Comment by basarat** [comment]
That is fixed with `6.0.17`. With `jsx:preserve` the output file name is `.jsx` not `.js`, that was throwing off the logic. :rose:

**Comment by tomitrescak** [comment]
Good news ;) I'll check it now. Thanks! :tulip:

**Comment by gizmodus** [comment]
Ah, how I love your plugin! Great work, guys!

+1 for ordering items in semantic view alphabetically

**Comment by ozra** [comment]
As for coloring functions, vars, etc.: just style them as you want in `style.less`. Just use the inspector to figure out what classes to use.
