### ISSUE TITLE
Get Pending Requests is not accurate

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/atom-typescript#610]
I was just about to jump in and try to see what was taking so much time in the editor (the project I am working on takes up to half a minute to process text changes) and I wanted to add some timings to pending request debugging. That's a feature request, sorry. The bug is that it uses a naive `push`/`pop`, which even if things are executing and coming back in order wouldn't it be the reverse? At the very least, I imagine it should be `push`/`shift` for FIFO.

**Comment by basarat** [comment]
> I imagine it should be push/shift for FIFO.

Indeed
