### ISSUE TITLE
Syntax highlighting is lost after extending class with more than 1 generic parameter. 

### ISSUE THREAD

**Issue by gitsumanth** [TypeStrong/atom-typescript#611]
Hi,
     I have been using atom typescript for couple of months, everything works flawlessly. Today i noticed that any class extending another class with more than one generic parameter, loses syntax highlighting after that line. This affects both tsx and ts files.

Eg. 

```
class B<T, U> {
   value: number = 2
   str: Array<string> = ['abc','bbc']
}

class C extends B<any, any> {
  value: number = 5
  str2: string = "10" 
}
```

both lines inside class C lose syntax highlighting

As you can imagine this is also happening for React Components, since it has 2 generic parameters and all members, methods and JSX lose syntax highlighting. 

I dont know if this is a problem with the latest version 6.0.15 or some other plugin causing this. 

So far i have completely removed atom and re-installed atom-typescript (ONLY) and still the same problem. Any ideas on how to fix that?

I suspect something to do in the grammers *.cson files.

Thanks

**Comment by basarat** [comment]
> I suspect something to do in the grammers *.cson files.

Indeed. However I am unable to reproduce : 

![image](https://cloud.githubusercontent.com/assets/874898/10062957/99cb023a-62ab-11e5-820e-e7bcf8196624.png)


Screenshot please :rose:

**Comment by gitsumanth** [comment]
Here's a screenshot.

Light

<img width="317" alt="screen shot 2015-09-23 at 6 06 08 pm" src="https://cloud.githubusercontent.com/assets/1577349/10063025/e7a0fb1a-621d-11e5-9eb3-df0696bbd7af.png">

Dark
<img width="360" alt="screen shot 2015-09-23 at 6 07 40 pm" src="https://cloud.githubusercontent.com/assets/1577349/10063030/0b662c5a-621e-11e5-83c6-4a3a1045e6b2.png">

**Comment by gitsumanth** [comment]
Anybody else getting this problem, the fix is to downgrade Atom to 1.0.15. The newest update seems to be causing this problem.

**Comment by gdackys** [comment]
Same problem here, syntax highlighting with generics is a mess :(

**Comment by tomitrescak** [comment]
I can confirm. All react components are now completely white `class FilteredPracticals extends React.Component<IFilteredPracticalsProps, {}> ..`

**Comment by basarat** [comment]
I can reproduce now, broken with latest atom release :cry:  

Was: 
![image](https://cloud.githubusercontent.com/assets/874898/10062957/99cb023a-62ab-11e5-820e-e7bcf8196624.png)

Now : 
![image](https://cloud.githubusercontent.com/assets/874898/10089956/e8c2246a-636c-11e5-88b5-9abae33a7893.png)

**Comment by basarat** [comment]
Also : https://github.com/TypeStrong/atom-typescript/issues/614

**Comment by bgrieder** [comment]
This morning Atom upgraded to 1.0.18 ! This is going way too fast and unfortunately, syntax highlighting is still broken.
Is there a reliable way to ensure that my copy stays at 1.0.15 while you work on it ?

**Comment by basarat** [comment]
> Is there a reliable way to ensure that my copy stays at 1.0.15 while you work on it ?

Manually building atom ... but its painful.


@Cu3PO42 hope this helps : One offending rule : `oldstylefunction` will cause `meta.function.js` over subsequent lines after something like : 

```
function statusBar(state: StatusBarState = initialStatusBarState, action: StatusBarAction): StatusBarState {
    ////////////////EVERYTHING HERE/////////////
        if (action.activeProject) {
```

Sample : 
![image](https://cloud.githubusercontent.com/assets/874898/10128891/63ce522e-65fb-11e5-9e97-283d6413d99a.png)

**Comment by Cu3PO42** [comment]
@basarat I don't really have a grasp on why the Atom update breaks anything, though I'd really, really like to know. This particular issue did also not occur previous to the update, did it?

**Comment by basarat** [comment]
> This particular issue did also not occur previous to the update, did it

@Cu3PO42 yes. This (``oldstylefunction`) *issue* only happens with this new atom release.

**Comment by sgal** [comment]
Hey guys,

Do we have any issue in the **atom** repo linked to this? Or how this will be solved?

Please advise.

**Comment by basarat** [comment]
> Do we have any issue in the atom repo linked to this?

Don't have a good way to report it atom. Since it didn't show up for other grammars (I just checked https://github.com/atom/atom/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+1.0.15+grammar), if we create an issue it is very likely to get closed as can not reproduce unless we provide a concrete actionable item. 

> Or how this will be solved?

It can be fixed by turning off all the nice typescript specific rules and just leaving the ones from language-javascript. I'll do that this weekend. Sorry for the inconvenience and thanks for your patience :rose:

**Comment by basarat** [comment]
For now I've reported https://github.com/atom/first-mate/issues/62

**Comment by Cu3PO42** [comment]
@basarat now that we at least know about the change that might be relevant, I'll try to do a deeper investigation when I have the time. But right now it's scholarship application time and Uni starts next week, so time is more than limited.

**Comment by kitsonk** [comment]
This issue is doing my head in.  I don't know if it helps, but here is a minimum reporoducable I have:

![type arguments comma](https://cloud.githubusercontent.com/assets/1282577/10190759/d0f9de10-6766-11e5-9f7b-148c46e57e30.gif)

**Comment by subjectix** [comment]
I found a monkey patching solution for the time being:
If you add an empty multi-line comment before the `,` the highlighting comes back to life :smile: 

```js
React.Component<Props /**/ , void>
```

**Comment by tomitrescak** [comment]
@subjectix thanks for this, was driving me crazy! Atom automatically updates on every restart and is just major pain in the (|). Hopefully Atom people will figure out soon what is the cause.

**Comment by basarat** [comment]
Fixed with https://github.com/TypeStrong/atom-typescript/releases/tag/v7.1.0 :rose:
