### ISSUE TITLE
Syntax highlighting lost when using tuples 

### ISSUE THREAD

**Issue by bgrieder** [TypeStrong/atom-typescript#614]
Definition File
Atom: 1.0.16
atom-typescript: 6.0.17
all themes

    class Test {

        breaks = (ok: string, notOk: [string, string]): void => {}

    }

![screen shot 2015-09-24 at 09 36 06](https://cloud.githubusercontent.com/assets/797684/10067840/f014a1f2-629f-11e5-9503-7d194df1ddd9.png)

**EDIT**

atom-typescript 6.0.17 really doesn't like tuples  :)

    type Tuple = [string, string]

breaks syntax highlighting of the code that follows

**EDIT 2**
This problem does not exist with atom 1.0.15

**Comment by sgal** [comment]
Same problem goes for function argument's default value

Atom: 1.0.16
atom-typescript: 6.0.17
all themes

```typescript
private makeTransitionSequence(preAnimations: any[],
                               duration : number = 2,
                               callback : any = this.transitionDone,
                               callbackScope : any = this) : TimelineMax {
    return new TimelineMax();
}
```

![screen shot 2015-09-24 at 10 46 35 am](https://cloud.githubusercontent.com/assets/2971261/10069033/a6aa6178-62a9-11e5-903f-7582f18a0f3a.png)

**Comment by basarat** [comment]
This has happened due to changes in *atom*. 

This issue is an extension of https://github.com/TypeStrong/atom-typescript/issues/611#issuecomment-143085486

**Comment by basarat** [comment]
fixed with https://github.com/TypeStrong/atom-typescript/releases/tag/v7.1.0 :rose:
