### ISSUE TITLE
Decorator error when constructor has multiple args

### ISSUE THREAD

**Issue by daynedavis** [TypeStrong/atom-typescript#616]
When making an angular 2 component there is an error on both the Component and View decorators any time the class constructor takes multiple arguments.
![screen shot 2015-09-25 at 2 04 42 pm](https://cloud.githubusercontent.com/assets/7105109/10108366/7c430292-638e-11e5-871b-1a4228fceecb.png)
![screen shot 2015-09-25 at 2 04 57 pm](https://cloud.githubusercontent.com/assets/7105109/10108376/8a4496c6-638e-11e5-80f1-23630d5a45b9.png)

However there are no errors after removing the second and third arguments from the constructor
![screen shot 2015-09-25 at 2 05 16 pm](https://cloud.githubusercontent.com/assets/7105109/10108388/a60a040e-638e-11e5-82b1-c886f9d5cee3.png)

**Comment by gdi2290** [comment]
that's odd, I know that Angular 2 still needs work with their type definitions for example currently the pipes property is missing from the View decorator in the type definition

cc @jashmenn (maintainer of the repo for this example)

**Comment by basarat** [comment]
Closing at it seems like a TypeScript / Angular definition error. Feel free to continue the discussion here, I'll be watching if this turns out to be something that needs to be fixed in atomts :rose:
