### ISSUE TITLE
Documentation improvement: TS version used by atom

### ISSUE THREAD

**Issue by atsu85** [TypeStrong/atom-typescript#617]
Please document what version plugin is using. As i understand based on the documentation: 
https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md
"version" attribute in tsconfig.json is not used at the moment by any tools, including atom-typescript.

**Comment by GoToLoop** [comment]
What a coincidence! I've just entered here to ask the same thing.
I'd also like to know which "tsc" version "ntsc" is based upon.
Is there any command in "ntsc" which would dump that specific info?

When requesting to "Create Tsconfig.json Project File" I've got "version": "1.5.0-beta"!  O_o
So I'm pretty unsure which TypeScript version the emitter transpiler is using!

**Comment by basarat** [comment]
Its the version from microsoft/typescript/master on this date : https://github.com/TypeStrong/atom-typescript/blob/dff8e9c40a54eaa2985f0b7dea24c22353ffcd75/package.json#L56 currently : 20th september 2015

**Comment by GoToLoop** [comment]
So it's very bleeding edge w/ latest features, right? More than excellent. That's what I wanted!  :D

**Comment by basarat** [comment]
> So it's very bleeding edge w/ latest features, right

yes :rose: 

I've removed the version option as you are not the first people to be confused by it. If it needed to be in the FAQ then we can probably do without that (unused and not respected) option. Refs https://github.com/TypeStrong/atom-typescript/issues/469
