### ISSUE TITLE
Unknown Option: compileOnSave

### ISSUE THREAD

**Issue by devpunk** [TypeStrong/atom-typescript#618]
Since the recent update to atom-typescript 6.0.18 I get an error message with the text "Unknown Option: compileOnSave" when I try to save a ts-file while I have set compiler-option "compileOnSave": false" in tsconfig.json.

I am on Atom 1.0.19 and Ubuntu 14.04. Atom installed via .deb package.

**Comment by basarat** [comment]
> I have set compiler-option "compileOnSave": false" in tsconfig.json.

Can you share the `tsconfig.json` file. I think you might be adding the key to the wrong place

**Comment by devpunk** [comment]
Here's my tsconfig.json
```
{
    "compilerOptions": {
        "target": "es5",
        "module": "amd",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "outDir": ".",
        "compileOnSave": false
    },
    "filesGlob": [
        "./**/*.ts",
        "!./node_modules/**/*.ts",
        "!./jspm_packages/**/*.ts"
    ],
    "files": [
        "./base/Application.ts",
        "./base/interface/ApplicationConfig.d.ts",
        "./base/interface/Route.d.ts",
        "./base/routing/Route.ts",
        "./base/routing/Router.ts"
    ]
}
```
Notice that below the typescript logo there's also a message "no tsconfig.json" which somehow contradicts the "Unknown option" message because the latter, of course, indicates that a tsconfig.json was actually found.
![compileonsave-error](https://cloud.githubusercontent.com/assets/6525873/10179074/f09a7242-6703-11e5-8d9a-c51ef42df2c5.png)

**Comment by basarat** [comment]
`compileOnSave` needs to be at the *root*. Its not a subkey of `compilerOptions`. Fixed: 

```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "amd",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "outDir": "."
    },
    "compileOnSave": false,
    "filesGlob": [
        "./**/*.ts",
        "!./node_modules/**/*.ts",
        "!./jspm_packages/**/*.ts"
    ],
    "files": [
        "./base/Application.ts",
        "./base/interface/ApplicationConfig.d.ts",
        "./base/interface/Route.d.ts",
        "./base/routing/Route.ts",
        "./base/routing/Router.ts"
    ]
}
```

Please continue discussion if you still have confusion. Closing for now :rose:

**Comment by basarat** [comment]
These are the root options : https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#options

**Comment by devpunk** [comment]
Oh, thanks man. Of course, I associated "compileOnSave" with "compiler" and didn't even consider it a root option. But triggering the complier upon saving is not the compiler's job, of course. When viewed from this angle it makes sense to have it separate.
