### ISSUE TITLE
Create tsconfig for files in folders

### ISSUE THREAD

**Issue by yotamN** [TypeStrong/atom-typescript#620]
All my typescript files are inside folders and because of this I can't generate a tsconfig file in the root directory and use all the features.

What I need to do in order to have a tsconfig file is create a file in the root directory and generate the tsconfig and than delete the file from the tsconfig and from the directory.

**Comment by basarat** [comment]
> What I need to do in order to have a tsconfig file is create a file in the root directory and generate the tsconfig and than delete the file from the tsconfig and from the directory.

I am a bit confused. Can you share the directory tree *before* and *after* running the **proposed command**. Thanks :rose:
