### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by tomitrescak** [TypeStrong/atom-typescript#621]
Hi, you guys do a wonderfull job on this plugin, but it would be nice to know what is new. You just released version 7, so it would be nice to know what all has entered that. Will that be possible? The release page has no description. Thanks!

**Comment by basarat** [comment]
We are documenting breaking changes at the moment : https://github.com/TypeStrong/atom-typescript/blob/master/docs/CHANGELOG.md We definitely need to setup something better in future

**Comment by basarat** [comment]
Related (but not blocking us) https://github.com/atom/settings-view/issues/282

**Comment by basarat** [comment]
I started to be more disciplined : https://github.com/TypeStrong/atom-typescript/releases :rose:

**Comment by tomitrescak** [comment]
I allready helped me to localise the problem with typescript release messing up imports, so I knew which version to test to make sure ;) Thanks!
