### ISSUE TITLE
Bottom bar with error message is changing its height when tooltip appears

### ISSUE THREAD

**Issue by sgal** [TypeStrong/atom-typescript#622]
__Environment__
**Atom**: 1.0.19
**atom-typescript**: 7.0.0
**OS**: Mac OS 10.10.5

Bottom bar is changing its height when you have any errors in the file/project and you hover the source code. When tooltip appears the bottom bar is "jumping" (see image below).

![atom-bottom-bar-issue](https://cloud.githubusercontent.com/assets/2971261/10130137/f484a556-65c5-11e5-9b00-627997f1b441.gif)

I've inspected the bottom bar's view and it seems that when you hover the code, atom shows the loading icon (with github logo) for less than a second. The problem is that logo is higher than the line with error message, so bottom bar is "jumping".

The bottom bar is not jumping when you have no errors in the file/project, since there's no line with error message.

I've temporarily fixed it on my local machine by adding 
```css
line-height: 24px;
```
to the line with error message in __mainPanelView.ts__ (line 81)

Thanks,
Sergey

**Comment by basarat** [comment]
Good fix. Thanks! :rose:  `7.0.1`
