### ISSUE TITLE
Insane number of pending requests appeared

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/atom-typescript#624]
Not entirely sure what triggered it (may have been a previously queued look up reference task) but when a new tab popped open and I closed it again, my pending tasks was at (almost) 1000.

![image](https://cloud.githubusercontent.com/assets/1088987/10147339/452d62ba-65e2-11e5-9531-50592101d1ba.png)

And it's not going down either.

**Comment by ralfbiedert** [comment]
Are you using `exclude` in your tsconfig.json? I had the same issue and had to revert back to `filesGlob` and `files`.

**Comment by blakeembrey** [comment]
No, I'm not - I usually do have an unusual amount of pending requests on this project but haven't had the time to debug it. The unusual thing about this was that 997 appeared immediately - I wasn't building it up this time.

**Comment by rcchen** [comment]
+1 also having this issue, I'm not using the `exclude` property in `tsconfig.json` either.

**Comment by tjoskar** [comment]
I have the same problem. 
I can't say when or why it happens, it just do. I'm using this addon every day and it may happens once a week (ie. not so often) and it is often solved by exit Atom, wait for a few minutes (≈10 min) and starting atom again.

**Comment by basarat** [comment]
> wait for a few minutes (≈10 min) and starting atom again.

Thanks for the tip. I happened to me once and it just completely drove me insane that I had to keep restarting atom (it locks up because of this as well) .... and after a while it was all good. I assumed it was an Atom bug that they fixed ... now I know its just photons
