### ISSUE TITLE
No syntax highlighting for tsx files

### ISSUE THREAD

**Issue by snowcxt** [TypeStrong/atom-typescript#626]
![image](https://cloud.githubusercontent.com/assets/1463415/10152055/cc88eda4-6602-11e5-8641-dcc26c1e66e7.png)

The root cause could be https://github.com/TypeStrong/atom-typescript/issues/611

**Comment by basarat** [comment]
> The root cause could be #611

indeed.

**Comment by basarat** [comment]
Try https://github.com/TypeStrong/atom-typescript/releases/tag/v7.1.0 :rose:
