### ISSUE TITLE
atom-typescript should check fileNames case

### ISSUE THREAD

**Issue by stepancar** [TypeStrong/atom-typescript#628]
Hello, @basarat!
I faced this [issue](https://github.com/Microsoft/TypeScript/issues/5016) 
typescript folk already faced with similar [issue](https://github.com/Microsoft/TypeScript/issues/3626)
see [comment](https://github.com/Microsoft/TypeScript/issues/3626#issuecomment-122323868)
May be has the meaning to add filepath checking by atom-typescript? 
Thank you!

**Comment by basarat** [comment]
> May be has the meaning to add filepath checking by atom-typescript?

Sound like a good idea. But If TypeScript supports it natively then we will not have to. So closing it as a duplicate of https://github.com/Microsoft/TypeScript/issues/3626
