### ISSUE TITLE
Error window going crazy.

### ISSUE THREAD

**Issue by tomitrescak** [TypeStrong/atom-typescript#632]
Please see the gif. When, the error message is too long, it keeps jumping up and down what is really distracting.

![test](https://cloud.githubusercontent.com/assets/2682705/10213103/10e283f2-684c-11e5-96bc-e9f5430d6515.gif)

**Comment by basarat** [comment]
I have this code for the error sample : 
```ts
var foo = {somethingReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyLong:123, c1:'123',c2:'123',c3:'123',c4:'123',c5:'123',c6:'123',c7:'123',c8:'123',c9:'123',c10:'123',c11:'123',c12:'123',c13:'123',c14:'123'}; 
foo  = 123 /**/
``` 
It doesn't reproduce this ... however we do see the error message trimming and not trimming (because of the pending error request screen). 

I'll make is to that the pending requests icon always takes space even if not visible. Thanks for the report :rose:

**Comment by basarat** [comment]
Fore ref, Code https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/atom/views/mainPanelView.ts

**Comment by basarat** [comment]
https://github.com/TypeStrong/atom-typescript/releases/tag/v7.1.5 :rose:
