### ISSUE TITLE
"outFile" in tsconfig.json produces "The project file contains invalid options"

### ISSUE THREAD

**Issue by ralfbiedert** [TypeStrong/atom-typescript#633]
When I add `"outFile": "build/library.js",` to `compilerOptions` in my `tsconfig.json` I receive an atom-typescript build message:

The project file contains invalid options

Building the same project with `tsc` works fine. When I remove the line the build works again in Atom.

<img width="788" alt="screen shot 2015-10-01 at 14 39 01" src="https://cloud.githubusercontent.com/assets/301288/10220796/2e6d5732-684a-11e5-81cb-e6f22a0f4b70.png">

I am using Atom 1.0.19, atom-typescript 7.0.2, Typescript 1.7.0-dev.20151001 on Mac OS 10.11.

**Comment by basarat** [comment]
`out` became `outFile` in TypeScript 1.6 I think. `out` still works though, and you can use that for now. 

I've asked for clarification about the plan for these (similar in purpose) options : https://github.com/Microsoft/TypeScript/issues/5107 once its clear if we should just rename `out` to `outFile` :rose:
