### ISSUE TITLE
Defining arguments in constructor on single line breaks syntax highlighting

### ISSUE THREAD

**Issue by timothysoehnlin** [TypeStrong/atom-typescript#638]
When defining a class constructor, and defining members in the constructor, syntax highlighting will break if the constructor keyword and member declaration is all on one line.

Example:

    constructor(distinct:boolean = false) {
        ...
    }

This seems to break highlighting for the rest of the file, but putting the arguments onto individual lines seems to resolve the issue:

    constructor(
        distinct:boolean = false
    ) {
         ...
    }

**Comment by timothysoehnlin** [comment]
This looks like this might be related to #611

**Comment by basarat** [comment]
Fixed with https://github.com/TypeStrong/atom-typescript/releases/tag/v7.1.0 :rose:
