### ISSUE TITLE
Tooltips have bad z-index, when scrolling overlap bottom issues pane instead of being cropped by it

### ISSUE THREAD

**Issue by DanielJoyce** [TypeStrong/atom-typescript#639]
1) Type in some code with typescript error
2) Hover so tooltip appears
3) Mousewheel window up/down
4) Note that tooltip scrolls over linter error message in footer area instead of being clipped to editor text area.

**Comment by basarat** [comment]
> Mousewheel window up/down

that doesn't make the tooltip or the linter error message change its location in my testing. 

Am I missing something: 

![zindex](https://cloud.githubusercontent.com/assets/874898/10273271/7cd8779e-6b79-11e5-9881-2e8924d8275b.gif)
