### ISSUE TITLE
typescript format code, crashes on larger files ~ 1000 lines

### ISSUE THREAD

**Issue by hansrwindhoff** [TypeStrong/atom-typescript#640]
on smaller files repeatedly pushing crtl+alt L indents further and further.
this is on windows 8.1 (64)

on osx it works for me

**Comment by basarat** [comment]
> on osx it works for me

I've had the opposite happen for me (increasing indent on mac and sticking on windows).

Its an issue that needs to go to https://github.com/Microsoft/TypeScript/issues
