### ISSUE TITLE
Cannot find module when importing with require using relative path

### ISSUE THREAD

**Issue by pepri** [TypeStrong/atom-typescript#641]
When using relative path in `require` call, the atom-typescript cannot find the module. Compiling with `tsc` directly from command line works.

The minimal test case consists of 3 files in the same directory: `a.ts`, `b.ts` and `tsconfig.json` (their content is below). Compiling from command line `tsc --module amd` creates `out` directory with `a.js` and `b.js` files with no error.

When opening the directory with these files in Atom editor, the atom-typescript complains that it "Cannot find module 'b'." in `a.ts` on the first line with `import b = require('b');`. Using `import b = require('./b');` instead works, but I want to use paths relative from the project root (the location of `tsconfig.json`). This worked before I updated atom-typescript package.

How can I use relative paths with `require` calls? Am I doing something wrong?

The environment:
OS: Ubuntu 15.04
Atom: 1.0.19
atom-typescript: 7.1.1

The content of the files follows:
`b.ts`:
~~~ts
export = "test"
~~~

`a.ts`:
~~~ts
import b = require('b'); // cannot find module 'b', but works with require('./b');
console.log('a' + b.length);
~~~

`tsconfig.json`
~~~json
{
    "compilerOptions": {
        "outDir": "out"
    },
    "filesGlob": [
        "./**/*.ts",
        "!./node_modules/**/*.ts"
    ],
    "files": [
        "./a.ts",
        "./b.ts"
    ]
}
~~~

**Comment by basarat** [comment]
Change your `tsconfig.json` to : 

```json
{
    "compilerOptions": {
        "outDir": "out",
        "moduleResolution": "classic"
    },
    "filesGlob": [
        "./**/*.ts",
        "!./node_modules/**/*.ts"
    ],
    "files": [
        "./a.ts",
        "./b.ts"
    ]
}
```

The module resolution algorithm was changed in TypeScript 1.6 :rose:

**Comment by basarat** [comment]
Also add `'module': 'amd'`` as we default to node (I recommend that is what you use with something like webpack)

**Comment by pepri** [comment]
Thank you, `"moduleResolution": "classic"` is exactly what I needed.

**Comment by dlants** [comment]
Note, the reason this works in `tsc` but not in the plugin, it seems, is that `tsc` defaults to 'classic' resolution for some targets (amd, system, es2015).

https://www.typescriptlang.org/docs/handbook/module-resolution.html#classic

I think the atom plugin does not, and thus needs the explicit moduleresolution setting in tsconfig.
