### ISSUE TITLE
es6 imports translated to modules even when output set to es6 

### ISSUE THREAD

**Issue by tomitrescak** [TypeStrong/atom-typescript#643]
Hi

Up until latest update my es6 imports were left the way they was when transpilig to es6.
From the latest update now they are transpiled to the module representation.

For example:

```
import TabControl from "../../components/tabs/tab_control";
```

is transpiled to 

```
var tab_control_1 = require("../../components/tabs/tab_control");
```

The worst part is, that it breaks the TSX transpilation as for example

```javascript
  <TabControl tabs={this.state.tabs}>
            {
              this.props.validations.map((validation: BoardValidation, index: number) => {
                return <BoardValidationView key={index} />
              })
            }
</TabControl>
```

is transpiled to:

```
<tab_control_1.default tabs={this.state.tabs}>
            {this.props.validations.map((validation, index) => {
            return <BoardValidationView key={index} />;
        })}
          </TabControl>
```

Note how the closing tag is not transpiled.

I am sure that this is bug in Microsoft transpilation, but can the transpilation of import statements be disabled? Up until today all was working well ... now none of my TS project runs ;((

For completeness, here is my tsconfig

```
{
    "compilerOptions": {
        "target": "es6",
        "declaration": false,
        "noImplicitAny": true,
        "removeComments": false,
        "noLib": false,
        "preserveConstEnums": true,
        "noEmitHelpers": true,
        "suppressImplicitAnyIndexErrors": true,
        "watch": true,
        "outDir": "../dist",
        "jsx": "preserve"
    },
...
}

**Comment by tomitrescak** [comment]
Thanks to the description you left in releases, I've found out that this happens from version 7.1.2 in which you have updated typescript to the latest version. I have also left a comment within their issues.

**Comment by sickboy** [comment]
I can confirm this issue

**Comment by tomitrescak** [comment]
Do now roll back to 7.1.1 which has a previous version of typescript. Seems like a TS issue.

**Comment by basarat** [comment]
TypeScript issue report : https://github.com/Microsoft/TypeScript/issues/5110

**Comment by basarat** [comment]
Reverted for now till https://github.com/Microsoft/TypeScript/issues/5110 is resolved : https://github.com/TypeStrong/atom-typescript/releases/tag/v7.1.4 :rose:

**Comment by basarat** [comment]
Fixed : https://github.com/TypeStrong/atom-typescript/releases/tag/v7.7.0 User action required :rose:

**Comment by basarat** [comment]
Tsconfig / TypeScript : for people using `"target" : "es6"` they should now also use `"module": "es6"` in tsconfig `compilerOptions
