### ISSUE TITLE
Syntax "if/else if" highlighting lost

### ISSUE THREAD

**Issue by isuda** [TypeStrong/atom-typescript#645]
when I write:

```
if(...) {
  //...
} else if(...) {
  //...
}
```
The syntax highlighting is broken on the "if" and "else if" if there is no space between the if and the opening bracket. This used to work correctly a few weeks or a month ago.

![image](https://cloud.githubusercontent.com/assets/25780/10343831/c5a14940-6cd4-11e5-956e-e40c69391d4c.png)

**Comment by isuda** [comment]
Also, FWIW, it highlights properly in language-javascript.

**Comment by basarat** [comment]
The following works, and is the recommended formatting `if <space> (`  as well: 
```ts
if(...) {
  //...
} else if(...) {
```

Marking as up for grabs though as it would be nice to have it all :rose:

**Comment by basarat** [comment]
any effort in grammar should go to https://github.com/TypeStrong/atom-typescript/issues/675 :rose:

**Comment by mjohnsonengr** [comment]
Note the same issue occurs in for loops: 
![image](https://cloud.githubusercontent.com/assets/7274059/11783177/f02e52a0-a232-11e5-90ab-270c613a1313.png)

**Comment by basarat** [comment]
Should work with release https://github.com/TypeStrong/atom-typescript/releases/tag/v8.0.0 :rose: If not raise issue at https://github.com/Microsoft/TypeScript-TmLanguage/issues and link us :rose:
