### ISSUE TITLE
Replace custom `tsconfig` logic with `tsconfig` module

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/atom-typescript#646]
It will probably require a new minor version of `tsconfig` with the correct errors thrown/exposed, but it would be great to consolidate the logic to https://github.com/TypeStrong/tsconfig. Any thoughts? 

Edit: Definitely feel free just to close this, I know there's a lot more going on here than there.

**Comment by basarat** [comment]
The main thing lacking is `validation` and error reporting for invalid settings. 

Minor : And also a few atom/IDE specific options

**Comment by nycdotnet** [comment]
Once I'm over the hump in the next month or so, I'd love to consolidate grunt-ts onto this also (assuming you're willing to take some PRs).  If it's a shared module it will also make it worthwhile doing things like allowing comments (assuming that does get pulled-in by the TypeScript team) and not trashing indentation on updates, tabs vs. spaces, etc.

**Comment by blakeembrey** [comment]
Yeah, that'd be great. Right now, it's one way only, but I've had to do JSON editing for TSD recently and the same model could work in TSConfig.

**Comment by blakeembrey** [comment]
Ok, this is released - but we can make improvements over time to the API, such as writing, etc. Please make issues for anything needed at https://github.com/TypeStrong/tsconfig.
