### ISSUE TITLE
how to force autocomplete to search for full string instead letters

### ISSUE THREAD

**Issue by yoorek** [TypeStrong/atom-typescript#650]
Example: when i enter 'ngm' and press TAB i get  very long list of suggestions that has e.g 'interface DocumentFragment' on it just because it has 'n' 'g' 'm' letters in it. It is not what I expected - i have 'ngm' snippet for 'Angular Module' and I have to scroll to end of list to choose it.

How can I force autocomplete to suggest only matches of full string i provided ?

**Comment by basarat** [comment]
>  i have 'ngm' snippet for 'Angular Module' and I have to scroll to end of list to choose it.

We can either put snippets before other completions or after other completions. 

# Reason

The ordering is in the control of atom, and there are two providers : us and snippets. Mixing (in order) completions from different providers is not possible. 

See https://github.com/TypeStrong/atom-typescript/issues/566 for the request where we made completions appear *before* snippets.

**Comment by yoorek** [comment]
It is not only the case of ordering. The more important thing is what gets on the list - a lot element s that should not be there.

Another example - I want to autocomplete for 'console' - when I enter 'conso' I get:

- console
- Console
(and it;s good) and then I get:
- DateConstructor or 
- oncompassneedscalibration (just because they have letters in right order)

This makes 'autocomplete' pretty useless.

Is there a way to make search 'strict'?

**Comment by basarat** [comment]
> just because they have letters in right order

Some people (including myself) find this much pleasing than the strictness of VS style autocomplete. 

> Is there a way to make search 'strict'?

Not at the moment. But I actually like it the way it is. I definitely understand your frustration ... but its different people want different things in this case, sorry about that :rose: 

# Long term 

An ideal solution would be to match within suggestions from different providers. That needs support from atom upstream.

**Comment by yoorek** [comment]
It is not only 'VS style' of autocomplete - WebStorm, Sublime, Brackets... they all work with 'strict' search.
Nice you like your work and please yourself with it :-)

**Comment by basarat** [comment]
@yoorek quick fix. Press the `up` key to get to snippets fast ;)

**Comment by yoorek** [comment]
Actually my team found better and quicker "fix" to multiple typescript related problems in Atom - switching back to WebStorm ;-)

**Comment by basarat** [comment]
> Actually my team found better and quicker "fix" to multiple typescript related problems in Atom - switching back to WebStorm ;-)

good call :rose: :100: :)
