### ISSUE TITLE
filesGlob excludes no longer work in 7.3.0

### ISSUE THREAD

**Issue by sickboy** [TypeStrong/atom-typescript#651]
My use case:
~~~
    "filesGlob": [
        "./cdn_source/**/*.ts",
        "./cdn_source/typings/**/*.ts",
        "./scripts/typings/**/*.d.ts",
        "./cdn/aurelia/**/*.d.ts",
        "!./node_modules/**/*.ts",
        "!./cdn/aurelia/node_modules/**/*.ts",
        "!./cdn/aurelia/jspm_packages/npm/rx@*/ts/**/*.ts",
        "./cdn/aurelia/jspm_packages/npm/rx@*/ts/rx.all.es6.d.ts"
    ],
~~~

but all rx@ ts files are included in files section now.
I've tried different orders but doesnt seem to help.

**Comment by arusakov** [comment]
+1

**Comment by blakeembrey** [comment]
Apologies, this is definitely my fault. I'll open a new PR for this today, I completely blanked and forgot that `filesGlob` has negation support.

**Comment by david-driscoll** [comment]
This is so brutal with a reference to ntypescript and rx, I couldn't compile from the command line without making sure atom was dead.  Thanks for the quick turn around though.

**Comment by blakeembrey** [comment]
@sickboy @arusakov @david-driscoll Could you please try the latest version? :smile: It should be a lot quicker now.

**Comment by david-driscoll** [comment]
:+1: fixed!

**Comment by sickboy** [comment]
@blakeembrey Excluding works again thanks.
BUT I can not override excludes anymore.

~~~
        "!./cdn/aurelia/jspm_packages/npm/rx@*/ts/**/*.ts",
        "./cdn/aurelia/jspm_packages/npm/rx@*/ts/rx.all.es6.d.ts"
~~~
should still give me "rx.all.es6.d.ts" but it doesn't. The order doesn't seem to matter.
Would be great if it could do first match perhaps.

so then it should be configured as:

~~~
        "./cdn/aurelia/jspm_packages/npm/rx@*/ts/rx.all.es6.d.ts"
        "!./cdn/aurelia/jspm_packages/npm/rx@*/ts/**/*.ts",
~~~

and then because it hits the first one, it should no longer look at the next

**Comment by nycdotnet** [comment]
@sickboy Can you try this:
```
"!./cdn/aurelia/jspm_packages/npm/rx@*/ts/**",
"./cdn/aurelia/jspm_packages/npm/rx@*/ts/rx.all.es6.d.ts"
```

**Comment by sickboy** [comment]
@nycdotnet hmm thanks but no dice :(

**Comment by basarat** [comment]
@sickboy I've created an issue for your report : https://github.com/TypeStrong/tsconfig/issues/11

Sorry about the inconvenience but the glob library that we were using before had major performance issue + different projects were using different libs. 

Moving to https://github.com/TypeStrong/tsconfig/ means that all our projects (and any other OSS projects out there than need this support) give the same answer to filesGlob queries so its not an atom-ts locked thing :rose:. Again : Sorry about the current annoyance :rose:

**Comment by blakeembrey** [comment]
@sickboy I'm really sorry for that regression, thanks for helping me experiment and resolve this! I'm not actually sure what was going on there, since it shouldn't resolve into that folder anyway if you're only specifying the single file glob. Please let me know if this is still broken in `v7.4.1`.

**Comment by sickboy** [comment]
@basarat and @blakeembrey thanks a lot, the glob exclude/include works again, however now Atom does not recognize that there is a tsconfig.json for my .ts files anymore.
I wonder if it has to do with the fact that the files section now no longer contains leading "./"
