### ISSUE TITLE
tsconfig target es6 and module 7.4.0

### ISSUE THREAD

**Issue by arusakov** [TypeStrong/atom-typescript#654]
I write tsconfig.json like this:
```json
{
    "compilerOptions": {
      "target": "es6"
    },
    "filesGlob": [
        "./**/*.+(ts|tsx)"
    ]
}
```
When I save file, atom-typescript regenerate it to this:
```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true
    },
    "filesGlob": [
        "./**/*.+(ts|tsx)"
    ],
    "files": [
        "main.ts",
        "typings.d.ts"
    ],
    "exclude": []
}
```
Then I have typescript error:
TS1204: Cannot compile modules into 'commonjs', 'amd', 'system' or 'umd' when targeting 'ES6' or higher.
ES6 target and module property should not be simultaneously.

**Comment by nycdotnet** [comment]
Can you set module to `undefined` or ""?

**Comment by arusakov** [comment]
@nycdotnet Thank you! It's good workaround. But it's still a bug.

**Comment by nycdotnet** [comment]
OK we'll investigate.  Sorry for the trouble.

//cc: @blakeembrey not sure if you have time to look into this.  I'm crushed until next week.

**Comment by arusakov** [comment]
@nycdotnet Maybe I can help you. Is bug in the [TypeStrong/tsconfig](https://github.com/TypeStrong/tsconfig) repo?

**Comment by nycdotnet** [comment]
We'd love to have you take a look at it.  We just set up atom-typescript to use that, so probably, but I haven't looked into it at all.

**Comment by blakeembrey** [comment]
Definitely a bug/bad feature in `tsconfig`, let me do a patch for you now.

**Comment by dallonf** [comment]
I am having the same problem, but cannot work around it. If I set module to `null` or `""`, I get the error `Argument for '--module' option must be 'commonjs', 'amd', 'system' or 'umd'.`. And of course, if I remove the property, atom-typescript puts it back.

**Comment by blakeembrey** [comment]
I just released a patch for `v.7.4.1`, please let me know if it resolves your problems :smile:
