### ISSUE TITLE
Find All References - line numbers off by 1

### ISSUE THREAD

**Issue by nycdotnet** [TypeStrong/atom-typescript#655]
The reported line number in Find All References is 1 less than the actual line number.

Repro:
Find all references on a symbol (Shift+F12).
Note the line number.
Look at that line - it's 1 off.

This is probably a perfect up-for-grabs issue, so I'm not going to fix it.

**Comment by lordmat0** [comment]
I'll pick this up

**Comment by basarat** [comment]
Fix : https://github.com/TypeStrong/atom-typescript/pull/816

**Comment by basarat** [comment]
Released : https://github.com/TypeStrong/atom-typescript/releases/tag/v8.1.0 :rose:
