### ISSUE TITLE
Renaming doesn't work

### ISSUE THREAD

**Issue by arusakov** [TypeStrong/atom-typescript#659]
F2 button doesn't work and "TypeScript: Rename Refactor" command doesn't work too.

**Comment by blakeembrey** [comment]
Do you have any more details? It works for me and that code hasn't changed in a long time.

**Comment by basarat** [comment]
Tested on mac (I used it this morning in my commute) and on PC. 

Probably `F2` is not what you are pressing :rocket: Try using the keybinding resolver `ctrl + .`/`cmd + .`

**Comment by arusakov** [comment]
I restart Atom and it's work again... I will continue monitoring for this heisen bug.
