### ISSUE TITLE
Add reviews

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#66]
"I was shocked at how good it felt to poke around on the compiler with it." [Jonathan Turner](https://twitter.com/jntrnr)
"And guess what, it worked perfectly. Like everything else!" [Daniel Earwicker](http://stackoverflow.com/users/27423/daniel-earwicker)

**Comment by basarat** [comment]
@danielearwicker would like your approval for this.

**Comment by danielearwicker** [comment]
100% approved. You can add "Faster than Visual Studio!" as well.

**Comment by basarat** [comment]
https://github.com/TypeStrong/atom-typescript/issues/91#issuecomment-77989838

**Comment by basarat** [comment]
https://gitter.im/TypeStrong/atom-typescript?at=550598b9ff6ec3eb42fa6a14
