### ISSUE TITLE
Disable autocompletion after a comma

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/atom-typescript#660]
It's kind of annoying, but I never want autocompletion after I've just pressed the comma. It happens every time and since "enter" triggers completion I've ended up with a jank workflow of pressing command, esc, enter, typing over and over again.

**Comment by basarat** [comment]
> It's kind of annoying, but I never want autocompletion after I've just pressed the comma

Agreed. Feel free to change that by adding it here : https://github.com/TypeStrong/atom-typescript/blob/a37d592225d7be09b3f872cf7eaa37214c2a77d7/lib/main/atom/autoCompleteProvider.ts#L143-L147 :rose:
