### ISSUE TITLE
ModuleResolution doesn't work correctly.

### ISSUE THREAD

**Issue by isuda** [TypeStrong/atom-typescript#664]
I have a project with a tsconfig.json that is compiled externally (and also does not generate d.ts files).

tsc will compile the project correctly, but atom will output lots of "module not found" errors when I use the node style module resolution. When I do add `compileOnSave: true`. It warns me that "the compile failed, but the emit succeeded".

![image](https://cloud.githubusercontent.com/assets/25780/10523822/3f3dd81a-7331-11e5-8482-c115bb926410.png)

If it works for tsc, it should work for atom-typescript?

**Comment by isuda** [comment]
I should also note that changing the import to `import {Test} from "./test/index"` works, but of course, thats the same as if I were using `moduleResolution: "classic"`.

**Comment by basarat** [comment]
Which version of `tsc` are you using. Importing a `.ts` file without a `.d.ts` file was only fixed 3 days ago :) https://github.com/Microsoft/TypeScript/issues/5225 

But last time we updated to TypeScript latest people's code broke so haven't done a quick push. Tracking it here though https://github.com/TypeStrong/atom-typescript/issues/663 :rose:

**Comment by basarat** [comment]
PS: can you copy paste the code files here ... so I don't have to setup for testing :)

**Comment by isuda** [comment]
My tsc version is 1.6.2.

tsconfig.json:
```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": false,
        "noLib": false
    },
    "compileOnSave": true,
    "filesGlob": [
        "./**/*.ts"
    ],
    "files": [
        "main.ts",
        "test/index.ts"
    ],
    "exclude": []
}
```

main.ts:
```
import {Test} from "./test";

let t = new Test();
```

test/index.ts:
```
export class Test {

}
```

**Comment by basarat** [comment]
I just tried typescript latest locally. Bug still exists. Reported here https://github.com/Microsoft/TypeScript/issues/5277 :rose:

**Comment by basarat** [comment]
Released https://github.com/TypeStrong/atom-typescript/releases/tag/v7.9.0 :rose:

**Comment by isuda** [comment]
Thanks!
