### ISSUE TITLE
syntax highlighting fails for optional function arguments

### ISSUE THREAD

**Issue by psnider** [TypeStrong/atom-typescript#667]
Similar to #395?

The declaration in the first line has proper syntax highlighting,
...while adding a question mark in the second line removes highlighting
and the highlighting on the next line is incorrect (type is misrecognized)
 
<img width="423" alt="ts highlight opt args bug" src="https://cloud.githubusercontent.com/assets/940931/10559116/f594976e-74d7-11e5-82b6-d1a5f371636e.png">

This also seems to affect much of the following highlighting.

**Comment by basarat** [comment]
any effort in grammar should go to https://github.com/TypeStrong/atom-typescript/issues/675 :rose:

**Comment by basarat** [comment]
Should work with release https://github.com/TypeStrong/atom-typescript/releases/tag/v8.0.0 :rose: If not raise issue at https://github.com/Microsoft/TypeScript-TmLanguage/issues and link us :rose:
