### ISSUE TITLE
snippets seem broken

### ISSUE THREAD

**Issue by hansrwindhoff** [TypeStrong/atom-typescript#668]
![untitled](https://cloud.githubusercontent.com/assets/2334281/10559321/357b0c32-74ab-11e5-833e-5a5254ffbdc6.png)

**Comment by basarat** [comment]
Snippets now appear at the bottom. Press the `up` key to get there *fast*: 

![image](https://cloud.githubusercontent.com/assets/874898/10567344/4814a008-764d-11e5-9fd2-446ddf5394e1.png)


See https://github.com/TypeStrong/atom-typescript/issues/566 for details :rose:

**Comment by hansrwindhoff** [comment]
cool, thanks for the heads up :)
