### ISSUE TITLE
Add facility to disable emit-on-save

### ISSUE THREAD

**Issue by robertknight** [TypeStrong/atom-typescript#67]
My project's build outputs TypeScript-compiled Javascript in a separate build dir (`src\lib\foo.ts -> build\lib\foo.js`) to avoid polluting the source tree with build artefacts.

It would be useful if it was possible to either:

1) Disable emit-on-save.
2) Be able to configure the options that the code is built with, including output directory and flags such as module type and noImplicitAny.

Discussion on Gitter:

> But valid suggestion to have atom-typescript config. Please open an issue : 
> https://github.com/TypeStrong/atom-typescript/issues and this will be the first config option we add

I see a reference to tsconfig.json which will apparently be a standard way to configure TypeScript in future but I don't know too much about the plans for it. Would that be another way to address this use case?

# Admin task list
* [ ] add emit on save plugin option + architecture for watched configurations. 
* [x] add `tsconfig` TypeScript PR to docs. https://github.com/Microsoft/TypeScript/pull/1692

**Comment by basarat** [comment]
> Be able to configure the options that the code is built with, including output directory and flags such as module type and noImplicitAny.

Yes `tsconfig` already does this portion: https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md



> Disable emit-on-save.

I'll add this a plugin option. Reason: Don't want to a) pollute `tsconfig` , b) people getting an project and not being able to build without modifying `tsconfig`. 

Tasks
* [ ] add emit on save plugin option + architecture for watched configurations. 
* [ ] add `tsconfig` TypeScript PR to docs. https://github.com/Microsoft/TypeScript/pull/1692

**Comment by basarat** [comment]
@robertknight having re-read the comments I just noticed your `either`. Perhaps I shouldn't have added this option as I do not see a reason *why you would want to disable compile on save*. Because *it is faster than any other typescript plugin I've tried*.

**Comment by basarat** [comment]
Nevertheless I have the code staged and will push it, potentially for people that use something else like `webpack` etc to compile on the fly.

**Comment by basarat** [comment]
![image](https://cloud.githubusercontent.com/assets/874898/6104876/98cbd99e-b0a5-11e4-9ad6-a0cb4c73a30d.png)
:boom:

**Comment by robertknight** [comment]
@basarat - For my particular use case, compile-on-save would be fine if the usual output directory was preserved - although I still need to run 'make' to perform other build steps.

Thanks for implementing this so quickly.

**Comment by kalaomer** [comment]
Is this setting available now? I can't find it.

**Comment by basarat** [comment]
@kalaomer  We ended up making it a part of compileOnSave : https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md

**Comment by kalaomer** [comment]
Oh, thanks!

**Comment by gordonklaus** [comment]
Please add this setting back to the plugin.

Editor/plugin-specific configuration doesn't belong in `tsconfig.json` which is a configuration file for the compiler.  Imagine if everyone's different favorite editor/plugin decided to read its configuration from `tsconfig.json`:  We would end up with a `tsconfig.json` full of options each of which only a few people cared about; a mess.

**Comment by alexeypetrushin** [comment]
Please add the option of disabling notification back, I added options to config, still see notifications with warnings/errors every time I save the file, it's extremely annoying. 

```
    "compileOnSave": false,
    "buildOnSave": false,
```

**Comment by joesonw** [comment]
The compileOnSave should be off by default, user can use it when they want to. Or it MESSES THINGS UP!!!!!!!!!
