### ISSUE TITLE
Syntax highlighting fails with union types in parentheses

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/atom-typescript#670]
![image](https://cloud.githubusercontent.com/assets/1088987/10585878/65ba728a-764e-11e5-880e-69cf62626da9.png)

```ts
interface X {
  node: (x | y)[]
}

const value = 10
```

**Comment by qs-mobile** [comment]
I've done some experimenting with your code to figure out the rule that is failing. 

I found a way to "fix" the highlighting by adding the space before **x** type

<img width="170" alt="screen shot 2015-10-20 at 10 39 52 am" src="https://cloud.githubusercontent.com/assets/8364210/10602164/f29d89f8-7716-11e5-9a9a-ccc14d07f8af.png">

```typescript
interface X {
    b: ( x | y)[];
}

const value = 10;
```

It is related to the [type](https://github.com/TypeStrong/atom-typescript/blob/master/grammars/typescript.cson#L730) rule in the grammar.

It also might be a case, that it's recognised as a function;

**Comment by sgal** [comment]
I've done some experimenting with your code to figured out the rule that is failing. 

I found a way to "fix" the highlighting by adding the space before **x** type

<img width="170" alt="screen shot 2015-10-20 at 10 39 52 am" src="https://cloud.githubusercontent.com/assets/8364210/10602164/f29d89f8-7716-11e5-9a9a-ccc14d07f8af.png">

```typescript
interface X {
    b: ( x | y)[];
}

const value = 10;
```

It is related to the [type](https://github.com/TypeStrong/atom-typescript/blob/master/grammars/typescript.cson#L730) rule in the grammar.

It also might be a case, that it's recognised as a function

**Comment by robyoder** [comment]
+1

Thanks for the workaround, @sgal!

**Comment by basarat** [comment]
any effort in grammar should go to https://github.com/TypeStrong/atom-typescript/issues/675 :rose:

**Comment by basarat** [comment]
Should work with release https://github.com/TypeStrong/atom-typescript/releases/tag/v8.0.0 :rose: If not raise issue at https://github.com/Microsoft/TypeScript-TmLanguage/issues and link us :rose:

Thanks @blakeembrey :100:
