### ISSUE TITLE
intellisense for tsx files not working

### ISSUE THREAD

**Issue by ra0o0f** [TypeStrong/atom-typescript#673]
hi

after updating to 7.4.4 intellisense not working with .tsx files, snippet not working too.
ts files are ok

i tried to uninstall and reinstalling plugin, but it doesn't help either.

thanks

**Comment by samuel-vincent** [comment]
Having exactly the same issue.

**Comment by ra0o0f** [comment]
for now stay with 7.4.3

apm install atom-typescript@7.4.3

**Comment by blakeembrey** [comment]
@ra0o0f @samuel-vincent I just pushed a quick patch for the scope of completion and linting. Can you let me know if it works now?

**Comment by ra0o0f** [comment]
@blakeembrey code completion works now, but snippet doesnt yet.

exapmle: `importr` or `import`

![image](https://cloud.githubusercontent.com/assets/2182530/10646946/c6505c90-7842-11e5-968e-67fc651c60ba.png)

**Comment by blakeembrey** [comment]
Unless I'm mistaken, snippets have never been supported there. I'll open a new issue for this.

**Comment by blakeembrey** [comment]
@ra0o0f Support for snippets added with `v7.4.6`

**Comment by ra0o0f** [comment]
@blakeembrey thanks a lot
