### ISSUE TITLE
Review `source.tsx` usage

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/atom-typescript#676]
I changed a few things to use `source.tsx` today, but there's a few parts in the codebase that likely need to be patched.
- `typescriptGrammar.ts` - Is this used?
- `ts-view.ts` - I think this is actually an existing issue, but it's using the `source.ts` grammar for rendering - what about when it's being triggered from a `.tsx` file?
- `settings/language-typescript.cson` - Definitely needs updating, should the rules be different in any way?

**Comment by basarat** [comment]
> typescriptGrammar.ts - Is this used?

Nope. This is the dynamic grammar that we had to disable. Feel free to delete.

> ts-view.ts

Hmmm ... its a wrapper around atom's editor as used in the markdown preview (doc) : https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/atom/components/ts-view.ts#L11-L12 

We could pass it an attribute for `.ts` or `.tsx` logic 

> settings/language-typescript.cson - Definitely needs updating, should the rules be different in any way?

Maybe (i've never quite learnt text mate grammar details completely) ... `atom-react` has a settings file : https://github.com/orktes/atom-react/blob/master/settings/JavaScript%20(JSX).cson
