### ISSUE TITLE
tsconfig.json always save to CRLF on Windows environment

### ISSUE THREAD

**Issue by stan0227** [TypeStrong/atom-typescript#678]
Atom Editor now has line ending selector for selecting ending format of file.

But on Windows environment even I try to select LF format for tsconfig.json which always be saved to CRLF format.

Does it have limitation to solve the issue? Thanks a lot!

**Comment by blakeembrey** [comment]
Looks like it's currently done intentionally and can't be changed (https://github.com/TypeStrong/atom-typescript/blob/master/dist/main/tsconfig/tsconfig.js#L422). The fix here would be to detect the current line endings, like we do with indent, and stringify it back the same.

**Comment by basarat** [comment]
Also the setting needs to be sent from the front end process to the backend process (which is the main reason it hasn't been done yet)

**Comment by slikts** [comment]
> The fix here would be to detect the current line endings, like we do with indent, and stringify it back the same.

Using a separate file instead of `tsconfig.json` would be even better, especially since TS now [supports comments](https://github.com/Microsoft/TypeScript/issues/4987) in `tsconfig.json`.
