### ISSUE TITLE
Go To Declaration should center cursor

### ISSUE THREAD

**Issue by mjohnsonengr** [TypeStrong/atom-typescript#679]
When I press F12 to go to a declaration, the cursor is moved to the destination line and the view scrolls such that the destination is very close to the bottom of the visible area.  It would be nice (and maybe others would agree) if the view adjusted so that the destination line shows up at approximately the middle of the visible area.

My justifications for this suggestion are two-fold, although both reveal that I may be either biased or spoiled.  Discussion will determine which, if either holds true.
1. I am used to Visual Studio which does this (other users may also be migrating to Atom from the same situation)
2. I flipped my monitor 90 degrees so it is in portrait orientation.  It displays about 110 lines of code on the screen, so I tend to lose track of the cursor when it is at the bottom of the screen.

Thoughts?

**Comment by mjohnsonengr** [comment]
I missed the point that may seal the deal.

About 80% of the time that I use Go To Declaration, I'm navigating to a method, and will most likely be looking at the following 10-20 lines very soon after this action.

I keep thinking that other people will probably prefer this differently, which indicates that this might be a candidate for a customization option.  Correct me if it already is and I missed it.

**Comment by basarat** [comment]
We just ask atom to bring the line in view : https://github.com/TypeStrong/atom-typescript/blob/c0d11587e70b54272d7b5ad4497dd5fa35b88fe1/lib/main/atom/gotoHistory.ts#L17-L23

If atom provides an API will will use it ... if not don't feel like writing / maintaining it. Sorry :rose: but a good suggestion nonetheless.

**Comment by basarat** [comment]
Leaving open in case someone files the API endpoint :rose:

**Comment by dsifford** [comment]
I'd love to be able to handle this and send a PR, but I really have no idea where to even begin (atom's api is extremely foreign to me).


That being said, I think these two resources might be handy for those who are able to decipher the api and the structure of this project....


How is was done in atom bookmarks: https://github.com/atom/bookmarks/pull/45/files
The (possibly) relevant api method: https://atom.io/docs/api/v1.7.3/TextEditor#instance-scrollToCursorPosition

Hope that is at least somewhat helpful. 👍

**Comment by lierdakil** [comment]
Released as v12.2.0 :tada:
