### ISSUE TITLE
less than combined with typecast causes bad syntax highlighting

### ISSUE THREAD

**Issue by mjohnsonengr** [TypeStrong/atom-typescript#680]
Being fairly new and ignorant in the ways of Atom, I don't know if this belongs here or Atom, but assume somebody would correct me if I'm putting this in the wrong place.

I have a code file where the bottom half of it is all yellow for some reason.  It appears to be triggered by the combination of less-than and a typecast inside a for loop.  By removing either the typecast or the less than, the syntax highlighting looks great.  Attached is an image of the problem as well.

```typescript
export class Foo {
    public doStuff(item: Bar) {
        // for some reason, we know that item is a Bar2
        for (var i = 0; i < (<Bar2>item).getStuff(); i++) {
            // stuff to do
        }
    }
}

export class Bar {

}

export class Bar2 extends Bar {
    public getStuff() {
        return 2;
    }
}
```
![image](https://cloud.githubusercontent.com/assets/7274059/10676405/1b9260ce-78c3-11e5-82e6-8de6a60e6334.png)

**Comment by basarat** [comment]
Belongs here. Bug in the grammar : https://github.com/TypeStrong/atom-typescript/blob/master/grammars/typescript.cson
up for grabs :rose:

**Comment by basarat** [comment]
@mjohnsonengr was this a tsx file?

**Comment by basarat** [comment]
> was this a tsx file?

Answered my own question. Ts file 
![image](https://cloud.githubusercontent.com/assets/874898/10987971/52d1a994-848c-11e5-8804-57d6e62830aa.png)

**Comment by basarat** [comment]
any effort in grammar should go to https://github.com/TypeStrong/atom-typescript/issues/675 :rose:

**Comment by basarat** [comment]
Should work with release https://github.com/TypeStrong/atom-typescript/releases/tag/v8.0.0 :rose: If not raise issue at https://github.com/Microsoft/TypeScript-TmLanguage/issues and link us :rose:
