### ISSUE TITLE
Support stripInternal compiler option

### ISSUE THREAD

**Issue by adidahiya** [TypeStrong/atom-typescript#684]
atom-typescript v7.5.1 complains about `Unknown Option: stripInternal` in tsconfig.json, but it works with `tsc` just fine.

https://github.com/Microsoft/TypeScript/wiki/Compiler-Options

**Comment by basarat** [comment]
Released : https://github.com/TypeStrong/atom-typescript/releases/tag/v7.6.1 :rose:

**Comment by adidahiya** [comment]
@basarat thanks!
