### ISSUE TITLE
Intellisense for overloaded methods and constructors

### ISSUE THREAD

**Issue by mjohnsonengr** [TypeStrong/atom-typescript#686]
This might be candidate for being broken up, but before I flood the issue log with a bunch of stuff, I want to make sure these are valid here.  Some may be non-issues and some may actually be in the scope of autocomplete-plus.

What works: When I hover over a method, I can see it's signature.  When I press Ctrl+Space to activate autocomplete-plus, I see the method signatures in the autocomplete list.

Problem 1: When I hover over an overloaded method, I only see the first signature, and a "(+3 overloads)" tag.

Problem 2: When I hit ctrl+space in a constructor's parameter list, I don't get anything.

Ultimately, this all leads to the problem that prompted me to post here: I cannot see an overloaded constructor's signature without going to its definition.

![image](https://cloud.githubusercontent.com/assets/7274059/10761557/8cab9010-7c87-11e5-8312-afe3e8503e99.png)

**Comment by basarat** [comment]
> Problem 1: When I hover over an overloaded method, I only see the first signature, and a "(+3 overloads)" tag

Create a seperate issue. Belongs here, but we will probably defer to Microsoft/TypeScript as the language service endpoint probably doesn't provide this :rose: 

> Problem 2: When I hit ctrl+space in a constructor's parameter list, I don't get anything.

Not sure what you meant. It only works at the root `()`  (same limitation applies for plain functions):

![image](https://cloud.githubusercontent.com/assets/874898/10775639/50bc90d6-7d5e-11e5-9c22-73c83cf1350a.png)

Create an issue along the lines of `partial function argument snippet completion` if you want to get the snippet in `someFunc(123,/*here*/)` (if that is what you meant) :rose:

**Comment by mjohnsonengr** [comment]
> Create a seperate issue.

Will do.

> Not sure what you meant. It only works at the root ()

There is more to say about this problem as I only gave you one case; Since I saw your example worked (and indeed it worked in my environment), I played around a little bit and saw that in your example, if you overload the constructor to also take no arguments, e.g.

    class Foo {
        constructor();
        constructor(foo:string);
        constructor(foo?:string){}
    }

then activating autocomplete with the cursor `let foo = new Foo(/*here*/)` now shows nothing.  The same can be said if there were only a single constructor that took no arguments.

*The problem primarily happens when a method has no arguments, or has an overload with no arguments.*

That being said, would you like me to create a separate issue for that or can we recycle this one?

> Create an issue along the lines of partial function argument snippet completion if you want to get the snippet in someFunc(123,/*here*/) (if that is what you meant) :rose:

I actually didn't even notice that the snippet only shows when you are at the beginning of the parens; I'll create said issue :grin: 

I will be creating two more issues as discussed above, but I'd still like to hear back about the middle child above: auto completion box when calling a method that takes no arguments.

**Comment by basarat** [comment]
> would you like me to create a separate issue for that or can we recycle this one?

A new issue. As its easier for me to mark as up for grabs and people don't need to read all that has been said here :rose:
