### ISSUE TITLE
Syntax Highlighting breaks for implements if followed by extends

### ISSUE THREAD

**Issue by avarices** [TypeStrong/atom-typescript#689]
If you insert the following code into atom, typescript will color the last class improperly

    interface SomeInterface {

    }

    class ParentClass {
        constructor() {

        }
    }

    class MyClass extends ParentClass implements SomeInterface {

        constructor() {
            super()
        }

    }

Here is an image to show you what I mean
![Image of syntax highlighting bug](http://i.imgur.com/kvhINFm.png)
As you can see the highlighting for the last three words `on line 11` all have the same highlighting. 

Is this fixable, if so when should I expect an update? Thanks for looking into the issue

**Comment by basarat** [comment]
> Is this fixable, if so when should I expect an update? Thanks for looking into the issue

Up for grabs for now

**Comment by basarat** [comment]
any effort in grammar should go to https://github.com/TypeStrong/atom-typescript/issues/675 :rose:

**Comment by basarat** [comment]
Closed in favor of : https://github.com/Microsoft/TypeScript-TmLanguage/issues/4 :rose:
