### ISSUE TITLE
Incorrectly marked errors before a file is saved.

### ISSUE THREAD

**Issue by hiscodeness** [TypeStrong/atom-typescript#691]
Just updated to atom-typescript 7.6.3. I see a lot of incorrectly marked errors while editing a file and it is highly distracting:
![image](https://cloud.githubusercontent.com/assets/8625258/10789932/06d75732-7d89-11e5-9987-f4e7971096de.png)

Simply saving the file makes atom 're-evaluate' the contents and all incorrectly marked errors disappear:
![image](https://cloud.githubusercontent.com/assets/8625258/10789948/18d49152-7d89-11e5-9296-1266e6d1a158.png)

**Comment by hiscodeness** [comment]
Restarting the editor fixed this issue.

**Comment by basarat** [comment]
Try sync next time ... its faster https://github.com/TypeStrong/atom-typescript#sync
