### ISSUE TITLE
noImplicitAny error in tsc missing in atom-ts

### ISSUE THREAD

**Issue by slikts** [TypeStrong/atom-typescript#693]
tsc version 1.6.2
##### tsconfig.json:

`{
  "compilerOptions": {
    "noImplicitAny": true
  },
  "files": [
    "index.ts"
  ]
}`
##### index.ts:

`let foo = {}; foo["bar"];`

tsc error:

`index.ts(1,15): error TS7017: Index signature of object type implicitly has an 'any' type.`

The same error should be in atom-ts but isn't.

**Comment by slikts** [comment]
One more error that atom-ts doesn't show:

```{
  "compilerOptions": {
    "target": "es6"
  },
  "files": [
    "index.ts"
  ]
}```

```import bla = require("./test");```

This error shows up in tsc but is missing from atom-ts:

```index.ts(1,1): error TS1202: Import assignment cannot be used when targeting ECMAScript 6 or higher. Consider using 'import * as ns from "mod"', 'import {a} from "mod"' or 'import d from "mod"' instead.```

**Comment by slikts** [comment]
Forgot to mention that atom-ts version is 7.6.3.

**Comment by basarat** [comment]
> Import assignment cannot be used when targeting ECMAScript 6 or higher. Consider using 'import * as ns from "mod"', 'import {a} from "mod"' or 'import d from "mod"' instead.

They can be used in TypeScript latest (the version we are using) :rose: 

> noImplicitAny error in tsc missing in atom-ts

That still needs analysis. Marking as up for grabs :rose:

**Comment by JJBocanegra** [comment]
The problem of the first post is still happening and this have barely a year already.

**Comment by finaiized** [comment]
I just tested this with TypeScript 2.4.1, Atom 1.18.0, and atom-typescript 11.0.6 and can confirm this seems to work now with the above configuration:

![noImplicitAny error](https://user-images.githubusercontent.com/955189/27991024-ad07a8d2-641e-11e7-8b7b-b6a50b94bdbe.png)
