### ISSUE TITLE
330 releases in 1 year?

### ISSUE THREAD

**Issue by yoorek** [TypeStrong/atom-typescript#695]
Releasing every 1-3 commits, 2-4 times a day? Really?

**Comment by johnnyreilly** [comment]
Never heard of continuous delivery? :smile:

**Comment by yoorek** [comment]
Yep, it's a new trend - Extreme Continuous Delivery ;-)

**Comment by basarat** [comment]
:rose:

**Comment by cebor** [comment]
+1 for a weekly release cycle!

**Comment by poelstra** [comment]
Maybe we can have it both ways: would it be possible to publish the
'dailies' to @next, and e.g. once a week pick something that has proven
to be stable as @latest? 

That way people will have a stable experience by default, and can opt-in
to the bleeding edge. 

On 2015-11-03 12:21, Felix Itzenplitz wrote: 

> +1 for a weekly release cycle! 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/TypeStrong/atom-typescript/issues/695#issuecomment-153322671

**Comment by basarat** [comment]
> +1 for a weekly release cycle!

@cebor you can run updates on a weekly basis on a day that suits *you* best :rose:

> Maybe we can have it both ways: would it be possible to publish the
> 'dailies' to @next, and e.g. once a week pick something that has proven
> to be stable as @latest?

@poelstra nice idea. The conventional way of doing this in atom is create *two* packages e.g in this case it would be `atom-typescript-beta`. Don't feel like going through that overhead just yet. Noted though :rose:
