### ISSUE TITLE
No longer rewrite tsconfig.json `files` section

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#701]
Tsconfig now supports comments : https://github.com/Microsoft/TypeScript/pull/5450/files 

It's already difficult to rewrite tsconfig.json (to keep the filesGlob in sync). People have complained about merge conflicts https://github.com/TypeStrong/atom-typescript/issues/266  and options like formatting : https://github.com/TypeStrong/atom-typescript/issues/678 

I'm thinking of disabling `files` rewriting *permanently*  thoughts? @blakeembrey @nycdotnet

**Comment by blakeembrey** [comment]
I'm cool with it, but I can see it breaking a lot of peoples workflows after exploring some of the issues here around `tsconfig`. Maybe we need to pull it into `tsconfig` and/or provide a CLI for those users, but note a comment caveat. Or just leave it as an option and disable it going forward.

For tooling, anything using `tsconfig` will continue support `filesGlob`. I don't think there's much using it though, so everything else will not work. Not sure how many people are relying on the expansion, the hope is not many to none.

**Comment by nycdotnet** [comment]
I like the current behavior, but I'm not going to fight for it if you're unwilling to support it anymore.  I do think that it would be fine to have the default atom-typescript-created tsconfig.json exclude `node_modules` and to not use the `files` or `filesGlob` properties, for example.

**Comment by basarat** [comment]
I guess the issue is that on bad atom days (and they tend to happen), they would not have another fallback IDE to support their code :-/ 

Will provide an option to stop expansion for those that care about their comments + formatting. The rest can use it as it stands now

Will create a seperate issue to track that. Thanks! :rose:
