### ISSUE TITLE
Option to prevent rewriting tsconfig.json file

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#703]
For people that don't care about keeping `files` in sync (for other IDE use) or just don't want us messing with their `tsconfig.json` file formatting, provide an option to disable tsconfig.json overwriting

* [x] Add some place to use this setting (the simplest location would be to use `tsconfig.json` as that file is available to `tsconfig.ts` (our code that rewrites `tsconfig.json`)
* [x] Add code to `tsconfig.ts` to use this option
* [x] Document option  [here](https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md) and optionally [here](https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md)

**Comment by JKillian** [comment]
(+1) We're using `grunt-ts` to update the files on compile and it writes paths/orders them a little different than `atom-typescript`. It would be great to have a way to disable auto-updating `files`.

**Comment by slikts** [comment]
The current atom-ts options in `tsconfig.json` have the problem of being easy to confuse with the default TS options, especially to people unfamiliar with atom-ts. Adding more options would make this problem worse, so new options should at least be under a separate key to make it clear what they belong to.

**Comment by basarat** [comment]
> so new options should at least be under a separate key to make it clear what they belong to

:+1: in this case as we want grunt to ignore this option

**Comment by blakeembrey** [comment]
If it's going to be a key in `tsconfig.json`, it should be default off otherwise people need to add implementation specific details to disable implementation specific features. I would prefer a checkbox in the atom package itself. I personally don't use any of the auto-updating in any packages, but I know it's always possible that I'd end up consuming one.

**Comment by sszuflita** [comment]
This feature is fairly annoying for my project's setup and I'd be happy to implement this. I'm currently having some trouble getting the project to build; are their docs on this?

When I run grunt, I get a ton of errors like:

atom-typescript/lib/main/atom/typescriptGrammar.ts(183,53): error TS2503: Cannot find namespace 'ts'.
atom-typescript/lib/main/lang/core/project.ts(43,32): error TS2304: Cannot find name 'ts'.
atom-typescript/lib/main/lang/fixmyts/quickFixes/addClassMember.ts(112,13): error TS2322: Type '{ span: { start: any; length: number; }; newText: string; filePath: any; }' is not assignable to type 'Refactoring'.

**Comment by sszuflita** [comment]
I realized that the grunt file was broken (https://github.com/TypeStrong/atom-typescript/issues/4).

I'm working on this now.

**Comment by basarat** [comment]
Released : https://github.com/TypeStrong/atom-typescript/releases/tag/v7.10.2 :rose:

**Comment by tomitrescak** [comment]
@basarat The tsconfig now stopped automatically recognising new files aeith the following error in the console:

```
TypeError: Cannot read property 'rewriteTsconfig' of undefined
    at Object.getProjectSync (/Users/tomi/.atom/packages/atom-typescript/dist/main/tsconfig/tsconfig.js:218:81)
    at getOrCreateProjectFile (/Users/tomi/.atom/packages/atom-typescript/dist/main/lang/projectCache.js:73:36)
    at Object.getOrCreateProject (/Users/tomi/.atom/packages/atom-typescript/dist/main/lang/projectCache.js:140:27)
    at Object.getProjectFileDetails (/Users/tomi/.atom/packages/atom-typescript/dist/main/lang/projectService.js:331:34)
    at Child.RequesterResponder.processRequest (/Users/tomi/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:48:60)
    at process.<anonymous> (/Users/tomi/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:226:23)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

**Comment by tomitrescak** [comment]
Is there any quick fix for this or shall I roll back to previous version? Thanks!

**Comment by thomastrapanese** [comment]
up, i have the same issue

**Comment by basarat** [comment]
@tomitrescak rollback for now please. 

Pinging @sszuflita for investigation :rose:

**Comment by basarat** [comment]
@tomitrescak nevermind. Hotfix released : https://github.com/TypeStrong/atom-typescript/releases/tag/v7.11.0 hopefully that fixes it :rose:

**Comment by thomastrapanese** [comment]
it work well for me, thanks
