### ISSUE TITLE
Renamed/deleted files with errors stays in error panel - restart required

### ISSUE THREAD

**Issue by yoorek** [TypeStrong/atom-typescript#705]
When I delete file with error or change it's name error stays in error panel of "opened files" (even it's not opened) - refresh button does not help, re-build does not help. Need to restart Atom to get rid off error. 

<img width="858" alt="zrzut ekranu 2015-11-04 o 08 58 43" src="https://cloud.githubusercontent.com/assets/271500/10932683/0061c032-82d3-11e5-83a8-5529d50126df.png">

**Comment by basarat** [comment]
Yeah, the `no project file found` error is more sticky and only goes away *if you create the tsconfig file using the provided command*. 

Up for grabs :rose:

**Comment by yoorek** [comment]
Look closer at the screenshot - it complains about "no tsconfig" for file that is both CLOSED and DELETED (in .Trash folder) - how "create the tsconfig file using the provided command." would help? You suggest that I I create tsconfig for Trash files, quite hilarious :-)

**Comment by basarat** [comment]
> how "create the tsconfig file using the provided command." would help? You suggest to create tsconfig for Trash files ;-) ?

Such trash talk 🌹
