### ISSUE TITLE
parenthesized types break highlighting

### ISSUE THREAD

**Issue by chadaustin** [TypeStrong/atom-typescript#706]
```
  message_handlers: (number);
```

breaks highlighting for the rest of the file.

```
  message_handlers: number;
```

works fine.

**Comment by basarat** [comment]
Verified. Up for grabs :rose:

```ts
var message_handlers: (number);
var bar = 123;
```
![image](https://github-cloud.s3.amazonaws.com/assets%2F874898%2F10958023%2F037a12d8-83be-11e5-9130-c537ec1e05c3.png)

**Comment by basarat** [comment]
any effort in grammar should go to https://github.com/TypeStrong/atom-typescript/issues/675 :rose:

**Comment by mjohnsonengr** [comment]
Hi,

I think this is related so I'll attach a screenshot; the parentheses around typing information in this case is in a method parameter.

![image](https://cloud.githubusercontent.com/assets/7274059/11476241/e15aa322-973e-11e5-83ba-4640fbfdacc6.png)

**Comment by basarat** [comment]
Should work with release https://github.com/TypeStrong/atom-typescript/releases/tag/v8.0.0 :rose: If not raise issue at https://github.com/Microsoft/TypeScript-TmLanguage/issues and link us :rose:
