### ISSUE TITLE
Syntax Highlighting not working for function shorthand in objects

### ISSUE THREAD

**Issue by zimme** [TypeStrong/atom-typescript#707]
```js
callSomeFunctionWithOptions({
  // function not highlighted
  callback(error, result): void {
    ...
  }
});

callSomeFunctionWithOptions({
  // function highlighted
  callback: function callback(error, result): void {
    ...
  }
});
```

**Comment by basarat** [comment]
Verified bug: 

```ts
let foo = {
    // not highlighted
    callback(error, result): void {
    }
}

let bar = {
    // function highlighted
    callback: function callback(error, result): void {
    }
}
```

![image](https://cloud.githubusercontent.com/assets/874898/10985450/74da2104-8475-11e5-991e-3f902b8e867f.png)

**Comment by quadrophobiac** [comment]
Hi there, I'm interested in picking up this bug to work on. I've developed on Electron in the past (most recent PR here https://github.com/theodi/comma-chameleon/pull/76) and hacked away at Atom getting a few personal workflows in place. Can I proceed on working on this?

**Comment by basarat** [comment]
@quadrophobiac any effort in grammar should go to : https://github.com/TypeStrong/atom-typescript/issues/675

**Comment by basarat** [comment]
Should work with release https://github.com/TypeStrong/atom-typescript/releases/tag/v8.0.0 :rose: If not raise issue at https://github.com/Microsoft/TypeScript-TmLanguage/issues and link us :rose:
