### ISSUE TITLE
Multiple tsconfig.json files - files section no longer updated

### ISSUE THREAD

**Issue by LivesleyWA** [TypeStrong/atom-typescript#708]
I have a project with two tsconfig.json files. Used to update the files section of both. No longer works - one does the other does not.

**Comment by LivesleyWA** [comment]
This seems to be a wider problem. I have a project where none of the tsconfig files entries are being populated. Same general entries and it was working before the latest updates so I don't think it's the tsconfig file.

**Comment by Zyzle** [comment]
Yup, I'm seeing the same problem here, `filesGlob` no longer populates the files section.

Atom 1.2.0-beta-0 atom-typescript 7.8.0

**Comment by basarat** [comment]
@LivesleyWA try running `sync` on your project with a ts file from the same project open https://github.com/TypeStrong/atom-typescript#sync

Does that fix it?

**Comment by LivesleyWA** [comment]
I have a structure

 - lib
  tsconfig.json
  - ts
   - stuff one
   - stuff two
 - test
  tsconfig.json
  - ts
   - test stuff one
   - test stuff two

By default, the lib tsconfig file is populated whilst the test tsconfig file is not.

For a number of reasons to do with Webstorm (used for testing nodejs apps) test tsconfig contains references to lib folders (Webstorm can't handle more than one tsconfig file and seems to find the test tsconfig file). So test ts config has the following

"filesGlob": [
    "./ts/**/*.ts",
    "./typescript references/**/*.d.ts",
    "../lib/ts/**/*.ts",
    "../lib/typescript references/**/*.d.ts"
  ],

After a bit of fiddling I have found that to regenerate test tsconfig
- At least one ts file must be in the test folder containing the test tsconfig file or one of its sub-folders
- A sync run on a ts files in the test stuff xxx folder or a  test stuff xxx sub-folder regenerates the test tsconfig file

Once the test tsconfig file is synched, it continues to work, although the lib tsconfig file then stops synching. If I shut down Atom and restart, the synching reverts to the lib tsconfig file.

Hope this helps. Now I know the trick I at least have a workable work-around.

**Comment by basarat** [comment]
This is by design. We cache the contents of `tsconfig` till you open a file we do not know about from our previous look at tsconfig. And we have a single `file` -> `tsconfig` map so if a file is in two tsconfig the last tsconfig that was used is what is considered *active*. We show this in *our panel*.

![image](https://cloud.githubusercontent.com/assets/874898/11173924/cb00a096-8c70-11e5-8b7b-9d9d3f08e3e4.png)

An ideal solution would be to force the user to select the tsconfig they are working with upfront, or provide an option for *sticky current project* :rose:

**Comment by flahertyb** [comment]
Yes, would be nice to have manual control over the active tsconfig.

**Comment by psnider** [comment]
I'm using version 8.5.0 of atom-typescript.

I have several tsconfig.json files in my project, which has several aggregated micro-services,
each laid out in this structure:
- src/SERVICE_NAME/server/tsconfig.json
- src/SERVICE_NAME/client/tsconfig.json

The tsconfig files also reference some shared files in:
- src/shared.

I've found that sometimes the tsconfig.json updating works fine, 
but other times, it just doesn't seem to happen no matter what I try.

Unfortunately, I haven't found any clues to what triggers this behavior.

**Comment by basarat** [comment]
> but other times, it just doesn't seem to happen no matter what I try

If you open a file from `server` *first* then all the files referenced (including `shared`) will point to that `tsconfig.json`. Then even if you update `client/tsconfig.json` it will have seemingly *no* effect on any file that the editor opens (as they all already point to `server`). 

# Fix

We need a project selector. I'll create an issue documenting this fact.

**Comment by basarat** [comment]
I've created an issue for discussion : https://github.com/TypeStrong/atom-typescript/issues/910 :rose:
