### ISSUE TITLE
Preferred quote character fails

### ISSUE THREAD

**Issue by DonSanto** [TypeStrong/atom-typescript#710]
Adding a single quotation mark in the settings for "preferred quote character" does not remove the warnings that single quotes should be double quotes.

**Comment by blakeembrey** [comment]
@DonSanto Do you have more details (screenshot, error message, etc) for this? It sounds like this is coming from a linter, and not from `atom-typescript`.

**Comment by DonSanto** [comment]
@blakeembrey Thanks, nice one. Indeed it was a linter issue. linter-tslint seams to not approve single quotes characters.

**Comment by blakeembrey** [comment]
There's a configuration option for that in `tslint`. Take a look at the README (https://github.com/palantir/tslint) and usage (https://github.com/typings/cli/blob/master/tslint.json#L72).

**Comment by alexgorbatchev** [comment]
I'm seeing this in 10.1.7 using typescript 2.0.3 installed globally.

![dashboard-navigation_20161010091719](https://cloud.githubusercontent.com/assets/65633/19242955/5c065ff2-8eca-11e6-9ee2-754ab23c7a19.png)
