### ISSUE TITLE
Shouldn't depend on 'linter'

### ISSUE THREAD

**Issue by ssorallen** [TypeStrong/atom-typescript#711]
While this package does provide a "linter" service, 'linter' is not actually a dependency of this package. Because of that dependency, installing 'atom-typescript' also installs 'linter' even if you don't want that functionality.

The 'package-deps' section could be removed.

**Comment by blakeembrey** [comment]
@ssorallen I think keeping the automatic installation is a good experience, users are easily confused otherwise. The linter is a common UI to interact with too. You can always disable the linter if you don't want to use it.

**Comment by ssorallen** [comment]
I had the opposite experience where a user didn't notice 'linter' had even been installed and hadn't wanted it. I can understand wanting to avoid a poor experience where someone wants a linting experience, but that can be shown in documentation at the top of the README.

Right now if you install atom-typescript and then uninstall linter, Atom reinstalls the linter even if you don't want it and even though it's not a real dependency.

**Comment by blakeembrey** [comment]
I would open an issue under https://github.com/steelbrain/package-deps for the unable to uninstall, it isn't maintaining any kind of state which remembers what's previously been installed. If you want to disable it, there's a disable button for packages - that should work for you. May I ask what they were using `atom-typescript` for instead of linting?

Anyway, I'm sure it can be added to the README that it'll be installed.

**Comment by ssorallen** [comment]
Most of the features don't have to do with linting do they? Autocomplete, snippets, format code, etc.

The [nuclide-diagnostics](https://github.com/facebook/nuclide/tree/master/pkg/nuclide/diagnostics) package can also consume linter/provideLinter providers, so we didn't want 'linter' installed.

**Comment by blakeembrey** [comment]
No, it doesn't, but having information about your code is the biggest draw to me (yes, autocompletion and such is cool, personal biggest feature is obviously the type safety). I was just looking at that package too, it's awesome if it's supporting `linter` providers - I'm tempted to use it now :+1:

**Comment by ssorallen** [comment]
> Edit: Fragmentation is a PITA too here

Agreed! But the beauty of just going through `providedServices` is there can be many implementations that consume the service.

Since it has no actual hard dependency, I'd still remove it. However, I can see some value in forcibly installing one consumer I suppose though if there's no easy way to inform someone they need to install 'linter' or another consumer separately.
