### ISSUE TITLE
Using exclusion in filesGlob still giving errors

### ISSUE THREAD

**Issue by JaKXz** [TypeStrong/atom-typescript#713]
This is my `tsconfig.json`:

```json
{
  "version": "1.6.2",
  "compilerOptions": {
    "experimentalDecorators": true,
    "module": "commonjs",
    "noImplicitAny": false,
    "target": "ES5",
    "sourceMap": true
  },
  "filesGlob": [
    "typings/tsd.d.ts",
    "index.ts",
    "!**/*.spec.ts",
    "!*spec.ts", 
    "!mocha.conf.ts"
  ],
  "files": [
    "typings/tsd.d.ts",
    "index.ts"
  ]
}
```

However, I'm still seeing Project-wide TS errors in Atom, and I think as a result I'm not getting auto-completion as I work... the error message says, for each of those files:

> The file "/absolute/path/to/mocha.conf.ts" is not included in the TypeScript compilation context. If this is not intended, please check the "files" or "filesGlob" section of your tsconfig.json file. **at line 1 col 1 in mocha.conf.ts**

Also, I'm assuming (if this isn't broken) that I only need `!**/*.spec.ts` to ignore all those files from the current directory down?

**Comment by blakeembrey** [comment]
@JaKXz That error is a separate error. It's a duplicate of #558

**Comment by JaKXz** [comment]
Ah. Will close. Thanks.
