### ISSUE TITLE
Updating to “atom-typescript@7.8.0” failed.

### ISSUE THREAD

**Issue by darkoverlordofdata** [TypeStrong/atom-typescript#714]
I selected update, and got this error. Now I don't have any syntax highlighting or code completion, and it says it can't find my tsconfig.json. Basically, atom is now unusable.

events.js:72

        throw er; // Unhandled 'error' event
              ^

Error: ENOENT, open '/home/bruce/.atom/packages/atom-typescript/node_modules/emissary/node_modules/es6-weak-map/node_modules/es5-ext/test/error/custom.js'

**Comment by impinball** [comment]
Try `apm uninstall atom-typescript; apm install atom-typescript`.

**Comment by basarat** [comment]
Sorry about that. Please see : https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#failed-to-update Comment if that doesn't fix it :rose:
