### ISSUE TITLE
Auto-complete type suggestion

### ISSUE THREAD

**Issue by JaKXz** [TypeStrong/atom-typescript#716]
I love how atom-typescript suggests the given types for undeclared variables on hover. However, it would be awesome if there was a keystroke to put in this type suggestion automatically, because they can get complicated... e.g.

```ts
const ALLOWED_METHODS = _(['post']);
```

is a `_.LoDashImplicitArrayWrapper<string>`, but the only way to remember that is to go into the `lodash.d.ts` file manually copy it in.

Did a quick search for this through the FAQs/commands/issues/PRs, didn't see anything, but apologies if this is a duplicate.

**Comment by basarat** [comment]
You mean have `Keyboard shortcut for Type information` currently only shown on `Mouse Hover` ? https://github.com/TypeStrong/atom-typescript#type-information-on-hover

**Comment by JaKXz** [comment]
Yep!

**Comment by basarat** [comment]
@JaKXz cool, created a clean issue for the request : https://github.com/TypeStrong/atom-typescript/issues/726 :rose:
