### ISSUE TITLE
It can't seem to find the tsconfig in my project

### ISSUE THREAD

**Issue by impinball** [TypeStrong/atom-typescript#717]
It used to work, but since upgrading to 7.8.0, it can't find my tsconfig.json anymore. It could even in 7.7.2

**Comment by basarat** [comment]
The only change between 7.8.0 and 7.7.2 was a change in `ntypescript` : https://github.com/TypeStrong/atom-typescript/commit/747f7d2bc9bfe319e49b8a420cf506509c2c69db don't see why that would break it.

It's been working fine here ... so would need repro to help :-/ :rose:

**Comment by impinball** [comment]
It does this on load. I tried reinstalling, but it might be an issue with other plugins. I'll close this, and re-open it (or create a new issue) when I have time to properly vet the problem.

**Comment by basarat** [comment]
> It does this on load

We basically cache the contents of tsconfig.json and don't do any additional disk watching and if there is a new file we only update tsconfig.json if you open the new file in atom. Alternatively you can do a sync ;) :rose:

**Comment by impinball** [comment]
I tried that, but like I said, I need to better vet the problem. (My Chrome
wouldn't work on install, and only a few weeks later did I finally figure
out that the problem was stale dconf entries that needed removed.)
