### ISSUE TITLE
Imports get lost, when classes are only referenced in switch/case branches

### ISSUE THREAD

**Issue by mechanoid** [TypeStrong/atom-typescript#719]
hi,

as stated in the headline, it seems that there is a problem when resolving the require statements for an output file. If a required class is only referenced inside switch/case statement the according require statement is not available in the list of required files anymore.

To get a better understanding of the problem, you may take a look at an example i have created:

https://github.com/mechanoid/ts-import-error-test

Because the same is going well with `tsc` it seems to be a problem of the atom-typescript plugin. 

Maybe you have a hint for me, or maybe you can validate that it is an actual bug. 

Thanks in advance, Falk

**Comment by basarat** [comment]
Seems like an issue with TypeScript nightly. Issue moved here : https://github.com/Microsoft/TypeScript/issues/5666 :rose:

**Comment by DanielRosenwasser** [comment]
@mechanoid check out the latest nightly build.

**Comment by basarat** [comment]
Released https://github.com/TypeStrong/atom-typescript/releases/tag/v7.10.0 :rose:
