### ISSUE TITLE
New unreachable code compiler options need to be handled

### ISSUE THREAD

**Issue by mjohnsonengr** [TypeStrong/atom-typescript#720]
Version 7.8.0 updated to the latest ntypescript which features some new compiler options: `allowUnreachableCode`, `allowUnusedLabels`, `noImplicitReturns`, and `noFallthroughCasesInSwitch` which are all unrecognized in tsconfig.json.

**Comment by basarat** [comment]
# Guidance 

https://github.com/TypeStrong/atom-typescript/blob/11f485ba80dc7e4aeee6176714c1efbff7398b9e/lib/main/tsconfig/tsconfig.ts#L12-L16
