### ISSUE TITLE
Auto-complete running much slower after update

### ISSUE THREAD

**Issue by stacklance** [TypeStrong/atom-typescript#722]
After the latest update, I found that the auto-complete is running much slower. Actually, there are a lot more auto-complete jobs running now. For example, when trying to do auto-complete for relative paths on an import, the number of jobs that get run eventually are around 40 for me, whereas before it used be like 10.

**Comment by basarat** [comment]
@stacklance can you share your tsconfig.json . Also see : https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#for-really-large-projects-atom-typescript-gets-slow :rose:

**Comment by lazutkin** [comment]
Same problem. Today I need restart Atom in order to get workable autocompletion

**Comment by basarat** [comment]
@lazutkin can you share your tsconfig.json :)

**Comment by lazutkin** [comment]
Sure!

```
{
    "version": "1.7",
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "sourceMap": false,
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "outDir": "./build"
    },
    "compileOnSave": false,
    "filesGlob": [
        "./src/**/*.ts",
        "!./node_modules/**/*.ts",
        "!./src/typings/**/*.ts"
    ],
    "files": [...],
    "formatCodeOptions": {
        "indentSize": 2,
        "tabSize": 2,
        "newLineCharacter": "\r\n",
        "convertTabsToSpaces": true,
        "insertSpaceAfterCommaDelimiter": true,
        "insertSpaceAfterSemicolonInForStatements": true,
        "insertSpaceBeforeAndAfterBinaryOperators": true,
        "insertSpaceAfterKeywordsInControlFlowStatements": true,
        "insertSpaceAfterFunctionKeywordForAnonymousFunctions": false,
        "insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
        "placeOpenBraceOnNewLineForFunctions": false,
        "placeOpenBraceOnNewLineForControlBlocks": false
    },
    "exclude": [],
    "atom": {
        "rewriteTsconfig": true
    }
}
```

**Comment by basarat** [comment]
@lazutkin like I mentioned https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#for-really-large-projects-atom-typescript-gets-slow the `filesGlob` should be `"!node_modules/**",` instead of `"!node_modules/**/*.ts",` Same for other excludes :rose: That should fix it for you :rocket: 

Also since stacklance hasn't responded with their tsconfig closing the issue :rose:

**Comment by lazutkin** [comment]
Ok, thanks!
