### ISSUE TITLE
Is the value of 'this' in switch statement in Typescript 1.6.2 and atom-typescript emited incorrectly?

### ISSUE THREAD

**Issue by kpgarrod** [TypeStrong/atom-typescript#723]
I asked a question in SO:  http://stackoverflow.com/questions/33710856/is-the-value-of-this-in-switch-statement-in-typescript-1-6-2-and-atom-typescri

The issue doesn't seem to occur in VSCode on my system or in WebStorm on somebody else's, so I guess it is looking like an atom-typescript issue. Here is a copy of the SO post:

I have some Typescript code that looks something like this:

    class Test {
	    private userId: string
	    constructor() {
          this.userId = 'test'
	    }
        test() {
		  return new Promise((resolve, reject) => {
			let sharing = 'private'
			console.log("before switch this.userId", this.userId);
			switch (sharing) {
		      case "private":
			    resolve(this.userId);
				break;
			}
		  })
        }
    }

If I edit it in [the Typescript playground][1] the following Javascript code is emitted as I expect:

    var Test = (function () {
      function Test() {
        this.userId = 'test';
      }
      Test.prototype.test = function () {
        var _this = this;
        return new Promise(function (resolve, reject) {
            var sharing = 'private';
            console.log("before switch this.userId", _this.userId);
            switch (sharing) {
                case "private":
                    resolve(_this.userId);
                    break;
            }
        });
      };
      return Test;
    })();

However, if I edit the same code in my installed Atom editor, what is emitted is:

    var Test = (function () {
      function Test() {
        this.userId = 'test';
      }
      Test.prototype.test = function () {
        var _this = this;
        return new Promise(function (resolve, reject) {
            var sharing = 'private';
            console.log("before switch this.userId", _this.userId);
            switch (sharing) {
                case "private":
                    resolve(this.userId); // This resolve is missing a _
                    break;
            }
        });
      };
      return Test;
    })();

The difference is in the resolve statement 12 lines down. What is being resolved is `this.userId` instead of `_this.userId`.

I am running a new installation with:

 - Atom 1.1.0
 - atom-typescript 7.8.0 
 - Ubuntu 15.10
 - typescript 1.6.2 installed with npm

  [1]: http://www.typescriptlang.org/Playground

**Comment by basarat** [comment]
Released https://github.com/TypeStrong/atom-typescript/releases/tag/v7.10.0 :rose:

**Comment by kpgarrod** [comment]
@basarat Thanks for the fantastic support as usual! I noticed that the bug was in Typescript 1.8.0. I know that you include your own version of Typescript in the plugin, but with 135,000 users, I wonder if it is still appropriate to use quite such a bleeding edge version? I know it's a balancing act but the editor/plugin is already the best available, so maybe now is the time to favour reliability over new features? Just a thought.

**Comment by basarat** [comment]
> I know it's a balancing act but the editor/plugin is already the best available, so maybe now is the time to favour reliability over new features? Just a thought.

Agreed and thanks for the kind words! But don't want the [technical debt](https://en.wikipedia.org/wiki/Technical_debt) (< learnt this term from @blakeembrey, just thought I'd share the term which might already be familar to you but wasn't to me :rose:) of not updating to TypeScript latest :rose:

That said there is nothing stopping a user from not updating atom-ts for a while, we don't force push it down to users. I have started to make TypeScript version updates a `minor` (instead of `patch`) version changes to be more explicit.
