### ISSUE TITLE
String literal types shown as errors (red highlighting) but compile correctly.

### ISSUE THREAD

**Issue by tomsdev** [TypeStrong/atom-typescript#724]
I found this bug while trying out the new "String literal types" syntax with examples from https://github.com/Microsoft/TypeScript/pull/5185

I believe it's an atom-typescript bug as it does compile correctly. I also found a workaround as you can see in the screenshot below by wrapping the string literal types in parenthesis.

<img width="674" alt="screen shot 2015-11-15 at 4 48 15 pm" src="https://cloud.githubusercontent.com/assets/1284597/11169444/bbff57bc-8bb8-11e5-83d8-97e4f3a5682d.png">
<img width="433" alt="screen shot 2015-11-15 at 4 48 34 pm" src="https://cloud.githubusercontent.com/assets/1284597/11169445/bc013f3c-8bb8-11e5-91bd-ffd025d9b1b1.png">
<img width="277" alt="screen shot 2015-11-15 at 4 49 32 pm" src="https://cloud.githubusercontent.com/assets/1284597/11169450/daa509b4-8bb8-11e5-9daa-741060514fed.png">

**Comment by basarat** [comment]
Yes. This is a bug in our grammar. Any effort towards a fix should start here : https://github.com/TypeStrong/atom-typescript/issues/675 :rose:

**Comment by basarat** [comment]
Should work Released https://github.com/TypeStrong/atom-typescript/releases/tag/v8.0.0 :rose: If not raise issue at https://github.com/Microsoft/TypeScript-TmLanguage/issues :rose:
