### ISSUE TITLE
Keyboard shortcut for Type information at cursor

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#726]
Currently only shown on Mouse Hover : https://github.com/TypeStrong/atom-typescript#type-information-on-hover

Requested by @JaKXz here https://github.com/TypeStrong/atom-typescript/issues/716#issuecomment-156810461

**Comment by daniel-trinh** [comment]
+1

**Comment by michalczukm** [comment]
Hi, I would like to grab this issue. Should I get somehow assigned on issue? contributing.md doesn't cover that :smile: 

PS Any concrete key-binding suggested?
R# / JetBrains IDEs have ctrl+q for similar functionality. I would suggest to use that.

**Comment by nycdotnet** [comment]
Go ahead and implement. If ctrl+q isn't used already with Atom then it sounds good.  :)

**Comment by michalczukm** [comment]
ok, thanks for answer :)

**Comment by dylanscott** [comment]
Hope I'm not stepping on anyones toes, but I was sorely missing this feature after switching to Atom recently so I took a crack at it with #970

**Comment by basarat** [comment]
Released with `8.11.0` (minor update). Thanks @dylanscott :rose:
