### ISSUE TITLE
Ts Worker Failing

### ISSUE THREAD

**Issue by tomitrescak** [TypeStrong/atom-typescript#728]
Since not so long the TS worker fails after several seconds after opening Atom and never starts again ;( This is message in the log:

```
/Users/tomi/.atom/packages/typescript-modules-helper/lib/typescript-import.coffee:44 bound event

/Users/tomi/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:193 ts worker restarting. Don't know why it stopped with code: null
```

**Comment by tomitrescak** [comment]
I noticed another error related to this:

```

/Users/tomi/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:180 CHILD ERR STDERR: Atom Helper(63023,0x7fff74876000) malloc: *** error for object 0x7f923840ce20: pointer being freed was not allocated
```

**Comment by basarat** [comment]
> which every 3-6 minutes.

ouch. Does trying an older version (try a month old version) fix it ... if not then it might be a new atom version bug 

> Did anyone else report this behaviour?

No. And its running fine all day on my windows machine

**Comment by tomitrescak** [comment]
Rolled back to Atom 1.1.0 and so far all looks good. Looks like Atom issue ;(

**Comment by JoshEngebretson** [comment]
I am having this issue on 1.2.1, can't rollback to 1.1 currently

**Comment by basarat** [comment]
@JoshEngebretson  are you on a Mac ?

**Comment by basarat** [comment]
@JoshEngebretson is `pointer being freed was not allocated` in your console too?

**Comment by tomitrescak** [comment]
@basarat I'm on Mac as well.

**Comment by JoshEngebretson** [comment]
Here is what I am seeing:

<img width="428" alt="screen shot 2015-11-17 at 2 59 36 pm" src="https://cloud.githubusercontent.com/assets/376203/11227621/e7faab62-8d3b-11e5-89ba-c59d4e732bc0.png">

**Comment by ksachdeva** [comment]
facing the same issue

**Comment by basarat** [comment]
I've created an issue : https://github.com/atom/atom/issues/9663 :rose:

**Comment by tomitrescak** [comment]
I can confirm that with Atom 1.3.0 beta all is OK.

**Comment by jon49** [comment]
I'm getting this issue on XUbuntu. I'm using 1.1.0. I'll see if I can figure out how to upgrade to 1.3.0.

**Comment by jon49** [comment]
Don't seem to be having any issues with 1.3.0 beta

**Comment by adidahiya** [comment]
Atom 1.30 beta fixed this for me as well

**Comment by tomitrescak** [comment]
I think we can close this one as all seems to be well with Atom 1.3.+
