### ISSUE TITLE
Pending requests... I know

### ISSUE THREAD

**Issue by xealot** [TypeStrong/atom-typescript#730]
I know there are other tickets with this name but I don't think any of them apply. I'm pretty much a complete newb with Atom and the only reason I use it is for this plugin. I have these pending requests that keep stacking up. Here is a shot of the console.

![image](https://cloud.githubusercontent.com/assets/189873/11227260/fa474b92-8d52-11e5-9068-1638100467a5.png)

And the pending requests...

![image](https://cloud.githubusercontent.com/assets/189873/11227265/030caf88-8d53-11e5-816f-678f11fbe8b6.png)

I am updated to newest Atom-Typescript and Atom and using TS 1.6.x

**Comment by basarat** [comment]
> know there are other tickets with this name but I don't think any of them apply.

You are right. This is because of a recent atom update. Original report : https://github.com/TypeStrong/atom-typescript/issues/728 

Also reported to atom team : https://github.com/atom/atom/issues/9663 :rose:

**Comment by JoshEngebretson** [comment]
I really hope this gets addressed soon, destroys the usability of this wunderbar package on OSX

**Comment by xealot** [comment]
Yeah, this is no bueno... After updating to Atom 1.2.1 it's unusable (it was only mostly unusable before). Is there any sort of cheap workaround @basarat?

**Comment by basarat** [comment]
> Is there any sort of cheap workaround

Not that I know of. Would be great if there was a way to disable atom autoupdate ... please let me know if you find a way :rose: I mostly just end up throwing my hands and using notepad (+ grunt)


![](https://media.giphy.com/media/tKf8cu9qfzhN6/giphy.gif)

**Comment by tomjon** [comment]
Damn. I was really enjoying using Atom + atom-typescript but it seems this is still happening with Atom 1.8.0 and atom-typescript 10.0.0. If I wait long enough the requests subside but it's definitely keeping my MacBook's fan busy.
