### ISSUE TITLE
Open ts file hang/crash on windows

### ISSUE THREAD

**Issue by unional** [TypeStrong/atom-typescript#731]
This will be a hard one. It was working fine in previous build. Currently when I open certain ts file, atom hang and not responding until I force close it.

There is no error on console and no spinning on cpu.

The file is shown before color coding and then just freeze there.

I have tsconfig.

**Comment by basarat** [comment]
Clear your atom storage folder. e.g. for me `C:\Users\basaratsyed\.atom\storage`. This is a know atom bug ... I don't have an issue, but our team feels it consistently. 

Let me know if that fixes it please :rose:

**Comment by unional** [comment]
Nope. Claring the storage folder does not fix it.

**Comment by basarat** [comment]
@unional moving this ts file on its own + tsconfig > to a different Dir .... does that fix it?

**Comment by unional** [comment]
Nope. Doesn't fix it. 

Move the file to ./x folder, move tsconfig to that folder, remove all files (`files:[]`). Still hang.

**Comment by basarat** [comment]
Sweet, Now can I have just this file to try and repro :rose:

**Comment by basarat** [comment]
https://gist.github.com/ :rose:

**Comment by unional** [comment]
Oops. Take it back. It works now.

**Comment by unional** [comment]
Hang on. Trying things out. Stop working again when I move tsconfig back to root.

**Comment by basarat** [comment]
https://gitter.im/TypeStrong/atom-typescript :rose:

**Comment by unional** [comment]
ok. :)

**Comment by unional** [comment]
seems like the same issue:
https://github.com/TypeStrong/atom-typescript/issues/207

**Comment by c0gnize** [comment]
Same issue observed on Windows 10, atom 1.2.4.
Editor fully hangs after opening any big ts file (regardless of tsconfig), for example [react.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a809e347c94f642cdffae40c42b1ea45f84ad9ad/react/react.d.ts).
But it happens only when i use atom-typescript and editorconfig packages together.
May be this is a bug of atom, i don't know.

**Comment by unional** [comment]
I speculate this is the issue:

`atom-typescript` has pending actions leak when the content is changed before the actions are performed.

1. `editorconfig` will make changes, to any files that opens, and fire multiple change events.
2. When the file is opened, `atom-typescript` will queue pending actions, as well as for each change.
3. I notice some pending actions are stucked as I work on the project.
4. When opening large file, or file that would invoke multiple changes, the pending actions quickly consume memory that leads to out of memory that I saw.
5. Potentially if `atom-typescript` make any changes to the file and fire change event, and the change is not compatible to `editorconfig` change, deadlock occurs.

Related to https://github.com/TypeStrong/atom-typescript/issues/748

**Comment by basarat** [comment]
Thanks for narrowing it down. @blakeembrey already pointed out to me that the fact that we don't batch edits to the backend can lead to huge number of pending requests e.g. when formatting like your sample and then the backend crashes for some reason. 

Batching is something that needs to be implemented in our workerLib ... keeping it open till I have an idea of how to implement it best :rose:

**Comment by unional** [comment]
Batching would be nice, but I think the problem stem from not handling case that the edit is no longer relevant:
![image](https://cloud.githubusercontent.com/assets/3254987/11519148/a0d38e2c-984c-11e5-9cd7-21544bfb2563.png)

This is one instance that the request count stuck there and never goes down.

**Comment by glen-84** [comment]
Same. I can't open `node.d.ts` without Atom freezing. :disappointed:

**Comment by unional** [comment]
One way to easily hang the system:
* Open this file (create a new file locally or get that file): https://github.com/aurelia/event-aggregator/blob/master/test/event-aggregator.spec.js
* [ctrl-D] to select all `ea`
* Try to rename it

Typing each character add about 110 pending requests, when there is more then 240 (i.e. typing more then 3 characters in a short time) hangs the system.

**Comment by unional** [comment]
@basarat , I think this really need to be address first, before other features. Do you think the batching would be the solution? I can see what can I do to help. Right now I can't use the plugin for some of my projects as `atom-typescript` consistently freeze the system.

![image](https://cloud.githubusercontent.com/assets/3254987/12150643/d26276e0-b45f-11e5-94c8-8c9b5d3da739.png)

It seems like it is not consuming much memory, just spinning the cpu (it's 8 core).

**Comment by unional** [comment]
As for the batching, I can see it would help, as each typing adds an `editText` request. However also it takes about 2-3 seconds (in the project I'm working on) to process each request.

**Comment by glen-84** [comment]
Since this only happens when using atom-editorconfig, it would probably be resolved if atom-editorconfig didn't touch files on open (which it's not supposed to do).

See [here](https://github.com/editorconfig/editorconfig/issues/248#issuecomment-167981607). Feel free to submit that issue, as I am unable to.

**Comment by unional** [comment]
Nope. It happens without `atom-editorconfig`.  I have it disabled for a long time so I can use `atom-typescript`

**Comment by glen-84** [comment]
Interesting. For me, when I disabled it and restarted Atom, the issue went away.

**Comment by unional** [comment]
That's a different issue with `atom-editorconfig` and `atom-typescript` race against each other.  This one is performance related.

**Comment by glen-84** [comment]
My bad, I was getting mixed up with #748.

**Comment by unional** [comment]
No problem. :) I was speculating this was related to #748 also, but it turns out to be not the case.

**Comment by unional** [comment]
@basarat , caught an error:
In https://github.com/TypeStrong/atom-typescript/blob/master/lib/worker/lib/workerLib.ts#L186, and 196:

`_this.getProcess().send(...)` throws as `_this.getProcess()` returns null. It seems to be from a parent with no child.

Because it throws in 196 too, the original exception `cannot read property 'send' f null` is eaten.

**Comment by basarat** [comment]
@unional if there is an error *sending to no child*, we don't care. This is because as soon as a child comes online :

* it will query the parent for any unsaved editors : https://github.com/TypeStrong/atom-typescript/blob/cdc8d9865a0abc8e6ca6bfb7d02e08dec675286e/lib/main/lang/projectCache.ts#L92-L109 * and then start fielding new queries

I may be wrong :rose:

**Comment by unional** [comment]
In the incident I saw, the pending requests remain in queue and never get handled.
I think the **thread** is lost this `processResponse` is never get called so `delete this.currentListeners[parsed.messaged][parsed.id]` will not get called and they remains in queue forever.

I put a breakpoint in `processResponse` and it never get hit.

**Comment by basarat** [comment]
> , the pending requests remain in queue and never get handled.

Indeed. That is an issue. Feel free to create one

**Comment by unional** [comment]
@basarat , I add a some code trying to batch editText. Please provide some input. :)
https://github.com/unional/atom-typescript/commit/fd477cad9f1dc19eb14c5eb22e3fbfad8807c02d

**Comment by MTyson** [comment]
Possibly related:

https://github.com/TypeStrong/atom-typescript/issues/971

**Comment by MTyson** [comment]
Sad to say, uninstalling atom-typescript as I type, due to this issue.
