### ISSUE TITLE
filesGlob not working in 7.11.0

### ISSUE THREAD

**Issue by patsissons** [TypeStrong/atom-typescript#732]
I thought it might just be my complex project that I was working in, but I created an ultra basic project and auto-created a `tsconfig.json` file to reproduce. no files section is created unfortunately.

My sample environment:
* `/src/test.ts` is the only file (just contains `'use strict';`)
* use the *Typescript: Create Tsconfig.json Project File* command
    * `/src/tsconfig.json` created

`filesGlob` section looks like this:
```json
{
    "filesGlob": [
        "**/*.ts",
        "**/*.tsx",
        "!node_modules/**"
    ]
}
```

tried saving the `test.ts`, running sync on `test.ts`, saving `tsconfig.json`, running sync on `tsconfig.json`. The typescript panel shows that `test.ts` belongs to `~src\tsconfig.json` and no issues are reported with either file.

This is happening on Win10 with latest atom (`1.2.1`)

any ideas on what might be wrong? I don't see anything in the dev console...

**Comment by unional** [comment]
Same here.

**Comment by patsissons** [comment]
I figured it out. It has to do with the new `rewriteTsconfig` option (see [the docs](https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#atom) for more info).

The docs suggest that it defaults to true, but it seems to be false by default right now.

**Comment by basarat** [comment]
@patsissons thanks for reporting. Fixed : https://github.com/TypeStrong/atom-typescript/releases/tag/v7.11.1 :rose:

**Comment by patsissons** [comment]
great turn-around!

**Comment by basarat** [comment]
![](http://38.media.tumblr.com/e8127e3c0d61dcd563d196888ac064ff/tumblr_inline_mo1w4z8q361qz4rgp.gif)  https://github.com/TypeStrong/atom-typescript/pull/715

Although I am still thankful to the original author for getting it done (which I was failing to do) :rose:
