### ISSUE TITLE
Should lintOnFly be false?

### ISSUE THREAD

**Issue by Arcanemagus** [TypeStrong/atom-typescript#734]
I was looking over your linter configuration and it seems you specify [`lintOnFly` as true](https://github.com/TypeStrong/atom-typescript/blob/master/lib/linter.ts#L25), but as far as I can tell you are only linting files on disk which means that should be false.

Am I missing a part where you pass the current buffer contents to the linter somehow, or was this just an oversight?

**Comment by basarat** [comment]
> Am I missing a part where you pass the current buffer contents to the linter somehow

We pass it to our background language service worker on the fly ... and in the linter we query the background language service worker :rose:

**Comment by Arcanemagus** [comment]
Cool, just wanted to make sure since all I saw in the quick look was it passing the filePath and requiring the file be saved to disk before allowing a lint :wink:. Thanks for checking on this!

**Comment by basarat** [comment]
> Thanks for checking on this!

thank *you* for your interest :rose:

![](https://media.giphy.com/media/qaoDDDoKwD1Ty/giphy.gif)
