### ISSUE TITLE
JS Status is intially misleading

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#737]
Its starts out with `JS Outdated` 

![image](https://cloud.githubusercontent.com/assets/874898/11326772/79b8ba42-91c6-11e5-85e0-03550a2b0df5.png)

It should really be something like `Inderterminite` till we do an actual validation. 

## Current

* Its `oudated` by default < This needs to change
* Its `current` if user saves file and `compileOnSave` was true (or user does a build)
* Its `outdated` if the user edits the file after the last time we did a compile for a file

refs https://github.com/TypeStrong/atom-typescript/issues/736

**Comment by pelted** [comment]
As someone new to atom-typescript and experiencing the recent ongoing issue with the latest Atom version and the stalled worker I really thought this meant I had something wrong or a node package out of date. The JS Outdated was maddening for my first couple of hours trying to find my way around.

**Comment by laurelnaiad** [comment]
I"m starting to believe that my problem in #736 was due to babel compile not being applied before doing the diff on the file.

**Comment by basarat** [comment]
> not being applied before doing the diff on the file.

That is definitely true. Another :bug: !

**Comment by laurelnaiad** [comment]
PR Coming... again, not happy with my patch, but I'm on a roll... almost to the point where I can use atom-typescript on a project. Feel free to rearrange my patches, I know they're sloppy, but I really have to get to functional on a project that isn't named 'atom-typescript'. :)

**Comment by basarat** [comment]
> I know they're sloppy, but I really have to get to functional on a project that isn't named 'atom-typescript'.

they are quite nice IMHO :rose:

**Comment by basarat** [comment]
This issue is still open. The portion done was just a bug that was detected as a part of the analysis for this https://github.com/TypeStrong/atom-typescript/issues/737#issuecomment-159767647

**Comment by laurelnaiad** [comment]
Sorry for the linked issue noise -- I was rebasing a branch that had a reference to this issue in its commit message. I'll make sure this doesn't keep happening.

**Comment by tommybananas** [comment]
Has this been fixed yet? I'm still seeing this warning

**Comment by dustinchang** [comment]
Same as @tommybananas. Could this be that it's still a bug because I'm using Typescript 2?

**Comment by BDHiv** [comment]
![image](https://cloud.githubusercontent.com/assets/6011475/19460464/5d4de9f0-94b2-11e6-9954-30dd12862f73.png)
 
i recently install typescript and update atom to  1.22.2, same problem

**Comment by nyabwana** [comment]
I also have the same message showing. I have just installed atom and atom-typescript today. I was trying out the editor because it looks funky

**Comment by shapir** [comment]
Yep; Atom still says "JS Outdated" for each .ts and .spec.ts file (used within Angular 2 env.)

**Comment by Julix91** [comment]
Just had this, super glad that this thread exists, otherwise I too would have assumed I did something wrong. :)

**Comment by josemera** [comment]
same

**Comment by mrjpsilver** [comment]
Just installed `atom` and `atom-typescript` fresh, and I'm seeing this issue.

**Comment by alexeypetrushin** [comment]
Same issue

**Comment by mipesom** [comment]
Me too

**Comment by tvanesse** [comment]
Same here.

**Comment by 4esnog** [comment]
Same :heavy_plus_sign:

**Comment by wallaceicy06** [comment]
Same

**Comment by Shijir** [comment]
Not even fixed until today.

**Comment by davideicardi** [comment]
Have you try with this solution:
https://github.com/TypeStrong/atom-typescript/issues/1013#issuecomment-268327889

Can be the same issue? Post your tsconfig to see the differences...

**Comment by Shijir** [comment]
Are you suggesting `"declaration": true` as a solution? That's for compiling typescript with declaration files though. This one is IDE related issue.

**Comment by davideicardi** [comment]
I just suggesting tha probably these two bugs are related, I suspect something related to compilation... With my solution now I don't see anymore this issue in any kind of project, with or without declarations...

I just try to help you ☺

**Comment by Shijir** [comment]
No, thanks for trying to help. For me, `"compileOnSave": false` is working. 😕
