### ISSUE TITLE
cannot find module 'angular2/angular2'

### ISSUE THREAD

**Issue by Geraldf** [TypeStrong/atom-typescript#740]
Hi I wonder, what I am doing wrong, that atom-typescript always shows "cannot find module
 'angular2/angular2'" 

I have the following code at line 1 in my .ts file 
```
import {Component, bootstrap} from 'angular2/angular2';
```
at this line it shows the error message. 

my tsconfig.json looks contains the following entry:
```
  "files": [
        "./app/main.ts",
        "./typings/angular2/angular2.d.ts",
        "./typings/tsd.d.ts"
    ],
```

I was under the impression, that the atom-typescript looks at the tsconfig.json file to find the d.ts files.

**Comment by basarat** [comment]
> I was under the impression, that the atom-typescript looks at the tsconfig.json file to find the d.ts files.

It will. Does the `angular2.d.ts` contain something like `declare module "angular2/angular2"` If not its a problem with the defintion.

**Comment by basarat** [comment]
Feel free to continue discussion if you feel its an issue with this plugin :rose:
