### ISSUE TITLE
Can't start atom with editorconfig package

### ISSUE THREAD

**Issue by unional** [TypeStrong/atom-typescript#748]
I'm using `atom-typescript`, `editorconfig` and `project-manager`. 

I have a project that have several files opened automatically (from last recent close).  Some of these files are (or "will be", see below) edited automatically by `editorconfig`.

In this situation, `atom` hangs.

If I turned off `atom-typescript`, atom is opened without problem and I can see those files are being edited (hence "will be", as atom was crashing otherwise).

Seems like a race issue?

**Comment by unional** [comment]
Seems to be not an issue with the `storage` as some other projects are opened without problem.?

**Comment by basarat** [comment]
> If I turned off atom-typescript, atom is opened without problem and I can see those files are being edited (hence "will be", as atom was crashing otherwise).

Turn off rewrite in your tsconfig. Atom and the other package might be having a fight over whose version of the tsconfig.json file is more pretty :lipstick:  :) https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#i-keep-getting-changes-to-tsconfigjson

**Comment by unional** [comment]
I'll test with excluding `tsconfig.json` form editorconfig. Will post progress

**Comment by unional** [comment]
It still crash. Turns out it is not the `tsconfig.json`. The file opened is a typescript file, and `editorconfig` will try to format it, and `atom-typescript` choke on it?  Seems to be similar to the previous bug that I filed?

**Comment by unional** [comment]
One more update: It doesn't really matter if it is typescript file or not, in one instance I have a `.p4ignore` opened and it still crashes. Could still be another file in the opened files that cause the crash. Will continue to monitor

**Comment by glen-84** [comment]
I have the same problem all the time. I also have the editorconfig plug-in installed.

To fix it I have to remove `C:\Users\{user}\.atom\storage\editor-1f7cc550e0164939d8f0c519486fe3e9166db101`, which is really annoying.
