### ISSUE TITLE
Automatic installation github.com/atom-community/linter

### ISSUE THREAD

**Issue by nexcode** [TypeStrong/atom-typescript#757]
After installation I deleted *github.com/atom-community/linter* package
But, after restarting the editor it has again install!
Maybe you should **make a checkbox in the settings**?

**Comment by basarat** [comment]
> Maybe you should make a checkbox in the settings?

We feel that linter is critical to a good experience :rose: You need to use both or none, sorry about that, you have the right to disagree and I definitely understand your point of view.
