### ISSUE TITLE
ts worker restarting. Don't know why it stopped with code: null

### ISSUE THREAD

**Issue by david-byng** [TypeStrong/atom-typescript#760]
After editing typescript files for a while, the message
```
ts worker restarting. Don't know why it stopped with code: null
/Users/USERNAME/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:193
```
is output to the console. Autocomplete then stops working, and items begin stacking up in pending requests. Eventually error messages start being thrown:
```
PARENT ERR: no child when you tried to send : getQuickFixes
Uncaught (in promise) Error: No worker active to recieve message: getQuickFixes
    at Parent.RequesterResponder.sendToIpcHeart (/Users/USERNAME/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:27:39)
    at Object.getQuickFixes (/Users/USERNAME/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:105:47)
    at /Users/USERNAME/.atom/packages/atom-typescript/dist/main/atom/editorSetup.js:19:16
    at later (/Users/USERNAME/.atom/packages/atom-typescript/dist/main/lang/utils.js:173:31)
```

This usually happens when I stop typing while the code is invalid and wait for an autocomplete suggestion (eg: `let foo: Foo = bar; if (baz[foo.^]` - where `^` is the caret, and the line does not continue). Autocompletion does not come back even when the code is corrected.

The following may be related:
```
CHILD ERR STDERR: Atom Helper(18200,0x7fff776e5000) malloc: *** error for object 0x7feabc90ac50: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
/Users/USERNAME/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:180
```

**Comment by basarat** [comment]
> malloc: *** error for object 0x7feabc90ac50: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug


Already reported https://github.com/TypeStrong/atom-typescript/issues/728 . Also reported to the Atom team : https://github.com/atom/atom/issues/9663 :rose:
