### ISSUE TITLE
Add "allowSyntheticDefaultImports" compiler option

### ISSUE THREAD

**Issue by glen-84** [TypeStrong/atom-typescript#762]
See https://github.com/Microsoft/TypeScript/pull/5577

`ntypescript` will also need to be updated.

**Comment by basarat** [comment]
A recent PR that adds options to tsconfig.json : https://github.com/TypeStrong/atom-typescript/pull/725

General guidance is available here : https://github.com/TypeStrong/atom-typescript/blob/cb7f23e26d03e28bd21e65ff5be92cf9581b2a4c/lib/main/tsconfig/tsconfig.ts#L12-L16 :rose:
