### ISSUE TITLE
TSX navigate to definition

### ISSUE THREAD

**Issue by tomitrescak** [TypeStrong/atom-typescript#766]
This may be a duplicate, but I could not find it between issues.
It is a feature request, to have the possibility to use "CMD+R" just like in ".ts" files to navigate to definition / symbol.

Thanks! Keep up the great work!

**Comment by basarat** [comment]
released https://github.com/TypeStrong/atom-typescript/releases/tag/v7.14.1 :rose:

**Comment by tomitrescak** [comment]
Awesome! Works! :tulip:

**Comment by tomitrescak** [comment]
Hi, this is not working again ;(

**Comment by tomitrescak** [comment]
Actually .. sorry .. this is working, but pressing "CMD + SHIFT + R" in tsx files gets nothing. Should I open a new issue?

**Comment by basarat** [comment]
If you feel like there is a bug go for it 🌹
