### ISSUE TITLE
Hover type information doesn't seem to be working

### ISSUE THREAD

**Issue by dsifford** [TypeStrong/atom-typescript#768]
Hello,

I recently installed this plugin and it's fantastic. The only issue I am having is I can not seem to get the hover type info to work at all.

I disabled all my other plugins and tried again and it still doesn't work. 

Any suggestions? Anything I can do/provide for you (debug logs/etc). Happy to help figure this out.

Thanks

**Comment by basarat** [comment]
> only issue I am having is I can not seem to get the hover type info to work at all.

If you use multiple panes it might not work. Have a single pane and then reload atom :-/ Its hacky *not supported officially by atom APIs* code `¯\_(ツ)_/¯`

**Comment by dsifford** [comment]
@basarat Thanks for the reply. 

While multiple panes does cause some issues, it is not what is causing my specific issue. It still happens even without multiple panes. 

I'm running atom beta (which, I suppose could be the source of my issues) and also Windows 10 Pro Beta (fast build)

Let me know if theres any logs I can provide for you if you'd like.

**Comment by basarat** [comment]
> I'm running atom beta (which, I suppose could be the source of my issues)

Probably. I personally don't track beta so marking as up for grabs for now :rose:

**Comment by kyleholzinger** [comment]
Not sure if you guys are still working on this, but it's still a little broken:

![screencast 2016-10-19 11-56-54](https://cloud.githubusercontent.com/assets/2652762/19526799/99df7db0-95f3-11e6-9736-8f7b60760781.gif)

Text overflows outside of the tooltip

**Comment by dsifford** [comment]
@kyleholzinger 

You can fix that issue pretty simply in your own stylesheet. (it's likely a conflict with your UI theme).

To fix it, do this:

1. Press <kbd>cmd</kbd> + <kbd>shift</kbd> + <kbd>i</kbd> to bring up dev tools.
2. Switch over to the `Sources` panel.
3. Hover something so that a tooltip shows up.
4. While hovering, hit <kbd>F8</kbd> to pause script execution.
5. Click the element inspector and hover the tooltip to find the css selector and look for any stylesheet conflicts.

To save you time, here's the CSS selectors:

![image](https://cloud.githubusercontent.com/assets/5240018/19529011/3f846886-95fc-11e6-9be1-5595383f1708.png)

**Comment by dsifford** [comment]
Also this: https://github.com/TypeStrong/atom-typescript/pull/1067

**Comment by kyleholzinger** [comment]
@dsifford unfortunately I can't click f8, ironically because atom-typescript uses it for `go-to-next`. Any way to un-bind this?

**Comment by kyleholzinger** [comment]
@dsifford So I added `'f8': 'unset!'` to my keybindings and now it does nothing. Do you know the command for stopping execution of everything?

**Comment by kyleholzinger** [comment]
Nevermind, just copied and pasted that stylesheet into my custom stylesheets. All good, though it'd be awesome if that got merged in so I could delete it
