### ISSUE TITLE
JavaScript Autocomplete?

### ISSUE THREAD

**Issue by kepler0** [TypeStrong/atom-typescript#769]
Could this package provide Autocomplete Suggestions for JavaScript files, much like Visual Studio Code seems to be doing?

**Comment by basarat** [comment]
Duplicate of https://github.com/TypeStrong/atom-typescript/issues/315

Note: Its difficult to add complex features like this when this is not my main hobby project anymore, so probably will never be done.

**Comment by kepler0** [comment]
Thanks for answering! I'd love to contribute if you're open to more contributors. I'm just starting to get into TypeScript, it's pretty neat.

**Comment by basarat** [comment]
> I'd love to contribute if you're open to more contributors.

Always!:rose: But not this feature. I feel that maintaining this is quickly going to get out of hand. Till TypeScript official supports `salsa` mode https://github.com/Microsoft/TypeScript/issues?q=is%3Aopen+is%3Aissue+label%3ASalsa
