### ISSUE TITLE
TSX: Incorrect Tag Matching

### ISSUE THREAD

**Issue by unional** [TypeStrong/atom-typescript#771]
![image](https://cloud.githubusercontent.com/assets/3254987/11612444/7c2da138-9bae-11e5-94d4-a0439284c1dc.png)

See the end tag `A` is matched with the self-closing `A` inside.

**Comment by basarat** [comment]
We don't do anything special here. Matching done by atom. Might be us not tokenizing *self closing* tags correctly.

**Comment by unional** [comment]
File on atom/atom?

**Comment by basarat** [comment]
> File on atom/atom?

good idea :rose:

**Comment by unional** [comment]
Confirmed the same issue with JSX using package `language-javascript-jsx`.

**Comment by basarat** [comment]
Just checked HTML grammar. It works fine : 

![image](https://cloud.githubusercontent.com/assets/874898/11645509/2b15fa64-9da9-11e5-8432-55e7462af49f.png)


Guess we / jsx doesn't do `end` on self closing. That's what they will probably point us to :rose:

**Comment by unional** [comment]
So likely something need to change on this rule?

````
	"jsx-tag-open":
		name: "tag.open.tsx"
		begin: '''
			(?x)
			  (<)
			  ([_$a-zA-Z][-$\\w.]*(?<!\\.|-))
			  (?=\\s+(?!\\?)|/?>)
		'''
		end: "(/?>)"
		beginCaptures:
			"1":
				name: "punctuation.definition.tag.begin.tsx"
			"2":
				name: "entity.name.tag.tsx"
		endCaptures:
			"1":
				name: "punctuation.definition.tag.end.tsx"
		patterns: [
			{
				include: "#comment"
			}
			{
				include: "#jsx-tag-attributes"
			}
			{
				include: "#jsx-tag-attributes-illegal"
			}
		]
````

Sorry, not expert in regex. :P

**Comment by unional** [comment]
Probably this is the issue:
![image](https://cloud.githubusercontent.com/assets/3254987/11645678/7935d3e8-9d0b-11e5-861a-d1465761e53c.png)

There is an extra `begin jsx` inside the end tag

And for tsx:
![image](https://cloud.githubusercontent.com/assets/3254987/11645730/cf2eabf8-9d0b-11e5-84ec-901936208388.png)
There is an extra `open tsx` at the beginning.

**Comment by unional** [comment]
Seems like it is indeed `atom`:
https://github.com/atom/bracket-matcher/issues/115
