### ISSUE TITLE
Option to disable the 'quick fix' lightbulb

### ISSUE THREAD

**Issue by doliver3** [TypeStrong/atom-typescript#772]
Could you provide an option disable the 'quick fix' light bulb?

It is very distracting appearing randomly next to most lines. 

It is extremely rare it has any commands of use. In addition, it should not require looking up the documentation on atom-typescript to figure out what it does. If it is visible, clicking on it should display the dropdown of quick fix options.

**Comment by basarat** [comment]
> Could you provide an option disable the 'quick fix' light bulb?

I feel like disabling the quick fix infrastructure to make this package simpler to maintain :-/

**Comment by glen-84** [comment]
I agree. I don't understand why it shows up with no suggestions.

**Comment by basarat** [comment]
I've only disabled the lightbulb for now :rose:

**Comment by basarat** [comment]
released https://github.com/TypeStrong/atom-typescript/releases/tag/v7.14.2 :rose:

**Comment by mjohnsonengr** [comment]
:+1: Thanks :grin:

**Comment by doliver3** [comment]
I just tried out the updated version, and the lightbulb is disabled. 
Thanks for the quick turnaround handling this!
