### ISSUE TITLE
Multi type function property: Cannot invoke an expression whose type lack a call signature

### ISSUE THREAD

**Issue by unional** [TypeStrong/atom-typescript#773]
Is this error from `atom-typescript`?

````
interface Route {
  match: ((context: RouteContext) => any) | string | RegExp
}
````

![image](https://cloud.githubusercontent.com/assets/3254987/11703558/0a9c6312-9e95-11e5-8551-6761df707460.png)

https://github.com/palantir/tslint/issues/862

**Comment by blakeembrey** [comment]
Yes, but this is a TypeScript error. Since your signature says it might be a string or a RegExp, `match` is not always a function. Try wrapping it in a function check, and make sure that interface is correct.

**Comment by unional** [comment]
I do want to let `match` be `string | RegExp | ((context: RouteContext) => any)`
I tried to wrap it in a function check, but the error persist. What function check do you recommend or define the interface differently?

For function check, I'm doing:
````
if (typeof route.match === 'function' ) // won't work on IE8
or
if (_.isFunction(route.match)) // using lodash
````

**Comment by blakeembrey** [comment]
If the interface is correct, then don't change that. Did you write the Underscore/Lodash definition file? You could implement it using type guards if you're using TypeScript 1.6+. 

Otherwise, you can always use a type assertion to make it work:

```
if (_.isFunction(route.match)) {
  (route.match as Function)(context)
}
```

**Comment by unional** [comment]
Seems like `(route.match as Function)` doesn't work. Need to be more specific `(route.match as ((context: RouteContext) => any))`.
Sounds like some covariance improvements needed on TypeScript?

**Comment by blakeembrey** [comment]
It's probably correct, that was just a random throw out but the proper type would be better. The best solution here would be to fix the type guard in the lodash definition you're using.

I'll close this now, but feel free to continue the discussion.

**Comment by unional** [comment]
Thanks!
