### ISSUE TITLE
"let" keyword incorrectly inferred from name "bullet"

### ISSUE THREAD

**Issue by mjohnsonengr** [TypeStrong/atom-typescript#775]
I'll reference #675 so you don't have to, but I can't add the category:grammar tag.

This specifically seems to happen with the word "bullet" from which "let" is incorrectly grabbed which I assume is the reason certain amounts of syntax highlighting break after this in the document.

![image](https://cloud.githubusercontent.com/assets/7274059/11727623/13303cbc-9f42-11e5-8cc3-254daeaa492a.png)

**Comment by basarat** [comment]
Should work with release https://github.com/TypeStrong/atom-typescript/releases/tag/v8.0.0 :rose: If not raise issue at https://github.com/Microsoft/TypeScript-TmLanguage/issues and link me :rose:
