### ISSUE TITLE
Tsx errors on optional properties 

### ISSUE THREAD

**Issue by debdattabasu** [TypeStrong/atom-typescript#778]
see https://github.com/Microsoft/TypeScript/issues/6029. 

The error message says that 'key' and 'props' property must be given, but they are defined as optional on IntrinsicAttributes and IntrinsicClassicAttributes. This is a problem with latest typescript trunk version. version 1.7.3 compiles without issues. I am facing this issue in latest atom-typescript.

**Comment by j6lim** [comment]
FYI: downgrading atom-typescript to 7.9.0 worked for me

**Comment by j6lim** [comment]
It seems that trunk versions of typescript break frequently. Please consider using the latest stable version for people using atom-typescript plugin in their mission critical tasks.

**Comment by basarat** [comment]
> Please consider using the latest stable version for people using atom-typescript plugin in their mission critical tasks.

I can understand the motivation. But not tracking the latest results in *more bugs* when *we do go to latest* :rose:  @debdattabasu thanks for reporting :rose:

**Comment by priyatham-aps** [comment]
@basarat 
I have started facing this issue a few days back when I updated my atom-typescript package. We are not facing this issue in our project build as we are using an earlier typescript version.

I am guessing atom-typescript package uses its own bundled typescript version and not the one I have installed within my project or even globally, which essentially breaks our usage of atom and this package. Is there a way to set which typescript version atom-typescript uses other than downgrading the package itself?

Thanks.

**Comment by basarat** [comment]
> Is there a way to set which typescript version atom-typescript uses other than downgrading the package itself

@priyatham-aps use the old version of the language service : https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#which-version-of-typescript-does-atom-typescript-use :rose:

**Comment by myitcv** [comment]
@basarat [tsuquyomi](https://github.com/Quramy/tsuquyomi) (the Vim equivalent) uses a [locally installed TypeScript version by default](https://github.com/Quramy/tsuquyomi#use-typescript-installed-locally). This seems a sensible default - is it possible to configure `atom-typescript` in this way?

**Comment by basarat** [comment]
> This seems a sensible default - is it possible to configure atom-typescript in this way

There is already a request to have this package support typescript version specified using tsconfig.json. If there is a consensus on that we might go that way.

**Comment by myitcv** [comment]
@basarat why would the TypeScript version be specified in `tsconfig.json` given it's already specified in `package.json` (or equivalent)? 

Is there any reason why `atom-typescript` wouldn't adopt the same logic as `tsuquyomi`?

**Comment by basarat** [comment]
@myitcv I take my words back. I prefer `package.json` lookup :rose:

**Comment by myitcv** [comment]
@basarat  :+1: 

I think the algorithm need only be as simple as iteratively searching for  `node_modules/typescript/lib/typescriptServices.js` in the directory containing the open file, all the way up to `/`. No need to parse `package.json`
