### ISSUE TITLE
Syntax Highlighting: for gurad functions with generic type

### ISSUE THREAD

**Issue by lazutkin** [TypeStrong/atom-typescript#779]
A snippet below

<img width="526" alt="messages_ts_-__users_dimka_projects_api_medesk_md_-_atom" src="https://cloud.githubusercontent.com/assets/1035026/11768793/e58d3fa4-a1e8-11e5-9480-abf9f70aa627.png">

**Comment by basarat** [comment]
Cheers :beer: https://github.com/TypeStrong/atom-typescript/issues/675 needs a hero :rose:

**Comment by basarat** [comment]
Should work with release https://github.com/TypeStrong/atom-typescript/releases/tag/v8.0.0 :rose: If not raise issue at https://github.com/Microsoft/TypeScript-TmLanguage/issues and link us :rose:
