### ISSUE TITLE
With `noEmit: true` the `Compile failed but emit succeeded` message should not show

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#780]
Currently it does which is a bit misleading.

**Comment by aspirisen** [comment]
Have the same

**Comment by tetreault** [comment]
Also getting this issue when trying to work on Angular 2/NativeScript project. 

My `tsconfig.json` file looks like this: 

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "sourceMap": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true
    },
    "exclude": [
        "node_modules",
        "platforms",
        "**/*.aot.ts"
    ]
}
```

Version of `atom-typescript` is 10.1.13. Of course, removing `"noEmitOnError": true` resolves the issue but it seems like there's enough traction here to warrant another look at this bug perhaps. Thanks for your help and effort @basarat.
