### ISSUE TITLE
Weird syntax highlighting

### ISSUE THREAD

**Issue by zimme** [TypeStrong/atom-typescript#781]
Seems to be triggered by the `event` keyword?
![](https://i.imgur.com/Ydomgog.png)

**Comment by basarat** [comment]
Very likely. https://github.com/TypeStrong/atom-typescript/issues/675 needs a hero :rose:

**Comment by basarat** [comment]
Should work with release https://github.com/TypeStrong/atom-typescript/releases/tag/v8.0.0 :rose: If not raise issue at https://github.com/Microsoft/TypeScript-TmLanguage/issues and link us :rose:
