### ISSUE TITLE
Auto import feature

### ISSUE THREAD

**Issue by cevek** [TypeStrong/atom-typescript#782]
Webstorm have cool feature like auto import entities from indexed files

for example we are typing: `new Foo()` and WS prompt "import Foo from 'foo.ts'?" if we says yes, then it append to header `import {Foo} from './deep/folder/path/foo'`
![jhl ts - del - --dev-del 2015-12-16 13-20-51](https://cloud.githubusercontent.com/assets/3171573/11838406/e522fc78-a3f7-11e5-9229-3ee7658e1a4b.png)

**Comment by basarat** [comment]
Cool. Some guidance : https://github.com/TypeStrong/atom-typescript/blob/master/docs/quickfix.md

:warning: Its hard stuff that needs close attention that I find difficult for people that aren't me ... so instead of marking up for grabs marking as wishlist :rose:

**Comment by cevek** [comment]
Great! 
But why `import foo = require('../foo')` instead of `import {foo} from '../foo'`?

**Comment by basarat** [comment]
> why import foo = require('../foo') instead of import {foo} from '../foo'?

`import foo =` is not the same as `import {foo}`. it is more like `import * as foo` :rose:

**Comment by jschwarty** [comment]
I have a PR (https://github.com/TypeStrong/atom-typescript/pull/791) submitted that adds a quick fix option for an "import from" statement.

**Comment by amb-it-ion** [comment]
I got a missing dependency "Cannot find name ", but get no quick fix suggestion. I am on version 7.16.1. Any advice?

Thanks for your work - this feature is much needed.

**Comment by basarat** [comment]
@amb-it-ion can you share the code snippet. Might be the `canProvideFix` check is not valid for your code https://github.com/TypeStrong/atom-typescript/pull/791/files#diff-8fa30ff973791698c79754125ec84700R39

**Comment by dawidk92** [comment]
+1

**Comment by Regaddi** [comment]
+1

**Comment by sharpmachine** [comment]
+1

**Comment by basarat** [comment]
Please note that the TypeScript team is investigating a QuickFix api similar to Refactor api. Everyone is ofcourse is free to do whatever, this was just info :rose:

**Comment by satanworker** [comment]
Sorry, guys but is it working right now?
really want to use atom with TS, but without auto import feature like in Webstrom, feels really akward :)

**Comment by gvlekke** [comment]
+1

**Comment by jonaskello** [comment]
+1 This is the reason I stay with Webstorm. There is a [package](https://atom.io/packages/js-autoimport) that does this for regular js. Could it be ported to work for ts?

**Comment by fernandogomesdf** [comment]
+1

**Comment by tuliogalli** [comment]
please 👍

**Comment by jonaskello** [comment]
If I understand correctly [this PR](https://github.com/Microsoft/TypeScript/pull/9353) adds this feature to the TS language service. If that is true I guess it is just a matter of connecting it.

**Comment by dogancana** [comment]
+1

**Comment by ctretyak** [comment]
i need it!

**Comment by guncha** [comment]
I need it too!! 😄

**Comment by elvnthaus** [comment]
please please +1

**Comment by harrydroid** [comment]
Please I need it too, I had switched to VisualCode Studio

**Comment by carvalhods** [comment]
+1

**Comment by rickdgit** [comment]
+1

**Comment by Goodwine** [comment]
@dogancana, This package does help but it's not good enough.
For example in my `tsconfig` I have `paths:{ "asd": [ "../a/s/d" ] }, files: "../a/s/d/F.ts"`
Then when I try to use `F`, instead of adding `import F from 'asd/F'` I would get `import F from '../../../../../a/s/d/F'`

**Comment by guncha** [comment]
Codefix support that lets you do this sort of thing is now in the latest `atom-typescript`. To use: put the cursor on identifier where you see the "Cannot find name 'foo'", then press `ctrl+enter` to show available codefixes. It works with `paths` option in `tsconfig.json`, but only if you have specified a single path, not multiple.

**Comment by Drabc** [comment]
Is there anything special I need to do to set this up? I just tried it and it didn't work
atom 1.18.0
os Fedora 24
atom-typescript 11.0.4

**Comment by guncha** [comment]
@Drabc There isn't any special setup required, you just need a fairly recent Typescript version. It also might not work because you're trying to auto-import something from node_modules. This only works for imports from files in your project.

**Comment by Goodwine** [comment]
Same, it does work for me but my binding is `alt-enter`, try pressing `Ctrl-Shift-P` and look for "intentions: show" maybe you have it bound to different keys.

**Comment by guncha** [comment]
Right, I wasn't clear that `ctrl+enter` is the default for OSX only. For Linux and Windows, it's `alt+enter`. This is the package we're using for the GUI part of this: https://atom.io/packages/intentions

**Comment by AndrewBogushevich** [comment]
Using atom 1.18x64 on windows7

**Comment by klesun** [comment]
Just for info, 2.1.5 < "fairly recent Typescript version" <= 2.4.2

**Comment by AndrewBogushevich** [comment]
```
$ npm list -g typescript
+-- @angular/cli@1.0.1
| `-- typescript@2.2.2
+-- typescript@2.4.2
`-- typings@2.1.1
  `-- typings-core@2.3.3
    `-- typescript@2.3.1
```

**Comment by xiaobaker** [comment]
this is awesome! btw do we support single quote instead of double quote in the autofix?

**Comment by kevinlinhaw** [comment]
@AndrewBogushevich
Did you get it to work on Windows?
I tried on atom 1.20.0 x64 on both Windows10 and Windows8, no dice.
neither shortcut key and intentions: show command works....

on mac it works perfectly though, any ideas?

**Comment by AndrewBogushevich** [comment]
@kevinlinhaw 
Nope. I've just installed VSCode.

**Comment by eugensunic** [comment]
Come on guys WHY ISN'T THERE STILL A PACKAGE FOR THIS?!?!

**Comment by guncha** [comment]
@eugensunic, because you haven't built it.

**Comment by juanlet** [comment]
this would be super nice
