### ISSUE TITLE
Using `import` completion results in `import` removing prefixed whitespace

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/atom-typescript#783]
Sometimes you want/need whitespace - E.g. writing an ambient module definition manually.

**Comment by basarat** [comment]
# Guidance

This code : https://github.com/TypeStrong/atom-typescript/blob/9a5c29ffe11ab0e5944bad4a24d9e17b83cb5717/lib/main/atom/autoCompleteProvider.ts#L201-L240 should preserve whitespace :rose:

@blakeembrey Label as up for grabs if want it open for someone else :rose:

**Comment by austin94** [comment]
@blakeembrey I would be willing to take a stab at this one if you want to assignee the issue to be.  I've been using this tool for quite a while so I'm looking to give back!

**Comment by blakeembrey** [comment]
@austin94 We can't assign issues to people outside the organisation (I know, it'd be cool for GitHub to maybe allow this) but it's all yours if you're willing to work on it! Thank you :+1:

**Comment by austin94** [comment]
@blakeembrey Just made pull request #805.  Let me know what you think.

**Comment by basarat** [comment]
Fixed with https://github.com/TypeStrong/atom-typescript/pull/805 :rose: Released https://github.com/TypeStrong/atom-typescript/releases/tag/v7.16.1
