### ISSUE TITLE
Syntax Highlighting doesn't seem to work correctly

### ISSUE THREAD

**Issue by GabrielCTroia** [TypeStrong/atom-typescript#786]
There is a huge difference between Javascript's Syntax Highlighting and Typescript's. 
I'm not yet convinced this is a problem with atom-typescript but I did test more than one theme and it renders the same.

Please see some screenshots using Dark One below:

![screen shot 2015-12-17 at 2 01 02 pm](https://cloud.githubusercontent.com/assets/2099521/11879015/ed80d2f8-a4c6-11e5-8a23-ac1c38c50d26.png)

![screen shot 2015-12-17 at 2 01 14 pm](https://cloud.githubusercontent.com/assets/2099521/11879025/f71faa28-a4c6-11e5-902a-83a342dae719.png)

![screen shot 2015-12-17 at 2 01 21 pm](https://cloud.githubusercontent.com/assets/2099521/11879031/03d2f19e-a4c7-11e5-8069-ddfc22561963.png)

compared to its equivalent in JS:

![screen shot 2015-12-17 at 2 04 31 pm](https://cloud.githubusercontent.com/assets/2099521/11879049/1f3da078-a4c7-11e5-87f0-17583aba8b81.png)

![screen shot 2015-12-17 at 2 04 56 pm](https://cloud.githubusercontent.com/assets/2099521/11879080/3808484c-a4c7-11e5-8b0c-460d99c9f963.png)

**Comment by basarat** [comment]
It very well is a problem with this package. https://github.com/TypeStrong/atom-typescript/issues/675 needs a hero :rose:

**Comment by basarat** [comment]
Should work with release https://github.com/TypeStrong/atom-typescript/releases/tag/v8.0.0 :rose: If not raise issue at https://github.com/Microsoft/TypeScript-TmLanguage/issues and link us :rose:
