### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by DaltonNotetech** [TypeStrong/atom-typescript#788]
class Cl extends A implements Inter {
	a: string = "";
	f() {
		this.a = "";
	}
}

Here all the words in "A implements Inter" is od same color. Please fix it. I tried may themes....

**Comment by basarat** [comment]
Thanks. https://github.com/TypeStrong/atom-typescript/issues/675 needs a hero :rose:

**Comment by basarat** [comment]
Should work with release https://github.com/TypeStrong/atom-typescript/releases/tag/v8.0.0 :rose: If not raise issue at https://github.com/Microsoft/TypeScript-TmLanguage/issues and link us :rose:

**Comment by DaltonNotetech** [comment]
https://github.com/Microsoft/TypeScript-TmLanguage/issues/46
Not Even fixed in atom-typescript 8.0.0
