### ISSUE TITLE
Support "Find References" aka "Find Usages"

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#79]
https://atom.io/packages/atom-ternjs adds a panel at the bottom

Would be great if we could link this from the rename variable dialog.

Another sample :

https://github.com/atom/find-and-replace/blob/master/lib/project/results-pane.coffee
https://github.com/atom/find-and-replace/blob/master/lib/project/result-view.coffee
https://github.com/atom/find-and-replace/blob/master/lib/project/match-view.coffee

**Comment by park9140** [comment]
@basarat, https://github.com/atom/symbols-view/issues/70, for reference, the base symbols provider does has a view for this.

**Comment by basarat** [comment]
Alright I'll unassign myself till I understand that a bit more :heart:

**Comment by basarat** [comment]
Alright I've looked at it. Its basically "file symbols" and "project symbols". We already support that. 

Its not "find references" and therefore not related to this issue.

**Comment by mjohnsonengr** [comment]
Thank you so much for supporting this!  The view is 10x better than how Visual Studio or WebStorm do it!

**Comment by basarat** [comment]
> Thank you so much for supporting this! The view is 10x better than how Visual Studio or WebStorm do it!

:rose:

**Comment by j-walker23** [comment]
I am not even sure what this ticket is about but i agree with that last line for sure!! Thank you!
