### ISSUE TITLE
Stop opening all refactored files 

### ISSUE THREAD

**Issue by alexwall** [TypeStrong/atom-typescript#792]
is it possible **not** to open all refactored files. Just refactor and save the files. 

The problem is, when I use an common function in many files e.g. customLog() and want to rename it to something different like logInfo(), typescript/atom opens all the refactored files. 
I loose my (overview of my) workspace and the system slows down, because of opening all this files.

**Comment by basarat** [comment]
> The problem is, when I use an common function in many files e.g. customLog() and want to rename it to something different like logInfo(), typescript/atom opens all the refactored files.

I definitely understand, and I too feel frustrated by this sometimes. However this is unidiomatic as far as various IDEs go. So rejecting for now :rose:
