### ISSUE TITLE
Friendly heads-up: Depreciation cop showing 6 new depreciations as of 12/27/15

### ISSUE THREAD

**Issue by dsifford** [TypeStrong/atom-typescript#794]
See screenshot below:

![image](https://cloud.githubusercontent.com/assets/5240018/12011777/19301fb8-acaa-11e5-9851-627b28592586.png)

**Comment by basarat** [comment]
doesn't show for me for some reason. But the calls definitely exist, so up for grabs :rose: 

![image](https://cloud.githubusercontent.com/assets/874898/12015906/b952627e-ad97-11e5-9491-6451779d9ac8.png)
