### ISSUE TITLE
Unable to import native node modules like http, crypto

### ISSUE THREAD

**Issue by mr-moon** [TypeStrong/atom-typescript#795]
```
import crypto = require('crypto');
```
Results in
![image](https://cloud.githubusercontent.com/assets/933164/12026960/5df7c1e0-adc8-11e5-8b1a-650d534a86b7.png)

config.json is rather simple:
```
{
	"buildOnSave": true,
	"exclude": [],

	"compilerOptions": {
		"charset": " UTF-8",
		"removeComments": true,
		"sourceMap": false
	},

  "formatCodeOptions": {
  	"indentSize": 4,
  	"tabSize": 4,
  	"newLineCharacter": "\r\n",
  	"convertTabsToSpaces": false,
  	"insertSpaceAfterCommaDelimiter": true,
  	"insertSpaceAfterSemicolonInForStatements": true,
  	"insertSpaceBeforeAndAfterBinaryOperators": true,
  	"insertSpaceAfterKeywordsInControlFlowStatements": true,
  	"insertSpaceAfterFunctionKeywordForAnonymousFunctions": false,
  	"insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
  	"placeOpenBraceOnNewLineForFunctions": false,
  	"placeOpenBraceOnNewLineForControlBlocks": false
	}
}
```

Could not find any more info on this. What did I miss?

**Comment by laurelnaiad** [comment]
I use tsd (http://definitelytyped.org/tsd/) to easily get references to d.ts files, so my tsconfig for a node project would include:

```
        "./typings/node/node.d.ts",
```

having entered

```
tsd install node --save
```

and ensured that my typings directory is included in my filesGlob.

```
    "filesGlob": [
        "./typings/**/*.d.ts",
        (etc)
    ],
    "files": [
        "./typings/node/node.d.ts",
        (etc)
    ]
```

**Comment by mr-moon** [comment]
@laurelnaiad thanks. That nailed it. I wish it was documented.

**Comment by laurelnaiad** [comment]
It can be confusing. Perhaps like you, I started learning Typescript in atom-typescript, and it's not always clear where Typescript proper (i.e. the tsc compiler) leaves off and atom-typescript begins. Throw in the fact that Typescript grew up in the Visual Studio world, and it gets weirder (see the whole subject of /// references).....

In this case, the d.ts business is a pure typescript-ism, but filesGlob isn't (it's an atom-typescript-ism). tsd is a community project to help people get d.ts files, but not a part of Typescript or atom-typescript.
