### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kbh1245** [TypeStrong/atom-typescript#797]
[launcher] Process exited with error code 1

C:\Users\pandurang\AppData\Roaming\npm\node_modules\protractor\node_modules\sele
nium-webdriver\lib\goog\async\nexttick.js:41
  goog.global.setTimeout(function() { throw exception; }, 0);
                                      ^
 Error while waiting for Protractor to sync with the page: "window.angular is un
defined.  This could be either because this is a non-angular page or because you
r test involves client-side navigation, which can interfere with Protractor's bo
otstrapping.  See http://git.io/v4gXM for details"

**Comment by basarat** [comment]
Sorry, this isn't launcher. Perhaps the error report redirected here wrongly? Feel free to discuss if I am wrong :rose:
