### ISSUE TITLE
Add HTML autocomplete to backticks

### ISSUE THREAD

**Issue by dchacke** [TypeStrong/atom-typescript#800]
Following up on https://github.com/TypeStrong/atom-typescript/issues/221 (shout out to @jbarket for [implementing](https://github.com/TypeStrong/atom-typescript/pull/798) this!), it would be great to also add support for HTML element autocompletion. Perhaps this is only relevant for use with Angular, or there could be an option to toggle this feature.

Currently, it has autocomplete options but pretends to be in the global typescript context. This can lead to confusing autocomplete suggestions such as:

<img width="676" alt="confusing autocomplete suggestion" src="https://cloud.githubusercontent.com/assets/2866749/12077671/487e6cfc-b1a5-11e5-8b87-ea59ada97ecb.png">

(Note how the term "directives" is used as part of Typescript in line 27 and therefore suggested in line 33 even though we're in HTML land at that point.)

Ideally the autocompletion would also auto-close tags, tab through attributes, etc, just like in any other `.html` file.

**Comment by Emnalyeriar** [comment]
Emmet support with inline templates would be even more great

**Comment by jbarket** [comment]
@Emnalyeriar, I actually have this setup in mine. One of the cool things about the Emmet package is that you can easily tell it other grammars to expand in. I have this in my keymap.cson:

'atom-text-editor[data-grammar="source ts"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'

It'd be nice to find a way to only make Emmet work inside of the template tags, but I'm not sure if that's possible without actually adding something specific to the Emmet package itself.

**Comment by Emnalyeriar** [comment]
@jbarket Thanks I'll try this!

**Comment by qlaffont** [comment]
Hi, for me it doesn't work :/ 

keymap : 
`
{
    "48": {
        "alted": 64
    },
    "51": {
        "accent": true,
        "alted": 35
    },
    "52": {
        "alted": 123
    },
    "53": {
        "alted": 91
    },
    "54": {
        "alted": 124
    },
    "56": {
        "accent": true,
        "alted": 92
    },
    "57": {
        "alted": 94
    },
    "219": {
        "alted": 93
    },
    'atom-text-editor[data-grammar="source ts"]:not([mini])':
      'tab': 'emmet:expand-abbreviation-with-tab'
}

`

**Comment by mumairofficial** [comment]
there is greate extension for that https://marketplace.visualstudio.com/items?itemName=jakethashi.vscode-angular2-emmet

![use-extension](https://user-images.githubusercontent.com/6498132/33357639-20f43850-d4e5-11e7-8564-27d829c84156.gif)
