### ISSUE TITLE
Error on install in fresh atom installation v1.3.2 on Windows

### ISSUE THREAD

**Issue by robbatt** [TypeStrong/atom-typescript#801]
I'm on Windows 10. I got several other errors on install of atom-typescript, so finally wiped the whole atom installation clean and did a fresh install. This still gave me following error:

```
Installing “atom-typescript@7.16.0” failed.Hide output…

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EPERM, open 'C:\Users\rob\AppData\Local\Temp\apm-install-dir-11603-3236-uk4ftr\node_modules\atom-typescript\node_modules\babel\node_modules\babel-core\node_modules\core-js\modules\core.log.js'
```

**Comment by basarat** [comment]
> Error: EPERM, open 'C:\Users\rob\AppData\Local\Temp\apm-install-dir-11603-3236-uk4ftr\node_modules\atom-typescript\node_modules\babel\node_modules\babel-core\node_modules\core-js\modules\core.log.js'

Seems like babel installation from https://github.com/TypeStrong/atom-typescript/blob/466aab51daf582cd92140246ef1ba3ba46cbfaff/package.json#L49 is failing.

Most likey a bug in `npm install` run by *apm*. Would love it if you report on github/atom and link back here :rose:
