### ISSUE TITLE
Syntax highlighting broken when using function parameter

### ISSUE THREAD

**Issue by jpolo** [TypeStrong/atom-typescript#802]
Version 7.16.0

```
function myFunction<T>(f: (v?: any) => T) {
  //all highlighting is broken after this line
}

```

**Comment by basarat** [comment]
Thanks. https://github.com/TypeStrong/atom-typescript/issues/675 needs a hero :rose:

**Comment by basarat** [comment]
Should work with release https://github.com/TypeStrong/atom-typescript/releases/tag/v8.0.0 :rose: If not raise issue at https://github.com/Microsoft/TypeScript-TmLanguage/issues and link us :rose:
