### ISSUE TITLE
Applying the formatter multiple times corrupts the file

### ISSUE THREAD

**Issue by the-destro** [TypeStrong/atom-typescript#803]
I have noticed that if I do cmd+alt+l multiple times in a row on a file that it will start removing things and "damaging" the file making it unable to compile.

**Comment by basarat** [comment]
Surprisingly today was the first day this happened to me too. I'm not actively working on it so up for grabs. 

# Workaround 

Undo the changes that caused the corruption, save file, and try again :rose:

**Comment by the-destro** [comment]
This may be resolved in the latest update to both Atom and atom-typescript. I can't seem to reproduce it anymore....

**Comment by HeberLZ** [comment]
This is still happened, i just installed atom and atom-typescript for the first time and i'm having this issue, any news on this?

**Comment by Clay-Ferguson** [comment]
This bug definitely still exists. I thought I was having files messed with by hackers or something. What happens is that you end up with like one single character removed from various function names, etc. If this is a typescript bug related to running formatter multiple times it sure smells to me like a concurrency bug. The file is not being locked right, for exclusive access, or the formatter is not being stopped from running multiple concurrent threads stepping on each other as they write the file.
