### ISSUE TITLE
syntax highlighting doesn't work for decorators

### ISSUE THREAD

**Issue by RevanScript** [TypeStrong/atom-typescript#804]
It looks like this:

![Screen]
(https://i.gyazo.com/9d2f2d551f9b0e32b898197a28102547.png)

**Comment by giladgray** [comment]
Looks even worse on the class itself. Doesn't get any scopes!

**Comment by basarat** [comment]
Thanks. https://github.com/TypeStrong/atom-typescript/issues/675 needs a hero :rose:

**Comment by basarat** [comment]
Should work with release https://github.com/TypeStrong/atom-typescript/releases/tag/v8.0.0 :rose: If not raise issue at https://github.com/Microsoft/TypeScript-TmLanguage/issues and link us :rose:
