### ISSUE TITLE
Auto-Format on save

### ISSUE THREAD

**Issue by lordmat0** [TypeStrong/atom-typescript#810]
Hi there,

Just wondering if this was already included or if there is a way to do this? If not I'll give it a go to include it.

Thanks
Mat

**Comment by basarat** [comment]
> Just wondering if this was already included or if there is a way to do this? If not I'll give it a go to include it.

No included. If you want to add it please add under the `atom` key in tsconfig :rose: https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#atom

**Comment by lordmat0** [comment]
Okay I'll give it a go tonight :)

**Comment by basarat** [comment]
Fix https://github.com/TypeStrong/atom-typescript/pull/815 :rose:

**Comment by basarat** [comment]
Released : https://github.com/TypeStrong/atom-typescript/releases/tag/v8.1.0 :rose:
