### ISSUE TITLE
*.tsconfig.json / multiple tsconfig.json files in same directory?

### ISSUE THREAD

**Issue by laurelnaiad** [TypeStrong/atom-typescript#811]
Just a thought/feature request: I wish I could house multiple tsconfig files in the same directory. If they were sought as a glob of  `["tsconfig.json", "*.tsconfig.json"]` then it could be possible, no?

**Comment by blakeembrey** [comment]
The TypeScript compiler will be supporting multiple `tsconfig.json` files soon enough, so this is definitely important. I think it should be configured for each project, perhaps? It might be a good time to revisit how Atom TypeScript manages project configuration.

**Comment by laurelnaiad** [comment]
I will try to track down what plans are on the table for multiple tsconfigs within the compiler itself. I haven't been tracking that.

My use case: 

5 different tsconfig files in one repository: one is a browser app, one is the database code (we have V8 in our database tier, think of it like a thin middle tier above the database); one is e2e tests; one is a common library;  one is the build process automation itself.

There are process reasons why giving some of these projects the same "natural root" (i.e. tsconfig dir)  would be helpful. I don't think there are any deal-breakers with needing to keep each tsconfig in its own directory, but keeping them together, it seems, would simplify globbing scenarios handoffs between gulp streams (in my case) where the relative path from the root is what I'd really like too be tracking, whereas instead I have to track lots of paths to lots of roots. As I said, it's not like it can't be done. I just think it would be easier when transpiling several projects in one context if the tsconfig files and project roots were all easily held together.

As I'm using a gulp-typescript process for actual transpiling (we have reqs. for the repo to be able to build itself with minimal external tooling), I could just "give the compiler what it wants", as far as tsconfig goes, to actually build the separate projects within the repo in one pass, but atom-typescript only looks for files that exactly match `tsconfig.json`, as far as I know, and so there is a collision in the directory for that name, or the files aren't recognized as tsconfig files.... so it's really "just" the editor that I can't fudge in the direction I'd rather be going -- not that that's small potatoes or anything. :)

Lacking a common root, the overall repo/solution just has more "roots" to worry about when doing the build.

I was suggesting a manner of file naming to distinguish them only so as to minimize the "extra stuff" that would need to be configured in atom-typescript on a project-by-project basis. The filesGlobs and files arrays can take care of themselves as far as what files belong to what project, so it's really just **(at least in my optimistic head)** a matter of getting atom-typescript to broaden its definition of what a tsconfig file name looks like. Maybe that's more the compiler's business than it is the editor's though?

**Comment by basarat** [comment]
## One Idea

The current automatic lookup of tsconfig (up the directory tree) (code in [`projectCache.ts`](https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/lang/projectCache.ts)) can be migrated to something like a user controlled `activeProject` (sample https://github.com/alm-tools/alm/blob/master/docs/features/README.md#project-search code https://github.com/alm-tools/alm/blob/master/src/server/lang/activeProject.ts) 

But this is a massive refactor likely to change how one uses atom-ts and one that can lead to subtle bugs and changing user expectations :-/

**Comment by Meligy** [comment]
A classic scenario for this is being able to put tests next to the files they test. It's very common in Angular projects to have `foo.component.ts`, and `foo.component.spec.ts`.
