### ISSUE TITLE
Not registering paths specified in System.js

### ISSUE THREAD

**Issue by ShMcK** [TypeStrong/atom-typescript#814]
I'm unsure why Atom-TypeScript fails to register System.js file names resembling file paths. Other editors (Webstorm, Sublime) don't seem to share this same issue.

##### Example

Paths are loaded as:

    System.register("path/to/file", [], function() { ... });

The content is imported

    import {file} from 'path/to/file';

Resulting in the following error:

    Cannot find module 'path/to/file'

Despite the displayed error, all files load without issue.

##### Use Case

This is necessary for use with the Angular2-Meteor package which automatically generates System.js modules based on path names. See the tutorial for an [example](http://www.angular-meteor.com/tutorials/socially/angular2/3-way-data-binding), note the error for 'collections/parties'.

**Comment by basarat** [comment]
> Despite the displayed error, all files load without issue.

Probably because we default to `moduleResolution: node` as I prefer to have node modules resolved automatically. Set it to `classic` as a workaround :rose:

**Comment by ShMcK** [comment]
Thanks! Problem solved.
