### ISSUE TITLE
export not highlighted in syntax

### ISSUE THREAD

**Issue by mzelmanovich** [TypeStrong/atom-typescript#817]
After 8.0.0 updated the syntax changed. Export used to be highlight but is no longer.

**Comment by Jonatthu** [comment]
![captura](https://cloud.githubusercontent.com/assets/3742176/12286575/3709fba8-b97a-11e5-9d8c-999411dc95c0.PNG)
Same issue here with version 8

**Comment by mzelmanovich** [comment]
appears to be happening with class as well.

**Comment by basarat** [comment]
Thanks for the image :rose: Please also provide a copy paste code sample

**Comment by Jonatthu** [comment]
import {Component, Directive, Input} from 'angular2/core';
import {COMMON_DIRECTIVES, NgStyle} from 'angular2/common';
import {IImagetthu} from './IImagetthu';

@Component({
  selector: 'imagetthu',
  styleUrls: ['app/js/Common/Imagetthu/Imagetthu.css'],
  directives: [NgStyle, COMMON_DIRECTIVES],
  template: `
    <div class="Gallery">
      <div *ngFor="image in Images" class="Image" [ngClass]="{active: isOn}" [ngStyle]="{'background-image': image.ImageUrl}">
        <div class="Title">
          {{image.Name}}
        </div>
        <div class="Description" [ngClass]="{active: isOn}">
          {{image.Description}}
        </div>
      </div>
    </div>
  `,
})
export class Imagetthu {
  @Input() Images: IImagetthu[];

  OpenGallery(Image: IImagetthu): void {

  }

}

**Comment by basarat** [comment]
> Thanks to you for your great work

Thank you! Its not just me though :rose: 

## Question

I see `export`(/cc @mzelmanovich) and `class` (/cc @Jonatthu) both being highlighted: 

![image](https://cloud.githubusercontent.com/assets/874898/12340976/6a7a83dc-bb72-11e5-82f0-c9688d8e638d.png)

Or am I misreading the issue? :rose:

**Comment by Jonatthu** [comment]
Oh sorry its my mistake, I mean the syntax in the template property in the component decorator, was in html highlighted in the version 7.16.0, but now version 8.0.0 is just a string syntax, Could you please send me the correct url of another open issue like this in the version 8?

**Comment by basarat** [comment]
> I mean the syntax in the template property in the component decorator, was in html highlighted in the version 7.16.0, but now version 8.0.0 is just a string syntax

Created a new issue especially for this purpose : https://github.com/TypeStrong/atom-typescript/issues/818

Please let me know if there was something here that isn't addressed there :rose:
