### ISSUE TITLE
Async highlighting is broken in 8.1

### ISSUE THREAD

**Issue by RevanScript** [TypeStrong/atom-typescript#819]
Async highlight is not working after upgrade to 8.0 (or 8.1) for methods

```javascript
    public async asyncResponse(): Promise<Object> {
        return {
            promiseResult: 'promise is ok'
        }
    }
```

also, `class` keyword now looks like `storage type ts` in this example:

```javascript
export class IndexController extends AppController {
...
```

**Comment by basarat** [comment]
Please create an issue at https://github.com/Microsoft/TypeScript-TmLanguage/issues and link back here :rose:

**Comment by basarat** [comment]
I've added grammar docs https://github.com/TypeStrong/atom-typescript/blob/master/docs/grammar.md#cson-grammar to help everyone know what's going on :rose:
