### ISSUE TITLE
Class property types without semi-colons break highlighting

### ISSUE THREAD

**Issue by OttoRobba** [TypeStrong/atom-typescript#820]
![typescript_bug](https://cloud.githubusercontent.com/assets/597287/12439308/457ae728-bf16-11e5-9e1f-b2438e659a25.png)

In this example, x, y and constructor will not be properly colored. As you add in semi-colons, their highlighting is fixed.

**Comment by basarat** [comment]
Use semicolons! (sorry ... excuse my attempt at humor :rose:).

For grammar issues go here : https://github.com/Microsoft/TypeScript-TmLanguage/issues and link back to us if you want us to pull from upstream :rose:.

More : https://github.com/TypeStrong/atom-typescript/blob/master/docs/grammar.md#cson-grammar
