### ISSUE TITLE
F2 key conflict

### ISSUE THREAD

**Issue by Zorgatone** [TypeStrong/atom-typescript#822]
F2 is used by atom's official package "bookmarks" to jump to the next bookmark.
When atom-typescript is active F2 renames a variable instead.

Maybe use another shrotcut?

**Comment by basarat** [comment]
You should be able to `unset` the defaults provided by atom-typescript (please google and link to docs when you find them for others) and set your own. Leaving open for further discussion :rose:

**Comment by harryjubb** [comment]
You can add the following to your `keymap.cson` (Atom menu -> Keymap... on a Mac):

```
'atom-text-editor':
  'f2': 'bookmarks:jump-to-next-bookmark'
```

This overrides the key conflict with the bookmark default.

I still think that this is a genuine issue and that the atom-typescript default should be changed to not conflict with the "bookmarks" package.

**Comment by AlexanderKozhevin** [comment]
@Zorgatone you can close the issue
