### ISSUE TITLE
TSX indentation wrong after code format

### ISSUE THREAD

**Issue by bgrieder** [TypeStrong/atom-typescript#823]
The first "wrapping" closing tag is systematically moved to one full ident to the right. 
Parent closing tags "follow"

![tsx-formatting](https://cloud.githubusercontent.com/assets/797684/12617941/09267664-c512-11e5-9e4b-47d4338c9af3.gif)

atom: 1.4.1
atom-typescript: 8.1.0

**Comment by basarat** [comment]
Thanks. Let me update to TypeScript latest.

Once we update to TypeScript latest and it still doesn't work you can create a bug at Microsoft/TypeScript  :rose: (similar to https://github.com/Microsoft/TypeScript/issues/3838)

**Comment by basarat** [comment]
Planning an update for Friday :rose:

**Comment by bgrieder** [comment]
Great. Thanks. Will update Friday and report back/create a bug, as appropriate.

**Comment by basarat** [comment]
@bgrieder I made some time and did a release : https://github.com/TypeStrong/atom-typescript/releases/tag/v8.2.0 Because I couldn't keep my hands off `readonly` :) :rose: 

Please raise with MS if formatting doesn't do what you expect and link me in for my knowledge :rose:

**Comment by bgrieder** [comment]
Many thanks but unfortunately this seemed to have no impact on this issue.
Once thing that bugs me: 
We are using tsc 1.7.5.
From https://github.com/TypeStrong/atom-typescript/issues/469, I understand atom-typescript is using its own version (ntypescript)
Updating our project to use the nightly of typescript will not help in any way, right ?

**Comment by basarat** [comment]
> Updating our project to use the nightly of typescript will not help in any way, right ?

Will not help with formatting. Other than that it will allow you to use the latest features in the build server.

**Comment by bgrieder** [comment]
OK.
I created issue https://github.com/Microsoft/TypeScript/issues/6687
Hope I got the ntypescript version correct
