### ISSUE TITLE
Modules are not resolving when using jspm

### ISSUE THREAD

**Issue by asotog** [TypeStrong/atom-typescript#824]
Recently i started to try http://jspm.io/ which installs modules out of the node_module folder but now the typescript modules are not getting resolved

**Comment by basarat** [comment]
@asotog can you share a project with 

* Expected State
* Actual Error statements 

:rose:

**Comment by asotog** [comment]
Hi I think this can be closed it is related to the way typescript resolves the paths https://github.com/Microsoft/TypeScript/issues/5039#issuecomment-175917940 thanks
