### ISSUE TITLE
Updated Grammers in v8.2.0 broke syntax highlighting for Allman style indentation.

### ISSUE THREAD

**Issue by brad-jones** [TypeStrong/atom-typescript#825]
After I updated to v8.2.0 I noticed my synatx highlighting was a little off.

Example of broken highlighting:
![image](https://cloud.githubusercontent.com/assets/2754772/12665880/4876d7ea-c68f-11e5-9501-c6e9f825bbf7.png)

Expected highlighting:
![image](https://cloud.githubusercontent.com/assets/2754772/12665908/a3fd41da-c68f-11e5-9db2-a870aa601fe2.png)

If I change my example class to conform to a K&R style indentation then the highlighting works correctly. 
![image](https://cloud.githubusercontent.com/assets/2754772/12666019/b7861e4c-c690-11e5-8e96-5c7ab586bcdd.png)

If I reverse the changes made by: 1faf60737494d8c0123883d775d487530b622515 I get my expected highlighting back.

**Comment by mLaird** [comment]
My syntax colors are completely gone for typescript .ts  files.  My html files still show colors for different syntax elements, but all my .ts files became black and white in atom sometime in late January. I've been fussing with the tsconfig.json in the hope of restoring color syntax, but nothing changes.  I use atom's One Light for both UI and Syntax.  I've tried changing to other atom standard offerings, but the .ts files are black and white with all of them - for me.  Need help.
