### ISSUE TITLE
Question: Formatting for code hints

### ISSUE THREAD

**Issue by mhartington** [TypeStrong/atom-typescript#828]
Howdy, quick question really about how to format jsdoc info

So currently, with ionic, we're just inlining markdown in our code as part of our doc build process. Unfortunately, this is problematic with your plugin as it outputs everything as one long string 

![screen shot 2016-02-01 at 12 43 29 pm](https://cloud.githubusercontent.com/assets/2835826/12725641/adb63642-c8e1-11e5-94aa-3f524745abcb.png)

Now my question is, if were to format this a bit more with ngdoc/jsdoc style tags, would the preview window pick up that formatting?

**Comment by basarat** [comment]
> if were to format this a bit more with ngdoc/jsdoc style tags, would the preview window pick up that formatting

We just pass the doc comment as it is from the TypeScript language service to atom autocomplete 

Would love to have input from https://github.com/atom/autocomplete-plus/issues :rose:

**Comment by mhartington** [comment]
Good to know :smile: 
Will pass this along
Thanks
