### ISSUE TITLE
When tsconfig.json is modified, the changes have no effect until Atom is restarted

### ISSUE THREAD

**Issue by claudio-silva** [TypeStrong/atom-typescript#83]
For instance: change `compilerOptions.module` and recompile (`ctrl + shift + b`). The emitted code remains the same. If you restart Atom (or select `View->Reload`) and recompile, the code will be emitted correctly.
The same applies to other properties of `tsconfig.json` (ex. the `files` property - this one made me scratch my head for a while until I figured out what was happening).

**Comment by basarat** [comment]
Thanks. Already in queue #80

**Comment by basarat** [comment]
Published as `v0.57.0`.

@csnover / @park9140 would be great if anyone can test it on a mac. Since `chokidar` will be running under `atom` in those cases and I haven't tested.

@claudio-silva Feel free to log any more bugs that are major blockers for you :heart:

**Comment by claudio-silva** [comment]
Cool! It woks like a charm! :sunglasses:
Thank you!
I know you've got many issues pending and your time is limited, but sill, as you said, "it helps prioritize", so I'll report any issues I find as I start using Atom + `atom-typescript` for serious work.
