### ISSUE TITLE
Performance is underwhelming

### ISSUE THREAD

**Issue by Bifros7** [TypeStrong/atom-typescript#830]
Hi, I'm having trouble with this plugin. I've been using it for quite a while for working with angular2 at work and I love it, but the performance has recently become really bad. It can take upwards of 10seconds for autocompletion to show up, and compiling on save of a single, small file can take even longer.

I've been using it both on a filesystem over the network mounted via sshfs and stored locally on my SSD and it doesn't seem to make a difference. I've updated atom to the latest version, 1.4.1 and even completely reinstalled it. Deactivating all plugins except typescript doesn't help either.

Can anyone help me with troubleshooting these issues?

**Comment by s-panferov** [comment]
@Bifros7 	I'm not the package maintainer, but I've faced with similar issue one. Try to add this to your tsconfig.json

```
    "exclude": [
        "node_modules"
    ]
```

**Comment by Bifros7** [comment]
@s-panferov Thanks for the suggestion, but I have already excluded node_modules.

**Comment by basarat** [comment]
@Bifros7 can you share your `tsconfig.json` :rose:

**Comment by Bifros7** [comment]
I don't think I can share the complete config since this is a corporate project, but I can give you the general structure.

`{
   "compilerOptions": {
      "declaration": false,
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true,
      "isolatedModules": false,
      "module": "commonjs",
      "noImplicitAny": false,
      "noLib": false,
      "outDir": "./webapp/app",
      "preserveConstEnums": true,
      "removeComments": true,
      "suppressImplicitAnyIndexErrors": true,
      "target": "es5"
   },
   "exclude": [
      "./node_modules/"
   ],
   "files": [
      "./typings/custom/es6.d.ts",
      "./typings/custom/jquery.d.ts",
      "./typings/custom/negsoft.d.ts",
      "./typings/jquery/jquery.d.ts",
      "./typings/jqueryui/jqueryui.d.ts",
      "./typings/underscore/underscore.d.ts",
      "./webapp/app/app.ts",
---about 150 more .ts files in /webapp/---
   ],
   "filesGlob": [
      "./**/*.ts",
      "./**/*.tsx",
      "!./node_modules/**/*"
   ],
   "atom": {
      "rewriteTsconfig": true
   }
}
`

I hope this helps even though I couldn't include the complete file.

**Comment by basarat** [comment]
> I hope this helps

It does. You have `"!./node_modules/**/*"` This is bad. Should be `"!./node_modules/**"`

docs : https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#for-really-large-projects-atom-typescript-gets-slow :rose:
