### ISSUE TITLE
Disable JS Auto Generating Feature.

### ISSUE THREAD

**Issue by remaerd** [TypeStrong/atom-typescript#835]
Hello, Love your work really much. I'm creating games and it backend and Atom-TypeScript is my best choice. Thank you very much.

However, I have a small feature request to disable this package to generate JS files automatically. I'm currently using a game engine named "Egret" to create HTML5 web games. When I try to save a TS file. This package will run the `tsc` command to generate the JS code for me. But my game engine do not need them and I have no idea how to disable this feature for this project.

Could you consider make this possible to disable this feature? I'm wondering a special comment in the tsconfig.json may suit the need. Grunt / Gulp user may benefits from this feature too. If their workflow is complicated, They can still enjoy other wonderful features provided by this great package.

Thank you again.

**Comment by nycdotnet** [comment]
You can set `compileOnSave: false` in your tsconfig.json to achieve this.  Feel free to re-open if this does not solve your problem.

https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#compileonsave
