### ISSUE TITLE
Nesting file types

### ISSUE THREAD

**Issue by defyjoy** [TypeStrong/atom-typescript#839]
Is there a way to support nesting file for `app.js` and `app.js.map` under app.ts . It makes easier to find the typescript file or else it gets lost under lot of files . Need a feature very similar to [Microsoft File Nesting extension](https://visualstudiogallery.msdn.microsoft.com/3ebde8fb-26d8-4374-a0eb-1e4e2665070c) , Can we do this for typescript . It'd be pretty handy.

**Comment by laurelnaiad** [comment]
AFAIK, atom's tree view doesn't have the kind of extensibility that it really should in order to do this properly.

**Comment by laurelnaiad** [comment]
Then again, I wonder how much could be done with some crafty/hacky css.

**Comment by defyjoy** [comment]
perhaps grouping the nodes based on file name would do the trick ? I am pretty new to atom though .
