### ISSUE TITLE
Support ctrl+/ to create a comment inside JSX code

### ISSUE THREAD

**Issue by lbguilherme** [TypeStrong/atom-typescript#844]
![5e7a58a7db1b82c1c0808f0b656df9c8](https://cloud.githubusercontent.com/assets/546954/12949466/b916077c-cfe6-11e5-80d2-2bf59af468ac.png)

Pressing `ctrl`+`/` on the second line produces this:

![a9e732ae136d2ee9e99e3af97a8ad5c2](https://cloud.githubusercontent.com/assets/546954/12949469/c594ebb2-cfe6-11e5-95e3-04f151df9da5.png)

Which is not a comment at all (and is correctly not highlighted as such). A better behavior would be this:

![e70ac5aee98b9fd547b9b0a57a4a5f90](https://cloud.githubusercontent.com/assets/546954/12949475/d096e2cc-cfe6-11e5-8843-a71fe6e624a6.png)

**Comment by MrOggy85** [comment]
Intermediate fix, add this snippet:
```
'.source.ts':
  'comment.jsx':
    'prefix': 'commentjsx'
    'body': '{/* $1 */}'
```
Usage
* Cut your code
* use snippet by writing `commentjsx`
* Paste
