### ISSUE TITLE
Use typescript classifier for syntax highlighting

### ISSUE THREAD

**Issue by 2426021684** [TypeStrong/atom-typescript#850]
Use typescript classifier for syntax highlighting.

**Comment by basarat** [comment]
@2426021684 good Idea. We did that but atom spec on grammar is not final so we dropped it for now. Some old docs https://github.com/TypeStrong/atom-typescript/blob/master/docs/grammar.md#dynamic-grammar

Also using the TypeScript *lexical classifier* is unsufficient and using the *syntactic classifer* is non trivial (details https://github.com/codemirror/CodeMirror/issues/3839) :rose: 

Closing as too complex and makes the package fragile unless one is maintaining it everyday.
