### ISSUE TITLE
Two ampersands && are parsed as two separate operators

### ISSUE THREAD

**Issue by denis-sokolov** [TypeStrong/atom-typescript#851]
`&&` is parsed as `keyword operator arithmetic ts` + `keyword operator arithmetic ts` instead of one boolean operator. This prevents proper font rendering for combined operators.

**Comment by long-lazuli** [comment]
#926 is fixing this.

**Comment by long-lazuli** [comment]
You can now update the grammar.
https://github.com/Microsoft/TypeScript-TmLanguage/pull/145
