### ISSUE TITLE
Panel is too wide

### ISSUE THREAD

**Issue by tomitrescak** [TypeStrong/atom-typescript#852]
When the error message is too wide, the panel is expanded with is and the buttons and progressbars disappear with it. It is needed either to cut off the overflow or wrap it:

Image below shows the full width of Atom window, notice the missing buttons.

![screen shot 2016-02-16 at 11 42 35](https://cloud.githubusercontent.com/assets/2682705/13064017/9730046c-d4a2-11e5-9acd-88aa0019ca07.png)

**Comment by stepancar** [comment]
@tomitrescak , agree with you

**Comment by giladgray** [comment]
this causes problems for me in fullscreen mode when the editor stretches beyond the application viewport, pushing my minimap off the screen.
