### ISSUE TITLE
report wrong

### ISSUE THREAD

**Issue by SallyOne** [TypeStrong/atom-typescript#853]
hi,i use this plugin write angular2,but find a problem.please see http://plnkr.co/edit/?p=preview. This code
`getHeroes() {
    this._heroService.getHeroes().then(heroes => this.heroes = heroes);
  }`

will report a wrong.Specific information is Type '{}' is not assignable to type 'Hero[]'.But in browser angular2 can run right.It is bug?

**Comment by blakeembrey** [comment]
@SallyOne You didn't share a link that others can view. However, it's unlikely that this is an Atom TypeScript issue as it's just a TypeScript problem you're facing. I can't comment without seeing the code, but most likely the types aren't assignable.

**Comment by SallyOne** [comment]
sorry.this is link:  http://plnkr.co/edit/39QSqX24mV6gVqGxVUSq?p=preview

**Comment by blakeembrey** [comment]
I can't replicate your issue, it's working fine for me. Please make sure the typings you use for `Promise` are correct.

**Comment by stepancar** [comment]
@SallyOne , it's not atom-typescript issue. As i understand, problem with this._heroService.getHeroes()
