### ISSUE TITLE
Cannot find TypeScript module in node_modules

### ISSUE THREAD

**Issue by tmlbl** [TypeStrong/atom-typescript#854]
I have a TypeScript module I have written installed in my `node_modules` folder. The `index.ts` file looks something like this:

```typescript
import {MyClass} from "./src/MyClass";

export var Class = MyClass;

window["MyClass"] = MyClass;
```

I then require the module within the project like so:

```typescript
import myModule = require("my-module");
```

My `tsconfig.json` is pretty much just defaults:

```json
{
    "version": "1.5.0-beta",
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "isolatedModules": false,
        "jsx": "react",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": true
    },
// etc...
```

Atom is warning me that it cannot find the module, and that compilation is failing. However TypeScript (Version 1.9.0-dev.20160208) compiles just fine using that tsconfig. When I change the require statement to something like this:

```typescript
import myModule = require("../node_modules/my-module");
```

Atom stops complaining. This is fine for now but I want others on my team to be able to fire up the module in Atom with ease. Any ideas how to fix this? Am I missing something?

**Comment by laurelnaiad** [comment]
You should add `"moduleResolution": "node"` to your compiler options. Apparently this is the default in TS 1.9, but atom-typescript may not know that?
