### ISSUE TITLE
How do I give the path to tsconfig.json?

### ISSUE THREAD

**Issue by takeradi** [TypeStrong/atom-typescript#855]
My tsconfig.json is in a different directory. How do I give that path to the atom-typescript package?

**Comment by laurelnaiad** [comment]
Open a workspace at a directory level that is at or above the tsconfig.json file. If your tsconfig.json file is in the tree, and if it has a filesGlob that matches your .ts files and you're letting atom-typescript rewrite the files list based on the filesGlob array, and if you open one of those .ts files in atom, then you should be "experiencing" that tsconfig file with all of the rights and privileges thereunto.... i.e. F6 should try to build your project at that point, etc.

**Comment by gnz00** [comment]
Any better solution for this?
