### ISSUE TITLE
Does atom-typescript hide certain compilation errors?

### ISSUE THREAD

**Issue by migajek** [TypeStrong/atom-typescript#857]
conside the file below, test.ts
```
function writeF(f: () => number){ }
for (let i of [1,2,3,4,5]) {
  writeF(() => i);
}
```

it does compile with atom-typescript without any error shown:

![image](https://cloud.githubusercontent.com/assets/581492/13171148/7a58a848-d6f1-11e5-9d0c-e4508b1198bb.png)

**When compiled with command line tsc.exe, I've got the following error**

```
z:\tmp>tsc
test.ts(2,1): error TS4091: Loop contains block-scoped variable 'i' referenced by a function in the loop. This is only supported in ECMAScript 6 or higher.
```
(the JS file gets generated, though)

How / why does that happen? 
I don't think hiding errors is a desired behavior.

So far I've been happily developing and building my project with atom-typescript. Imagine my surprise when I've tried configuring build tools (gulp) and faced this situation

my command-line tsc is 1.7.3 
```
z:\tmp>tsc -v
message TS6029: Version 1.7.3
```

so is the Atom-included version

```
c:\Users\YYYY\.atom\packages\atom-typescript\node_modules\ntypescript\bin>tsc -v
message TS6029: Version 1.7.3
```

the tsconfig is the default one generated by Atom, included below.

atom-typescript is 8.2.0

```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "isolatedModules": false,
        "jsx": "react",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": true
    },
    "filesGlob": [
        "**/*.ts",
        "**/*.tsx",
        "!node_modules/**"
    ],
    "compileOnSave": true,
    "buildOnSave": false,
    "files": [
        "test.ts"
    ],
    "atom": {
        "rewriteTsconfig": true
    }
}
```

**Comment by blakeembrey** [comment]
No, errors are not hidden. But it's compiled with a different TypeScript version to yours that does support this feature. If you do `npm i typescript@next` you'll get the nightly, which is closer to what's in `atom-typescript`.

**Comment by migajek** [comment]
great, thank you for the explanation :)
