### ISSUE TITLE
"allowJs" compiler option rejected

### ISSUE THREAD

**Issue by sparseinference** [TypeStrong/atom-typescript#858]
I'm using the latest version of typescript, but atom-typescript claims that certain compiler options in the tsconfig.json file are invalid.

```
--allowJs
--project
```

for example.

Is there any way to work around this?

**Comment by dallonf** [comment]
Also seeing this issue with `allowJs`.

**Comment by jforcada** [comment]
Same problem here.

I compile with `tsc` in the shell anyway, but `atom-typescript` stops doing error checking and autocompletion, which should not happen in any case IMO.

**Comment by splodingsocks** [comment]
I'm running the latest typescript version as of today, 1.9.0-dev.20160324, and the compiler supports these options. Does atom-typescript bundle its own version of typescript? If so, can it be configured to point to a different version on the system?

**Comment by sparseinference** [comment]
@splodingsocks  - In the atom-typescript settings, I have configured the path to the "typescriptServices.js" in my global install of typescript. It still reports that the tsconfig.json file is invalid.

**Comment by splodingsocks** [comment]
@sparseinference  bummer. Thanks for the follow-up!
