### ISSUE TITLE
name change of .ts file not effective

### ISSUE THREAD

**Issue by onesick** [TypeStrong/atom-typescript#859]
Hi there,

I think you might be aware of this issue. But when I change the name of .ts file it only creates the new js and js.map files and do not erase the old compiled js files. So in effect, although my .ts has been changed, since the comipled .js files are alive, it still works like before, which is not what I intended and I had to manually erase those files.
Is it only happening to me because I am just using .gitignore file?
Is there a better way to handle these problems? Because at the moment in one folder I have only like 6 .ts files, which generated 2 more files each so I have 18files in a folder 2/3 of them that only takes the space. Please let me know if there are better alternatives.

Thank you.

**Comment by laurelnaiad** [comment]
I'm under the impression that atom-typescript does as you wish *if* it notices the renaming of the file, and that it generally only notices this if (a) it already knew what project the .ts file belonged to and (b) you do the renaming from within atom (while viewing a .ts file, b/c the editor plugin is active (or more active) when a .ts file is in a single pane of the editor... or something like that?
