### ISSUE TITLE
Files can get mangled if you don't restart Atom after updating to 8.3.0

### ISSUE THREAD

**Issue by rleidal** [TypeStrong/atom-typescript#864]
I updated to version 8.3.0 during a short break and started noticing some odd behavior.
If lines weren't "aligned" to the auto-indenter's ideals the parsing would flag errors.

For example:

```
class test{
  value: number;
  constructor(){
    this.number = 5;  //4 spaces Works fine
  this.number = 6;    //2 spaces - parse error #Cannot find object is
  }
}
```

Furthermore the format on save would start mangling the file.
Super indenting some lines.
Deleting large swaths of code from the start of lines to fix super indentations on the next save.
Removing curly braces after function definitions.

It seems like there needs to be a reinitialize hook after upgrades to restore state to a known-good value.

**Comment by danimbrogno** [comment]
Experiencing this issue as well, even after restarting Atom.
