### ISSUE TITLE
Quickfix for interface method stubs

### ISSUE THREAD

**Issue by bali182** [TypeStrong/atom-typescript#867]
I find this a very useful feature, mostly for compiled languages like java or scala.

Let's say you have an interface:

``` ts
interface IFoo {
  foo(): number
  bar(): string
}
```

Now when you start writing an implementation, and you have this:

``` ts
class FooImpl implements IFoo {
}
```

It would be really helpful to have a quickfix, that is able to generate for you something like this:

``` ts
class FooImpl implements IFoo {
  foo(): number {
    return undefined;
  }
  bar(): string {
    return undefined;
  }
}
```

Because otherwise you have to go to the interface, copy-paste the methods, ... I don't have to explain the process.

Do you consider implementing this? If not, would you consider accepting a PR if I were to implement it?

**Comment by nycdotnet** [comment]
Would absolutely accept a PR.  Thank you.

**Comment by karlkras** [comment]
@nycdotnet , was there any traction on this feature add request?

**Comment by nycdotnet** [comment]
I haven't seen any, but would still love a PR for it.

**Comment by bali182** [comment]
I started looking at how this could be done, when I found this: https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/lang/fixmyts/quickFixes/implementInterface.ts (which is I guess what this issue is about), but unfortunately I didn't go any further and forgot about it :cry:

**Comment by kyasbal-1994** [comment]
Is there any plan to be implemented? As long as I see the code of quick fix, the quick fix code wouldn't do anything.  The quickfix just shows `implement interface` suggestion.
I the quickfix should be removed if the feature is not implemented. I thought that was bug first time but actually that is only not implemented.

**Comment by p-bakker** [comment]
I've implemented this today locally, using the TypeScript Language Service getCodeFixesAtPosition API, which seems to do exactly what this Quickfix is supposed to do.

Any thoughts as to why the LanguageService API wasn't used before or why it doesn't seem to be used for any of the other Quickfixes (afaics from a quick look through the code)

The only problem I have is that the formatting is off. Anyone knows how to fix the formatting? I would've thought the LangaugeService would return me the code fixes properly formatted, but that doesn't seem to be the case.

If I can get this formatting resolved, I can make a Pull Request out of this

**Comment by guncha** [comment]
Quickfixes were only recently added to the Typescript API while `atom-typescript` has had them for a while. It's a similar story with a few other features like glob support in `tsconfig.json`. Now that the compiler has these, it doesn't make sense to use the custom versions. There's a rewrite of the plugin to only use official APIs in #1166 and I intend to deprecate the current master once that beta gets some testing in the trenches. 

One thing it is currently lacking is Codefix support and I would be extremely happy if some enterprising soul would add that.
