### ISSUE TITLE
Errors don't refresh when the same file is open in multiple panes

### ISSUE THREAD

**Issue by Ptival** [TypeStrong/atom-typescript#869]
Often, when doing some refactoring, I split my editor in two panes (Ctrl-k Right) and start editing one of the panes.

In this setting, sometimes the error messages don't refresh until I focus my cursor on the file opened in the other pane.

Steps to reproduce:
1. Open a .ts file in a project
2. Ctrl+k Right (should split in two panes, put your focus in the right pane)
3. Type something wrong (like `let x : boolean = 42;`)
4. Ctrl+s should save and report an error in the left pane.
5. Click on the left pane, replace `boolean` with `number` and do Ctrl+s, the error is still reported.
6. Click on the right pane, the error is finally removed.

**Comment by 0815fox** [comment]
I can confirm this bug with Atom 1.5.3 and atom-typescript 8.3.0. Just ran over the same issue.

There seem to be two "error views", the one named "Typescript" realizes that the error is gone. The builtin one not.

![snapshot](https://cloud.githubusercontent.com/assets/8955528/13489767/2d1476ce-e129-11e5-8861-69a3295863a3.jpeg)

**Comment by zenwarr** [comment]
Can confirm this too (atom 1.7.4 and atom-typescript 8.10.2). This behaviour can be very annoying. Errors persist until i save file and switch to another pane.

**Comment by roddypratt** [comment]
Here's a quick screencast I made showing the problems I'm seeing when using multiple panes. https://screencast-o-matic.com/watch/cb1o2eXRGd

This with Atom 1.18.0, atom-typescript 11.0.3,

**Comment by tamethecomplex** [comment]
I have this issue even when working with a single pane...typescript version 2.3.4, Atom 1.18.0, and atom-typescript 11.0.6.

Anyone else having this issue independent of multiple panes vs not?

**Comment by demisx** [comment]
I run into this issue constantly in latest Atom 1.20.1 and atom-typescript 11.0.9. It got to a point that 2-pane mode is no longer usable in Atom.
