### ISSUE TITLE
Autocompletion only shows 10 entries

### ISSUE THREAD

**Issue by claudio-silva** [TypeStrong/atom-typescript#87]
I see on your code that you have hardcoded a limit to the number or items that are displayed.
Perhaps you have done it for performance reasons, nevertheless one of the main purposes of autocompletion is to provide a means for API exploration "on the spot" and that limitation defeats that purpose.
For me, it's a real "show stopper". Being unable to explore all options available to me at the cursor position it's... very unproductive.
Would you remove that limit, or at the very least, provide a way for the user to configure it?

**Comment by basarat** [comment]
> Would you remove that limit, or at the very least, provide a way for the user to configure it

I will remove increase that limit to 50 + force autocomplete+ to do the same if you are using atom-typescript. 

original source of limit was : https://github.com/atom-community/autocomplete-plus/blob/27947fa7dc7a4ff7894f7b6e5b7650dd0116e9b6/lib/main.coffee#L20-L25

**Comment by claudio-silva** [comment]
Great!
Although I suspect I might hit that new limit ocasionaly, as some component classes on my framework have lots of properties + methods.
The best way would be for the user to be able to set that limit him/herself. Perhaps a setting in `tsconfig.json` or on the package's UI for settings?
Or, as an easier-to-implement alternative, would 100 as limit be too much?
Nevertheless, for now I suppose it will have to do. I'll let you know if I hit the limit anytime soon.

**Comment by basarat** [comment]
> The best way would be for the user to be able to set that limit him/herself. Perhaps a setting in tsconfig.json or on the package's UI for settings

I could remove the limit in our code completely. And then its up to the user to configure autocomplete plus however *they* like. That would be the best option.

**Comment by claudio-silva** [comment]
Indeed! :+1:

**Comment by basarat** [comment]
![image](https://cloud.githubusercontent.com/assets/874898/6222401/1abf2cd8-b6a7-11e4-80d6-b00bf1dae3fd.png)

**Comment by basarat** [comment]
Published in `v0.58.0`.

**Comment by basarat** [comment]
Investigate : how bad is it if we (silently) just increase the limit to 100 if its under that count

**Comment by jvilk** [comment]
Please keep a limit in place. My project, DoppioJVM, now generates an 8MB declaration file at build-time to provide typings for JVM classes. Right now, atom-typescript is super speedy when typing `JVMTypes.java` (etc), which would normally return over 900 results.

Proof:
https://gist.github.com/jvilk/39354703e0e5d150fe37

**Comment by basarat** [comment]
@jvilk thanks and agreed. I've been running it with 100 and it does slow down sometimes. So leaving it up to the user to find their own sweet spot.
