### ISSUE TITLE
BaseUrl and Path support

### ISSUE THREAD

**Issue by tomitrescak** [TypeStrong/atom-typescript#870]
@basarat is Microsoft/Typescript#5039 supported in the plugin? I cannot make it work and it should be available in the @next branch which you use with the plugin.

Maybe I'm doing something wrong. Thanks.

**Comment by tomitrescak** [comment]
My tsc compiler works fine, only Atom throws errors. Is it possible to update the compiler to the latest version in order to use this great functionality?

**Comment by basarat** [comment]
@tomitrescak sorry but I've withdrawn a bit from OSS. Work on this has been picked up by other people though : https://github.com/TypeStrong/atom-typescript/pull/849 :rose:

**Comment by tomitrescak** [comment]
Nooooooooo! :( Good luck then! ;)
