### ISSUE TITLE
Slow compilation when node_modules is present

### ISSUE THREAD

**Issue by tomitrescak** [TypeStrong/atom-typescript#871]
Hi, even when I move my tsconfig.json into the child directory out of reach of node_modules the compilation is still 10-15 times slower when node_modules directory is present. My current directory structure is following:

```
appRoot
|- tsconfig.json
node_modules
```

my tsconfig.json is following:

```
...
  "filesGlob": [
    "!node_modules",
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ],
...
```

Any idea on how can I resolve long compilation times? It is not a stressing issue.

**Comment by tomitrescak** [comment]
Is there really that nothing can be done? I just move the nodes modules directory outside of the project and compilation is 10times faster. All the ignore flags seem not to work. Is there any way I could ignore it?

**Comment by apptoix** [comment]
I had the same problem before. Try on Preferences->Core settings-> Ignore files, add node_modules.
That was the only workaround I found.

**Comment by Springrbua** [comment]
I have (or had) the same problem on a Angular2 Web-Application I am currently working on.
I could work with Atom Typescript for quite a while, without any (or only very few and rare) problems. But suddenly the "pending request" used to constantly grow, whenever i open a file and start coding. Also saving a file, while continuing to code wasn't possible.
I can't remember, when the problem first occured. It might be an update of Angular2 or another npm package, which added more files, it might be a change in the files (tsconfig or something like that) I made or even an update of Atom Typescript.  
However today it seems to work a lot better (faster) then yesterday. The things i changed are the following:
- Update from Angular2 Beta 14 to Beta 16 and update of Zone.JS from 0.6.6 to 0.6.12
- Changed the filesGlob-pattern from "!./node_modules/**/*.ts" to "!./**/node_modules/**"
- Added the exclude property with the value "["./**/node_modules"]"

I am not sure if any of this things reduced the lag or if it is just random. At least i can work with it today, without having to wait a few minutes after every "ctrl+s"...
