### ISSUE TITLE
"Building"/"Build success" overlay hides file tabs

### ISSUE THREAD

**Issue by 0815fox** [TypeStrong/atom-typescript#872]
The tabs which show multiple files are hidden by the "Building" message. That way it is impossible to switch to another file using the tabs, while a build message is shown:

![snapshot](https://cloud.githubusercontent.com/assets/8955528/13490079/c35f030a-e12a-11e5-8da7-a320cfea9a90.jpeg)

Not sure if the messages are a built-in feature in atom, as I am new to atom. So my report might be in the wrong place here.

**Comment by gauravk92** [comment]
+1

**Comment by nycdotnet** [comment]
If the build messages were just moved down slightly, would that fix the problem for you?

**Comment by 0815fox** [comment]
Definitely.
Additionally,hide on click were heloful.

Am 25. März 2016 04:36:20 MEZ, schrieb Steve Ognibene <notifications@github.com>:
>If the build messages were just moved down slightly, would that fix the
>problem for you?
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/TypeStrong/atom-typescript/issues/872#issuecomment-201122073

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by gauravk92** [comment]
That would solve it for me as well! 🎉
On Fri, Mar 25, 2016 at 3:29 AM 0815fox <notifications@github.com> wrote:

> Definitely.
> Additionally,hide on click were heloful.
>
> Am 25. März 2016 04:36:20 MEZ, schrieb Steve Ognibene <
> notifications@github.com>:
> >If the build messages were just moved down slightly, would that fix the
> >problem for you?
> >
> >---
> >You are receiving this because you authored the thread.
> >Reply to this email directly or view it on GitHub:
> >
> https://github.com/TypeStrong/atom-typescript/issues/872#issuecomment-201122073
>
> --
> Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail
> gesendet.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/TypeStrong/atom-typescript/issues/872#issuecomment-201232416>
>
-- 
Sent from my iPhone

**Comment by nycdotnet** [comment]
OK.  PRs certainly accepted.  This should hopefully be fairly straight-forward to implement.  Tagging up-for-grabs.

**Comment by gauravk92** [comment]
I was considering looking into this last night but don't have any
familiarity with the code base.

If anyone has some familiarity and can post a reference to where to make
the change to the build notification position, I'm sure that would be
helpful.

If it's still up for grabs after a few days I will probably have a look and
try to submit a PR. Thanks!
On Fri, Mar 25, 2016 at 12:34 PM Steve Ognibene <notifications@github.com>
wrote:

> OK. PRs certainly accepted. This should hopefully be fairly
> straight-forward to implement. Tagging up-for-grabs.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/TypeStrong/atom-typescript/issues/872#issuecomment-201447969>
>
-- 
Sent from my iPhone

**Comment by nycdotnet** [comment]
I would search for the string that appears in the notification and go from there.  Alternatively, search for top or tooltip.  I expect this to be fairly basic, and it might even be a one line change.

**Comment by gauravk92** [comment]
It looks like the notifications are handled by atom and this should be
moved to an Atom issue. In the meantime I've added the following CSS to my
stylesheet which has fixed the issue for me.

atom-notifications { padding-top: 51px; }

On Sat, Mar 26, 2016 at 3:43 PM Steve Ognibene <notifications@github.com>
wrote:

> I would search for the string that appears in the notification and go from
> there. Alternatively, search for top or tooltip. I expect this to be fairly
> basic, and it might even be a one line change.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/TypeStrong/atom-typescript/issues/872#issuecomment-201944941>
>
-- 
Sent from my iPhone

**Comment by atombender** [comment]
Could we get a setting to _disable_ the notifications? They're super annoying, and they pile up — if you save multiple times, the previous build notifications don't go away. Compile progress is shown in the TypeScript status bar, so I don't know why the notifications are needed.
