### ISSUE TITLE
align constructor parameters

### ISSUE THREAD

**Issue by BugsBunnyBR** [TypeStrong/atom-typescript#877]
Hi, I have a constructor with lots of parameters and if I break line atom is not formatting it properly.

Today:

```
  constructor(protected nav: NavController, navParams: NavParams, protected proposalService: ProposalService,
    bankService: BankService, contractService: ContractService, constants: Constants) {
```

Expected:

```
  constructor(protected nav: NavController, navParams: NavParams, protected proposalService: ProposalService,
              bankService: BankService, contractService: ContractService, constants: Constants) {
```

**Comment by pubkey** [comment]
Same problem here.
I added the linting-rule to my tsconfig
```json
    "align": [
      true,
      "arguments",
      "parameters"
    ]
```

the linting in atom shows an error, but typescript-autoformat does not understand it.

**Comment by guncha** [comment]
Formatting is purely handled by the compiler so every editor that's using `tsserver` API is going to have the same issue. There isn't much `atom-typescript` can do for you here. Your best bet is to find an analogous issue in the Typescript and VSCode repos and see what's the suggested solution there and if they even are going to consider it.
