### ISSUE TITLE
Autocomplete and compileOnSave

### ISSUE THREAD

**Issue by shadeglare** [TypeStrong/atom-typescript#878]
Seems **autocomplete** is not working when **compileOnSave** is false. 

If change a type name in one file and try to import it from another there'a always no export member found error. It works fine with **compileOnSave** is on but I use other building tools and need only refactoring and autocomplete without emitting output.

I use atom-typescript 8.3.0.

**Comment by laurelnaiad** [comment]
You can set the compiler option `"noEmit": true` to suppress all the tsc output in atom-typescript while leaving "compileOnSave": true to make sure that atom-typescript keeps up with your source code changes, etc. With this combination, you can use F6 to get atom-typescript's opinion of the build all while having a gulp watch process in the background doing all sorts of ungodly things to the code (including transpilation).

**Comment by keathmilligan** [comment]
Setting noEmit to true makes the editor happy, but it causes gulp-typescript to fail. I had to resort to creating two tsconfig files one for atom-typescript and another for gulp with a different name. atom-typescript really needs to manage its own settings outside of tsconfig.
