### ISSUE TITLE
Return from Declaration

### ISSUE THREAD

**Issue by xealot** [TypeStrong/atom-typescript#879]
The standard Atom editor has a `return-from-declaration` shortcut that I would love to see for Typescript. Coming from an IDEA IDE world and having the ability to jump back and forth when tracing code is invaluable.

**Comment by oldbasilbear** [comment]
Me too - it's a bit lop-sided without the ability to get back where you came from.

**Comment by guncha** [comment]
It certainly is, but there's a more general solution to this problem. Give https://atom.io/packages/last-cursor-position a whirl.

**Comment by deanproxy** [comment]
@guncha this doesn't do what the original request wanted.  Last cursor does not operate in the same manner as return-from-declaration.  You will get random return points with the last-cursor-position plugin when combining it with go-to-declaration.

**Comment by guncha** [comment]
That is correct - I've been missing something like `return-from-declaration` lately since `last-cursor-position` will not work as well if you've jumped around after `go-to-declaration` a few times.

It wouldn't be too hard to add, though I'd probably just do it for `atom-typescript-beta` (#1166).

**Comment by deanproxy** [comment]
It also helps with those that use vim-mode because for some reason your cursor location isn't properly registered when in "normal mode." You have to first enter insert mode, then jump away and `last-cursor-position` will make an attempt to bring you back as long as you don't muck around in the new location like you mentioned.

I'm not familiar with this plugin except for using it recently, but I can have a go at trying to make a fix for this and see what I come up with.

**Comment by guncha** [comment]
Yes, that'd be great. I think all you need is:

1) Keep a stack of file locations (filepath / line / column) that is shared between the jumping  commands.
2) Update `go-to-definition` to push locations on this stack and create the `return-from-definition` command to pop them.

**Comment by deanproxy** [comment]
Okay, I have a [pull request](https://github.com/TypeStrong/atom-typescript/pull/1190) in for this issue.

This is my first attempt at an Atom plugin, so feel free to request any changes before accepting the pull request. I have attempted to follow your contributions docs, but I may have missed something.

**Comment by deanproxy** [comment]
I can also add it to the tsserver branch if you'd like. Wasn't sure if you were going to do that yourself...
