### ISSUE TITLE
On autocompletion, properties display type "property" instead of the true type

### ISSUE THREAD

**Issue by claudio-silva** [TypeStrong/atom-typescript#88]
It would be quite useful...

**Comment by basarat** [comment]
so show "number" instead of what it is currently: 
![image](https://cloud.githubusercontent.com/assets/874898/6223714/d4d5a45a-b6c3-11e4-8d73-02ff008878ab.png)

Am I right?

**Comment by basarat** [comment]
Quick experiment:
![image](https://cloud.githubusercontent.com/assets/874898/6223743/5aafb250-b6c4-11e4-96d9-c58bf8c5b199.png)

Perhaps such details are better served via #34 as this becomes *TMI* too quickly

**Comment by basarat** [comment]
> this becomes TMI too quickly

not more TMI than methods,functions. Properties are now treated just the same.
