### ISSUE TITLE
Better filter for Dependency graph

### ISSUE THREAD

**Issue by 0815fox** [TypeStrong/atom-typescript#880]
Is it possible to filter dependency graph in a more advanced way? For example I'd like to only see files, which are in a not in a folder named "test" and start with C.
e.g. as a regex, might be sth. like this:

```
/(?!.*\/test\/.*)\/C.*\.ts/
```

**Comment by laurelnaiad** [comment]
Did you try it?

Quoting from the code comment:

https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/tsconfig/tsconfig.ts#L136

`    filesGlob?: string[];                               // optional: An array of 'glob / minimatch / RegExp' patterns to specify source files`

**Comment by laurelnaiad** [comment]
I've never tried a regex, myself, but that comment would lead me to believe it's intended to work.

**Comment by 0815fox** [comment]
Sorry, might have expressed not clear enough: I mean the [Dependency Graph](https://github.com/TypeStrong/atom-typescript/blob/master/docs/dependency-view.md), not the tsconfig file...

**Comment by laurelnaiad** [comment]
You were totally clear, but I glossed over those key words.

**Comment by Igmat** [comment]
It's definitely needed feature to make Dependency Graph more useful. It's common case to include tests in `tsconfig` but those file not very related to actual sources when we are building graph.

**Comment by sompylasar** [comment]
https://github.com/TypeStrong/atom-typescript/issues/1252 _`Dependency view` option removed?_
