### ISSUE TITLE
outFile option prevents output

### ISSUE THREAD

**Issue by PierreAnctil** [TypeStrong/atom-typescript#883]
When adding the `outFile `option in _tsconfig.json_, the **output is not generated**.

See the minimalist attached example:
When the `outFile` option is removed, the output files are generated (but in several files).
When using tsc in the command line, the output is generated.

**Config:**
atom 1.5.4
atom-typescript 8.3.0
typescript 1.8.7
Windows 10

[test.zip](https://github.com/TypeStrong/atom-typescript/files/172188/test.zip)

**Comment by basarat** [comment]
Reported in the wild as well : http://stackoverflow.com/questions/36024552/atom-tsconfig-not-compiling-when-it-vscode-it-does

**Comment by iTouchTheSky** [comment]
Seems like we have to change that here : 
https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/tsconfig/tsconfig.ts#L317 
to reflect `compilerOptions.outFile = ...` instead.

Doing so fix the compilling with outFile, but the compile time is really slow.

**Comment by basarat** [comment]
Makes sense. Would also like it if `out` is moved to `outFile` https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/tsconfig/tsconfig.ts#L311-L313 and then `outFile` is used wherever `out` is used in the codebase currently (projectService.ts and building.ts) :rose:

**Comment by iTouchTheSky** [comment]
I fixed it, How can I push my branch ?

**Comment by basarat** [comment]
@iTouchTheSky hopefully you pressed the `fork` button on top and *then* you did the edits to your local branch. If so just do `git add .` `git commit -m "your message"` and then `git push`. Now if you go to your fork on github (it should show your commits as the last ones there) you should see a "Create Pull Request" button. 


Alternatively you can edit the file *here* online (edit button on top of each file). Github will automatically create a fork and add your commits and allow you to create a PR (pull request). 

More : https://help.github.com/articles/using-pull-requests/ :rose:

**Comment by basarat** [comment]
Please https://github.com/TypeStrong/atom-typescript/releases/tag/v8.3.1 a go :rose:

**Comment by PierreAnctil** [comment]
I just tried 8.3.1 and the issue is indeed resolved
Thanks a lot @iTouchTheSky and @basarat

**Comment by iTouchTheSky** [comment]
No problem I needed it for my workspace too so I figured why not fix it instead of waiting on someone to fix it :)
