### ISSUE TITLE
Wrong highlight in words with keywords

### ISSUE THREAD

**Issue by mmicu** [TypeStrong/atom-typescript#885]
The image clarifies every doubt.

![screen shot 2016-03-16 at 00 23 10](https://cloud.githubusercontent.com/assets/14826658/13797369/5a7eeb24-eb0d-11e5-8120-1823023a2758.png)

**Comment by GregOnNet** [comment]
Hi,

I can not reproduce the mentioned problem.
Maybe it is gone with one of the latest updates? 

![screen shot 2016-05-20 at 14 52 24](https://cloud.githubusercontent.com/assets/444278/15428248/7faf137c-1e9a-11e6-8a20-84a1cbb78703.png)

Kinds
Greg
