### ISSUE TITLE
Compiling a single file

### ISSUE THREAD

**Issue by tomitrescak** [TypeStrong/atom-typescript#887]
Hi, this is more a question than am issue, for which I apologise. 

Would you be able to point me to a correct location in your source code, where you deal with a compilation of file on save? It looks like you correctly compile only a single file without recompiling the whole project. I am trying to achieve the same behaviour with Gulp but I just cannot make it work with type checking. Thanks!

**Comment by liukun** [comment]
Seems this package call `tsc` functionalities internally by `ntypescript` module which is not possible by external script IMHO.
