### ISSUE TITLE
Project file contains invalid options forceConsistentCasingInFileNames

### ISSUE THREAD

**Issue by denis-sokolov** [TypeStrong/atom-typescript#888]
A [compiler option](https://github.com/Microsoft/TypeScript/wiki/Compiler-Options) forceConsistentCasingInFileNames causes the entire atom-typescript to fail. No typechecks or suggestions of any sort work when the option is in the config.

```
Error: Project file contains invalid options
    at Object.getProjectSync (~/.atom/packages/atom-typescript/dist/main/tsconfig/tsconfig.js:260:32)
```

More generally, perhaps you should not handle unknown keys gracefully?

**Comment by princjef** [comment]
I run into the same problem using the same compiler option.

While I do appreciate a warning in the case of unknown compiler options (handy in case of misspellings and such), it seems like they should just be ignored for static analysis or there should at least be an option to ignore them.

**Comment by wiggisser** [comment]
I have the same problem with the option "listEmittedFiles".
