### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by claudio-silva** [TypeStrong/atom-typescript#89]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
Object.activate (/Users/claudio/.atom/packages/atom-typescript/lib/main/atomts.js:34:9)
```

**Comment by claudio-silva** [comment]
That's the error message I get from Deprecation Cop.
It seems not be critical, but it seems to be something you should take into account.

**Comment by basarat** [comment]
I haven't found an alternative yet. Thanks for creating an issue.

**Comment by basarat** [comment]
TODO: 

View is probably a singleton. 
Check if we get the same view each time. Log it out to reveal in Dom.

**Comment by basarat** [comment]
> View is probably a singleton.

No. The workspace view i.e. `atom.views.getView(atom.workspace)` is a singleton, but it is not the same as the `editorView` which is repeated for each editor.
