### ISSUE TITLE
Typescript backticks color highlighting inside

### ISSUE THREAD

**Issue by pitops** [TypeStrong/atom-typescript#892]
I have noticed that when using this with Angular 2 and i write inline templates, there is not syntax coloring everything is in the same color, is there a way to enable coloring inside backticks?

```

@Component({
  selector: "ng2-app",
  template: `
    <section class="jumbotron full-height">
      <top-navigation></top-navigation>
      <div class="container">
        <router-outlet></router-outlet>
      </div>
    </section>
  `,
  directives: [TopNavigationComponent, ArcListComponent]
})

```

**Comment by ZombieHippie** [comment]
Backticks are purely a template string, there is no inherent *language* that is used between backticks. Maybe there is a solution to detecting the language between the ticks, but that may not be desirable to have as an added process.

**Comment by albtdd** [comment]
I think that may be very very desirable to have that feature. I have tried IntelliJ IDEA, that support that feature, and is fantastic. I hope that Atom supported too in the near future.

![atom](https://cloud.githubusercontent.com/assets/12040245/14344869/5e10eb94-fcaa-11e5-9f64-a5af90657acb.jpg)

**Comment by pitops** [comment]
@ZombieHippie  As @albtdd presented, for angular 2 devs it will become a very desirable feature and its frustrating to not have a solution, when phpstorm/webstorm/intelli j idea have it out of the box already. I do not really like those programs as they are more memory heavy and the likes and it would be a very welcome feature if i want to stay with atom. So i hope someone does it a reality.

**Comment by ZombieHippie** [comment]
Very interesting, and cool! It would be neat to have a toggleable syntax
highlighting.

**Comment by Deviad** [comment]
Still waiting for this.

**Comment by ZombieHippie** [comment]
Hey @Deviad , I took a swing at this for you as it was an incredibly easy fix, my update is one commit ahead of the latest release tag and I have published my alternative version on atom.

https://atom.io/packages/atom-typescript-zh-backticks

If you use this version, you may need to rename your config keys. I don't very much wish to create a pull request for this, as I'm not entirely sure the way I did it is the "best way".

![image](https://cloud.githubusercontent.com/assets/2925395/14594585/94ad0826-04fd-11e6-80d9-5357d75b7d66.png)

**Comment by pitops** [comment]
@ZombieHippie can you make this a standalone addon?

**Comment by ZombieHippie** [comment]
@pitops it's possible to release as a language, but I don't have time, and I don't actually know if it would work separated from the main package.

**Comment by Deviad** [comment]
@ZombieHippie Hello, thank you very much for the time you've dedicated to this modification. I really appreciate it. Thank you!

**Comment by ZombieHippie** [comment]
You're welcome, I hope it works without issues. Otherwise, you can probably
patch the original package manually with that comparison I mentioned.

**Comment by GregOnNet** [comment]
Hi,

https://github.com/TypeStrong/atom-typescript/pull/948 has added html-syntax-highlighting in Angular 2 Components.

Is this solution suitable for you?

Kinds
Greg

**Comment by pitops** [comment]
yep this can be closed now, at last official support cheers!

**Comment by jrwhip** [comment]
I am using atom-typescript v12 and it does not appear to have html-sytax-highlighting in components. Has this feature been removed since it was added in v8?

**Comment by lierdakil** [comment]
We currently lack resources to support our own grammar fork, and it created conflicts with Atom's bundled typescript grammar. So we ultimately opted to discontinue our grammar and let Atom team handle the grammar on their end. Sorry.

See https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#syntax-highlighting-is-bad
