### ISSUE TITLE
tsconfig.json "declaration": true but d.ts files not generated

### ISSUE THREAD

**Issue by jeffschwartz** [TypeStrong/atom-typescript#894]
Atom v1.6.0

atom-typescript v8.4.0

My complete tsconfig.json:

``` json
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "isolatedModules": false,
        "jsx": "react",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "declaration": true,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": true,
        "sourceMap": true,
        "outDir": "dist"
    }
}
```

**Comment by Busyrev** [comment]
same issue, win 10, tsc Version 1.8.10, 
`{
  "compilerOptions": {
    "rootDir": "./src/ts",
    "outDir": "./local_build/js",
    "outFile": "local_build/js/app.js",
    "declaration": true
  }
}`

**Comment by scippio** [comment]
I have same problem (using `gulp-typescript` and `createProject("tsconfig.json"))` so I must run `tsc` manually and all is ok after that ...

**Comment by dylanrenwick** [comment]
@scippio are you manually piping `tsProject.dts` in your gulpfile?
See [gulp-typescript's readme](https://github.com/ivogabe/gulp-typescript)

**Comment by lierdakil** [comment]
Pretty sure this issue is long outdated.
