### ISSUE TITLE
100% CPU in ubuntu 14.04 with atom-typescript 8.4.0

### ISSUE THREAD

**Issue by petervojtek** [TypeStrong/atom-typescript#896]
atom will occupy 100% of cpu when .ts file is opened and this plugin (version 8.4.0) is enabled.
OS: 32bit ubuntu 14.04
atom v 1.1.0

**Comment by nycdotnet** [comment]
Do you experience this if using the latest atom (v1.6)?

**Comment by petervojtek** [comment]
Hi @nycdotnet, I installed atom 1.6 from via apt-get and when I start it, I see only this screen. So now I cannot use atom at all :(

![screenshot from 2016-03-23 22 23 53](https://cloud.githubusercontent.com/assets/225506/14001430/17911406-f146-11e5-9900-64bb53985c1c.png)

**Comment by a-reda** [comment]
I have the same issue while using atom v1.6. The CPU is at 100% and the number of tasks keeps growing.

**Comment by leocorder** [comment]
Same issue here. atom v1.9.9 and atom-typescript v10.1.6

**Comment by leocorder** [comment]
I managed to increase performance significantly by modifying the file **tsconfig.json** to this:

```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": false
    },
    "exclude": [
        "node_modules",
        "platforms"
    ]
}

```
