### ISSUE TITLE
100% CPU when config file contains unknown option

### ISSUE THREAD

**Issue by wereHamster** [TypeStrong/atom-typescript#897]
I use typescript 1.9.0-dev.20160321 because I need the baseUrl option. The atom-typescript plugin can't handle that and starts using 100% CPU. It prints heaps of `Error: Project file contains invalid` into the console and has queued about 3300 pending requests (see https://cloudup.com/ck65Dky_ORa and https://cloudup.com/cl8zQh7HJRk).

**Comment by nycdotnet** [comment]
thanks for the report.

**Comment by CristyTarantino** [comment]
+1
