### ISSUE TITLE
Go To Declaration ignores file open in different pane

### ISSUE THREAD

**Issue by Ptival** [TypeStrong/atom-typescript#898]
When splitting my editor in multiple panes (Ctrl-K-based shortcuts), I feel like my expectation upon using F12 (Go To Declaration) would be that the editor jumps to the suitable file if it is open in any pane.

Right now, it will open the destination file in the current pane. This could be a valid behavior but having the option would be great.

How to reproduce:
- You need two files such that file source.ts has a definition in file target.ts
- Open source.ts
- Split the editor in two panes (Ctrl+Shift+P -> Pane: Split Right)
- In one of the panes, open target.ts
- In the other pane, find a use of something defined in target.ts, and Go To Declaration (F12)

Wanted behavior:
- The editor goes to the declaration in the pane where target.ts was already opened.

Current behavior:
- The editor opens another target.ts in the current pane.

Sorry, it's a bit of a nitpick. :-)

**Comment by basarat** [comment]
We just use the `atom` API endpoint : `atom.workspace.open` : https://github.com/TypeStrong/atom-typescript/blob/50b75523600a71570dbe9eab55e1c0c1f2eca5b0/lib/main/atom/commands/commands.ts#L148 If it provides a better API endpoint feel free to PR :heart: :rose: 

FWIW our tooltips break horribly across multiple panes too :) I don't do much multi pane development personally, but definitely see the desire (try opening typescript source's `checker.ts`, last I checked it was `15K+` lines :rose:)
