### ISSUE TITLE
Linter stops linting after first lint of file

### ISSUE THREAD

**Issue by adamduren** [TypeStrong/atom-typescript#906]
I have been using this package for months and have never encountered this issue. The linter appears to stop functioning after it lints one time. The only way to get it to lint is by performing a soft reset and then it lints the file once more. My tsconfig.json has not changed recently. It happened in the middle of the day. No updates were performed before this occured AFAIK.

Debugging steps taken:
 * Restart Atom
 * Restart Windows
 * Uninstall atom-typescript
 * Reinstall atom-typescript
 * Uninstall and Install atom-typescript 8.3.2
   * Repeat down to 8.0.0

I have included additional information below. Please let me know if there is anything I can do to help.

Additional Information:
 * Tsc version: 1.8.7
 * Atom Version: 1.6.1
 * Plugin Version: 1.8.4
 * OS: Windows 10

**Comment by adamduren** [comment]
Here is my tsconfig file. I have also disabled all third party plugins except for the core plugins.

```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "system",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "moduleResolution": "node",
        "removeComments": false,
        "noImplicitAny": true,
        "suppressImplicitAnyIndexErrors": true
    },
    "exclude": [
        "node_modules",
        "jspm_packages"
    ]
}
```

**Comment by adamduren** [comment]
Things get even stranger. I removed my `.atom` folder to start from scratch and only install `atom-typescript`. The behavior originally describe still persists. The `.js` files are getting generated on save but are only outputting the compiled version from the last soft reset.

I can delete any `.js` file then edit or truncate the corresponding `.ts` file and save. The output does not correspond. I then do a soft-reset and the output is now correct.

**Comment by adamduren** [comment]
@basarat

**Comment by basarat** [comment]
Think it might be an `atom-linter` bug. I don't maintain the linter myself /cc @steelbrain :rose:

**Comment by steelbrain** [comment]
@adamduren Can you try installing `linter-eslint` or any other linter provider and see if you get the same behavior with those providers as well

**Comment by adamduren** [comment]
I tried linter-eslint with no luck. However I was able to fix it by stashing my changes and reapplying them. It does not make sense to me how this would have fixed it but it works for now and I'm unable to recreate the issue. Thanks for getting back to me, hopefully this was just a strange one-off.
