### ISSUE TITLE
Atom-typescript reports definition files as "not included in the compilation context" when they cross symbolic links

### ISSUE THREAD

**Issue by Ptival** [TypeStrong/atom-typescript#908]
For some reason I had decided I would centralize my `DefinitelyTyped/` folder, and have all my TypeScript projects point to it by a symbolic link.

```
~/Project1/DefinitelyTyped ---symbolic link---> ~/DefinitelyTyped
~/Project2/DefinitelyTyped ---symbolic link---> ~/DefinitelyTyped
```

And in each `tsconfig.json` I write:

```
files: [
  "DefinitelyTyped/library/library.d.ts",
]
```

This works well, except when I am editing a file in one of the projects, and I jump into a library definition, the file `~/DefinitelyTyped/library/library.d.ts` opens, and atom-typescript reports that it is not in my current compilation context.

I'm not quite sure how you would detect that, but it would be nice if atom-typescript was smart enough to realize that it is the same file as `~/Project1/DefinitelyTyped/library/library.d.ts`, which is indeed in my compilation context.

**Comment by michael-yx-wu** [comment]
I am also having this issue. Restarting my editor seems to "fix" it temporarily, at least until I open another definition file. It's not show-stopping, but is slightly frustrating.
