### ISSUE TITLE
Installing failes for plugin “atom-typescript@8.5.0”

### ISSUE THREAD

**Issue by akshayat** [TypeStrong/atom-typescript#909]
I am trying to install atom-tpyescript plugin in atom IDE. When I press Install button I get this. I tried installing using command prompt too, it is giving me same error.
```
Installing atom-typescript to C:\Users\vadherak\.atom\packages
assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: Expected there to only be one child in node_modules
    at C:\Users\vadherak\AppData\Local\atom\app-1.7.0-beta1\resources\app\apm\lib\install.js:165:22
    at ChildProcess.onChildExit (C:\Users\vadherak\AppData\Local\atom\app-1.7.0-beta1\resources\app\apm\lib\command.js:51:49)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

**Comment by akshayat** [comment]
I have 1.7.0-beta1 version of Atom

**Comment by kankaristo** [comment]
I was having this issue with Atom 1.7.0-beta0, but the install was successful with Atom 1.7.0-beta4. I don't know if the update fixed it or if it just magically started working.

**Comment by akshayat** [comment]
It worked for me in 1.6.2 - stable version.

**Comment by RichardSlater** [comment]
I also have this working on `1.7.0-beta4`, perhaps this was an issue specific to `1.7.0-beta0`-`1`, or perhaps an adverse interaction with another package.  @akshayat if this is still an issue for you after updating to `1.7.0-beta4` perhaps you could post a list of all of the extensions and their versions.

**Comment by basarat** [comment]
Should work fine if you follow this : https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#failed-to-update

If it still doesn't work please leave a comment and someone will reopen :rose:
