### ISSUE TITLE
Bad syntax highlighting

### ISSUE THREAD

**Issue by Stacey-Gammon** [TypeStrong/atom-typescript#912]
Shouldn't this syntax have better highlighting for the class member variables and functions?
![syntaxhighlighting](https://cloud.githubusercontent.com/assets/16563603/14370183/6c7a8524-fcf9-11e5-8f5e-12fcccc22858.png)

**Comment by basarat** [comment]
Please create an issue here : https://github.com/Microsoft/TypeScript-TmLanguage we just use that for syntax highlighting :rose: https://github.com/TypeStrong/atom-typescript/blob/master/docs/grammar.md
