### ISSUE TITLE
Keep declarations file updated

### ISSUE THREAD

**Issue by heruan** [TypeStrong/atom-typescript#915]
Say I have a `tsconfig.json` with this entry:
```
    filesGlob: [ "./modules/**/*.d.ts" ]
```
then when a `.d.ts` file in `./modules` changes, Atom seems not to be aware of it and I need to reload to have the current declarations updated.

**Comment by basarat** [comment]
> Atom seems not to be aware of it and I need to reload to have the current declarations updated.

By design https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#atom-typescript-is-complaining-about-not-finding-files-or-other-weird-errors. We do not do file watching in this editor. However if you edit the file *in atom* everything should just work :rose:
