### ISSUE TITLE
Autocomplete shows snippet in last position

### ISSUE THREAD

**Issue by fredericlefeurmou** [TypeStrong/atom-typescript#916]
The autocomplete shows my snippets in last position. Is that normal?

![screenshot from 2016-04-08 19 11 21](https://cloud.githubusercontent.com/assets/1689073/14391750/3efcdfdc-fdbe-11e5-8060-5e7cdec31966.png)

**Comment by basarat** [comment]
Yes. Its an atom thing, not really and atom-typescript thing :rose:
