### ISSUE TITLE
Atom freezes after 200+ pending requests are active at once

### ISSUE THREAD

**Issue by chrillewoodz** [TypeStrong/atom-typescript#917]
Every time the little counter at the bottom right in atom reaches 200 or higher, atom freezes and I have to restart it. This only happens when this plugin is used. It's seriously annoying because you can barely write 5 lines of code without a restart.. Is there a fix for this?

**Comment by GregOnNet** [comment]
Hi @chrillewoodz,

I ran into the same problem like you.
I don't know why these actions are not processed like expected.

I solved the problem by excluding `node_modules/` in the `tsconfig.json`.
So I think there is a problem indexing `typescript`-files.
