### ISSUE TITLE
Painless guidance for Mutliple Project Support

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#92]
Basically files that need to work on server as well as client. Plus we need good TS debugging experience (more important once generators / `async` land). 

For the server code we compile it using `commonjs` with source maps.

FYI I did https://github.com/basarat/demo-fullstack/tree/master/src once upon a time for `grunt-ts`.

**Comment by csnover** [comment]
I don’t understand why this is being committed to this repository?

**Comment by csnover** [comment]
I don’t understand why this is being committed to this repository? This isn’t relevant to IDE codeintel…

**Comment by basarat** [comment]
Just like other examples we have for testing. This will be for testing multi target support i.e client code + server code + common code. All using tsconfig files. 

When we start adding tests these will be the code samples that should continue to work. Or when working on feature PRs right now we can run their code against these examples ourselves. 

I definitely need to add ignore on publish.

**Comment by csnover** [comment]
How are these examples used for testing?

**Comment by basarat** [comment]
Manually at the moment. I open the file in the ts folder. Change it. And make sure we get the right js at the right place.

**Comment by basarat** [comment]
refs https://github.com/TypeStrong/atom-typescript/issues/26

**Comment by basarat** [comment]
I am thinking the easiest solution would be to just symlink : http://stackoverflow.com/questions/954560/what-does-git-do-to-files-that-are-a-symbolic-link 

This way when you are editing `common` files "which project you are working on" gets driven by the file system and not our code.

+ves:
* Clear what active project is from the file path. Don't need to come up with hacky locating of *relevant* `tsconfig.json` files for `common`. 
* Don't have to deal with possible duplicates as in "errors from project `client` as well as errors from project `server`"

-ves:
* You need to open and save the file twice if you want the change to take place for both client / server projects. This is a big negative as it kills "just start coding" philosophy. 

@fdecampredon / @derekcicerone do you have a suggestion in this area?

**Comment by derekcicerone** [comment]
We've tried both approaches actually: before the Eclipse plug-in supported multiple projects, we just used symlinks (like bower link) to make it work. Then we added explicit support though honestly we haven't done anything that makes it better than the symlinks so far.

**Comment by csnover** [comment]
> You need to open and save the file twice if you want the change to take place for both client / server projects. This is a big negative as it kills "just start coding" philosophy. 

Using the same module format (AMD or, maybe eventually, ES) on client and server doesn’t have this problem, nor does running a watcher or Node.js server for e.g. browserify if you build out to CJS. Why would you try to shove this into code intel plugin for Atom?

**Comment by basarat** [comment]
@csnover that is the answer that I was looking for. A single project for client + server + test, is that the recommendation? If so then the whole of milestone 3 https://github.com/TypeStrong/atom-typescript/milestones/ can go away.

**Comment by basarat** [comment]
> A single project for client + server

I see no way of achieving this with `outDir`. Perhaps `outDir` is a bad idea.

**Comment by basarat** [comment]
Also source map line numbers are *wrong*. Everything is pointing to line `6` (the last line in the file). 

![image](https://cloud.githubusercontent.com/assets/874898/6243490/bbab5208-b796-11e4-8296-f25431cb6f24.png)

My fault. I really didn't expect this to work. 
![image](https://cloud.githubusercontent.com/assets/874898/6243501/e6171e00-b796-11e4-953c-04f2549d46de.png)

**Comment by basarat** [comment]
A loader seems to be the only way to get a reliable sourcemap with correct line numbers
![image](https://cloud.githubusercontent.com/assets/874898/6243997/26aacdea-b7a1-11e4-8f73-9283bce192dc.png)


TODO: investigate error reporting on Build, Add an *no emit js* option under `tsconfig:atom:emit:boolean`

**Comment by basarat** [comment]
This issue is too old and thus closing. Some portions of the concerns here will be delt with #492 :rose:
