### ISSUE TITLE
rewriteTsConfig no more updates tsconfig

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [TypeStrong/atom-typescript#921]
setup:
win10
atom 1.6.2
atom-typescript 8.8

2 days ago I used filesGlob to add files to the files array and it worked and now the whole rewriting has stopped and what bothers me even more is that I do not get any errors or anything so I really have no idea where to look for a fix

my tsconfig:

```
{
    "filesGlob": [
        "./app/**/*.ts",
        "./calendar_view/**/*.ts",
        "main-config.ts"
    ],
    "compilerOptions": {
        "target": "es5",
        "experimentalDecorators": true,
        "module": "amd",
        "moduleResolution": "node",
        "isolatedModules": false,
        "jsx": "react",
        "emitDecoratorMetadata": true,
        "declaration": false,
        "noImplicitAny": false,
        "noImplicitUseStrict": false,
        "removeComments": true,
        "noLib": false,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": true
    },
    "exclude": [
        "typings/main",
        "typings/main.d.ts"
    ],
    "compileOnSave": true,
    "buildOnSave": false,
    "atom": {
        "rewriteTsconfig": true
    }
}
```

my folder structure 
![image](https://cloud.githubusercontent.com/assets/6378638/14489520/fbafa076-016d-11e6-96d9-678441cdb864.png)

**Comment by deevus** [comment]
Same problem here. `tsconfig.json` isn't updating on save. 

win10
atom 1.8.0-beta3
atom-typescript 8.10.1

**Comment by koloboid** [comment]
The with 11.0.1, Linux, Atom 1.15.0
Have the same issue on multiple installs
It's really annoying, we had to downgrade (apm install atom-typescript@10.1.15) to get it work.

**Comment by Forestdev** [comment]
Same on MacOS Sierra Version 10.12.4

**Comment by guncha** [comment]
`rewriteTsconfig` feature was removed because it's no longer necessary. Typescript compiler now supports globs using `include` and `exclude` so you should use those to configure your project.

https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by CindySLiu** [comment]
Can anyone explain what "atom" property is in tsconfig? I searched it on internet on tsconfig schema. I cannot find this property. 

Thanks in advance!!!
