### ISSUE TITLE
Better user experience for targeting release/local version of typescript

### ISSUE THREAD

**Issue by leonyu** [TypeStrong/atom-typescript#922]
`atom-typescript` is based off `ntypescript` which is closer to nightly. As TypeScript is gaining popularity, the project should consider make it easier to target release/local version of typescript instead of `ntypescript`/nightly. Given the next release is 2.0, which likely going to have significant breaking changes, it might save users of `atom-typescript` a lot of headaches to have the default compiler be pointed to release version or their local version. 

Currently there is at least the following difference between nightly and release: 

``` typescript
const mixin = {
  mixinMethod() {
    return this.props;
  }
};
```

Error in nightly here because `this` is inferred as the `{ mixinMethod: Function }` in 2.0; however, it is inferred as `any` in 1.8.  

While it is possible to manually set `typescriptServices`, i think we should make it easier to target either release or local version

Release version can probably be done by bundling `typescript` along side with `ntypescript`. Local installation can probably be done by detecting location of global `node_module` or `tsc` via shell command.

**Comment by iamolivinius** [comment]
I'd love to see that happen, too!

I think atom-typescript should give you the same result as you'd get from your tsc command line compiler. 

A nice option would be "use local installation over the global one" or "use global installation only".
