### ISSUE TITLE
custom `typescriptServices` still references `lib.d.ts` from `ntypescript`

### ISSUE THREAD

**Issue by leonyu** [TypeStrong/atom-typescript#923]
After setting a custom `typescriptServices`, `atom-typescript` still references `lib.d.ts` from `ntypescript`. 

This causes incompatibility when the versions are significantly different.

**Comment by pcan** [comment]
Any news about this? Visual Studio allows this kind of customization, see [here](https://github.com/Microsoft/TypeScript/wiki/Dev-Mode-in-Visual-Studio#using-a-custom-language-service-file). Another inputbox in the settings pane (like the one for `typescriptServices`) should be enough, right?
