### ISSUE TITLE
End bracket highlighting fails on curly brackets in space

### ISSUE THREAD

**Issue by 0815fox** [TypeStrong/atom-typescript#925]
See screenshot. The curly bracket inside the string is marked as ending bracket. However, syntax highlighting itself does not fail on that (inside the string is a Base85 encoded value). Probably this happens as well with square and round brackets...
![snapshot2](https://cloud.githubusercontent.com/assets/8955528/14529342/64bb47aa-0254-11e6-9c64-d30c23c557c5.jpeg)

**Comment by basarat** [comment]
Indeed. Please raise an issue here : https://github.com/atom/bracket-matcher :rose:
