### ISSUE TITLE
Resizable / Hide-able Console Palette

### ISSUE THREAD

**Issue by jpdevries** [TypeStrong/atom-typescript#928]
I understand the point of TypeScript is to be strict on warnings, but on an 11" MacBook Air the warning palette takes up too much vertical space. There doesn't seem to be a way to collapse, hide, or detach it. I think it would be really nice to be able to detach it to another tab.

![](http://j4p.us/2E342z0S1a0w/Screen%20Shot%202016-04-18%20at%201.58.48%20PM.png)

**Comment by basarat** [comment]
That is not our panel. Its linters https://github.com/steelbrain/linter :rose:
