### ISSUE TITLE
Find all references and peek definition feature

### ISSUE THREAD

**Issue by Jonatthu** [TypeStrong/atom-typescript#931]
Does the atom-typescript package offers this feature?
Does other package offer this kind of feature for ts files?
Need something like this.

![image](https://cloud.githubusercontent.com/assets/3742176/14663628/d7c22cce-0677-11e6-96cc-f479f9fccf13.png)

**Comment by basarat** [comment]
We have `goto definition` and `find references`. But neither are inline like vscode. As far as I know there aren't any other functional atom + typescript packages. :rose:

FWIW I plan to add inline view into [alm.tools](http://alm.tools/) It already has it *full screen* but `peek` style inlining would be nice 

![](https://raw.githubusercontent.com/alm-tools/alm-tools.github.io/master/screens/findReferences.gif)

Its not hard to do but I'll wait a bit more for monaco to npm package before doing it in alm though :rose:
