### ISSUE TITLE
Ability to hide the atom-typescript status bar

### ISSUE THREAD

**Issue by tomduncalf** [TypeStrong/atom-typescript#932]
I would like to hide the `atom-typescript` status bar (i.e. the top bar in the image below) entirely, as I don't use it and it takes up screen estate (and sometimes gets into a weird "flickering" state when typing).

![image](https://cloud.githubusercontent.com/assets/5458070/14707631/908f01dc-07bd-11e6-9f1d-102ca495e5bd.png)

Is there a way to remove it? If not, would a PR to add the option to hide it be accepted?

**Comment by antoinerey** [comment]
You can customize pretty much everything in Atom, the appearance is, of course, included. All you have to do is add this to your custom stylesheets.

``` css
.atomts {
  display: none;
}
```

This will completely hide the bottom bar. But you can also just hide some parts by modifying the CSS selector. This is CSS after all... :D

**Comment by tomduncalf** [comment]
I never even thought Atom could have custom stylesheets! Amazing, thanks :)

**Comment by tomduncalf** [comment]
For anyone else who would like to do the same:

1. Open up your custom stylesheet (`Atom > Stylesheet...` on Mac)
2. Add the following at the bottom of the file:

```
atom-panel.bottom .atomts {
    display: none !important;
}
```

Thanks for the help @antoinerey, I had kind of forgotten Atom was all HTML + CSS + JS until now, so very impressive :)

**Comment by sompylasar** [comment]
Now the element is `<ts-status-panel>` so to hide it, a different selector is required:
```
ts-status-panel {
  display: none !important;
}
```
