### ISSUE TITLE
Property decorator breaks syntax highlighting

### ISSUE THREAD

**Issue by maxleiko** [TypeStrong/atom-typescript#934]
When using `PropertyDecorator`, if those decorators are wrapped in a function, then you lose the syntax highlighting on the whole property line:

![atom-typescript-decorator-fail2](https://cloud.githubusercontent.com/assets/834945/14743163/865f75c8-08a0-11e6-9f85-1517ba081858.png)

Without any decorator it works fine:

![atom-typescript-decorator-fail](https://cloud.githubusercontent.com/assets/834945/14743167/8a4f02c0-08a0-11e6-9ae0-b32c8178f64c.png)

And the weird thing is that "object" decorators do not break syntax highlighting:

![atom-typescript-decorator-fail3](https://cloud.githubusercontent.com/assets/834945/14743152/7a09ee20-08a0-11e6-8f3a-80423e96c45e.png)

With a function decorator, the whole property line appears as a **meta.method.declaration.ts**

**Comment by basarat** [comment]
Please report upstream :rose: https://github.com/TypeStrong/atom-typescript/blob/master/docs/grammar.md#cson-grammar
