### ISSUE TITLE
Bug flagged when using Visual Studio Code & Sublime Text but not with atom-typescript

### ISSUE THREAD

**Issue by jeffschwartz** [TypeStrong/atom-typescript#935]
All apps are current.

The following code compiles clean using atom-typescript:

``` typescript
interface PreambleGlobal {
    preamble: any;
}
let preambleGlobal: Window | NodeJS.Global = typeof window === "object" && window || global;
let pGlobal: PreambleGlobal = <PreambleGlobal>preambleGlobal;
```

Image of Atom
![atom-not-showing-error](https://cloud.githubusercontent.com/assets/271288/14764466/ca676672-0986-11e6-8183-f82c1d586a53.png)

However, when using either Visual Studio Code or Sublime Text the above code generates a compiler error:

sanitycheck.ts(5,31): error TS2352: Neither type 'Window | Global' nor type 'PreambleGlobal' is assignable to the other.
  Type 'Global' is not assignable to type 'PreambleGlobal'.
    Property 'preamble' is missing in type 'Global'.

Image of Visual Studio Code
![vscode-showing-error](https://cloud.githubusercontent.com/assets/271288/14764475/1723756e-0987-11e6-825a-df3091c25945.png)

Image of Sublime Text
![sublime-showing-error](https://cloud.githubusercontent.com/assets/271288/14764512/3e021cac-0988-11e6-8174-7238a83f271e.png)

**Comment by basarat** [comment]
Please try latest. Its highlighting on my system

![image](https://cloud.githubusercontent.com/assets/874898/14765980/7c87db28-0a3d-11e6-936c-62b7b63ad9bd.png)

Will reopen if you still have issue. I see you have `5 updates` to apply :rose:

**Comment by jeffschwartz** [comment]
@basarat thanks for the quick response. I just installed the latest atom-typescript package so I am currently at v8.9.1 (please see image below). With the latest installed the offending line of code is still not being flagged:

Image of atom-typescript v8.9.1
![screen shot 2016-04-24 at 7 33 33 am](https://cloud.githubusercontent.com/assets/271288/14767264/a60795ea-09ef-11e6-8843-3a783eae50b0.png)

My tsconfig.json is as follows:
![screen shot 2016-04-24 at 7 40 49 am](https://cloud.githubusercontent.com/assets/271288/14767299/0cfc38fa-09f0-11e6-89a7-daa28edfda67.png)

Also, here's a list of my globally installed Node packages, including typescript:
![screen shot 2016-04-24 at 7 46 13 am](https://cloud.githubusercontent.com/assets/271288/14767333/d4fdf456-09f0-11e6-8729-05244c7b381c.png)

I'm on a Mac running OS X 10.9.5.

**Comment by basarat** [comment]
> With the latest installed the offending line of code is still not being flagged:

Is any code being flagged? Try `var foo:number = "hello"`

**Comment by jeffschwartz** [comment]
Just to be on the safe side I just did:
apm uninstall atom-typescript
apm install atom-typescript

Yes, other code is being flagged:
![screen shot 2016-04-24 at 8 00 54 am](https://cloud.githubusercontent.com/assets/271288/14767439/dce987dc-09f2-11e6-8e64-b815ffd23e65.png)

**Comment by jeffschwartz** [comment]
Also, just to be safe, I disabled linter-tslint thinking there might be a conflict but it didn't have any affect :(

**Comment by jeffschwartz** [comment]
Just in case it helps, here is a list of my atom packages generated using apm list --packages:
[packages.txt](https://github.com/TypeStrong/atom-typescript/files/233410/packages.txt)

**Comment by jeffschwartz** [comment]
btw when I run tsc --p tsconfig.json the compiler flags the error:

```bash
specs/sanitycheck.ts(5,31): error TS2352: Neither type 'Window | Global' nor type 'PreambleGlobal' is assignable to the other.
  Type 'Global' is not assignable to type 'PreambleGlobal'.
    Property 'preamble' is missing in type 'Global'.
```
