### ISSUE TITLE
Support auto-indent/automatically closing elements?

### ISSUE THREAD

**Issue by cafreeman** [TypeStrong/atom-typescript#936]
Does atom-typescript support any kind of real-time formatting for `.tsx` files? In JSX files, I get indentation, new-lines, and and closing tags automatically, but it seems like none of that is working with tsx files.

Admittedly, I can force Atom to use a different grammar for tsx files and all of the automatic features come back, but then you lose any typescript-linting. Is there a way to have both?

**Comment by basarat** [comment]
> and all of the automatic features come back

Which grammar. If we copy paste their settings file https://github.com/TypeStrong/atom-typescript/blob/master/settings/language-tsx.cson we might get the same result :rose:

**Comment by cafreeman** [comment]
I've had the best luck with using the grammar from Atom's language-babel package:

https://atom.io/packages/language-babel

**Comment by basarat** [comment]
Indeed they are different https://github.com/gandm/language-babel/blob/master/settings/language-babel.json vs. https://github.com/TypeStrong/atom-typescript/blob/master/settings/language-tsx.cson

Bit hesitant. Would prefer it was something from the atom team / atom team maintained

**Comment by cafreeman** [comment]
FWIW, it's one of the most-downloaded packages out there, so I don't imagine it's going anywhere any time soon. 😉
