### ISSUE TITLE
Bad Syntax Highlighting?

### ISSUE THREAD

**Issue by jamescmartinez** [TypeStrong/atom-typescript#937]
This syntax highlighting for TypeScript doesn't look right. I've attached screenshots of the syntax highlighting; the TypeScript screenshot is on the top and the Javascript screenshot is on the bottom.

`Atom 1.7.2`
`atom-typescript 8.9.1`

![screen shot 2016-04-28 at 3 07 05 am](https://cloud.githubusercontent.com/assets/1286597/14882674/b3b92b3e-0cee-11e6-9584-d6652db368f5.png)
![screen shot 2016-04-28 at 3 09 39 am](https://cloud.githubusercontent.com/assets/1286597/14882678/b787629e-0cee-11e6-93ee-1d74ba2d80eb.png)

**Comment by gizmodus** [comment]
+1

**Comment by cafreeman** [comment]
+1

**Comment by dtslvr** [comment]
+1

**Comment by amamut** [comment]
+100

**Comment by basarat** [comment]
We use the official grammar files from Microsoft. Please create an issue there if you want : https://github.com/TypeStrong/atom-typescript/blob/master/docs/grammar.md#cson-grammar :rose:
