### ISSUE TITLE
JSX code in "Find references" feature is not visible

### ISSUE THREAD

**Issue by guncha** [TypeStrong/atom-typescript#939]
I tried to search for an existing issue, but didn't find anything.

A screenshot should make it obvious: 

![image](https://cloud.githubusercontent.com/assets/679632/14959309/b993c1ec-105c-11e6-87f2-53103d69392c.png)

The last two lines in actuality are `ReactDOM.render(<ScrollContainer ...>` and `</ScrollContainer>, container)` so this seems to be a JSX issue. I'm using the latest version of atom-typescript `8.9.1` with Atom `1.7.3`.

Any pointers for this one?

**Comment by basarat** [comment]
> Any pointers for this one?

I've known this for a while but was lazy to fix it as no one reported. Fixed it now https://github.com/TypeStrong/atom-typescript/commit/457f2fbf078c7bd0763952dd0e31dfa812798172 

Released : https://github.com/TypeStrong/atom-typescript/releases/tag/v8.10.1 :rose:
