### ISSUE TITLE
using ?-Operator + backticks + special charactar => Syntax Highlight Error

### ISSUE THREAD

**Issue by alexwall** [TypeStrong/atom-typescript#942]
<img width="350" alt="bildschirmfoto 2016-05-07 um 10 04 08" src="https://cloud.githubusercontent.com/assets/316469/15091014/6f270546-143b-11e6-9ba8-df178330aac0.png">
<img width="330" alt="bildschirmfoto 2016-05-07 um 10 04 21" src="https://cloud.githubusercontent.com/assets/316469/15091017/6f5c197a-143b-11e6-8a80-621c1c364cc9.png">
<img width="316" alt="bildschirmfoto 2016-05-07 um 10 04 52" src="https://cloud.githubusercontent.com/assets/316469/15091018/6f5e344e-143b-11e6-9c70-c1b86a3677e5.png">
<img width="363" alt="bildschirmfoto 2016-05-07 um 10 05 13" src="https://cloud.githubusercontent.com/assets/316469/15091015/6f5b62c8-143b-11e6-929b-d33eef175ed9.png">
<img width="343" alt="bildschirmfoto 2016-05-07 um 10 05 42" src="https://cloud.githubusercontent.com/assets/316469/15091016/6f5bd35c-143b-11e6-849a-f30335381c72.png">

**Comment by michael-yx-wu** [comment]
I've encountered this as well. If you have large file, this renders the rest of it very hard to read.

**Comment by marktani** [comment]
Same problem here. The rest of the file is highlighted as a string.
