### ISSUE TITLE
Wish: Define output-directory for transpiled files

### ISSUE THREAD

**Issue by hmrc87** [TypeStrong/atom-typescript#944]
It would be great if I could define an output directory for the js and source-map files. Per default they are located right next to the TypeScript-Files. It would be nice to define a directory relative to the TypeScript file or a directory relative to the ProjectRoot.

**Comment by 2426021684** [comment]
Edit tsconfig.json

**Comment by hmrc87** [comment]
Thank you! I ended up setting the "outDir"-Option in tsconfig.json compiler options
