### ISSUE TITLE
formatCodeOptions are ignored

### ISSUE THREAD

**Issue by tomitrescak** [TypeStrong/atom-typescript#947]
Whatever I specify in formatcodeoptions if tsconfig is ignored during transpilation.

For example specifying ""indentSize": 2" is ignored and typescript keeps transipiling with 4.

Thanks

**Comment by basarat** [comment]
> For example specifying ""indentSize": 2" is ignored

The `formatCodeOptions` are to format TypeScript (and not the generated JavaScript). Apprently the generated JavaScript is always 4 indent (you can double check / feature request from the team if you want https://github.com/Microsoft/TypeScript/issues/new) :rose:
