### ISSUE TITLE
Suggestion: Please remove the context sensitive nature of Build in the command palette

### ISSUE THREAD

**Issue by jeffschwartz** [TypeStrong/atom-typescript#950]
Currently you have to have a .ts or d.ts file open in the editor and it has to have the input focus in order to run Build from the command palette (perhaps other typescript specific commands also). However, Build should always be available from the command palette anytime there is a tsconfig.json file indicating a typescript project has been defined/declared. Perhaps there is a better way but relying on the presence of tsconfig.json is immediately obvious. IMHO it is very annoying and distracting having to first open a .ts file just to be able to build a project.
![screen shot 2016-05-13 at 6 39 00 pm](https://cloud.githubusercontent.com/assets/271288/15263671/1bb4923a-193a-11e6-8b5b-4e0a6bd9271b.png)

**Comment by basarat** [comment]
> IMHO it is very annoying and distracting having to first open a .ts file just to be able to build a project

Quite commonly people have multiple tsconfig.json (including some from node_modules). Which one should we build is a bit of a puzzle unless one has a file open (even then it can be a puzzle if multiple projects reference the file ... we just use the last one the user uses which is generally the right one). 

Something like [the alm project selector](https://basarat.gitbooks.io/alm/content/features/omni-search.html#project-search) can help mitigate it a bit 

![](https://raw.githubusercontent.com/alm-tools/alm-tools.github.io/master/screens/projectSearch.gif)

That is being discussed here : https://github.com/TypeStrong/atom-typescript/issues/910 

Closing as there is a technical limitation here and the project discussion has started here : https://github.com/TypeStrong/atom-typescript/issues/910 Feel free to voice / bounce ideas here or there even after closing :rose:
