### ISSUE TITLE
"strictNullChecks": true breaks "outDir" option

### ISSUE THREAD

**Issue by alexwall** [TypeStrong/atom-typescript#953]
When I use this option 
`"strictNullChecks": true`

all Javascript files will be created in the same folder where the typescript file is.
The tsconfig option 
`"outDir":`
will be ignored

**Comment by ahc-andrew** [comment]
I can't replicate this.  It works for me with this config.

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "outDir": "out",
    "target": "es5",
    "strictNullChecks": true
  },
  "files": [
    "src/Engine.ts",
    "src/Parameters.ts",
    "typings/tsd.d.ts"
  ]
}
```
  Can you share your config?

Are you sure your tsconfig file is being used? Try breaking it somehow

**Comment by alexwall** [comment]
Maybe it was fixed or I really had broken the tsconfig. However it seams to work right now.
