### ISSUE TITLE
typescript format not working

### ISSUE THREAD

**Issue by lcurrens** [TypeStrong/atom-typescript#959]
Update - after removing trailing comma after formatOnSave, it seems to be working now.
----------------------------------------------------------------------------------------
Format with ctrl-alt-l and format on save does not seem to work at all, it's not doing anything.

I have the following tsconfig.json.  Am I missing something?

{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  },
  "exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts"
  ],
  "formatCodeOptions": {
    "indentSize": 4,
    "tabSize": 4,
    "newLineCharacter": "\r\n",
    "convertTabsToSpaces": true,
    "insertSpaceAfterCommaDelimiter": true,
    "insertSpaceAfterSemicolonInForStatements": true,
    "insertSpaceBeforeAndAfterBinaryOperators": true,
    "insertSpaceAfterKeywordsInControlFlowStatements": true,
    "insertSpaceAfterFunctionKeywordForAnonymousFunctions": false,
    "insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
    "placeOpenBraceOnNewLineForFunctions": false,
    "placeOpenBraceOnNewLineForControlBlocks": false
  },
  "atom": {
    "formatOnSave": true,
  }
}

**Comment by basarat** [comment]
> Update - after removing trailing comma after formatOnSave, it seems to be working now.

Yup. Invalid json => invalid tsconfig => no typescript support :rose: FWIW you should have seen an error in the error panel :rose:
