### ISSUE TITLE
"Go to Declaration" in right-click menu does not trigger "TypeScript: Go to Declaration"

### ISSUE THREAD

**Issue by mikeguta** [TypeStrong/atom-typescript#96]
I'm talking about the right-click menu in Atom v0.180.0 on Windows 7 with atom-typescript v0.59.0. Ctrl+B is working fine albeit very slow in some cases.

**Comment by basarat** [comment]
Are you sure it's atom ts's menu item. We didn't add it. I'll check if it's there by default. I doubt it. Thanks for using ❤️

**Comment by basarat** [comment]
That menu item is *not from us* but it does exist on my system as well. You can see I have atomts disabled : 

![image](https://cloud.githubusercontent.com/assets/874898/6258085/d19c9b16-b819-11e4-95a4-ac2937c1ea31.png)

**Comment by basarat** [comment]
Alright. That menu item is a known issue : https://github.com/atom/language-php/issues/14 

comes from the symbols view package : https://github.com/atom/symbols-view/issues/9

**Comment by basarat** [comment]
Alright. I can support this but know that it will not be "under the mouse" but really where the last "cursor" was left : https://github.com/atom/symbols-view/issues/9#issuecomment-74969777 

I'd be happier to disable the menu item for TS really.

**Comment by mikeguta** [comment]
Thank you, Works great!
