### ISSUE TITLE
Add import from statement misses things

### ISSUE THREAD

**Issue by buehler** [TypeStrong/atom-typescript#961]
Hey guys!

I ran into an error (or is it misusage from my side?) when using your package in atom. I tried to import multiple things from a file and the quick fix just does not find anything else beside a class.

The quickfix feature does not find any exported const, enum, functions, whatever.

Also, when I have two classes or anything exported in a file, that's not recognized as well.

And as a bonus question :-)
Are imports optimized?

e.g.
```typescript
import {Foo} from 'Foo';
import {Bar} from 'Foo';

// should become

import {Foo, Bar} from 'Foo';
```

Cheers
Chris

**Comment by basarat** [comment]
> Are imports optimized

Nope. 

> The quickfix feature does not find any exported const, enum, functions, whatever.

Yup. Its really simple and only checks for filepath : https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/lang/fixmyts/quickFixes/addImportStatement.ts  / https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/lang/modules/getPathCompletions.ts

Closing this just to keep the queue shorter for the next fellow :rose:
