### ISSUE TITLE
TextEditor.screenPositionForPixelPosition is deprecated.

### ISSUE THREAD

**Issue by JVieraLedo** [TypeStrong/atom-typescript#963]
This is now a view method. Call TextEditorElement::screenPositionForPixelPosition instead.

```
TextEditor.screenPositionForPixelPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:3104:12)
HTMLDivElement.<anonymous> (/Users/gstock/.atom/packages/atom-typescript/dist/main/atom/tooltipManager.js:35:31)
HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by ramk18** [comment]
Is anyone working on this?

**Comment by FlawaCLV** [comment]
+1

**Comment by flpms** [comment]
+1

**Comment by gluons** [comment]
Since May 2016. Oh! Now Feb 2017. Really long. Did anyone see this issue?

**Comment by mateusz-90** [comment]
I'm getting this issue in Atom 1.14.2 x64
`TextEditor.screenPositionForPixelPosition - /opt/atom/resources/app.asar/src/text-editor.js:3532:12
HTMLDivElement.<anonymous> - /home/nullbyte/.atom/packages/atom-typescript/dist/main/atom/tooltipManager.js:35:31
HTMLDivElement.dispatch - /home/nullbyte/.atom/packages/atom-typescript/node_modules/jquery/dist/jquery.js:4435:9
HTMLDivElement.elemData.handle - /home/nullbyte/.atom/packages/atom-typescript/node_modules/jquery/dist/jquery.js:4121:28`

**Comment by koba-ninkigumi** [comment]
https://github.com/ionide/ionide-atom-fsharp/issues/259

Is this a hint?

**Comment by bradrich** [comment]
+1 Anyone?... Bueller?...

**Comment by koba-ninkigumi** [comment]
I fixed this issue -> 

https://github.com/TypeStrong/atom-typescript/pull/1197
https://github.com/TypeStrong/atom-typescript/pull/1201

**Comment by guncha** [comment]
That's right, thanks to @koba-ninkigumi this should be fixed in the latest version. Please re-open if you find it still being an issue.
