### ISSUE TITLE
Autocomplete Not Working

### ISSUE THREAD

**Issue by JoshMDiaz** [TypeStrong/atom-typescript#964]
Autocomplete doesn't seem to be working for me. I have updated to the latest version. Is anyone else having this issue?

**Comment by Maistho** [comment]
It's probably #332

**Comment by JoshMDiaz** [comment]
That was it! Thanks

**Comment by tobiasfiechter** [comment]
Since I upgraded Atom to 1.17 I have no atocomplete at all for typescript.
