### ISSUE TITLE
Syntax highlighting sometimes depends on semicolons

### ISSUE THREAD

**Issue by johnchristopherjones** [TypeStrong/atom-typescript#966]
TypeScript syntax highlighting sometimes breaks when semicolons are omitted.  Attached are two screenshots and example code that produces the error.  Presently GitHub syntax highlighting for TypeScript produces the same error.

Note the highlighting for both the word "statuses" and the string literal "started".

## Without Semicolon:

```TypeScript
export class StatusSelector {
  @Output() select = new EventEmitter()
  statuses = ["started", "completed"]
}
```

![statuses_without_semicolon](https://cloud.githubusercontent.com/assets/865836/15724645/092010dc-2816-11e6-8eb5-cc2a8cb47936.png)

## With Semicolon:
```TypeScript
export class StatusSelector {
  @Output() select = new EventEmitter();
  statuses = ["started", "completed"]
}
```

![statuses_with_semicolon](https://cloud.githubusercontent.com/assets/865836/15724653/0e5518fe-2816-11e6-93b9-dbfdbfe46748.png)

Edit: Revised screenshots

**Comment by michasko** [comment]
Same thing happens for me after every `@`-keyword (`@Input`, `@Output` etc.).

How it looks like:
![screen-1](https://cloud.githubusercontent.com/assets/3853033/16108285/8df0d50c-33a2-11e6-9d66-1079cfa7f1f4.png)
how I think it should look:
![screen-2](https://cloud.githubusercontent.com/assets/3853033/16108289/950e3d8e-33a2-11e6-8067-a8aa513e633c.png)

**Comment by basarat** [comment]
Please raise here : https://github.com/Microsoft/TypeScript-TmLanguage/issues :rose:

Docs https://github.com/TypeStrong/atom-typescript/blob/master/docs/grammar.md#cson-grammar
