### ISSUE TITLE
Performance issues?

### ISSUE THREAD

**Issue by dgbonomo** [TypeStrong/atom-typescript#968]
I've been using my laptop for some coding and I keep running into massive performance issues with atom-typescript (I've tried disabling it, and the problems disappeared).

I can be typing and Atom's editor will completely freeze/hang for up to 20 seconds, sometimes even longer.  During that time, CPU use will spike and one of the Atom processes will take up close to 1GB of RAM until both suddenly level off again and Atom responds again like nothing ever happened.  This doesn't seem to affect system UI elements like the menu, although closing Atom during this time also doesn't work.

I'm not sure why this is so, but these extended freezes can happen every minute or every few minutes and it's getting to the point where it's just excrutiating to get any work done - so I'd love some insight or see if something could be done there.

Things worth pointing out (off the top of my head)
- These lock-ups haven't happened on my desktop machine
- This has happened even on tiny files (ie a handful of lines; although I'll have other files open too)
- My "pending request" always skyrockets, it's easily at 400 to 500

Developer Tools screenshot:
- http://i.imgur.com/LtFly5b.png

Laptop details:
- Windows 10 Home 64-bit
- Intel Core i7-2670QM @ 2.2 GHz
- 8GB RAM

**Comment by mminutel** [comment]
I get this as well. Right now it has been frozen for over five minutes. I can confirm that disabling this package prevents this from happening. My "pending requests" seems to max out at 300. My CPU utilization doesn't spike as far as I can tell, but there is an Atom background process that is taking up almost a Gig. This is happening on my desktop rig that has a Skylake i5 and 16GB of RAM.
