### ISSUE TITLE
A lot of Pending Requests

### ISSUE THREAD

**Issue by AndersonDev** [TypeStrong/atom-typescript#969]
Hi. I am using Angular 2 and Webpack for developing an Atom with atom-typescript. On every save I have increasing of pending requests. I tried to find solution, however they are old...

![image](https://cloud.githubusercontent.com/assets/6890368/15802187/2034c5de-2ab3-11e6-8ec7-51b4f018b390.png)

Thanks!

**Comment by DNRN** [comment]
I have a similar issue. Please help us on this one, because working in Atom right now is a bit frustrating :)

**Comment by nikhildev** [comment]
Do you mind posting your tsconfig file?

**Comment by pstawinski** [comment]
I have same problem. My project is build on: https://github.com/preboot/angular2-webpack with almost no changes... So my tsconfig is:
```
{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "noEmitHelpers": true
  },
  "compileOnSave": false,
  "buildOnSave": false
}
```

**Comment by nikhildev** [comment]
I had the same issue. Basically, the plugin wasn't able to find my ts files and thats why the pending requests were getting queued up. I got around it by including

```
"filesGlob": [
      "**/*.ts"
    ],
```

and 

```
"atom": {
    "rewriteTsconfig": true
  }
```

In my tsconfig. This will rewrite the tsconfig file by scanning through your application for .ts files. Also, make sure that the tsconfig is the root folder of your app src and does not have node_modules as any child.

**Comment by AndersonDev** [comment]
@DNRN @nikhildev @pstawinski the solusion is very easy:
### tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "buildOnSave": false
}
```

We **add**:
```
"exclude": [
    "node_modules"
  ]
```
and compiler ignore the tone of aditional files.

**Comment by pstawinski** [comment]
Thank you!

**Comment by robyoder** [comment]
Excluding node_modules seemed to help briefly, but after a few seconds, I'm back with the same kind of errors:

<img width="554" alt="screen shot 2016-07-18 at 6 45 19 pm" src="https://cloud.githubusercontent.com/assets/622513/16935749/2d860bc4-4d1f-11e6-969d-3b8a830ebc52.png">

**Comment by robyoder** [comment]
Related issues: #968, #1037. There are several old related issues as well (#728, #760, #556, #349), but they seem to have been resolved at one point and now the problem is back. @basarat, any ideas?

Here are my latest errors:

<img width="517" alt="screen shot 2016-08-05 at 1 40 34 pm" src="https://cloud.githubusercontent.com/assets/622513/17448562/3d3e73fc-5b12-11e6-9382-174fbe00c2fe.png">

**Comment by robyoder** [comment]
So, another data point. I originally had `tsconfig` referencing files like this:

```json
	"files": [
		"src/ts/main.ts",
		"typings/index.d.ts"
	]
```

My `main.ts` file is the entry point and all the other files are referenced via `import`s. I thought that would be the best way, and I would avoid spending time compiling files that I wasn't currently referencing anywhere. If I change that to this, though, it seems to work fine:

```json
	"filesGlob": [
		"src/ts/**/*.ts",
		"typings/index.d.ts"
	]
```

This apparently lets TS build its index much faster and seems to be the recommended way. My question is, though, is my first way supposed to be supported?

**Comment by intellix** [comment]
I'm also quite confused about how different the performance is between atom-typescript and VSCode with an angular-cli generated project (I haven't tried any other project though tbh).

I have a component like this:

```ts
```

**Comment by aderbas** [comment]
Any solution for this? I am having the same problem in a Anguar 2 project, for me Infinity Pending Requests and the number endless increases. 

tsconfig.json
```
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  },
  "exclude": [
    "node_modules"
  ]
}
```
