### ISSUE TITLE
Editor not responding after install atom-typescript

### ISSUE THREAD

**Issue by Mo-la-machette** [TypeStrong/atom-typescript#971]
Hello, 
I have a problem for one week, When i launch Atom, the editor send a message : "Editor is not responding". so i have launch atom in safe mode and here, no problem. I have reinstall atom-typescript and just after the install finish, same error appear. 
Here my tsconfig.json : 
`{<br>
  "compilerOptions": {
    "target": "es5",
    "outDir":"telemedecine-app/app",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "compileOnSave":false,
  "exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts",
    "telemedecine-app/node_modules",
    "src/lib"
  ]
}`
PS : No problem of freeze with atom-typescript before this week.
Thank you.

**Comment by codeRebelBase** [comment]
We're also experiencing regular "Editor is not responding" while using atom-typescript on an angular2 project.

**Comment by yk64** [comment]
I'm experiencing the same with angular2 projects.

**Comment by MTyson** [comment]
Also seeing this with typescript files in angular2 project.

**Comment by waiwaiku** [comment]
My project is ng2 , use atom-typescritpt and open atom respond is so long.
