### ISSUE TITLE
Compile on save on different directory

### ISSUE THREAD

**Issue by Parziphal** [TypeStrong/atom-typescript#975]
The Compile on save feature is really nice, now I don't need to transpile the code with gulp or anything. But writing the js files along the ts files feels a little messy to me. Any chance the output dir could be changed?

**Comment by basarat** [comment]
> Any chance the output dir could be changed?

Use `compilerOptions`. `outDir` in your tsconfig.json :rose:

**Comment by Parziphal** [comment]
Works perfectly. Thanks!
