### ISSUE TITLE
Feature Request: tsx/jsx comment

### ISSUE THREAD

**Issue by normalser** [TypeStrong/atom-typescript#977]
Right now when I use `cmd+/` in tsx file in jsx part of the file:

eg. on second line of:

```
<div>
  <div>...</div>
</div>
```

then it will convert it to

```
<div>
  // <div>...</div>
</div>
```

It would be awesome if it could turn it into 

```
<div>
{/* <div>...</div> */}
</div>
```

Thanks for the great plugin

**Comment by dsifford** [comment]
@wallverb See [this discussion](https://discuss.atom.io/t/how-to-create-key-binding-for-inserting-text-in-editor/21718/6).

**Comment by silentcloud** [comment]
+1

**Comment by SilentScope** [comment]
+1

**Comment by JNaftali** [comment]
Bump and +1. The babel package in Atom has managed this. Disappointing that the TS package hasn't kept up.

**Comment by MrOggy85** [comment]
duplication of #844
