### ISSUE TITLE
Idea: have `log` autocomplete to `console.log()`

### ISSUE THREAD

**Issue by AskYous** [TypeStrong/atom-typescript#979]
Hello,

When typing in JavaScript in Atom, if a developer types "`log`", Atom will suggest `console.log()` automatically. But when the JavaScript is transformed into TypeScript, this handy feature is gone. My suggestion is to add this feature.

**Comment by basarat** [comment]
> My suggestion is to add this feature.

Can be done with `snippets` : PR this if you want https://github.com/TypeStrong/atom-typescript/blob/master/snippets/typescript-snippets.cson :rose:
