### ISSUE TITLE
Project Owner Needed

### ISSUE THREAD

**Issue by normalser** [TypeStrong/atom-typescript#980]
Hi,

What is the status of this project? Is it pretty much abandoned ?

**Comment by basarat** [comment]
Sorry about the delay, I had to discuss it with colleagues offline. Their thoughts are very similar to mine. 

* This project needs a new owner, someone who loves TypeScript **and** Atom. I've personally [moved on from atom](http://alm.tools/). Adding all the *new* features in TypeScript as they come out is somewhat of a full time job. We've added long term users of this project that showed interest in helping out as commiters and TypeStrong is happy to take more people if they show sufficient skill / desire to create. [I discussed the internals of the editor to help others as well](https://www.youtube.com/watch?v=WOuNb2MGR4o) :rose: 

* The plugin is still functional for many of us enough that it does most of what it used to do. Many of us use it day to day. If any of us need a feature that isn't here yet, someone would probably add it.

This was previously discussed here as well https://github.com/TypeStrong/atom-typescript/issues/913 :rose:
