### ISSUE TITLE
TSX Closing Tag Formatting

### ISSUE THREAD

**Issue by nickfujita** [TypeStrong/atom-typescript#983]
Closing tags on jsx in tsx files are formatted as offset to the right of the screen and faded. Is this a feature that I can disable, or possibly a bug?

![image](https://cloud.githubusercontent.com/assets/6342442/16160591/f1585ec2-347d-11e6-8cfb-b7d49e3f21ca.png)

Atom v1.8.0
Atom-Typescript v0.8.11
Windows 10

**Comment by basarat** [comment]
Just added to FAQ : https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#syntax-highlighting-is-bad :rose:
