### ISSUE TITLE
Quick fix: import statement for default exports

### ISSUE THREAD

**Issue by nielslyngsoe** [TypeStrong/atom-typescript#985]
Hey guys

I would like to be able to choose an option in the Quick Fix menu that create an import statement but for a default export module.

Currently you can get this:
import {Foo} from 'Foo';

But I would like an option that results in this:
import Foo from 'Foo';

Let me know if you want me to do a Pull Request, but I thought you might have a better way of solving this than my way.

Thanks for the good work

**Comment by robinisaksson** [comment]
+1

**Comment by nycdotnet** [comment]
Please feel free to implement a PR.
