### ISSUE TITLE
Typing enter before a closing bracket results in wrong indentation on new line

### ISSUE THREAD

**Issue by adambuczynski** [TypeStrong/atom-typescript#986]
Ref https://github.com/atom/atom/issues/12013
See example:

![ss](https://www.dropbox.com/s/ydrj3pjiofafwec/wrong%20indentation%20with%20closing%20bracket.gif?dl=1)

When you press `enter` with the cursor positioned just before the closing bracket, the indentation of the new line is one unit off.

This is on Atom 1.10.0-dev-e5a3c9e, OS X 10.11.5.

The simplest example with a closing bracket will work to reproduce this:

```js
    //)
    if (this.date) {
```

Place cursor between the comment slashes and the closing bracket and hit enter. It will move the closing bracket to this position:

```js
    //
  )
    if (this.date) {
```

Note that this happens with both javascript and typescript. I assume the typescript language grammar was built based on the javascript one, and as such probably inherited this bug.

**Comment by basarat** [comment]
> Note that this happens with both javascript and typescript

Indeed. Its this file : https://github.com/TypeStrong/atom-typescript/blob/master/settings/language-typescript.cson copied for langauge-grammar

I've done some fancy stuff in http://alm.tools/ with using the TypeScript language service : https://github.com/alm-tools/alm/blob/7ce9406b6b7c7fca57e9004f6843e6345eadfc24/src/app/monaco/languages/typescript/formatting.ts#L55 but its not easy to port over. So closing for now. If you have a fix in langauge-javascript we'd be happy to accept a pull request to here as well :rose: :heart:
