### ISSUE TITLE
When target is es2015, atom complains 'Cannot find name Promise.'

### ISSUE THREAD

**Issue by t246246** [TypeStrong/atom-typescript#988]
When I write tsconfig.json `"target:es6"`, no problems without `/// <reference ... />` line.  But when I change it to `"target:es2015"`, atom error occurred 'Cannot find name Promise.'

I tried with typings, i.e. `es6-shim/index.d.ts` is under `typings` folder, and `@types`, under `node_modules/@types`. In both case result are the same.

atom 1.8.0 on MacOS X
atom-typescript: 8.11.0
typescript: 1.9.0-dev.20160625-1.0

**Comment by envygeeks** [comment]
@t246246 Try "es5" or "es6" instead of that.

**Comment by t246246** [comment]
According to this https://github.com/Microsoft/TypeScript/issues/5209, es2015 should be allowed as well as es6. So I think this is a bug of atom side.

**Comment by envygeeks** [comment]
@t246246 I agree, that's just what ended up working for me.

**Comment by basarat** [comment]
> So I see no reason target es6 and es2015 behave differently.

Curious. Do they behave differently for you?

**Comment by t246246** [comment]
@basarat: Yes, es6 shows no error, es2015 shows error on Promise.

**Comment by basarat** [comment]
Does it compile on the command line tsc?

**Comment by t246246** [comment]
No error with
```
$ node_modules/.bin/tsc -p tsconfig.json
```
Source is [angular hero demo](https://angular.io/resources/live-examples/router/ts/plnkr.html).

Edit tsconfig.json, install es6-shim type definition with
```
npm install @types/es6-shim
```
and open app/dialog.service.ts with atom.

**Comment by Luminess** [comment]
Have you installed the nodejs typings and kept them up to date? The latest one is 6.0.0 on the dt or env repositories.

**Comment by t246246** [comment]
@Luminess Thank you. That's the very reason. After I install
```
$ npm install @types/node -D
```
error disappears.  (I use node.js v4.4.7, and no longer use `typings` as I've heard it will be deprecated, so the current version is  "@types/node": "4.0.26-alpha".)  One odd thing is that once the error disappeared, it will be never shown after I remove @types/node folder, maybe atom caches it somewhere.

**Comment by t246246** [comment]
Sorry, my mistake. It does not solve the problems.
Still got error when target is es2015.

**Comment by Luminess** [comment]
There's your problem, you can't exclude the typings folder. It has to be included for VSCode, atom-typescript, and tsc to work properly.

**Comment by t246246** [comment]
@Luminess 
You might be right. But when target is es6 and exclude typings folder, atom does not generate error.
So if the behaviour of exclude should be what you wrote, this is a bug, because typings folder is not excluded for atom when target is es6.

**Comment by Luminess** [comment]
Wat? Context please. I don't understand what you mean by "and exclude typings folder". Do you mean "and typings folder is excluded"? Also, what do you mean by "typings folder is not excluded for atom when target is es6".

**Comment by t246246** [comment]
Please read my tsconfig.json setting in my previous comment.
With this setting, typings folder is excluded, but no error shown in atom.
When I change target es6 to es2015, atom shows error.
My point is there should be no difference es6 and es2015.

**Comment by Luminess** [comment]
Can we see the error?

**Comment by t246246** [comment]
![untitled](https://cloud.githubusercontent.com/assets/19387062/16714191/cb56ff7c-46f6-11e6-88fa-2d42faeac21e.png)

**Comment by Luminess** [comment]
[ES2015](http://www.typescriptlang.org/docs/handbook/compiler-options.html) is not even a valid option for the compiler target. ES6 is the highest.

**Comment by t246246** [comment]
Thank you. Your deference is for typescript 1.8. As I said earlier I am using typescript 1.9-dev (now switched to typescript 2.0-dev.)  And as I mentioned earlier (in 3rd message), es2015 should be allowed as well as es6. https://github.com/Microsoft/TypeScript/issues/5209 That issue is closed with merged pull request, so I think it is now implemented.

**Comment by Luminess** [comment]
If it is solved, can you please close this issue?

**Comment by t246246** [comment]
Not solved. Workaround is to use target es6.

**Comment by t246246** [comment]
Typescript 2.0 is out and I see the document https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#user-content-including-built-in-type-declarations-with---lib
Adding 
```
                "lib" : ["es6.promise"],
```
to CompilerOptions would solve this problem.
And here is the desription
```
built-in API declarations were only limited to target: ES6.
```
and it seems to official, so I will close this issue soon later.

**Comment by t246246** [comment]
With atom 1.8.0, error disappears when I add "lib" : ["es2015.promise"].
But with atom 1.9.0-beta, other error occurs "Unknown option: lib" in `tsconfig.json`, and error (on Promise) does not disappears.

It seems lib option is not yet supported, so "Unknown option: lib" is understandable error, but I don't understand why it works with atom 1.8.  It is more complex issue that I thought.

**Comment by myagoo** [comment]
Please mimic TS on this and support es2015 as es6, I'm the last one of my team using atom + atom-typescript and  it bothers my colleagues on VSCode that I had to change target: "es2015" (futureproof) to "es6" (deprecated name)

**Comment by liangtongxie** [comment]
why there also is a same problem when I  change  'target' from  es6 to es5?

**Comment by swinc** [comment]
I can resolve this issue in `tsconfig` with

`"target": "es5"` but also with

`"lib": ["DOM", "ES5", "ScriptHost", "ES2015"]`

(using TypeScript 2.1)

**Comment by basarat** [comment]
> "lib": ["DOM", "ES5", "ScriptHost", "ES2015"]

just `lib: ['dom', 'es6]` https://basarat.gitbooks.io/typescript/content/docs/types/lib.d.ts.html#lib-option (es5 is already contained in es6 and scripthost is not needed) :rose:
