### ISSUE TITLE
not reporting certain compilation errors with noImplicitAny compiler option

### ISSUE THREAD

**Issue by KarateSnoopy** [TypeStrong/atom-typescript#989]
This may be the the same as https://github.com/TypeStrong/atom-typescript/issues/857 but I can't figure it out.  

If I open an atom example project such as \atom-typescript-examples\autoindenttest\tsconfig.json, and add this compile option:

`"noImplicitAny": true,`

then adding this line to a autoindenttext.ts yields a error as expected inside Atom:

`var cache = []; // as expected: error TS7005: Variable 'cache' implicitly has an 'any[]' type.`

running tsc on that folder manually (either released 1.8.10, or latest Version 1.9.0-dev.20160625-1.0) yields the same error as expected.

However if I add this code to:

```
let x : {[index: number]: number} = {};
x['hmm'] = 10;

```

results in auto-typescript finding no compile errors inside Atom, but tsc run manually report this:

`autoindenttext.ts(6,1): error TS7015: Element implicitly has an 'any' type because index expression is not of type 'number'.`

Even if I use ntsc (released ntypescript@1.201606260106.1) it reports the error as expected like just tsc, but I can't figure out how to make atom-typescript see this TS7015 error as reported by ntsc.

I figure this might be caused by stale typescript compiler inside atom-typescript, so I tried opening atom-typescript source in Atom, linking Atom to use the source folder, and upgrading to the latest ntypescript (which is built daily with the latest typescript), and then rebuilding atom-typescript and reloading the Atom window but it didn't help.   Any idea?  Seems like there's something else going on

Thanks,
Jason

**Comment by radarsu** [comment]
Also when we do with option noImplicitAny:
```
let x: {} = {};
x["test"] = "test";
```
Atom-typescript will not rise an error. while ts compiler returns:
`Index signature of object type implicitly has an 'any' type`
