### ISSUE TITLE
CTRL+ALT+L Locks Screen in Ubuntu

### ISSUE THREAD

**Issue by Clay-Ferguson** [TypeStrong/atom-typescript#990]
CTRL+ALT+L is therefore never a good option for an app to use that will ever be run on Ubuntu. I'm looking for a way to reassign that shortcut because without it this plugin becomes pretty useless (or just VERY difficult to use) on Ubuntu.

CTRL+ALT+L is the keybinding that does reformatting of the code, but conflicts with Ubuntu default keybindings.

**Comment by envygeeks** [comment]
`Ctrl`+`Shift`+`L` means nothing to Ubuntu for Logout.  To logout it's `Ctrl`+`Alt`+`Del` or `Ctrl`+`Alt`+`Backspace`.  `Ctrl`+`Alt`+`L` is lock (not logout.)  Your keybinding is **not** a default system keybinding.

**Comment by Clay-Ferguson** [comment]
@envygeeks Yes, CTRL+ALT+L is the lock screen.  Thanks for pointing out the typo in the issue description. It should read "Locks you out in Ubuntu." and it *is* the default system keybinding, which i'm sure is what you meant.

**Comment by envygeeks** [comment]
I said ***your*** keybinding is not the default, not CTRL+ALT+L.  CTRL+SHIFT+L is ***not*** a default keybinding and never will be because CTRL+SHIFT is reserved for applications, but Super+SHIFT is not.  I said exactly what I meant :wink:

**Comment by Clay-Ferguson** [comment]
No, my keybinding IS the default, and therefore CTRL+ALT+L locks the screen.

**Comment by envygeeks** [comment]
@Clay-Ferguson except you said CTRL+SHIFT+L which is what my comments were about, so what point are you trying to make? My comments were based on that, whether you change it later or not does not change the past comments that were made ***before*** that.

**Comment by basarat** [comment]
> CTRL+ALT+L is the keybinding that does reformatting of the code, but conflicts with Ubuntu default keybindings.

Sorry about that. That keybinding came from my usage of JetBrain tools. You are free to map the command to some other key binding in your own config. Or submit a PR that *only* changes the defaults for linux (I'm happy to let you pick the default). Closing for now :rose:
