### ISSUE TITLE
Syntax Highlighting Inside Constructor Function

### ISSUE THREAD

**Issue by haydenJogs92** [TypeStrong/atom-typescript#991]
Hello,

I recently switched to using typescript for an Ionic2/angular2 project.

But I've noticed that it no longer highlights code inside a components constructor: 
![image](https://cloud.githubusercontent.com/assets/16627615/16465727/2c7d262e-3e0e-11e6-95bd-1ad3703368bd.png)

I'm using atom-typescript.

When I was writing in es6, it had no trouble with syntax highlighting inside a constructor.

**Comment by basarat** [comment]
Should not happen. Please provide a code sample. But instead of here, make an issue report at : https://github.com/Microsoft/TypeScript-TmLanguage/issues 

I added this to the faq just now :memo: https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#syntax-highlighting-is-bad :rose:
