### ISSUE TITLE
Since TypeScript now supports filesGlob natively we definitely shouldn't expand it by default

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#992]

**Comment by basarat** [comment]
Of course the user can explicitly toggle it. Just changed the **default** to be false :rose:

**Comment by basarat** [comment]
Released https://github.com/TypeStrong/atom-typescript/releases/tag/v9.0.0 :rose:

**Comment by pwnall** [comment]
native filesGlob support will come in TS 2.0, which is not yet released -- documenting this for other folks who come here with the same question as me.

References:
https://github.com/Microsoft/TypeScript/pull/8841
https://github.com/Microsoft/TypeScript/issues/1927

**Comment by piotrwitek** [comment]
This post can introduce confusion, it implies that TS will have a native filesGlob option support, which is not the case, instead there is "include" which can server similar purpose.

References:
https://github.com/Microsoft/TypeScript-Handbook/issues/334#issuecomment-230184744
https://github.com/Microsoft/TypeScript/pull/5980
