### ISSUE TITLE
atom-typescript can't find tsconfig.json

### ISSUE THREAD

**Issue by jtuu** [TypeStrong/atom-typescript#994]
My project structure is something like this:
- /
  - foo/
    - other/
  - bar/
    - tsconfig.json
    - src/
      - ts/
        - file.ts

This used to work fine until I updated to atom-typescript 9.0.0.
After updating to 9.0.0 it can no longer find tsconfig.json.
`no tsconfig.json`

**Comment by olee** [comment]
Same here!
This is causing me quite some pain right now.

I have a project with client and server (node) sources in the same project but with different roots and different tsconfig.json files:
- `/`
  - `tsconfig.json` (for server sources in `/src`)
  - `src/...`
  - `client/`
    - `tsconfig.json` (for client sources in `/client/src`)
    - `src/...`

**Comment by runartrollet** [comment]
Any solution to this? I have a very similar project-structure, and `atom-typescript` doesn't seem to pick up the `tsconfig.json`. For now, I solved it with putting a symbolic link to the `tsconfig.json`-file into my `src`-folder. Here is my folder-structure. If any more information is needed, I will gladly provide them.

- tsconfig.json
- src/
     - app.ts

**Comment by PierreGUI** [comment]
Wouldn't it be simpler to just be able to give the plugin a path to config file (something like `configFileName`)?
I had to create a symlink to my `tsconfig.json` otherwise atom couldn't find it, as it's located in a subfolder of my project's root.

Providing such path from the package's settings in Atom would be a great way of solving this issue.

**Comment by guncha** [comment]
And if you're working on multiple projects that need this feature, would you go to the package's settings every time you switch between them? That does not seem sustainable.

It's almost like we need a way for each project to tell the plugin where to find the `tsconfig.json` file. Perhaps another configuration file in an easy to find location - at the project root? But then, why not just put `tsconfig.json` there in the first place? 😄

**Comment by PierreGUI** [comment]
Indeed it's a fair point. Guess there's no easy solution for this one, then 🤔

**Comment by guncha** [comment]
👍 on the per-project configuration in Atom.
